TI-OpenThread: thermostat.c File Reference
CC26X2R1_LAUNCHXL/thread/thermostat/thermostat.c File Reference
#include <openthread/config.h>
#include <openthread-core-config.h>
#include <stddef.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <openthread/coap.h>
#include <openthread/link.h>
#include <openthread/platform/uart.h>
#include <openthread/thread.h>
#include <ti/display/Display.h>
#include <ti/display/DisplayExt.h>
#include <ti/grlib/grlib.h>
#include <sched.h>
#include <pthread.h>
#include <mqueue.h>
#include <ti/drivers/GPIO.h>
#include "otsupport/otrtosapi.h"
#include "otsupport/otinstance.h"
#include "ti_drivers_config.h"
#include "graphicext.h"
#include "images.h"
#include "thermostat.h"
#include "utils/code_utils.h"
#include "tiop_ui.h"
#include "disp_utils.h"
#include "otstack.h"
#include "task_config.h"
#include "tiop_config.h"
Macros
#define ATTR_COUNT 2
#define ATTR_READ 0x01
#define ATTR_REPORT 0x04
#define ATTR_WRITE 0x02
#define FRAME_PERIOD 230
#define TEMP_MAX_CHARS 3
#define THERMOSTAT_PROC_QUEUE_MAX_MSG (9)
Size of the message queue for Thermostat_procQueue
Enumerations
enum Thermostat_mode {
Thermostat_modeCooling, Thermostat_modeHeating, Thermostat_modeCooling, Thermostat_modeHeating,
Thermostat_modeCooling, Thermostat_modeHeating, Thermostat_modeCooling, Thermostat_modeHeating,
Thermostat_modeCooling, Thermostat_modeHeating, Thermostat_modeCooling, Thermostat_modeHeating
}
Functions
static void coapHandleSetPt (void *aContext, otMessage *aMessage, const otMessageInfo *aMessageInfo)
Callback function registered with the Coap server. Processes the coap request from the clients.
static void coapHandleTemp (void *aContext, otMessage *aMessage, const otMessageInfo *aMessageInfo)
Callback function registered with the Coap server. Processes the coap request from the clients.
static void flushLcd (void)
Display's the image on the LCD screen.
static uint32_t getCharOffset (uint8_t character, int charOffset)
Calculates the offset for the font sprite buffers based on a char.
void GraphicExt_requestProcess ()
Request processing of event.
void otPlatUartReceived (const uint8_t *aBuf, uint16_t aBufLength)
void otPlatUartSendDone (void)
static void processEvent (Thermostat_evt event)
Processes the events.
void processKeyChangeCB (Button_Handle _buttonHandle, Button_EventMask _buttonEvents)
Handles the key press events.
static void processOtStackEvents (uint8_t event, void *aContext)
Processes the OT stack events.
static otError setupCoapServer (otInstance *aInstance, const attrDesc_t *attr)
sets up the application coap server.
void Thermostat_postEvt (Thermostat_evt event)
Posts an event to the Thermostat task.
void * Thermostat_task (void *arg0)
void Thermostat_taskCreate (void)
static void updateSetPtLcd (char *temperatureStr)
update the setpoint font buffers on the setpoint digit sprites.
static void updateTemperatureLcd (char *temperatureStr)
update the temperature font buffers on the temperature digit sprites.
static void updateThermostatMode (void)
update the mode of the thermostat by comparing the setpoint and temp.
Variables
static attrDesc_t coapAttrs [ATTR_COUNT]
static otCoapResource coapResourceSetPt
static otCoapResource coapResourceTemp
static Button_Handle rightButtonHandle
static bool serverSetup
static int setPoint = 34
static char stack [TASK_CONFIG_THERMOSTAT_TASK_STACK_SIZE]
static char statusBuf [MAX_STATUS_LINE_VALUE_LEN]
static int temperature = 68
static mqd_t Thermostat_procQueueDesc
const char Thermostat_procQueueName [] = "th_process"
static Thermostat_mode thermostatMode = Thermostat_modeCooling
static char thermostatSetPt [TEMP_MAX_CHARS] = "34"
static char thermostatTemp [TEMP_MAX_CHARS] = "68"
const uint8_t zeroCharOffset = '0'
Macro Definition Documentation
ATTR_READ
#define ATTR_READ 0x01
Referenced by setupCoapServer().
ATTR_WRITE
#define ATTR_WRITE 0x02
Referenced by setupCoapServer().
ATTR_REPORT
#define ATTR_REPORT 0x04
ATTR_COUNT
#define ATTR_COUNT 2
FRAME_PERIOD
#define FRAME_PERIOD 230
Referenced by Thermostat_task().
TEMP_MAX_CHARS
#define TEMP_MAX_CHARS 3
Referenced by coapHandleSetPt(), and coapHandleTemp().
THERMOSTAT_PROC_QUEUE_MAX_MSG
#define THERMOSTAT_PROC_QUEUE_MAX_MSG (9)
Size of the message queue for Thermostat_procQueue
There are 8/11 events that can be raised, it is unlikely that they will all be raised at the same time. Add one buffer queue element.
Referenced by Thermostat_task().
Enumeration Type Documentation
Thermostat_mode
enum Thermostat_mode
Thermostat Modes.
Enumerator
Thermostat_modeCooling
Thermostat_modeHeating
Thermostat_modeCooling
Thermostat_modeHeating
Thermostat_modeCooling
Thermostat_modeHeating
Thermostat_modeCooling
Thermostat_modeHeating
Thermostat_modeCooling
Thermostat_modeHeating
Thermostat_modeCooling
Thermostat_modeHeating
Function Documentation
Thermostat_task()
void* Thermostat_task (void * arg0)
Thermostat processing thread.
References CUI_COLOR_CYAN, CUI_COLOR_RED, CUI_COLOR_RESET, CUI_COLOR_WHITE, DISPUTILS_LCDPRINTF, DispUtils_open(), DISPUTILS_SERIALPRINTF, extAddress, FRAME_PERIOD, GraphicExt_initAnimationModule(), OtInstance_get(), OtRtosApi_lock(), OtRtosApi_unlock(), OtStack_registerCallback(), OtStack_setupInterfaceAndNetwork(), OtStack_taskCreate(), processEvent(), processOtStackEvents(), rightButtonHandle, statusBuf, THERMOSTAT_PROC_QUEUE_MAX_MSG, Thermostat_procQueueDesc, Thermostat_procQueueName, thermostatSetPt, thermostatTemp, and tiopCUIInit().
Referenced by Thermostat_taskCreate().
getCharOffset()
static uint32_t getCharOffset (uint8_t character, int charOffset) static
Calculates the offset for the font sprite buffers based on a char.
Parameters
character character to map to font, any char from '0' to '9'.
charOffset offset for the font buffer.
Returns
None
References zeroCharOffset.
Referenced by updateSetPtLcd(), and updateTemperatureLcd().
updateTemperatureLcd()
static void updateTemperatureLcd (char * temperatureStr) static
update the temperature font buffers on the temperature digit sprites.
Parameters
temperatureStr current temperature in string form.
Returns
None
References getCharOffset(), GraphicExt_sprite_t::image, TEMP_FONT_OFFSET, thermostatSpriteList, and thermostatTempFontPix.
Referenced by processEvent().
updateSetPtLcd()
static void updateSetPtLcd (char * temperatureStr) static
update the setpoint font buffers on the setpoint digit sprites.
Parameters
temperatureStr current setpoint in string form.
Returns
None
References getCharOffset(), GraphicExt_sprite_t::image, SETPT_FONT_OFFSET, thermostatSetPtFontPix, and thermostatSpriteList.
Referenced by processEvent().
updateThermostatMode()
static void updateThermostatMode (void) static
update the mode of the thermostat by comparing the setpoint and temp.
Returns
None
References COOL_ANIMATION_END, GraphicExt_animateBackground(), HEAT_ANIMATION_END, GraphicExt_sprite_t::image, MODE_ICON_OFFSET, setPoint, temperature, Thermostat_modeCooling, Thermostat_modeHeating, thermostatBackgroundImage, thermostatMode, thermostatModePix, and thermostatSpriteList.
Referenced by processEvent().
coapHandleSetPt()
static void coapHandleSetPt (void * aContext, otMessage * aMessage, const otMessageInfo * aMessageInfo) static
Callback function registered with the Coap server. Processes the coap request from the clients.
Parameters
aContext A pointer to the context information.
aMessage A pointer to the message.
aMessageInfo A pointer to the message info.
Returns
None
References TEMP_MAX_CHARS, Thermostat_evtSetPtChange, Thermostat_postEvt(), and thermostatSetPt.
Referenced by processEvent().
coapHandleTemp()
static void coapHandleTemp (void * aContext, otMessage * aMessage, const otMessageInfo * aMessageInfo) static
Callback function registered with the Coap server. Processes the coap request from the clients.
Parameters
aContext A pointer to the context information.
aMessage A pointer to the message.
aMessageInfo A pointer to the message info.
Returns
None
References TEMP_MAX_CHARS, Thermostat_evtTempChange, Thermostat_postEvt(), and thermostatTemp.
Referenced by processEvent().
setupCoapServer()
static otError setupCoapServer (otInstance * aInstance, const attrDesc_t * attr) static
sets up the application coap server.
Parameters
aInstance A pointer to the context information.
attr Attribute data
Returns
OT_ERROR_NONE if successful, else error code
References ATTR_READ, ATTR_WRITE, OtRtosApi_lock(), and OtRtosApi_unlock().
Referenced by processEvent().
flushLcd()
static void flushLcd (void) static
Display's the image on the LCD screen.
Returns
None
References GraphicExt_drawSprites(), SPRITE_COUNT, and thermostatSpriteList.
Referenced by processEvent().
processKeyChangeCB()
void processKeyChangeCB (Button_Handle _buttonHandle, Button_EventMask _buttonEvents)
Handles the key press events.
Handles the key pressed events for examples.
Parameters
_buttonHandle identifies which keys were pressed
_buttonEvents identifies the event that occurred on the key
Returns
None
References rightButtonHandle, Thermostat_evtKeyRight, and Thermostat_postEvt().
processOtStackEvents()
static void processOtStackEvents (uint8_t event, void * aContext) static
Processes the OT stack events.
Parameters
event event identifier
aContext context pointer for the event
Returns
None
References OT_STACK_EVENT_DEV_ROLE_CHANGED, OT_STACK_EVENT_NWK_DATA_CHANGED, OT_STACK_EVENT_NWK_JOINED, OT_STACK_EVENT_NWK_JOINED_FAILURE, Thermostat_evtDevRoleChanged, Thermostat_evtNwkJoined, Thermostat_evtNwkJoinFailure, Thermostat_evtNwkSetup, and Thermostat_postEvt().
Referenced by Thermostat_task().
processEvent()
static void processEvent (Thermostat_evt event) static
Processes the events.
Returns
None
References coapAttrs, coapHandleSetPt(), coapHandleTemp(), COOL_ANIMATION_END, CUI_COLOR_RED, CUI_COLOR_RESET, CUI_COLOR_WHITE, CUI_conn_join_fail, CUI_conn_joined, CUI_conn_joining, CUI_processMenuUpdate(), DISPUTILS_LCDPRINTF, DISPUTILS_SERIALPRINTF, flushLcd(), GraphicExt_animateBackground(), GraphicExt_processEvt(), OT_STACK_EVENT_NWK_JOIN_IN_PROGRESS, OtInstance_get(), OtRtosApi_lock(), OtRtosApi_unlock(), OtStack_joinConfiguredNetwork(), OtStack_joinState(), OtStack_setupInterfaceAndNetwork(), OtStack_setupNetwork(), serverSetup, setPoint, setupCoapServer(), statusBuf, temperature, Thermostat_evtDevRoleChanged, Thermostat_evtGraphicExt, Thermostat_evtKeyRight, Thermostat_evtNwkJoined, Thermostat_evtNwkJoinFailure, Thermostat_evtNwkSetup, Thermostat_evtSetPtChange, Thermostat_evtTempChange, thermostatBackgroundImage, thermostatSetPt, thermostatTemp, tiopCUIUpdateApp(), tiopCUIUpdateChannel(), tiopCUIUpdateConnStatus(), tiopCUIUpdateExtPANID(), tiopCUIUpdateMasterkey(), tiopCUIUpdateNwkName(), tiopCUIUpdatePANID(), tiopCUIUpdateRole(), tiopCUIUpdateShortAddr(), updateSetPtLcd(), updateTemperatureLcd(), and updateThermostatMode().
Referenced by Thermostat_task().
otPlatUartReceived()
void otPlatUartReceived (const uint8_t * aBuf, uint16_t aBufLength)
Documented in openthread/platform/uart.h.
otPlatUartSendDone()
void otPlatUartSendDone (void)
Documented in openthread/platform/uart.h.
Thermostat_postEvt()
void Thermostat_postEvt (Thermostat_evt event)
Posts an event to the Thermostat task.
Parameters
event event to post.
Returns
None
References Thermostat_procQueueDesc.
Referenced by coapHandleSetPt(), coapHandleTemp(), GraphicExt_requestProcess(), processKeyChangeCB(), and processOtStackEvents().
GraphicExt_requestProcess()
void GraphicExt_requestProcess (void)
Request processing of event.
Used to indicate to the application that GraphicExt_processEvt should be called. This is usually called when the frame draw timeout expires.
References CUI_cursorInfo_t::col, CUI_INPUT_DOWN, CUI_INPUT_EXECUTE, CUI_INPUT_LEFT, CUI_INPUT_RIGHT, CUI_INPUT_UP, CUI_IS_INPUT_NUM, CUI_ITEM_INTERCEPT_START, CUI_ITEM_INTERCEPT_STOP, CUI_ITEM_PREVIEW, MAX_MENU_LINE_LEN, OtInstance_get(), OtRtosApi_lock(), OtRtosApi_unlock(), processMenuUpdateFn(), CUI_cursorInfo_t::row, setPoint, Thermostat_evtGraphicExt, Thermostat_evtSetPtChange, Thermostat_postEvt(), thermostat_setPoint(), thermostatSetPt, tiopCUINwkReset(), tiopCUIReset(), uiActionAttach(), and uiActionJoin().
Thermostat_taskCreate()
void Thermostat_taskCreate (void)
Documented in task_config.h.
References stack, TASK_CONFIG_THERMOSTAT_TASK_PRIORITY, TASK_CONFIG_THERMOSTAT_TASK_STACK_SIZE, and Thermostat_task().
Variable Documentation
zeroCharOffset
const uint8_t zeroCharOffset = '0'
Referenced by getCharOffset().
Thermostat_procQueueName
const char Thermostat_procQueueName[] = "th_process"
Referenced by Thermostat_task().
Thermostat_procQueueDesc
mqd_t Thermostat_procQueueDesc static
Referenced by Thermostat_postEvt(), and Thermostat_task().
stack
char stack[TASK_CONFIG_THERMOSTAT_TASK_STACK_SIZE] static
Referenced by Thermostat_taskCreate().
coapResourceTemp
otCoapResource coapResourceTemp static
coapResourceSetPt
otCoapResource coapResourceSetPt static
thermostatTemp
char thermostatTemp[TEMP_MAX_CHARS] = "68" static
Referenced by coapHandleTemp(), processEvent(), and Thermostat_task().
temperature
int temperature = 68 static
Referenced by processEvent(), and updateThermostatMode().
thermostatSetPt
char thermostatSetPt[TEMP_MAX_CHARS] = "34" static
Referenced by coapHandleSetPt(), GraphicExt_requestProcess(), processEvent(), and Thermostat_task().
setPoint
int setPoint = 34 static
Referenced by GraphicExt_requestProcess(), processEvent(), and updateThermostatMode().
thermostatMode
Thermostat_mode thermostatMode = Thermostat_modeCooling static
Referenced by updateThermostatMode().
coapAttrs
attrDesc_t coapAttrs[ATTR_COUNT] static
Initial value:
= {
{
    .uriPath = THERMOSTAT_TEMP_URI,
    .type = (ATTR_READ|ATTR_WRITE),
    .pValue = thermostatTemp,
    .pAttrCoapResource = &coapResourceTemp
},
{
    .uriPath = THERMOSTAT_SET_PT_URI,
    .type = (ATTR_READ|ATTR_WRITE),
    .pValue = thermostatSetPt,
    .pAttrCoapResource = &coapResourceSetPt
}
}
Referenced by processEvent().
rightButtonHandle
Button_Handle rightButtonHandle static
Referenced by processKeyChangeCB(), and Thermostat_task().
serverSetup
bool serverSetup static
Referenced by processEvent().
statusBuf
char statusBuf[MAX_STATUS_LINE_VALUE_LEN] static
Referenced by processEvent(), and Thermostat_task().
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale