TI-OpenThread: system.c File Reference
CC2652RB_LAUNCHXL/thread/cli_ftd/platform/system.c File Reference
Detailed Description
This file includes the platform-specific initializers.
#include <openthread/config.h>
#include "system.h"
#include <stdio.h>
Functions
void otSysInit (int argc, char *argv[])
Function Documentation
otSysInit()
void otSysInit (int argc, char * argv[])
Function documented in system.h
References platformAlarmInit(), platformAlarmMicroInit(), platformDebugUartInit(), platformRadioInit(), and platformRandomInit().
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale