TI-OpenThread: tiop_ui.c File Reference
CC1352R1_LAUNCHXL/thread/door_lock/tiop_ui.c File Reference
#include "tiop_ui.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include "tiop_config.h"
#include "otsupport/otinstance.h"
#include "otsupport/otrtosapi.h"
#include <openthread/thread.h>
#include "ti_drivers_config.h"
#include "tiop_app_defs.h"
Functions
CUI_SUB_MENU_END CUI_SUB_MENU_END CUI_APP_MENU CUI_SUB_MENU_END CUI_MAIN_MENU_END void tiopCUIInit (char *appString, Button_Handle *rightButtonHandle)
Initialize example CUI functionality.
void tiopCUIUpdateApp (char *appInfo)
Update Application specific CUI output line.
void tiopCUIUpdateChannel (uint8_t ch)
Update channel CUI output.
void tiopCUIUpdateConnStatus (cuiConn status)
Update connection status CUI output line.
void tiopCUIUpdateDeviceInfo (void)
Update device info CUI output line.
void tiopCUIUpdateExtPANID (otExtendedPanId extPan)
Update Extended panid CUI output.
void tiopCUIUpdateMasterkey (otMasterKey key)
Update masterkey CUI output.
void tiopCUIUpdateNwkName (const char *name)
Update network name CUI output.
void tiopCUIUpdatePANID (otPanId pan)
Update panid CUI output.
void tiopCUIUpdateRole (otDeviceRole role)
Update device role CUI output line.
void tiopCUIUpdateShortAddr (otShortAddress s)
Update short address CUI output.
void uiActionProcessConfigureChannel (const char _input, char *_pLines[3], CUI_cursorInfo_t *_pCurInfo)
Handle reading user input into the channel configuration in CUI.
void uiActionProcessConfigurePanId (const char _input, char *_pLines[3], CUI_cursorInfo_t *_pCurInfo)
Handle reading user input into the panid configuration in CUI.
Variables
static uint32_t appInfoLine
static CUI_clientHandle_t clientHandle
static uint32_t connStatusLine
static uint32_t deviceInfoLine
static uint32_t deviceRoleLine
static uint8_t display_channel
static otExtAddress extAddress
static otExtendedPanId extPanId
static LED_Handle greenLedHandle
static otMasterKey masterkey
static uint32_t nwkInfoLine1
static uint32_t nwkInfoLine2
static uint32_t nwkInfoLine3
static const char * nwkName
static otPanId panid
static LED_Handle redLedHandle
static otShortAddress shortAddr
Function Documentation
tiopCUIInit()
CUI_SUB_MENU_END CUI_SUB_MENU_END CUI_APP_MENU CUI_SUB_MENU_END CUI_MAIN_MENU_END void tiopCUIInit (char * appString, Button_Handle * rightButtonHandle)
Initialize example CUI functionality.
documented in tiop_ui.h
References appInfoLine, clientHandle, CUI_clientParams_t::clientName, connStatusLine, CUI_clientOpen(), CUI_clientParamsInit(), CUI_conn_disabled, CUI_init(), CUI_paramsInit(), CUI_registerMenu(), CUI_statusLineResourceRequest(), deviceInfoLine, deviceRoleLine, display_channel, extAddress, extPanId, greenLedHandle, CUI_params_t::manageUart, masterkey, MAX_CLIENT_NAME_LEN, CUI_clientParams_t::maxStatusLines, nwkInfoLine1, nwkInfoLine2, nwkInfoLine3, nwkName, OtInstance_get(), OtRtosApi_lock(), OtRtosApi_unlock(), panid, processKeyChangeCB(), redLedHandle, shortAddr, tiopCUIUpdateApp(), tiopCUIUpdateConnStatus(), tiopCUIUpdateDeviceInfo(), tiopCUIUpdateMasterkey(), tiopCUIUpdateNwkName(), tiopCUIUpdatePANID(), and tiopCUIUpdateRole().
tiopCUIUpdateDeviceInfo()
void tiopCUIUpdateDeviceInfo (void)
Update device info CUI output line.
documented in tiop_ui.h
References clientHandle, CUI_COLOR_MAGENTA, CUI_COLOR_RED, CUI_COLOR_RESET, CUI_statusLinePrintf(), deviceInfoLine, and extAddress.
Referenced by tiopCUIInit().
tiopCUIUpdateNwkName()
void tiopCUIUpdateNwkName (const char * name)
Update network name CUI output.
documented in tiop_ui.h
References clientHandle, CUI_COLOR_MAGENTA, CUI_COLOR_RESET, CUI_statusLinePrintf(), extPanId, nwkInfoLine1, and nwkName.
Referenced by tiopCUIInit().
tiopCUIUpdateExtPANID()
void tiopCUIUpdateExtPANID (otExtendedPanId extPan)
Update Extended panid CUI output.
documented in tiop_ui.h
References clientHandle, CUI_COLOR_MAGENTA, CUI_COLOR_RESET, CUI_statusLinePrintf(), extPanId, nwkInfoLine1, and nwkName.
tiopCUIUpdateMasterkey()
void tiopCUIUpdateMasterkey (otMasterKey key)
Update masterkey CUI output.
documented in tiop_ui.h
References clientHandle, CUI_COLOR_MAGENTA, CUI_COLOR_RESET, CUI_statusLinePrintf(), masterkey, and nwkInfoLine2.
Referenced by tiopCUIInit().
tiopCUIUpdatePANID()
void tiopCUIUpdatePANID (otPanId pan)
Update panid CUI output.
documented in tiop_ui.h
References clientHandle, CUI_COLOR_RESET, CUI_COLOR_YELLOW, CUI_statusLinePrintf(), display_channel, nwkInfoLine3, panid, and shortAddr.
Referenced by tiopCUIInit(), and uiActionProcessConfigurePanId().
tiopCUIUpdateChannel()
void tiopCUIUpdateChannel (uint8_t ch)
Update channel CUI output.
documented in tiop_ui.h
References clientHandle, CUI_COLOR_RESET, CUI_COLOR_YELLOW, CUI_statusLinePrintf(), display_channel, nwkInfoLine3, panid, and shortAddr.
Referenced by uiActionProcessConfigureChannel().
tiopCUIUpdateShortAddr()
void tiopCUIUpdateShortAddr (otShortAddress s)
Update short address CUI output.
documented in tiop_ui.h
References clientHandle, CUI_COLOR_RESET, CUI_COLOR_YELLOW, CUI_statusLinePrintf(), display_channel, nwkInfoLine3, panid, and shortAddr.
tiopCUIUpdateRole()
void tiopCUIUpdateRole (otDeviceRole role)
Update device role CUI output line.
documented in tiop_ui.h
References clientHandle, CUI_COLOR_RED, CUI_COLOR_RESET, CUI_statusLinePrintf(), deviceRoleLine, greenLedHandle, and redLedHandle.
Referenced by tiopCUIInit().
tiopCUIUpdateConnStatus()
void tiopCUIUpdateConnStatus (cuiConn status)
Update connection status CUI output line.
documented in tiop_ui.h
References clientHandle, connStatusLine, CUI_COLOR_RED, CUI_COLOR_RESET, CUI_conn_disabled, CUI_conn_join_fail, CUI_conn_joined, CUI_conn_joining, and CUI_statusLinePrintf().
Referenced by tiopCUIInit().
tiopCUIUpdateApp()
void tiopCUIUpdateApp (char * appInfo)
Update Application specific CUI output line.
documented in tiop_ui.h
References appInfoLine, clientHandle, and CUI_statusLinePrintf().
Referenced by tiopCUIInit().
uiActionProcessConfigurePanId()
void uiActionProcessConfigurePanId (const char _input, char * _pLines[3], CUI_cursorInfo_t * _pCurInfo)
Handle reading user input into the panid configuration in CUI.
documented in tiop_ui.h
References CUI_cursorInfo_t::col, CUI_INPUT_DOWN, CUI_INPUT_EXECUTE, CUI_INPUT_LEFT, CUI_INPUT_RIGHT, CUI_INPUT_UP, CUI_IS_INPUT_HEX, CUI_ITEM_INTERCEPT_START, CUI_ITEM_INTERCEPT_STOP, CUI_ITEM_PREVIEW, OtInstance_get(), OtRtosApi_lock(), OtRtosApi_unlock(), CUI_cursorInfo_t::row, and tiopCUIUpdatePANID().
uiActionProcessConfigureChannel()
void uiActionProcessConfigureChannel (const char _input, char * _pLines[3], CUI_cursorInfo_t * _pCurInfo)
Handle reading user input into the channel configuration in CUI.
documented in tiop_ui.h
References CUI_cursorInfo_t::col, CUI_INPUT_DOWN, CUI_INPUT_EXECUTE, CUI_INPUT_LEFT, CUI_INPUT_RIGHT, CUI_INPUT_UP, CUI_IS_INPUT_NUM, CUI_ITEM_INTERCEPT_START, CUI_ITEM_INTERCEPT_STOP, CUI_ITEM_PREVIEW, display_channel, OtInstance_get(), OtRtosApi_lock(), OtRtosApi_unlock(), CUI_cursorInfo_t::row, and tiopCUIUpdateChannel().
Variable Documentation
redLedHandle
LED_Handle redLedHandle static
Referenced by tiopCUIInit(), and tiopCUIUpdateRole().
greenLedHandle
LED_Handle greenLedHandle static
Referenced by tiopCUIInit(), and tiopCUIUpdateRole().
clientHandle
CUI_clientHandle_t clientHandle static
Referenced by tiopCUIInit(), tiopCUIUpdateApp(), tiopCUIUpdateChannel(), tiopCUIUpdateConnStatus(), tiopCUIUpdateDeviceInfo(), tiopCUIUpdateExtPANID(), tiopCUIUpdateMasterkey(), tiopCUIUpdateNwkName(), tiopCUIUpdatePANID(), tiopCUIUpdateRole(), and tiopCUIUpdateShortAddr().
deviceInfoLine
uint32_t deviceInfoLine static
Referenced by tiopCUIInit(), and tiopCUIUpdateDeviceInfo().
nwkInfoLine1
uint32_t nwkInfoLine1 static
Referenced by tiopCUIInit(), tiopCUIUpdateExtPANID(), and tiopCUIUpdateNwkName().
nwkInfoLine2
uint32_t nwkInfoLine2 static
Referenced by tiopCUIInit(), and tiopCUIUpdateMasterkey().
nwkInfoLine3
uint32_t nwkInfoLine3 static
Referenced by tiopCUIInit(), tiopCUIUpdateChannel(), tiopCUIUpdatePANID(), and tiopCUIUpdateShortAddr().
deviceRoleLine
uint32_t deviceRoleLine static
Referenced by tiopCUIInit(), and tiopCUIUpdateRole().
connStatusLine
uint32_t connStatusLine static
Referenced by tiopCUIInit(), and tiopCUIUpdateConnStatus().
appInfoLine
uint32_t appInfoLine static
Referenced by tiopCUIInit(), and tiopCUIUpdateApp().
panid
otPanId panid static
Referenced by tiopCUIInit(), tiopCUIUpdateChannel(), tiopCUIUpdatePANID(), and tiopCUIUpdateShortAddr().
display_channel
uint8_t display_channel static
Referenced by tiopCUIInit(), tiopCUIUpdateChannel(), tiopCUIUpdatePANID(), tiopCUIUpdateShortAddr(), and uiActionProcessConfigureChannel().
shortAddr
otShortAddress shortAddr static
Referenced by tiopCUIInit(), tiopCUIUpdateChannel(), tiopCUIUpdatePANID(), and tiopCUIUpdateShortAddr().
extAddress
otExtAddress extAddress static
Referenced by tiopCUIInit(), and tiopCUIUpdateDeviceInfo().
extPanId
otExtendedPanId extPanId static
Referenced by tiopCUIInit(), tiopCUIUpdateExtPANID(), and tiopCUIUpdateNwkName().
masterkey
otMasterKey masterkey static
Referenced by tiopCUIInit(), and tiopCUIUpdateMasterkey().
nwkName
const char* nwkName static
Referenced by tiopCUIInit(), tiopCUIUpdateExtPANID(), and tiopCUIUpdateNwkName().
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale