TI-OpenThread: cli.c File Reference
CC26X2R1_LAUNCHXL/thread/cli_ftd/cli.c File Reference
#include <openthread/config.h>
#include <openthread-core-config.h>
#include <assert.h>
#include <stddef.h>
#include <sched.h>
#include <pthread.h>
#include <unistd.h>
#include <ti/drivers/GPIO.h>
#include <openthread/cli.h>
#include <openthread/instance.h>
#include "otsupport/otrtosapi.h"
#include "otsupport/otinstance.h"
#include "task_config.h"
#include "ti_drivers_config.h"
Functions
void * cli_task (void *arg0)
Invalidate the OAD IMAGE HEADER.
void cli_taskCreate (void)
void otPlatLog (otLogLevel aLogLevel, otLogRegion aLogRegion, const char *aFormat,...)
Variables
static char cli_stack [TASK_CONFIG_CLI_TASK_STACK_SIZE]
Function Documentation
cli_task()
void* cli_task (void * arg0)
Invalidate the OAD IMAGE HEADER.
This provides a way to revert to factory image by invalidating the existing stack/application image and doing a system reset. On boot, the BIM on finding the internal invalidated image will restore to factory image.
Returns
None Main thread starting the CLI example within OpenThread.
References OtInstance_get(), OtRtosApi_lock(), OtRtosApi_unlock(), and OtStack_taskCreate().
Referenced by cli_taskCreate().
cli_taskCreate()
void cli_taskCreate (void)
Documented in task_config.h.
References cli_stack, cli_task(), img_header_single_app::h, img_common_header::imgID, oad_image_header, TASK_CONFIG_CLI_TASK_PRIORITY, and TASK_CONFIG_CLI_TASK_STACK_SIZE.
otPlatLog()
void otPlatLog (otLogLevel aLogLevel, otLogRegion aLogRegion, const char * aFormat, ...)
Variable Documentation
cli_stack
char cli_stack[TASK_CONFIG_CLI_TASK_STACK_SIZE] static
Referenced by cli_taskCreate().
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale