TI-OpenThread: cui.c File Reference
CC2652RB_LAUNCHXL/thread/empty_ftd/cui.c File Reference
#include <stdbool.h>
#include <string.h>
#include <stdio.h>
#include <ti/sysbios/BIOS.h>
#include <ti/sysbios/knl/Semaphore.h>
#include <ti/sysbios/knl/Task.h>
#include <ti/sysbios/knl/Clock.h>
#include <ti/drivers/dpl/HwiP.h>
#include <ti/drivers/UART.h>
#include <ti/drivers/uart/UARTCC26XX.h>
#include <ti/drivers/utils/Random.h>
#include <ti/drivers/apps/LED.h>
#include <xdc/runtime/System.h>
#include <DeviceFamily_constructPath(driverlib/cpu.h)>
#include "ti_drivers_config.h"
#include "cui.h"
Macros
#define CUI_END_CHAR 0x03
#define CUI_ESC_CLR "\033[2J"
#define CUI_ESC_CLR_STAT_LINE_VAL "\033[2K"
#define CUI_ESC_CLR_UP "\033[1J"
#define CUI_ESC_CUR_HIDE "\033[?25l"
#define CUI_ESC_CUR_HOME "\033[H"
#define CUI_ESC_CUR_LINE "\033[%d;0H"
#define CUI_ESC_CUR_MENU_BTM "\033[3;%dH"
#define CUI_ESC_CUR_ROW_COL "\033[%d;%dH"
#define CUI_ESC_CUR_SHOW "\033[?25h"
#define CUI_ESC_DOWN "\033[B"
#define CUI_ESC_ESC "\033\0\0\0\0"
#define CUI_ESC_LEFT "\033[D"
#define CUI_ESC_RIGHT "\033[C"
#define CUI_ESC_TRM_MODE "\033[20"
#define CUI_ESC_UP "\033[A"
#define CUI_ETX_LEN 1
#define CUI_INITIAL_STATUS_OFFSET 5
#define CUI_LABEL_VAL_SEP ": "
#define CUI_MAX_LABEL_AND_SEP_LEN (MAX_STATUS_LINE_LABEL_LEN + (sizeof(CUI_LABEL_VAL_SEP)))
#define CUI_MENU_START_CHAR 0x01
#define CUI_MENU_START_ESCAPE_LEN 32
#define CUI_NL_CR "\n\r"
#define CUI_NL_CR_LEN 2
#define CUI_NUM_UART_CHARS 5
#define CUI_STATUS_LINE_START_CHAR 0x02
Enumerations
enum CUI_rscStatus_t {
CUI_RELEASED = 0, CUI_ACQUIRED = 0xDEADBEEF, CUI_RELEASED = 0, CUI_ACQUIRED = 0xDEADBEEF,
CUI_RELEASED = 0, CUI_ACQUIRED = 0xDEADBEEF, CUI_RELEASED = 0, CUI_ACQUIRED = 0xDEADBEEF,
CUI_RELEASED = 0, CUI_ACQUIRED = 0xDEADBEEF, CUI_RELEASED = 0, CUI_ACQUIRED = 0xDEADBEEF,
CUI_RELEASED = 0, CUI_ACQUIRED = 0xDEADBEEF, CUI_RELEASED = 0, CUI_ACQUIRED = 0xDEADBEEF,
CUI_RELEASED = 0, CUI_ACQUIRED = 0xDEADBEEF, CUI_RELEASED = 0, CUI_ACQUIRED = 0xDEADBEEF,
CUI_RELEASED = 0, CUI_ACQUIRED = 0xDEADBEEF, CUI_RELEASED = 0, CUI_ACQUIRED = 0xDEADBEEF,
CUI_RELEASED = 0, CUI_ACQUIRED = 0xDEADBEEF, CUI_RELEASED = 0, CUI_ACQUIRED = 0xDEADBEEF,
CUI_RELEASED = 0, CUI_ACQUIRED = 0xDEADBEEF, CUI_RELEASED = 0, CUI_ACQUIRED = 0xDEADBEEF,
CUI_RELEASED = 0, CUI_ACQUIRED = 0xDEADBEEF, CUI_RELEASED = 0, CUI_ACQUIRED = 0xDEADBEEF,
CUI_RELEASED = 0, CUI_ACQUIRED = 0xDEADBEEF, CUI_RELEASED = 0, CUI_ACQUIRED = 0xDEADBEEF,
CUI_RELEASED = 0, CUI_ACQUIRED = 0xDEADBEEF, CUI_RELEASED = 0, CUI_ACQUIRED = 0xDEADBEEF,
CUI_RELEASED = 0, CUI_ACQUIRED = 0xDEADBEEF, CUI_RELEASED = 0, CUI_ACQUIRED = 0xDEADBEEF,
CUI_RELEASED = 0, CUI_ACQUIRED = 0xDEADBEEF, CUI_RELEASED = 0, CUI_ACQUIRED = 0xDEADBEEF,
CUI_RELEASED = 0, CUI_ACQUIRED = 0xDEADBEEF, CUI_RELEASED = 0, CUI_ACQUIRED = 0xDEADBEEF,
CUI_RELEASED = 0, CUI_ACQUIRED = 0xDEADBEEF, CUI_RELEASED = 0, CUI_ACQUIRED = 0xDEADBEEF,
CUI_RELEASED = 0, CUI_ACQUIRED = 0xDEADBEEF, CUI_RELEASED = 0, CUI_ACQUIRED = 0xDEADBEEF,
CUI_RELEASED = 0, CUI_ACQUIRED = 0xDEADBEEF, CUI_RELEASED = 0, CUI_ACQUIRED = 0xDEADBEEF,
CUI_RELEASED = 0, CUI_ACQUIRED = 0xDEADBEEF, CUI_RELEASED = 0, CUI_ACQUIRED = 0xDEADBEEF
}
Functions
static CUI_retVal_t CUI_acquireStatusLine (const CUI_clientHandle_t _clientHandle, const char *_pLabel, const bool _refreshInd, uint32_t *_pLineId)
static CUI_retVal_t CUI_acquireStatusLine (const CUI_clientHandle_t _clientHandle, const char _pLabel[MAX_STATUS_LINE_LABEL_LEN], const bool _refreshInd, uint32_t *_pLineId)
void CUI_assert (const char *_assertMsg, const bool _spinLock)
static void CUI_callMenuUartUpdateFn ()
CUI_clientHandle_t CUI_clientOpen (CUI_clientParams_t *_pParams)
void CUI_clientParamsInit (CUI_clientParams_t *_pClientParams)
CUI_retVal_t CUI_close ()
CUI_retVal_t CUI_deRegisterMenu (const CUI_clientHandle_t _clientHandle, CUI_menu_t *_pMenu)
static void CUI_dispMenu (bool _menuPopulated)
static CUI_retVal_t CUI_findMenu (CUI_menu_t *_pMenu, CUI_menu_t *_pDesiredMenu, uint32_t *_pPrevItemIndex)
static int CUI_getClientIndex (const CUI_clientHandle_t _clientHandle)
static bool CUI_handleMenuIntercept (CUI_menuItem_t *_pItemEntry, uint8_t _input)
static bool CUI_handleMenuList (CUI_menuItem_t *_pItemEntry, uint8_t _input)
CUI_retVal_t CUI_init (CUI_params_t *_pParams)
void CUI_menuActionBack (const int32_t _itemEntry)
static void CUI_menuActionExecute (void)
void CUI_menuActionHelp (char _input, char *_lines[3], CUI_cursorInfo_t *_curInfo)
static void CUI_menuActionNavigate (uint8_t _navDir)
CUI_retVal_t CUI_menuNav (const CUI_clientHandle_t _clientHandle, CUI_menu_t *_pMenu, const uint32_t _itemIndex)
void CUI_paramsInit (CUI_params_t *_pParams)
CUI_retVal_t CUI_processMenuUpdate (void)
static CUI_retVal_t CUI_publicAPIChecks (const CUI_clientHandle_t _clientHandle)
CUI_retVal_t CUI_registerMenu (const CUI_clientHandle_t _clientHandle, CUI_menu_t *_pMenu)
CUI_retVal_t CUI_statusLinePrintf (const CUI_clientHandle_t _clientHandle, const uint32_t _lineId, const char *_format,...)
CUI_retVal_t CUI_statusLineResourceRequest (const CUI_clientHandle_t _clientHandle, const char _pLabel[MAX_STATUS_LINE_LABEL_LEN], const bool _refreshInd, uint32_t *_pLineId)
static void CUI_updateCursor (void)
CUI_retVal_t CUI_updateMultiMenuTitle (const char *_pTitle)
static CUI_retVal_t CUI_updateRemLen (size_t *_currRemLen, char *_buff, size_t _buffSize)
static CUI_retVal_t CUI_validateHandle (const CUI_clientHandle_t _clientHandle)
static CUI_retVal_t CUI_writeString (void *_buffer, size_t _size)
static void UartReadCallback (UART_Handle _handle, void *_buf, size_t _size)
static void UartWriteCallback (UART_Handle _handle, void *_buf, size_t _size)
Variables
CUI_menu_t * cuiMultiMenu = (CUI_menu_t *)&cuiMultiMenuData
uint8_t cuiMultiMenuData [sizeof(CUI_menu_t)+((MAX_REGISTERED_MENUS+1) *sizeof(CUI_menuItem_t))]
static CUI_clientHandle_t gClientHandles [MAX_CLIENTS]
static Semaphore_Handle gClientsSem
static Semaphore_Struct gClientsSemStruct
static size_t gCurrMenuItemEntry = 0
static bool gCursorActive
static CUI_cursorInfo_t gCursorInfo
static uint32_t gMaxStatusLines [MAX_CLIENTS]
static CUI_menuResource_t gMenuResources [MAX_REGISTERED_MENUS]
static Semaphore_Handle gMenuSem
static Semaphore_Struct gMenuSemStruct
static bool gModuleInitialized = false
static CUI_menu_t * gpCurrMenu
static CUI_menu_t * gpMainMenu
static char gpMultiMenuTitle [] = " TI DMM Application "
static size_t gPrevMenuItemEntry = 0
static uint8_t gRingBuff [512]
static size_t gRingBuffHeadIdx = 0
static size_t gRingBuffPendLen = 0
static size_t gRingBuffTailIdx = 0
static Semaphore_Params gSemParams
static CUI_statusLineResource_t * gStatusLineResources [MAX_CLIENTS]
static Semaphore_Handle gStatusSem
static Semaphore_Struct gStatusSemStruct
static UART_Handle gUartHandle = NULL
static UART_Params gUartParams
static uint8_t gUartRxBuffer [CUI_NUM_UART_CHARS]
static Semaphore_Handle gUartSem
static Semaphore_Struct gUartSemStruct
static uint8_t gUartTxBuffer [CUI_NUM_UART_CHARS]
char menuBuff [CUI_MENU_START_ESCAPE_LEN+MAX_MENU_LINE_LEN+CUI_NL_CR_LEN+MAX_MENU_LINE_LEN+CUI_NL_CR_LEN+MAX_MENU_LINE_LEN+CUI_ETX_LEN]
Macro Definition Documentation
CUI_INITIAL_STATUS_OFFSET
#define CUI_INITIAL_STATUS_OFFSET 5
Referenced by CUI_assert(), and CUI_statusLinePrintf().
CUI_LABEL_VAL_SEP
#define CUI_LABEL_VAL_SEP ": "
Referenced by CUI_acquireStatusLine().
CUI_MAX_LABEL_AND_SEP_LEN
#define CUI_MAX_LABEL_AND_SEP_LEN (MAX_STATUS_LINE_LABEL_LEN + (sizeof(CUI_LABEL_VAL_SEP)))
Referenced by CUI_statusLinePrintf().
CUI_MENU_START_CHAR
#define CUI_MENU_START_CHAR 0x01
Referenced by CUI_dispMenu().
CUI_STATUS_LINE_START_CHAR
#define CUI_STATUS_LINE_START_CHAR 0x02
Referenced by CUI_assert(), and CUI_statusLinePrintf().
CUI_END_CHAR
#define CUI_END_CHAR 0x03
Referenced by CUI_assert(), CUI_dispMenu(), and CUI_statusLinePrintf().
CUI_NL_CR
#define CUI_NL_CR "\n\r"
Referenced by CUI_dispMenu(), and CUI_statusLinePrintf().
CUI_ESC_UP
#define CUI_ESC_UP "\033[A"
Referenced by CUI_processMenuUpdate().
CUI_ESC_DOWN
#define CUI_ESC_DOWN "\033[B"
Referenced by CUI_processMenuUpdate().
CUI_ESC_RIGHT
#define CUI_ESC_RIGHT "\033[C"
Referenced by CUI_processMenuUpdate().
CUI_ESC_LEFT
#define CUI_ESC_LEFT "\033[D"
Referenced by CUI_processMenuUpdate().
CUI_ESC_ESC
#define CUI_ESC_ESC "\033\0\0\0\0"
Referenced by CUI_processMenuUpdate().
CUI_ESC_TRM_MODE
#define CUI_ESC_TRM_MODE "\033[20"
Referenced by CUI_close(), and CUI_init().
CUI_ESC_CLR
#define CUI_ESC_CLR "\033[2J"
Referenced by CUI_close(), and CUI_init().
CUI_ESC_CLR_UP
#define CUI_ESC_CLR_UP "\033[1J"
Referenced by CUI_deRegisterMenu(), and CUI_dispMenu().
CUI_ESC_CLR_STAT_LINE_VAL
#define CUI_ESC_CLR_STAT_LINE_VAL "\033[2K"
Referenced by CUI_assert(), and CUI_statusLinePrintf().
CUI_ESC_CUR_HIDE
#define CUI_ESC_CUR_HIDE "\033[?25l"
Referenced by CUI_assert(), CUI_close(), CUI_deRegisterMenu(), CUI_dispMenu(), CUI_init(), and CUI_statusLinePrintf().
CUI_ESC_CUR_SHOW
#define CUI_ESC_CUR_SHOW "\033[?25h"
Referenced by CUI_updateCursor().
CUI_ESC_CUR_HOME
#define CUI_ESC_CUR_HOME "\033[H"
Referenced by CUI_assert(), CUI_deRegisterMenu(), CUI_dispMenu(), CUI_statusLinePrintf(), and CUI_updateCursor().
CUI_ESC_CUR_MENU_BTM
#define CUI_ESC_CUR_MENU_BTM "\033[3;%dH"
Referenced by CUI_deRegisterMenu(), and CUI_dispMenu().
CUI_ESC_CUR_LINE
#define CUI_ESC_CUR_LINE "\033[%d;0H"
Referenced by CUI_assert(), and CUI_statusLinePrintf().
CUI_ESC_CUR_ROW_COL
#define CUI_ESC_CUR_ROW_COL "\033[%d;%dH"
Referenced by CUI_updateCursor().
CUI_NUM_UART_CHARS
#define CUI_NUM_UART_CHARS 5
CUI_MENU_START_ESCAPE_LEN
#define CUI_MENU_START_ESCAPE_LEN 32
Referenced by CUI_dispMenu(), CUI_handleMenuIntercept(), and CUI_handleMenuList().
CUI_NL_CR_LEN
#define CUI_NL_CR_LEN 2
Referenced by CUI_dispMenu(), CUI_handleMenuIntercept(), and CUI_handleMenuList().
CUI_ETX_LEN
#define CUI_ETX_LEN 1
Enumeration Type Documentation
CUI_rscStatus_t
enum CUI_rscStatus_t
Enumerator
CUI_RELEASED
CUI_ACQUIRED
CUI_RELEASED
CUI_ACQUIRED
CUI_RELEASED
CUI_ACQUIRED
CUI_RELEASED
CUI_ACQUIRED
CUI_RELEASED
CUI_ACQUIRED
CUI_RELEASED
CUI_ACQUIRED
CUI_RELEASED
CUI_ACQUIRED
CUI_RELEASED
CUI_ACQUIRED
CUI_RELEASED
CUI_ACQUIRED
CUI_RELEASED
CUI_ACQUIRED
CUI_RELEASED
CUI_ACQUIRED
CUI_RELEASED
CUI_ACQUIRED
CUI_RELEASED
CUI_ACQUIRED
CUI_RELEASED
CUI_ACQUIRED
CUI_RELEASED
CUI_ACQUIRED
CUI_RELEASED
CUI_ACQUIRED
CUI_RELEASED
CUI_ACQUIRED
CUI_RELEASED
CUI_ACQUIRED
CUI_RELEASED
CUI_ACQUIRED
CUI_RELEASED
CUI_ACQUIRED
CUI_RELEASED
CUI_ACQUIRED
CUI_RELEASED
CUI_ACQUIRED
CUI_RELEASED
CUI_ACQUIRED
CUI_RELEASED
CUI_ACQUIRED
CUI_RELEASED
CUI_ACQUIRED
CUI_RELEASED
CUI_ACQUIRED
CUI_RELEASED
CUI_ACQUIRED
CUI_RELEASED
CUI_ACQUIRED
CUI_RELEASED
CUI_ACQUIRED
CUI_RELEASED
CUI_ACQUIRED
CUI_RELEASED
CUI_ACQUIRED
CUI_RELEASED
CUI_ACQUIRED
CUI_RELEASED
CUI_ACQUIRED
CUI_RELEASED
CUI_ACQUIRED
CUI_RELEASED
CUI_ACQUIRED
CUI_RELEASED
CUI_ACQUIRED
Function Documentation
CUI_publicAPIChecks()
static CUI_retVal_t CUI_publicAPIChecks (const CUI_clientHandle_t _clientHandle) static
References CUI_MODULE_UNINITIALIZED, CUI_validateHandle(), and gModuleInitialized.
Referenced by CUI_deRegisterMenu(), CUI_menuNav(), CUI_registerMenu(), CUI_statusLinePrintf(), and CUI_statusLineResourceRequest().
CUI_acquireStatusLine() [1/2]
static CUI_retVal_t CUI_acquireStatusLine (const CUI_clientHandle_t _clientHandle, const char * _pLabel, const bool _refreshInd, uint32_t * _pLineId) static
Referenced by CUI_statusLineResourceRequest().
CUI_validateHandle()
static CUI_retVal_t CUI_validateHandle (const CUI_clientHandle_t _clientHandle) static
References CUI_getClientIndex(), CUI_INVALID_CLIENT_HANDLE, and CUI_SUCCESS.
Referenced by CUI_publicAPIChecks().
CUI_getClientIndex()
static int CUI_getClientIndex (const CUI_clientHandle_t _clientHandle) static
References gClientHandles, and MAX_CLIENTS.
Referenced by CUI_acquireStatusLine(), CUI_statusLinePrintf(), and CUI_validateHandle().
UartWriteCallback()
static void UartWriteCallback (UART_Handle _handle, void * _buf, size_t _size) static
References gRingBuff, gRingBuffPendLen, gRingBuffTailIdx, and gUartHandle.
Referenced by CUI_init().
UartReadCallback()
static void UartReadCallback (UART_Handle _handle, void * _buf, size_t _size) static
References CUI_callMenuUartUpdateFn(), gUartHandle, and gUartTxBuffer.
Referenced by CUI_init().
CUI_updateRemLen()
static CUI_retVal_t CUI_updateRemLen (size_t * _currRemLen, char * _buff, size_t _buffSize) static
References CUI_FAILURE, and CUI_SUCCESS.
Referenced by CUI_statusLinePrintf().
CUI_writeString()
static CUI_retVal_t CUI_writeString (void * _buffer, size_t _size) static
References CUI_SUCCESS, CUI_UART_FAILURE, gRingBuff, gRingBuffHeadIdx, gRingBuffPendLen, gRingBuffTailIdx, gUartHandle, and gUartSem.
Referenced by CUI_assert(), CUI_close(), CUI_deRegisterMenu(), CUI_dispMenu(), CUI_init(), CUI_statusLinePrintf(), and CUI_updateCursor().
CUI_menuActionNavigate()
static void CUI_menuActionNavigate (uint8_t _navDir) static
References CUI_dispMenu(), CUI_INPUT_LEFT, CUI_INPUT_RIGHT, gCurrMenuItemEntry, and CUI_menu_s::numItems.
Referenced by CUI_processMenuUpdate().
CUI_menuActionExecute()
static void CUI_menuActionExecute (void) static
References CUI_dispMenu(), CUI_MENU_ITEM_TYPE_ACTION, CUI_MENU_ITEM_TYPE_SUBMENU, gCurrMenuItemEntry, gPrevMenuItemEntry, CUI_menuItem_t::item, CUI_menuItem_t::itemType, CUI_menu_s::menuItems, CUI_menuItem_t::pFnAction, and CUI_menuItem_t::pSubMenu.
Referenced by CUI_processMenuUpdate().
CUI_dispMenu()
static void CUI_dispMenu (bool _menuPopulated) static
References CUI_END_CHAR, CUI_ESC_CLR_UP, CUI_ESC_CUR_HIDE, CUI_ESC_CUR_HOME, CUI_ESC_CUR_MENU_BTM, CUI_ITEM_PREVIEW, CUI_MENU_ITEM_TYPE_INTERCEPT, CUI_MENU_ITEM_TYPE_LIST, CUI_MENU_ITEM_TYPE_SUBMENU, CUI_MENU_START_CHAR, CUI_MENU_START_ESCAPE_LEN, CUI_NL_CR, CUI_NL_CR_LEN, CUI_writeString(), CUI_list_s::currListIndex, gCurrMenuItemEntry, gpCurrMenu, CUI_menuItem_t::item, CUI_menuItem_t::itemType, MAX_MENU_LINE_LEN, menuBuff, CUI_menu_s::menuItems, CUI_menu_s::numItems, CUI_menuItem_t::pDesc, CUI_menuItem_t::pFnIntercept, CUI_list_s::pFnListAction, CUI_menuItem_t::pList, CUI_menuItem_t::pSubMenu, CUI_menu_s::pTitle, and CUI_menu_s::pUpper.
Referenced by CUI_deRegisterMenu(), CUI_handleMenuIntercept(), CUI_handleMenuList(), CUI_menuActionExecute(), CUI_menuActionNavigate(), CUI_menuNav(), CUI_processMenuUpdate(), CUI_registerMenu(), and CUI_updateMultiMenuTitle().
CUI_callMenuUartUpdateFn()
static void CUI_callMenuUartUpdateFn () static
References gpCurrMenu, CUI_menu_s::pUpper, and CUI_menu_s::uartUpdateFn.
Referenced by UartReadCallback().
CUI_updateCursor()
static void CUI_updateCursor (void) static
References CUI_cursorInfo_t::col, CUI_ESC_CUR_HOME, CUI_ESC_CUR_ROW_COL, CUI_ESC_CUR_SHOW, CUI_writeString(), gCursorActive, and CUI_cursorInfo_t::row.
Referenced by CUI_handleMenuIntercept(), and CUI_statusLinePrintf().
CUI_handleMenuIntercept()
static bool CUI_handleMenuIntercept (CUI_menuItem_t * _pItemEntry, uint8_t _input) static
References CUI_cursorInfo_t::col, CUI_dispMenu(), CUI_INPUT_ESC, CUI_INPUT_EXECUTE, CUI_ITEM_INTERCEPT_CANCEL, CUI_ITEM_INTERCEPT_START, CUI_ITEM_INTERCEPT_STOP, CUI_MENU_ITEM_TYPE_INTERCEPT, CUI_MENU_START_ESCAPE_LEN, CUI_NL_CR_LEN, CUI_updateCursor(), gCursorActive, CUI_menuItem_t::interceptActive, CUI_menuItem_t::item, CUI_menuItem_t::itemType, MAX_MENU_LINE_LEN, menuBuff, CUI_menuItem_t::pFnIntercept, and CUI_cursorInfo_t::row.
Referenced by CUI_processMenuUpdate().
CUI_handleMenuList()
static bool CUI_handleMenuList (CUI_menuItem_t * _pItemEntry, uint8_t _input) static
References CUI_dispMenu(), CUI_INPUT_BACK, CUI_INPUT_ESC, CUI_INPUT_EXECUTE, CUI_INPUT_LEFT, CUI_INPUT_RIGHT, CUI_MENU_ITEM_TYPE_LIST, CUI_MENU_START_ESCAPE_LEN, CUI_NL_CR_LEN, CUI_list_s::currListIndex, CUI_menuItem_t::interceptActive, CUI_menuItem_t::item, CUI_menuItem_t::itemType, MAX_MENU_LINE_LEN, CUI_list_s::maxListItems, menuBuff, CUI_menuItem_t::pDesc, CUI_list_s::pFnListAction, and CUI_menuItem_t::pList.
Referenced by CUI_processMenuUpdate().
CUI_findMenu()
static CUI_retVal_t CUI_findMenu (CUI_menu_t * _pMenu, CUI_menu_t * _pDesiredMenu, uint32_t * _pPrevItemIndex) static
References CUI_FAILURE, CUI_SUCCESS, CUI_menuItem_t::item, CUI_menu_s::menuItems, CUI_menu_s::numItems, CUI_menuItem_t::pDesc, and CUI_menuItem_t::pSubMenu.
Referenced by CUI_menuNav().
CUI_init()
CUI_retVal_t CUI_init (CUI_params_t * _pParams)
References CUI_ESC_CLR, CUI_ESC_CUR_HIDE, CUI_ESC_TRM_MODE, CUI_FAILURE, CUI_SUCCESS, CUI_writeString(), gClientHandles, gClientsSem, gClientsSemStruct, gMenuResources, gMenuSem, gMenuSemStruct, gModuleInitialized, gpMultiMenuTitle, gSemParams, gStatusSem, gStatusSemStruct, gUartHandle, gUartParams, gUartRxBuffer, gUartSem, gUartSemStruct, CUI_params_t::manageUart, MAX_CLIENTS, MAX_REGISTERED_MENUS, CUI_menu_s::numItems, CUI_menu_s::pTitle, CUI_menu_s::pUpper, UartReadCallback(), CUI_menu_s::uartUpdateFn, and UartWriteCallback().
Referenced by CUI_assert().
CUI_paramsInit()
void CUI_paramsInit (CUI_params_t * _pParams)
References CUI_params_t::manageUart.
Referenced by CUI_assert().
CUI_clientOpen()
CUI_clientHandle_t CUI_clientOpen (CUI_clientParams_t * _pParams)
References CUI_FAILURE, gClientHandles, gClientsSem, gMaxStatusLines, gModuleInitialized, gStatusLineResources, MAX_CLIENTS, and CUI_clientParams_t::maxStatusLines.
CUI_clientParamsInit()
void CUI_clientParamsInit (CUI_clientParams_t * _pClientParams)
References CUI_clientParams_t::clientName, and CUI_clientParams_t::maxStatusLines.
CUI_close()
CUI_retVal_t CUI_close ()
References CUI_ESC_CLR, CUI_ESC_CUR_HIDE, CUI_ESC_TRM_MODE, CUI_SUCCESS, CUI_writeString(), gModuleInitialized, gStatusLineResources, gStatusSem, gUartHandle, and MAX_CLIENTS.
CUI_registerMenu()
CUI_retVal_t CUI_registerMenu (const CUI_clientHandle_t _clientHandle, CUI_menu_t * _pMenu)
References CUI_dispMenu(), CUI_INVALID_PARAM, CUI_MAX_MENUS_REACHED, CUI_MENU_ACTION_BACK_DESC, CUI_MENU_ACTION_HELP_DESC, CUI_MENU_ITEM_TYPE_ACTION, CUI_MENU_ITEM_TYPE_INTERCEPT, CUI_MENU_ITEM_TYPE_SUBMENU, CUI_menuActionBack(), CUI_menuActionHelp(), CUI_MISSING_UART_UPDATE_FN, CUI_publicAPIChecks(), CUI_SUCCESS, cuiMultiMenu, gCurrMenuItemEntry, gMenuResources, gMenuSem, gpMainMenu, CUI_menuItem_t::interceptActive, CUI_menuItem_t::item, CUI_menuItem_t::itemType, MAX_REGISTERED_MENUS, CUI_menu_s::menuItems, CUI_menu_s::numItems, CUI_menuItem_t::pDesc, CUI_menuItem_t::pFnAction, CUI_menuItem_t::pFnIntercept, CUI_menuItem_t::pSubMenu, CUI_menu_s::pUpper, and CUI_menu_s::uartUpdateFn.
Referenced by CUI_processMenuUpdate().
CUI_deRegisterMenu()
CUI_retVal_t CUI_deRegisterMenu (const CUI_clientHandle_t _clientHandle, CUI_menu_t * _pMenu)
References CUI_dispMenu(), CUI_ESC_CLR_UP, CUI_ESC_CUR_HIDE, CUI_ESC_CUR_HOME, CUI_ESC_CUR_MENU_BTM, CUI_INVALID_PARAM, CUI_MENU_ACTION_HELP_DESC, CUI_MENU_ITEM_TYPE_INTERCEPT, CUI_menuActionHelp(), CUI_MISSING_UART_UPDATE_FN, CUI_publicAPIChecks(), CUI_RESOURCE_NOT_ACQUIRED, CUI_SUCCESS, CUI_writeString(), cuiMultiMenu, gCurrMenuItemEntry, gMenuResources, gMenuSem, gpMainMenu, CUI_menuItem_t::interceptActive, CUI_menuItem_t::item, CUI_menuItem_t::itemType, MAX_MENU_LINE_LEN, MAX_REGISTERED_MENUS, CUI_menu_s::menuItems, CUI_menu_s::numItems, CUI_menuItem_t::pDesc, CUI_menuItem_t::pFnIntercept, CUI_menuItem_t::pSubMenu, and CUI_menu_s::uartUpdateFn.
Referenced by CUI_processMenuUpdate().
CUI_updateMultiMenuTitle()
CUI_retVal_t CUI_updateMultiMenuTitle (const char * _pTitle)
References CUI_dispMenu(), CUI_INVALID_PARAM, CUI_SUCCESS, and CUI_menu_s::pTitle.
Referenced by CUI_processMenuUpdate().
CUI_menuNav()
CUI_retVal_t CUI_menuNav (const CUI_clientHandle_t _clientHandle, CUI_menu_t * _pMenu, const uint32_t _itemIndex)
References CUI_dispMenu(), CUI_findMenu(), CUI_INVALID_CLIENT_HANDLE, CUI_INVALID_PARAM, CUI_publicAPIChecks(), CUI_SUCCESS, gCurrMenuItemEntry, gMenuResources, gPrevMenuItemEntry, MAX_REGISTERED_MENUS, and CUI_menu_s::numItems.
Referenced by CUI_processMenuUpdate().
CUI_processMenuUpdate()
CUI_retVal_t CUI_processMenuUpdate (void)
References CUI_deRegisterMenu(), CUI_dispMenu(), CUI_ESC_DOWN, CUI_ESC_ESC, CUI_ESC_LEFT, CUI_ESC_RIGHT, CUI_ESC_UP, CUI_FAILURE, CUI_handleMenuIntercept(), CUI_handleMenuList(), CUI_INPUT_BACK, CUI_INPUT_DOWN, CUI_INPUT_ESC, CUI_INPUT_EXECUTE, CUI_INPUT_LEFT, CUI_INPUT_RIGHT, CUI_INPUT_UP, CUI_MENU_ITEM_TYPE_INTERCEPT, CUI_MENU_ITEM_TYPE_LIST, CUI_menuActionExecute(), CUI_menuActionNavigate(), CUI_menuNav(), CUI_registerMenu(), CUI_SUCCESS, CUI_updateMultiMenuTitle(), gCurrMenuItemEntry, gModuleInitialized, gpMainMenu, gPrevMenuItemEntry, gUartHandle, gUartRxBuffer, gUartTxBuffer, CUI_menuItem_t::interceptActive, CUI_menuItem_t::itemType, CUI_menu_s::menuItems, CUI_menu_s::numItems, and CUI_menu_s::pUpper.
CUI_statusLineResourceRequest()
CUI_retVal_t CUI_statusLineResourceRequest (const CUI_clientHandle_t _clientHandle, const char _pLabel[MAX_STATUS_LINE_LABEL_LEN], const bool _refreshInd, uint32_t * _pLineId)
References CUI_acquireStatusLine(), CUI_INVALID_PARAM, CUI_publicAPIChecks(), CUI_statusLinePrintf(), and CUI_SUCCESS.
CUI_statusLinePrintf()
CUI_retVal_t CUI_statusLinePrintf (const CUI_clientHandle_t _clientHandle, const uint32_t _lineId, const char * _format, ...)
References CUI_ACQUIRED, CUI_END_CHAR, CUI_ESC_CLR_STAT_LINE_VAL, CUI_ESC_CUR_HIDE, CUI_ESC_CUR_HOME, CUI_ESC_CUR_LINE, CUI_getClientIndex(), CUI_INITIAL_STATUS_OFFSET, CUI_INVALID_CLIENT_HANDLE, CUI_MAX_LABEL_AND_SEP_LEN, CUI_NL_CR, CUI_publicAPIChecks(), CUI_RESOURCE_NOT_ACQUIRED, CUI_STATUS_LINE_START_CHAR, CUI_SUCCESS, CUI_updateCursor(), CUI_updateRemLen(), CUI_writeString(), gStatusLineResources, MAX_REGISTERED_MENUS, and MAX_STATUS_LINE_VALUE_LEN.
Referenced by CUI_statusLineResourceRequest().
CUI_assert()
void CUI_assert (const char * _assertMsg, const bool _spinLock)
References CUI_COLOR_RED, CUI_COLOR_RESET, CUI_END_CHAR, CUI_ESC_CLR_STAT_LINE_VAL, CUI_ESC_CUR_HIDE, CUI_ESC_CUR_HOME, CUI_ESC_CUR_LINE, CUI_init(), CUI_INITIAL_STATUS_OFFSET, CUI_paramsInit(), CUI_STATUS_LINE_START_CHAR, CUI_writeString(), gModuleInitialized, and MAX_STATUS_LINE_VALUE_LEN.
CUI_menuActionBack()
void CUI_menuActionBack (const int32_t _itemEntry)
References gCurrMenuItemEntry, gPrevMenuItemEntry, and CUI_menu_s::pUpper.
Referenced by CUI_registerMenu().
CUI_menuActionHelp()
void CUI_menuActionHelp (char _input, char * _lines[3], CUI_cursorInfo_t * _curInfo)
References CUI_ITEM_PREVIEW, and MAX_MENU_LINE_LEN.
Referenced by CUI_deRegisterMenu(), and CUI_registerMenu().
CUI_acquireStatusLine() [2/2]
static CUI_retVal_t CUI_acquireStatusLine (const CUI_clientHandle_t _clientHandle, const char _pLabel[MAX_STATUS_LINE_LABEL_LEN], const bool _refreshInd, uint32_t * _pLineId) static
References CUI_ACQUIRED, CUI_getClientIndex(), CUI_INVALID_PARAM, CUI_LABEL_VAL_SEP, CUI_NO_ASYNC_LINES_RELEASED, CUI_RELEASED, CUI_SUCCESS, gMaxStatusLines, gStatusLineResources, and gStatusSem.
Variable Documentation
gModuleInitialized
bool gModuleInitialized = false static
Referenced by CUI_assert(), CUI_clientOpen(), CUI_close(), CUI_init(), CUI_processMenuUpdate(), and CUI_publicAPIChecks().
gSemParams
Semaphore_Params gSemParams static
Referenced by CUI_init().
gClientHandles
CUI_clientHandle_t gClientHandles[MAX_CLIENTS] static
Referenced by CUI_clientOpen(), CUI_getClientIndex(), and CUI_init().
gMaxStatusLines
uint32_t gMaxStatusLines[MAX_CLIENTS] static
Referenced by CUI_acquireStatusLine(), and CUI_clientOpen().
gClientsSem
Semaphore_Handle gClientsSem static
Referenced by CUI_clientOpen(), and CUI_init().
gClientsSemStruct
Semaphore_Struct gClientsSemStruct static
Referenced by CUI_init().
gUartParams
UART_Params gUartParams static
Referenced by CUI_init().
gUartHandle
UART_Handle gUartHandle = NULL static
Referenced by CUI_close(), CUI_init(), CUI_processMenuUpdate(), CUI_writeString(), UartReadCallback(), and UartWriteCallback().
gUartTxBuffer
uint8_t gUartTxBuffer[CUI_NUM_UART_CHARS] static
Referenced by CUI_processMenuUpdate(), and UartReadCallback().
gUartRxBuffer
uint8_t gUartRxBuffer[CUI_NUM_UART_CHARS] static
Referenced by CUI_init(), and CUI_processMenuUpdate().
gUartSem
Semaphore_Handle gUartSem static
Referenced by CUI_init(), and CUI_writeString().
gUartSemStruct
Semaphore_Struct gUartSemStruct static
Referenced by CUI_init().
gRingBuff
uint8_t gRingBuff[512] static
Referenced by CUI_writeString(), and UartWriteCallback().
gRingBuffHeadIdx
size_t gRingBuffHeadIdx = 0 static
Referenced by CUI_writeString().
gRingBuffTailIdx
size_t gRingBuffTailIdx = 0 static
Referenced by CUI_writeString(), and UartWriteCallback().
gRingBuffPendLen
size_t gRingBuffPendLen = 0 static
Referenced by CUI_writeString(), and UartWriteCallback().
gpCurrMenu
CUI_menu_t* gpCurrMenu static
Referenced by CUI_callMenuUartUpdateFn(), and CUI_dispMenu().
gpMainMenu
CUI_menu_t* gpMainMenu static
Referenced by CUI_deRegisterMenu(), CUI_processMenuUpdate(), and CUI_registerMenu().
gCurrMenuItemEntry
size_t gCurrMenuItemEntry = 0 static
Referenced by CUI_deRegisterMenu(), CUI_dispMenu(), CUI_menuActionBack(), CUI_menuActionExecute(), CUI_menuActionNavigate(), CUI_menuNav(), CUI_processMenuUpdate(), and CUI_registerMenu().
gPrevMenuItemEntry
size_t gPrevMenuItemEntry = 0 static
Referenced by CUI_menuActionBack(), CUI_menuActionExecute(), CUI_menuNav(), and CUI_processMenuUpdate().
gCursorActive
bool gCursorActive static
Referenced by CUI_handleMenuIntercept(), and CUI_updateCursor().
gCursorInfo
CUI_cursorInfo_t gCursorInfo static
gMenuResources
CUI_menuResource_t gMenuResources[MAX_REGISTERED_MENUS] static
Referenced by CUI_deRegisterMenu(), CUI_init(), CUI_menuNav(), and CUI_registerMenu().
gMenuSem
Semaphore_Handle gMenuSem static
Referenced by CUI_deRegisterMenu(), CUI_init(), and CUI_registerMenu().
gMenuSemStruct
Semaphore_Struct gMenuSemStruct static
Referenced by CUI_init().
menuBuff
char menuBuff[CUI_MENU_START_ESCAPE_LEN+MAX_MENU_LINE_LEN+CUI_NL_CR_LEN+MAX_MENU_LINE_LEN+CUI_NL_CR_LEN+MAX_MENU_LINE_LEN+CUI_ETX_LEN]
Referenced by CUI_dispMenu(), CUI_handleMenuIntercept(), and CUI_handleMenuList().
gpMultiMenuTitle
char gpMultiMenuTitle[] = " TI DMM Application " static
Referenced by CUI_init().
cuiMultiMenuData
uint8_t cuiMultiMenuData[sizeof(CUI_menu_t)+((MAX_REGISTERED_MENUS+1) *sizeof(CUI_menuItem_t))]
cuiMultiMenu
CUI_menu_t* cuiMultiMenu = (CUI_menu_t *)&cuiMultiMenuData
Referenced by CUI_deRegisterMenu(), and CUI_registerMenu().
gStatusLineResources
CUI_statusLineResource_t* gStatusLineResources[MAX_CLIENTS] static
Referenced by CUI_acquireStatusLine(), CUI_clientOpen(), CUI_close(), and CUI_statusLinePrintf().
gStatusSem
Semaphore_Handle gStatusSem static
Referenced by CUI_acquireStatusLine(), CUI_close(), and CUI_init().
gStatusSemStruct
Semaphore_Struct gStatusSemStruct static
Referenced by CUI_init().
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale