TI-OpenThread: keys_utils.c File Reference
CC1352P_4_LAUNCHXL/thread/doorlock_oad_secure/keys_utils.c File Reference
#include <stdbool.h>
#include <time.h>
#include <ti/drivers/GPIO.h>
#include "ti_drivers_config.h"
#include "keys_utils.h"
Functions
void gpioButtonFxn (uint_least8_t index)
Callback function for the GPIO Button.
static void KeysUtils_changeHandler (union sigval val)
Callback function called when the key debounce period expires.
void KeysUtils_initialize (KeyUtils_PressedCB_t keyCb)
Enable interrupts for keys on GPIOs.
Variables
static KeyUtils_PressedCB_t appKeyChangeHandler = NULL
static volatile uint8_t keysPressed
static timer_t keyTimerID
Function Documentation
gpioButtonFxn()
void gpioButtonFxn (uint_least8_t index)
Callback function for the GPIO Button.
Parameters
index identifies the button pressed.
Returns
None
References KEY_DEBOUNCE_TIMEOUT, KEYS_LEFT, KEYS_RIGHT, keysPressed, and keyTimerID.
Referenced by KeysUtils_initialize().
KeysUtils_changeHandler()
static void KeysUtils_changeHandler (union sigval val) static
Callback function called when the key debounce period expires.
Parameters
val input argument(ignored).
Returns
None
References appKeyChangeHandler, and keysPressed.
Referenced by KeysUtils_initialize().
KeysUtils_initialize()
void KeysUtils_initialize (KeyUtils_PressedCB_t keyCb)
Enable interrupts for keys on GPIOs.
Parameters
keyCb - application key pressed callback
References appKeyChangeHandler, gpioButtonFxn(), KeysUtils_changeHandler(), and keyTimerID.
Variable Documentation
keysPressed
volatile uint8_t keysPressed static
Referenced by gpioButtonFxn(), and KeysUtils_changeHandler().
appKeyChangeHandler
KeyUtils_PressedCB_t appKeyChangeHandler = NULL static
Referenced by KeysUtils_changeHandler(), and KeysUtils_initialize().
keyTimerID
timer_t keyTimerID static
Referenced by gpioButtonFxn(), and KeysUtils_initialize().
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale