TI-OpenThread: radio.c File Reference
CC1352R1_LAUNCHXL/thread/oad_cli/platform/radio.c File Reference
#include <openthread/config.h>
#include "radio.h"
#include <stddef.h>
#include <openthread/diag.h>
#include <openthread/platform/alarm-milli.h>
#include <openthread/platform/diag.h>
#include <openthread/platform/radio.h>
#include <openthread/platform/entropy.h>
#include <utils/code_utils.h>
#include <ti/devices/DeviceFamily.h>
#include <DeviceFamily_constructPath(driverlib/aon_rtc.h)>
#include <DeviceFamily_constructPath(driverlib/rf_data_entry.h)>
#include <DeviceFamily_constructPath(driverlib/rf_common_cmd.h)>
#include <DeviceFamily_constructPath(driverlib/rf_mailbox.h)>
#include <DeviceFamily_constructPath(driverlib/rf_ieee_cmd.h)>
#include <DeviceFamily_constructPath(driverlib/rf_ieee_mailbox.h)>
#include <DeviceFamily_constructPath(inc/hw_ccfg.h)>
#include <DeviceFamily_constructPath(inc/hw_fcfg1.h)>
#include <ti/drivers/rf/RF.h>
#include <ti_radio_config.h>
#include "system.h"
#include "ti_drivers_config.h"
#include "tiop_config.h"
Macros
#define PLATFORM_RADIO_TX_TEST_MODULATED_WORD 0xAAAA
#define PLATFORM_RADIO_TX_TEST_SYNC_WORD 0x71764129
#define PLATFORM_RADIO_TX_TEST_UNMODULATED_WORD 0xFFFF
#define RF_NUM_RAT_TICKS_IN_1_US 4
Functions
static otRadioFrame * ackSearchRxQueue (struct rx_queue_info *rqi, unsigned int events, uint8_t ackDsn)
static void clearRxQueue (void)
static otRadioFrame * handleRxAckFinish (struct rx_queue_info *p, uint8_t ackDsn)
static void handleRxDataFinish (struct rx_queue_info *p)
static unsigned int handleTxAck (RF_Handle aRfHandle)
static void handleTxState (otInstance *aInstance, unsigned int events)
static void nextQueueEntry (struct rx_queue_info *p)
otError otPlatDiagRadioToneStart (otInstance *aInstance, bool aModulated)
otError otPlatDiagRadioToneStop (otInstance *aInstance)
otError otPlatRadioAddSrcMatchExtEntry (otInstance *aInstance, const otExtAddress *aExtAddress)
otError otPlatRadioAddSrcMatchShortEntry (otInstance *aInstance, const uint16_t aShortAddress)
void otPlatRadioClearSrcMatchExtEntries (otInstance *aInstance)
otError otPlatRadioClearSrcMatchExtEntry (otInstance *aInstance, const otExtAddress *aExtAddress)
void otPlatRadioClearSrcMatchShortEntries (otInstance *aInstance)
otError otPlatRadioClearSrcMatchShortEntry (otInstance *aInstance, const uint16_t aShortAddress)
otError otPlatRadioDisable (otInstance *aInstance)
otError otPlatRadioEnable (otInstance *aInstance)
void otPlatRadioEnableSrcMatch (otInstance *aInstance, bool aEnable)
otError otPlatRadioEnergyScan (otInstance *aInstance, uint8_t aScanChannel, uint16_t aScanDuration)
otRadioCaps otPlatRadioGetCaps (otInstance *aInstance)
otError otPlatRadioGetCcaEnergyDetectThreshold (otInstance *aInstance, int8_t *aThreshold)
void otPlatRadioGetIeeeEui64 (otInstance *aInstance, uint8_t *aIeeeEui64)
bool otPlatRadioGetPromiscuous (otInstance *aInstance)
int8_t otPlatRadioGetReceiveSensitivity (otInstance *aInstance)
Get the receive command's sensitivity.
int8_t otPlatRadioGetRssi (otInstance *aInstance)
otRadioFrame * otPlatRadioGetTransmitBuffer (otInstance *aInstance)
otError otPlatRadioGetTransmitPower (otInstance *aInstance, int8_t *aPower)
bool otPlatRadioIsEnabled (otInstance *aInstance)
otError otPlatRadioReceive (otInstance *aInstance, uint8_t aChannel)
otError otPlatRadioSetCcaEnergyDetectThreshold (otInstance *aInstance, int8_t aThreshold)
void otPlatRadioSetExtendedAddress (otInstance *aInstance, const otExtAddress *aAddress)
void otPlatRadioSetPanId (otInstance *aInstance, uint16_t aPanid)
void otPlatRadioSetPromiscuous (otInstance *aInstance, bool aEnable)
void otPlatRadioSetShortAddress (otInstance *aInstance, uint16_t aAddress)
otError otPlatRadioSetTransmitPower (otInstance *aInstance, int8_t aPower)
otError otPlatRadioSleep (otInstance *aInstance)
otError otPlatRadioTransmit (otInstance *aInstance, otRadioFrame *aFrame)
void platformRadioInit (void)
void platformRadioProcess (otInstance *aInstance, uintptr_t arg)
static void platformRadioProcessReceiveDone (otInstance *aInstance, otRadioFrame *aReceiveFrame, otError aReceiveError)
static void platformRadioProcessTransmitDone (otInstance *aInstance, otRadioFrame *aTransmitFrame, otRadioFrame *aAckFrame, otError aTransmitError)
static otError populateReceiveFrame (struct rx_queue_info *p)
static void processRxQueue (otInstance *aInstance, unsigned int events)
static void radioSignal (unsigned int evts)
Post a Radio Signal.
static void releaseAndNext (struct rx_queue_info *p)
static void releaseQueueEntry (struct rx_queue_info *p)
void rfCoreDiagChannelDisable (uint8_t aChannel)
void rfCoreDiagChannelEnable (uint8_t aChannel)
static void rfCoreEdScanCmdCallback (RF_Handle aRfHandle, RF_CmdHandle aRfCmdHandle, RF_EventMask aRfEventMask)
Callback for the Energy Detect command.
static void rfCoreErrorCallback (RF_Handle aHandle, RF_CmdHandle aCmdHandle, RF_EventMask aEvents)
static RF_Stat rfCoreExecuteAbortCmd (RF_Handle aRfHandle, RF_CmdHandle aRfCmdHandle)
sends the direct abort command to the radio core
static uint8_t rfCoreFindEmptyExtSrcMatchIdx (void)
walks the ext address source match list to find an empty slot
static uint8_t rfCoreFindEmptyShortSrcMatchIdx (void)
walks the short address source match list to find an empty slot
static uint8_t rfCoreFindExtSrcMatchIdx (const uint64_t *aAddress)
walks the ext address source match list to find an address
static uint8_t rfCoreFindShortSrcMatchIdx (const uint16_t aAddress)
walks the short address source match list to find an address
static void rfCoreInitBufs (void)
initialize the RX/TX buffers
static void rfCoreInitReceiveParams (void)
initialize the RX command structure
void rfCoreInitSetupCmd (void)
initializes the setup command structure
static RF_Stat rfCoreModifyRxAutoPend (RF_Handle aRfHandle, bool aEnable)
enable/disable autoPend
static RF_Stat rfCoreModifyRxFrameFilter (RF_Handle aRfHandle, bool aEnable)
enable/disable filtering
static RF_Stat rfCoreModifySourceMatchEntry (RF_Handle aRfHandle, uint8_t aEntryNo, platformRadio_address aType, bool aEnable)
sends the immediate modify source matching command to the radio core
static void rfCoreRxCallback (RF_Handle aRfHandle, RF_CmdHandle aRfCmdHandle, RF_EventMask aRfEventMask)
static RF_CmdHandle rfCoreSendEdScanCmd (RF_Handle aRfHandle, uint8_t aChannel, uint16_t aDuration)
sends the energy detect scan command to the radio core
static RF_CmdHandle rfCoreSendReceiveCmd (RF_Handle aRfHandle)
sends the rx command to the radio core
static RF_CmdHandle rfCoreSendTransmitCmd (otInstance *aInstance, RF_Handle aRfHandle, uint8_t *aPsdu, uint8_t aLen)
sends the tx command to the radio core
static RF_CmdHandle rfCoreSendTxTestCmd (RF_Handle aRfHandle, bool aModulated)
static otError rfCoreSetTransmitPower (int8_t aPower)
Sets the transmit.
static void rfCoreTxCallback (RF_Handle aRfHandle, RF_CmdHandle aRfCmdHandle, RF_EventMask aRfEventMask)
static void rfCoreTxTestCmdCallback (RF_Handle aRfHandle, RF_CmdHandle aRfCmdHandle, RF_EventMask aRfEventMask)
Callback for the Transmit Test command.
static RF_CmdHandle startTransmit (RF_Handle aRfHandle)
Start a transmission, or a start a retry.
Variables
static volatile rfc_CMD_IEEE_CSMA_t sCsmaBackoffCmd
static bool sDisableChannel = false
static volatile rfc_CMD_IEEE_ED_SCAN_t sEdScanCmd
static uint16_t seedRandom
static volatile rfc_CMD_IEEE_MOD_FILT_t sModifyReceiveFilterCmd
static volatile rfc_CMD_IEEE_MOD_SRC_MATCH_t sModifyReceiveSrcMatchCmd
static volatile rfc_CMD_RADIO_SETUP_t sRadioSetupCmd
static volatile rfc_CMD_IEEE_RX_t sReceiveCmd
static RF_CmdHandle sReceiveCmdHandle
static int8_t sReqTxPower = TIOP_CONFIG_TX_POWER
static RF_Handle sRfHandle
static RF_Object sRfObject
static volatile rfc_ieeeRxOutput_t sRfStats
static uint8_t sRxBuf0 [RX_BUF_SIZE]
static uint8_t sRxBuf1 [RX_BUF_SIZE]
static uint8_t sRxBuf2 [RX_BUF_SIZE]
static uint8_t sRxBuf3 [RX_BUF_SIZE]
static dataQueue_t sRxDataQueue = { 0 }
static volatile ext_src_match_data_t sSrcMatchExtData
static volatile short_src_match_data_t sSrcMatchShortData
static volatile platformRadio_phyState sState
static volatile rfc_CMD_IEEE_TX_t sTransmitCmd
static RF_CmdHandle sTransmitCmdHandle
static otError sTransmitError
static otRadioFrame sTransmitFrame
static uint8_t sTransmitPsdu [OT_RADIO_FRAME_MAX_SIZE]
static volatile unsigned int sTransmitRetryCount = 0
static volatile rfc_CMD_IEEE_RX_ACK_t sTransmitRxAckCmd
static volatile rfc_CMD_TX_TEST_t sTxTestCmd
static RF_CmdHandle sTxTestCmdHandle
Macro Definition Documentation
RF_NUM_RAT_TICKS_IN_1_US
#define RF_NUM_RAT_TICKS_IN_1_US 4
Referenced by populateReceiveFrame().
PLATFORM_RADIO_TX_TEST_SYNC_WORD
#define PLATFORM_RADIO_TX_TEST_SYNC_WORD 0x71764129
PLATFORM_RADIO_TX_TEST_MODULATED_WORD
#define PLATFORM_RADIO_TX_TEST_MODULATED_WORD 0xAAAA
Referenced by rfCoreSendTxTestCmd().
PLATFORM_RADIO_TX_TEST_UNMODULATED_WORD
#define PLATFORM_RADIO_TX_TEST_UNMODULATED_WORD 0xFFFF
Referenced by rfCoreSendTxTestCmd().
Function Documentation
startTransmit()
static RF_CmdHandle startTransmit (RF_Handle aRfHandle) static
Start a transmission, or a start a retry.
Parameters
[in] aRfHandle The rf handle
Returns
RF command handle for the transmission.
References rfCoreTxCallback(), and sCsmaBackoffCmd.
Referenced by handleTxAck(), and rfCoreSendTransmitCmd().
radioSignal()
static void radioSignal (unsigned int evts) static
Post a Radio Signal.
Some Radio event has occurred, wake the process loops.
Parameters
[in] evts Events to post
References platformRadioSignal().
Referenced by otPlatRadioSleep(), rfCoreEdScanCmdCallback(), rfCoreRxCallback(), and rfCoreTxCallback().
rfCoreInitBufs()
static void rfCoreInitBufs (void) static
initialize the RX/TX buffers
Zeros out the receive and transmit buffers and sets up the data structures of the receive queue.
References DATA_ENTRY_LENSZ_BYTE, sRxBuf0, sRxBuf1, sRxBuf2, sRxBuf3, sRxDataQueue, and sTransmitPsdu.
Referenced by platformRadioInit().
rfCoreInitSetupCmd()
void rfCoreInitSetupCmd (void)
initializes the setup command structure
The sRadioSetupCmd struct is used by the RF driver to bring the
References sRadioSetupCmd.
Referenced by platformRadioInit().
rfCoreInitReceiveParams()
static void rfCoreInitReceiveParams (void) static
initialize the RX command structure
Sets the default values for the receive command structure.
References PLATFORM_RADIO_EXTADD_SRC_MATCH_NUM, PLATFORM_RADIO_SHORTADD_SRC_MATCH_NUM, sReceiveCmd, sRfStats, sRxDataQueue, sSrcMatchExtData, and sSrcMatchShortData.
Referenced by platformRadioInit().
otPlatRadioGetReceiveSensitivity()
int8_t otPlatRadioGetReceiveSensitivity (otInstance * aInstance)
Get the receive command's sensitivity.
References sReceiveCmd.
rfCoreExecuteAbortCmd()
static RF_Stat rfCoreExecuteAbortCmd (RF_Handle aRfHandle, RF_CmdHandle aRfCmdHandle) static
sends the direct abort command to the radio core
Parameters
[in] aRfHandle The handle for the RF core client
[in] aRfCmdHandle The command handle to be aborted
Returns
the value from the command status register
Return values
RF_StatSuccess the command completed correctly
References RF_DRIVER_ABORT.
Referenced by otPlatDiagRadioToneStart(), otPlatDiagRadioToneStop(), otPlatRadioEnergyScan(), otPlatRadioReceive(), otPlatRadioSetExtendedAddress(), otPlatRadioSetPanId(), otPlatRadioSetShortAddress(), otPlatRadioSleep(), and rfCoreSetTransmitPower().
rfCoreModifyRxFrameFilter()
static RF_Stat rfCoreModifyRxFrameFilter (RF_Handle aRfHandle, bool aEnable) static
enable/disable filtering
Uses the radio core to alter the current running RX command filtering options. This ensures there is no access fault between the CM3 and CM0 for the RX command.
This function leaves the type of frames to be filtered the same as the receive command.
Note
An IEEE RX command must be running while this command executes.
Parameters
[in] aRfHandle The handle for the RF core client
[in] aEnable TRUE: enable frame filtering FALSE: disable frame filtering
Returns
the value from the command status register
Return values
RF_StatCmdDoneSuccess the command completed correctly
References sModifyReceiveFilterCmd, and sReceiveCmd.
Referenced by otPlatRadioSetPromiscuous().
rfCoreModifyRxAutoPend()
static RF_Stat rfCoreModifyRxAutoPend (RF_Handle aRfHandle, bool aEnable) static
enable/disable autoPend
Uses the radio core to alter the current running RX command filtering options. This ensures there is no access fault between the CM3 and CM0 for the RX command.
This function leaves the type of frames to be filtered the same as the receive command.
Note
An IEEE RX command must be running while this command executes.
Parameters
[in] aRfHandle The handle for the RF core client
[in] aEnable TRUE: enable autoPend, FALSE: disable autoPend
Returns
the value from the command status register
Return values
RF_StatCmdDoneSuccess the command completed correctly
References sModifyReceiveFilterCmd, and sReceiveCmd.
Referenced by otPlatRadioEnableSrcMatch().
rfCoreModifySourceMatchEntry()
static RF_Stat rfCoreModifySourceMatchEntry (RF_Handle aRfHandle, uint8_t aEntryNo, platformRadio_address aType, bool aEnable) static
sends the immediate modify source matching command to the radio core
Uses the radio core to alter the current source matching parameters used by the running RX command. This ensures there is no access fault between the CM3 and CM0, and ensures that the RX command has cohesive view of the data. The CM3 may make alterations to the source matching entries if the entry is marked as disabled.
Note
An IEEE RX command must be running while this command executes.
Parameters
[in] aRfHandle The handle for the RF core client
[in] aEntryNo The index of the entry to alter
[in] aType TRUE: the entry is a short address FALSE: the entry is an extended address
[in] aEnable Whether the given entry is to be enabled or disabled
Returns
the value from the command status register
Return values
RF_StatCmdDoneSuccess the command completed correctly
References sModifyReceiveSrcMatchCmd.
Referenced by otPlatRadioAddSrcMatchExtEntry(), otPlatRadioAddSrcMatchShortEntry(), otPlatRadioClearSrcMatchExtEntries(), otPlatRadioClearSrcMatchExtEntry(), otPlatRadioClearSrcMatchShortEntries(), and otPlatRadioClearSrcMatchShortEntry().
rfCoreFindShortSrcMatchIdx()
static uint8_t rfCoreFindShortSrcMatchIdx (const uint16_t aAddress) static
walks the short address source match list to find an address
Parameters
[in] aAddress the short address to search for
Returns
the index where the address was found
Return values
PLATFORM_RADIO_SRC_MATCH_NONE the address was not found
References PLATFORM_RADIO_SHORTADD_SRC_MATCH_NUM, PLATFORM_RADIO_SRC_MATCH_NONE, and sSrcMatchShortData.
Referenced by otPlatRadioAddSrcMatchShortEntry(), and otPlatRadioClearSrcMatchShortEntry().
rfCoreFindEmptyShortSrcMatchIdx()
static uint8_t rfCoreFindEmptyShortSrcMatchIdx (void) static
walks the short address source match list to find an empty slot
Returns
the index of an unused address slot
Return values
PLATFORM_RADIO_SRC_MATCH_NONE no unused slots available
References PLATFORM_RADIO_SHORTADD_SRC_MATCH_NUM, PLATFORM_RADIO_SRC_MATCH_NONE, and sSrcMatchShortData.
Referenced by otPlatRadioAddSrcMatchShortEntry().
rfCoreFindExtSrcMatchIdx()
static uint8_t rfCoreFindExtSrcMatchIdx (const uint64_t * aAddress) static
walks the ext address source match list to find an address
Parameters
[in] aAddress the ext address to search for
Returns
the index where the address was found
Return values
PLATFORM_RADIO_SRC_MATCH_NONE the address was not found
References PLATFORM_RADIO_EXTADD_SRC_MATCH_NUM, PLATFORM_RADIO_SRC_MATCH_NONE, and sSrcMatchExtData.
Referenced by otPlatRadioAddSrcMatchExtEntry(), and otPlatRadioClearSrcMatchExtEntry().
rfCoreFindEmptyExtSrcMatchIdx()
static uint8_t rfCoreFindEmptyExtSrcMatchIdx (void) static
walks the ext address source match list to find an empty slot
Returns
the index of an unused address slot
Return values
PLATFORM_RADIO_SRC_MATCH_NONE no unused slots available
References PLATFORM_RADIO_EXTADD_SRC_MATCH_NUM, PLATFORM_RADIO_SRC_MATCH_NONE, and sSrcMatchExtData.
Referenced by otPlatRadioAddSrcMatchExtEntry().
handleTxAck()
static unsigned int handleTxAck (RF_Handle aRfHandle) static
Helper function for handling retries when transmitting.
Return values
event mask to post if done
References IEEE802154_MAC_MAX_FRAMES_RETRIES, RF_EVENT_TX_DONE, sCsmaBackoffCmd, startTransmit(), sTransmitCmd, sTransmitCmdHandle, sTransmitRetryCount, and sTransmitRxAckCmd.
Referenced by rfCoreTxCallback().
rfCoreTxCallback()
static void rfCoreTxCallback (RF_Handle aRfHandle, RF_CmdHandle aRfCmdHandle, RF_EventMask aRfEventMask) static
Callback for the TX command chain.
This callback is called on completion of the command string or failure of an individual command in the string.
Parameters
[in] aRfHandle Handle of the RF object
[in] aRfCmdHandle Handle of the command chain that finished
[in] aRfEventMask Events that happened to trigger this callback
References handleTxAck(), IEEE802154_ACK_REQUEST, radioSignal(), RF_EVENT_TX_CMD_PREEMPTED, RF_EVENT_TX_DONE, sCsmaBackoffCmd, seedRandom, and sTransmitCmd.
Referenced by startTransmit().
rfCoreSendTransmitCmd()
static RF_CmdHandle rfCoreSendTransmitCmd (otInstance * aInstance, RF_Handle aRfHandle, uint8_t * aPsdu, uint8_t aLen) static
sends the tx command to the radio core
Sends the packet to the radio core to be sent asynchronously.
Parameters
[in] aRfHandle The handle for the RF core client
[in] aPsdu A pointer to the data to be sent
Note
this must be 4 byte aligned and not include the FCS, that is calculated in hardware.
Parameters
[in] aLen The length in bytes of data pointed to by psdu.
Returns
handle of the running command returned by the command scheduler
References IEEE802154_ACK_REQUEST, IEEE802154_DSN_OFFSET, IEEE802154_MAC_ACK_WAIT_DURATION, IEEE802154_MAC_MAX_BE, IEEE802154_MAC_MAX_CSMA_BACKOFFS, IEEE802154_MAC_MIN_BE, IEEE802154_SYMBOLS_PER_SEC, otDiagIsEnabled(), PLATFORM_RADIO_RAT_TICKS_PER_SEC, rfCoreSendReceiveCmd(), sCsmaBackoffCmd, seedRandom, startTransmit(), sTransmitCmd, sTransmitRetryCount, and sTransmitRxAckCmd.
Referenced by otPlatRadioTransmit().
rfCoreSendReceiveCmd()
static RF_CmdHandle rfCoreSendReceiveCmd (RF_Handle aRfHandle) static
sends the rx command to the radio core
Sends the pre-built receive command to the radio core. This sets up the radio to receive packets according to the settings in the global rx command.
Note
This function does not alter any of the parameters of the rx command. It is only concerned with sending the command to the radio core. See otPlatRadioSetPanId for an example of how the rx settings are set changed.
Parameters
[in] aRfHandle The handle for the RF core client
Returns
handle of the running command returned by the command scheduler
References rfCoreRxCallback(), and sReceiveCmd.
Referenced by otPlatDiagRadioToneStop(), otPlatRadioReceive(), otPlatRadioSetExtendedAddress(), otPlatRadioSetPanId(), otPlatRadioSetShortAddress(), platformRadioProcess(), rfCoreRxCallback(), rfCoreSendTransmitCmd(), and rfCoreSetTransmitPower().
rfCoreRxCallback()
static void rfCoreRxCallback (RF_Handle aRfHandle, RF_CmdHandle aRfCmdHandle, RF_EventMask aRfEventMask) static
Callback for the receive command.
Parameters
[in] aRfHandle Handle of the RF object
[in] aRfCmdHandle Handle of the command chain that finished
[in] aRfEventMask Events that happened to trigger this callback
References radioSignal(), RF_EVENT_BUF_FULL, RF_EVENT_RX_ACK_DONE, RF_EVENT_RX_CMD_PREEMPTED, RF_EVENT_RX_CMD_STOP, RF_EVENT_RX_DONE, rfCoreSendReceiveCmd(), sReceiveCmd, sReceiveCmdHandle, and sRfHandle.
Referenced by rfCoreSendReceiveCmd().
rfCoreSetTransmitPower()
static otError rfCoreSetTransmitPower (int8_t aPower) static
Sets the transmit.
Sets the transmit power within the radio setup command or the override list.
References platformRadio_phyState_Disabled, platformRadio_phyState_Sleep, rfCoreExecuteAbortCmd(), rfCoreSendReceiveCmd(), sReceiveCmd, sReceiveCmdHandle, sRfHandle, and sState.
Referenced by otPlatRadioReceive(), and otPlatRadioSetTransmitPower().
rfCoreEdScanCmdCallback()
static void rfCoreEdScanCmdCallback (RF_Handle aRfHandle, RF_CmdHandle aRfCmdHandle, RF_EventMask aRfEventMask) static
Callback for the Energy Detect command.
Parameters
[in] aRfHandle Handle of the RF object
[in] aRfCmdHandle Handle of the command chain that finished
[in] aRfEventMask Events that happened to trigger this callback
References radioSignal(), and RF_EVENT_ED_SCAN_DONE.
Referenced by rfCoreSendEdScanCmd().
rfCoreSendEdScanCmd()
static RF_CmdHandle rfCoreSendEdScanCmd (RF_Handle aRfHandle, uint8_t aChannel, uint16_t aDuration) static
sends the energy detect scan command to the radio core
Sends the Energy Detect scan command to the radio core. This scans the given channel for activity.
Parameters
[in] aRfHandle The handle for the RF core client
[in] aChannel The IEEE page 0 channel to scan
[in] aDuration Time in ms to scan
Returns
handle of the running command returned by the command scheduler
References PLATFORM_RADIO_RAT_TICKS_PER_SEC, rfCoreEdScanCmdCallback(), and sEdScanCmd.
Referenced by otPlatRadioEnergyScan().
rfCoreTxTestCmdCallback()
static void rfCoreTxTestCmdCallback (RF_Handle aRfHandle, RF_CmdHandle aRfCmdHandle, RF_EventMask aRfEventMask) static
Callback for the Transmit Test command.
Parameters
[in] aRfHandle Handle of the RF object
[in] aRfCmdHandle Handle of the command chain that finished
[in] aRfEventMask Events that happened to trigger this callback
Referenced by rfCoreSendTxTestCmd().
rfCoreSendTxTestCmd()
static RF_CmdHandle rfCoreSendTxTestCmd (RF_Handle aRfHandle, bool aModulated) static
Parameters
[in] aRfHandle The handle for the RF core client
[in] aModulated TRUE: Send modulated word FALSE: Send unmodulated word
Returns
handle of the running command returned by the command scheduler
References PLATFORM_RADIO_TX_TEST_MODULATED_WORD, PLATFORM_RADIO_TX_TEST_UNMODULATED_WORD, rfCoreTxTestCmdCallback(), and sTxTestCmd.
Referenced by otPlatDiagRadioToneStart().
rfCoreErrorCallback()
static void rfCoreErrorCallback (RF_Handle aHandle, RF_CmdHandle aCmdHandle, RF_EventMask aEvents) static
Default error callback for RF Driver.
Errors are unlikely, and fatal.
Referenced by otPlatRadioEnable().
rfCoreDiagChannelDisable()
void rfCoreDiagChannelDisable (uint8_t aChannel)
Function documented in radio.h
References otPlatRadioReceive(), and sDisableChannel.
rfCoreDiagChannelEnable()
void rfCoreDiagChannelEnable (uint8_t aChannel)
Function documented in radio.h
References otPlatRadioReceive(), and sDisableChannel.
platformRadioInit()
void platformRadioInit (void)
Function documented in system.h
References otPlatEntropyGet(), platformRadio_phyState_Disabled, rfCoreInitBufs(), rfCoreInitReceiveParams(), rfCoreInitSetupCmd(), seedRandom, and sState.
otPlatRadioEnable()
otError otPlatRadioEnable (otInstance * aInstance)
Function documented in platform/radio.h
References platformRadio_phyState_Disabled, platformRadio_phyState_Sleep, rfCoreErrorCallback(), sRadioSetupCmd, sRfHandle, sRfObject, and sState.
otPlatRadioIsEnabled()
bool otPlatRadioIsEnabled (otInstance * aInstance)
Function documented in platform/radio.h
References platformRadio_phyState_Disabled, and sState.
otPlatRadioDisable()
otError otPlatRadioDisable (otInstance * aInstance)
Function documented in platform/radio.h
References platformRadio_phyState_Disabled, platformRadio_phyState_Sleep, sRfHandle, and sState.
otPlatRadioGetCcaEnergyDetectThreshold()
otError otPlatRadioGetCcaEnergyDetectThreshold (otInstance * aInstance, int8_t * aThreshold)
Function documented in platform/radio.h
otPlatRadioSetCcaEnergyDetectThreshold()
otError otPlatRadioSetCcaEnergyDetectThreshold (otInstance * aInstance, int8_t aThreshold)
Function documented in platform/radio.h
otPlatRadioEnergyScan()
otError otPlatRadioEnergyScan (otInstance * aInstance, uint8_t aScanChannel, uint16_t aScanDuration)
Function documented in platform/radio.h
References platformRadio_phyState_EdScan, platformRadio_phyState_Receive, platformRadio_phyState_Sleep, rfCoreExecuteAbortCmd(), rfCoreSendEdScanCmd(), sReceiveCmd, sReceiveCmdHandle, sRfHandle, and sState.
otPlatRadioSetTransmitPower()
otError otPlatRadioSetTransmitPower (otInstance * aInstance, int8_t aPower)
Function documented in platform/radio.h
References rfCoreSetTransmitPower(), and sReqTxPower.
otPlatRadioGetTransmitPower()
otError otPlatRadioGetTransmitPower (otInstance * aInstance, int8_t * aPower)
Function documented in platform/radio.h
References sRfHandle.
otPlatRadioReceive()
otError otPlatRadioReceive (otInstance * aInstance, uint8_t aChannel)
Function documented in platform/radio.h
References platformRadio_phyState_Receive, platformRadio_phyState_Sleep, rfCoreExecuteAbortCmd(), rfCoreSendReceiveCmd(), rfCoreSetTransmitPower(), sDisableChannel, sReceiveCmd, sReceiveCmdHandle, sReqTxPower, sRfHandle, and sState.
Referenced by rfCoreDiagChannelDisable(), and rfCoreDiagChannelEnable().
otPlatRadioSleep()
otError otPlatRadioSleep (otInstance * aInstance)
Function documented in platform/radio.h
References platformRadio_phyState_Receive, platformRadio_phyState_Sleep, radioSignal(), RF_EVENT_SLEEP_YIELD, rfCoreExecuteAbortCmd(), sReceiveCmd, sReceiveCmdHandle, sRfHandle, and sState.
otPlatRadioGetTransmitBuffer()
otRadioFrame* otPlatRadioGetTransmitBuffer (otInstance * aInstance)
Function documented in platform/radio.h
References sTransmitFrame.
otPlatRadioTransmit()
otError otPlatRadioTransmit (otInstance * aInstance, otRadioFrame * aFrame)
Function documented in platform/radio.h
References platformRadio_phyState_Receive, platformRadio_phyState_Transmit, rfCoreSendTransmitCmd(), sRfHandle, sState, and sTransmitCmdHandle.
otPlatRadioGetRssi()
int8_t otPlatRadioGetRssi (otInstance * aInstance)
Function documented in platform/radio.h
References sRfStats.
otPlatRadioGetCaps()
otRadioCaps otPlatRadioGetCaps (otInstance * aInstance)
Function documented in platform/radio.h
otPlatRadioEnableSrcMatch()
void otPlatRadioEnableSrcMatch (otInstance * aInstance, bool aEnable)
Function documented in platform/radio.h
References rfCoreModifyRxAutoPend(), sReceiveCmd, and sRfHandle.
otPlatRadioAddSrcMatchShortEntry()
otError otPlatRadioAddSrcMatchShortEntry (otInstance * aInstance, const uint16_t aShortAddress)
Function documented in platform/radio.h
References PLATFORM_RADIO_SRC_MATCH_NONE, platformRadio_address_short, rfCoreFindEmptyShortSrcMatchIdx(), rfCoreFindShortSrcMatchIdx(), rfCoreModifySourceMatchEntry(), sReceiveCmd, sRfHandle, and sSrcMatchShortData.
otPlatRadioClearSrcMatchShortEntry()
otError otPlatRadioClearSrcMatchShortEntry (otInstance * aInstance, const uint16_t aShortAddress)
Function documented in platform/radio.h
References PLATFORM_RADIO_SRC_MATCH_NONE, platformRadio_address_short, rfCoreFindShortSrcMatchIdx(), rfCoreModifySourceMatchEntry(), sReceiveCmd, sRfHandle, and sSrcMatchShortData.
otPlatRadioAddSrcMatchExtEntry()
otError otPlatRadioAddSrcMatchExtEntry (otInstance * aInstance, const otExtAddress * aExtAddress)
Function documented in platform/radio.h
References PLATFORM_RADIO_SRC_MATCH_NONE, platformRadio_address_ext, rfCoreFindEmptyExtSrcMatchIdx(), rfCoreFindExtSrcMatchIdx(), rfCoreModifySourceMatchEntry(), sReceiveCmd, sRfHandle, and sSrcMatchExtData.
otPlatRadioClearSrcMatchExtEntry()
otError otPlatRadioClearSrcMatchExtEntry (otInstance * aInstance, const otExtAddress * aExtAddress)
Function documented in platform/radio.h
References PLATFORM_RADIO_SRC_MATCH_NONE, platformRadio_address_ext, rfCoreFindExtSrcMatchIdx(), rfCoreModifySourceMatchEntry(), sReceiveCmd, sRfHandle, and sSrcMatchExtData.
otPlatRadioClearSrcMatchShortEntries()
void otPlatRadioClearSrcMatchShortEntries (otInstance * aInstance)
Function documented in platform/radio.h
References PLATFORM_RADIO_SHORTADD_SRC_MATCH_NUM, platformRadio_address_short, platformRadio_phyState_Receive, platformRadio_phyState_Transmit, rfCoreModifySourceMatchEntry(), sRfHandle, sSrcMatchShortData, and sState.
otPlatRadioClearSrcMatchExtEntries()
void otPlatRadioClearSrcMatchExtEntries (otInstance * aInstance)
Function documented in platform/radio.h
References PLATFORM_RADIO_EXTADD_SRC_MATCH_NUM, platformRadio_address_ext, platformRadio_phyState_Receive, platformRadio_phyState_Transmit, rfCoreModifySourceMatchEntry(), sRfHandle, sSrcMatchExtData, and sState.
otPlatRadioGetPromiscuous()
bool otPlatRadioGetPromiscuous (otInstance * aInstance)
Function documented in platform/radio.h
References sReceiveCmd.
otPlatRadioSetPromiscuous()
void otPlatRadioSetPromiscuous (otInstance * aInstance, bool aEnable)
Function documented in platform/radio.h
References rfCoreModifyRxFrameFilter(), sReceiveCmd, and sRfHandle.
otPlatRadioGetIeeeEui64()
void otPlatRadioGetIeeeEui64 (otInstance * aInstance, uint8_t * aIeeeEui64)
Function documented in platform/radio.h
otPlatRadioSetPanId()
void otPlatRadioSetPanId (otInstance * aInstance, uint16_t aPanid)
Function documented in platform/radio.h
Note
it is entirely possible for this function to fail, but there is no valid way to return that error since the funciton prototype was changed.
References platformRadio_phyState_Receive, platformRadio_phyState_Transmit, rfCoreExecuteAbortCmd(), rfCoreSendReceiveCmd(), sReceiveCmd, sReceiveCmdHandle, sRfHandle, and sState.
otPlatRadioSetExtendedAddress()
void otPlatRadioSetExtendedAddress (otInstance * aInstance, const otExtAddress * aAddress)
Function documented in platform/radio.h
Note
it is entirely possible for this function to fail, but there is no valid way to return that error since the function prototype was changed.
References platformRadio_phyState_Receive, platformRadio_phyState_Transmit, rfCoreExecuteAbortCmd(), rfCoreSendReceiveCmd(), sReceiveCmd, sReceiveCmdHandle, sRfHandle, and sState.
otPlatRadioSetShortAddress()
void otPlatRadioSetShortAddress (otInstance * aInstance, uint16_t aAddress)
Function documented in platform/radio.h
Note
it is entirely possible for this function to fail, but there is no valid way to return that error since the funciton prototype was changed.
References platformRadio_phyState_Receive, platformRadio_phyState_Transmit, rfCoreExecuteAbortCmd(), rfCoreSendReceiveCmd(), sReceiveCmd, sReceiveCmdHandle, sRfHandle, and sState.
otPlatDiagRadioToneStart()
otError otPlatDiagRadioToneStart (otInstance * aInstance, bool aModulated)
Function documented in platform/radio.h
References platformRadio_phyState_Receive, platformRadio_phyState_Sleep, rfCoreExecuteAbortCmd(), rfCoreSendTxTestCmd(), sReceiveCmdHandle, sRfHandle, sState, and sTxTestCmdHandle.
otPlatDiagRadioToneStop()
otError otPlatDiagRadioToneStop (otInstance * aInstance)
Function documented in platform/radio.h
References platformRadio_phyState_Receive, platformRadio_phyState_Sleep, rfCoreExecuteAbortCmd(), rfCoreSendReceiveCmd(), sReceiveCmdHandle, sRfHandle, sState, and sTxTestCmdHandle.
platformRadioProcessTransmitDone()
static void platformRadioProcessTransmitDone (otInstance * aInstance, otRadioFrame * aTransmitFrame, otRadioFrame * aAckFrame, otError aTransmitError) static
References otPlatDiagModeGet(), and sTransmitCmd.
Referenced by handleTxState().
platformRadioProcessReceiveDone()
static void platformRadioProcessReceiveDone (otInstance * aInstance, otRadioFrame * aReceiveFrame, otError aReceiveError) static
References otPlatDiagModeGet().
Referenced by handleRxDataFinish().
releaseQueueEntry()
static void releaseQueueEntry (struct rx_queue_info * p) static
Release an entry in the RX buffer list
Referenced by releaseAndNext().
nextQueueEntry()
static void nextQueueEntry (struct rx_queue_info * p) static
Given a queue entry, give the next queue entry.
Referenced by ackSearchRxQueue(), handleRxAckFinish(), handleRxDataFinish(), processRxQueue(), and releaseAndNext().
releaseAndNext()
static void releaseAndNext (struct rx_queue_info * p) static
Release the current entry and move to the next entry in the rx queue.
References nextQueueEntry(), and releaseQueueEntry().
Referenced by handleRxDataFinish(), handleTxState(), and processRxQueue().
populateReceiveFrame()
static otError populateReceiveFrame (struct rx_queue_info * p) static
References IEEE802154_FRAME_PENDING_MASK, RF_NUM_RAT_TICKS_IN_1_US, sReceiveCmd, sSrcMatchExtData, and sSrcMatchShortData.
Referenced by handleRxAckFinish(), and handleRxDataFinish().
handleRxDataFinish()
static void handleRxDataFinish (struct rx_queue_info * p) static
An RX queue entry is in the finished state, process it.
References IEEE802154_ACK_REQUEST, IEEE802154_DSN_OFFSET, IEEE802154_FRAME_TYPE_ACK, IEEE802154_FRAME_TYPE_MASK, nextQueueEntry(), platformRadio_phyState_Transmit, platformRadioProcessReceiveDone(), populateReceiveFrame(), releaseAndNext(), RF_EVENT_RX_ACK_DONE, and sState.
Referenced by processRxQueue().
handleRxAckFinish()
static otRadioFrame* handleRxAckFinish (struct rx_queue_info * p, uint8_t ackDsn) static
An RX queue entry is in the finished state, process it.
References IEEE802154_DSN_OFFSET, IEEE802154_FRAME_TYPE_ACK, IEEE802154_FRAME_TYPE_MASK, nextQueueEntry(), platformRadio_phyState_Transmit, populateReceiveFrame(), and sState.
Referenced by ackSearchRxQueue().
clearRxQueue()
static void clearRxQueue (void) static
Empties the rx queue, regardless of the current state of the entries.
References sRxDataQueue.
Referenced by platformRadioProcess().
processRxQueue()
static void processRxQueue (otInstance * aInstance, unsigned int events) static
Scan through the RX queue, looking for completed entries.
References handleRxDataFinish(), nextQueueEntry(), releaseAndNext(), and sRxDataQueue.
Referenced by platformRadioProcess().
ackSearchRxQueue()
static otRadioFrame* ackSearchRxQueue (struct rx_queue_info * rqi, unsigned int events, uint8_t ackDsn) static
References handleRxAckFinish(), and nextQueueEntry().
Referenced by handleTxState().
handleTxState()
static void handleTxState (otInstance * aInstance, unsigned int events) static
Handle events in the TX state.
References ackSearchRxQueue(), IEEE802154_ACK_REQUEST, IEEE802154_DSN_OFFSET, platformRadio_phyState_Receive, platformRadioProcessTransmitDone(), releaseAndNext(), sRxDataQueue, sState, sTransmitCmd, sTransmitError, and sTransmitFrame.
Referenced by platformRadioProcess().
platformRadioProcess()
void platformRadioProcess (otInstance * aInstance, uintptr_t arg)
Function documented in system.h This is called from the main process loop.
References clearRxQueue(), handleTxState(), IEEE802154_ACK_REQUEST, PLATFORM_RADIO_INVALID_RSSI, platformRadio_phyState_Disabled, platformRadio_phyState_EdScan, platformRadio_phyState_Receive, platformRadio_phyState_Sleep, platformRadio_phyState_Transmit, processRxQueue(), RF_EVENT_BUF_FULL, RF_EVENT_ED_SCAN_DONE, RF_EVENT_RX_ACK_DONE, RF_EVENT_RX_CMD_PREEMPTED, RF_EVENT_RX_CMD_STOP, RF_EVENT_RX_DONE, RF_EVENT_SLEEP_YIELD, RF_EVENT_TX_CMD_PREEMPTED, RF_EVENT_TX_DONE, rfCoreSendReceiveCmd(), sCsmaBackoffCmd, sEdScanCmd, sReceiveCmd, sReceiveCmdHandle, sRfHandle, sState, sTransmitCmd, and sTransmitRxAckCmd.
Variable Documentation
sState
volatile platformRadio_phyState sState static
Referenced by handleRxAckFinish(), handleRxDataFinish(), handleTxState(), otPlatDiagRadioToneStart(), otPlatDiagRadioToneStop(), otPlatRadioClearSrcMatchExtEntries(), otPlatRadioClearSrcMatchShortEntries(), otPlatRadioDisable(), otPlatRadioEnable(), otPlatRadioEnergyScan(), otPlatRadioIsEnabled(), otPlatRadioReceive(), otPlatRadioSetExtendedAddress(), otPlatRadioSetPanId(), otPlatRadioSetShortAddress(), otPlatRadioSleep(), otPlatRadioTransmit(), platformRadioInit(), platformRadioProcess(), and rfCoreSetTransmitPower().
sDisableChannel
bool sDisableChannel = false static
Referenced by otPlatRadioReceive(), rfCoreDiagChannelDisable(), and rfCoreDiagChannelEnable().
sTransmitRetryCount
volatile unsigned int sTransmitRetryCount = 0 static
Referenced by handleTxAck(), and rfCoreSendTransmitCmd().
sRadioSetupCmd
volatile rfc_CMD_RADIO_SETUP_t sRadioSetupCmd static
Referenced by otPlatRadioEnable(), and rfCoreInitSetupCmd().
sModifyReceiveFilterCmd
volatile rfc_CMD_IEEE_MOD_FILT_t sModifyReceiveFilterCmd static
Referenced by rfCoreModifyRxAutoPend(), and rfCoreModifyRxFrameFilter().
sModifyReceiveSrcMatchCmd
volatile rfc_CMD_IEEE_MOD_SRC_MATCH_t sModifyReceiveSrcMatchCmd static
Referenced by rfCoreModifySourceMatchEntry().
sEdScanCmd
volatile rfc_CMD_IEEE_ED_SCAN_t sEdScanCmd static
Referenced by platformRadioProcess(), and rfCoreSendEdScanCmd().
sTxTestCmd
volatile rfc_CMD_TX_TEST_t sTxTestCmd static
Referenced by rfCoreSendTxTestCmd().
sReceiveCmd
volatile rfc_CMD_IEEE_RX_t sReceiveCmd static
Referenced by otPlatRadioAddSrcMatchExtEntry(), otPlatRadioAddSrcMatchShortEntry(), otPlatRadioClearSrcMatchExtEntry(), otPlatRadioClearSrcMatchShortEntry(), otPlatRadioEnableSrcMatch(), otPlatRadioEnergyScan(), otPlatRadioGetPromiscuous(), otPlatRadioGetReceiveSensitivity(), otPlatRadioReceive(), otPlatRadioSetExtendedAddress(), otPlatRadioSetPanId(), otPlatRadioSetPromiscuous(), otPlatRadioSetShortAddress(), otPlatRadioSleep(), platformRadioProcess(), populateReceiveFrame(), rfCoreInitReceiveParams(), rfCoreModifyRxAutoPend(), rfCoreModifyRxFrameFilter(), rfCoreRxCallback(), rfCoreSendReceiveCmd(), and rfCoreSetTransmitPower().
sCsmaBackoffCmd
volatile rfc_CMD_IEEE_CSMA_t sCsmaBackoffCmd static
Referenced by handleTxAck(), platformRadioProcess(), rfCoreSendTransmitCmd(), rfCoreTxCallback(), and startTransmit().
sTransmitCmd
volatile rfc_CMD_IEEE_TX_t sTransmitCmd static
Referenced by handleTxAck(), handleTxState(), platformRadioProcess(), platformRadioProcessTransmitDone(), rfCoreSendTransmitCmd(), and rfCoreTxCallback().
sTransmitRxAckCmd
volatile rfc_CMD_IEEE_RX_ACK_t sTransmitRxAckCmd static
Referenced by handleTxAck(), platformRadioProcess(), and rfCoreSendTransmitCmd().
sSrcMatchExtData
volatile ext_src_match_data_t sSrcMatchExtData static
Referenced by otPlatRadioAddSrcMatchExtEntry(), otPlatRadioClearSrcMatchExtEntries(), otPlatRadioClearSrcMatchExtEntry(), populateReceiveFrame(), rfCoreFindEmptyExtSrcMatchIdx(), rfCoreFindExtSrcMatchIdx(), and rfCoreInitReceiveParams().
sSrcMatchShortData
volatile short_src_match_data_t sSrcMatchShortData static
Referenced by otPlatRadioAddSrcMatchShortEntry(), otPlatRadioClearSrcMatchShortEntries(), otPlatRadioClearSrcMatchShortEntry(), populateReceiveFrame(), rfCoreFindEmptyShortSrcMatchIdx(), rfCoreFindShortSrcMatchIdx(), and rfCoreInitReceiveParams().
sRfStats
volatile rfc_ieeeRxOutput_t sRfStats static
Referenced by otPlatRadioGetRssi(), and rfCoreInitReceiveParams().
sRxBuf0
uint8_t sRxBuf0[RX_BUF_SIZE] static
Referenced by rfCoreInitBufs().
sRxBuf1
uint8_t sRxBuf1[RX_BUF_SIZE] static
Referenced by rfCoreInitBufs().
sRxBuf2
uint8_t sRxBuf2[RX_BUF_SIZE] static
Referenced by rfCoreInitBufs().
sRxBuf3
uint8_t sRxBuf3[RX_BUF_SIZE] static
Referenced by rfCoreInitBufs().
sRxDataQueue
dataQueue_t sRxDataQueue = { 0 } static
Referenced by clearRxQueue(), handleTxState(), processRxQueue(), rfCoreInitBufs(), and rfCoreInitReceiveParams().
sTransmitFrame
otRadioFrame sTransmitFrame static
Referenced by handleTxState(), and otPlatRadioGetTransmitBuffer().
sTransmitError
otError sTransmitError static
Referenced by handleTxState().
sTransmitPsdu
uint8_t sTransmitPsdu[OT_RADIO_FRAME_MAX_SIZE] static
Referenced by rfCoreInitBufs().
sRfObject
RF_Object sRfObject static
Referenced by otPlatRadioEnable().
sRfHandle
RF_Handle sRfHandle static
Referenced by otPlatDiagRadioToneStart(), otPlatDiagRadioToneStop(), otPlatRadioAddSrcMatchExtEntry(), otPlatRadioAddSrcMatchShortEntry(), otPlatRadioClearSrcMatchExtEntries(), otPlatRadioClearSrcMatchExtEntry(), otPlatRadioClearSrcMatchShortEntries(), otPlatRadioClearSrcMatchShortEntry(), otPlatRadioDisable(), otPlatRadioEnable(), otPlatRadioEnableSrcMatch(), otPlatRadioEnergyScan(), otPlatRadioGetTransmitPower(), otPlatRadioReceive(), otPlatRadioSetExtendedAddress(), otPlatRadioSetPanId(), otPlatRadioSetPromiscuous(), otPlatRadioSetShortAddress(), otPlatRadioSleep(), otPlatRadioTransmit(), platformRadioProcess(), rfCoreRxCallback(), and rfCoreSetTransmitPower().
sReceiveCmdHandle
RF_CmdHandle sReceiveCmdHandle static
Referenced by otPlatDiagRadioToneStart(), otPlatDiagRadioToneStop(), otPlatRadioEnergyScan(), otPlatRadioReceive(), otPlatRadioSetExtendedAddress(), otPlatRadioSetPanId(), otPlatRadioSetShortAddress(), otPlatRadioSleep(), platformRadioProcess(), rfCoreRxCallback(), and rfCoreSetTransmitPower().
sTransmitCmdHandle
RF_CmdHandle sTransmitCmdHandle static
Referenced by handleTxAck(), and otPlatRadioTransmit().
sTxTestCmdHandle
RF_CmdHandle sTxTestCmdHandle static
Referenced by otPlatDiagRadioToneStart(), and otPlatDiagRadioToneStop().
seedRandom
uint16_t seedRandom static
Referenced by platformRadioInit(), rfCoreSendTransmitCmd(), and rfCoreTxCallback().
sReqTxPower
int8_t sReqTxPower = TIOP_CONFIG_TX_POWER static
Value requested in dBm from the upper layers on the last call to otPlatRadioSetTransmitPower.
Referenced by otPlatRadioReceive(), and otPlatRadioSetTransmitPower().
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale