TI-OpenThread: nvocmp.c File Reference
CC1352P_4_LAUNCHXL/thread/door_lock/platform/nv/nvocmp.c File Reference
#include <string.h>
#include <ti/sysbios/gates/GateMutexPri.h>
#include "nvocmp.h"
#include "crc.h"
#include <driverlib/vims.h>
Macros
#define DEFAULT_COMPACTHDR {NVOCMP_NULLOFFSET, NVOCMP_NULLPAGE, NVOCMP_SIGNATURE};
#define FLASH_PAGE_SIZE (1 << PAGE_SIZE_LSHIFT)
#define NVOCMP_ACTIVEIDBIT 0x2
#define NVOCMP_ADDPAGE(p, n) (((p) + (n)) % NVOCMP_NVSIZE)
#define NVOCMP_ALERT(cond, message)
#define NVOCMP_ALLACTIVE 0x3
#define NVOCMP_ASSERT(cond, message)
#define NVOCMP_ASSERT1(cond) {if(!cond) while(1);}
#define NVOCMP_CMPRID(s, i, b)
#define NVOCMP_CMPSPACE 12
#define NVOCMP_COMPACTHDRLEN (sizeof(NVOCMP_compactHdr_t))
#define NVOCMP_COMPACTHDRLEN (sizeof(NVOCMP_compactHdr_t))
#define NVOCMP_COMPMODEOFS 6
#define NVOCMP_COMPR 0
#define NVOCMP_CRCONREAD 1
#define NVOCMP_DECPAGE(p) NVOCMP_ADDPAGE(p,NVOCMP_NVSIZE - 1)
#define NVOCMP_ERASEDBYTE 0xFF
#define NVOCMP_ERASEDWORD 0xFFFFFFFF
#define NVOCMP_FASTCP 1
#define NVOCMP_FASTITEM 0
#define NVOCMP_FASTOFF 1
#define NVOCMP_FINDHMASK 0xF0
#define NVOCMP_FINDLMASK 0x0F
#define NVOCMP_FLASHACCESS(err)
#define NVOCMP_FLASHOFFSET(pg, ofs) ((uint32_t)(((pg) << PAGE_SIZE_LSHIFT) + (ofs)))
#define NVOCMP_FOLLOWBIT 0x4
#define NVOCMP_GPRAM
#define NVOCMP_HDRCRCINC 5
#define NVOCMP_HDRLE 0
#define NVOCMP_HDRSIGOFS 6
#define NVOCMP_HDRVLDOFS 5
#define NVOCMP_INCPAGE(p) NVOCMP_ADDPAGE(p,1)
#define NVOCMP_INVALIDSUBID 0xFFFF
#define NVOCMP_ITEMHDREND (NVOCMP_ITEMHDRLEN - 1)
#define NVOCMP_ITEMHDRLEN 7
#define NVOCMP_LOCK() int32_t key = GateMutexPri_enter(NVOCMP_gMutexPri);
#define NVOCMP_MAXCYCLE 0xFE
#define NVOCMP_MAXITEMID 0x03FF
#define NVOCMP_MAXLEN 0x0FFF
#define NVOCMP_MAXSUBID 0x03FF
#define NVOCMP_MAXSYSID 0x003F
#define NVOCMP_MIGRATE_DISABLED
#define NVOCMP_MINCYCLE 0x01
#define NVOCMP_NOCOMPHDR 3
#define NVOCMP_NULLOFFSET 0xFFFF
#define NVOCMP_NULLPAGE 0xFF
#define NVOCMP_NVONEP 1
#define NVOCMP_NVPAGES 2
#define NVOCMP_NVS_INDEX 0
#define NVOCMP_NVSIZE NVOCMP_size
#define NVOCMP_NVTWOP 2
#define NVOCMP_NWSAMEITEM 0
#define NVOCMP_ONEBYTE 1
#define NVOCMP_PGCDONE 0xFC
#define NVOCMP_PGCDST 0xFE
#define NVOCMP_PGCSRC 0xF8
#define NVOCMP_PGDATAEND (FLASH_PAGE_SIZE - 1)
#define NVOCMP_PGDATALEN (FLASH_PAGE_SIZE - NVOCMP_PGDATAOFS)
#define NVOCMP_PGDATAOFS (NVOCMP_PGHDRLEN + NVOCMP_NOCOMPHDR*NVOCMP_COMPACTHDRLEN)
#define NVOCMP_PGHDRCYC 1
#define NVOCMP_PGHDRLEN (sizeof(NVOCMP_pageHdr_t))
#define NVOCMP_PGHDROFS 0
#define NVOCMP_PGHDRPST 0
#define NVOCMP_PGHDRSIG 3
#define NVOCMP_PGHDRVER 2
#define NVOCMP_PGMODEBIT 0x04
#define NVOCMP_PGNORMAL 0xFF
#define NVOCMP_SIGNATURE 0x96
#define NVOCMP_SMALLITEM 12
#define NVOCMP_SOMEINACTIVE 0x0
#define NVOCMP_UNLOCK(err)
#define NVOCMP_VALIDIDBIT 0x1
#define NVOCMP_VERSION 0x03
#define NVOCMP_XFERBLKMAX 32
#define NVOCTP_PGACTIVE 0xA5
#define NVOCTP_PGDATAOFS NVOCMP_PGHDRLEN
#define NVOCTP_PGXFER 0x24
#define NVOCTP_SIGNATURE 0x96
#define NVOCTP_VERSION 0x02
#define PAGE_SIZE_LSHIFT 13
#define RAM_BUFFER_ADDRESS (uint8_t *)0x11000000
#define THISPAGEHDR 0
#define XSRCENDHDR 2
#define XSRCSTARTHDR 1
Typedefs
typedef uint8_t cmpIH_t[NVOCMP_ITEMHDRLEN]
typedef enum NVOCMP_compactStatus NVOCMP_compactStatus_t
typedef enum NVOCMP_initAction NVOCMP_initAction_t
typedef enum NVOCMP_pageState NVOCMP_pageState_t
typedef enum NVOCMP_writeMode NVOCMP_writeMode_t
Enumerations
enum {
NVOCMP_FINDANY = 0x00, NVOCMP_FINDSYSID, NVOCMP_FINDITMID, NVOCMP_FINDSTRICT,
NVOCMP_FINDCONTENT = 0x10
}
enum NVOCMP_compactStatus {
NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03,
NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02,
NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01,
NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00,
NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10,
NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03,
NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02,
NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01,
NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00,
NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10,
NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03,
NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02,
NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01,
NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00,
NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10,
NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03,
NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02,
NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01,
NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00,
NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10,
NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03,
NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02,
NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01,
NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00,
NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10,
NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03,
NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02,
NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01,
NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00,
NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10,
NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03,
NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02,
NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01,
NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00,
NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10,
NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03,
NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02,
NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01,
NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00,
NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10,
NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03,
NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02,
NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01,
NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00,
NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10,
NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03,
NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02,
NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01,
NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00,
NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10,
NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03,
NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02,
NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01,
NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00,
NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10,
NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03,
NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02,
NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01,
NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00,
NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10,
NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03,
NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02,
NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01,
NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00,
NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10,
NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03,
NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02,
NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01,
NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00,
NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10,
NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03,
NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02,
NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01,
NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00,
NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10,
NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03,
NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02,
NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01,
NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00,
NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10,
NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02, NVOCMP_COMPACT_BOTHDOE = 0x03,
NVOCMP_COMPACT_FAILURE = 0x10, NVOCMP_COMPACT_SUCCESS = 0x00, NVOCMP_COMPACT_SRCDONE = 0x01, NVOCMP_COMPACT_DSTDONE = 0x02,
NVOCMP_COMPACT_BOTHDOE = 0x03, NVOCMP_COMPACT_FAILURE = 0x10
}
enum NVOCMP_initAction {
NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE,
NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0,
NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN,
NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME,
NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE,
NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT,
NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN,
NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE,
NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0,
NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN,
NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME,
NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE,
NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT,
NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN,
NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE,
NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0,
NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN,
NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME,
NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE,
NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT,
NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN,
NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE,
NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0,
NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN,
NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME,
NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE,
NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT,
NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN,
NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE,
NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0,
NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN,
NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME,
NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE,
NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT,
NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN,
NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE,
NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0,
NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN,
NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME,
NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE,
NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT,
NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN,
NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE,
NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0,
NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN,
NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME,
NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE,
NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT,
NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN,
NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE,
NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0,
NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN,
NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME,
NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE,
NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT,
NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN,
NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE,
NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0,
NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN,
NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME,
NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE,
NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT,
NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN,
NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE,
NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0,
NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN,
NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME,
NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE,
NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT,
NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN,
NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE,
NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0,
NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN,
NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME,
NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE,
NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT,
NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN,
NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE,
NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0,
NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN,
NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME,
NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE,
NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT,
NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN,
NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE,
NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0,
NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN,
NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME,
NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE,
NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT,
NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN,
NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE,
NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0,
NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN,
NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME,
NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE,
NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT,
NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN,
NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE,
NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0,
NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN,
NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME,
NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE,
NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT,
NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN,
NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE,
NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0,
NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN,
NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME,
NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE,
NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT,
NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN,
NVOCMP_NORMAL_INIT = 0, NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE,
NVOCMP_FORCE_CLEAN, NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN, NVOCMP_NORMAL_INIT = 0,
NVOCMP_NORMAL_RESUME, NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE, NVOCMP_FORCE_CLEAN,
NVOCMP_NORMAL_MIGRATE, NVOCMP_ERROR_UNKNOWN
}
enum NVOCMP_pageState {
NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C,
NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF,
NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78,
NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE,
NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70,
NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E,
NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00,
NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C,
NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF,
NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78,
NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE,
NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70,
NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E,
NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00,
NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C,
NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF,
NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78,
NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE,
NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70,
NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E,
NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00,
NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C,
NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF,
NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78,
NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE,
NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70,
NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E,
NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00,
NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C,
NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF,
NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78,
NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE,
NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70,
NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E,
NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00,
NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C,
NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF,
NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78,
NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE,
NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70,
NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E,
NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00,
NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C,
NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF,
NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78,
NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE,
NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70,
NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E,
NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00,
NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C,
NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF,
NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78,
NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE,
NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70,
NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E,
NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00,
NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C,
NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF,
NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78,
NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE,
NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70,
NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E,
NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00,
NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C,
NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF,
NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78,
NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE,
NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70,
NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E,
NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00,
NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C,
NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF,
NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78,
NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE,
NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70,
NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E,
NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00,
NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C,
NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF,
NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78,
NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE,
NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70,
NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E,
NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00,
NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C,
NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF,
NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78,
NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE,
NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70,
NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E,
NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00,
NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C,
NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF,
NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78,
NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE,
NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70,
NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E,
NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00,
NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C,
NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF,
NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78,
NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE,
NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70,
NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E,
NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00,
NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C,
NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF,
NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78,
NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE,
NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70,
NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E,
NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00,
NVOCMP_PGNACT = 0xFF, NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C,
NVOCMP_PGFULL = 0x78, NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00, NVOCMP_PGNACT = 0xFF,
NVOCMP_PGXDST = 0xFE, NVOCMP_PGRDY = 0x7E, NVOCMP_PGACT = 0x7C, NVOCMP_PGFULL = 0x78,
NVOCMP_PGXSRC = 0x70, NVOCMP_PGNDEF = 0x00
}
enum NVOCMP_writeMode {
NVOCMP_WRITE = 0, NVOCMP_CREATE, NVOCMP_UPDATE, NVOCMP_WRITE = 0,
NVOCMP_CREATE, NVOCMP_UPDATE, NVOCMP_WRITE = 0, NVOCMP_CREATE,
NVOCMP_UPDATE, NVOCMP_WRITE = 0, NVOCMP_CREATE, NVOCMP_UPDATE,
NVOCMP_WRITE = 0, NVOCMP_CREATE, NVOCMP_UPDATE, NVOCMP_WRITE = 0,
NVOCMP_CREATE, NVOCMP_UPDATE, NVOCMP_WRITE = 0, NVOCMP_CREATE,
NVOCMP_UPDATE, NVOCMP_WRITE = 0, NVOCMP_CREATE, NVOCMP_UPDATE,
NVOCMP_WRITE = 0, NVOCMP_CREATE, NVOCMP_UPDATE, NVOCMP_WRITE = 0,
NVOCMP_CREATE, NVOCMP_UPDATE, NVOCMP_WRITE = 0, NVOCMP_CREATE,
NVOCMP_UPDATE, NVOCMP_WRITE = 0, NVOCMP_CREATE, NVOCMP_UPDATE,
NVOCMP_WRITE = 0, NVOCMP_CREATE, NVOCMP_UPDATE, NVOCMP_WRITE = 0,
NVOCMP_CREATE, NVOCMP_UPDATE, NVOCMP_WRITE = 0, NVOCMP_CREATE,
NVOCMP_UPDATE, NVOCMP_WRITE = 0, NVOCMP_CREATE, NVOCMP_UPDATE,
NVOCMP_WRITE = 0, NVOCMP_CREATE, NVOCMP_UPDATE, NVOCMP_WRITE = 0,
NVOCMP_CREATE, NVOCMP_UPDATE, NVOCMP_WRITE = 0, NVOCMP_CREATE,
NVOCMP_UPDATE, NVOCMP_WRITE = 0, NVOCMP_CREATE, NVOCMP_UPDATE,
NVOCMP_WRITE = 0, NVOCMP_CREATE, NVOCMP_UPDATE, NVOCMP_WRITE = 0,
NVOCMP_CREATE, NVOCMP_UPDATE, NVOCMP_WRITE = 0, NVOCMP_CREATE,
NVOCMP_UPDATE, NVOCMP_WRITE = 0, NVOCMP_CREATE, NVOCMP_UPDATE,
NVOCMP_WRITE = 0, NVOCMP_CREATE, NVOCMP_UPDATE, NVOCMP_WRITE = 0,
NVOCMP_CREATE, NVOCMP_UPDATE, NVOCMP_WRITE = 0, NVOCMP_CREATE,
NVOCMP_UPDATE, NVOCMP_WRITE = 0, NVOCMP_CREATE, NVOCMP_UPDATE,
NVOCMP_WRITE = 0, NVOCMP_CREATE, NVOCMP_UPDATE, NVOCMP_WRITE = 0,
NVOCMP_CREATE, NVOCMP_UPDATE, NVOCMP_WRITE = 0, NVOCMP_CREATE,
NVOCMP_UPDATE, NVOCMP_WRITE = 0, NVOCMP_CREATE, NVOCMP_UPDATE,
NVOCMP_WRITE = 0, NVOCMP_CREATE, NVOCMP_UPDATE, NVOCMP_WRITE = 0,
NVOCMP_CREATE, NVOCMP_UPDATE, NVOCMP_WRITE = 0, NVOCMP_CREATE,
NVOCMP_UPDATE, NVOCMP_WRITE = 0, NVOCMP_CREATE, NVOCMP_UPDATE,
NVOCMP_WRITE = 0, NVOCMP_CREATE, NVOCMP_UPDATE, NVOCMP_WRITE = 0,
NVOCMP_CREATE, NVOCMP_UPDATE, NVOCMP_WRITE = 0, NVOCMP_CREATE,
NVOCMP_UPDATE, NVOCMP_WRITE = 0, NVOCMP_CREATE, NVOCMP_UPDATE,
NVOCMP_WRITE = 0, NVOCMP_CREATE, NVOCMP_UPDATE, NVOCMP_WRITE = 0,
NVOCMP_CREATE, NVOCMP_UPDATE, NVOCMP_WRITE = 0, NVOCMP_CREATE,
NVOCMP_UPDATE, NVOCMP_WRITE = 0, NVOCMP_CREATE, NVOCMP_UPDATE,
NVOCMP_WRITE = 0, NVOCMP_CREATE, NVOCMP_UPDATE, NVOCMP_WRITE = 0,
NVOCMP_CREATE, NVOCMP_UPDATE, NVOCMP_WRITE = 0, NVOCMP_CREATE,
NVOCMP_UPDATE, NVOCMP_WRITE = 0, NVOCMP_CREATE, NVOCMP_UPDATE,
NVOCMP_WRITE = 0, NVOCMP_CREATE, NVOCMP_UPDATE, NVOCMP_WRITE = 0,
NVOCMP_CREATE, NVOCMP_UPDATE, NVOCMP_WRITE = 0, NVOCMP_CREATE,
NVOCMP_UPDATE, NVOCMP_WRITE = 0, NVOCMP_CREATE, NVOCMP_UPDATE,
NVOCMP_WRITE = 0, NVOCMP_CREATE, NVOCMP_UPDATE, NVOCMP_WRITE = 0,
NVOCMP_CREATE, NVOCMP_UPDATE, NVOCMP_WRITE = 0, NVOCMP_CREATE,
NVOCMP_UPDATE, NVOCMP_WRITE = 0, NVOCMP_CREATE, NVOCMP_UPDATE,
NVOCMP_WRITE = 0, NVOCMP_CREATE, NVOCMP_UPDATE, NVOCMP_WRITE = 0,
NVOCMP_CREATE, NVOCMP_UPDATE, NVOCMP_WRITE = 0, NVOCMP_CREATE,
NVOCMP_UPDATE, NVOCMP_WRITE = 0, NVOCMP_CREATE, NVOCMP_UPDATE,
NVOCMP_WRITE = 0, NVOCMP_CREATE, NVOCMP_UPDATE, NVOCMP_WRITE = 0,
NVOCMP_CREATE, NVOCMP_UPDATE, NVOCMP_WRITE = 0, NVOCMP_CREATE,
NVOCMP_UPDATE, NVOCMP_WRITE = 0, NVOCMP_CREATE, NVOCMP_UPDATE,
NVOCMP_WRITE = 0, NVOCMP_CREATE, NVOCMP_UPDATE, NVOCMP_WRITE = 0,
NVOCMP_CREATE, NVOCMP_UPDATE
}
Functions
static uint8_t NVOCMP_addItem (NVOCMP_nvHandle_t *pNvHandle, NVOCMP_itemHdr_t *iHdr, uint8_t *pBuf, NVOCMP_writeMode_t wm)
static void NVOCMP_changePageState (NVOCMP_nvHandle_t *pNvHandle, uint8_t pg, NVOCMP_pageState_t state)
static uint8_t NVOCMP_checkItem (NVINTF_itemID_t *id, uint16_t len, NVOCMP_itemHdr_t *iHdr, uint8_t flag)
static NVOCMP_compactStatus_t NVOCMP_compact (NVOCMP_nvHandle_t *pNvHandle)
static uint8_t NVOCMP_compactNvApi (uint16_t min)
static int16_t NVOCMP_compactPage (NVOCMP_nvHandle_t *pNvHandle, uint16_t nBytes)
static uint8_t NVOCMP_createItemApi (NVINTF_itemID_t id, uint32_t len, void *buf)
static uint8_t NVOCMP_deleteItemApi (NVINTF_itemID_t id)
static void NVOCMP_disableCache (uint32_t *vm)
static uint8_t NVOCMP_doNextApi (NVINTF_nvProxy_t *prx)
static uint8_t NVOCMP_doNVCRC (uint8_t pg, uint16_t ofs, uint16_t len, uint8_t crc, bool flag)
static uint8_t NVOCMP_doRAMCRC (uint8_t *input, uint16_t len, uint8_t crc)
static uint8_t NVOCMP_erase (NVOCMP_nvHandle_t *pNvHandle, uint8_t dstPg)
static uint8_t NVOCMP_eraseNvApi (void)
static bool NVOCMP_expectCompApi (uint16_t len)
static int8_t NVOCMP_findItem (NVOCMP_nvHandle_t *pNvHandle, uint8_t pg, uint16_t ofs, NVOCMP_itemHdr_t *pHdr, int8_t flag, NVOCMP_itemInfo_t *pInfo)
static uint16_t NVOCMP_findOffset (uint8_t pg, uint16_t ofs)
static bool NVOCMP_findSignature (uint8_t pg, uint16_t *pSrcOff)
static uint8_t NVOCMP_getDstPage (NVOCMP_nvHandle_t *pNvHandle, uint16_t len)
static uint32_t NVOCMP_getFreeNvApi (void)
static uint32_t NVOCMP_getItemLenApi (NVINTF_itemID_t id)
static void NVOCMP_initNv (NVOCMP_nvHandle_t *pNvHandle)
static uint8_t NVOCMP_initNvApi (void *param)
void NVOCMP_loadApiPtrs (NVINTF_nvFuncts_t *pfn)
void NVOCMP_loadApiPtrsExt (NVINTF_nvFuncts_t *pfn)
void NVOCMP_loadApiPtrsMin (NVINTF_nvFuncts_t *pfn)
static int32_t NVOCMP_lockNvApi (void)
Global function to lock the NV priority gate mutex.
static void NVOCMP_read (uint8_t pg, uint16_t off, uint8_t *pBuf, uint16_t len)
static uint8_t NVOCMP_readByte (uint8_t pg, uint16_t ofs)
static uint8_t NVOCMP_readContItemApi (NVINTF_itemID_t id, uint16_t ofs, uint16_t rlen, void *rBuf, uint16_t clen, uint16_t coff, void *cBuf, uint16_t *pSubId)
static void NVOCMP_readHeader (uint8_t pg, uint16_t ofs, NVOCMP_itemHdr_t *iHdr, bool flag)
static uint8_t NVOCMP_readItem (NVOCMP_itemHdr_t *iHdr, uint16_t ofs, uint16_t len, void *pBuf, bool flag)
static uint8_t NVOCMP_readItemApi (NVINTF_itemID_t id, uint16_t ofs, uint16_t len, void *buf)
static void NVOCMP_restoreCache (uint32_t vm)
static uint8_t NVOCMP_scanPage (NVOCMP_nvHandle_t *pNvHandle, uint8_t pg, NVOCMP_pageInfo_t *pPageInfo)
void NVOCMP_setCheckVoltage (void *funcPtr)
static void NVOCMP_setCompactHdr (uint8_t dstPg, uint8_t pg, int16_t offset, uint16_t location)
static void NVOCMP_setItemInactive (NVOCMP_nvHandle_t *pNvHandle, uint8_t pg, uint16_t iOfs)
static void NVOCMP_setPageState (NVOCMP_nvHandle_t *pNvHandle, uint8_t pg, NVOCMP_pageState_t state)
static void NVOCMP_unlockNvApi (int32_t)
static uint8_t NVOCMP_updateItemApi (NVINTF_itemID_t id, uint32_t len, void *buf)
static uint8_t NVOCMP_verifyCRC (uint16_t iOfs, uint16_t len, uint8_t crc, uint8_t pg, bool flag)
static uint8_t NVOCMP_write (uint8_t dstPg, uint16_t off, uint8_t *pBuf, uint16_t len)
static void NVOCMP_writeByte (uint8_t pg, uint16_t ofs, uint8_t bwv)
static void NVOCMP_writeItem (NVOCMP_nvHandle_t *pNvHandle, NVOCMP_itemHdr_t *pHdr, uint8_t dstPg, uint16_t dstOff, uint8_t *pBuf)
static uint8_t NVOCMP_writeItemApi (NVINTF_itemID_t id, uint16_t len, void *buf)
Variables
NVOCMP_initAction_t gAction
static uint8_t NVOCMP_failF = NVINTF_NOTREADY
static uint8_t NVOCMP_failW
static GateMutexPri_Handle NVOCMP_gMutexPri
static uint8_t NVOCMP_itemBuffer [NVOCMP_SMALLITEM]
NVOCMP_nvHandle_t NVOCMP_nvHandle
static NVS_Attrs NVOCMP_nvsAttrs
static NVS_Handle NVOCMP_nvsHandle
uint8_t NVOCMP_size
static bool(* NVOCMP_voltCheckFptr)(void)
Macro Definition Documentation
NVOCMP_NVPAGES
#define NVOCMP_NVPAGES 2
Referenced by NVOCMP_initNvApi().
NVOCMP_FASTCP
#define NVOCMP_FASTCP 1
NVOCMP_COMPR
#define NVOCMP_COMPR 0
NVOCMP_HDRLE
#define NVOCMP_HDRLE 0
NVOCMP_FASTOFF
#define NVOCMP_FASTOFF 1
NVOCMP_FASTITEM
#define NVOCMP_FASTITEM 0
NVOCMP_NWSAMEITEM
#define NVOCMP_NWSAMEITEM 0
NVOCMP_MIGRATE_DISABLED
#define NVOCMP_MIGRATE_DISABLED
NVOCMP_NVONEP
#define NVOCMP_NVONEP 1
NVOCMP_NVTWOP
#define NVOCMP_NVTWOP 2
Referenced by NVOCMP_restoreCache().
NVOCMP_NVSIZE
#define NVOCMP_NVSIZE NVOCMP_size
Referenced by NVOCMP_eraseNvApi(), NVOCMP_findItem(), NVOCMP_findOffset(), NVOCMP_getDstPage(), NVOCMP_getFreeNvApi(), NVOCMP_initNv(), NVOCMP_initNvApi(), NVOCMP_restoreCache(), and NVOCMP_scanPage().
NVOCMP_ADDPAGE
#define NVOCMP_ADDPAGE (p, n) (((p) + (n)) % NVOCMP_NVSIZE)
Referenced by NVOCMP_findItem(), NVOCMP_findSignature(), and NVOCMP_scanPage().
NVOCMP_INCPAGE
#define NVOCMP_INCPAGE (p) NVOCMP_ADDPAGE(p,1)
Referenced by NVOCMP_findItem(), NVOCMP_findOffset(), NVOCMP_findSignature(), NVOCMP_getDstPage(), NVOCMP_getFreeNvApi(), NVOCMP_initNv(), NVOCMP_restoreCache(), and NVOCMP_scanPage().
NVOCMP_DECPAGE
#define NVOCMP_DECPAGE (p) NVOCMP_ADDPAGE(p,NVOCMP_NVSIZE - 1)
Referenced by NVOCMP_findItem(), NVOCMP_findOffset(), NVOCMP_findSignature(), NVOCMP_initNv(), and NVOCMP_scanPage().
NVOCMP_NVS_INDEX
#define NVOCMP_NVS_INDEX 0
Referenced by NVOCMP_initNvApi().
NVOCMP_MAXSYSID
#define NVOCMP_MAXSYSID 0x003F
Referenced by NVOCMP_checkItem().
NVOCMP_MAXITEMID
#define NVOCMP_MAXITEMID 0x03FF
Referenced by NVOCMP_checkItem().
NVOCMP_MAXSUBID
#define NVOCMP_MAXSUBID 0x03FF
Referenced by NVOCMP_checkItem().
NVOCMP_MAXLEN
#define NVOCMP_MAXLEN 0x0FFF
Referenced by NVOCMP_checkItem().
NVOCMP_INVALIDSUBID
#define NVOCMP_INVALIDSUBID 0xFFFF
Referenced by NVOCMP_readContItemApi().
NVOCMP_ERASEDBYTE
#define NVOCMP_ERASEDBYTE 0xFF
Referenced by NVOCMP_findOffset().
NVOCMP_ERASEDWORD
#define NVOCMP_ERASEDWORD 0xFFFFFFFF
Referenced by NVOCMP_findOffset().
NVOCMP_ONEBYTE
#define NVOCMP_ONEBYTE 1
Referenced by NVOCMP_readByte(), and NVOCMP_readHeader().
NVOCMP_CMPSPACE
#define NVOCMP_CMPSPACE 12
NVOCMP_NULLPAGE
#define NVOCMP_NULLPAGE 0xFF
Referenced by NVOCMP_addItem(), NVOCMP_erase(), NVOCMP_expectCompApi(), NVOCMP_findItem(), NVOCMP_getDstPage(), NVOCMP_initNv(), NVOCMP_initNvApi(), NVOCMP_restoreCache(), and NVOCMP_scanPage().
NVOCMP_XFERBLKMAX
#define NVOCMP_XFERBLKMAX 32
Referenced by NVOCMP_compact(), NVOCMP_doNVCRC(), and NVOCMP_findSignature().
NVOCMP_SMALLITEM
#define NVOCMP_SMALLITEM 12
Referenced by NVOCMP_writeItem().
NVOCMP_CRCONREAD
#define NVOCMP_CRCONREAD 1
Referenced by NVOCMP_readItem().
NVOCMP_FINDLMASK
#define NVOCMP_FINDLMASK 0x0F
Referenced by NVOCMP_findItem(), and NVOCMP_findOffset().
NVOCMP_FINDHMASK
#define NVOCMP_FINDHMASK 0xF0
Referenced by NVOCMP_findItem(), and NVOCMP_findOffset().
NVOCMP_FLASHOFFSET
#define NVOCMP_FLASHOFFSET (pg, ofs) ((uint32_t)(((pg) << PAGE_SIZE_LSHIFT) + (ofs)))
Referenced by NVOCMP_erase(), NVOCMP_read(), NVOCMP_setCheckVoltage(), and NVOCMP_write().
NVOCMP_FLASHACCESS
#define NVOCMP_FLASHACCESS (err)
Value:
{if (NVOCMP_voltCheckFptr)\
    { if (!NVOCMP_voltCheckFptr()) { err = NVINTF_LOWPOWER;}}}
Referenced by NVOCMP_compactNvApi(), NVOCMP_compactPage(), NVOCMP_createItemApi(), NVOCMP_deleteItemApi(), NVOCMP_erase(), NVOCMP_eraseNvApi(), NVOCMP_findItem(), NVOCMP_updateItemApi(), NVOCMP_write(), and NVOCMP_writeItemApi().
NVOCMP_LOCK
#define NVOCMP_LOCK () int32_t key = GateMutexPri_enter(NVOCMP_gMutexPri);
Referenced by NVOCMP_compactNvApi(), NVOCMP_createItemApi(), NVOCMP_deleteItemApi(), NVOCMP_doNextApi(), NVOCMP_eraseNvApi(), NVOCMP_getItemLenApi(), NVOCMP_readContItemApi(), NVOCMP_readItemApi(), NVOCMP_updateItemApi(), and NVOCMP_writeItemApi().
NVOCMP_UNLOCK
#define NVOCMP_UNLOCK (err)
Value:
{ \
    GateMutexPri_leave(NVOCMP_gMutexPri, key); return(err); }
Referenced by NVOCMP_compactNvApi(), NVOCMP_createItemApi(), NVOCMP_deleteItemApi(), NVOCMP_doNextApi(), NVOCMP_eraseNvApi(), NVOCMP_getItemLenApi(), NVOCMP_readContItemApi(), NVOCMP_readItemApi(), NVOCMP_updateItemApi(), and NVOCMP_writeItemApi().
NVOCMP_CMPRID
#define NVOCMP_CMPRID (s, i, b)
Value:
((uint32_t)((((((s) & NVOCMP_MAXSYSID) << NVOCMP_CMPSPACE)   | \
                                            ((i) & NVOCMP_MAXITEMID)) << NVOCMP_CMPSPACE) | \
                                            ((b) & NVOCMP_MAXSUBID)))
Referenced by NVOCMP_checkItem(), NVOCMP_findItem(), NVOCMP_findOffset(), and NVOCMP_readHeader().
NVOCMP_ASSERT
#define NVOCMP_ASSERT (cond, message)
Referenced by NVOCMP_checkItem(), NVOCMP_compact(), NVOCMP_findItem(), NVOCMP_findOffset(), NVOCMP_findSignature(), NVOCMP_initNvApi(), NVOCMP_scanPage(), and NVOCMP_writeItem().
NVOCMP_ALERT
#define NVOCMP_ALERT (cond, message)
Referenced by NVOCMP_addItem(), NVOCMP_checkItem(), NVOCMP_compact(), NVOCMP_compactNvApi(), NVOCMP_createItemApi(), NVOCMP_deleteItemApi(), NVOCMP_doNextApi(), NVOCMP_erase(), NVOCMP_findItem(), NVOCMP_findOffset(), NVOCMP_findSignature(), NVOCMP_initNvApi(), NVOCMP_readHeader(), NVOCMP_restoreCache(), NVOCMP_updateItemApi(), NVOCMP_verifyCRC(), NVOCMP_write(), and NVOCMP_writeItem().
NVOCMP_ASSERT1
#define NVOCMP_ASSERT1 (cond) {if(!cond) while(1);}
Referenced by NVOCMP_findItem(), and NVOCMP_scanPage().
PAGE_SIZE_LSHIFT
#define PAGE_SIZE_LSHIFT 13
FLASH_PAGE_SIZE
#define FLASH_PAGE_SIZE (1 << PAGE_SIZE_LSHIFT)
Referenced by NVOCMP_compact(), NVOCMP_compactNvApi(), NVOCMP_compactPage(), NVOCMP_doNextApi(), NVOCMP_findItem(), NVOCMP_findOffset(), NVOCMP_findSignature(), NVOCMP_getDstPage(), NVOCMP_getFreeNvApi(), NVOCMP_initNvApi(), NVOCMP_readContItemApi(), NVOCMP_restoreCache(), NVOCMP_scanPage(), and NVOCMP_writeItem().
NVOCMP_VERSION
#define NVOCMP_VERSION 0x03
Referenced by NVOCMP_restoreCache(), NVOCMP_scanPage(), and NVOCMP_setPageState().
NVOCMP_SIGNATURE
#define NVOCMP_SIGNATURE 0x96
Referenced by NVOCMP_checkItem(), NVOCMP_compact(), NVOCMP_findSignature(), NVOCMP_readHeader(), NVOCMP_restoreCache(), NVOCMP_scanPage(), NVOCMP_setPageState(), and NVOCMP_writeItem().
NVOCMP_GPRAM
#define NVOCMP_GPRAM
RAM_BUFFER_ADDRESS
#define RAM_BUFFER_ADDRESS (uint8_t *)0x11000000
Referenced by NVOCMP_compact(), NVOCMP_doNVCRC(), NVOCMP_findOffset(), NVOCMP_findSignature(), NVOCMP_readHeader(), and NVOCMP_readItem().
NVOCMP_PGHDRLEN
#define NVOCMP_PGHDRLEN (sizeof(NVOCMP_pageHdr_t))
Referenced by NVOCMP_compactPage(), NVOCMP_findItem(), NVOCMP_getDstPage(), NVOCMP_getFreeNvApi(), NVOCMP_restoreCache(), NVOCMP_scanPage(), NVOCMP_setPageState(), and NVOCMP_writeItem().
NVOCMP_COMPACTHDRLEN [1/2]
#define NVOCMP_COMPACTHDRLEN (sizeof(NVOCMP_compactHdr_t))
Referenced by NVOCMP_findItem(), and NVOCMP_setCompactHdr().
NVOCMP_PGHDROFS
#define NVOCMP_PGHDROFS 0
Referenced by NVOCMP_changePageState(), NVOCMP_compactPage(), NVOCMP_findItem(), NVOCMP_getDstPage(), NVOCMP_getFreeNvApi(), NVOCMP_restoreCache(), NVOCMP_scanPage(), and NVOCMP_writeItem().
NVOCMP_PGHDRPST
#define NVOCMP_PGHDRPST 0
NVOCMP_PGHDRCYC
#define NVOCMP_PGHDRCYC 1
NVOCMP_PGHDRVER
#define NVOCMP_PGHDRVER 2
Referenced by NVOCMP_restoreCache(), and NVOCMP_setItemInactive().
NVOCMP_PGHDRSIG
#define NVOCMP_PGHDRSIG 3
NVOCMP_COMPMODEOFS
#define NVOCMP_COMPMODEOFS 6
Referenced by NVOCMP_compactPage(), and NVOCMP_findItem().
NVOCMP_NOCOMPHDR
#define NVOCMP_NOCOMPHDR 3
NVOCMP_PGDATAOFS
#define NVOCMP_PGDATAOFS (NVOCMP_PGHDRLEN + NVOCMP_NOCOMPHDR*NVOCMP_COMPACTHDRLEN)
Referenced by NVOCMP_compact(), NVOCMP_erase(), NVOCMP_findItem(), NVOCMP_findOffset(), NVOCMP_findSignature(), NVOCMP_initNv(), NVOCMP_restoreCache(), and NVOCMP_scanPage().
NVOCMP_PGDATAEND
#define NVOCMP_PGDATAEND (FLASH_PAGE_SIZE - 1)
NVOCMP_PGDATALEN
#define NVOCMP_PGDATALEN (FLASH_PAGE_SIZE - NVOCMP_PGDATAOFS)
NVOCMP_PGNORMAL
#define NVOCMP_PGNORMAL 0xFF
Referenced by NVOCMP_erase(), NVOCMP_restoreCache(), and NVOCMP_scanPage().
NVOCMP_PGCDST
#define NVOCMP_PGCDST 0xFE
Referenced by NVOCMP_compactPage(), NVOCMP_findItem(), and NVOCMP_scanPage().
NVOCMP_PGCDONE
#define NVOCMP_PGCDONE 0xFC
Referenced by NVOCMP_compactPage(), and NVOCMP_findItem().
NVOCMP_PGCSRC
#define NVOCMP_PGCSRC 0xF8
Referenced by NVOCMP_compactPage(), and NVOCMP_findItem().
NVOCMP_PGMODEBIT
#define NVOCMP_PGMODEBIT 0x04
NVOCTP_PGACTIVE
#define NVOCTP_PGACTIVE 0xA5
Referenced by NVOCMP_initNv(), and NVOCMP_scanPage().
NVOCTP_PGXFER
#define NVOCTP_PGXFER 0x24
Referenced by NVOCMP_initNv(), and NVOCMP_scanPage().
NVOCTP_PGDATAOFS
#define NVOCTP_PGDATAOFS NVOCMP_PGHDRLEN
Referenced by NVOCMP_restoreCache().
NVOCTP_VERSION
#define NVOCTP_VERSION 0x02
Referenced by NVOCMP_restoreCache(), and NVOCMP_scanPage().
NVOCTP_SIGNATURE
#define NVOCTP_SIGNATURE 0x96
Referenced by NVOCMP_restoreCache(), and NVOCMP_scanPage().
NVOCMP_MINCYCLE
#define NVOCMP_MINCYCLE 0x01
Referenced by NVOCMP_erase().
NVOCMP_MAXCYCLE
#define NVOCMP_MAXCYCLE 0xFE
Referenced by NVOCMP_erase().
NVOCMP_ALLACTIVE
#define NVOCMP_ALLACTIVE 0x3
Referenced by NVOCMP_restoreCache(), NVOCMP_setItemInactive(), and NVOCMP_setPageState().
NVOCMP_SOMEINACTIVE
#define NVOCMP_SOMEINACTIVE 0x0
Referenced by NVOCMP_restoreCache(), NVOCMP_scanPage(), and NVOCMP_setItemInactive().
NVOCMP_ITEMHDRLEN
#define NVOCMP_ITEMHDRLEN 7
Referenced by NVOCMP_addItem(), NVOCMP_compact(), NVOCMP_expectCompApi(), NVOCMP_findItem(), NVOCMP_findOffset(), NVOCMP_findSignature(), NVOCMP_initNv(), NVOCMP_initNvApi(), NVOCMP_readHeader(), NVOCMP_scanPage(), and NVOCMP_writeItem().
NVOCMP_HDRSIGOFS
#define NVOCMP_HDRSIGOFS 6
NVOCMP_HDRVLDOFS
#define NVOCMP_HDRVLDOFS 5
Referenced by NVOCMP_setItemInactive().
NVOCMP_HDRCRCINC
#define NVOCMP_HDRCRCINC 5
Referenced by NVOCMP_verifyCRC(), and NVOCMP_writeItem().
NVOCMP_ACTIVEIDBIT
#define NVOCMP_ACTIVEIDBIT 0x2
Referenced by NVOCMP_compact(), NVOCMP_findItem(), NVOCMP_findOffset(), NVOCMP_findSignature(), NVOCMP_readHeader(), NVOCMP_setItemInactive(), and NVOCMP_writeItem().
NVOCMP_VALIDIDBIT
#define NVOCMP_VALIDIDBIT 0x1
Referenced by NVOCMP_compact(), NVOCMP_findItem(), NVOCMP_findOffset(), NVOCMP_findSignature(), and NVOCMP_readHeader().
NVOCMP_FOLLOWBIT
#define NVOCMP_FOLLOWBIT 0x4
Referenced by NVOCMP_findItem(), NVOCMP_findOffset(), NVOCMP_initNv(), NVOCMP_readHeader(), and NVOCMP_scanPage().
NVOCMP_ITEMHDREND
#define NVOCMP_ITEMHDREND (NVOCMP_ITEMHDRLEN - 1)
NVOCMP_NULLOFFSET
#define NVOCMP_NULLOFFSET 0xFFFF
Referenced by NVOCMP_erase(), and NVOCMP_restoreCache().
DEFAULT_COMPACTHDR
#define DEFAULT_COMPACTHDR {NVOCMP_NULLOFFSET, NVOCMP_NULLPAGE, NVOCMP_SIGNATURE};
Referenced by NVOCMP_setCompactHdr().
THISPAGEHDR
#define THISPAGEHDR 0
Referenced by NVOCMP_erase(), NVOCMP_findItem(), and NVOCMP_restoreCache().
XSRCSTARTHDR
#define XSRCSTARTHDR 1
Referenced by NVOCMP_compact(), NVOCMP_erase(), NVOCMP_findItem(), NVOCMP_findSignature(), and NVOCMP_restoreCache().
XSRCENDHDR
#define XSRCENDHDR 2
Referenced by NVOCMP_compact(), NVOCMP_erase(), NVOCMP_findItem(), NVOCMP_findSignature(), and NVOCMP_restoreCache().
NVOCMP_COMPACTHDRLEN [2/2]
#define NVOCMP_COMPACTHDRLEN (sizeof(NVOCMP_compactHdr_t))
Typedef Documentation
NVOCMP_pageState_t
typedef enum NVOCMP_pageState NVOCMP_pageState_t
NVOCMP_compactStatus_t
typedef enum NVOCMP_compactStatus NVOCMP_compactStatus_t
cmpIH_t
typedef uint8_t cmpIH_t[NVOCMP_ITEMHDRLEN]
NVOCMP_initAction_t
typedef enum NVOCMP_initAction NVOCMP_initAction_t
NVOCMP_writeMode_t
typedef enum NVOCMP_writeMode NVOCMP_writeMode_t
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
NVOCMP_FINDANY
NVOCMP_FINDSYSID
NVOCMP_FINDITMID
NVOCMP_FINDSTRICT
NVOCMP_FINDCONTENT
NVOCMP_pageState
enum NVOCMP_pageState
Enumerator
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_PGNACT
NVOCMP_PGXDST
NVOCMP_PGRDY
NVOCMP_PGACT
NVOCMP_PGFULL
NVOCMP_PGXSRC
NVOCMP_PGNDEF
NVOCMP_compactStatus
enum NVOCMP_compactStatus
Enumerator
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_COMPACT_SUCCESS
NVOCMP_COMPACT_SRCDONE
NVOCMP_COMPACT_DSTDONE
NVOCMP_COMPACT_BOTHDOE
NVOCMP_COMPACT_FAILURE
NVOCMP_initAction
enum NVOCMP_initAction
Enumerator
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_NORMAL_INIT
NVOCMP_NORMAL_RESUME
NVOCMP_RECOVER_COMPACT
NVOCMP_RECOVER_ERASE
NVOCMP_FORCE_CLEAN
NVOCMP_NORMAL_MIGRATE
NVOCMP_ERROR_UNKNOWN
NVOCMP_writeMode
enum NVOCMP_writeMode
Enumerator
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
NVOCMP_WRITE
NVOCMP_CREATE
NVOCMP_UPDATE
Function Documentation
NVOCMP_initNvApi()
static uint8_t NVOCMP_initNvApi (void * param) static
References NVOCMP_diag_t::available, FLASH_PAGE_SIZE, NVINTF_FAILURE, NVINTF_NOTFOUND, NVINTF_NOTREADY, NVINTF_SUCCESS, NVOCMP_ALERT, NVOCMP_ASSERT, NVOCMP_EXCEPTION, NVOCMP_failF, NVOCMP_initNv(), NVOCMP_ITEMHDRLEN, NVOCMP_NULLPAGE, NVOCMP_NVPAGES, NVOCMP_NVS_INDEX, NVOCMP_NVSIZE, NVOCMP_readItemApi(), NVOCMP_setCheckVoltage(), NVOCMP_writeItemApi(), and NVOCMP_diag_t::resets.
Referenced by NVOCMP_loadApiPtrs(), NVOCMP_loadApiPtrsExt(), and NVOCMP_loadApiPtrsMin().
NVOCMP_compactNvApi()
static uint8_t NVOCMP_compactNvApi (uint16_t min) static
References FLASH_PAGE_SIZE, NVINTF_BADPARAM, NVINTF_SUCCESS, NVOCMP_ALERT, NVOCMP_compactPage(), NVOCMP_failF, NVOCMP_failW, NVOCMP_FLASHACCESS, NVOCMP_LOCK, and NVOCMP_UNLOCK.
Referenced by NVOCMP_loadApiPtrs(), NVOCMP_loadApiPtrsExt(), and NVOCMP_loadApiPtrsMin().
NVOCMP_createItemApi()
static uint8_t NVOCMP_createItemApi (NVINTF_itemID_t id, uint32_t len, void * buf) static
References NVINTF_BADPARAM, NVINTF_EXIST, NVINTF_FAILURE, NVINTF_NOTFOUND, NVINTF_SUCCESS, NVOCMP_addItem(), NVOCMP_ALERT, NVOCMP_checkItem(), NVOCMP_CREATE, NVOCMP_findItem(), NVOCMP_FINDSTRICT, NVOCMP_FLASHACCESS, NVOCMP_LOCK, and NVOCMP_UNLOCK.
Referenced by NVOCMP_loadApiPtrs(), and NVOCMP_loadApiPtrsExt().
NVOCMP_updateItemApi()
static uint8_t NVOCMP_updateItemApi (NVINTF_itemID_t id, uint32_t len, void * buf) static
References NVINTF_BADPARAM, NVINTF_FAILURE, NVINTF_NOTFOUND, NVINTF_SUCCESS, NVOCMP_addItem(), NVOCMP_ALERT, NVOCMP_checkItem(), NVOCMP_failW, NVOCMP_findItem(), NVOCMP_FINDSTRICT, NVOCMP_FLASHACCESS, NVOCMP_LOCK, NVOCMP_setItemInactive(), NVOCMP_UNLOCK, and NVOCMP_UPDATE.
Referenced by NVOCMP_loadApiPtrs(), and NVOCMP_loadApiPtrsExt().
NVOCMP_deleteItemApi()
static uint8_t NVOCMP_deleteItemApi (NVINTF_itemID_t id) static
References NVINTF_BADSYSID, NVINTF_FAILURE, NVINTF_NOTFOUND, NVINTF_SUCCESS, NVOCMP_ALERT, NVOCMP_checkItem(), NVOCMP_findItem(), NVOCMP_FINDSTRICT, NVOCMP_FLASHACCESS, NVOCMP_LOCK, NVOCMP_setItemInactive(), and NVOCMP_UNLOCK.
Referenced by NVOCMP_loadApiPtrs(), and NVOCMP_loadApiPtrsExt().
NVOCMP_getItemLenApi()
static uint32_t NVOCMP_getItemLenApi (NVINTF_itemID_t id) static
References NVINTF_SUCCESS, NVOCMP_checkItem(), NVOCMP_findItem(), NVOCMP_FINDSTRICT, NVOCMP_LOCK, and NVOCMP_UNLOCK.
Referenced by NVOCMP_loadApiPtrs(), and NVOCMP_loadApiPtrsExt().
NVOCMP_readItemApi()
static uint8_t NVOCMP_readItemApi (NVINTF_itemID_t id, uint16_t ofs, uint16_t len, void * buf) static
References NVINTF_BADPARAM, NVOCMP_checkItem(), NVOCMP_findItem(), NVOCMP_FINDSTRICT, NVOCMP_LOCK, NVOCMP_readItem(), and NVOCMP_UNLOCK.
Referenced by NVOCMP_initNvApi(), NVOCMP_loadApiPtrs(), NVOCMP_loadApiPtrsExt(), and NVOCMP_loadApiPtrsMin().
NVOCMP_readContItemApi()
static uint8_t NVOCMP_readContItemApi (NVINTF_itemID_t id, uint16_t ofs, uint16_t rlen, void * rBuf, uint16_t clen, uint16_t coff, void * cBuf, uint16_t * pSubId) static
References FLASH_PAGE_SIZE, NVINTF_BADPARAM, NVOCMP_checkItem(), NVOCMP_FINDCONTENT, NVOCMP_findItem(), NVOCMP_FINDITMID, NVOCMP_FINDSTRICT, NVOCMP_INVALIDSUBID, NVOCMP_LOCK, and NVOCMP_UNLOCK.
Referenced by NVOCMP_loadApiPtrs(), and NVOCMP_loadApiPtrsExt().
NVOCMP_writeItemApi()
static uint8_t NVOCMP_writeItemApi (NVINTF_itemID_t id, uint16_t len, void * buf) static
References NVINTF_BADPARAM, NVINTF_SUCCESS, NVOCMP_addItem(), NVOCMP_checkItem(), NVOCMP_failW, NVOCMP_FINDSTRICT, NVOCMP_FLASHACCESS, NVOCMP_LOCK, NVOCMP_setItemInactive(), NVOCMP_UNLOCK, and NVOCMP_WRITE.
Referenced by NVOCMP_initNvApi(), NVOCMP_loadApiPtrs(), NVOCMP_loadApiPtrsExt(), and NVOCMP_loadApiPtrsMin().
NVOCMP_doNextApi()
static uint8_t NVOCMP_doNextApi (NVINTF_nvProxy_t * prx) static
References nvintf_nvproxy_t::buffer, nvintf_nvproxy_t::flag, FLASH_PAGE_SIZE, nvintf_nvproxy_t::itemid, nvintf_nvproxy_t::len, NVINTF_BADPARAM, NVINTF_DOANYID, NVINTF_DODELETE, NVINTF_DOFIND, NVINTF_DOITMID, NVINTF_DOREAD, NVINTF_DOSTART, NVINTF_DOSYSID, NVINTF_NOTFOUND, NVINTF_SUCCESS, NVINTF_SYSID_NVDRVR, NVOCMP_ALERT, NVOCMP_FINDANY, NVOCMP_findItem(), NVOCMP_FINDITMID, NVOCMP_FINDSYSID, NVOCMP_LOCK, NVOCMP_readItem(), NVOCMP_setItemInactive(), NVOCMP_UNLOCK, nvintf_nvproxy_t::subid, and nvintf_nvproxy_t::sysid.
Referenced by NVOCMP_loadApiPtrsExt().
NVOCMP_lockNvApi()
static int32_t NVOCMP_lockNvApi (void) static
Global function to lock the NV priority gate mutex.
Returns
Key value needed to unlock the gate
Referenced by NVOCMP_loadApiPtrsExt().
NVOCMP_unlockNvApi()
static void NVOCMP_unlockNvApi (int32_t key) static
Referenced by NVOCMP_loadApiPtrsExt().
NVOCMP_expectCompApi()
static bool NVOCMP_expectCompApi (uint16_t len) static
References NVOCMP_getDstPage(), NVOCMP_ITEMHDRLEN, and NVOCMP_NULLPAGE.
Referenced by NVOCMP_loadApiPtrs(), NVOCMP_loadApiPtrsExt(), and NVOCMP_loadApiPtrsMin().
NVOCMP_eraseNvApi()
static uint8_t NVOCMP_eraseNvApi (void) static
References NVINTF_SUCCESS, NVOCMP_changePageState(), NVOCMP_erase(), NVOCMP_failW, NVOCMP_FLASHACCESS, NVOCMP_LOCK, NVOCMP_NVSIZE, NVOCMP_PGRDY, NVOCMP_PGXDST, and NVOCMP_UNLOCK.
Referenced by NVOCMP_loadApiPtrs(), NVOCMP_loadApiPtrsExt(), and NVOCMP_loadApiPtrsMin().
NVOCMP_getFreeNvApi()
static uint32_t NVOCMP_getFreeNvApi (void) static
References FLASH_PAGE_SIZE, NVOCMP_INCPAGE, NVOCMP_NVSIZE, NVOCMP_PGACT, NVOCMP_PGHDRLEN, NVOCMP_PGHDROFS, NVOCMP_PGNACT, NVOCMP_PGRDY, and NVOCMP_read().
Referenced by NVOCMP_loadApiPtrs(), NVOCMP_loadApiPtrsExt(), and NVOCMP_loadApiPtrsMin().
NVOCMP_initNv()
static void NVOCMP_initNv (NVOCMP_nvHandle_t * pNvHandle) static
References NVINTF_SUCCESS, NVOCMP_changePageState(), NVOCMP_compactPage(), NVOCMP_DECPAGE, NVOCMP_erase(), NVOCMP_findItem(), NVOCMP_FINDSTRICT, NVOCMP_FOLLOWBIT, NVOCMP_INCPAGE, NVOCMP_ITEMHDRLEN, NVOCMP_NORMAL_INIT, NVOCMP_NORMAL_MIGRATE, NVOCMP_NORMAL_RESUME, NVOCMP_NULLPAGE, NVOCMP_NVSIZE, NVOCMP_PGACT, NVOCMP_PGDATAOFS, NVOCMP_PGFULL, NVOCMP_PGRDY, NVOCMP_PGXDST, NVOCMP_PGXSRC, NVOCMP_readHeader(), NVOCMP_RECOVER_COMPACT, NVOCMP_scanPage(), NVOCMP_setItemInactive(), NVOCTP_PGACTIVE, and NVOCTP_PGXFER.
Referenced by NVOCMP_initNvApi(), and NVOCMP_scanPage().
NVOCMP_scanPage()
static uint8_t NVOCMP_scanPage (NVOCMP_nvHandle_t * pNvHandle, uint8_t pg, NVOCMP_pageInfo_t * pPageInfo) static
References FLASH_PAGE_SIZE, NVINTF_SUCCESS, NVOCMP_ADDPAGE, NVOCMP_ASSERT, NVOCMP_ASSERT1, NVOCMP_changePageState(), NVOCMP_compactPage(), NVOCMP_DECPAGE, NVOCMP_erase(), NVOCMP_ERROR_UNKNOWN, NVOCMP_findItem(), NVOCMP_findOffset(), NVOCMP_FINDSTRICT, NVOCMP_FOLLOWBIT, NVOCMP_FORCE_CLEAN, NVOCMP_INCPAGE, NVOCMP_initNv(), NVOCMP_ITEMHDRLEN, NVOCMP_NORMAL_INIT, NVOCMP_NORMAL_MIGRATE, NVOCMP_NORMAL_RESUME, NVOCMP_NULLPAGE, NVOCMP_NVSIZE, NVOCMP_PGACT, NVOCMP_PGCDST, NVOCMP_PGDATAOFS, NVOCMP_PGFULL, NVOCMP_PGHDRLEN, NVOCMP_PGHDROFS, NVOCMP_PGNACT, NVOCMP_PGNORMAL, NVOCMP_PGRDY, NVOCMP_PGXDST, NVOCMP_PGXSRC, NVOCMP_read(), NVOCMP_readHeader(), NVOCMP_RECOVER_COMPACT, NVOCMP_RECOVER_ERASE, NVOCMP_setItemInactive(), NVOCMP_SIGNATURE, NVOCMP_SOMEINACTIVE, NVOCMP_VERSION, NVOCTP_PGACTIVE, NVOCTP_PGXFER, NVOCTP_SIGNATURE, and NVOCTP_VERSION.
Referenced by NVOCMP_initNv(), and NVOCMP_restoreCache().
NVOCMP_findItem()
static int8_t NVOCMP_findItem (NVOCMP_nvHandle_t * pNvHandle, uint8_t pg, uint16_t ofs, NVOCMP_itemHdr_t * pHdr, int8_t flag, NVOCMP_itemInfo_t * pInfo) static
References FLASH_PAGE_SIZE, NVINTF_BADPARAM, NVINTF_NOTFOUND, NVINTF_SUCCESS, NVOCMP_ACTIVEIDBIT, NVOCMP_ADDPAGE, NVOCMP_ALERT, NVOCMP_ASSERT, NVOCMP_ASSERT1, NVOCMP_changePageState(), NVOCMP_CMPRID, NVOCMP_compact(), NVOCMP_COMPACT_FAILURE, NVOCMP_COMPACTHDRLEN, NVOCMP_compactPage(), NVOCMP_COMPMODEOFS, NVOCMP_DECPAGE, NVOCMP_erase(), NVOCMP_EXCEPTION, NVOCMP_FINDANY, NVOCMP_FINDCONTENT, NVOCMP_FINDHMASK, NVOCMP_FINDITMID, NVOCMP_FINDLMASK, NVOCMP_FINDSTRICT, NVOCMP_FINDSYSID, NVOCMP_FLASHACCESS, NVOCMP_FOLLOWBIT, NVOCMP_INCPAGE, NVOCMP_ITEMHDRLEN, NVOCMP_NULLPAGE, NVOCMP_NVSIZE, NVOCMP_PGACT, NVOCMP_PGCDONE, NVOCMP_PGCDST, NVOCMP_PGCSRC, NVOCMP_PGDATAOFS, NVOCMP_PGFULL, NVOCMP_PGHDRLEN, NVOCMP_PGHDROFS, NVOCMP_PGNACT, NVOCMP_PGRDY, NVOCMP_PGXDST, NVOCMP_PGXSRC, NVOCMP_read(), NVOCMP_readHeader(), NVOCMP_readItem(), NVOCMP_setItemInactive(), NVOCMP_VALIDIDBIT, NVOCMP_write(), NVOCMP_writeByte(), THISPAGEHDR, XSRCENDHDR, and XSRCSTARTHDR.
Referenced by NVOCMP_addItem(), NVOCMP_createItemApi(), NVOCMP_deleteItemApi(), NVOCMP_doNextApi(), NVOCMP_findOffset(), NVOCMP_getItemLenApi(), NVOCMP_initNv(), NVOCMP_readContItemApi(), NVOCMP_readItemApi(), NVOCMP_restoreCache(), NVOCMP_scanPage(), and NVOCMP_updateItemApi().
NVOCMP_addItem()
static uint8_t NVOCMP_addItem (NVOCMP_nvHandle_t * pNvHandle, NVOCMP_itemHdr_t * iHdr, uint8_t * pBuf, NVOCMP_writeMode_t wm) static
References NVINTF_BADLENGTH, NVINTF_SUCCESS, NVOCMP_ALERT, NVOCMP_compactPage(), NVOCMP_findItem(), NVOCMP_FINDSTRICT, NVOCMP_getDstPage(), NVOCMP_ITEMHDRLEN, NVOCMP_NULLPAGE, NVOCMP_read(), NVOCMP_UPDATE, NVOCMP_WRITE, and NVOCMP_writeItem().
Referenced by NVOCMP_createItemApi(), NVOCMP_updateItemApi(), and NVOCMP_writeItemApi().
NVOCMP_writeItem()
static void NVOCMP_writeItem (NVOCMP_nvHandle_t * pNvHandle, NVOCMP_itemHdr_t * pHdr, uint8_t dstPg, uint16_t dstOff, uint8_t * pBuf) static
References FLASH_PAGE_SIZE, NVINTF_BADLENGTH, NVINTF_FAILURE, NVOCMP_ACTIVEIDBIT, NVOCMP_ALERT, NVOCMP_ASSERT, NVOCMP_changePageState(), NVOCMP_doRAMCRC(), NVOCMP_HDRCRCINC, NVOCMP_ITEMHDRLEN, NVOCMP_PGACT, NVOCMP_PGHDRLEN, NVOCMP_PGHDROFS, NVOCMP_PGRDY, NVOCMP_read(), NVOCMP_setItemInactive(), NVOCMP_SIGNATURE, NVOCMP_SMALLITEM, and NVOCMP_write().
Referenced by NVOCMP_addItem().
NVOCMP_erase()
static uint8_t NVOCMP_erase (NVOCMP_nvHandle_t * pNvHandle, uint8_t dstPg) static
References NVINTF_FAILURE, NVINTF_LOWPOWER, NVINTF_SUCCESS, NVOCMP_ALERT, NVOCMP_FLASHACCESS, NVOCMP_FLASHOFFSET, NVOCMP_MAXCYCLE, NVOCMP_MINCYCLE, NVOCMP_NULLOFFSET, NVOCMP_NULLPAGE, NVOCMP_PGDATAOFS, NVOCMP_PGNACT, NVOCMP_PGNORMAL, NVOCMP_setCompactHdr(), NVOCMP_setPageState(), THISPAGEHDR, XSRCENDHDR, and XSRCSTARTHDR.
Referenced by NVOCMP_compact(), NVOCMP_compactPage(), NVOCMP_eraseNvApi(), NVOCMP_findItem(), NVOCMP_initNv(), NVOCMP_restoreCache(), and NVOCMP_scanPage().
NVOCMP_compactPage()
static int16_t NVOCMP_compactPage (NVOCMP_nvHandle_t * pNvHandle, uint16_t nBytes) static
References FLASH_PAGE_SIZE, NVINTF_SUCCESS, NVOCMP_changePageState(), NVOCMP_compact(), NVOCMP_COMPACT_FAILURE, NVOCMP_COMPMODEOFS, NVOCMP_erase(), NVOCMP_FLASHACCESS, NVOCMP_PGACT, NVOCMP_PGCDONE, NVOCMP_PGCDST, NVOCMP_PGCSRC, NVOCMP_PGFULL, NVOCMP_PGHDRLEN, NVOCMP_PGHDROFS, NVOCMP_PGXDST, NVOCMP_PGXSRC, NVOCMP_read(), and NVOCMP_writeByte().
Referenced by NVOCMP_addItem(), NVOCMP_compactNvApi(), NVOCMP_findItem(), NVOCMP_findOffset(), NVOCMP_initNv(), and NVOCMP_scanPage().
NVOCMP_compact()
static NVOCMP_compactStatus_t NVOCMP_compact (NVOCMP_nvHandle_t * pNvHandle) static
References FLASH_PAGE_SIZE, NVINTF_SUCCESS, NVOCMP_ACTIVEIDBIT, NVOCMP_ALERT, NVOCMP_ASSERT, NVOCMP_changePageState(), NVOCMP_COMPACT_FAILURE, NVOCMP_COMPACT_SUCCESS, NVOCMP_disableCache(), NVOCMP_erase(), NVOCMP_findSignature(), NVOCMP_ITEMHDRLEN, NVOCMP_PGDATAOFS, NVOCMP_PGXDST, NVOCMP_read(), NVOCMP_readHeader(), NVOCMP_restoreCache(), NVOCMP_setCompactHdr(), NVOCMP_SIGNATURE, NVOCMP_VALIDIDBIT, NVOCMP_verifyCRC(), NVOCMP_write(), NVOCMP_XFERBLKMAX, RAM_BUFFER_ADDRESS, XSRCENDHDR, and XSRCSTARTHDR.
Referenced by NVOCMP_compactPage(), NVOCMP_findItem(), and NVOCMP_findSignature().
NVOCMP_getDstPage()
static uint8_t NVOCMP_getDstPage (NVOCMP_nvHandle_t * pNvHandle, uint16_t len) static
References FLASH_PAGE_SIZE, NVOCMP_changePageState(), NVOCMP_INCPAGE, NVOCMP_NULLPAGE, NVOCMP_NVSIZE, NVOCMP_PGACT, NVOCMP_PGFULL, NVOCMP_PGHDRLEN, NVOCMP_PGHDROFS, NVOCMP_PGNACT, NVOCMP_PGRDY, and NVOCMP_read().
Referenced by NVOCMP_addItem(), and NVOCMP_expectCompApi().
NVOCMP_changePageState()
static void NVOCMP_changePageState (NVOCMP_nvHandle_t * pNvHandle, uint8_t pg, NVOCMP_pageState_t state) static
References NVINTF_SUCCESS, NVOCMP_PGACT, NVOCMP_PGHDROFS, and NVOCMP_writeByte().
Referenced by NVOCMP_compact(), NVOCMP_compactPage(), NVOCMP_eraseNvApi(), NVOCMP_findItem(), NVOCMP_getDstPage(), NVOCMP_initNv(), NVOCMP_restoreCache(), NVOCMP_scanPage(), and NVOCMP_writeItem().
NVOCMP_setPageState()
static void NVOCMP_setPageState (NVOCMP_nvHandle_t * pNvHandle, uint8_t pg, NVOCMP_pageState_t state) static
References NVINTF_SUCCESS, NVOCMP_ALLACTIVE, NVOCMP_PGACT, NVOCMP_PGHDRLEN, NVOCMP_SIGNATURE, NVOCMP_VERSION, and NVOCMP_write().
Referenced by NVOCMP_erase().
NVOCMP_setItemInactive()
static void NVOCMP_setItemInactive (NVOCMP_nvHandle_t * pNvHandle, uint8_t pg, uint16_t iOfs) static
References NVOCMP_ACTIVEIDBIT, NVOCMP_ALLACTIVE, NVOCMP_HDRVLDOFS, NVOCMP_PGHDRVER, NVOCMP_readByte(), NVOCMP_SOMEINACTIVE, and NVOCMP_writeByte().
Referenced by NVOCMP_deleteItemApi(), NVOCMP_doNextApi(), NVOCMP_findItem(), NVOCMP_findOffset(), NVOCMP_initNv(), NVOCMP_scanPage(), NVOCMP_updateItemApi(), NVOCMP_writeItem(), and NVOCMP_writeItemApi().
NVOCMP_readItem()
static uint8_t NVOCMP_readItem (NVOCMP_itemHdr_t * iHdr, uint16_t ofs, uint16_t len, void * pBuf, bool flag) static
References NVINTF_BADLENGTH, NVINTF_BADOFFSET, NVINTF_SUCCESS, NVOCMP_CRCONREAD, NVOCMP_read(), NVOCMP_verifyCRC(), and RAM_BUFFER_ADDRESS.
Referenced by NVOCMP_doNextApi(), NVOCMP_findItem(), NVOCMP_findOffset(), and NVOCMP_readItemApi().
NVOCMP_checkItem()
static uint8_t NVOCMP_checkItem (NVINTF_itemID_t * id, uint16_t len, NVOCMP_itemHdr_t * iHdr, uint8_t flag) static
References nvintf_itemid_t::itemID, NVINTF_BADITEMID, NVINTF_BADLENGTH, NVINTF_BADSUBID, NVINTF_BADSYSID, NVINTF_NOTREADY, NVINTF_SUCCESS, NVOCMP_ALERT, NVOCMP_ASSERT, NVOCMP_CMPRID, NVOCMP_MAXITEMID, NVOCMP_MAXLEN, NVOCMP_MAXSUBID, NVOCMP_MAXSYSID, NVOCMP_SIGNATURE, nvintf_itemid_t::subID, and nvintf_itemid_t::systemID.
Referenced by NVOCMP_createItemApi(), NVOCMP_deleteItemApi(), NVOCMP_getItemLenApi(), NVOCMP_readContItemApi(), NVOCMP_readItemApi(), NVOCMP_updateItemApi(), and NVOCMP_writeItemApi().
NVOCMP_read()
static void NVOCMP_read (uint8_t pg, uint16_t off, uint8_t * pBuf, uint16_t len) inline static
References NVOCMP_FLASHOFFSET.
Referenced by NVOCMP_addItem(), NVOCMP_compact(), NVOCMP_compactPage(), NVOCMP_doNVCRC(), NVOCMP_findItem(), NVOCMP_findOffset(), NVOCMP_findSignature(), NVOCMP_getDstPage(), NVOCMP_getFreeNvApi(), NVOCMP_readByte(), NVOCMP_readHeader(), NVOCMP_readItem(), NVOCMP_restoreCache(), NVOCMP_scanPage(), NVOCMP_setCompactHdr(), and NVOCMP_writeItem().
NVOCMP_write()
static uint8_t NVOCMP_write (uint8_t dstPg, uint16_t off, uint8_t * pBuf, uint16_t len) static
References NVINTF_FAILURE, NVINTF_LOWPOWER, NVINTF_SUCCESS, NVOCMP_ALERT, NVOCMP_FLASHACCESS, and NVOCMP_FLASHOFFSET.
Referenced by NVOCMP_compact(), NVOCMP_findItem(), NVOCMP_findSignature(), NVOCMP_setCompactHdr(), NVOCMP_setPageState(), NVOCMP_writeByte(), and NVOCMP_writeItem().
NVOCMP_readHeader()
static void NVOCMP_readHeader (uint8_t pg, uint16_t ofs, NVOCMP_itemHdr_t * iHdr, bool flag) static
References NVOCMP_ACTIVEIDBIT, NVOCMP_ALERT, NVOCMP_CMPRID, NVOCMP_FOLLOWBIT, NVOCMP_ITEMHDRLEN, NVOCMP_ONEBYTE, NVOCMP_read(), NVOCMP_SIGNATURE, NVOCMP_VALIDIDBIT, and RAM_BUFFER_ADDRESS.
Referenced by NVOCMP_compact(), NVOCMP_findItem(), NVOCMP_findOffset(), NVOCMP_findSignature(), NVOCMP_initNv(), and NVOCMP_scanPage().
NVOCMP_setCompactHdr()
static void NVOCMP_setCompactHdr (uint8_t dstPg, uint8_t pg, int16_t offset, uint16_t location) static
References DEFAULT_COMPACTHDR, NVOCMP_COMPACTHDRLEN, NVOCMP_read(), and NVOCMP_write().
Referenced by NVOCMP_compact(), NVOCMP_erase(), and NVOCMP_findSignature().
NVOCMP_findOffset()
static uint16_t NVOCMP_findOffset (uint8_t pg, uint16_t ofs) static
References FLASH_PAGE_SIZE, NVINTF_BADPARAM, NVINTF_NOTFOUND, NVINTF_SUCCESS, NVOCMP_ACTIVEIDBIT, NVOCMP_ALERT, NVOCMP_ASSERT, NVOCMP_CMPRID, NVOCMP_compactPage(), NVOCMP_DECPAGE, NVOCMP_disableCache(), NVOCMP_ERASEDBYTE, NVOCMP_ERASEDWORD, NVOCMP_EXCEPTION, NVOCMP_FINDANY, NVOCMP_FINDCONTENT, NVOCMP_FINDHMASK, NVOCMP_findItem(), NVOCMP_FINDITMID, NVOCMP_FINDLMASK, NVOCMP_FINDSTRICT, NVOCMP_FINDSYSID, NVOCMP_FOLLOWBIT, NVOCMP_INCPAGE, NVOCMP_ITEMHDRLEN, NVOCMP_NVSIZE, NVOCMP_PGDATAOFS, NVOCMP_read(), NVOCMP_readHeader(), NVOCMP_readItem(), NVOCMP_restoreCache(), NVOCMP_setItemInactive(), NVOCMP_VALIDIDBIT, and RAM_BUFFER_ADDRESS.
Referenced by NVOCMP_restoreCache(), and NVOCMP_scanPage().
NVOCMP_doNVCRC()
static uint8_t NVOCMP_doNVCRC (uint8_t pg, uint16_t ofs, uint16_t len, uint8_t crc, bool flag) static
References crc_update(), NVOCMP_read(), NVOCMP_XFERBLKMAX, and RAM_BUFFER_ADDRESS.
Referenced by NVOCMP_verifyCRC().
NVOCMP_doRAMCRC()
static uint8_t NVOCMP_doRAMCRC (uint8_t * input, uint16_t len, uint8_t crc) static
References crc_update().
Referenced by NVOCMP_verifyCRC(), and NVOCMP_writeItem().
NVOCMP_verifyCRC()
static uint8_t NVOCMP_verifyCRC (uint16_t iOfs, uint16_t len, uint8_t crc, uint8_t pg, bool flag) static
References NVINTF_CORRUPT, NVINTF_SUCCESS, NVOCMP_ALERT, NVOCMP_doNVCRC(), NVOCMP_doRAMCRC(), and NVOCMP_HDRCRCINC.
Referenced by NVOCMP_compact(), NVOCMP_findSignature(), and NVOCMP_readItem().
NVOCMP_readByte()
static uint8_t NVOCMP_readByte (uint8_t pg, uint16_t ofs) static
References NVOCMP_ONEBYTE, and NVOCMP_read().
Referenced by NVOCMP_restoreCache(), and NVOCMP_setItemInactive().
NVOCMP_writeByte()
static void NVOCMP_writeByte (uint8_t pg, uint16_t ofs, uint8_t bwv) static
References NVOCMP_write().
Referenced by NVOCMP_changePageState(), NVOCMP_compactPage(), NVOCMP_findItem(), NVOCMP_restoreCache(), and NVOCMP_setItemInactive().
NVOCMP_loadApiPtrs()
void NVOCMP_loadApiPtrs (NVINTF_nvFuncts_t * pfn)
References nvintf_nvfuncts_t::compactNV, nvintf_nvfuncts_t::createItem, nvintf_nvfuncts_t::deleteItem, nvintf_nvfuncts_t::doNext, nvintf_nvfuncts_t::eraseNV, nvintf_nvfuncts_t::expectComp, nvintf_nvfuncts_t::getFreeNV, nvintf_nvfuncts_t::getItemLen, nvintf_nvfuncts_t::initNV, nvintf_nvfuncts_t::lockNV, NVOCMP_compactNvApi(), NVOCMP_createItemApi(), NVOCMP_deleteItemApi(), NVOCMP_eraseNvApi(), NVOCMP_expectCompApi(), NVOCMP_getFreeNvApi(), NVOCMP_getItemLenApi(), NVOCMP_initNvApi(), NVOCMP_readContItemApi(), NVOCMP_readItemApi(), NVOCMP_updateItemApi(), NVOCMP_writeItemApi(), nvintf_nvfuncts_t::readContItem, nvintf_nvfuncts_t::readItem, nvintf_nvfuncts_t::unlockNV, nvintf_nvfuncts_t::updateItem, and nvintf_nvfuncts_t::writeItem.
NVOCMP_loadApiPtrsMin()
void NVOCMP_loadApiPtrsMin (NVINTF_nvFuncts_t * pfn)
References nvintf_nvfuncts_t::compactNV, nvintf_nvfuncts_t::createItem, nvintf_nvfuncts_t::deleteItem, nvintf_nvfuncts_t::doNext, nvintf_nvfuncts_t::eraseNV, nvintf_nvfuncts_t::expectComp, nvintf_nvfuncts_t::getFreeNV, nvintf_nvfuncts_t::getItemLen, nvintf_nvfuncts_t::initNV, nvintf_nvfuncts_t::lockNV, NVOCMP_compactNvApi(), NVOCMP_eraseNvApi(), NVOCMP_expectCompApi(), NVOCMP_getFreeNvApi(), NVOCMP_initNvApi(), NVOCMP_readItemApi(), NVOCMP_writeItemApi(), nvintf_nvfuncts_t::readContItem, nvintf_nvfuncts_t::readItem, nvintf_nvfuncts_t::unlockNV, nvintf_nvfuncts_t::updateItem, and nvintf_nvfuncts_t::writeItem.
NVOCMP_loadApiPtrsExt()
void NVOCMP_loadApiPtrsExt (NVINTF_nvFuncts_t * pfn)
References nvintf_nvfuncts_t::compactNV, nvintf_nvfuncts_t::createItem, nvintf_nvfuncts_t::deleteItem, nvintf_nvfuncts_t::doNext, nvintf_nvfuncts_t::eraseNV, nvintf_nvfuncts_t::expectComp, nvintf_nvfuncts_t::getFreeNV, nvintf_nvfuncts_t::getItemLen, nvintf_nvfuncts_t::initNV, nvintf_nvfuncts_t::lockNV, NVOCMP_compactNvApi(), NVOCMP_createItemApi(), NVOCMP_deleteItemApi(), NVOCMP_doNextApi(), NVOCMP_eraseNvApi(), NVOCMP_expectCompApi(), NVOCMP_getFreeNvApi(), NVOCMP_getItemLenApi(), NVOCMP_initNvApi(), NVOCMP_lockNvApi(), NVOCMP_readContItemApi(), NVOCMP_readItemApi(), NVOCMP_unlockNvApi(), NVOCMP_updateItemApi(), NVOCMP_writeItemApi(), nvintf_nvfuncts_t::readContItem, nvintf_nvfuncts_t::readItem, nvintf_nvfuncts_t::unlockNV, nvintf_nvfuncts_t::updateItem, and nvintf_nvfuncts_t::writeItem.
NVOCMP_setCheckVoltage()
void NVOCMP_setCheckVoltage (void * funcPtr)
References NVOCMP_FLASHOFFSET, NVOCMP_setLowVoltageCb(), and NVOCMP_voltCheckFptr.
Referenced by NVOCMP_initNvApi().
NVOCMP_disableCache()
static void NVOCMP_disableCache (uint32_t * vm) static
Referenced by NVOCMP_compact(), NVOCMP_findOffset(), and NVOCMP_findSignature().
NVOCMP_restoreCache()
static void NVOCMP_restoreCache (uint32_t vm) static
References FLASH_PAGE_SIZE, NVINTF_BADVERSION, NVINTF_FAILURE, NVINTF_LOWPOWER, NVINTF_SUCCESS, NVOCMP_ALERT, NVOCMP_ALLACTIVE, NVOCMP_changePageState(), NVOCMP_erase(), NVOCMP_EXCEPTION, NVOCMP_FINDANY, NVOCMP_findItem(), NVOCMP_findOffset(), NVOCMP_INCPAGE, NVOCMP_NULLOFFSET, NVOCMP_NULLPAGE, NVOCMP_NVSIZE, NVOCMP_NVTWOP, NVOCMP_PGACT, NVOCMP_PGDATAOFS, NVOCMP_PGFULL, NVOCMP_PGHDRLEN, NVOCMP_PGHDROFS, NVOCMP_PGHDRVER, NVOCMP_PGNACT, NVOCMP_PGNORMAL, NVOCMP_PGRDY, NVOCMP_PGXDST, NVOCMP_PGXSRC, NVOCMP_read(), NVOCMP_readByte(), NVOCMP_scanPage(), NVOCMP_SIGNATURE, NVOCMP_SOMEINACTIVE, NVOCMP_VERSION, NVOCMP_writeByte(), NVOCTP_PGDATAOFS, NVOCTP_SIGNATURE, NVOCTP_VERSION, THISPAGEHDR, XSRCENDHDR, and XSRCSTARTHDR.
Referenced by NVOCMP_compact(), NVOCMP_findOffset(), and NVOCMP_findSignature().
NVOCMP_findSignature()
static bool NVOCMP_findSignature (uint8_t pg, uint16_t * pSrcOff) static
References FLASH_PAGE_SIZE, NVINTF_SUCCESS, NVOCMP_ACTIVEIDBIT, NVOCMP_ADDPAGE, NVOCMP_ALERT, NVOCMP_ASSERT, NVOCMP_compact(), NVOCMP_COMPACT_DSTDONE, NVOCMP_COMPACT_FAILURE, NVOCMP_COMPACT_SRCDONE, NVOCMP_COMPACT_SUCCESS, NVOCMP_DECPAGE, NVOCMP_disableCache(), NVOCMP_INCPAGE, NVOCMP_ITEMHDRLEN, NVOCMP_PGDATAOFS, NVOCMP_read(), NVOCMP_readHeader(), NVOCMP_restoreCache(), NVOCMP_setCompactHdr(), NVOCMP_SIGNATURE, NVOCMP_VALIDIDBIT, NVOCMP_verifyCRC(), NVOCMP_write(), NVOCMP_XFERBLKMAX, RAM_BUFFER_ADDRESS, XSRCENDHDR, and XSRCSTARTHDR.
Referenced by NVOCMP_compact().
Variable Documentation
NVOCMP_nvsHandle
NVS_Handle NVOCMP_nvsHandle static
NVOCMP_nvsAttrs
NVS_Attrs NVOCMP_nvsAttrs static
NVOCMP_nvHandle
NVOCMP_nvHandle_t NVOCMP_nvHandle
NVOCMP_failF
uint8_t NVOCMP_failF = NVINTF_NOTREADY static
Referenced by NVOCMP_compactNvApi(), and NVOCMP_initNvApi().
NVOCMP_failW
uint8_t NVOCMP_failW static
Referenced by NVOCMP_compactNvApi(), NVOCMP_eraseNvApi(), NVOCMP_updateItemApi(), and NVOCMP_writeItemApi().
NVOCMP_gMutexPri
GateMutexPri_Handle NVOCMP_gMutexPri static
NVOCMP_itemBuffer
uint8_t NVOCMP_itemBuffer[NVOCMP_SMALLITEM] static
NVOCMP_voltCheckFptr
bool(* NVOCMP_voltCheckFptr) (void) static
Referenced by NVOCMP_setCheckVoltage().
gAction
NVOCMP_initAction_t gAction
NVOCMP_size
uint8_t NVOCMP_size
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale