TI-OpenThread: ncp.c File Reference
CC1352P_4_LAUNCHXL/thread/ncp_ftd/ncp.c File Reference
#include <openthread/config.h>
#include <openthread-core-config.h>
#include <assert.h>
#include <stddef.h>
#include <sched.h>
#include <pthread.h>
#include <unistd.h>
#include <ti/drivers/GPIO.h>
#include <openthread/ncp.h>
#include <openthread/instance.h>
#include "otsupport/otrtosapi.h"
#include "otsupport/otinstance.h"
#include "task_config.h"
#include "ti_drivers_config.h"
Functions
void * ncp_task (void *arg0)
void ncp_taskCreate (void)
void otPlatLog (otLogLevel aLogLevel, otLogRegion aLogRegion, const char *aFormat,...)
Variables
static char ncp_stack [TASK_CONFIG_NCP_TASK_STACK_SIZE]
Function Documentation
ncp_task()
void* ncp_task (void * arg0)
Main thread starting the NCP example within OpenThread.
References OtInstance_get(), OtRtosApi_lock(), OtRtosApi_unlock(), and OtStack_taskCreate().
Referenced by ncp_taskCreate().
ncp_taskCreate()
void ncp_taskCreate (void)
Create the task for the ncp application.
References ncp_stack, ncp_task(), TASK_CONFIG_NCP_TASK_PRIORITY, and TASK_CONFIG_NCP_TASK_STACK_SIZE.
otPlatLog()
void otPlatLog (otLogLevel aLogLevel, otLogRegion aLogRegion, const char * aFormat, ...)
Variable Documentation
ncp_stack
char ncp_stack[TASK_CONFIG_NCP_TASK_STACK_SIZE] static
Referenced by ncp_taskCreate().
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale