TI-OpenThread: otrtosapi.c File Reference
CC1352P_2_LAUNCHXL/thread/cli_ftd/otsupport/otrtosapi.c File Reference
Detailed Description
This file contains the implementation of the stack protective mutex.
#include "otrtosapi.h"
#include <assert.h>
#include <stdint.h>
#include <semaphore.h>
Functions
void OtRtosApi_init (void)
void OtRtosApi_lock (void)
void OtRtosApi_unlock (void)
Variables
static sem_t OtRtosApi_sem
Function Documentation
OtRtosApi_init()
void OtRtosApi_init (void)
Initialize the RTOS mutex protecting the OpenThread APIs.
Documented in ot_rtos_api.h.
Referenced by OtStack_taskCreate().
OtRtosApi_lock()
void OtRtosApi_lock (void)
Lock the OpenThread Stack mutex.
Documented in ot_rtos_api.h.
Referenced by app_postEvt(), cli_task(), DoorLock_task(), Empty_postEvt(), empty_task(), GraphicExt_requestProcess(), ncp_task(), oad_sendRegMsg(), oad_sendReqMsg(), oad_sendRspMsg(), oad_setupCoapServer(), OtInstance_get(), OtStack_joinConfiguredNetwork(), OtStack_joinNetwork(), OtStack_setupInterfaceAndNetwork(), OtStack_setupNetwork(), OtStack_task(), processEvent(), setupCoapServer(), Shade_postEvt(), Shade_task(), TempSensor_postEvt(), TempSensor_task(), tempSensorReport(), Thermostat_task(), tiopCUIInit(), uiActionProcessConfigureChannel(), and uiActionProcessConfigurePanId().
OtRtosApi_unlock()
void OtRtosApi_unlock (void)
Unlock the OpenThread Stack mutex.
Documented in ot_rtos_api.h.
Referenced by app_postEvt(), cli_task(), DoorLock_task(), Empty_postEvt(), empty_task(), GraphicExt_requestProcess(), ncp_task(), oad_sendRegMsg(), oad_sendReqMsg(), oad_sendRspMsg(), oad_setupCoapServer(), OtInstance_get(), OtStack_joinConfiguredNetwork(), OtStack_joinNetwork(), OtStack_setupInterfaceAndNetwork(), OtStack_setupNetwork(), OtStack_task(), processEvent(), setupCoapServer(), Shade_postEvt(), Shade_task(), TempSensor_postEvt(), TempSensor_task(), tempSensorReport(), Thermostat_task(), tiopCUIInit(), uiActionProcessConfigureChannel(), and uiActionProcessConfigurePanId().
Variable Documentation
OtRtosApi_sem
sem_t OtRtosApi_sem static
Referenced by OtRtosApi_init(), OtRtosApi_lock(), and OtRtosApi_unlock().
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale