TI-OpenThread: tempsensor.c File Reference
CC2652RB_LAUNCHXL/thread/temp_sensor/tempsensor.c File Reference
#include <openthread/config.h>
#include <openthread-core-config.h>
#include <assert.h>
#include <stddef.h>
#include <string.h>
#include <stdio.h>
#include <time.h>
#include <openthread/coap.h>
#include <openthread/ip6.h>
#include <openthread/link.h>
#include <openthread/platform/uart.h>
#include <openthread/thread.h>
#include <ti/devices/DeviceFamily.h>
#include <DeviceFamily_constructPath(driverlib/aon_batmon.h)>
#include <sched.h>
#include <pthread.h>
#include <mqueue.h>
#include <ti/drivers/GPIO.h>
#include "otsupport/otrtosapi.h"
#include "otsupport/otinstance.h"
#include "ti_drivers_config.h"
#include "tempsensor.h"
#include "utils/code_utils.h"
#include "disp_utils.h"
#include "otstack.h"
#include "tiop_ui.h"
#include "task_config.h"
#include "tiop_config.h"
Macros
#define ATTR_READ 0x01
#define ATTR_REPORT 0x04
#define ATTR_WRITE 0x02
#define DEFAULT_COAP_HEADER_TOKEN_LEN 2
#define TEMPSENSOR_PROC_QUEUE_MAX_MSG (8)
Size of the message queue for TempSensor_procQueue
#define TIOP_TEMPSENSOR_REPORTING_ADDRESS "ff02::1"
#define TIOP_TEMPSENSOR_REPORTING_INTERVAL 10000
#define TIOP_THERMOSTAT_ADDRESS "ff03::1"
Functions
static void coapHandleServer (void *aContext, otMessage *aMessage, const otMessageInfo *aMessageInfo)
Callback function registered with the Coap server. Processes the coap request from the clients.
static void configureReportingTimer (void)
Configure the timer.
void otPlatUartReceived (const uint8_t *aBuf, uint16_t aBufLength)
void otPlatUartSendDone (void)
static void processEvent (TempSensor_evt event)
Processes the events.
void processKeyChangeCB (Button_Handle _buttonHandle, Button_EventMask _buttonEvents)
Handles the key press events.
static void processOtStackEvents (uint8_t event, void *aContext)
Processes the OT stack events.
static void reportingTimeoutCB (union sigval val)
Callback function registered with the Coap server. Processes the coap request from the clients.
static otError setupCoapServer (otInstance *aInstance, const attrDesc_t *attr)
sets up the application coap server.
static void startReportingTimer (uint32_t timeout)
Starts the reporting timer.
void TempSensor_postEvt (TempSensor_evt event)
Posts an event to the Temperature Sensor task.
static void * TempSensor_task (void *arg0)
void TempSensor_taskCreate (void)
static void tempSensorReport (void)
Reports the temperature to another coap device.
Variables
static uint8_t attrTemperature [11] = "70"
const attrDesc_t coapAttr
static otCoapResource coapResource
static uint16_t peerPort = OT_DEFAULT_COAP_PORT
static otIp6Address reportingAddress
static timer_t reportTimerID
static Button_Handle rightButtonHandle
static bool serverSetup
static char stack [TASK_CONFIG_TEMPSENSOR_TASK_STACK_SIZE]
static char statusBuf [MAX_STATUS_LINE_VALUE_LEN]
static int temperatureValue = 70
static mqd_t TempSensor_procQueueDesc
const char TempSensor_procQueueName [] = "ts_process"
static otIp6Address thermostatAddress
Macro Definition Documentation
ATTR_READ
#define ATTR_READ 0x01
Referenced by setupCoapServer().
ATTR_WRITE
#define ATTR_WRITE 0x02
Referenced by setupCoapServer().
ATTR_REPORT
#define ATTR_REPORT 0x04
TIOP_TEMPSENSOR_REPORTING_INTERVAL
#define TIOP_TEMPSENSOR_REPORTING_INTERVAL 10000
Referenced by processEvent(), and tempSensorReport().
TIOP_THERMOSTAT_ADDRESS
#define TIOP_THERMOSTAT_ADDRESS "ff03::1"
Referenced by TempSensor_task().
TIOP_TEMPSENSOR_REPORTING_ADDRESS
#define TIOP_TEMPSENSOR_REPORTING_ADDRESS "ff02::1"
Referenced by TempSensor_task().
DEFAULT_COAP_HEADER_TOKEN_LEN
#define DEFAULT_COAP_HEADER_TOKEN_LEN 2
Referenced by tempSensorReport().
TEMPSENSOR_PROC_QUEUE_MAX_MSG
#define TEMPSENSOR_PROC_QUEUE_MAX_MSG (8)
Size of the message queue for TempSensor_procQueue
There are 7/10 events that can be raised, it is unlikely that they will all be raised at the same time. Add one buffer queue element.
Referenced by TempSensor_task().
Function Documentation
TempSensor_task()
void * TempSensor_task (void * arg0) static
Temp Sensor processing thread.
References attrTemperature, configureReportingTimer(), CUI_COLOR_RED, CUI_COLOR_RESET, CUI_COLOR_WHITE, DispUtils_open(), DISPUTILS_SERIALPRINTF, extAddress, OtInstance_get(), OtRtosApi_lock(), OtRtosApi_unlock(), OtStack_registerCallback(), OtStack_setupInterfaceAndNetwork(), OtStack_taskCreate(), processEvent(), processOtStackEvents(), reportingAddress, rightButtonHandle, statusBuf, TEMPSENSOR_PROC_QUEUE_MAX_MSG, TempSensor_procQueueDesc, TempSensor_procQueueName, thermostatAddress, TIOP_TEMPSENSOR_REPORTING_ADDRESS, TIOP_THERMOSTAT_ADDRESS, and tiopCUIInit().
Referenced by TempSensor_taskCreate().
reportingTimeoutCB()
static void reportingTimeoutCB (union sigval val) static
Callback function registered with the Coap server. Processes the coap request from the clients.
Parameters
val Argument passed by the clock if set up.
Returns
None
References TempSensor_evtReportTemp, and TempSensor_postEvt().
Referenced by configureReportingTimer().
configureReportingTimer()
static void configureReportingTimer (void) static
Configure the timer.
Returns
None
References reportingTimeoutCB(), and reportTimerID.
Referenced by TempSensor_task().
startReportingTimer()
static void startReportingTimer (uint32_t timeout) static
Starts the reporting timer.
Parameters
timeout Time in milliseconds.
Should be called after the reporting timer has been created, and after the global address has been registered.
References reportTimerID.
Referenced by processEvent(), and tempSensorReport().
tempSensorReport()
static void tempSensorReport (void) static
Reports the temperature to another coap device.
Returns
None
References attrTemperature, DEFAULT_COAP_HEADER_TOKEN_LEN, DISPUTILS_SERIALPRINTF, OtInstance_get(), OtRtosApi_lock(), OtRtosApi_unlock(), peerPort, reportingAddress, startReportingTimer(), temperatureValue, THERMOSTAT_TEMP_URI, and TIOP_TEMPSENSOR_REPORTING_INTERVAL.
Referenced by processEvent().
coapHandleServer()
static void coapHandleServer (void * aContext, otMessage * aMessage, const otMessageInfo * aMessageInfo) static
Callback function registered with the Coap server. Processes the coap request from the clients.
Parameters
aContext A pointer to the context information.
aMessage A pointer to the message.
aMessageInfo A pointer to the message info.
Returns
None
References attrTemperature.
Referenced by setupCoapServer().
setupCoapServer()
static otError setupCoapServer (otInstance * aInstance, const attrDesc_t * attr) static
sets up the application coap server.
Parameters
aInstance A pointer to the context information.
attr Attribute data
Returns
OT_ERROR_NONE if successful, else error code
References ATTR_READ, ATTR_WRITE, coapHandleServer(), coapResource, OtRtosApi_lock(), and OtRtosApi_unlock().
Referenced by processEvent().
processKeyChangeCB()
void processKeyChangeCB (Button_Handle _buttonHandle, Button_EventMask _buttonEvents)
Handles the key press events.
Handles the key pressed events for examples.
Parameters
_buttonHandle identifies which keys were pressed
_buttonEvents identifies the event that occurred on the key
Returns
None
References rightButtonHandle, TempSensor_evtKeyRight, and TempSensor_postEvt().
processOtStackEvents()
static void processOtStackEvents (uint8_t event, void * aContext) static
Processes the OT stack events.
Parameters
event event identifier
aContext context pointer for the event
Returns
None
References OT_STACK_EVENT_DEV_ROLE_CHANGED, OT_STACK_EVENT_NWK_DATA_CHANGED, OT_STACK_EVENT_NWK_JOINED, OT_STACK_EVENT_NWK_JOINED_FAILURE, TempSensor_evtDevRoleChanged, TempSensor_evtNwkJoined, TempSensor_evtNwkJoinFailure, TempSensor_evtNwkSetup, and TempSensor_postEvt().
Referenced by TempSensor_task().
processEvent()
static void processEvent (TempSensor_evt event) static
Processes the events.
Returns
None
References attrTemperature, coapAttr, CUI_COLOR_RED, CUI_COLOR_RESET, CUI_COLOR_WHITE, CUI_conn_join_fail, CUI_conn_joined, CUI_conn_joining, CUI_processMenuUpdate(), DISPUTILS_LCDPRINTF, DISPUTILS_SERIALPRINTF, OT_STACK_EVENT_NWK_JOIN_IN_PROGRESS, OtInstance_get(), OtRtosApi_lock(), OtRtosApi_unlock(), OtStack_joinConfiguredNetwork(), OtStack_joinState(), OtStack_setupInterfaceAndNetwork(), OtStack_setupNetwork(), reportingAddress, serverSetup, setupCoapServer(), startReportingTimer(), statusBuf, TempSensor_evtAddressValid, TempSensor_evtDevRoleChanged, TempSensor_evtKeyRight, TempSensor_evtNwkJoined, TempSensor_evtNwkJoinFailure, TempSensor_evtNwkSetup, TempSensor_evtReportTemp, TempSensor_postEvt(), tempSensorReport(), thermostatAddress, TIOP_TEMPSENSOR_REPORTING_INTERVAL, tiopCUIUpdateApp(), tiopCUIUpdateChannel(), tiopCUIUpdateConnStatus(), tiopCUIUpdateExtPANID(), tiopCUIUpdateMasterkey(), tiopCUIUpdateNwkName(), tiopCUIUpdatePANID(), tiopCUIUpdateRole(), and tiopCUIUpdateShortAddr().
Referenced by TempSensor_task().
otPlatUartReceived()
void otPlatUartReceived (const uint8_t * aBuf, uint16_t aBufLength)
Documented in openthread/platform/uart.h.
otPlatUartSendDone()
void otPlatUartSendDone (void)
Documented in openthread/platform/uart.h.
TempSensor_postEvt()
void TempSensor_postEvt (TempSensor_evt event)
Posts an event to the Temperature Sensor task.
Parameters
event event to post.
Returns
None
References CUI_ITEM_INTERCEPT_START, MAX_MENU_LINE_LEN, OtInstance_get(), OtRtosApi_lock(), OtRtosApi_unlock(), processMenuUpdateFn(), TempSensor_procQueueDesc, tiopCUINwkReset(), tiopCUIReset(), uiActionAttach(), and uiActionJoin().
Referenced by processEvent(), processKeyChangeCB(), processOtStackEvents(), and reportingTimeoutCB().
TempSensor_taskCreate()
void TempSensor_taskCreate (void)
Creation funciton for the temperature sensor application task.
References stack, TASK_CONFIG_TEMPSENSOR_TASK_PRIORITY, TASK_CONFIG_TEMPSENSOR_TASK_STACK_SIZE, and TempSensor_task().
Variable Documentation
reportTimerID
timer_t reportTimerID static
Referenced by configureReportingTimer(), and startReportingTimer().
thermostatAddress
otIp6Address thermostatAddress static
Referenced by processEvent(), and TempSensor_task().
reportingAddress
otIp6Address reportingAddress static
Referenced by processEvent(), TempSensor_task(), and tempSensorReport().
peerPort
uint16_t peerPort = OT_DEFAULT_COAP_PORT static
Referenced by tempSensorReport().
TempSensor_procQueueName
const char TempSensor_procQueueName[] = "ts_process"
Referenced by TempSensor_task().
TempSensor_procQueueDesc
mqd_t TempSensor_procQueueDesc static
Referenced by TempSensor_postEvt(), and TempSensor_task().
stack
char stack[TASK_CONFIG_TEMPSENSOR_TASK_STACK_SIZE] static
Referenced by TempSensor_taskCreate().
coapResource
otCoapResource coapResource static
Referenced by setupCoapServer().
attrTemperature
uint8_t attrTemperature[11] = "70" static
Referenced by coapHandleServer(), processEvent(), TempSensor_task(), and tempSensorReport().
temperatureValue
int temperatureValue = 70 static
Referenced by tempSensorReport().
coapAttr
const attrDesc_t coapAttr
Initial value:
= {
    TEMPSENSOR_TEMP_URI,
    (ATTR_READ|ATTR_REPORT),
    attrTemperature,
}
Referenced by processEvent().
rightButtonHandle
Button_Handle rightButtonHandle static
Referenced by processKeyChangeCB(), and TempSensor_task().
serverSetup
bool serverSetup static
Referenced by processEvent().
statusBuf
char statusBuf[MAX_STATUS_LINE_VALUE_LEN] static
Referenced by processEvent(), and TempSensor_task().
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale