TI-OpenThread: tiop_ui.h File Reference
LP_CC2652RSIP/thread/thermostat/tiop_ui.h File Reference
#include "cui.h"
#include <openthread/thread.h>
Enumerations
enum cuiConn {
CUI_conn_disabled, CUI_conn_joining, CUI_conn_joined, CUI_conn_join_fail,
CUI_conn_disabled, CUI_conn_joining, CUI_conn_joined, CUI_conn_join_fail,
CUI_conn_disabled, CUI_conn_joining, CUI_conn_joined, CUI_conn_join_fail,
CUI_conn_disabled, CUI_conn_joining, CUI_conn_joined, CUI_conn_join_fail,
CUI_conn_disabled, CUI_conn_joining, CUI_conn_joined, CUI_conn_join_fail,
CUI_conn_disabled, CUI_conn_joining, CUI_conn_joined, CUI_conn_join_fail,
CUI_conn_disabled, CUI_conn_joining, CUI_conn_joined, CUI_conn_join_fail,
CUI_conn_disabled, CUI_conn_joining, CUI_conn_joined, CUI_conn_join_fail,
CUI_conn_disabled, CUI_conn_joining, CUI_conn_joined, CUI_conn_join_fail,
CUI_conn_disabled, CUI_conn_joining, CUI_conn_joined, CUI_conn_join_fail,
CUI_conn_disabled, CUI_conn_joining, CUI_conn_joined, CUI_conn_join_fail,
CUI_conn_disabled, CUI_conn_joining, CUI_conn_joined, CUI_conn_join_fail,
CUI_conn_disabled, CUI_conn_joining, CUI_conn_joined, CUI_conn_join_fail,
CUI_conn_disabled, CUI_conn_joining, CUI_conn_joined, CUI_conn_join_fail,
CUI_conn_disabled, CUI_conn_joining, CUI_conn_joined, CUI_conn_join_fail,
CUI_conn_disabled, CUI_conn_joining, CUI_conn_joined, CUI_conn_join_fail,
CUI_conn_disabled, CUI_conn_joining, CUI_conn_joined, CUI_conn_join_fail,
CUI_conn_disabled, CUI_conn_joining, CUI_conn_joined, CUI_conn_join_fail,
CUI_conn_disabled, CUI_conn_joining, CUI_conn_joined, CUI_conn_join_fail,
CUI_conn_disabled, CUI_conn_joining, CUI_conn_joined, CUI_conn_join_fail,
CUI_conn_disabled, CUI_conn_joining, CUI_conn_joined, CUI_conn_join_fail,
CUI_conn_disabled, CUI_conn_joining, CUI_conn_joined, CUI_conn_join_fail,
CUI_conn_disabled, CUI_conn_joining, CUI_conn_joined, CUI_conn_join_fail,
CUI_conn_disabled, CUI_conn_joining, CUI_conn_joined, CUI_conn_join_fail,
CUI_conn_disabled, CUI_conn_joining, CUI_conn_joined, CUI_conn_join_fail,
CUI_conn_disabled, CUI_conn_joining, CUI_conn_joined, CUI_conn_join_fail,
CUI_conn_disabled, CUI_conn_joining, CUI_conn_joined, CUI_conn_join_fail,
CUI_conn_disabled, CUI_conn_joining, CUI_conn_joined, CUI_conn_join_fail,
CUI_conn_disabled, CUI_conn_joining, CUI_conn_joined, CUI_conn_join_fail,
CUI_conn_disabled, CUI_conn_joining, CUI_conn_joined, CUI_conn_join_fail,
CUI_conn_disabled, CUI_conn_joining, CUI_conn_joined, CUI_conn_join_fail,
CUI_conn_disabled, CUI_conn_joining, CUI_conn_joined, CUI_conn_join_fail,
CUI_conn_disabled, CUI_conn_joining, CUI_conn_joined, CUI_conn_join_fail,
CUI_conn_disabled, CUI_conn_joining, CUI_conn_joined, CUI_conn_join_fail,
CUI_conn_disabled, CUI_conn_joining, CUI_conn_joined, CUI_conn_join_fail,
CUI_conn_disabled, CUI_conn_joining, CUI_conn_joined, CUI_conn_join_fail
}
Functions
void processKeyChangeCB (Button_Handle _buttonHandle, Button_EventMask _buttonEvents)
Handles the key pressed events for examples.
void processMenuUpdateFn (void)
Handles CUI Menu update events for examples.
void tiopCUIInit (char *appString, Button_Handle *rightButtonHandle)
Initialize example CUI functionality.
void tiopCUINwkReset (const char _input, char *_pLines[3], CUI_cursorInfo_t *_pCurInfo)
Reset the OpenThread Instance as well as clear out the previous network data. CUI function type that is called when the Nwk reset menu option is selected in the Example CUI menu.
void tiopCUIReset (const char _input, char *_pLines[3], CUI_cursorInfo_t *_pCurInfo)
Reset the OpenThread Instance without clearing out previous network data. CUI function type that is called when the reset menu option is selected in the Example CUI menu.
void tiopCUIUpdateApp (char *appInfo)
Update Application specific CUI output line.
void tiopCUIUpdateChannel (uint8_t ch)
Update channel CUI output.
void tiopCUIUpdateConnStatus (cuiConn status)
Update connection status CUI output line.
void tiopCUIUpdateDeviceInfo (void)
Update device info CUI output line.
void tiopCUIUpdateExtPANID (otExtendedPanId extPan)
Update Extended panid CUI output.
void tiopCUIUpdateMasterkey (otMasterKey key)
Update masterkey CUI output.
void tiopCUIUpdateNwkName (const char *name)
Update network name CUI output.
void tiopCUIUpdatePANID (otPanId pan)
Update panid CUI output.
void tiopCUIUpdateRole (otDeviceRole role)
Update device role CUI output line.
void tiopCUIUpdateShortAddr (otShortAddress s)
Update short address CUI output.
void uiActionAttach (const int32_t _itemEntry)
Handles attach menu option event for examples.
void uiActionJoin (const int32_t _itemEntry)
Handles join menu option event for examples.
void uiActionProcessConfigureChannel (const char _input, char *_pLines[3], CUI_cursorInfo_t *_pCurInfo)
Handle reading user input into the channel configuration in CUI.
void uiActionProcessConfigurePanId (const char _input, char *_pLines[3], CUI_cursorInfo_t *_pCurInfo)
Handle reading user input into the panid configuration in CUI.
Enumeration Type Documentation
cuiConn
enum cuiConn
Connection status
Enumerator
CUI_conn_disabled
CUI_conn_joining
CUI_conn_joined
CUI_conn_join_fail
CUI_conn_disabled
CUI_conn_joining
CUI_conn_joined
CUI_conn_join_fail
CUI_conn_disabled
CUI_conn_joining
CUI_conn_joined
CUI_conn_join_fail
CUI_conn_disabled
CUI_conn_joining
CUI_conn_joined
CUI_conn_join_fail
CUI_conn_disabled
CUI_conn_joining
CUI_conn_joined
CUI_conn_join_fail
CUI_conn_disabled
CUI_conn_joining
CUI_conn_joined
CUI_conn_join_fail
CUI_conn_disabled
CUI_conn_joining
CUI_conn_joined
CUI_conn_join_fail
CUI_conn_disabled
CUI_conn_joining
CUI_conn_joined
CUI_conn_join_fail
CUI_conn_disabled
CUI_conn_joining
CUI_conn_joined
CUI_conn_join_fail
CUI_conn_disabled
CUI_conn_joining
CUI_conn_joined
CUI_conn_join_fail
CUI_conn_disabled
CUI_conn_joining
CUI_conn_joined
CUI_conn_join_fail
CUI_conn_disabled
CUI_conn_joining
CUI_conn_joined
CUI_conn_join_fail
CUI_conn_disabled
CUI_conn_joining
CUI_conn_joined
CUI_conn_join_fail
CUI_conn_disabled
CUI_conn_joining
CUI_conn_joined
CUI_conn_join_fail
CUI_conn_disabled
CUI_conn_joining
CUI_conn_joined
CUI_conn_join_fail
CUI_conn_disabled
CUI_conn_joining
CUI_conn_joined
CUI_conn_join_fail
CUI_conn_disabled
CUI_conn_joining
CUI_conn_joined
CUI_conn_join_fail
CUI_conn_disabled
CUI_conn_joining
CUI_conn_joined
CUI_conn_join_fail
CUI_conn_disabled
CUI_conn_joining
CUI_conn_joined
CUI_conn_join_fail
CUI_conn_disabled
CUI_conn_joining
CUI_conn_joined
CUI_conn_join_fail
CUI_conn_disabled
CUI_conn_joining
CUI_conn_joined
CUI_conn_join_fail
CUI_conn_disabled
CUI_conn_joining
CUI_conn_joined
CUI_conn_join_fail
CUI_conn_disabled
CUI_conn_joining
CUI_conn_joined
CUI_conn_join_fail
CUI_conn_disabled
CUI_conn_joining
CUI_conn_joined
CUI_conn_join_fail
CUI_conn_disabled
CUI_conn_joining
CUI_conn_joined
CUI_conn_join_fail
CUI_conn_disabled
CUI_conn_joining
CUI_conn_joined
CUI_conn_join_fail
CUI_conn_disabled
CUI_conn_joining
CUI_conn_joined
CUI_conn_join_fail
CUI_conn_disabled
CUI_conn_joining
CUI_conn_joined
CUI_conn_join_fail
CUI_conn_disabled
CUI_conn_joining
CUI_conn_joined
CUI_conn_join_fail
CUI_conn_disabled
CUI_conn_joining
CUI_conn_joined
CUI_conn_join_fail
CUI_conn_disabled
CUI_conn_joining
CUI_conn_joined
CUI_conn_join_fail
CUI_conn_disabled
CUI_conn_joining
CUI_conn_joined
CUI_conn_join_fail
CUI_conn_disabled
CUI_conn_joining
CUI_conn_joined
CUI_conn_join_fail
CUI_conn_disabled
CUI_conn_joining
CUI_conn_joined
CUI_conn_join_fail
CUI_conn_disabled
CUI_conn_joining
CUI_conn_joined
CUI_conn_join_fail
CUI_conn_disabled
CUI_conn_joining
CUI_conn_joined
CUI_conn_join_fail
Function Documentation
tiopCUIInit()
void tiopCUIInit (char * appString, Button_Handle * rightButtonHandle)
Initialize example CUI functionality.
Parameters
rightButtonHandle a pointer to the button handle to be filled for the application
appString contains the application specific string to be output
Returns
None
documented in tiop_ui.h
References appInfoLine, clientHandle, CUI_clientParams_t::clientName, connStatusLine, CUI_clientOpen(), CUI_clientParamsInit(), CUI_conn_disabled, CUI_init(), CUI_paramsInit(), CUI_registerMenu(), CUI_statusLineResourceRequest(), deviceInfoLine, deviceRoleLine, display_channel, extAddress, extPanId, greenLedHandle, CUI_params_t::manageUart, masterkey, MAX_CLIENT_NAME_LEN, CUI_clientParams_t::maxStatusLines, nwkInfoLine1, nwkInfoLine2, nwkInfoLine3, nwkName, OtInstance_get(), OtRtosApi_lock(), OtRtosApi_unlock(), panid, processKeyChangeCB(), redLedHandle, shortAddr, tiopCUIUpdateApp(), tiopCUIUpdateConnStatus(), tiopCUIUpdateDeviceInfo(), tiopCUIUpdateMasterkey(), tiopCUIUpdateNwkName(), tiopCUIUpdatePANID(), and tiopCUIUpdateRole().
Referenced by DoorLock_task(), empty_task(), Shade_task(), TempSensor_task(), and Thermostat_task().
tiopCUIUpdateRole()
void tiopCUIUpdateRole (otDeviceRole role)
Update device role CUI output line.
Parameters
role contains the role the device is in the network
Returns
None
documented in tiop_ui.h
References clientHandle, CUI_COLOR_RED, CUI_COLOR_RESET, CUI_statusLinePrintf(), deviceRoleLine, greenLedHandle, and redLedHandle.
Referenced by processEvent(), and tiopCUIInit().
tiopCUIUpdateDeviceInfo()
void tiopCUIUpdateDeviceInfo (void)
Update device info CUI output line.
Returns
None
documented in tiop_ui.h
References clientHandle, CUI_COLOR_MAGENTA, CUI_COLOR_RED, CUI_COLOR_RESET, CUI_statusLinePrintf(), deviceInfoLine, and extAddress.
Referenced by tiopCUIInit().
tiopCUIUpdatePANID()
void tiopCUIUpdatePANID (otPanId pan)
Update panid CUI output.
Parameters
pan contains the panid for the network
Returns
None
documented in tiop_ui.h
References clientHandle, CUI_COLOR_RESET, CUI_COLOR_YELLOW, CUI_statusLinePrintf(), display_channel, nwkInfoLine3, panid, and shortAddr.
Referenced by processEvent(), tiopCUIInit(), and uiActionProcessConfigurePanId().
tiopCUIUpdateChannel()
void tiopCUIUpdateChannel (uint8_t ch)
Update channel CUI output.
Parameters
ch contains the channel for the network
Returns
None
documented in tiop_ui.h
References clientHandle, CUI_COLOR_RESET, CUI_COLOR_YELLOW, CUI_statusLinePrintf(), display_channel, nwkInfoLine3, panid, and shortAddr.
Referenced by processEvent(), and uiActionProcessConfigureChannel().
tiopCUIUpdateShortAddr()
void tiopCUIUpdateShortAddr (otShortAddress s)
Update short address CUI output.
Parameters
s contains the short address for the device
Returns
None
documented in tiop_ui.h
References clientHandle, CUI_COLOR_RESET, CUI_COLOR_YELLOW, CUI_statusLinePrintf(), display_channel, nwkInfoLine3, panid, and shortAddr.
Referenced by processEvent().
tiopCUIUpdateMasterkey()
void tiopCUIUpdateMasterkey (otMasterKey key)
Update masterkey CUI output.
Parameters
key contains the masterkey for the network
Returns
None
documented in tiop_ui.h
References clientHandle, CUI_COLOR_MAGENTA, CUI_COLOR_RESET, CUI_statusLinePrintf(), masterkey, and nwkInfoLine2.
Referenced by processEvent(), and tiopCUIInit().
tiopCUIUpdateExtPANID()
void tiopCUIUpdateExtPANID (otExtendedPanId extPan)
Update Extended panid CUI output.
Parameters
extPan contains the extended pan id for the network
Returns
None
documented in tiop_ui.h
References clientHandle, CUI_COLOR_MAGENTA, CUI_COLOR_RESET, CUI_statusLinePrintf(), extPanId, nwkInfoLine1, and nwkName.
Referenced by processEvent().
tiopCUIUpdateNwkName()
void tiopCUIUpdateNwkName (const char * name)
Update network name CUI output.
Parameters
name contains the name of the network
Note
name must be in persistent memory as the pointer is kept for future screen refreshes
Returns
None
documented in tiop_ui.h
References clientHandle, CUI_COLOR_MAGENTA, CUI_COLOR_RESET, CUI_statusLinePrintf(), extPanId, nwkInfoLine1, and nwkName.
Referenced by processEvent(), and tiopCUIInit().
tiopCUIUpdateConnStatus()
void tiopCUIUpdateConnStatus (cuiConn status)
Update connection status CUI output line.
Parameters
status contains the connection status for the device to the network
Returns
None
documented in tiop_ui.h
References clientHandle, connStatusLine, CUI_COLOR_RED, CUI_COLOR_RESET, CUI_conn_disabled, CUI_conn_join_fail, CUI_conn_joined, CUI_conn_joining, and CUI_statusLinePrintf().
Referenced by processEvent(), and tiopCUIInit().
tiopCUIUpdateApp()
void tiopCUIUpdateApp (char * appInfo)
Update Application specific CUI output line.
Parameters
appInfo contains the application specific string to be output
Returns
None
documented in tiop_ui.h
References appInfoLine, clientHandle, and CUI_statusLinePrintf().
Referenced by processEvent(), and tiopCUIInit().
uiActionProcessConfigurePanId()
void uiActionProcessConfigurePanId (const char _input, char * _pLines[3], CUI_cursorInfo_t * _pCurInfo)
Handle reading user input into the panid configuration in CUI.
Returns
None
documented in tiop_ui.h
References CUI_cursorInfo_t::col, CUI_INPUT_DOWN, CUI_INPUT_EXECUTE, CUI_INPUT_LEFT, CUI_INPUT_RIGHT, CUI_INPUT_UP, CUI_IS_INPUT_HEX, CUI_ITEM_INTERCEPT_START, CUI_ITEM_INTERCEPT_STOP, CUI_ITEM_PREVIEW, OtInstance_get(), OtRtosApi_lock(), OtRtosApi_unlock(), CUI_cursorInfo_t::row, and tiopCUIUpdatePANID().
uiActionProcessConfigureChannel()
void uiActionProcessConfigureChannel (const char _input, char * _pLines[3], CUI_cursorInfo_t * _pCurInfo)
Handle reading user input into the channel configuration in CUI.
Returns
None
documented in tiop_ui.h
References CUI_cursorInfo_t::col, CUI_INPUT_DOWN, CUI_INPUT_EXECUTE, CUI_INPUT_LEFT, CUI_INPUT_RIGHT, CUI_INPUT_UP, CUI_IS_INPUT_NUM, CUI_ITEM_INTERCEPT_START, CUI_ITEM_INTERCEPT_STOP, CUI_ITEM_PREVIEW, display_channel, OtInstance_get(), OtRtosApi_lock(), OtRtosApi_unlock(), CUI_cursorInfo_t::row, and tiopCUIUpdateChannel().
uiActionAttach()
void uiActionAttach (const int32_t _itemEntry)
Handles attach menu option event for examples.
Returns
None
uiActionJoin()
void uiActionJoin (const int32_t _itemEntry)
Handles join menu option event for examples.
Returns
None
processKeyChangeCB()
void processKeyChangeCB (Button_Handle _buttonHandle, Button_EventMask _buttonEvents)
Handles the key pressed events for examples.
Returns
None
Handles the key pressed events for examples.
Parameters
_buttonHandle identifies which keys were pressed
_buttonEvents identifies the event that occurred on the key
Returns
None
References app_postEvt(), DoorLock_evtKeyRight, Empty_evtKeyRight, Empty_postEvt(), rightButtonHandle, Shade_evtKeyRight, Shade_postEvt(), TempSensor_evtKeyRight, TempSensor_postEvt(), Thermostat_evtKeyRight, and Thermostat_postEvt().
Referenced by DoorLock_task(), setupCoapServer(), and tiopCUIInit().
processMenuUpdateFn()
void processMenuUpdateFn (void)
Handles CUI Menu update events for examples.
Returns
None
tiopCUINwkReset()
void tiopCUINwkReset (const char _input, char * _pLines[3], CUI_cursorInfo_t * _pCurInfo)
Reset the OpenThread Instance as well as clear out the previous network data. CUI function type that is called when the Nwk reset menu option is selected in the Example CUI menu.
Returns
None
tiopCUIReset()
void tiopCUIReset (const char _input, char * _pLines[3], CUI_cursorInfo_t * _pCurInfo)
Reset the OpenThread Instance without clearing out previous network data. CUI function type that is called when the reset menu option is selected in the Example CUI menu.
Returns
None
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale