TI-OpenThread: tempsensor.h File Reference
LP_CC2652RSIP/thread/temp_sensor/tempsensor.h File Reference
Macros
#define TEMPSENSOR_TEMP_URI "tempsensor/temperature"
#define THERMOSTAT_TEMP_URI "thermostat/temperature"
Enumerations
enum TempSensor_evt {
TempSensor_evtReportTemp, TempSensor_evtNwkSetup, TempSensor_evtDevRoleChanged, TempSensor_evtAddressValid,
TempSensor_evtKeyRight, TempSensor_evtNwkJoined, TempSensor_evtNwkJoinFailure, TempSensor_evtReportTemp,
TempSensor_evtNwkSetup, TempSensor_evtDevRoleChanged, TempSensor_evtAddressValid, TempSensor_evtKeyRight,
TempSensor_evtNwkJoined, TempSensor_evtNwkJoinFailure, TempSensor_evtReportTemp, TempSensor_evtNwkSetup,
TempSensor_evtDevRoleChanged, TempSensor_evtAddressValid, TempSensor_evtKeyRight, TempSensor_evtNwkJoined,
TempSensor_evtNwkJoinFailure, TempSensor_evtReportTemp, TempSensor_evtNwkSetup, TempSensor_evtDevRoleChanged,
TempSensor_evtAddressValid, TempSensor_evtKeyRight, TempSensor_evtNwkJoined, TempSensor_evtNwkJoinFailure,
TempSensor_evtReportTemp, TempSensor_evtNwkSetup, TempSensor_evtDevRoleChanged, TempSensor_evtAddressValid,
TempSensor_evtKeyRight, TempSensor_evtNwkJoined, TempSensor_evtNwkJoinFailure, TempSensor_evtReportTemp,
TempSensor_evtNwkSetup, TempSensor_evtDevRoleChanged, TempSensor_evtAddressValid, TempSensor_evtKeyRight,
TempSensor_evtNwkJoined, TempSensor_evtNwkJoinFailure
}
Functions
void TempSensor_postEvt (TempSensor_evt event)
Posts an event to the Temperature Sensor task.
Macro Definition Documentation
TEMPSENSOR_TEMP_URI
#define TEMPSENSOR_TEMP_URI "tempsensor/temperature"
THERMOSTAT_TEMP_URI
#define THERMOSTAT_TEMP_URI "thermostat/temperature"
Enumeration Type Documentation
TempSensor_evt
enum TempSensor_evt
Temperature Sensor events.
Enumerator
TempSensor_evtReportTemp
TempSensor_evtNwkSetup
TempSensor_evtDevRoleChanged
TempSensor_evtAddressValid
TempSensor_evtKeyRight
TempSensor_evtNwkJoined
TempSensor_evtNwkJoinFailure
TempSensor_evtReportTemp
TempSensor_evtNwkSetup
TempSensor_evtDevRoleChanged
TempSensor_evtAddressValid
TempSensor_evtKeyRight
TempSensor_evtNwkJoined
TempSensor_evtNwkJoinFailure
TempSensor_evtReportTemp
TempSensor_evtNwkSetup
TempSensor_evtDevRoleChanged
TempSensor_evtAddressValid
TempSensor_evtKeyRight
TempSensor_evtNwkJoined
TempSensor_evtNwkJoinFailure
TempSensor_evtReportTemp
TempSensor_evtNwkSetup
TempSensor_evtDevRoleChanged
TempSensor_evtAddressValid
TempSensor_evtKeyRight
TempSensor_evtNwkJoined
TempSensor_evtNwkJoinFailure
TempSensor_evtReportTemp
TempSensor_evtNwkSetup
TempSensor_evtDevRoleChanged
TempSensor_evtAddressValid
TempSensor_evtKeyRight
TempSensor_evtNwkJoined
TempSensor_evtNwkJoinFailure
TempSensor_evtReportTemp
TempSensor_evtNwkSetup
TempSensor_evtDevRoleChanged
TempSensor_evtAddressValid
TempSensor_evtKeyRight
TempSensor_evtNwkJoined
TempSensor_evtNwkJoinFailure
Function Documentation
TempSensor_postEvt()
void TempSensor_postEvt (TempSensor_evt event)
Posts an event to the Temperature Sensor task.
Parameters
event event to post.
Returns
None
References CUI_ITEM_INTERCEPT_START, MAX_MENU_LINE_LEN, OtInstance_get(), OtRtosApi_lock(), OtRtosApi_unlock(), processMenuUpdateFn(), TempSensor_postEvt(), TempSensor_procQueueDesc, tiopCUINwkReset(), tiopCUIReset(), uiActionAttach(), and uiActionJoin().
Referenced by processEvent(), processKeyChangeCB(), processOtStackEvents(), reportingTimeoutCB(), and TempSensor_postEvt().
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale