TI-OpenThread: crc32.c File Reference
LP_CC2652RSIP/thread/doorlock_oad_secure/oad/crc32.c File Reference
#include "flash_interface.h"
#include "oad_image_header.h"
Macros
#define CRC32_BUF_SZ 256
#define CRC32_POLYNOMIAL ((uint32_t)0xEDB88320) /* reveresed version or 802.3 polynomial 0x04C11DB7 */
Functions
uint32_t CRC32_calc (uint8_t page, uint32_t pageSize, uint16_t offset, uint32_t len, bool useExtFl)
void * CRC32_memCpy (void *dest, const void *src, uint16_t len)
uint32_t CRC32_value (uint32_t inCRC)
Macro Definition Documentation
CRC32_POLYNOMIAL
#define CRC32_POLYNOMIAL ((uint32_t)0xEDB88320) /* reveresed version or 802.3 polynomial 0x04C11DB7 */
Referenced by CRC32_value().
CRC32_BUF_SZ
#define CRC32_BUF_SZ 256
Referenced by CRC32_calc().
Function Documentation
CRC32_memCpy()
void* CRC32_memCpy (void * dest, const void * src, uint16_t len)
Referenced by CRC32_calc().
CRC32_value()
uint32_t CRC32_value (uint32_t inCRC)
References CRC32_POLYNOMIAL.
Referenced by CRC32_calc().
CRC32_calc()
uint32_t CRC32_calc (uint8_t page, uint32_t pageSize, uint16_t offset, uint32_t len, bool useExtFl)
References CRC32_BUF_SZ, CRC32_memCpy(), CRC32_value(), EFL_FLASH_SIZE, IMG_DATA_OFFSET, MAX_ONCHIP_FLASH_PAGES, and readFlashPg().
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale