TI-OpenThread: alarm_micro.c File Reference
LP_CC2652RSIP/thread/oad_cli/platform/alarm_micro.c File Reference
#include <openthread/config.h>
#include <stdbool.h>
#include <stdint.h>
#include <time.h>
#include <openthread/platform/alarm-micro.h>
#include "system.h"
Functions
void AlarmMicro_handler (union sigval val)
uint32_t otPlatAlarmMicroGetNow (void)
void otPlatAlarmMicroStartAt (otInstance *aInstance, uint32_t aT0, uint32_t aDt)
void otPlatAlarmMicroStop (otInstance *aInstance)
void platformAlarmMicroInit (void)
void platformAlarmMicroProcess (otInstance *aInstance)
Variables
static bool AlarmMicro_running = false
static uint32_t AlarmMicro_time = 0
static uint32_t AlarmMicro_time0 = 0
static timer_t AlarmMicro_timerid = 0
Function Documentation
AlarmMicro_handler()
void AlarmMicro_handler (union sigval val)
Handler for the POSIX clock callback.
References platformAlarmMicroSignal().
Referenced by platformAlarmMicroInit().
platformAlarmMicroInit()
void platformAlarmMicroInit (void)
Function documented in system.h
References AlarmMicro_handler(), AlarmMicro_running, and AlarmMicro_timerid.
otPlatAlarmMicroGetNow()
uint32_t otPlatAlarmMicroGetNow (void)
Function documented in platform/alarm-micro.h
Referenced by otPlatAlarmMicroStartAt(), and platformAlarmMicroProcess().
otPlatAlarmMicroStartAt()
void otPlatAlarmMicroStartAt (otInstance * aInstance, uint32_t aT0, uint32_t aDt)
Function documented in platform/alarm-micro.h
References AlarmMicro_running, AlarmMicro_time, AlarmMicro_time0, AlarmMicro_timerid, otPlatAlarmMicroGetNow(), and platformAlarmMicroSignal().
otPlatAlarmMicroStop()
void otPlatAlarmMicroStop (otInstance * aInstance)
Function documented in platform/alarm-micro.h
References AlarmMicro_running, and AlarmMicro_timerid.
platformAlarmMicroProcess()
void platformAlarmMicroProcess (otInstance * aInstance)
Function documented in system.h
References AlarmMicro_running, AlarmMicro_time, AlarmMicro_time0, AlarmMicro_timerid, otPlatAlarmMicroGetNow(), and platformAlarmMicroSignal().
Variable Documentation
AlarmMicro_time0
uint32_t AlarmMicro_time0 = 0 static
Referenced by otPlatAlarmMicroStartAt(), and platformAlarmMicroProcess().
AlarmMicro_time
uint32_t AlarmMicro_time = 0 static
Referenced by otPlatAlarmMicroStartAt(), and platformAlarmMicroProcess().
AlarmMicro_timerid
timer_t AlarmMicro_timerid = 0 static
Referenced by otPlatAlarmMicroStartAt(), otPlatAlarmMicroStop(), platformAlarmMicroInit(), and platformAlarmMicroProcess().
AlarmMicro_running
bool AlarmMicro_running = false static
Referenced by otPlatAlarmMicroStartAt(), otPlatAlarmMicroStop(), platformAlarmMicroInit(), and platformAlarmMicroProcess().
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale