TI-OpenThread: otinstance.h File Reference
LP_CC2652RSIP/thread/thermostat/otsupport/otinstance.h File Reference
#include <openthread/instance.h>
Functions
otInstance * OtInstance_get (void)
Function Documentation
OtInstance_get()
otInstance* OtInstance_get (void)
Get a pointer to the OpenThread instance object.
Returns
Pointer to the OpenThread instance object.
Documented in otsupport/otinstance.h.
References OtRtosApi_lock(), OtRtosApi_unlock(), and OtStack_instance.
Referenced by app_postEvt(), cli_task(), DoorLock_task(), Empty_postEvt(), empty_task(), GraphicExt_requestProcess(), ncp_task(), OAD_open(), oad_sendRegMsg(), oad_sendReqMsg(), oad_sendRspMsg(), oad_timeoutCB(), OtStack_joinConfiguredNetwork(), OtStack_joinNetwork(), OtStack_setupInterfaceAndNetwork(), OtStack_setupNetwork(), OtStack_task(), processEvent(), Shade_postEvt(), Shade_task(), TempSensor_postEvt(), TempSensor_task(), tempSensorReport(), Thermostat_task(), tiopCUIInit(), uiActionProcessConfigureChannel(), and uiActionProcessConfigurePanId().
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale