TI-OpenThread: system.h File Reference
LP_CC2652RSIP/thread/thermostat/platform/system.h File Reference
#include <openthread-core-config.h>
#include <stdint.h>
#include <openthread/config.h>
#include <openthread/instance.h>
Functions
otError otPlatUartFlush (void)
void otSysInit (int argc, char *argv[])
void platformAlarmInit (void)
void platformAlarmMicroInit (void)
void platformAlarmMicroProcess (otInstance *aInstance)
void platformAlarmMicroSignal (void)
void platformAlarmProcess (otInstance *aInstance)
void platformAlarmSignal (void)
void platformDebugUartInit (void)
void platformRadioInit (void)
void platformRadioProcess (otInstance *aInstance, uintptr_t arg)
void platformRadioSignal (uintptr_t arg)
void platformRandomInit (void)
void platformRandomProcess (void)
void platformRandomSignal (void)
void platformSpiProcess (void)
void platformSpiSignal (void)
void platformUartProcess (uintptr_t arg)
void platformUartSignal (uintptr_t arg)
Variables
otInstance * sInstance
Function Documentation
otSysInit()
void otSysInit (int argc, char * argv[])
Initialize the platform support modules.
Function documented in system.h
References platformAlarmInit(), platformAlarmMicroInit(), platformDebugUartInit(), platformRadioInit(), and platformRandomInit().
Referenced by OtStack_task().
platformDebugUartInit()
void platformDebugUartInit (void)
Initialize the debug uart
platformAlarmInit()
void platformAlarmInit (void)
This method initializes the alarm service used by OpenThread.
Function documented in system.h
References Alarm_handler(), Alarm_running, and Alarm_timerid.
Referenced by otSysInit().
platformAlarmSignal()
void platformAlarmSignal (void)
Signal the processing loop to process the alarm module.
Callback from the alarm module indicating need for processing.
References OtStack_procQueueCmd_alarm, and OtStack_procQueueDesc.
Referenced by Alarm_handler(), otPlatAlarmMilliStartAt(), and platformAlarmProcess().
platformAlarmProcess()
void platformAlarmProcess (otInstance * aInstance)
This method performs alarm driver processing.
Function documented in system.h
References Alarm_running, Alarm_time, Alarm_time0, Alarm_timerid, otPlatAlarmMilliGetNow(), otPlatDiagModeGet(), and platformAlarmSignal().
Referenced by OtStack_task().
platformAlarmMicroInit()
void platformAlarmMicroInit (void)
This method initializes the alarm service used by OpenThread.
Function documented in system.h
References AlarmMicro_handler(), AlarmMicro_running, and AlarmMicro_timerid.
Referenced by otSysInit().
platformAlarmMicroSignal()
void platformAlarmMicroSignal (void)
Signal the processing loop to process the alarm module.
Callback from the alarm module indicating need for processing.
References OtStack_procQueueCmd_alarmu, and OtStack_procQueueDesc.
Referenced by AlarmMicro_handler(), otPlatAlarmMicroStartAt(), and platformAlarmMicroProcess().
platformAlarmMicroProcess()
void platformAlarmMicroProcess (otInstance * aInstance)
This method performs alarm driver processing.
Function documented in system.h
References AlarmMicro_running, AlarmMicro_time, AlarmMicro_time0, AlarmMicro_timerid, otPlatAlarmMicroGetNow(), and platformAlarmMicroSignal().
Referenced by OtStack_task().
platformRadioInit()
void platformRadioInit (void)
This method initializes the radio service used by OpenThread.
Function documented in system.h
References otPlatEntropyGet(), platformRadio_phyState_Disabled, rfCoreInitBufs(), rfCoreInitReceiveParams(), rfCoreInitSetupCmd(), seedRandom, and sState.
Referenced by otSysInit().
platformRadioSignal()
void platformRadioSignal (uintptr_t arg)
Callback from the radio module indicating need for processing.
References OtStack_procQueueCmd_radio, and OtStack_procQueueDesc.
Referenced by radioSignal().
platformRadioProcess()
void platformRadioProcess (otInstance * aInstance, uintptr_t arg)
This method performs radio driver processing.
Function documented in system.h This is called from the main process loop.
References clearRxQueue(), handleTxState(), IEEE802154_ACK_REQUEST, PLATFORM_RADIO_INVALID_RSSI, platformRadio_phyState_Disabled, platformRadio_phyState_EdScan, platformRadio_phyState_Receive, platformRadio_phyState_Sleep, platformRadio_phyState_Transmit, processRxQueue(), RF_EVENT_BUF_FULL, RF_EVENT_ED_SCAN_DONE, RF_EVENT_RX_ACK_DONE, RF_EVENT_RX_CMD_PREEMPTED, RF_EVENT_RX_CMD_STOP, RF_EVENT_RX_DONE, RF_EVENT_SLEEP_YIELD, RF_EVENT_TX_CMD_PREEMPTED, RF_EVENT_TX_DONE, rfCoreSendReceiveCmd(), sCsmaBackoffCmd, sEdScanCmd, sReceiveCmd, sReceiveCmdHandle, sRfHandle, sState, sTransmitCmd, and sTransmitRxAckCmd.
Referenced by OtStack_task().
platformRandomInit()
void platformRandomInit (void)
This method initializes the random number service used by OpenThread.
Function documented in system.h
References TRNG_handle.
Referenced by otSysInit().
platformRandomSignal()
void platformRandomSignal (void)
Callback from random module indicating need for processing.
Callback from the random generator module indicating need for processing.
References OtStack_procQueueCmd_random, and OtStack_procQueueDesc.
platformRandomProcess()
void platformRandomProcess (void)
This method performs random driver processing.
Function documented in system.h
Referenced by OtStack_task().
platformUartSignal()
void platformUartSignal (uintptr_t arg)
Signal the processing loop to process the uart module.
Callback from the alarm module indicating need for processing.
References OtStack_procQueueCmd_uart, and OtStack_procQueueDesc.
Referenced by uartReadCallback(), and uartWriteCallback().
platformUartProcess()
void platformUartProcess (uintptr_t arg)
This method performs uart driver processing.
Function documented in system.h
References otPlatUartFlush(), otPlatUartReceived(), otPlatUartSendDone(), PLATFORM_UART_EVENT_RX_DONE, PLATFORM_UART_EVENT_TX_DONE, PlatformUart_receiveBuffer, PlatformUart_receiveLen, and PlatformUart_uartHandle.
platformSpiSignal()
void platformSpiSignal (void)
Signal the processing loop to process the spi module.
Callback from the spi module indicating need for processing.
References OtStack_procQueueCmd_spi, and OtStack_procQueueDesc.
Referenced by platSpiCallback().
platformSpiProcess()
void platformSpiProcess (void)
This method performs spi driver processing.
References sContext, and sProcessCallback.
otPlatUartFlush()
otError otPlatUartFlush (void)
This method performs UART Flush.
Function documented in system.h
Referenced by platformUartProcess().
Variable Documentation
sInstance
otInstance* sInstance
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale