TI-OpenThread: oad_storage.h File Reference
LP_CC2652RSIP/thread/doorlock_oad_secure/oad/oad_storage.h File Reference
#include <stdint.h>
#include <stdbool.h>
#include <oad_image_header.h>
Data Structures
struct OADStorage_imgIdentifyPld_t
Macros
#define OADStorage_ATT_OVERHEAD 3
#define OADStorage_BLK_NUM_HDR_SZ 0
#define OADStorage_BLOCK_SIZE 128 + OADStorage_BLK_NUM_HDR_SZ
Enumerations
enum OADStorage_Status_t {
OADStorage_Status_Success, OADStorage_Failed, OADStorage_CrcError, OADStorage_FlashError,
OADStorage_Aborted, OADStorage_Rejected, OADStorage_Status_Success, OADStorage_Failed,
OADStorage_CrcError, OADStorage_FlashError, OADStorage_Aborted, OADStorage_Rejected,
OADStorage_Status_Success, OADStorage_Failed, OADStorage_CrcError, OADStorage_FlashError,
OADStorage_Aborted, OADStorage_Rejected, OADStorage_Status_Success, OADStorage_Failed,
OADStorage_CrcError, OADStorage_FlashError, OADStorage_Aborted, OADStorage_Rejected,
OADStorage_Status_Success, OADStorage_Failed, OADStorage_CrcError, OADStorage_FlashError,
OADStorage_Aborted, OADStorage_Rejected, OADStorage_Status_Success, OADStorage_Failed,
OADStorage_CrcError, OADStorage_FlashError, OADStorage_Aborted, OADStorage_Rejected
}
OADStorage_Status_t status codes.
Functions
bool OADStorage_checkFactoryImage (void)
void OADStorage_close (void)
uint8_t OADStorage_createFactoryImageBackup (void)
OADStorage_Status_t OADStorage_eraseImgPage (uint32_t page)
uint16_t OADStorage_getFactoryImage (void)
OADStorage_Status_t OADStorage_imgBlockRead (uint16_t blockNum, uint8_t *pBlockData)
OADStorage_Status_t OADStorage_imgBlockWrite (uint32_t blockNum, uint8_t *pBlockData, uint8_t len)
OADStorage_Status_t OADStorage_imgFinalise (void)
uint16_t OADStorage_imgIdentifyRead (uint8_t imageType, OADStorage_imgIdentifyPld_t *pImgId)
uint16_t OADStorage_imgIdentifyWrite (uint8_t *pValue)
void OADStorage_imgInfoRead (uint8_t *pimgInfo)
void OADStorage_init (void)
Macro Definition Documentation
OADStorage_ATT_OVERHEAD
#define OADStorage_ATT_OVERHEAD 3
OADStorage_BLK_NUM_HDR_SZ
#define OADStorage_BLK_NUM_HDR_SZ 0
OADStorage_BLOCK_SIZE
#define OADStorage_BLOCK_SIZE 128 + OADStorage_BLK_NUM_HDR_SZ
Enumeration Type Documentation
OADStorage_Status_t
enum OADStorage_Status_t
OADStorage_Status_t status codes.
Enumerator
OADStorage_Status_Success
Success.
OADStorage_Failed
Fail.
OADStorage_CrcError
Acknowledgment or Response Timed out.
OADStorage_FlashError
flash access error
OADStorage_Aborted
Canceled by application.
OADStorage_Rejected
OAD request rejected by application.
OADStorage_Status_Success
Success.
OADStorage_Failed
Fail.
OADStorage_CrcError
Acknowledgment or Response Timed out.
OADStorage_FlashError
flash access error
OADStorage_Aborted
Canceled by application.
OADStorage_Rejected
OAD request rejected by application.
OADStorage_Status_Success
Success.
OADStorage_Failed
Fail.
OADStorage_CrcError
Acknowledgment or Response Timed out.
OADStorage_FlashError
flash access error
OADStorage_Aborted
Canceled by application.
OADStorage_Rejected
OAD request rejected by application.
OADStorage_Status_Success
Success.
OADStorage_Failed
Fail.
OADStorage_CrcError
Acknowledgment or Response Timed out.
OADStorage_FlashError
flash access error
OADStorage_Aborted
Canceled by application.
OADStorage_Rejected
OAD request rejected by application.
OADStorage_Status_Success
Success.
OADStorage_Failed
Fail.
OADStorage_CrcError
Acknowledgment or Response Timed out.
OADStorage_FlashError
flash access error
OADStorage_Aborted
Canceled by application.
OADStorage_Rejected
OAD request rejected by application.
OADStorage_Status_Success
Success.
OADStorage_Failed
Fail.
OADStorage_CrcError
Acknowledgment or Response Timed out.
OADStorage_FlashError
flash access error
OADStorage_Aborted
Canceled by application.
OADStorage_Rejected
OAD request rejected by application.
Function Documentation
OADStorage_init()
void OADStorage_init (void)
References OADStorage_imgIdentifyPld_t::bimVer, img_common_header::bimVer, OADStorage_imgIdentifyPld_t::crcStat, img_common_header::crcStat, EXT_FLASH_PAGE, imgHdr::fixedHdr, FLASH_FAILURE, flash_open(), FLASH_SUCCESS, flashNumPages, flashPageSize, hasExternalFlash(), imageAddress, imagePage, OADStorage_imgIdentifyPld_t::imgCpStat, img_common_header::imgCpStat, OADStorage_imgIdentifyPld_t::imgID, img_common_header::imgID, OADStorage_imgIdentifyPld_t::imgNo, img_common_header::imgNo, OADStorage_imgIdentifyPld_t::imgType, img_common_header::imgType, OADStorage_imgIdentifyPld_t::len, img_common_header::len, OADStorage_imgIdentifyPld_t::metaVer, img_common_header::metaVer, OAD_EXTFL_ID_VAL, OAD_IMG_ID_LEN, OAD_IMG_ID_VAL, oadBlkTot, oadFindExtFlImgAddr(), OADStorage_BLK_NUM_HDR_SZ, OADStorage_BLOCK_SIZE, OADStorage_imgIdentifyRead(), readFlashPg(), OADStorage_imgIdentifyPld_t::softVer, img_common_header::softVer, and useExternalFlash.
Referenced by oad_processNtf(), and OAD_resume().
OADStorage_imgIdentifyRead()
uint16_t OADStorage_imgIdentifyRead (uint8_t imageType, OADStorage_imgIdentifyPld_t * pImgId)
OADStorage_imgIdentifyWrite()
uint16_t OADStorage_imgIdentifyWrite (uint8_t * pValue)
References candidateImageLength, EXT_FLASH_PAGE, FLASH_FAILURE, imageAddress, imagePage, OADStorage_imgIdentifyPld_t::imgType, metaPage, numBlksInImgHdr, oadBlkTot, oadCheckImageID(), oadFindExtFlImgAddr(), oadFindExtFlMetaPage(), oadImgBytesPerBlock, OADStorage_Status_Success, and useExternalFlash.
Referenced by oad_processNtf(), and OAD_resume().
OADStorage_imgBlockRead()
OADStorage_Status_t OADStorage_imgBlockRead (uint16_t blockNum, uint8_t * pBlockData)
References FLASH_FAILURE, FLASH_SUCCESS, imageAddress, oadImgBytesPerBlock, OADStorage_BLK_NUM_HDR_SZ, OADStorage_BLOCK_SIZE, OADStorage_FlashError, OADStorage_Status_Success, and readFlashPg().
OADStorage_imgInfoRead()
void OADStorage_imgInfoRead (uint8_t * pimgInfo)
OADStorage_imgBlockWrite()
OADStorage_Status_t OADStorage_imgBlockWrite (uint32_t blockNum, uint8_t * pBlockData, uint8_t len)
References EFL_PAGE_SIZE, eraseFlashPg(), imgHdr::fixedHdr, FLASH_FAILURE, FLASH_SUCCESS, imageAddress, imagePage, img_common_header::len, numBlksInImgHdr, oadImgBytesPerBlock, OADStorage_BLK_NUM_HDR_SZ, OADStorage_FlashError, OADStorage_Status_Success, oadValidateCandidateHdr(), and writeFlashPg().
Referenced by oad_writeImgBlock().
OADStorage_eraseImgPage()
OADStorage_Status_t OADStorage_eraseImgPage (uint32_t page)
References eraseFlashPg(), FLASH_SUCCESS, imagePage, OADStorage_FlashError, and OADStorage_Status_Success.
Referenced by oad_storage_resume().
OADStorage_imgFinalise()
OADStorage_Status_t OADStorage_imgFinalise (void)
References candidateImageType, ExtImageInfo_t::counter, CRC_VALID, img_common_header::crcStat, EFL_META_COPY_SZ, eraseFlashPg(), ExtImageInfo_t::extFlAddr, ExtImageInfo_t::fixedHdr, FLASH_FAILURE, FLASH_SUCCESS, imageAddress, imagePage, img_common_header::imgCpStat, metaPage, NEED_COPY, OAD_EXTFL_ID_VAL, OAD_IMG_HDR_LEN, OAD_IMG_ID_LEN, OAD_IMG_TYPE_APPSTACKLIB, OAD_IMG_TYPE_PERSISTENT_APP, oadCheckDL(), OADStorage_Failed, OADStorage_FlashError, OADStorage_Status_Success, readFlashPg(), useExternalFlash, and writeFlashPg().
Referenced by oad_checkDLComplete().
OADStorage_close()
void OADStorage_close (void)
References flash_close().
Referenced by OAD_close().
OADStorage_createFactoryImageBackup()
uint8_t OADStorage_createFactoryImageBackup (void)
References _imgHdr, img_common_header::crc32, CRC32_calc(), CRC_OFFSET, CRC_VALID, img_common_header::crcStat, DEFAULT_STATE, EFL_ADDR_META, EFL_PAGE_SIZE, eraseFlashPg(), EXT_FLASH_PAGE, imgHdr::fixedHdr, flash_close(), flash_open(), FLASH_SUCCESS, img_common_header::imgCpStat, img_common_header::imgID, imgHdr::imgPayload, img_common_header::imgType, img_common_header::len, OAD_EXTFL_ID_VAL, OAD_IMG_HDR_LEN, OAD_IMG_TYPE_FACTORY, oadEraseExtFlashPages(), oadFindFactImgAddr(), OADStorage_FlashError, OADStorage_Status_Success, img_seg_payload::startAddr, and writeFlash().
Referenced by OAD_open().
OADStorage_checkFactoryImage()
bool OADStorage_checkFactoryImage (void)
References CRC_INVALID, img_common_header::crcStat, EFL_ADDR_META_FACT_IMG, EFL_METADATA_LEN, imgHdr::fixedHdr, flash_close(), flash_open(), img_common_header::imgType, OAD_IMG_TYPE_FACTORY, and readFlash().
Referenced by OAD_open().
OADStorage_getFactoryImage()
uint16_t OADStorage_getFactoryImage (void)
References CRC_INVALID, img_common_header::crcStat, EFL_ADDR_META_FACT_IMG, EFL_METADATA_LEN, imgHdr::fixedHdr, flash_close(), flash_open(), img_common_header::imgType, OAD_IMG_TYPE_FACTORY, readFlash(), and img_common_header::techType.
Referenced by OAD_open().
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale