TI-OpenThread: graphicext.h File Reference
LP_CC2652RSIP/thread/thermostat/graphicext.h File Reference
#include <ti/display/Display.h>
#include <ti/display/DisplayExt.h>
#include <ti/sysbios/knl/Event.h>
#include <ti/grlib/grlib.h>
Data Structures
struct GraphicExt_sprite_t
Functions
void GraphicExt_animateBackground (Graphics_Image *frames, uint8_t startFrame, uint8_t endFrame, bool continuous)
Displays an animation by switching through different frames.
void GraphicExt_drawSprites (GraphicExt_sprite_t *spriteList, uint8_t spriteListLen, bool overlayBackground)
Draws a list of sprites on the screen.
void GraphicExt_initAnimationModule (Display_Handle *lcdHandle, uint32_t frameDuration)
Set up the animation timer.
void GraphicExt_processEvt (void)
Process an animation event.
void GraphicExt_requestProcess (void)
Request processing of event.
void GraphicExt_stopAnimate (void)
Stops a continuous animation.
Function Documentation
GraphicExt_initAnimationModule()
void GraphicExt_initAnimationModule (Display_Handle * lcdHandle, uint32_t frameDuration)
Set up the animation timer.
Parameters
lcdHandle handle for the LCD display
frameDuration time in milliseconds per each frame.
Returns
None
References animationTimerID, frameTime, GraphicExt_timerCallBack(), and lcdHdl.
Referenced by Thermostat_task().
GraphicExt_animateBackground()
void GraphicExt_animateBackground (Graphics_Image * frames, uint8_t startFrame, uint8_t endFrame, bool continuous)
Displays an animation by switching through different frames.
Parameters
frames array of frames to be displayed.
startFrame index of the initial frame to start the animation.
endFrame index of the last frame to be displayed.
continuous if true it will keep displaying the animation until GraphicExt_stopAnimate is called, otherwise the animation will be displayed once.
Returns
None
References backgroundFrames, contAnimation, currentEndFrame, currentFrame, currentStartFrame, GraphicExt_flushFrame(), and lcdHdl.
Referenced by processEvent(), and updateThermostatMode().
GraphicExt_stopAnimate()
void GraphicExt_stopAnimate (void)
Stops a continuous animation.
Returns
None
References animationTimerID.
Referenced by GraphicExt_flushFrame().
GraphicExt_drawSprites()
void GraphicExt_drawSprites (GraphicExt_sprite_t * spriteList, uint8_t spriteListLen, bool overlayBackground)
Draws a list of sprites on the screen.
Parameters
spriteList list of sprites to be drawn on screen.
spriteListLen length of sprite list.
overlayBackground if true it will draw the sprites on top of the current background set by GraphicExt_animateBackground, otherwise the background will be white.
Returns
None
References GraphicExt_flushSprites(), lcdHdl, listLength, and overlayBack.
Referenced by flushLcd().
GraphicExt_requestProcess()
void GraphicExt_requestProcess (void)
Request processing of event.
Used to indicate to the application that GraphicExt_processEvt should be called. This is usually called when the frame draw timeout expires.
References CUI_cursorInfo_t::col, CUI_INPUT_DOWN, CUI_INPUT_EXECUTE, CUI_INPUT_LEFT, CUI_INPUT_RIGHT, CUI_INPUT_UP, CUI_IS_INPUT_NUM, CUI_ITEM_INTERCEPT_START, CUI_ITEM_INTERCEPT_STOP, CUI_ITEM_PREVIEW, MAX_MENU_LINE_LEN, OtInstance_get(), OtRtosApi_lock(), OtRtosApi_unlock(), processMenuUpdateFn(), CUI_cursorInfo_t::row, setPoint, Thermostat_evtGraphicExt, Thermostat_evtSetPtChange, Thermostat_postEvt(), thermostat_setPoint(), thermostatSetPt, tiopCUINwkReset(), tiopCUIReset(), uiActionAttach(), and uiActionJoin().
GraphicExt_processEvt()
void GraphicExt_processEvt (void)
Process an animation event.
Returns
None
References GraphicExt_flushFrame(), and lcdHdl.
Referenced by processEvent().
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale