TI-OpenThread: graphicext.c File Reference
LP_CC2652RSIP/thread/thermostat/graphicext.c File Reference
#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>
#include "graphicext.h"
Functions
void GraphicExt_animateBackground (Graphics_Image *frames, uint8_t startFrame, uint8_t endFrame, bool continuous)
Displays an animation by switching through different frames.
void GraphicExt_drawSprites (GraphicExt_sprite_t *spriteList, uint8_t spriteListLen, bool overlayBackground)
Draws a list of sprites on the screen.
static void GraphicExt_flushFrame (Graphics_Context *context)
Flush the sprites after being drawn by GraphicExt_drawSprites.
static void GraphicExt_flushSprites (Graphics_Context *context)
Flush the sprites after being drawn by GraphicExt_drawSprites.
void GraphicExt_initAnimationModule (Display_Handle *lcdHandle, uint32_t frameDuration)
Set up the animation timer.
void GraphicExt_processEvt (void)
Process an animation event.
static bool GraphicExt_spInRange (uint8_t yPos, GraphicExt_sprite_t *sprite)
Determines if a sprite is within range.
void GraphicExt_stopAnimate (void)
Stops a continuous animation.
static void GraphicExt_timerCallBack (union sigval val)
Callback function for the timer timeout.
Variables
static timer_t animationTimerID
static Graphics_Image * backgroundFrames = NULL
static bool contAnimation = false
static uint8_t currentEndFrame
static uint8_t currentFrame
static uint8_t currentStartFrame
static struct itimerspec frameTime
static Display_Handle * lcdHdl
static uint8_t listLength
static bool overlayBack = false
static const uint32_t spriteImgPalette []
static GraphicExt_sprite_t * sprites = NULL
Function Documentation
GraphicExt_timerCallBack()
static void GraphicExt_timerCallBack (union sigval val) static
Callback function for the timer timeout.
Parameters
val Argument passed to CB if set when timer is initialized.
Returns
None
References GraphicExt_requestProcess().
Referenced by GraphicExt_initAnimationModule().
GraphicExt_flushSprites()
static void GraphicExt_flushSprites (Graphics_Context * context) static
Flush the sprites after being drawn by GraphicExt_drawSprites.
Parameters
context LCD Graphics context.
Returns
None
References backgroundFrames, currentFrame, GraphicExt_spInRange(), GraphicExt_sprite_t::image, listLength, overlayBack, GraphicExt_sprite_t::posX, GraphicExt_sprite_t::posY, and spriteImgPalette.
Referenced by GraphicExt_drawSprites(), and GraphicExt_flushFrame().
GraphicExt_flushFrame()
static void GraphicExt_flushFrame (Graphics_Context * context) static
Flush the sprites after being drawn by GraphicExt_drawSprites.
Parameters
context LCD Graphics context.
Returns
None
References animationTimerID, backgroundFrames, contAnimation, currentEndFrame, currentFrame, currentStartFrame, frameTime, GraphicExt_flushSprites(), GraphicExt_stopAnimate(), and overlayBack.
Referenced by GraphicExt_animateBackground(), and GraphicExt_processEvt().
GraphicExt_spInRange()
static bool GraphicExt_spInRange (uint8_t yPos, GraphicExt_sprite_t * sprite) static
Determines if a sprite is within range.
Parameters
yPos Y possition.
sprite Sprite to be compared vs yPos.
Returns
None
References GraphicExt_sprite_t::image, and GraphicExt_sprite_t::posY.
Referenced by GraphicExt_flushSprites().
GraphicExt_initAnimationModule()
void GraphicExt_initAnimationModule (Display_Handle * lcdHandle, uint32_t frameDuration)
Set up the animation timer.
Parameters
lcdHandle handle for the LCD display
frameDuration time in milliseconds per each frame.
Returns
None
References animationTimerID, frameTime, GraphicExt_timerCallBack(), and lcdHdl.
GraphicExt_animateBackground()
void GraphicExt_animateBackground (Graphics_Image * frames, uint8_t startFrame, uint8_t endFrame, bool continuous)
Displays an animation by switching through different frames.
Parameters
frames array of frames to be displayed.
startFrame index of the initial frame to start the animation.
endFrame index of the last frame to be displayed.
continuous if true it will keep displaying the animation until GraphicExt_stopAnimate is called, otherwise the animation will be displayed once.
Returns
None
References backgroundFrames, contAnimation, currentEndFrame, currentFrame, currentStartFrame, GraphicExt_flushFrame(), and lcdHdl.
GraphicExt_stopAnimate()
void GraphicExt_stopAnimate (void)
Stops a continuous animation.
Returns
None
References animationTimerID.
Referenced by GraphicExt_flushFrame().
GraphicExt_drawSprites()
void GraphicExt_drawSprites (GraphicExt_sprite_t * spriteList, uint8_t spriteListLen, bool overlayBackground)
Draws a list of sprites on the screen.
Parameters
spriteList list of sprites to be drawn on screen.
spriteListLen length of sprite list.
overlayBackground if true it will draw the sprites on top of the current background set by GraphicExt_animateBackground, otherwise the background will be white.
Returns
None
References GraphicExt_flushSprites(), lcdHdl, listLength, and overlayBack.
GraphicExt_processEvt()
void GraphicExt_processEvt (void)
Process an animation event.
Returns
None
References GraphicExt_flushFrame(), and lcdHdl.
Variable Documentation
animationTimerID
timer_t animationTimerID static
Referenced by GraphicExt_flushFrame(), GraphicExt_initAnimationModule(), and GraphicExt_stopAnimate().
frameTime
struct itimerspec frameTime static
Referenced by GraphicExt_flushFrame(), and GraphicExt_initAnimationModule().
lcdHdl
Display_Handle* lcdHdl static
Referenced by GraphicExt_animateBackground(), GraphicExt_drawSprites(), GraphicExt_initAnimationModule(), and GraphicExt_processEvt().
contAnimation
bool contAnimation = false static
Referenced by GraphicExt_animateBackground(), and GraphicExt_flushFrame().
overlayBack
bool overlayBack = false static
Referenced by GraphicExt_drawSprites(), GraphicExt_flushFrame(), and GraphicExt_flushSprites().
sprites
GraphicExt_sprite_t* sprites = NULL static
backgroundFrames
Graphics_Image* backgroundFrames = NULL static
Referenced by GraphicExt_animateBackground(), GraphicExt_flushFrame(), and GraphicExt_flushSprites().
listLength
uint8_t listLength static
Referenced by GraphicExt_drawSprites(), and GraphicExt_flushSprites().
currentStartFrame
uint8_t currentStartFrame static
Referenced by GraphicExt_animateBackground(), and GraphicExt_flushFrame().
currentEndFrame
uint8_t currentEndFrame static
Referenced by GraphicExt_animateBackground(), and GraphicExt_flushFrame().
currentFrame
uint8_t currentFrame static
Referenced by GraphicExt_animateBackground(), GraphicExt_flushFrame(), and GraphicExt_flushSprites().
spriteImgPalette
const uint32_t spriteImgPalette[] static
Initial value:
=
{
    0x000000,   0xffffff
}
Referenced by GraphicExt_flushSprites().
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale