TI-OpenThread: CC2652RB_LAUNCHXL_fxns.c File Reference
empty_ftd/CC2652RB_LAUNCHXL_fxns.c File Reference
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <ti/devices/cc13x2_cc26x2/driverlib/ioc.h>
#include <ti/devices/cc13x2_cc26x2/driverlib/cpu.h>
#include <ti/devices/cc13x2_cc26x2/driverlib/osc.h>
#include <ti/drivers/pin/PINCC26XX.h>
#include <ti/drivers/Board.h>
Functions
void Board_initHook ()
void CC2652RB_LAUNCHXL_sendExtFlashByte (PIN_Handle pinHandle, uint8_t byte)
void CC2652RB_LAUNCHXL_shutDownExtFlash (void)
void CC2652RB_LAUNCHXL_wakeUpExtFlash (void)
Function Documentation
CC2652RB_LAUNCHXL_sendExtFlashByte()
void CC2652RB_LAUNCHXL_sendExtFlashByte (PIN_Handle pinHandle, uint8_t byte)
Referenced by CC2652RB_LAUNCHXL_shutDownExtFlash().
CC2652RB_LAUNCHXL_wakeUpExtFlash()
void CC2652RB_LAUNCHXL_wakeUpExtFlash (void)
Referenced by CC2652RB_LAUNCHXL_shutDownExtFlash().
CC2652RB_LAUNCHXL_shutDownExtFlash()
void CC2652RB_LAUNCHXL_shutDownExtFlash (void)
References CC2652RB_LAUNCHXL_sendExtFlashByte(), and CC2652RB_LAUNCHXL_wakeUpExtFlash().
Referenced by Board_initHook().
Board_initHook()
void Board_initHook ()
References CC2652RB_LAUNCHXL_shutDownExtFlash().
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale