OpenThread: ThreadNetif Class Reference
ThreadNetif Class Reference
Core-netif
#include <thread_netif.hpp>
Public Member Functions
void Down (void)
bool IsTmfMessage (const Ip6::MessageInfo &aMessageInfo)
bool IsUp (void) const
otError RouteLookup (const Ip6::Address &aSource, const Ip6::Address &aDestination, uint8_t *aPrefixMatch)
otError SendMessage (Message &aMessage)
ThreadNetif (Instance &aInstance)
void Up (void)
Public Member Functions inherited from Netif
otError AddExternalUnicastAddress (const NetifUnicastAddress &aAddress)
otError AddUnicastAddress (NetifUnicastAddress &aAddress)
const NetifMulticastAddress * GetMulticastAddresses (void) const
otError GetNextExternalMulticast (uint8_t &aIterator, Address &aAddress) const
const NetifUnicastAddress * GetUnicastAddresses (void) const
bool IsMulticastPromiscuousEnabled (void) const
bool IsMulticastSubscribed (const Address &aAddress) const
bool IsUnicastAddress (const Address &aAddress) const
Netif (Instance &aInstance)
void RemoveAllExternalUnicastAddresses (void)
otError RemoveExternalUnicastAddress (const Address &aAddress)
otError RemoveUnicastAddress (const NetifUnicastAddress &aAddress)
void SetAddressCallback (otIp6AddressCallback aCallback, void *aCallbackContext)
void SetMulticastPromiscuous (bool aEnabled)
otError SubscribeAllRoutersMulticast (void)
otError SubscribeExternalMulticast (const Address &aAddress)
otError SubscribeMulticast (NetifMulticastAddress &aAddress)
void UnsubscribeAllExternalMulticastAddresses (void)
otError UnsubscribeAllRoutersMulticast (void)
otError UnsubscribeExternalMulticast (const Address &aAddress)
otError UnsubscribeMulticast (const NetifMulticastAddress &aAddress)
Public Member Functions inherited from InstanceLocator
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Public Member Functions inherited from LinkedListEntry< Netif >
const Netif * GetNext (void) const
Netif * GetNext (void)
void SetNext (Netif *aNext)
Static Private Member Functions
static otError TmfFilter (const Coap::Message &aMessage, const Ip6::MessageInfo &aMessageInfo, void *aContext)
Private Attributes
MeshCoP::ActiveDataset mActiveDataset
AnnounceBeginServer mAnnounceBegin
BackboneRouter::Leader mBackboneRouterLeader
Utils::ChildSupervisor mChildSupervisor
Coap::Coap mCoap
EnergyScanServer mEnergyScan
Ip6::Filter mIp6Filter
bool mIsUp
KeyManager mKeyManager
Lowpan::Lowpan mLowpan
Mac::Mac mMac
MeshForwarder mMeshForwarder
Mle::MleRouter mMleRouter
NetworkData::Leader mNetworkDataLeader
PanIdQueryServer mPanIdQuery
MeshCoP::PendingDataset mPendingDataset
Utils::SupervisionListener mSupervisionListener
Friends
class Instance
Additional Inherited Members
Protected Member Functions inherited from Netif
otError SubscribeAllNodesMulticast (void)
otError UnsubscribeAllNodesMulticast (void)
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Constructor & Destructor Documentation
ThreadNetif()
ThreadNetif (Instance & aInstance) explicit
This constructor initializes the Thread network interface.
Parameters
[in] aInstance A reference to the OpenThread instance.
References ThreadNetif::TmfFilter().
Member Function Documentation
Up()
void Up (void)
This method enables the Thread network interface.
References ot::kCoapUdpPort, ThreadNetif::mIsUp, OT_CHANGED_THREAD_NETIF_STATE, OT_NOOP, Netif::SubscribeAllNodesMulticast(), and VerifyOrExit.
Down()
void Down (void)
This method disables the Thread network interface.
References ThreadNetif::mIsUp, OT_CHANGED_THREAD_NETIF_STATE, OT_NOOP, Netif::RemoveAllExternalUnicastAddresses(), Netif::UnsubscribeAllExternalMulticastAddresses(), Netif::UnsubscribeAllNodesMulticast(), Netif::UnsubscribeAllRoutersMulticast(), and VerifyOrExit.
IsUp()
bool IsUp (void) const inline
This method indicates whether or not the Thread network interface is enabled.
Return values
TRUE If the Thread network interface is enabled.
FALSE If the Thread network interface is not enabled.
References ThreadNetif::mIsUp.
Referenced by otLinkSetEnabled(), and otLinkSetPromiscuous().
SendMessage()
otError SendMessage (Message & aMessage) inline
This method submits a message to the network interface.
Parameters
[in] aMessage A reference to the message.
Return values
OT_ERROR_NONE Successfully submitted the message to the interface.
References ThreadNetif::IsTmfMessage(), ThreadNetif::mMeshForwarder, ThreadNetif::RouteLookup(), MeshForwarder::SendMessage(), and ThreadNetif::TmfFilter().
RouteLookup()
otError RouteLookup (const Ip6::Address & aSource, const Ip6::Address & aDestination, uint8_t * aPrefixMatch)
This method performs a route lookup.
Parameters
[in] aSource A reference to the IPv6 source address.
[in] aDestination A reference to the IPv6 destination address.
[out] aPrefixMatch A pointer where the number of prefix match bits for the chosen route is stored.
Return values
OT_ERROR_NONE Successfully found a route.
OT_ERROR_NO_ROUTE Could not find a valid route.
References OT_ERROR_NO_ROUTE, and SuccessOrExit.
Referenced by ThreadNetif::SendMessage().
IsTmfMessage()
bool IsTmfMessage (const Ip6::MessageInfo & aMessageInfo)
This method returns whether Thread Management Framework Addressing Rules are met.
Return values
TRUE if Thread Management Framework Addressing Rules are met.
FALSE if Thread Management Framework Addressing Rules are not met.
References MessageInfo::GetPeerAddr(), MessageInfo::GetSockAddr(), Address::IsLinkLocal(), Address::IsLinkLocalMulticast(), Address::IsRealmLocalMulticast(), and VerifyOrExit.
Referenced by ThreadNetif::SendMessage(), and ThreadNetif::TmfFilter().
TmfFilter()
otError TmfFilter (const Coap::Message & aMessage, const Ip6::MessageInfo & aMessageInfo, void * aContext) static private
References ThreadNetif::IsTmfMessage(), OT_ERROR_NONE, OT_ERROR_NOT_TMF, and OT_UNUSED_VARIABLE.
Referenced by ThreadNetif::SendMessage(), and ThreadNetif::ThreadNetif().
Friends And Related Function Documentation
Instance
friend class Instance friend
Field Documentation
mCoap
Coap::Coap mCoap private
mActiveDataset
MeshCoP::ActiveDataset mActiveDataset private
mPendingDataset
MeshCoP::PendingDataset mPendingDataset private
mIp6Filter
Ip6::Filter mIp6Filter private
mKeyManager
KeyManager mKeyManager private
mLowpan
Lowpan::Lowpan mLowpan private
mMac
Mac::Mac mMac private
mMeshForwarder
MeshForwarder mMeshForwarder private
Referenced by ThreadNetif::SendMessage().
mMleRouter
Mle::MleRouter mMleRouter private
mNetworkDataLeader
NetworkData::Leader mNetworkDataLeader private
mIsUp
bool mIsUp private
Referenced by ThreadNetif::Down(), ThreadNetif::IsUp(), and ThreadNetif::Up().
mBackboneRouterLeader
BackboneRouter::Leader mBackboneRouterLeader private
mChildSupervisor
Utils::ChildSupervisor mChildSupervisor private
mSupervisionListener
Utils::SupervisionListener mSupervisionListener private
mAnnounceBegin
AnnounceBeginServer mAnnounceBegin private
mPanIdQuery
PanIdQueryServer mPanIdQuery private
mEnergyScan
EnergyScanServer mEnergyScan private
The documentation for this class was generated from the following files:
thread_netif.hpp
thread_netif.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale