OpenThread: Neighbor Class Reference
Neighbor Class Reference
#include <topology.hpp>
Public Types
enum State {
kStateInvalid, kStateRestored, kStateParentRequest, kStateParentResponse,
kStateChildIdRequest, kStateLinkRequest, kStateChildUpdateRequest, kStateValid
}
enum StateFilter {
kInStateValid, kInStateValidOrRestoring, kInStateChildIdRequest, kInStateValidOrAttaching,
kInStateAnyExceptInvalid, kInStateAnyExceptValidOrRestoring
}
Public Member Functions
void ClearExtAddress (void)
void GenerateChallenge (void)
const uint8_t * GetChallenge (void) const
uint8_t GetChallengeSize (void) const
Mle::DeviceMode GetDeviceMode (void) const
const Mac::ExtAddress & GetExtAddress (void) const
uint32_t GetKeySequence (void) const
TimeMilli GetLastHeard (void) const
uint8_t GetLinkFailures (void) const
uint32_t GetLinkFrameCounter (void) const
LinkQualityInfo & GetLinkInfo (void)
uint32_t GetMleFrameCounter (void) const
uint16_t GetRloc16 (void) const
uint8_t GetRouterId (void) const
State GetState (void) const
uint8_t GetVersion (void) const
void IncrementLinkFailures (void)
bool IsEnhancedKeepAliveSupported (void) const
bool IsFullNetworkData (void) const
bool IsFullThreadDevice (void) const
bool IsRxOnWhenIdle (void) const
bool IsSecureDataRequest (void) const
bool IsStateChildIdRequest (void) const
bool IsStateInvalid (void) const
bool IsStateLinkRequest (void) const
bool IsStateParentResponse (void) const
bool IsStateRestored (void) const
bool IsStateRestoring (void) const
bool IsStateValid (void) const
bool IsStateValidOrAttaching (void) const
bool IsStateValidOrRestoring (void) const
bool IsThreadVersion1p1 (void) const
bool MatchesFilter (StateFilter aFilter) const
void ResetLinkFailures (void)
void SetDeviceMode (Mle::DeviceMode aMode)
void SetExtAddress (const Mac::ExtAddress &aAddress)
void SetKeySequence (uint32_t aKeySequence)
void SetLastHeard (TimeMilli aLastHeard)
void SetLinkFrameCounter (uint32_t aFrameCounter)
void SetMleFrameCounter (uint32_t aFrameCounter)
void SetRloc16 (uint16_t aRloc16)
void SetState (State aState)
void SetVersion (uint8_t aVersion)
Public Member Functions inherited from InstanceLocator
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Protected Member Functions
void Init (Instance &aInstance)
Protected Member Functions inherited from InstanceLocatorInit
void Init (Instance &aInstance)
InstanceLocatorInit (void)
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Private Attributes
uint32_t mKeySequence
Current key sequence.
TimeMilli mLastHeard
Time when last heard.
uint8_t mLinkFailures
Consecutive link failure count.
LinkQualityInfo mLinkInfo
Link quality info (contains average RSS, link margin and link quality)
Mac::ExtAddress mMacAddr
The IEEE 802.15.4 Extended Address.
uint8_t mMode: 4
The MLE device mode.
uint16_t mRloc16
The RLOC16.
uint8_t mState: 4
The link state.
union {
struct {
uint8_t mChallenge [Mle::kMaxChallengeSize]
The challenge value.
} mPending
struct {
uint32_t mLinkFrameCounter
The Link Frame Counter.
uint32_t mMleFrameCounter
The MLE Frame Counter.
} mValid
} mValidPending
uint8_t mVersion
The MLE version.
Detailed Description
This class represents a Thread neighbor.
Member Enumeration Documentation
State
enum State
Neighbor link states.
Enumerator
kStateInvalid
Neighbor link is invalid.
kStateRestored
Neighbor is restored from non-volatile memory.
kStateParentRequest
Received an MLE Parent Request message.
kStateParentResponse
Received an MLE Parent Response message.
kStateChildIdRequest
Received an MLE Child ID Request message.
kStateLinkRequest
Sent an MLE Link Request message.
kStateChildUpdateRequest
Sent an MLE Child Update Request message (trying to restore the child)
kStateValid
Link is valid.
StateFilter
enum StateFilter
This enumeration defines state filters used for finding a neighbor or iterating through the child/neighbor table.
Each filter definition accepts a subset of State values.
Enumerator
kInStateValid
Accept child only in kStateValid.
kInStateValidOrRestoring
Accept child with IsStateValidOrRestoring() being true.
kInStateChildIdRequest
Accept child only in Child:kStateChildIdRequest.
kInStateValidOrAttaching
Accept child with IsStateValidOrAttaching() being true.
kInStateAnyExceptInvalid
Accept child in any state except kStateInvalid.
kInStateAnyExceptValidOrRestoring
Accept child in any state except IsStateValidOrRestoring().
Member Function Documentation
GetState()
State GetState (void) const inline
This method returns the current state.
Returns
The current state.
References Neighbor::mState.
Referenced by Mac::HandleReceivedFrame(), and Neighbor::IsStateValidOrAttaching().
SetState()
void SetState (State aState) inline
This method sets the current state.
Parameters
[in] aState The state value.
References Neighbor::mState.
Referenced by Mle::BecomeDetached(), Mle::HandleAttachTimer(), Mle::HandleChildUpdateResponse(), Mle::HandleParentResponse(), Neighbor::Init(), Mle::Restore(), Mle::SendChildIdRequest(), and Mle::SetRole().
IsStateInvalid()
bool IsStateInvalid (void) const inline
This method indicates whether the neighbor is in the Invalid state.
Returns
TRUE if the neighbor is in the Invalid state, FALSE otherwise.
References Neighbor::kStateInvalid, and Neighbor::mState.
Referenced by Neighbor::MatchesFilter().
IsStateChildIdRequest()
bool IsStateChildIdRequest (void) const inline
This method indicates whether the neighbor is in the Child ID Request state.
Returns
TRUE if the neighbor is in the Child ID Request state, FALSE otherwise.
References Neighbor::kStateChildIdRequest, and Neighbor::mState.
Referenced by Neighbor::MatchesFilter().
IsStateLinkRequest()
bool IsStateLinkRequest (void) const inline
This method indicates whether the neighbor is in the Link Request state.
Returns
TRUE if the neighbor is in the Link Request state, FALSE otherwise.
References Neighbor::kStateLinkRequest, and Neighbor::mState.
IsStateParentResponse()
bool IsStateParentResponse (void) const inline
This method indicates whether the neighbor is in the Parent Response state.
Returns
TRUE if the neighbor is in the Parent Response state, FALSE otherwise.
References Neighbor::kStateParentResponse, and Neighbor::mState.
Referenced by Mle::HandleAttachTimer(), and Mle::HandleParentResponse().
IsStateRestoring()
bool IsStateRestoring (void) const inline
This method indicates whether the neighbor is being restored.
Returns
TRUE if the neighbor is being restored, FALSE otherwise.
References Neighbor::kStateChildUpdateRequest, Neighbor::kStateRestored, and Neighbor::mState.
Referenced by Neighbor::IsStateValidOrRestoring().
IsStateRestored()
bool IsStateRestored (void) const inline
This method indicates whether the neighbor is in the Restored state.
Returns
TRUE if the neighbor is in the Restored state, FALSE otherwise.
References Neighbor::kStateRestored, and Neighbor::mState.
IsStateValid()
bool IsStateValid (void) const inline
This method indicates whether the neighbor is valid (frame counters are synchronized).
Returns
TRUE if the neighbor is valid, FALSE otherwise.
References Neighbor::kStateValid, and Neighbor::mState.
Referenced by Mle::GetNeighbor(), Mle::GetNextHop(), DataPollSender::GetParent(), Mle::HandleAdvertisement(), Mle::HandleChildIdResponse(), Mle::HandleChildUpdateResponse(), Mle::HandleDataResponse(), Mle::HandleUdpReceive(), Neighbor::MatchesFilter(), and Mac::ProcessReceiveSecurity().
IsStateValidOrRestoring()
bool IsStateValidOrRestoring (void) const inline
This method indicates whether the neighbor is in valid state or if it is being restored.
When in these states messages can be sent to and/or received from the neighbor.
Returns
TRUE if the neighbor is in valid, restored, or being restored states, FALSE otherwise.
References Neighbor::IsStateRestoring(), Neighbor::IsStateValidOrAttaching(), Neighbor::kStateValid, Neighbor::MatchesFilter(), and Neighbor::mState.
Referenced by Mle::GetNeighbor(), DataPollSender::GetPollDestinationAddress(), Neighbor::MatchesFilter(), and Mle::SendChildUpdateRequest().
IsStateValidOrAttaching()
bool IsStateValidOrAttaching (void) const
This method indicates if the neighbor state is valid, attaching, or restored.
The states kStateRestored, kStateChildIdRequest, kStateChildUpdateRequest, kStateValid, and kStateLinkRequest are considered as valid, attaching, or restored.
Returns
TRUE if the neighbor state is valid, attaching, or restored, FALSE otherwise.
References Neighbor::GetState(), Neighbor::kStateChildIdRequest, Neighbor::kStateChildUpdateRequest, Neighbor::kStateInvalid, Neighbor::kStateLinkRequest, Neighbor::kStateParentRequest, Neighbor::kStateParentResponse, Neighbor::kStateRestored, and Neighbor::kStateValid.
Referenced by Neighbor::IsStateValidOrRestoring(), and Neighbor::MatchesFilter().
MatchesFilter()
bool MatchesFilter (StateFilter aFilter) const
This method indicates whether neighbor state matches a given state filter.
Parameters
[in] aFilter A state filter (StateFilter enumeration) to match against.
Returns
TRUE if the neighbor state matches the filter, FALSE otherwise.
References Neighbor::IsStateChildIdRequest(), Neighbor::IsStateInvalid(), Neighbor::IsStateValid(), Neighbor::IsStateValidOrAttaching(), Neighbor::IsStateValidOrRestoring(), Neighbor::kInStateAnyExceptInvalid, Neighbor::kInStateAnyExceptValidOrRestoring, Neighbor::kInStateChildIdRequest, Neighbor::kInStateValid, Neighbor::kInStateValidOrAttaching, and Neighbor::kInStateValidOrRestoring.
Referenced by Neighbor::IsStateValidOrRestoring().
GetDeviceMode()
Mle::DeviceMode GetDeviceMode (void) const inline
This method gets the device mode flags.
Returns
The device mode flags.
References Neighbor::mMode.
Referenced by Neighbor::IsFullNetworkData(), Neighbor::IsFullThreadDevice(), Neighbor::IsRxOnWhenIdle(), and Neighbor::IsSecureDataRequest().
SetDeviceMode()
void SetDeviceMode (Mle::DeviceMode aMode) inline
This method sets the device mode flags.
Parameters
[in] aMode The device mode flags.
References DeviceMode::Get(), and Neighbor::mMode.
Referenced by Mle::HandleParentResponse(), and Mle::Restore().
IsRxOnWhenIdle()
bool IsRxOnWhenIdle (void) const inline
This method indicates whether or not the device is rx-on-when-idle.
Returns
TRUE if rx-on-when-idle, FALSE otherwise.
References Neighbor::GetDeviceMode(), and DeviceMode::IsRxOnWhenIdle().
Referenced by Mac::HandleReceivedFrame().
IsFullThreadDevice()
bool IsFullThreadDevice (void) const inline
This method indicates whether or not the device is a Full Thread Device.
Returns
TRUE if a Full Thread Device, FALSE otherwise.
References Neighbor::GetDeviceMode(), and DeviceMode::IsFullThreadDevice().
IsSecureDataRequest()
bool IsSecureDataRequest (void) const inline
This method indicates whether or not the device uses secure IEEE 802.15.4 Data Request messages.
Returns
TRUE if using secure IEEE 802.15.4 Data Request messages, FALSE otherwise.
References Neighbor::GetDeviceMode(), and DeviceMode::IsSecureDataRequest().
IsFullNetworkData()
bool IsFullNetworkData (void) const inline
This method indicates whether or not the device requests Full Network Data.
Returns
TRUE if requests Full Network Data, FALSE otherwise.
References Neighbor::GetDeviceMode(), and DeviceMode::IsFullNetworkData().
ClearExtAddress()
void ClearExtAddress (void) inline
This method sets all bytes of the Extended Address to zero.
References Neighbor::mMacAddr.
GetExtAddress()
const Mac::ExtAddress& GetExtAddress (void) const inline
This method returns the Extended Address.
Returns
A reference to the Extended Address.
References Neighbor::mMacAddr.
Referenced by Mle::GetNeighbor(), DataPollSender::GetPollDestinationAddress(), Mle::HandleMessageTransmissionTimer(), Mle::HandleParentResponse(), Mac::HandleReceivedFrame(), Mle::SendChildIdRequest(), Mle::SendChildUpdateRequest(), Mle::SendChildUpdateResponse(), and Mle::Store().
SetExtAddress()
void SetExtAddress (const Mac::ExtAddress & aAddress) inline
This method sets the Extended Address.
Parameters
[in] aAddress The Extended Address value to set.
References Neighbor::mMacAddr.
Referenced by Mle::HandleParentResponse(), and Mle::Restore().
GetKeySequence()
uint32_t GetKeySequence (void) const inline
This method gets the key sequence value.
Returns
The key sequence value.
References Neighbor::mKeySequence.
Referenced by Mle::HandleUdpReceive(), and Mac::ProcessReceiveSecurity().
SetKeySequence()
void SetKeySequence (uint32_t aKeySequence) inline
This method sets the key sequence value.
Parameters
[in] aKeySequence The key sequence value.
References Neighbor::mKeySequence.
Referenced by Mle::HandleParentResponse(), Mle::HandleUdpReceive(), Mac::ProcessReceiveSecurity(), and KeyManager::SetMasterKey().
GetLastHeard()
TimeMilli GetLastHeard (void) const inline
This method returns the last heard time.
Returns
The last heard time.
References Neighbor::mLastHeard.
SetLastHeard()
void SetLastHeard (TimeMilli aLastHeard) inline
This method sets the last heard time.
Parameters
[in] aLastHeard The last heard time.
References Neighbor::mLastHeard.
Referenced by Mle::HandleAdvertisement(), and Mac::HandleReceivedFrame().
GetLinkFrameCounter()
uint32_t GetLinkFrameCounter (void) const inline
This method gets the link frame counter value.
Returns
The link frame counter value.
References Neighbor::mValidPending.
Referenced by Mac::ProcessReceiveSecurity().
SetLinkFrameCounter()
void SetLinkFrameCounter (uint32_t aFrameCounter) inline
This method sets the link frame counter value.
Parameters
[in] aFrameCounter The link frame counter value.
References Neighbor::mValidPending.
Referenced by Mle::HandleChildUpdateResponse(), Mle::HandleParentResponse(), Mle::HandleUdpReceive(), Mac::ProcessReceiveSecurity(), and KeyManager::SetMasterKey().
GetMleFrameCounter()
uint32_t GetMleFrameCounter (void) const inline
This method gets the MLE frame counter value.
Returns
The MLE frame counter value.
References Neighbor::mValidPending.
Referenced by Mle::HandleUdpReceive().
SetMleFrameCounter()
void SetMleFrameCounter (uint32_t aFrameCounter) inline
This method sets the MLE frame counter value.
Parameters
[in] aFrameCounter The MLE frame counter value.
References Neighbor::mValidPending.
Referenced by Mle::HandleChildUpdateResponse(), Mle::HandleParentResponse(), Mle::HandleUdpReceive(), Mac::ProcessReceiveSecurity(), and KeyManager::SetMasterKey().
GetRloc16()
uint16_t GetRloc16 (void) const inline
This method gets the RLOC16 value.
Returns
The RLOC16 value.
References Neighbor::mRloc16.
Referenced by Mle::CheckReachability(), Mle::GetNeighbor(), Mle::GetNextHop(), DataPollSender::GetPollDestinationAddress(), Mle::HandleAdvertisement(), Mle::HandleChildUpdateRequest(), Mle::IsBetterParent(), Mle::Restore(), Mle::SetStateChild(), and MeshForwarder::UpdateNeighborOnSentFrame().
GetRouterId()
uint8_t GetRouterId (void) const inline
This method gets the Router ID value.
Returns
The Router ID value.
References ot::Mle::kRouterIdOffset, and Neighbor::mRloc16.
SetRloc16()
void SetRloc16 (uint16_t aRloc16) inline
This method sets the RLOC16 value.
Parameters
[in] aRloc16 The RLOC16 value.
References Neighbor::mRloc16.
Referenced by Mle::HandleChildIdResponse(), Mle::HandleParentResponse(), and Mle::Restore().
IsThreadVersion1p1()
bool IsThreadVersion1p1 (void) const inline
This method indicates whether or not it is a valid Thread 1.1 neighbor.
Returns
TRUE if it is a valid Thread 1.1 neighbor, FALSE otherwise.
References Neighbor::kStateInvalid, Neighbor::mState, Neighbor::mVersion, and OT_THREAD_VERSION_1_1.
IsEnhancedKeepAliveSupported()
bool IsEnhancedKeepAliveSupported (void) const inline
This method indicates whether Enhanced Keep-Alive is supported or not.
Returns
TRUE if Enhanced Keep-Alive is supported, FALSE otherwise.
References Neighbor::kStateInvalid, Neighbor::mState, Neighbor::mVersion, and OT_THREAD_VERSION_1_2.
Referenced by Mac::HandleReceivedFrame().
GetVersion()
uint8_t GetVersion (void) const inline
This method gets the device MLE version.
References Neighbor::mVersion.
Referenced by Mle::IsBetterParent(), and Mle::Store().
SetVersion()
void SetVersion (uint8_t aVersion) inline
This method sets the device MLE version.
Parameters
[in] aVersion The device MLE version.
References Neighbor::mVersion.
Referenced by Mle::HandleParentResponse(), and Mle::Restore().
GetLinkFailures()
uint8_t GetLinkFailures (void) const inline
This method gets the number of consecutive link failures.
Returns
The number of consecutive link failures.
References Neighbor::mLinkFailures.
Referenced by MeshForwarder::UpdateNeighborOnSentFrame().
IncrementLinkFailures()
void IncrementLinkFailures (void) inline
This method increments the number of consecutive link failures.
References Neighbor::mLinkFailures.
Referenced by MeshForwarder::UpdateNeighborOnSentFrame().
ResetLinkFailures()
void ResetLinkFailures (void) inline
This method resets the number of consecutive link failures to zero.
References Neighbor::mLinkFailures.
Referenced by Mle::HandleParentResponse(), and MeshForwarder::UpdateNeighborOnSentFrame().
GetLinkInfo()
LinkQualityInfo& GetLinkInfo (void) inline
This method returns the LinkQualityInfo object.
Returns
The LinkQualityInfo object.
References Neighbor::GenerateChallenge(), and Neighbor::mLinkInfo.
Referenced by Mle::CheckReachability(), Mle::HandleAttachTimer(), Mle::HandleParentResponse(), Mac::HandleReceivedFrame(), MeshForwarder::HandleSentFrame(), Mle::IsBetterParent(), and Mac::RecordFrameTransmitStatus().
GenerateChallenge()
void GenerateChallenge (void)
This method generates a new challenge value for MLE Link Request/Response exchanges.
References ot::Random::Crypto::FillBuffer(), and Neighbor::mValidPending.
Referenced by Neighbor::GetLinkInfo(), and Child::SetNetworkDataVersion().
GetChallenge()
const uint8_t* GetChallenge (void) const inline
This method returns the current challenge value for MLE Link Request/Response exchanges.
Returns
The current challenge value.
References Neighbor::mValidPending.
GetChallengeSize()
uint8_t GetChallengeSize (void) const inline
This method returns the size (bytes) of the challenge value for MLE Link Request/Response exchanges.
Returns
The size (bytes) of the challenge value for MLE Link Request/Response exchanges.
References Neighbor::Init(), and Neighbor::mValidPending.
Init()
void Init (Instance & aInstance) protected
This method initializes the Neighbor object.
Parameters
[in] aInstance A reference to OpenThread instance.
References InstanceLocatorInit::Init(), LinkQualityInfo::Init(), Neighbor::kStateInvalid, Neighbor::mLinkInfo, and Neighbor::SetState().
Referenced by Child::Clear(), Router::Clear(), Neighbor::GetChallengeSize(), Child::Init(), and Router::Init().
Field Documentation
mMacAddr
Mac::ExtAddress mMacAddr private
The IEEE 802.15.4 Extended Address.
Referenced by Neighbor::ClearExtAddress(), Neighbor::GetExtAddress(), and Neighbor::SetExtAddress().
mLastHeard
TimeMilli mLastHeard private
Time when last heard.
Referenced by Neighbor::GetLastHeard(), and Neighbor::SetLastHeard().
mLinkFrameCounter
uint32_t mLinkFrameCounter
The Link Frame Counter.
mMleFrameCounter
uint32_t mMleFrameCounter
The MLE Frame Counter.
mValid
struct { ... } mValid
mChallenge
uint8_t mChallenge[Mle::kMaxChallengeSize]
The challenge value.
mPending
struct { ... } mPending
mValidPending
union { ... } mValidPending
Referenced by Neighbor::GenerateChallenge(), Neighbor::GetChallenge(), Neighbor::GetChallengeSize(), Neighbor::GetLinkFrameCounter(), Neighbor::GetMleFrameCounter(), Neighbor::SetLinkFrameCounter(), and Neighbor::SetMleFrameCounter().
mKeySequence
uint32_t mKeySequence private
Current key sequence.
Referenced by Neighbor::GetKeySequence(), and Neighbor::SetKeySequence().
mRloc16
uint16_t mRloc16 private
The RLOC16.
Referenced by Neighbor::GetRloc16(), Neighbor::GetRouterId(), and Neighbor::SetRloc16().
mState
uint8_t mState private
The link state.
Referenced by Neighbor::GetState(), Neighbor::IsEnhancedKeepAliveSupported(), Neighbor::IsStateChildIdRequest(), Neighbor::IsStateInvalid(), Neighbor::IsStateLinkRequest(), Neighbor::IsStateParentResponse(), Neighbor::IsStateRestored(), Neighbor::IsStateRestoring(), Neighbor::IsStateValid(), Neighbor::IsStateValidOrRestoring(), Neighbor::IsThreadVersion1p1(), and Neighbor::SetState().
mMode
uint8_t mMode private
The MLE device mode.
Referenced by Neighbor::GetDeviceMode(), and Neighbor::SetDeviceMode().
mLinkFailures
uint8_t mLinkFailures private
Consecutive link failure count.
Referenced by Neighbor::GetLinkFailures(), Neighbor::IncrementLinkFailures(), and Neighbor::ResetLinkFailures().
mVersion
uint8_t mVersion private
The MLE version.
Referenced by Neighbor::GetVersion(), Neighbor::IsEnhancedKeepAliveSupported(), Neighbor::IsThreadVersion1p1(), and Neighbor::SetVersion().
mLinkInfo
LinkQualityInfo mLinkInfo private
Link quality info (contains average RSS, link margin and link quality)
Referenced by Neighbor::GetLinkInfo(), and Neighbor::Init().
The documentation for this class was generated from the following files:
topology.hpp
topology.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale