OpenThread: TlvUint16 Class Reference
TlvUint16 Class Reference
#include <tlvs.hpp>
Public Member Functions
uint16_t GetUint16Value (void) const
void Init (uint8_t aType)
bool IsValid (void) const
void SetUint16Value (uint16_t aValue)
Public Member Functions inherited from Tlv
otError AppendTo (Message &aMessage) const
uint8_t GetLength (void) const
Tlv * GetNext (void)
const Tlv * GetNext (void) const
uint32_t GetSize (void) const
uint8_t GetType (void) const
uint8_t * GetValue (void)
const uint8_t * GetValue (void) const
bool IsExtended (void) const
void SetLength (uint8_t aLength)
void SetType (uint8_t aType)
Private Attributes
uint16_t mValue
Additional Inherited Members
Public Types inherited from Tlv
enum { kBaseTlvMaxLength = OT_NETWORK_BASE_TLV_MAX_LENGTH }
Static Public Member Functions inherited from Tlv
static otError AppendTlv (Message &aMessage, uint8_t aType, const uint8_t *aValue, uint8_t aLength)
static otError AppendUint16Tlv (Message &aMessage, uint8_t aType, uint16_t aValue)
static otError AppendUint32Tlv (Message &aMessage, uint8_t aType, uint32_t aValue)
static otError AppendUint8Tlv (Message &aMessage, uint8_t aType, uint8_t aValue)
static otError Get (const Message &aMessage, uint8_t aType, uint16_t aMaxSize, Tlv &aTlv)
static otError GetOffset (const Message &aMessage, uint8_t aType, uint16_t &aOffset)
static otError GetValueOffset (const Message &aMessage, uint8_t aType, uint16_t &aOffset, uint16_t &aLength)
static otError ReadTlv (const Message &aMessage, uint8_t aType, void *aValue, uint8_t aLength)
static otError ReadUint16Tlv (const Message &aMessage, uint8_t aType, uint16_t &aValue)
static otError ReadUint32Tlv (const Message &aMessage, uint8_t aType, uint32_t &aValue)
static otError ReadUint8Tlv (const Message &aMessage, uint8_t aType, uint8_t &aValue)
Protected Types inherited from Tlv
enum { kExtendedLength = 255 }
Detailed Description
This class implements a simple TLV with a uint16_t value.
Member Function Documentation
Init()
void Init (uint8_t aType) inline
This method initializes the TLV.
Parameters
[in] aType The Type value.
References Tlv::SetLength(), and Tlv::SetType().
Referenced by Tlv::AppendUint16Tlv().
IsValid()
bool IsValid (void) const inline
This method indicates whether or not the TLV appears to be well-formed.
Return values
TRUE If the TLV appears to be well-formed.
FALSE If the TLV does not appear to be well-formed.
References Tlv::GetLength().
Referenced by Tlv::ReadUint16Tlv().
GetUint16Value()
uint16_t GetUint16Value (void) const inline
This method returns the uint16_t value.
Returns
The uint16_t value.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by Tlv::ReadUint16Tlv().
SetUint16Value()
void SetUint16Value (uint16_t aValue) inline
This method sets the uint16_t value.
Parameters
[in] aValue The uint16_t value.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by Tlv::AppendUint16Tlv().
Field Documentation
mValue
uint16_t mValue private
The documentation for this class was generated from the following file:
tlvs.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale