OpenThread: NetworkName Class Reference
NetworkName Class Reference
Core-mac
#include <mac_types.hpp>
Public Types
enum { kMaxSize = OT_NETWORK_NAME_MAX_SIZE }
Public Member Functions
const char * GetAsCString (void) const
NameData GetAsData (void) const
NetworkName (void)
otError Set (const NameData &aNameData)
Additional Inherited Members
Data Fields inherited from otNetworkName
char m8 [OT_NETWORK_NAME_MAX_SIZE+1]
Byte values.
Detailed Description
This structure represents an IEEE802.15.4 Network Name.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
kMaxSize
Constructor & Destructor Documentation
NetworkName()
NetworkName (void) inline
This constructor initializes the IEEE802.15.4 Network Name as an empty string.
References otExtAddress::m8.
Member Function Documentation
GetAsCString()
const char* GetAsCString (void) const inline
This method gets the IEEE802.15.4 Network Name as a null terminated C string.
Returns
The Network Name as a null terminated C string array.
References otExtAddress::m8, and ExtAddress::Set().
Referenced by ot::MeshCoP::GetBorderAgentRloc(), and TxFrame::ProcessTransmitAesCcm().
GetAsData()
NameData GetAsData (void) const
This method gets the IEEE802.15.4 Network Name as NameData.
Returns
The Network Name as NameData.
References otExtAddress::m8, and ot::StringLength().
Referenced by Mac::PrepareBeacon().
Set()
otError Set (const NameData & aNameData)
This method sets the IEEE 802.15.4 Network Name.
Parameters
[in] aNameData A reference to name data.
Return values
OT_ERROR_NONE Successfully set the IEEE 802.15.4 Network Name.
OT_ERROR_ALREADY The name is already set to the same string.
OT_ERROR_INVALID_ARGS Given name is too long.
References NameData::GetBuffer(), NameData::GetLength(), otExtAddress::m8, OT_ERROR_ALREADY, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, ot::StringLength(), and VerifyOrExit.
Referenced by TxFrame::ProcessTransmitAesCcm(), and Mac::SetNetworkName().
The documentation for this class was generated from the following files:
mac_types.hpp
mac_types.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale