OpenThread: Server Class Reference
Server Class Reference
#include <cli_server.hpp>
Public Member Functions
Interpreter & GetInterpreter (void)
virtual int Output (const char *aBuf, uint16_t aBufLength)
int OutputFormat (const char *aFormat,...)
int OutputFormatV (const char *aFormat, va_list aArguments)
Server (Instance *aInstance)
Static Public Attributes
static Server * sServer = NULL
Protected Types
enum { kMaxLineLength = OPENTHREAD_CONFIG_CLI_MAX_LINE_LENGTH }
Protected Attributes
Interpreter mInterpreter
Detailed Description
This class implements the CLI server.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
kMaxLineLength
Constructor & Destructor Documentation
Server()
Server (Instance * aInstance) inline explicit
Member Function Documentation
Output()
virtual int Output (const char * aBuf, uint16_t aBufLength) inline virtual
This method delivers raw characters to the client.
Parameters
[in] aBuf A pointer to a buffer.
[in] aBufLength Number of bytes in the buffer.
Returns
The number of bytes placed in the output queue.
Return values
-1 Driver is broken.
Reimplemented in Console, and Uart.
References OT_UNUSED_VARIABLE, Server::OutputFormat(), and Server::OutputFormatV().
Referenced by otCliOutput(), and Server::OutputFormatV().
OutputFormat()
int OutputFormat (const char * aFormat, ...)
This method delivers formatted output to the client.
Parameters
[in] aFormat A pointer to the format string.
[in] ... A variable list of arguments to format.
Returns
The number of bytes placed in the output queue.
Return values
-1 Driver is broken.
References Server::OutputFormatV().
Referenced by otCliPlatLogv(), and Server::Output().
OutputFormatV()
int OutputFormatV (const char * aFormat, va_list aArguments)
This method delivers formatted output to the client.
Parameters
[in] aFormat A pointer to the format string.
[in] aArguments A variable list of arguments for format.
Returns
The number of bytes placed in the output queue.
References Server::kMaxLineLength, and Server::Output().
Referenced by otCliOutputFormat(), otCliPlatLogv(), Server::Output(), and Server::OutputFormat().
GetInterpreter()
Interpreter& GetInterpreter (void) inline
This method returns a reference to the interpreter object.
Returns
A reference to the interpreter object.
References Server::mInterpreter.
Referenced by otCliAppendResult(), otCliOutputBytes(), and otCliSetUserCommands().
Field Documentation
sServer
Server * sServer = NULL static
Referenced by otCliAppendResult(), otCliConsoleInit(), otCliConsoleInputLine(), otCliOutput(), otCliOutputBytes(), otCliOutputFormat(), otCliPlatLogv(), otCliSetUserCommands(), otCliUartInit(), otPlatUartReceived(), and otPlatUartSendDone().
mInterpreter
Interpreter mInterpreter protected
Referenced by Server::GetInterpreter(), Uart::ProcessCommand(), and Console::ReceiveTask().
The documentation for this class was generated from the following files:
cli_server.hpp
cli_server.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale