OpenThread: MessageQueue Class Reference
MessageQueue Class Reference
Core-message
#include <message.hpp>
Public Types
enum QueuePosition { kQueuePositionHead, kQueuePositionTail }
Public Member Functions
otError Dequeue (Message &aMessage)
otError Enqueue (Message &aMessage)
otError Enqueue (Message &aMessage, QueuePosition aPosition)
Message * GetHead (void) const
void GetInfo (uint16_t &aMessageCount, uint16_t &aBufferCount) const
MessageQueue (void)
Private Member Functions
Message * GetTail (void) const
void SetTail (Message *aMessage)
Friends
class Message
class PriorityQueue
Additional Inherited Members
Data Fields inherited from otMessageQueue
void * mData
Opaque data used by the implementation.
Detailed Description
This class implements a message queue.
Member Enumeration Documentation
QueuePosition
enum QueuePosition
This enumeration represents a position (head or tail) in the queue. This is used to specify where a new message should be added in the queue.
Enumerator
kQueuePositionHead
Indicates the head (front) of the list.
kQueuePositionTail
Indicates the tail (end) of the list.
Constructor & Destructor Documentation
MessageQueue()
MessageQueue (void)
This constructor initializes the message queue.
Member Function Documentation
GetHead()
Message * GetHead (void) const
This method returns a pointer to the first message.
Returns
A pointer to the first message.
References Message::Next().
Referenced by MeshForwarder::ClearReassemblyList(), MessageQueue::GetHead(), Mle::HandleDelayedResponseTimer(), MeshForwarder::HandleFragment(), otMessageQueueGetHead(), Mle::RemoveDelayedDataResponseMessage(), MeshForwarder::Stop(), and MeshForwarder::UpdateReassemblyList().
Enqueue() [1/2]
otError Enqueue (Message & aMessage) inline
This method adds a message to the end of the list.
Parameters
[in] aMessage The message to add.
Return values
OT_ERROR_NONE Successfully added the message to the list.
OT_ERROR_ALREADY The message is already enqueued in a list.
References MessageQueue::Enqueue().
Referenced by Mle::AddDelayedResponse(), MessageQueue::Enqueue(), MeshForwarder::HandleFragment(), otMessageQueueEnqueue(), and otMessageQueueEnqueueAtHead().
Enqueue() [2/2]
otError Enqueue (Message & aMessage, QueuePosition aPosition)
This method adds a message at a given position (head/tail) of the list.
Parameters
[in] aMessage The message to add.
[in] aPosition The position (head or tail) where to add the message.
Return values
OT_ERROR_NONE Successfully added the message to the list.
OT_ERROR_ALREADY The message is already enqueued in a list.
References Message::IsInAQueue(), Message::Next(), OT_ASSERT, OT_ERROR_ALREADY, OT_ERROR_NONE, Message::Prev(), Message::SetMessageQueue(), and VerifyOrExit.
Dequeue()
otError Dequeue (Message & aMessage)
This method removes a message from the list.
Parameters
[in] aMessage The message to remove.
Return values
OT_ERROR_NONE Successfully removed the message from the list.
OT_ERROR_NOT_FOUND The message is not enqueued in a list.
References Message::GetMessageQueue(), Message::Next(), OT_ASSERT, OT_ERROR_NONE, OT_ERROR_NOT_FOUND, Message::Prev(), Message::SetMessageQueue(), and VerifyOrExit.
Referenced by MeshForwarder::ClearReassemblyList(), MessageQueue::Dequeue(), Mle::HandleDelayedResponseTimer(), MeshForwarder::HandleFragment(), otMessageQueueDequeue(), Mle::RemoveDelayedDataResponseMessage(), MeshForwarder::Stop(), and MeshForwarder::UpdateReassemblyList().
GetInfo()
void GetInfo (uint16_t & aMessageCount, uint16_t & aBufferCount) const
This method returns the number of messages and buffers enqueued.
Parameters
[out] aMessageCount Returns the number of messages enqueued.
[out] aBufferCount Returns the number of buffers enqueued.
References Message::GetNext().
GetTail()
Message* GetTail (void) const inline private
This method returns the tail of the list (last message in the list)
Returns
A pointer to the tail of the list.
Referenced by Message::GetNext().
SetTail()
void SetTail (Message * aMessage) inline private
This method set the tail of the list.
Parameters
[in] aMessage A pointer to the message to set as new tail.
Friends And Related Function Documentation
Message
friend class Message friend
PriorityQueue
friend class PriorityQueue friend
The documentation for this class was generated from the following files:
message.hpp
message.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale