OpenThread: MeshForwarder Class Reference
MeshForwarder Class Reference
Core-mesh-forwarding
#include <mesh_forwarder.hpp>
Public Member Functions
otError EvictMessage (uint8_t aPriority)
const otIpCounters & GetCounters (void) const
const MessageQueue & GetReassemblyQueue (void) const
bool GetRxOnWhenIdle (void) const
const PriorityQueue & GetSendQueue (void) const
void HandleResolved (const Ip6::Address &aEid, otError aError)
MeshForwarder (Instance &aInstance)
void RemoveDataResponseMessages (void)
void RemoveMessages (Child &aChild, uint8_t aSubType)
void ResetCounters (void)
otError SendMessage (Message &aMessage)
void SetDiscoverParameters (const Mac::ChannelMask &aScanChannels)
void SetRxOnWhenIdle (bool aRxOnWhenIdle)
void Start (void)
void Stop (void)
void UpdateIndirectMessages (void)
Public Member Functions inherited from InstanceLocator
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Private Types
enum { kStateUpdatePeriod = 1000, kDefaultMsgPriority = Message::kPriorityNormal, kNumFragmentPriorityEntries = OPENTHREAD_CONFIG_NUM_FRAGMENT_PRIORITY_ENTRIES }
enum MessageAction {
kMessageReceive, kMessageTransmit, kMessagePrepareIndirect, kMessageDrop,
kMessageReassemblyDrop, kMessageEvict
}
< Defines the action parameter in LogMessageInfo() method.
Private Member Functions
otError CheckReachability (const uint8_t *aFrame, uint16_t aFrameLength, const Mac::Address &aMeshSource, const Mac::Address &aMeshDest)
void ClearReassemblyList (void)
otError DecompressIp6Header (const uint8_t *aFrame, uint16_t aFrameLength, const Mac::Address &aMacSource, const Mac::Address &aMacDest, Ip6::Header &aIp6Header, uint8_t &aHeaderLength, bool &aNextHeaderCompressed)
FragmentPriorityEntry * FindFragmentPriorityEntry (uint16_t aTag, uint16_t aSrcRloc16)
otError FrameToMessage (const uint8_t *aFrame, uint16_t aFrameLength, uint16_t aDatagramSize, const Mac::Address &aMacSource, const Mac::Address &aMacDest, Message *&aMessage)
otError GetDestinationRlocByServiceAloc (uint16_t aServiceAloc, uint16_t &aMeshDest)
Message * GetDirectTransmission (void)
otError GetForwardFramePriority (const uint8_t *aFrame, uint16_t aFrameLength, const Mac::Address &aMeshSource, const Mac::Address &aMeshDest, uint8_t &aPriority)
otError GetFragmentPriority (Lowpan::FragmentHeader &aFragmentHeader, uint16_t aSrcRloc16, uint8_t &aPriority)
otError GetFramePriority (const uint8_t *aFrame, uint16_t aFrameLength, const Mac::Address &aMacSource, const Mac::Address &aMacDest, uint8_t &aPriority)
otError GetIp6Header (const uint8_t *aFrame, uint16_t aFrameLength, const Mac::Address &aMacSource, const Mac::Address &aMacDest, Ip6::Header &aIp6Header)
void GetMacDestinationAddress (const Ip6::Address &aIp6Addr, Mac::Address &aMacAddr)
void GetMacSourceAddress (const Ip6::Address &aIp6Addr, Mac::Address &aMacAddr)
FragmentPriorityEntry * GetUnusedFragmentPriorityEntry (void)
otError HandleDatagram (Message &aMessage, const otThreadLinkInfo &aLinkInfo, const Mac::Address &aMacSource)
void HandleDiscoverComplete (void)
void HandleDiscoverTimer (void)
void HandleFragment (const uint8_t *aFrame, uint16_t aFrameLength, const Mac::Address &aMacSource, const Mac::Address &aMacDest, const otThreadLinkInfo &aLinkInfo)
otError HandleFrameRequest (Mac::TxFrame &aFrame)
void HandleLowpanHC (const uint8_t *aFrame, uint16_t aFrameLength, const Mac::Address &aMacSource, const Mac::Address &aMacDest, const otThreadLinkInfo &aLinkInfo)
void HandleMesh (uint8_t *aFrame, uint16_t aFrameLength, const Mac::Address &aMacSource, const otThreadLinkInfo &aLinkInfo)
void HandleReceivedFrame (Mac::RxFrame &aFrame)
void HandleSentFrame (Mac::TxFrame &aFrame, otError aError)
void HandleUpdateTimer (void)
void LogFragmentFrameDrop (otError aError, uint16_t aFrameLength, const Mac::Address &aMacSource, const Mac::Address &aMacDest, const Lowpan::FragmentHeader &aFragmentHeader, bool aIsSecure)
void LogFrame (const char *aActionText, const Mac::Frame &aFrame, otError aError)
void LogLowpanHcFrameDrop (otError aError, uint16_t aFrameLength, const Mac::Address &aMacSource, const Mac::Address &aMacDest, bool aIsSecure)
void LogMessage (MessageAction aAction, const Message &aMessage, const Mac::Address *aAddress, otError aError)
uint16_t PrepareDataFrame (Mac::TxFrame &aFrame, Message &aMessage, const Mac::Address &aMacSource, const Mac::Address &aMacDest, bool aAddMeshHeader=false, uint16_t aMeshSource=0xffff, uint16_t aMeshDest=0xffff)
otError PrepareDiscoverRequest (void)
void RemoveMessage (Message &aMessage)
void ScheduleTransmissionTask (void)
void SendDestinationUnreachable (uint16_t aMeshSource, const Message &aMessage)
void SendIcmpErrorIfDstUnreach (const Message &aMessage, const Mac::Address &aMacSource, const Mac::Address &aMacDest)
void SendMesh (Message &aMessage, Mac::TxFrame &aFrame)
bool UpdateFragmentLifetime (void)
void UpdateFragmentPriority (Lowpan::FragmentHeader &aFragmentHeader, uint16_t aFragmentLength, uint16_t aSrcRloc16, uint8_t aPriority)
otError UpdateIp6Route (Message &aMessage)
otError UpdateIp6RouteFtd (Ip6::Header &ip6Header, Message &aMessage)
otError UpdateMeshRoute (Message &aMessage)
Neighbor * UpdateNeighborOnSentFrame (Mac::TxFrame &aFrame, otError aError, const Mac::Address &aMacDest)
bool UpdateReassemblyList (void)
void UpdateRoutes (const uint8_t *aFrame, uint16_t aFrameLength, const Mac::Address &aMeshSource, const Mac::Address &aMeshDest)
Static Private Member Functions
static void HandleDiscoverTimer (Timer &aTimer)
static void HandleUpdateTimer (Timer &aTimer)
static void ScheduleTransmissionTask (Tasklet &aTasklet)
Private Attributes
bool mAddMeshHeader
DataPollSender mDataPollSender
TimerMilli mDiscoverTimer
bool mEnabled
uint16_t mFragTag
otIpCounters mIpCounters
Mac::Address mMacDest
Mac::Address mMacSource
uint16_t mMeshDest
uint16_t mMeshSource
uint16_t mMessageNextOffset
MessageQueue mReassemblyList
uint16_t mRestorePanId
uint8_t mScanChannel
Mac::ChannelMask mScanChannels
bool mScanning
Tasklet mScheduleTransmissionTask
bool mSendBusy
Message * mSendMessage
PriorityQueue mSendQueue
TimerMilli mUpdateTimer
Friends
class DataPollSender
class IndirectSender
class Instance
class Mac::Mac
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Detailed Description
This class implements mesh forwarding within Thread.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
kStateUpdatePeriod
State update period in milliseconds.
kDefaultMsgPriority
Default message priority.
kNumFragmentPriorityEntries
The number of fragment priority entries.
MessageAction
enum MessageAction private
< Defines the action parameter in LogMessageInfo() method.
Enumerator
kMessageReceive
Indicates that the message was received.
kMessageTransmit
Indicates that the message was sent.
kMessagePrepareIndirect
Indicates that the message is being prepared for indirect tx.
kMessageDrop
Indicates that the outbound message is being dropped (e.g., dst unknown).
kMessageReassemblyDrop
Indicates that the message is being dropped from reassembly list.
kMessageEvict
Indicates that the message was evicted.
Constructor & Destructor Documentation
MeshForwarder()
MeshForwarder (Instance & aInstance) explicit
This constructor initializes the object.
Parameters
[in] aInstance A reference to the OpenThread instance.
References ot::Random::NonCrypto::GetUint16(), MeshForwarder::mFragTag, and MeshForwarder::ResetCounters().
Member Function Documentation
Start()
void Start (void)
This method enables mesh forwarding and the IEEE 802.15.4 MAC layer.
References MeshForwarder::mEnabled, and MeshForwarder::SetRxOnWhenIdle().
Referenced by MeshForwarder::SetRxOnWhenIdle().
Stop()
void Stop (void)
This method disables mesh forwarding and the IEEE 802.15.4 MAC layer.
References MessageQueue::Dequeue(), PriorityQueue::Dequeue(), Message::Free(), MessageQueue::GetHead(), PriorityQueue::GetHead(), MeshForwarder::HandleDiscoverComplete(), MeshForwarder::mDataPollSender, MeshForwarder::mEnabled, MeshForwarder::mReassemblyList, MeshForwarder::mScanning, MeshForwarder::mSendMessage, MeshForwarder::mSendQueue, MeshForwarder::mUpdateTimer, OT_NOOP, MeshForwarder::SetRxOnWhenIdle(), TimerMilli::Stop(), DataPollSender::StopPolling(), and VerifyOrExit.
Referenced by MeshForwarder::SetRxOnWhenIdle().
SendMessage()
otError SendMessage (Message & aMessage)
This method submits a message to the mesh forwarder for forwarding.
Parameters
[in] aMessage A reference to the message.
Return values
OT_ERROR_NONE Successfully enqueued the message.
OT_ERROR_ALREADY The message was already enqueued.
OT_ERROR_DROP The message could not be sent and should be dropped.
Referenced by ThreadNetif::SendMessage().
HandleResolved()
void HandleResolved (const Ip6::Address & aEid, otError aError)
This method is called by the address resolver when an EID-to-RLOC mapping has been resolved.
Parameters
[in] aEid A reference to the EID that has been resolved.
[in] aError OT_ERROR_NONE on success and OT_ERROR_DROP otherwise.
GetRxOnWhenIdle()
bool GetRxOnWhenIdle (void) const
This method indicates whether or not rx-on-when-idle mode is enabled.
Return values
TRUE The rx-on-when-idle mode is enabled.
FALSE The rx-on-when-idle-mode is disabled.
Referenced by MeshForwarder::HandleFragment().
SetRxOnWhenIdle()
void SetRxOnWhenIdle (bool aRxOnWhenIdle)
This method sets the rx-on-when-idle mode
Parameters
[in] aRxOnWhenIdle TRUE to enable, FALSE otherwise.
References MeshForwarder::mDataPollSender, MeshForwarder::Start(), DataPollSender::StartPolling(), MeshForwarder::Stop(), and DataPollSender::StopPolling().
Referenced by MeshForwarder::Start(), and MeshForwarder::Stop().
SetDiscoverParameters()
void SetDiscoverParameters (const Mac::ChannelMask & aScanChannels)
This method sets the scan parameters for MLE Discovery Request messages.
Parameters
[in] aScanChannels A reference to channel mask indicating which channels to scan. If aScanChannels is empty, then all channels are used instead.
References ChannelMask::GetMask(), ChannelMask::IsEmpty(), MeshForwarder::mScanChannels, and ChannelMask::SetMask().
UpdateIndirectMessages()
void UpdateIndirectMessages (void)
This method frees any indirect messages queued for children that are no longer attached.
RemoveMessages()
void RemoveMessages (Child & aChild, uint8_t aSubType)
This method frees any messages queued for an existing child.
Parameters
[in] aChild A reference to the child.
[in] aSubType The message sub-type to remove. Use Message::kSubTypeNone remove all messages for aChild.
RemoveDataResponseMessages()
void RemoveDataResponseMessages (void)
This method frees unicast/multicast MLE Data Responses from Send Message Queue if any.
EvictMessage()
otError EvictMessage (uint8_t aPriority)
This method evicts the message with lowest priority in the send queue.
Parameters
[in] aPriority The highest priority level of the evicted message.
Return values
OT_ERROR_NONE Successfully evicted a low priority message.
OT_ERROR_NOT_FOUND No low priority messages available to evict.
GetSendQueue()
const PriorityQueue& GetSendQueue (void) const inline
This method returns a reference to the send queue.
Returns
A reference to the send queue.
GetReassemblyQueue()
const MessageQueue& GetReassemblyQueue (void) const inline
This method returns a reference to the reassembly queue.
Returns
A reference to the reassembly queue.
GetCounters()
const otIpCounters& GetCounters (void) const inline
This method returns a reference to the IP level counters.
Returns
A reference to the IP level counters.
ResetCounters()
void ResetCounters (void) inline
This method resets the IP level counters.
Referenced by MeshForwarder::MeshForwarder().
SendIcmpErrorIfDstUnreach()
void SendIcmpErrorIfDstUnreach (const Message & aMessage, const Mac::Address & aMacSource, const Mac::Address & aMacDest) private
Referenced by MeshForwarder::HandleFragment(), and MeshForwarder::HandleLowpanHC().
CheckReachability()
otError CheckReachability (const uint8_t * aFrame, uint16_t aFrameLength, const Mac::Address & aMeshSource, const Mac::Address & aMeshDest) private
UpdateRoutes()
void UpdateRoutes (const uint8_t * aFrame, uint16_t aFrameLength, const Mac::Address & aMeshSource, const Mac::Address & aMeshDest) private
Referenced by MeshForwarder::HandleLowpanHC().
DecompressIp6Header()
otError DecompressIp6Header (const uint8_t * aFrame, uint16_t aFrameLength, const Mac::Address & aMacSource, const Mac::Address & aMacDest, Ip6::Header & aIp6Header, uint8_t & aHeaderLength, bool & aNextHeaderCompressed) private
References FragmentHeader::GetDatagramOffset(), Lowpan::IsLowpanHc(), OT_ERROR_NONE, OT_ERROR_NOT_FOUND, OT_ERROR_PARSE, FragmentHeader::ParseFrom(), and VerifyOrExit.
Referenced by MeshForwarder::GetFramePriority().
FrameToMessage()
otError FrameToMessage (const uint8_t * aFrame, uint16_t aFrameLength, uint16_t aDatagramSize, const Mac::Address & aMacSource, const Mac::Address & aMacDest, Message *& aMessage) private
References MeshForwarder::GetFramePriority(), Message::GetLength(), Message::GetOffset(), Message::kTypeIp6, Message::MoveOffset(), OT_ERROR_NO_BUFS, OT_ERROR_NONE, OT_ERROR_PARSE, Message::SetLength(), SuccessOrExit, VerifyOrExit, and Message::Write().
Referenced by MeshForwarder::HandleFragment(), and MeshForwarder::HandleLowpanHC().
GetIp6Header()
otError GetIp6Header (const uint8_t * aFrame, uint16_t aFrameLength, const Mac::Address & aMacSource, const Mac::Address & aMacDest, Ip6::Header & aIp6Header) private
GetMacDestinationAddress()
void GetMacDestinationAddress (const Ip6::Address & aIp6Addr, Mac::Address & aMacAddr) private
References Address::GetLocator(), Address::IsMulticast(), ot::Mac::kShortAddrBroadcast, Address::SetShort(), and Address::ToExtAddress().
Referenced by MeshForwarder::UpdateIp6Route().
GetMacSourceAddress()
void GetMacSourceAddress (const Ip6::Address & aIp6Addr, Mac::Address & aMacAddr) private
References Address::GetExtended(), Address::SetShort(), and Address::ToExtAddress().
Referenced by MeshForwarder::UpdateIp6Route().
GetDirectTransmission()
Message * GetDirectTransmission (void) private
References PriorityQueue::Dequeue(), ExitNow, Message::Free(), Message::GetDirectTransmission(), PriorityQueue::GetHead(), Message::GetNext(), Message::GetSubType(), Message::GetType(), MeshForwarder::kMessageDrop, Message::kSubTypeMleDiscoverRequest, Message::kType6lowpan, Message::kTypeIp6, MeshForwarder::LogMessage(), MeshForwarder::mSendQueue, OT_ERROR_ADDRESS_QUERY, OT_ERROR_DROP, OT_ERROR_NONE, MeshForwarder::PrepareDiscoverRequest(), Message::SetDoNotEvict(), MeshForwarder::UpdateIp6Route(), and MeshForwarder::UpdateMeshRoute().
Referenced by MeshForwarder::ScheduleTransmissionTask().
PrepareDiscoverRequest()
otError PrepareDiscoverRequest (void) private
References ExitNow, ChannelMask::GetNextChannel(), MeshForwarder::HandleDiscoverComplete(), ChannelMask::kChannelIteratorFirst, MeshForwarder::mRestorePanId, MeshForwarder::mScanChannel, MeshForwarder::mScanChannels, MeshForwarder::mScanning, OT_ERROR_DROP, OT_ERROR_NONE, OT_NOOP, and VerifyOrExit.
Referenced by MeshForwarder::GetDirectTransmission().
HandleMesh()
void HandleMesh (uint8_t * aFrame, uint16_t aFrameLength, const Mac::Address & aMacSource, const otThreadLinkInfo & aLinkInfo) private
Referenced by MeshForwarder::HandleReceivedFrame().
HandleFragment()
void HandleFragment (const uint8_t * aFrame, uint16_t aFrameLength, const Mac::Address & aMacSource, const Mac::Address & aMacDest, const otThreadLinkInfo & aLinkInfo) private
References Message::AddRss(), MeshForwarder::ClearReassemblyList(), MessageQueue::Dequeue(), MessageQueue::Enqueue(), MeshForwarder::FrameToMessage(), Message::Free(), FragmentHeader::GetDatagramOffset(), FragmentHeader::GetDatagramSize(), Message::GetDatagramTag(), FragmentHeader::GetDatagramTag(), MessageQueue::GetHead(), Message::GetLength(), Message::GetNext(), Message::GetOffset(), MeshForwarder::GetRxOnWhenIdle(), MeshForwarder::HandleDatagram(), Message::IsLinkSecurityEnabled(), Timer::IsRunning(), ot::kReassemblyTimeout, MeshForwarder::kStateUpdatePeriod, MeshForwarder::LogFragmentFrameDrop(), otThreadLinkInfo::mLinkSecurity, otThreadLinkInfo::mNetworkTimeOffset, Message::MoveOffset(), otThreadLinkInfo::mPanId, MeshForwarder::mReassemblyList, otThreadLinkInfo::mRss, otThreadLinkInfo::mTimeSyncSeq, MeshForwarder::mUpdateTimer, OT_ERROR_DROP, OT_ERROR_NONE, OT_ERROR_PARSE, FragmentHeader::ParseFrom(), MeshForwarder::SendIcmpErrorIfDstUnreach(), Message::SetDatagramTag(), Message::SetLength(), Message::SetLinkSecurityEnabled(), Message::SetPanId(), Message::SetTimeout(), TimerMilli::Start(), SuccessOrExit, VerifyOrExit, and Message::Write().
Referenced by MeshForwarder::HandleReceivedFrame().
HandleLowpanHC()
void HandleLowpanHC (const uint8_t * aFrame, uint16_t aFrameLength, const Mac::Address & aMacSource, const Mac::Address & aMacDest, const otThreadLinkInfo & aLinkInfo) private
References Message::AddRss(), MeshForwarder::FrameToMessage(), Message::Free(), MeshForwarder::HandleDatagram(), MeshForwarder::LogLowpanHcFrameDrop(), otThreadLinkInfo::mLinkSecurity, otThreadLinkInfo::mNetworkTimeOffset, otThreadLinkInfo::mPanId, otThreadLinkInfo::mRss, otThreadLinkInfo::mTimeSyncSeq, OT_ERROR_DROP, OT_ERROR_NONE, MeshForwarder::SendIcmpErrorIfDstUnreach(), Message::SetLinkSecurityEnabled(), Message::SetPanId(), SuccessOrExit, MeshForwarder::UpdateRoutes(), and VerifyOrExit.
Referenced by MeshForwarder::HandleReceivedFrame().
PrepareDataFrame()
uint16_t PrepareDataFrame (Mac::TxFrame & aFrame, Message & aMessage, const Mac::Address & aMacSource, const Mac::Address & aMacDest, bool aAddMeshHeader = false, uint16_t aMeshSource = 0xffff, uint16_t aMeshDest = 0xffff) private
References Message::GetChannel(), Message::GetDatagramTag(), Message::GetLength(), Frame::GetMaxPayloadLength(), Message::GetOffset(), Message::GetPanId(), Frame::GetPayload(), Message::GetSubType(), HeaderIe::Init(), FragmentHeader::Init(), FragmentHeader::InitFirstFragment(), Frame::InitMacHeader(), Mle::IsActiveRouter(), Address::IsBroadcast(), Address::IsExtended(), Message::IsLinkSecurityEnabled(), Address::IsShort(), Message::IsSubTypeMle(), MeshHeader::kAdditionalHopsLeft, Frame::kFcfAckRequest, Frame::kFcfDstAddrExt, Frame::kFcfDstAddrMask, Frame::kFcfDstAddrShort, Frame::kFcfFrameData, Frame::kFcfFrameVersion2006, Frame::kFcfFrameVersion2015, Frame::kFcfFrameVersionMask, Frame::kFcfIePresent, Frame::kFcfPanidCompression, Frame::kFcfSecurityEnabled, Frame::kFcfSrcAddrExt, Frame::kFcfSrcAddrMask, Frame::kFcfSrcAddrShort, FragmentHeader::kFirstFragmentHeaderSize, Frame::kHeaderIeTermination2, Frame::kHeaderIeVendor, Frame::kKeyIdMode0, Frame::kKeyIdMode1, Frame::kKeyIdMode2, ot::Mle::kMaxRouteCost, ot::Mac::kPanIdBroadcast, Frame::kSecEncMic32, Frame::kSecNone, Message::kSubTypeJoinerEntrust, Message::kSubTypeMleAnnounce, Message::kSubTypeMleDiscoverRequest, Message::kSubTypeMleDiscoverResponse, MeshForwarder::mFragTag, OT_ASSERT, OT_ERROR_NONE, OT_UNUSED_VARIABLE, Message::Read(), Mle::RouterIdFromRloc16(), Frame::SetChannel(), Message::SetDatagramTag(), Frame::SetDstAddr(), Frame::SetDstPanId(), Frame::SetFramePending(), HeaderIe::SetId(), HeaderIe::SetLength(), Message::SetLinkSecurityEnabled(), Message::SetOffset(), Frame::SetPayloadLength(), Address::SetShort(), Frame::SetSrcAddr(), Frame::SetSrcPanId(), and FragmentHeader::WriteTo().
Referenced by MeshForwarder::HandleFrameRequest().
SendMesh()
void SendMesh (Message & aMessage, Mac::TxFrame & aFrame) private
Referenced by MeshForwarder::HandleFrameRequest().
SendDestinationUnreachable()
void SendDestinationUnreachable (uint16_t aMeshSource, const Message & aMessage) private
UpdateIp6Route()
otError UpdateIp6Route (Message & aMessage) private
References ExitNow, Header::GetDestination(), MeshForwarder::GetMacDestinationAddress(), MeshForwarder::GetMacSourceAddress(), Header::GetSource(), Address::IsLinkLocal(), Address::IsLinkLocalMulticast(), Address::IsMulticast(), Message::IsSubTypeMle(), ot::Mac::kShortAddrBroadcast, MeshForwarder::mAddMeshHeader, MeshForwarder::mMacDest, MeshForwarder::mMacSource, OT_ASSERT, OT_ERROR_DROP, OT_ERROR_NONE, Message::Read(), Address::SetShort(), MeshForwarder::UpdateIp6RouteFtd(), and VerifyOrExit.
Referenced by MeshForwarder::GetDirectTransmission().
UpdateIp6RouteFtd()
otError UpdateIp6RouteFtd (Ip6::Header & ip6Header, Message & aMessage) private
Referenced by MeshForwarder::UpdateIp6Route().
UpdateMeshRoute()
otError UpdateMeshRoute (Message & aMessage) private
Referenced by MeshForwarder::GetDirectTransmission().
UpdateReassemblyList()
bool UpdateReassemblyList (void) private
References Message::DecrementTimeout(), MessageQueue::Dequeue(), MessageQueue::GetHead(), Message::GetNext(), MeshForwarder::kMessageReassemblyDrop, Message::kTypeIp6, MeshForwarder::LogMessage(), MeshForwarder::mIpCounters, MeshForwarder::mReassemblyList, otIpCounters::mRxFailure, and OT_ERROR_REASSEMBLY_TIMEOUT.
Referenced by MeshForwarder::HandleUpdateTimer().
UpdateFragmentLifetime()
bool UpdateFragmentLifetime (void) private
Referenced by MeshForwarder::HandleUpdateTimer().
UpdateFragmentPriority()
void UpdateFragmentPriority (Lowpan::FragmentHeader & aFragmentHeader, uint16_t aFragmentLength, uint16_t aSrcRloc16, uint8_t aPriority) private
HandleDatagram()
otError HandleDatagram (Message & aMessage, const otThreadLinkInfo & aLinkInfo, const Mac::Address & aMacSource) private
References Message::GetType(), MeshForwarder::kMessageReceive, Message::kTypeIp6, MeshForwarder::LogMessage(), MeshForwarder::mIpCounters, otIpCounters::mRxSuccess, and OT_ERROR_NONE.
Referenced by MeshForwarder::HandleFragment(), and MeshForwarder::HandleLowpanHC().
ClearReassemblyList()
void ClearReassemblyList (void) private
References MessageQueue::Dequeue(), Message::Free(), MessageQueue::GetHead(), Message::GetNext(), Message::GetType(), MeshForwarder::kMessageReassemblyDrop, Message::kTypeIp6, MeshForwarder::LogMessage(), MeshForwarder::mIpCounters, MeshForwarder::mReassemblyList, otIpCounters::mRxFailure, and OT_ERROR_NO_FRAME_RECEIVED.
Referenced by MeshForwarder::HandleFragment().
RemoveMessage()
void RemoveMessage (Message & aMessage) private
References PriorityQueue::Dequeue(), Message::Free(), InstanceLocator::GetInstance(), Message::GetPriorityQueue(), IgnoreReturnValue, Neighbor::kInStateAnyExceptInvalid, MeshForwarder::kMessageEvict, MeshForwarder::LogMessage(), MeshForwarder::mSendMessage, MeshForwarder::mSendQueue, OT_ASSERT, and OT_ERROR_NO_BUFS.
HandleDiscoverComplete()
void HandleDiscoverComplete (void) private
References MeshForwarder::mDiscoverTimer, MeshForwarder::mRestorePanId, MeshForwarder::mScanning, OT_ASSERT, and TimerMilli::Stop().
Referenced by MeshForwarder::HandleDiscoverTimer(), MeshForwarder::PrepareDiscoverRequest(), and MeshForwarder::Stop().
HandleReceivedFrame()
void HandleReceivedFrame (Mac::RxFrame & aFrame) private
References ExitNow, Frame::GetChannel(), Frame::GetDstAddr(), RxFrame::GetLqi(), Frame::GetPayload(), Frame::GetPayloadLength(), RxFrame::GetRssi(), Frame::GetSecurityEnabled(), Frame::GetSrcAddr(), Frame::GetSrcPanId(), Frame::GetType(), MeshForwarder::HandleFragment(), MeshForwarder::HandleLowpanHC(), MeshForwarder::HandleMesh(), FragmentHeader::IsFragmentHeader(), Lowpan::IsLowpanHc(), MeshHeader::IsMeshHeader(), Frame::kFcfFrameBeacon, Frame::kFcfFrameData, MeshForwarder::LogFrame(), otThreadLinkInfo::mChannel, MeshForwarder::mEnabled, otThreadLinkInfo::mLinkSecurity, otThreadLinkInfo::mLqi, otThreadLinkInfo::mNetworkTimeOffset, otThreadLinkInfo::mPanId, otThreadLinkInfo::mRss, otThreadLinkInfo::mTimeSyncSeq, OT_ERROR_DROP, OT_ERROR_INVALID_STATE, OT_ERROR_NONE, OT_ERROR_NOT_LOWPAN_DATA_FRAME, SuccessOrExit, and VerifyOrExit.
HandleFrameRequest()
otError HandleFrameRequest (Mac::TxFrame & aFrame) private
References ExitNow, ot::Mac::GenerateRandomPanId(), Message::GetLength(), Frame::GetLength(), Message::GetPanId(), Message::GetSubType(), Message::GetType(), Message::IsLinkSecurityEnabled(), ot::Mac::kPanIdBroadcast, Message::kSubTypeMleChildIdRequest, Message::kSubTypeMleDiscoverRequest, Message::kType6lowpan, Message::kTypeIp6, Message::kTypeSupervision, MeshForwarder::mAddMeshHeader, MeshForwarder::mEnabled, MeshForwarder::mMacDest, MeshForwarder::mMacSource, MeshForwarder::mMeshDest, MeshForwarder::mMeshSource, MeshForwarder::mMessageNextOffset, MeshForwarder::mScanChannel, MeshForwarder::mSendBusy, MeshForwarder::mSendMessage, OT_ASSERT, OT_ERROR_ABORT, OT_ERROR_NONE, otLogNoteMac, MeshForwarder::PrepareDataFrame(), MeshForwarder::SendMesh(), Frame::SetChannel(), TxFrame::SetIsARetransmission(), SuccessOrExit, and VerifyOrExit.
UpdateNeighborOnSentFrame()
Neighbor * UpdateNeighborOnSentFrame (Mac::TxFrame & aFrame, otError aError, const Mac::Address & aMacDest) private
References Frame::GetAckRequest(), Neighbor::GetLinkFailures(), Neighbor::GetRloc16(), Neighbor::IncrementLinkFailures(), Mle::IsActiveRouter(), ot::Mle::kFailedRouterTransmissions, MeshForwarder::mEnabled, OT_ERROR_NO_ACK, OT_ERROR_NONE, OT_NOOP, Neighbor::ResetLinkFailures(), and VerifyOrExit.
Referenced by MeshForwarder::HandleSentFrame().
HandleSentFrame()
void HandleSentFrame (Mac::TxFrame & aFrame, otError aError) private
References LinkQualityInfo::AddMessageTxStatus(), Message::ClearDirectTransmission(), PriorityQueue::Dequeue(), ExitNow, Message::Free(), Message::GetDirectTransmission(), Frame::GetDstAddr(), Message::GetLength(), Neighbor::GetLinkInfo(), Message::GetSubType(), Message::GetTxSuccess(), Message::GetType(), Message::IsChildPending(), Frame::IsEmpty(), Message::IsLinkSecurityEnabled(), MeshForwarder::kMessageTransmit, ot::Mac::kScanDurationDefault, Message::kSubTypeMleChildIdRequest, Message::kSubTypeMleDiscoverRequest, Message::kTypeIp6, MeshForwarder::LogMessage(), MeshForwarder::mDiscoverTimer, MeshForwarder::mEnabled, MeshForwarder::mIpCounters, MeshForwarder::mMessageNextOffset, MeshForwarder::mScheduleTransmissionTask, MeshForwarder::mSendBusy, MeshForwarder::mSendMessage, MeshForwarder::mSendQueue, otIpCounters::mTxFailure, otIpCounters::mTxSuccess, OT_ASSERT, OT_ERROR_ABORT, OT_ERROR_CHANNEL_ACCESS_FAILURE, OT_ERROR_FAILED, OT_ERROR_NO_ACK, OT_ERROR_NONE, OT_NOOP, otLogInfoMac, Tasklet::Post(), Message::SetOffset(), Message::SetTxSuccess(), TimerMilli::Start(), MeshForwarder::UpdateNeighborOnSentFrame(), and VerifyOrExit.
HandleDiscoverTimer() [1/2]
void HandleDiscoverTimer (Timer & aTimer) static private
References OwnerLocator::GetOwner(), and MeshForwarder::HandleDiscoverTimer().
HandleDiscoverTimer() [2/2]
void HandleDiscoverTimer (void) private
References PriorityQueue::Dequeue(), ExitNow, Message::Free(), ChannelMask::GetNextChannel(), MeshForwarder::HandleDiscoverComplete(), MeshForwarder::mScanChannel, MeshForwarder::mScanChannels, MeshForwarder::mScheduleTransmissionTask, MeshForwarder::mSendBusy, MeshForwarder::mSendMessage, MeshForwarder::mSendQueue, OT_ERROR_NONE, Tasklet::Post(), and Message::SetDirectTransmission().
Referenced by MeshForwarder::HandleDiscoverTimer().
HandleUpdateTimer() [1/2]
void HandleUpdateTimer (Timer & aTimer) static private
References OwnerLocator::GetOwner(), and MeshForwarder::HandleUpdateTimer().
HandleUpdateTimer() [2/2]
void HandleUpdateTimer (void) private
References MeshForwarder::kStateUpdatePeriod, MeshForwarder::mUpdateTimer, TimerMilli::Start(), MeshForwarder::UpdateFragmentLifetime(), and MeshForwarder::UpdateReassemblyList().
Referenced by MeshForwarder::HandleUpdateTimer().
ScheduleTransmissionTask() [1/2]
void ScheduleTransmissionTask (Tasklet & aTasklet) static private
References OwnerLocator::GetOwner(), and MeshForwarder::ScheduleTransmissionTask().
ScheduleTransmissionTask() [2/2]
void ScheduleTransmissionTask (void) private
References MeshForwarder::GetDirectTransmission(), Message::GetOffset(), MeshForwarder::mSendBusy, MeshForwarder::mSendMessage, OT_NOOP, Message::SetTxSuccess(), and VerifyOrExit.
Referenced by MeshForwarder::ScheduleTransmissionTask().
GetFramePriority()
otError GetFramePriority (const uint8_t * aFrame, uint16_t aFrameLength, const Mac::Address & aMacSource, const Mac::Address & aMacDest, uint8_t & aPriority) private
References String< SIZE >::AsCString(), MeshForwarder::DecompressIp6Header(), Ip6::DscpToPriority(), FragmentHeader::GetDatagramOffset(), FragmentHeader::GetDatagramSize(), FragmentHeader::GetDatagramTag(), Header::GetDestination(), UdpHeader::GetDestinationPort(), Header::GetDscp(), InstanceLocator::GetInstance(), Message::GetLength(), Header::GetNextHeader(), Message::GetPriority(), Message::GetRssAverager(), Header::GetSource(), Message::GetType(), Ip6::IpProtoToString(), Message::IsLinkSecurityEnabled(), Header::IsVersion6(), ot::kCoapUdpPort, MeshForwarder::kMessageDrop, MeshForwarder::kMessageEvict, MeshForwarder::kMessagePrepareIndirect, MeshForwarder::kMessageReassemblyDrop, MeshForwarder::kMessageReceive, MeshForwarder::kMessageTransmit, Message::kPriorityHigh, Message::kPriorityLow, Message::kPriorityNet, Message::kPriorityNormal, ot::Ip6::kProtoTcp, ot::Ip6::kProtoUdp, Message::kType6lowpan, Message::kTypeIp6, ot::Mle::kUdpPort, MeshForwarder::LogFragmentFrameDrop(), MeshForwarder::LogFrame(), MeshForwarder::LogLowpanHcFrameDrop(), MeshForwarder::LogMessage(), OT_ERROR_NONE, OT_ERROR_PARSE, OT_LOG_LEVEL_INFO, OT_LOG_LEVEL_NOTE, OT_NOOP, otLogInfoMac, otLogMac, otLogNoteMac, otThreadErrorToString(), Message::Read(), SuccessOrExit, Frame::ToInfoString(), RssAverager::ToString(), Address::ToString(), and VerifyOrExit.
Referenced by MeshForwarder::FrameToMessage().
GetFragmentPriority()
otError GetFragmentPriority (Lowpan::FragmentHeader & aFragmentHeader, uint16_t aSrcRloc16, uint8_t & aPriority) private
GetForwardFramePriority()
otError GetForwardFramePriority (const uint8_t * aFrame, uint16_t aFrameLength, const Mac::Address & aMeshSource, const Mac::Address & aMeshDest, uint8_t & aPriority) private
FindFragmentPriorityEntry()
FragmentPriorityEntry* FindFragmentPriorityEntry (uint16_t aTag, uint16_t aSrcRloc16) private
GetUnusedFragmentPriorityEntry()
FragmentPriorityEntry* GetUnusedFragmentPriorityEntry (void) private
GetDestinationRlocByServiceAloc()
otError GetDestinationRlocByServiceAloc (uint16_t aServiceAloc, uint16_t & aMeshDest) private
LogMessage()
void LogMessage (MessageAction aAction, const Message & aMessage, const Mac::Address * aAddress, otError aError) private
Referenced by MeshForwarder::ClearReassemblyList(), MeshForwarder::GetDirectTransmission(), MeshForwarder::GetFramePriority(), MeshForwarder::HandleDatagram(), MeshForwarder::HandleSentFrame(), MeshForwarder::RemoveMessage(), and MeshForwarder::UpdateReassemblyList().
LogFrame()
void LogFrame (const char * aActionText, const Mac::Frame & aFrame, otError aError) private
Referenced by MeshForwarder::GetFramePriority(), and MeshForwarder::HandleReceivedFrame().
LogFragmentFrameDrop()
void LogFragmentFrameDrop (otError aError, uint16_t aFrameLength, const Mac::Address & aMacSource, const Mac::Address & aMacDest, const Lowpan::FragmentHeader & aFragmentHeader, bool aIsSecure) private
Referenced by MeshForwarder::GetFramePriority(), and MeshForwarder::HandleFragment().
LogLowpanHcFrameDrop()
void LogLowpanHcFrameDrop (otError aError, uint16_t aFrameLength, const Mac::Address & aMacSource, const Mac::Address & aMacDest, bool aIsSecure) private
Referenced by MeshForwarder::GetFramePriority(), and MeshForwarder::HandleLowpanHC().
Friends And Related Function Documentation
Mac::Mac
friend class Mac::Mac friend
Instance
friend class Instance friend
DataPollSender
friend class DataPollSender friend
IndirectSender
friend class IndirectSender friend
Field Documentation
mDiscoverTimer
TimerMilli mDiscoverTimer private
Referenced by MeshForwarder::HandleDiscoverComplete(), and MeshForwarder::HandleSentFrame().
mUpdateTimer
TimerMilli mUpdateTimer private
Referenced by MeshForwarder::HandleFragment(), MeshForwarder::HandleUpdateTimer(), and MeshForwarder::Stop().
mSendQueue
PriorityQueue mSendQueue private
Referenced by MeshForwarder::GetDirectTransmission(), MeshForwarder::HandleDiscoverTimer(), MeshForwarder::HandleSentFrame(), MeshForwarder::RemoveMessage(), and MeshForwarder::Stop().
mReassemblyList
MessageQueue mReassemblyList private
Referenced by MeshForwarder::ClearReassemblyList(), MeshForwarder::HandleFragment(), MeshForwarder::Stop(), and MeshForwarder::UpdateReassemblyList().
mFragTag
uint16_t mFragTag private
Referenced by MeshForwarder::MeshForwarder(), and MeshForwarder::PrepareDataFrame().
mMessageNextOffset
uint16_t mMessageNextOffset private
Referenced by MeshForwarder::HandleFrameRequest(), and MeshForwarder::HandleSentFrame().
mSendMessage
Message* mSendMessage private
Referenced by MeshForwarder::HandleDiscoverTimer(), MeshForwarder::HandleFrameRequest(), MeshForwarder::HandleSentFrame(), MeshForwarder::RemoveMessage(), MeshForwarder::ScheduleTransmissionTask(), and MeshForwarder::Stop().
mMacSource
Mac::Address mMacSource private
Referenced by MeshForwarder::HandleFrameRequest(), and MeshForwarder::UpdateIp6Route().
mMacDest
Mac::Address mMacDest private
Referenced by MeshForwarder::HandleFrameRequest(), and MeshForwarder::UpdateIp6Route().
mMeshSource
uint16_t mMeshSource private
Referenced by MeshForwarder::HandleFrameRequest().
mMeshDest
uint16_t mMeshDest private
Referenced by MeshForwarder::HandleFrameRequest().
mAddMeshHeader
bool mAddMeshHeader private
Referenced by MeshForwarder::HandleFrameRequest(), and MeshForwarder::UpdateIp6Route().
mSendBusy
bool mSendBusy private
Referenced by MeshForwarder::HandleDiscoverTimer(), MeshForwarder::HandleFrameRequest(), MeshForwarder::HandleSentFrame(), and MeshForwarder::ScheduleTransmissionTask().
mScheduleTransmissionTask
Tasklet mScheduleTransmissionTask private
Referenced by MeshForwarder::HandleDiscoverTimer(), and MeshForwarder::HandleSentFrame().
mEnabled
bool mEnabled private
Referenced by MeshForwarder::HandleFrameRequest(), MeshForwarder::HandleReceivedFrame(), MeshForwarder::HandleSentFrame(), MeshForwarder::Start(), MeshForwarder::Stop(), and MeshForwarder::UpdateNeighborOnSentFrame().
mScanChannels
Mac::ChannelMask mScanChannels private
Referenced by MeshForwarder::HandleDiscoverTimer(), MeshForwarder::PrepareDiscoverRequest(), and MeshForwarder::SetDiscoverParameters().
mScanChannel
uint8_t mScanChannel private
Referenced by MeshForwarder::HandleDiscoverTimer(), MeshForwarder::HandleFrameRequest(), and MeshForwarder::PrepareDiscoverRequest().
mRestorePanId
uint16_t mRestorePanId private
Referenced by MeshForwarder::HandleDiscoverComplete(), and MeshForwarder::PrepareDiscoverRequest().
mScanning
bool mScanning private
Referenced by MeshForwarder::HandleDiscoverComplete(), MeshForwarder::PrepareDiscoverRequest(), and MeshForwarder::Stop().
mIpCounters
otIpCounters mIpCounters private
Referenced by MeshForwarder::ClearReassemblyList(), MeshForwarder::HandleDatagram(), MeshForwarder::HandleSentFrame(), and MeshForwarder::UpdateReassemblyList().
mDataPollSender
DataPollSender mDataPollSender private
Referenced by MeshForwarder::SetRxOnWhenIdle(), and MeshForwarder::Stop().
The documentation for this class was generated from the following files:
mesh_forwarder.hpp
mesh_forwarder.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale