OpenThread: SettingsDriver Class Reference
SettingsDriver Class Reference
#include <settings.hpp>
Public Member Functions
otError Add (uint16_t aKey, const uint8_t *aValue, uint16_t aValueLength)
void Deinit (void)
otError Delete (uint16_t aKey, int aIndex)
otError Get (uint16_t aKey, int aIndex, uint8_t *aValue, uint16_t *aValueLength) const
void Init (void)
otError Set (uint16_t aKey, const uint8_t *aValue, uint16_t aValueLength)
SettingsDriver (Instance &aInstance)
void Wipe (void)
Public Member Functions inherited from InstanceLocator
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Constructor & Destructor Documentation
SettingsDriver()
SettingsDriver (Instance & aInstance) explicit
Constructor.
Referenced by SettingsDriver::Wipe().
Member Function Documentation
Init()
void Init (void)
This method initializes the settings storage driver.
References InstanceLocator::GetInstance(), and otPlatSettingsInit().
Referenced by Settings::Init(), and SettingsDriver::Wipe().
Deinit()
void Deinit (void)
This method deinitializes the settings driver.
References InstanceLocator::GetInstance(), and otPlatSettingsDeinit().
Referenced by Settings::Deinit(), and SettingsDriver::Wipe().
Add()
otError Add (uint16_t aKey, const uint8_t * aValue, uint16_t aValueLength)
This method adds a value to aKey.
Parameters
[in] aKey The key associated with the value.
[in] aValue A pointer to where the new value of the setting should be read from. MUST NOT be NULL if aValueLength is non-zero.
[in] aValueLength The length of the data pointed to by aValue. May be zero.
Return values
OT_ERROR_NONE The value was added.
OT_ERROR_NO_BUFS Not enough space to store the value.
References InstanceLocator::GetInstance(), and otPlatSettingsAdd().
Referenced by Settings::AddChildInfo(), and SettingsDriver::Wipe().
Delete()
otError Delete (uint16_t aKey, int aIndex)
This method removes a value from aKey.
Parameters
[in] aKey The key associated with the value.
[in] aIndex The index of the value to be removed. If set to -1, all values for aKey will be removed.
Return values
OT_ERROR_NONE The given key and index was found and removed successfully.
OT_ERROR_NOT_FOUND The given key or index was not found.
References InstanceLocator::GetInstance(), and otPlatSettingsDelete().
Referenced by Settings::DeleteChildInfo(), Settings::DeleteNetworkInfo(), Settings::DeleteOperationalDataset(), Settings::DeleteParentInfo(), and SettingsDriver::Wipe().
Get()
otError Get (uint16_t aKey, int aIndex, uint8_t * aValue, uint16_t * aValueLength) const
This method fetches the value identified by aKey.
Parameters
[in] aKey The key associated with the requested value.
[in] aIndex The index of the specific item to get.
[out] aValue A pointer to where the value of the setting should be written. May be NULL if just testing for the presence or length of a key.
[in,out] aValueLength A pointer to the length of the value. When called, this should point to an integer containing the maximum bytes that can be written to aValue. At return, the actual length of the setting is written. May be NULL if performing a presence check.
Return values
OT_ERROR_NONE The value was fetched successfully.
OT_ERROR_NOT_FOUND The key was not found.
References InstanceLocator::GetInstance(), and otPlatSettingsGet().
Set()
otError Set (uint16_t aKey, const uint8_t * aValue, uint16_t aValueLength)
This method sets or replaces the value identified by aKey.
If there was more than one value previously associated with aKey, then they are all deleted and replaced with this single entry.
Parameters
[in] aKey The key associated with the value.
[in] aValue A pointer to where the new value of the setting should be read from. MUST NOT be NULL if aValueLength is non-zero.
[in] aValueLength The length of the data pointed to by aValue. May be zero.
Return values
OT_ERROR_NONE The value was changed.
OT_ERROR_NO_BUFS Not enough space to store the value.
References InstanceLocator::GetInstance(), and otPlatSettingsSet().
Referenced by SettingsDriver::Wipe().
Wipe()
void Wipe (void)
This method remves all values.
References SettingsDriver::Add(), SettingsDriver::Deinit(), SettingsDriver::Delete(), InstanceLocator::Get(), InstanceLocator::GetInstance(), SettingsDriver::Init(), InstanceLocator::InstanceLocator(), otPlatSettingsWipe(), SettingsDriver::Set(), and SettingsDriver::SettingsDriver().
Referenced by Settings::Wipe().
The documentation for this class was generated from the following files:
settings.hpp
core/common/settings.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale