OpenThread: HasRouteEntry Class Reference
HasRouteEntry Class Reference
Core-netdata » TLVs
#include <network_data_tlvs.hpp>
Public Member Functions
HasRouteEntry * GetNext (void)
const HasRouteEntry * GetNext (void) const
int8_t GetPreference (void) const
uint16_t GetRloc (void) const
void Init (void)
bool operator== (const HasRouteEntry &aOtherEntry) const
void SetPreference (int8_t aPrf)
void SetRloc (uint16_t aRloc16)
Private Types
enum { kPreferenceOffset = 6, kPreferenceMask = 3 << kPreferenceOffset }
Private Attributes
uint8_t mFlags
uint16_t mRloc
Detailed Description
This class implements Has Route TLV entry generation and parsing.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
kPreferenceOffset
kPreferenceMask
Member Function Documentation
Init()
void Init (void) inline
This method initializes the header.
References ot::Mac::kShortAddrInvalid.
GetRloc()
uint16_t GetRloc (void) const inline
This method returns the RLOC16 value.
Returns
The RLOC16 value.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by LeaderBase::ExternalRouteLookup(), and NetworkData::Iterate().
SetRloc()
void SetRloc (uint16_t aRloc16) inline
This method sets the RLOC16 value.
Parameters
[in] aRloc16 The RLOC16 value.
References ot::Encoding::BigEndian::HostSwap16().
GetPreference()
int8_t GetPreference (void) const inline
This method returns the Preference value.
Returns
The preference value.
Referenced by LeaderBase::ExternalRouteLookup(), and NetworkData::Iterate().
SetPreference()
void SetPreference (int8_t aPrf) inline
This method sets the Preference value.
Parameters
[in] aPrf The Preference value.
References OT_ASSERT, OT_ROUTE_PREFERENCE_HIGH, OT_ROUTE_PREFERENCE_LOW, and OT_ROUTE_PREFERENCE_MED.
GetNext() [1/2]
HasRouteEntry* GetNext (void) inline
This method returns a pointer to the next HasRouteEntry.
Returns
A pointer to the next HasRouteEntry.
Referenced by LeaderBase::ExternalRouteLookup(), and NetworkData::RemoveTemporaryData().
GetNext() [2/2]
const HasRouteEntry* GetNext (void) const inline
This method returns a pointer to the next HasRouteEntry.
Returns
A pointer to the next HasRouteEntry.
operator==()
bool operator== (const HasRouteEntry & aOtherEntry) const inline
This method indicates whether two entries fully match.
Parameters
[in] aOtherEntry Another entry to compare with it.
Return values
TRUE The two entries are equal.
FALSE The two entries are not equal.
Field Documentation
mRloc
uint16_t mRloc private
mFlags
uint8_t mFlags private
The documentation for this class was generated from the following file:
network_data_tlvs.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale