OpenThread: Settings Class Reference
Settings Class Reference
#include <settings.hpp>
Data Structures
class ChildInfoIterator
Public Member Functions
otError AddChildInfo (const ChildInfo &aChildInfo)
void Deinit (void)
otError DeleteChildInfo (void)
otError DeleteNetworkInfo (void)
otError DeleteOperationalDataset (bool aIsActive)
otError DeleteParentInfo (void)
void Init (void)
otError ReadNetworkInfo (NetworkInfo &aNetworkInfo) const
otError ReadOperationalDataset (bool aIsActive, MeshCoP::Dataset &aDataset) const
otError ReadParentInfo (ParentInfo &aParentInfo) const
otError SaveNetworkInfo (const NetworkInfo &aNetworkInfo)
otError SaveOperationalDataset (bool aIsActive, const MeshCoP::Dataset &aDataset)
otError SaveParentInfo (const ParentInfo &aParentInfo)
Settings (Instance &aInstance)
void Wipe (void)
Public Member Functions inherited from InstanceLocator
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Private Member Functions
otError Add (Key aKey, const void *aValue, uint16_t aSize)
otError Delete (Key aKey)
otError Read (Key aKey, void *aBuffer, uint16_t &aSize) const
otError Save (Key aKey, const void *aValue, uint16_t aSize)
Additional Inherited Members
Public Types inherited from SettingsBase
enum Key {
kKeyActiveDataset = 0x0001, kKeyPendingDataset = 0x0002, kKeyNetworkInfo = 0x0003, kKeyParentInfo = 0x0004,
kKeyChildInfo = 0x0005, kKeyReserved = 0x0006, kKeySlaacIidSecretKey = 0x0007
}
Data Fields inherited from SettingsBase
OT_TOOL_PACKED_BEGIN class ot::SettingsBase::NetworkInfo OT_TOOL_PACKED_END
OT_TOOL_PACKED_BEGIN class ot::SettingsBase::ParentInfo OT_TOOL_PACKED_END
OT_TOOL_PACKED_BEGIN class ot::SettingsBase::ChildInfo OT_TOOL_PACKED_END
Protected Member Functions inherited from SettingsBase
void LogChildInfo (const char *, const ChildInfo &) const
void LogFailure (otError, const char *, bool) const
void LogNetworkInfo (const char *, const NetworkInfo &) const
void LogParentInfo (const char *, const ParentInfo &) const
SettingsBase (Instance &aInstance)
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Detailed Description
This class defines methods related to non-volatile storage of settings.
Constructor & Destructor Documentation
Settings()
Settings (Instance & aInstance) inline explicit
This constructor initializes a Settings object.
Parameters
[in] aInstance A reference to the OpenThread instance.
Member Function Documentation
Init()
void Init (void)
This method initializes the platform settings (non-volatile) module.
This should be called before any other method from this class.
References SettingsDriver::Init().
Deinit()
void Deinit (void)
This method de-initializes the platform settings (non-volatile) module.
This method should be called when OpenThread instance is no longer in use.
References SettingsDriver::Deinit().
Wipe()
void Wipe (void)
This method removes all settings from the non-volatile store.
References otLogInfoCore, and SettingsDriver::Wipe().
SaveOperationalDataset()
otError SaveOperationalDataset (bool aIsActive, const MeshCoP::Dataset & aDataset)
This method saves the Operational Dataset (active or pending).
Parameters
[in] aIsActive Indicates whether Dataset is active or pending.
[in] aDataset A reference to a Dataset object to be saved.
Return values
OT_ERROR_NONE Successfully saved the Dataset.
OT_ERROR_NOT_IMPLEMENTED The platform does not implement settings functionality.
References Dataset::GetBytes(), and Dataset::GetSize().
ReadOperationalDataset()
otError ReadOperationalDataset (bool aIsActive, MeshCoP::Dataset & aDataset) const
This method reads the Operational Dataset (active or pending).
Parameters
[in] aIsActive Indicates whether Dataset is active or pending.
[out] aDataset A reference to a Dataset object to output the read content.
Return values
OT_ERROR_NONE Successfully read the Dataset.
OT_ERROR_NOT_FOUND No corresponding value in the setting store.
OT_ERROR_NOT_IMPLEMENTED The platform does not implement settings functionality.
References Dataset::GetBytes(), Dataset::kMaxSize, OT_ERROR_NONE, OT_ERROR_NOT_FOUND, Dataset::SetSize(), SuccessOrExit, and VerifyOrExit.
DeleteOperationalDataset()
otError DeleteOperationalDataset (bool aIsActive)
This method deletes the Operational Dataset (active/pending) from settings.
Parameters
[in] aIsActive Indicates whether Dataset is active or pending.
Return values
OT_ERROR_NONE Successfully deleted the Dataset.
OT_ERROR_NOT_IMPLEMENTED The platform does not implement settings functionality.
References SettingsDriver::Delete().
SaveNetworkInfo()
otError SaveNetworkInfo (const NetworkInfo & aNetworkInfo)
This method saves Network Info.
Parameters
[in] aNetworkInfo A reference to a NetworkInfo structure to be saved.
Return values
OT_ERROR_NONE Successfully saved Network Info in settings.
OT_ERROR_NOT_IMPLEMENTED The platform does not implement settings functionality.
References ExitNow, OT_ERROR_NONE, and SuccessOrExit.
ReadNetworkInfo()
otError ReadNetworkInfo (NetworkInfo & aNetworkInfo) const
This method reads Network Info.
Parameters
[out] aNetworkInfo A reference to a NetworkInfo structure to output the read content.
Return values
OT_ERROR_NONE Successfully read the Network Info.
OT_ERROR_NOT_FOUND No corresponding value in the setting store.
OT_ERROR_NOT_IMPLEMENTED The platform does not implement settings functionality.
References SettingsBase::NetworkInfo::Init(), and SuccessOrExit.
DeleteNetworkInfo()
otError DeleteNetworkInfo (void)
This method deletes Network Info from settings.
Return values
OT_ERROR_NONE Successfully deleted the value.
OT_ERROR_NOT_IMPLEMENTED The platform does not implement settings functionality.
References SettingsDriver::Delete(), otLogInfoCore, and SuccessOrExit.
SaveParentInfo()
otError SaveParentInfo (const ParentInfo & aParentInfo)
This method saves Parent Info.
Parameters
[in] aParentInfo A reference to a ParentInfo structure to be saved.
Return values
OT_ERROR_NONE Successfully saved Parent Info in settings.
OT_ERROR_NOT_IMPLEMENTED The platform does not implement settings functionality.
References ExitNow, OT_ERROR_NONE, and SuccessOrExit.
ReadParentInfo()
otError ReadParentInfo (ParentInfo & aParentInfo) const
This method reads Parent Info.
Parameters
[out] aParentInfo A reference to a ParentInfo structure to output the read content.
Return values
OT_ERROR_NONE Successfully read the Parent Info.
OT_ERROR_NOT_FOUND No corresponding value in the setting store.
OT_ERROR_NOT_IMPLEMENTED The platform does not implement settings functionality.
References SettingsBase::ParentInfo::Init(), and SuccessOrExit.
DeleteParentInfo()
otError DeleteParentInfo (void)
This method deletes Parent Info from settings.
Return values
OT_ERROR_NONE Successfully deleted the value.
OT_ERROR_NOT_IMPLEMENTED The platform does not implement settings functionality.
References SettingsDriver::Delete(), otLogInfoCore, and SuccessOrExit.
AddChildInfo()
otError AddChildInfo (const ChildInfo & aChildInfo)
This method adds a Child Info entry to settings.
Note
Child Info is a list-based settings property and can contain multiple entries.
Parameters
[in] aChildInfo A reference to a ChildInfo structure to be saved/added.
Return values
OT_ERROR_NONE Successfully saved the Child Info in settings.
OT_ERROR_NOT_IMPLEMENTED The platform does not implement settings functionality.
References SettingsDriver::Add(), and SuccessOrExit.
DeleteChildInfo()
otError DeleteChildInfo (void)
This method deletes all Child Info entries from the settings.
Note
Child Info is a list-based settings property and can contain multiple entries.
Return values
OT_ERROR_NONE Successfully deleted the value.
OT_ERROR_NOT_IMPLEMENTED The platform does not implement settings functionality.
References SettingsDriver::Delete(), otLogInfoCore, and SuccessOrExit.
Read()
otError Read (Key aKey, void * aBuffer, uint16_t & aSize) const private
References InstanceLocator::Get().
Save()
otError Save (Key aKey, const void * aValue, uint16_t aSize) private
Add()
otError Add (Key aKey, const void * aValue, uint16_t aSize) private
Delete()
otError Delete (Key aKey) private
References Settings::ChildInfoIterator::Delete().
The documentation for this class was generated from the following files:
settings.hpp
core/common/settings.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale