OpenThread: BeaconPayload Class Reference
BeaconPayload Class Reference
Core-mac
#include <mac_frame.hpp>
Public Types
enum { kProtocolId = 3, kInfoStringSize = 92 }
enum {
kProtocolVersion = 2, kVersionOffset = 4, kVersionMask = 0xf << kVersionOffset, kNativeFlag = 1 << 3,
kJoiningFlag = 1 << 0
}
typedef String< kInfoStringSize > InfoString
Public Member Functions
void ClearJoiningPermitted (void)
void ClearNative (void)
const ExtendedPanId & GetExtendedPanId (void) const
NameData GetNetworkName (void) const
uint8_t GetProtocolId (void) const
uint8_t GetProtocolVersion (void) const
void Init (void)
bool IsJoiningPermitted (void) const
bool IsNative (void) const
bool IsValid (void) const
void SetExtendedPanId (const ExtendedPanId &aExtPanId)
void SetJoiningPermitted (void)
void SetNative (void)
void SetNetworkName (const NameData &aNameData)
InfoString ToInfoString (void) const
Private Attributes
ExtendedPanId mExtendedPanId
uint8_t mFlags
char mNetworkName [NetworkName::kMaxSize]
uint8_t mProtocolId
Detailed Description
This class implements IEEE 802.15.4 Beacon Payload generation and parsing.
Member Typedef Documentation
InfoString
typedef String<kInfoStringSize> InfoString
This type defines the fixed-length String object returned from ToInfoString() method.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
kProtocolId
Thread Protocol ID.
kInfoStringSize
Max chars for the info string (.
See also
ToInfoString()).
anonymous enum
anonymous enum
Enumerator
kProtocolVersion
Thread Protocol version.
kVersionOffset
Version field bit offset.
kVersionMask
Version field mask.
kNativeFlag
Native Commissioner flag.
kJoiningFlag
Joining Permitted flag.
Member Function Documentation
Init()
void Init (void) inline
This method initializes the Beacon Payload.
Referenced by Mac::PrepareBeacon().
IsValid()
bool IsValid (void) const inline
This method indicates whether or not the beacon appears to be a valid Thread Beacon Payload.
Return values
TRUE if the beacon appears to be a valid Thread Beacon Payload.
FALSE if the beacon does not appear to be a valid Thread Beacon Payload.
Referenced by Mac::ConvertBeaconToActiveScanResult().
GetProtocolId()
uint8_t GetProtocolId (void) const inline
This method returns the Protocol ID value.
Returns
the Protocol ID value.
GetProtocolVersion()
uint8_t GetProtocolVersion (void) const inline
This method returns the Protocol Version value.
Returns
The Protocol Version value.
Referenced by Mac::ConvertBeaconToActiveScanResult().
IsNative()
bool IsNative (void) const inline
This method indicates whether or not the Native Commissioner flag is set.
Return values
TRUE if the Native Commissioner flag is set.
FALSE if the Native Commissioner flag is not set.
Referenced by Mac::ConvertBeaconToActiveScanResult().
ClearNative()
void ClearNative (void) inline
This method clears the Native Commissioner flag.
SetNative()
void SetNative (void) inline
This method sets the Native Commissioner flag.
IsJoiningPermitted()
bool IsJoiningPermitted (void) const inline
This method indicates whether or not the Joining Permitted flag is set.
Return values
TRUE if the Joining Permitted flag is set.
FALSE if the Joining Permitted flag is not set.
Referenced by Mac::ConvertBeaconToActiveScanResult().
ClearJoiningPermitted()
void ClearJoiningPermitted (void) inline
This method clears the Joining Permitted flag.
Referenced by Mac::PrepareBeacon().
SetJoiningPermitted()
void SetJoiningPermitted (void) inline
This method sets the Joining Permitted flag.
References OPENTHREAD_CONFIG_MAC_JOIN_BEACON_VERSION.
Referenced by Mac::PrepareBeacon().
GetNetworkName()
NameData GetNetworkName (void) const inline
This method gets the Network Name field.
Returns
The Network Name field as NameData.
Referenced by Mac::ConvertBeaconToActiveScanResult().
SetNetworkName()
void SetNetworkName (const NameData & aNameData) inline
This method sets the Network Name field.
Parameters
[in] aNameData The Network Name (as a NameData).
References NameData::CopyTo().
Referenced by Mac::PrepareBeacon().
GetExtendedPanId()
const ExtendedPanId& GetExtendedPanId (void) const inline
This method returns the Extended PAN ID field.
Returns
The Extended PAN ID field.
Referenced by Mac::ConvertBeaconToActiveScanResult().
SetExtendedPanId()
void SetExtendedPanId (const ExtendedPanId & aExtPanId) inline
This method sets the Extended PAN ID field.
Parameters
[in] aExtPanId An Extended PAN ID.
Referenced by Mac::PrepareBeacon().
ToInfoString()
InfoString ToInfoString (void) const
This method returns information about the Beacon as a InfoString.
Returns
An InfoString representing the beacon payload.
Referenced by TxFrame::ProcessTransmitAesCcm(), and Mac::SetPromiscuous().
Field Documentation
mProtocolId
uint8_t mProtocolId private
mFlags
uint8_t mFlags private
mNetworkName
char mNetworkName[NetworkName::kMaxSize] private
mExtendedPanId
ExtendedPanId mExtendedPanId private
The documentation for this class was generated from the following file:
mac_frame.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale