OpenThread: Address Class Reference
Address Class Reference
Core-ipv6 » IPv6
#include <ip6_address.hpp>
Public Types
enum { kAloc16Mask = 0xfc, kRloc16ReservedBitMask = 0x02 }
enum { kInterfaceIdentifierSize = 8, kIp6AddressStringSize = 40 }
enum {
kNodeLocalScope = 0, kInterfaceLocalScope = 1, kLinkLocalScope = 2, kRealmLocalScope = 3,
kAdminLocalScope = 4, kSiteLocalScope = 5, kOrgLocalScope = 8, kGlobalScope = 14
}
typedef String< kIp6AddressStringSize > InfoString
Public Member Functions
void Clear (void)
otError FromString (const char *aBuf)
const uint8_t * GetIid (void) const
uint8_t * GetIid (void)
uint16_t GetLocator (void) const
uint8_t GetScope (void) const
bool IsIidAnycastLocator (void) const
bool IsIidAnycastServiceLocator (void) const
bool IsIidLocator (void) const
bool IsIidReserved (void) const
bool IsIidRoutingLocator (void) const
bool IsLinkLocal (void) const
bool IsLinkLocalAllNodesMulticast (void) const
bool IsLinkLocalAllRoutersMulticast (void) const
bool IsLinkLocalMulticast (void) const
bool IsLoopback (void) const
bool IsMulticast (void) const
bool IsMulticastLargerThanRealmLocal (void) const
bool IsRealmLocalAllMplForwarders (void) const
bool IsRealmLocalAllNodesMulticast (void) const
bool IsRealmLocalAllRoutersMulticast (void) const
bool IsRealmLocalMulticast (void) const
bool IsReservedSubnetAnycast (void) const
bool IsSubnetRouterAnycast (void) const
bool IsUnspecified (void) const
bool operator!= (const Address &aOther) const
bool operator== (const Address &aOther) const
uint8_t PrefixMatch (const otIp6Address &aOther) const
void SetIid (const uint8_t *aIid)
void SetIid (const Mac::ExtAddress &aExtAddress)
void SetIidToLocator (uint16_t aLocator)
void SetLocator (uint16_t aLocator)
void SetMulticastNetworkPrefix (const uint8_t *aPrefix, uint8_t aPrefixLength)
void SetMulticastNetworkPrefix (const Mle::MeshLocalPrefix &aMeshLocalPrefix)
void SetMulticastNetworkPrefix (const otIp6Prefix &aPrefix)
void SetPrefix (const uint8_t *aPrefix, uint8_t aPrefixLength)
void SetPrefix (const Mle::MeshLocalPrefix &aMeshLocalPrefix)
void SetToAnycastLocator (const Mle::MeshLocalPrefix &aMeshLocalPrefix, uint16_t aAloc16)
void SetToLinkLocalAddress (const Mac::ExtAddress &aExtAddress)
void SetToLinkLocalAddress (const uint8_t *aIid)
void SetToLinkLocalAllNodesMulticast (void)
void SetToLinkLocalAllRoutersMulticast (void)
void SetToRealmLocalAllMplForwarders (void)
void SetToRealmLocalAllNodesMulticast (void)
void SetToRealmLocalAllRoutersMulticast (void)
void SetToRoutingLocator (const Mle::MeshLocalPrefix &aMeshLocalPrefix, uint16_t aRloc16)
void ToExtAddress (Mac::ExtAddress &aExtAddress) const
void ToExtAddress (Mac::Address &aMacAddress) const
InfoString ToString (void) const
Static Public Member Functions
static uint8_t PrefixMatch (const uint8_t *aPrefixA, const uint8_t *aPrefixB, uint8_t aMaxLength)
Private Types
enum { kInterfaceIdentifierOffset = 8, kIp4AddressSize = 4, kMulticastNetworkPrefixLengthOffset = 3, kMulticastNetworkPrefixOffset = 4 }
Private Member Functions
void SetPrefix (uint8_t aOffset, const uint8_t *aPrefix, uint8_t aPrefixLength)
void SetToLocator (const Mle::MeshLocalPrefix &aMeshLocalPrefix, uint16_t aLocator)
Static Private Member Functions
static const Address & GetLinkLocalAllNodesMulticast (void)
static const Address & GetLinkLocalAllRoutersMulticast (void)
static const Address & GetRealmLocalAllMplForwarders (void)
static const Address & GetRealmLocalAllNodesMulticast (void)
static const Address & GetRealmLocalAllRoutersMulticast (void)
Additional Inherited Members
Data Fields inherited from otIp6Address
union otIp6Address::OT_TOOL_PACKED_FIELD mFields
IPv6 accessor fields.
Detailed Description
This class implements an IPv6 address object.
Member Typedef Documentation
InfoString
typedef String<kIp6AddressStringSize> InfoString
This type defines the fixed-length String object returned from ToString().
Member Enumeration Documentation
anonymous enum
anonymous enum
Masks
Enumerator
kAloc16Mask
The mask for Aloc16.
kRloc16ReservedBitMask
The mask for the reserved bit of Rloc16.
anonymous enum
anonymous enum
Constants
Enumerator
kInterfaceIdentifierSize
Interface Identifier size in bytes.
kIp6AddressStringSize
Max buffer size in bytes to store an IPv6 address in string format.
anonymous enum
anonymous enum
IPv6 Address Scopes
Enumerator
kNodeLocalScope
Node-Local scope.
kInterfaceLocalScope
Interface-Local scope.
kLinkLocalScope
Link-Local scope.
kRealmLocalScope
Realm-Local scope.
kAdminLocalScope
Admin-Local scope.
kSiteLocalScope
Site-Local scope.
kOrgLocalScope
Organization-Local scope.
kGlobalScope
Global scope.
anonymous enum
anonymous enum private
Enumerator
kInterfaceIdentifierOffset
Interface Identifier offset in bytes.
kIp4AddressSize
Size of the IPv4 address.
kMulticastNetworkPrefixLengthOffset
Prefix-Based Multicast Address (RFC3306).
kMulticastNetworkPrefixOffset
Prefix-Based Multicast Address (RFC3306).
Member Function Documentation
Clear()
void Clear (void)
This method clears the IPv6 address by setting it to the Unspecified Address "::".
References otIp6Address::OT_TOOL_PACKED_FIELD::m8, and otIp6Address::mFields.
Referenced by Address::FromString().
IsUnspecified()
bool IsUnspecified (void) const
This method indicates whether or not the IPv6 address is the Unspecified Address.
Return values
TRUE If the IPv6 address is the Unspecified Address.
FALSE If the IPv6 address is not the Unspecified Address.
References otIp6Address::OT_TOOL_PACKED_FIELD::m32, and otIp6Address::mFields.
Referenced by Child::AddIp6Address(), Lowpan::Compress(), Child::HasIp6Address(), Child::RemoveIp6Address(), Ip6::SendDatagram(), and UdpSocket::SendTo().
IsLoopback()
bool IsLoopback (void) const
This method indicates whether or not the IPv6 address is the Loopback Address.
Return values
TRUE If the IPv6 address is the Loopback Address.
FALSE If the IPv6 address is not the Loopback Address.
References ot::Encoding::BigEndian::HostSwap32(), otIp6Address::OT_TOOL_PACKED_FIELD::m32, and otIp6Address::mFields.
Referenced by Address::GetScope().
IsLinkLocal()
bool IsLinkLocal (void) const
This method indicates whether or not the IPv6 address scope is Link-Local.
Return values
TRUE If the IPv6 address scope is Link-Local.
FALSE If the IPv6 address scope is not Link-Local.
References ot::Encoding::BigEndian::HostSwap16(), otIp6Address::OT_TOOL_PACKED_FIELD::m16, and otIp6Address::mFields.
Referenced by Filter::Accept(), Netif::AddExternalUnicastAddress(), Lowpan::Compress(), Address::GetScope(), Ip6::HandleDatagram(), ThreadNetif::IsTmfMessage(), Ip6::ProcessReceiveCallback(), Ip6::ShouldForwardToThread(), and MeshForwarder::UpdateIp6Route().
SetToLinkLocalAddress() [1/2]
void SetToLinkLocalAddress (const Mac::ExtAddress & aExtAddress)
This methods sets the IPv6 address to a Link-Local address with Interface Identifier generated from a given MAC Extended Address.
Parameters
[in] aExtAddress A MAC Extended Address (used to generate the IID).
References ot::Encoding::BigEndian::HostSwap32(), otIp6Address::OT_TOOL_PACKED_FIELD::m32, otIp6Address::mFields, and Address::SetIid().
Referenced by Mle::HandleMessageTransmissionTimer(), Mle::Mle(), Mle::SendChildIdRequest(), Mle::SendChildUpdateRequest(), and Mle::SendChildUpdateResponse().
SetToLinkLocalAddress() [2/2]
void SetToLinkLocalAddress (const uint8_t * aIid)
This methods sets the IPv6 address to a Link-Local address with a given Interface Identifier.
Parameters
[in] aIid A pointer to a buffer containing the Interface Identifier.
References ot::Encoding::BigEndian::HostSwap32(), otIp6Address::OT_TOOL_PACKED_FIELD::m32, otIp6Address::mFields, and Address::SetIid().
IsMulticast()
bool IsMulticast (void) const inline
This method indicates whether or not the IPv6 address is multicast address.
Return values
TRUE If the IPv6 address is a multicast address.
FALSE If the IPv6 address scope is not a multicast address.
References Address::IsIidAnycastLocator(), Address::IsIidAnycastServiceLocator(), Address::IsIidLocator(), Address::IsIidReserved(), Address::IsIidRoutingLocator(), Address::IsLinkLocalAllNodesMulticast(), Address::IsLinkLocalAllRoutersMulticast(), Address::IsLinkLocalMulticast(), Address::IsMulticastLargerThanRealmLocal(), Address::IsRealmLocalAllMplForwarders(), Address::IsRealmLocalAllNodesMulticast(), Address::IsRealmLocalAllRoutersMulticast(), Address::IsRealmLocalMulticast(), Address::IsReservedSubnetAnycast(), Address::IsSubnetRouterAnycast(), otIp6Address::OT_TOOL_PACKED_FIELD::m8, otIp6Address::mFields, Address::SetToLinkLocalAllNodesMulticast(), Address::SetToLinkLocalAllRoutersMulticast(), Address::SetToRealmLocalAllMplForwarders(), Address::SetToRealmLocalAllNodesMulticast(), and Address::SetToRealmLocalAllRoutersMulticast().
Referenced by Lowpan::Compress(), CoapBase::FindRelatedRequest(), MeshForwarder::GetMacDestinationAddress(), Address::GetScope(), Ip6::HandleDatagram(), Icmp::HandleEchoRequest(), Mle::HandleLeaderData(), Udp::HandlePayload(), PanIdQueryServer::HandleQuery(), EnergyScanServer::HandleRequest(), AnnounceBeginServer::HandleRequest(), Ip6::InsertMplOption(), Address::IsLinkLocalMulticast(), Address::IsMulticastLargerThanRealmLocal(), Address::IsRealmLocalMulticast(), CoapBase::ProcessReceivedRequest(), CoapBase::ProcessReceivedResponse(), CoapBase::Receive(), Ip6::SendDatagram(), Ip6::SendRaw(), Ip6::ShouldForwardToThread(), Icmp::ShouldHandleEchoRequest(), and MeshForwarder::UpdateIp6Route().
IsLinkLocalMulticast()
bool IsLinkLocalMulticast (void) const
This method indicates whether or not the IPv6 address is a link-local multicast address.
Return values
TRUE If the IPv6 address is a link-local multicast address.
FALSE If the IPv6 address scope is not a link-local multicast address.
References Address::GetScope(), Address::IsMulticast(), and Address::kLinkLocalScope.
Referenced by Filter::Accept(), Address::IsMulticast(), ThreadNetif::IsTmfMessage(), Ip6::ProcessReceiveCallback(), and MeshForwarder::UpdateIp6Route().
IsLinkLocalAllNodesMulticast()
bool IsLinkLocalAllNodesMulticast (void) const
This method indicates whether or not the IPv6 address is a link-local all nodes multicast address (ff02::01).
Return values
TRUE If the IPv6 address is a link-local all nodes multicast address.
FALSE If the IPv6 address is not a link-local all nodes multicast address.
References Address::GetLinkLocalAllNodesMulticast().
Referenced by Address::IsMulticast().
SetToLinkLocalAllNodesMulticast()
void SetToLinkLocalAllNodesMulticast (void)
This method sets the IPv6 address to the link-local all nodes multicast address (ff02::01).
References Address::GetLinkLocalAllNodesMulticast().
Referenced by Address::IsMulticast(), and Mle::SendAnnounce().
IsLinkLocalAllRoutersMulticast()
bool IsLinkLocalAllRoutersMulticast (void) const
This method indicates whether or not the IPv6 address is a link-local all routers multicast address (ff02::02).
Return values
TRUE If the IPv6 address is a link-local all routers multicast address.
FALSE If the IPv6 address is not a link-local all routers multicast address.
References Address::GetLinkLocalAllRoutersMulticast().
Referenced by Address::IsMulticast().
SetToLinkLocalAllRoutersMulticast()
void SetToLinkLocalAllRoutersMulticast (void)
This method sets the IPv6 address to the link-local all routers multicast address (ff02::02).
References Address::GetLinkLocalAllRoutersMulticast().
Referenced by Mle::Discover(), Address::IsMulticast(), and Mle::SendParentRequest().
IsRealmLocalMulticast()
bool IsRealmLocalMulticast (void) const
This method indicates whether or not the IPv6 address is a realm-local multicast address.
Return values
TRUE If the IPv6 address is a realm-local multicast address.
FALSE If the IPv6 address scope is not a realm-local multicast address.
References Address::GetScope(), Address::IsMulticast(), and Address::kRealmLocalScope.
Referenced by Ip6::InsertMplOption(), Address::IsMulticast(), ThreadNetif::IsTmfMessage(), and Ip6::SendDatagram().
IsRealmLocalAllNodesMulticast()
bool IsRealmLocalAllNodesMulticast (void) const
This method indicates whether or not the IPv6 address is a realm-local all nodes multicast address (ff03::01).
Return values
TRUE If the IPv6 address is a realm-local all nodes multicast address.
FALSE If the IPv6 address is not a realm-local all nodes multicast address.
References Address::GetRealmLocalAllNodesMulticast().
Referenced by Address::IsMulticast().
SetToRealmLocalAllNodesMulticast()
void SetToRealmLocalAllNodesMulticast (void)
This method sets the IPv6 address to the realm-local all nodes multicast address (ff03::01)
References Address::GetRealmLocalAllNodesMulticast().
Referenced by Address::IsMulticast().
IsRealmLocalAllRoutersMulticast()
bool IsRealmLocalAllRoutersMulticast (void) const
This method indicates whether or not the IPv6 address is a realm-local all routers multicast address (ff03::02).
Return values
TRUE If the IPv6 address is a realm-local all routers multicast address.
FALSE If the IPv6 address is not a realm-local all routers multicast address.
References Address::GetRealmLocalAllRoutersMulticast().
Referenced by Address::IsMulticast().
SetToRealmLocalAllRoutersMulticast()
void SetToRealmLocalAllRoutersMulticast (void)
This method sets the IPv6 address to the realm-local all routers multicast address (ff03::02).
References Address::GetRealmLocalAllRoutersMulticast().
Referenced by Address::IsMulticast().
IsRealmLocalAllMplForwarders()
bool IsRealmLocalAllMplForwarders (void) const
This method indicates whether or not the IPv6 address is a realm-local all MPL forwarders address (ff03::fc).
Return values
TRUE If the IPv6 address is a realm-local all MPL forwarders address.
FALSE If the IPv6 address is not a realm-local all MPL forwarders address.
References Address::GetRealmLocalAllMplForwarders().
Referenced by Address::IsMulticast().
SetToRealmLocalAllMplForwarders()
void SetToRealmLocalAllMplForwarders (void)
This method sets the the IPv6 address to the realm-local all MPL forwarders address (ff03::fc).
References Address::GetRealmLocalAllMplForwarders().
Referenced by Ip6::AddTunneledMplOption(), and Address::IsMulticast().
IsMulticastLargerThanRealmLocal()
bool IsMulticastLargerThanRealmLocal (void) const
This method indicates whether or not the IPv6 address is multicast larger than realm local.
Return values
TRUE If the IPv6 address is multicast larger than realm local.
FALSE If the IPv6 address is not multicast or the scope is not larger than realm local.
References Address::GetScope(), Address::IsMulticast(), and Address::kRealmLocalScope.
Referenced by Mle::AppendAddressRegistration(), Ip6::HandleDatagram(), Ip6::InsertMplOption(), Address::IsMulticast(), and Ip6::SendDatagram().
IsSubnetRouterAnycast()
bool IsSubnetRouterAnycast (void) const
This method indicates whether or not the IPv6 address is Subnet-Router Anycast (RFC 4291).
Return values
TRUE If the IPv6 address is a Subnet-Router Anycast address.
FALSE If the IPv6 address is not a Subnet-Router Anycast address.
References otIp6Address::OT_TOOL_PACKED_FIELD::m32, and otIp6Address::mFields.
Referenced by Address::IsIidReserved(), and Address::IsMulticast().
IsReservedSubnetAnycast()
bool IsReservedSubnetAnycast (void) const
This method indicates whether or not the IPv6 address is Reserved Subnet Anycast (RFC 2526).
Return values
TRUE If the IPv6 address is a Reserved Subnet Anycast address.
FALSE If the IPv6 address is not a Reserved Subnet Anycast address.
References ot::Encoding::BigEndian::HostSwap32(), otIp6Address::OT_TOOL_PACKED_FIELD::m16, otIp6Address::OT_TOOL_PACKED_FIELD::m32, otIp6Address::OT_TOOL_PACKED_FIELD::m8, and otIp6Address::mFields.
Referenced by Address::IsIidReserved(), and Address::IsMulticast().
IsIidReserved()
bool IsIidReserved (void) const
This method indicates whether or not the IPv6 address contains Reserved IPv6 IID (RFC 5453).
Return values
TRUE If the IPv6 address contains a reserved IPv6 IID.
FALSE If the IPv6 address does not contain a reserved IPv6 IID.
References Address::IsIidAnycastLocator(), Address::IsReservedSubnetAnycast(), and Address::IsSubnetRouterAnycast().
Referenced by Address::IsMulticast().
IsIidLocator()
bool IsIidLocator (void) const
This method indicates whether or not the Interface Identifier (IID) of the IPv6 address matches the locator pattern (0000:00ff:fe00:xxxx).
Return values
TRUE If the IPv6 address IID matches the locator pattern
FALSE If the IPv6 address IID does not match the locator pattern
References ot::Encoding::BigEndian::HostSwap16(), ot::Encoding::BigEndian::HostSwap32(), otIp6Address::OT_TOOL_PACKED_FIELD::m16, otIp6Address::OT_TOOL_PACKED_FIELD::m32, and otIp6Address::mFields.
Referenced by Icmp::HandleEchoRequest(), Address::IsIidAnycastLocator(), Address::IsIidAnycastServiceLocator(), Address::IsIidRoutingLocator(), Address::IsMulticast(), and Ip6::ProcessReceiveCallback().
IsIidRoutingLocator()
bool IsIidRoutingLocator (void) const
This method indicates whether or not the IPv6 address's Interface Identifier (IID) matches a Routing Locator (RLOC).
In addition to checking that the IID matches the locator pattern (0000:00ff:fe00:xxxx), this method also checks that the locator value is a valid RLOC16.
Return values
TRUE If the IPv6 address's IID matches a RLOC address.
FALSE If the IPv6 address's IID does not match a RLOC address.
References Address::IsIidLocator(), Address::kAloc16Mask, Address::kRloc16ReservedBitMask, otIp6Address::OT_TOOL_PACKED_FIELD::m8, and otIp6Address::mFields.
Referenced by Address::IsMulticast(), Mle::IsRoutingLocator(), and Ip6::SelectSourceAddress().
IsIidAnycastLocator()
bool IsIidAnycastLocator (void) const
This method indicates whether or not the IPv6 address's Interface Identifier (IID) matches an Anycast Locator (ALOC).
In addition to checking that the IID matches the locator pattern (0000:00ff:fe00:xxxx), this method also checks that the locator value is any valid ALOC16 (0xfc00 - 0xfcff).
Return values
TRUE If the IPv6 address's IID matches a ALOC address.
FALSE If the IPv6 address's IID does not match a ALOC address.
References Address::IsIidLocator(), Address::kAloc16Mask, otIp6Address::OT_TOOL_PACKED_FIELD::m8, and otIp6Address::mFields.
Referenced by CoapBase::FindRelatedRequest(), Mle::IsAnycastLocator(), Address::IsIidReserved(), Address::IsMulticast(), and Ip6::SelectSourceAddress().
IsIidAnycastServiceLocator()
bool IsIidAnycastServiceLocator (void) const
This method indicates whether or not the IPv6 address's Interface Identifier (IID) matches a Service Anycast Locator (ALOC).
In addition to checking that the IID matches the locator pattern (0000:00ff:fe00:xxxx), this method also checks that the locator value is a valid Service ALOC16 (0xfc10 0xfc2f).
Return values
TRUE If the IPv6 address's IID matches a ALOC address.
FALSE If the IPv6 address's IID does not match a ALOC address.
References Address::GetLocator(), Address::IsIidLocator(), ot::Mle::kAloc16ServiceEnd, and ot::Mle::kAloc16ServiceStart.
Referenced by Address::IsMulticast(), and Ip6::ProcessReceiveCallback().
GetLocator()
uint16_t GetLocator (void) const inline
This method gets the IPv6 address locator.
Returns
RLOC16 or ALOC16.
References ot::Encoding::BigEndian::HostSwap16(), otIp6Address::OT_TOOL_PACKED_FIELD::m16, and otIp6Address::mFields.
Referenced by Lowpan::CompressDestinationIid(), Lowpan::CompressSourceIid(), MeshForwarder::GetMacDestinationAddress(), and Address::IsIidAnycastServiceLocator().
SetLocator()
void SetLocator (uint16_t aLocator) inline
This method sets the IPv6 address locator.
This method only changes the last 2 bytes of the address and keeps the rest of the address as before.
Parameters
[in] aLocator RLOC16 or ALOC16.
References ot::Encoding::BigEndian::HostSwap16(), otIp6Address::OT_TOOL_PACKED_FIELD::m16, and otIp6Address::mFields.
Referenced by Mle::CheckReachability(), Mle::GetLocatorAddress(), and Mle::SetRloc16().
SetToRoutingLocator()
void SetToRoutingLocator (const Mle::MeshLocalPrefix & aMeshLocalPrefix, uint16_t aRloc16) inline
This method sets the IPv6 address to a Routing Locator (RLOC) IPv6 address with a given Mesh-local prefix and RLOC16 value.
Parameters
[in] aMeshLocalPrefix A Mesh Local Prefix.
[in] aRloc16 A RLOC16 value.
References Address::SetToLocator().
Referenced by Mle::GetLeaderAddress().
SetToAnycastLocator()
void SetToAnycastLocator (const Mle::MeshLocalPrefix & aMeshLocalPrefix, uint16_t aAloc16) inline
This method sets the IPv6 address to a Anycast Locator (ALOC) IPv6 address with a given Mesh-local prefix and ALOC16 value.
Parameters
[in] aMeshLocalPrefix A Mesh Local Prefix.
[in] aAloc16 A ALOC16 value.
References Address::SetPrefix(), and Address::SetToLocator().
Referenced by Mle::GetServiceAloc(), and Dhcp6Server::PrefixAgent::Set().
SetPrefix() [1/3]
void SetPrefix (const uint8_t * aPrefix, uint8_t aPrefixLength)
This method sets the IPv6 address prefix.
This method only changes the first aPrefixLength bits of the address and keeps the rest of the bits in the address as before.
Parameters
[in] aPrefix A buffer containing the prefix
[in] aPrefixLength The prefix length (in bits).
Referenced by Lowpan::CopyContext(), Child::GetMeshLocalIp6Address(), Address::operator!=(), Mle::SetMeshLocalPrefix(), Address::SetMulticastNetworkPrefix(), Address::SetPrefix(), Address::SetToAnycastLocator(), and Address::SetToLocator().
SetPrefix() [2/3]
void SetPrefix (const Mle::MeshLocalPrefix & aMeshLocalPrefix) inline
This method sets the IPv6 address prefix to the given Mesh Local Prefix.
Parameters
[in] aMeshLocalPrefix A Mesh Local Prefix.
References MeshLocalPrefix::kLength, otMeshLocalPrefix::m8, Address::SetMulticastNetworkPrefix(), and Address::SetPrefix().
SetMulticastNetworkPrefix() [1/3]
void SetMulticastNetworkPrefix (const uint8_t * aPrefix, uint8_t aPrefixLength)
This method sets the prefix content of the Prefix-Based Multicast Address.
Parameters
[in] aPrefix A buffer containing the prefix.
[in] aPrefixLength The prefix length (in bits).
References Address::kMulticastNetworkPrefixLengthOffset, Address::kMulticastNetworkPrefixOffset, otIp6Address::OT_TOOL_PACKED_FIELD::m8, otIp6Address::mFields, and Address::SetPrefix().
Referenced by Mle::ApplyMeshLocalPrefix(), Address::SetMulticastNetworkPrefix(), and Address::SetPrefix().
SetMulticastNetworkPrefix() [2/3]
void SetMulticastNetworkPrefix (const Mle::MeshLocalPrefix & aMeshLocalPrefix) inline
This method sets the prefix content of Mesh Local Prefix-Based Multicast Address.
Parameters
[in] aMeshLocalPrefix A reference to the Mesh Local Prefix.
References MeshLocalPrefix::kLength, otMeshLocalPrefix::m8, and Address::SetMulticastNetworkPrefix().
SetMulticastNetworkPrefix() [3/3]
void SetMulticastNetworkPrefix (const otIp6Prefix & aPrefix) inline
This method sets the prefix content of Prefix-Based Multicast Address.
Parameters
[in] aPrefix A reference to an IPv6 Prefix.
References otIp6Address::OT_TOOL_PACKED_FIELD::m8, otIp6Address::mFields, otIp6Prefix::mLength, otIp6Prefix::mPrefix, and Address::SetMulticastNetworkPrefix().
GetIid() [1/2]
const uint8_t* GetIid (void) const inline
This method returns a pointer to the Interface Identifier.
Returns
A pointer to the Interface Identifier.
References Address::kInterfaceIdentifierOffset, otIp6Address::OT_TOOL_PACKED_FIELD::m8, and otIp6Address::mFields.
Referenced by Child::AddIp6Address(), Lowpan::CompressDestinationIid(), Lowpan::CompressSourceIid(), Child::HasIp6Address(), and Child::RemoveIp6Address().
GetIid() [2/2]
uint8_t* GetIid (void) inline
This method returns a pointer to the Interface Identifier.
Returns
A pointer to the Interface Identifier.
References Address::GetScope(), Address::kInterfaceIdentifierOffset, otIp6Address::OT_TOOL_PACKED_FIELD::m8, otIp6Address::mFields, Address::operator==(), Address::PrefixMatch(), Address::SetIid(), Address::SetIidToLocator(), and Address::ToExtAddress().
SetIid() [1/2]
void SetIid (const uint8_t * aIid)
This method sets the Interface Identifier.
Parameters
[in] aIid A reference to the Interface Identifier.
References Address::kInterfaceIdentifierOffset, Address::kInterfaceIdentifierSize, otIp6Address::OT_TOOL_PACKED_FIELD::m8, and otIp6Address::mFields.
Referenced by Lowpan::ComputeIid(), Lowpan::DecompressBaseHeader(), Address::GetIid(), Child::GetMeshLocalIp6Address(), Address::SetToLinkLocalAddress(), and Mle::UpdateLinkLocalAddress().
SetIid() [2/2]
void SetIid (const Mac::ExtAddress & aExtAddress)
This method sets the Interface Identifier.
Parameters
[in] aExtAddress A reference to the extended address.
References ExtAddress::CopyTo(), Address::kInterfaceIdentifierOffset, otIp6Address::OT_TOOL_PACKED_FIELD::m8, otIp6Address::mFields, and ExtAddress::ToggleLocal().
SetIidToLocator()
void SetIidToLocator (uint16_t aLocator)
This method sets the Interface Identifier to Routing/Anycast Locator pattern 0000:00ff:fe00:xxxx with a given locator (RLOC16 or ALOC16) value.
Parameters
[in] aLocator RLOC16 or ALOC16.
References ot::Encoding::BigEndian::HostSwap16(), ot::Encoding::BigEndian::HostSwap32(), otIp6Address::OT_TOOL_PACKED_FIELD::m16, otIp6Address::OT_TOOL_PACKED_FIELD::m32, and otIp6Address::mFields.
Referenced by Lowpan::ComputeIid(), Address::GetIid(), Mle::Mle(), and Address::SetToLocator().
ToExtAddress() [1/2]
void ToExtAddress (Mac::ExtAddress & aExtAddress) const
This method converts the IPv6 Interface Identifier to an IEEE 802.15.4 Extended Address.
Parameters
[out] aExtAddress A reference to the extended address.
References Address::kInterfaceIdentifierOffset, otIp6Address::OT_TOOL_PACKED_FIELD::m8, otIp6Address::mFields, ExtAddress::Set(), and ExtAddress::ToggleLocal().
Referenced by Address::GetIid(), MeshForwarder::GetMacDestinationAddress(), MeshForwarder::GetMacSourceAddress(), Mle::HandleDiscoveryResponse(), Mle::HandleParentResponse(), and Mle::HandleUdpReceive().
ToExtAddress() [2/2]
void ToExtAddress (Mac::Address & aMacAddress) const
This method converts the IPv6 Interface Identifier to an IEEE 802.15.4 MAC Address.
Parameters
[out] aMacAddress A reference to the MAC address.
References Address::GetExtended(), Address::kInterfaceIdentifierOffset, otIp6Address::OT_TOOL_PACKED_FIELD::m8, otIp6Address::mFields, Address::SetExtended(), and ExtAddress::ToggleLocal().
GetScope()
uint8_t GetScope (void) const
This method returns the IPv6 address scope.
Returns
The IPv6 address scope.
References Address::IsLinkLocal(), Address::IsLoopback(), Address::IsMulticast(), Address::kGlobalScope, Address::kLinkLocalScope, Address::kNodeLocalScope, otIp6Address::OT_TOOL_PACKED_FIELD::m8, and otIp6Address::mFields.
Referenced by Address::GetIid(), NetifUnicastAddress::GetScope(), Ip6::InsertMplOption(), Address::IsLinkLocalMulticast(), Address::IsMulticastLargerThanRealmLocal(), Address::IsRealmLocalMulticast(), and Ip6::SelectSourceAddress().
PrefixMatch() [1/2]
uint8_t PrefixMatch (const otIp6Address & aOther) const
This method returns the number of IPv6 prefix bits that match.
Parameters
[in] aOther The IPv6 address to match against.
Returns
The number of IPv6 prefix bits that match.
References otIp6Address::OT_TOOL_PACKED_FIELD::m8, and otIp6Address::mFields.
Referenced by Address::GetIid(), Address::operator!=(), NetworkData::PrefixMatch(), Ip6::SelectSourceAddress(), and Leader::UpdateDomainPrefixConfig().
operator==()
bool operator== (const Address & aOther) const
This method evaluates whether or not the IPv6 addresses match.
Parameters
[in] aOther The IPv6 address to compare.
Return values
TRUE If the IPv6 addresses match.
FALSE If the IPv6 addresses do not match.
References otIp6Address::OT_TOOL_PACKED_FIELD::m8, and otIp6Address::mFields.
Referenced by Address::GetIid().
operator!=()
bool operator!= (const Address & aOther) const inline
This method evaluates whether or not the IPv6 addresses differ.
Parameters
[in] aOther The IPv6 address to compare.
Return values
TRUE If the IPv6 addresses differ.
FALSE If the IPv6 addresses do not differ.
References Address::FromString(), Address::GetLinkLocalAllNodesMulticast(), Address::GetLinkLocalAllRoutersMulticast(), Address::GetRealmLocalAllMplForwarders(), Address::GetRealmLocalAllNodesMulticast(), Address::GetRealmLocalAllRoutersMulticast(), Address::PrefixMatch(), Address::SetPrefix(), Address::SetToLocator(), and Address::ToString().
FromString()
otError FromString (const char * aBuf)
This method converts an IPv6 address string to binary.
Parameters
[in] aBuf A pointer to the NULL-terminated string.
Return values
OT_ERROR_NONE Successfully parsed the IPv6 address string.
OT_ERROR_INVALID_ARGS Failed to parse the IPv6 address string.
References Address::Clear(), Address::kIp4AddressSize, otIp6Address::OT_TOOL_PACKED_FIELD::m8, otIp6Address::mFields, OT_ERROR_NONE, OT_ERROR_PARSE, and VerifyOrExit.
Referenced by Address::operator!=().
ToString()
Address::InfoString ToString (void) const
This method converts an IPv6 address object to a string
Returns
An InfoString representing the IPv6 address.
References ot::Encoding::BigEndian::HostSwap16(), otIp6Address::OT_TOOL_PACKED_FIELD::m16, and otIp6Address::mFields.
Referenced by MeshForwarder::GetFramePriority(), Ip6::HandleDatagram(), Mle::LogMleMessage(), and Address::operator!=().
PrefixMatch() [2/2]
uint8_t PrefixMatch (const uint8_t * aPrefixA, const uint8_t * aPrefixB, uint8_t aMaxLength) static
This method returns the number of IPv6 prefix bits that match.
Parameters
[in] aPrefixA A pointer to the prefix to match.
[in] aPrefixB A pointer to the prefix to match against.
[in] aMaxLength Number of bytes of the two prefixes.
Returns
The number of prefix bits that match.
SetPrefix() [3/3]
void SetPrefix (uint8_t aOffset, const uint8_t * aPrefix, uint8_t aPrefixLength) private
References otIp6Address::OT_TOOL_PACKED_FIELD::m8, otIp6Address::mFields, and OT_ASSERT.
SetToLocator()
void SetToLocator (const Mle::MeshLocalPrefix & aMeshLocalPrefix, uint16_t aLocator) private
References Address::SetIidToLocator(), and Address::SetPrefix().
Referenced by Address::operator!=(), Address::SetToAnycastLocator(), and Address::SetToRoutingLocator().
GetLinkLocalAllNodesMulticast()
const Address & GetLinkLocalAllNodesMulticast (void) static private
References Netif::kLinkLocalAllNodesMulticastAddress, and otNetifMulticastAddress::mAddress.
Referenced by Address::IsLinkLocalAllNodesMulticast(), Address::operator!=(), and Address::SetToLinkLocalAllNodesMulticast().
GetLinkLocalAllRoutersMulticast()
const Address & GetLinkLocalAllRoutersMulticast (void) static private
References Netif::kLinkLocalAllRoutersMulticastAddress, and otNetifMulticastAddress::mAddress.
Referenced by Address::IsLinkLocalAllRoutersMulticast(), Address::operator!=(), and Address::SetToLinkLocalAllRoutersMulticast().
GetRealmLocalAllNodesMulticast()
const Address & GetRealmLocalAllNodesMulticast (void) static private
References Netif::kRealmLocalAllNodesMulticastAddress, and otNetifMulticastAddress::mAddress.
Referenced by Address::IsRealmLocalAllNodesMulticast(), Address::operator!=(), and Address::SetToRealmLocalAllNodesMulticast().
GetRealmLocalAllRoutersMulticast()
const Address & GetRealmLocalAllRoutersMulticast (void) static private
References Netif::kRealmLocalAllRoutersMulticastAddress, and otNetifMulticastAddress::mAddress.
Referenced by Address::IsRealmLocalAllRoutersMulticast(), Address::operator!=(), and Address::SetToRealmLocalAllRoutersMulticast().
GetRealmLocalAllMplForwarders()
const Address & GetRealmLocalAllMplForwarders (void) static private
References Netif::kRealmLocalAllMplForwardersMulticastAddress, and otNetifMulticastAddress::mAddress.
Referenced by Address::IsRealmLocalAllMplForwarders(), Address::operator!=(), and Address::SetToRealmLocalAllMplForwarders().
The documentation for this class was generated from the following files:
ip6_address.hpp
ip6_address.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale