OpenThread: Notifier Class Reference
Notifier Class Reference
Core-notifier
#include <notifier.hpp>
Data Structures
class Callback
struct ExternalCallback
Public Member Functions
bool HasSignaled (otChangedFlags aFlags) const
bool IsPending (void) const
Notifier (Instance &aInstance)
otError RegisterCallback (otStateChangedCallback aCallback, void *aContext)
void RemoveCallback (otStateChangedCallback aCallback, void *aContext)
void Signal (otChangedFlags aFlags)
void SignalIfFirst (otChangedFlags aFlags)
template<typename Type >
otError Update (Type &aVariable, const Type &aNewValue, otChangedFlags aFlags)
Public Member Functions inherited from InstanceLocator
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Private Types
enum { kMaxExternalHandlers = OPENTHREAD_CONFIG_MAX_STATECHANGE_HANDLERS, kFlagsStringLineLimit = 70, kMaxFlagNameLength = 25, kFlagsStringBufferSize = kFlagsStringLineLimit + kMaxFlagNameLength }
Private Member Functions
const char * FlagToString (otChangedFlags aFlag) const
void HandleStateChanged (void)
void LogChangedFlags (otChangedFlags aFlags) const
void RegisterCallback (Callback &aCallback)
Static Private Member Functions
static void HandleStateChanged (Tasklet &aTasklet)
Private Attributes
LinkedList< Callback > mCallbacks
ExternalCallback mExternalCallbacks [kMaxExternalHandlers]
otChangedFlags mFlagsToSignal
otChangedFlags mSignaledFlags
Tasklet mTask
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Detailed Description
This class implements the OpenThread Notifier.
It can be used to register callbacks that notify of state or configuration changes within OpenThread.
Two callback models are provided:
A Notifier::Callback object that upon initialization (from its constructor) auto-registers itself with the Notifier. This model is mainly used by OpenThread core modules.
A otStateChangedCallback callback handler which needs to be explicitly registered with the Notifier. This is commonly used by external users (provided as an OpenThread public API). Max number of such callbacks that can be registered at the same time is specified by OPENTHREAD_CONFIG_MAX_STATECHANGE_HANDLERS configuration parameter.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
kMaxExternalHandlers
kFlagsStringLineLimit
kMaxFlagNameLength
kFlagsStringBufferSize
Constructor & Destructor Documentation
Notifier()
Notifier (Instance & aInstance) explicit
This constructor initializes a Notifier instance.
Parameters
[in] aInstance A reference to OpenThread instance.
References Notifier::kMaxExternalHandlers, Notifier::ExternalCallback::mContext, Notifier::mExternalCallbacks, and Notifier::ExternalCallback::mHandler.
Member Function Documentation
RegisterCallback() [1/2]
otError RegisterCallback (otStateChangedCallback aCallback, void * aContext)
This method registers an otStateChangedCallback handler.
Parameters
[in] aCallback A pointer to the handler function that is called to notify of the changes.
[in] aContext A pointer to arbitrary context information.
Return values
OT_ERROR_NONE Successfully registered the callback.
OT_ERROR_ALREADY The callback was already registered.
OT_ERROR_NO_BUFS Could not add the callback due to resource constraints.
References Notifier::kMaxExternalHandlers, Notifier::ExternalCallback::mContext, Notifier::mExternalCallbacks, Notifier::ExternalCallback::mHandler, OT_ERROR_ALREADY, OT_ERROR_NO_BUFS, OT_ERROR_NONE, OT_NOOP, and VerifyOrExit.
Referenced by Notifier::Callback::Callback().
RemoveCallback()
void RemoveCallback (otStateChangedCallback aCallback, void * aContext)
This method removes/unregisters a previously registered otStateChangedCallback handler.
Parameters
[in] aCallback A pointer to the callback function pointer.
[in] aContex A pointer to arbitrary context information.
References Notifier::kMaxExternalHandlers, Notifier::ExternalCallback::mContext, Notifier::mExternalCallbacks, Notifier::ExternalCallback::mHandler, OT_NOOP, and VerifyOrExit.
Signal()
void Signal (otChangedFlags aFlags)
This method schedules signaling of changed flags.
Parameters
[in] aFlags A bit-field indicating what configuration or state has changed.
References Notifier::mFlagsToSignal, Notifier::mSignaledFlags, Notifier::mTask, and Tasklet::Post().
Referenced by Notifier::SignalIfFirst(), and Notifier::Update().
SignalIfFirst()
void SignalIfFirst (otChangedFlags aFlags)
This method schedules signaling of changed flags only if the set of flags has not been signaled before (first time signal).
Parameters
[in] aFlags A bit-field indicating what configuration or state has changed.
References Notifier::HasSignaled(), and Notifier::Signal().
Referenced by Notifier::Update().
IsPending()
bool IsPending (void) const inline
This method indicates whether or not a changed callback is pending.
Returns
TRUE if a state changed callback is pending, FALSE otherwise.
References Notifier::mFlagsToSignal.
HasSignaled()
bool HasSignaled (otChangedFlags aFlags) const inline
This method indicates whether or not a changed notification for a given set of flags has been signaled before.
Parameters
[in] aFlags A bit-field containing the flag-bits to check.
Return values
TRUE All flag bits in aFlags have been signaled before.
FALSE At least one flag bit in aFlags has not been signaled before.
References Notifier::mSignaledFlags.
Referenced by Notifier::SignalIfFirst().
Update()
otError Update (Type & aVariable, const Type & aNewValue, otChangedFlags aFlags) inline
This template method updates a variable of a type Type with a new value and signals the given changed flags.
If the variable is already set to the same value, this method returns OT_ERROR_ALREADY and the changed flags is signaled using SignalIfFirst() (i.e. signal is scheduled only if the flag has not been signaled before).
The template Type should support comparison operator == and assignment operator =.
Parameters
[in,out] aVariable A reference to the variable to update.
[in] aNewValue The new value.
[in] aFlags The changed flags to signal.
Return values
OT_ERROR_NONE The variable was update successfully and aFlags was signaled.
OT_ERROR_ALREADY The variable was already set to the same value.
References OT_ERROR_ALREADY, OT_ERROR_NONE, Notifier::Signal(), and Notifier::SignalIfFirst().
RegisterCallback() [2/2]
void RegisterCallback (Callback & aCallback) private
References Notifier::mCallbacks.
HandleStateChanged() [1/2]
void HandleStateChanged (Tasklet & aTasklet) static private
References OwnerLocator::GetOwner(), and Notifier::HandleStateChanged().
HandleStateChanged() [2/2]
void HandleStateChanged (void) private
References Notifier::FlagToString(), Notifier::kFlagsStringLineLimit, Notifier::kMaxExternalHandlers, Notifier::LogChangedFlags(), Notifier::mCallbacks, Notifier::ExternalCallback::mContext, Notifier::mExternalCallbacks, Notifier::mFlagsToSignal, Notifier::ExternalCallback::mHandler, OT_CHANGED_CHANNEL_MANAGER_NEW_CHANNEL, OT_CHANGED_COMMISSIONER_STATE, OT_CHANGED_IP6_ADDRESS_ADDED, OT_CHANGED_IP6_ADDRESS_REMOVED, OT_CHANGED_IP6_MULTICAST_SUBSCRIBED, OT_CHANGED_IP6_MULTICAST_UNSUBSCRIBED, OT_CHANGED_JOINER_STATE, OT_CHANGED_MASTER_KEY, OT_CHANGED_PSKC, OT_CHANGED_SECURITY_POLICY, OT_CHANGED_SUPPORTED_CHANNEL_MASK, OT_CHANGED_THREAD_BACKBONE_ROUTER_LOCAL, OT_CHANGED_THREAD_BACKBONE_ROUTER_STATE, OT_CHANGED_THREAD_CHANNEL, OT_CHANGED_THREAD_CHILD_ADDED, OT_CHANGED_THREAD_CHILD_REMOVED, OT_CHANGED_THREAD_EXT_PANID, OT_CHANGED_THREAD_KEY_SEQUENCE_COUNTER, OT_CHANGED_THREAD_LL_ADDR, OT_CHANGED_THREAD_ML_ADDR, OT_CHANGED_THREAD_NETDATA, OT_CHANGED_THREAD_NETIF_STATE, OT_CHANGED_THREAD_NETWORK_NAME, OT_CHANGED_THREAD_PANID, OT_CHANGED_THREAD_PARTITION_ID, OT_CHANGED_THREAD_RLOC_ADDED, OT_CHANGED_THREAD_RLOC_REMOVED, OT_CHANGED_THREAD_ROLE, OT_NOOP, otLogInfoCore, and VerifyOrExit.
Referenced by Notifier::HandleStateChanged().
LogChangedFlags()
void LogChangedFlags (otChangedFlags aFlags) const private
Referenced by Notifier::HandleStateChanged().
FlagToString()
const char * FlagToString (otChangedFlags aFlag) const private
Referenced by Notifier::HandleStateChanged().
Field Documentation
mFlagsToSignal
otChangedFlags mFlagsToSignal private
Referenced by Notifier::HandleStateChanged(), Notifier::IsPending(), and Notifier::Signal().
mSignaledFlags
otChangedFlags mSignaledFlags private
Referenced by Notifier::HasSignaled(), and Notifier::Signal().
mTask
Tasklet mTask private
Referenced by Notifier::Signal().
mCallbacks
LinkedList<Callback> mCallbacks private
Referenced by Notifier::HandleStateChanged(), and Notifier::RegisterCallback().
mExternalCallbacks
ExternalCallback mExternalCallbacks[kMaxExternalHandlers] private
Referenced by Notifier::HandleStateChanged(), Notifier::Notifier(), Notifier::RegisterCallback(), and Notifier::RemoveCallback().
The documentation for this class was generated from the following files:
notifier.hpp
notifier.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale