OpenThread: OwnerLocator Class Reference
OwnerLocator Class Reference
Core-locator
#include <locator.hpp>
Public Member Functions
template<typename OwnerType >
OwnerType & GetOwner (void)
Protected Member Functions
OwnerLocator (void *aOwner)
Detailed Description
This class implements a locator for owner of an object.
This is used as the base class for objects that provide a callback (e.g., Timer or Tasklet).
Constructor & Destructor Documentation
OwnerLocator()
OwnerLocator (void * aOwner) inline explicit protected
This constructor initializes the object.
Parameters
[in] aOwner A pointer to the owner object (as void *).
References OT_UNUSED_VARIABLE.
Member Function Documentation
GetOwner()
OwnerType & GetOwner (void)
This template method returns a reference to the owner object.
The caller needs to provide the OwnerType as part of the template type.
Returns
A reference to the owner of this object.
References Instance::Get().
Referenced by Mle::CheckReachability(), Mle::HandleAttachTimer(), Mle::HandleDelayedResponseTimer(), PendingDataset::HandleDelayTimer(), MeshForwarder::HandleDiscoverTimer(), KeyManager::HandleKeyRotationTimer(), Mle::HandleMessageTransmissionTimer(), Mac::HandleOperationTask(), Ip6::HandleOptions(), DataPollSender::HandlePollTimer(), Mpl::HandleSeedSetTimer(), Ip6::HandleSendQueue(), EnergyScanServer::HandleStateChanged(), Notifier::HandleStateChanged(), Mle::HandleStateChanged(), PanIdQueryServer::HandleTimer(), EnergyScanServer::HandleTimer(), AnnounceBeginServer::HandleTimer(), AnnounceSenderBase::HandleTimer(), SubMac::HandleTimer(), ActiveDataset::HandleTimer(), PendingDataset::HandleTimer(), Mac::HandleTimer(), MeshForwarder::HandleUpdateTimer(), and MeshForwarder::ScheduleTransmissionTask().
The documentation for this class was generated from the following files:
locator.hpp
locator-getters.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale