OpenThread: ResourceRecord Class Reference
ResourceRecord Class Reference
Core-dns
#include <dns_headers.hpp>
Public Member Functions
uint16_t GetClass (void) const
uint16_t GetLength (void) const
uint32_t GetTtl (void) const
uint16_t GetType (void) const
void SetClass (uint16_t aClass)
void SetLength (uint16_t aLength)
void SetTtl (uint32_t aTtl)
void SetType (uint16_t aType)
Private Attributes
uint16_t mClass
The class of the data in RDATA section.
uint16_t mLength
The length of RDATA section in bytes.
uint32_t mTtl
Specifies the maximum time that the resource record may be cached.
uint16_t mType
The type of the data in RDATA section.
Detailed Description
This class implements Resource Record body format (RR).
Member Function Documentation
GetType()
uint16_t GetType (void) const inline
This method returns the type of the resource record.
Returns
The type of the resource record.
References ot::Encoding::BigEndian::HostSwap16().
SetType()
void SetType (uint16_t aType) inline
This method sets the type of the resource record.
Parameters
[in] aType The type of the resource record.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by ResourceRecordAaaa::Init().
GetClass()
uint16_t GetClass (void) const inline
This method returns the class of the resource record.
Returns
The class of the resource record.
References ot::Encoding::BigEndian::HostSwap16().
SetClass()
void SetClass (uint16_t aClass) inline
This method sets the class of the resource record.
Parameters
[in] aClass The class of the resource record.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by ResourceRecordAaaa::Init().
GetTtl()
uint32_t GetTtl (void) const inline
This method returns the time to live field of the resource record.
Returns
The time to live field of the resource record.
References ot::Encoding::BigEndian::HostSwap32().
SetTtl()
void SetTtl (uint32_t aTtl) inline
This method sets the time to live field of the resource record.
Parameters
[in] aTtl The time to live field of the resource record.
References ot::Encoding::BigEndian::HostSwap32().
Referenced by ResourceRecordAaaa::Init().
GetLength()
uint16_t GetLength (void) const inline
This method returns the length of the resource record.
Returns
The length of the resource record.
References ot::Encoding::BigEndian::HostSwap16().
SetLength()
void SetLength (uint16_t aLength) inline
This method sets the length of the resource record.
Parameters
[in] aLength The length of the resource record.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by ResourceRecordAaaa::Init().
Field Documentation
mType
uint16_t mType private
The type of the data in RDATA section.
mClass
uint16_t mClass private
The class of the data in RDATA section.
mTtl
uint32_t mTtl private
Specifies the maximum time that the resource record may be cached.
mLength
uint16_t mLength private
The length of RDATA section in bytes.
The documentation for this class was generated from the following file:
dns_headers.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale