OpenThread: TimerMilliScheduler Class Reference
TimerMilliScheduler Class Reference
Core-timer
#include <timer.hpp>
Public Member Functions
void Add (TimerMilli &aTimer)
void ProcessTimers (void)
void Remove (TimerMilli &aTimer)
TimerMilliScheduler (Instance &aInstance)
Public Member Functions inherited from InstanceLocator
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Static Private Attributes
static const AlarmApi sAlarmMilliApi
Additional Inherited Members
Protected Member Functions inherited from TimerScheduler
void Add (Timer &aTimer, const AlarmApi &aAlarmApi)
void ProcessTimers (const AlarmApi &aAlarmApi)
void Remove (Timer &aTimer, const AlarmApi &aAlarmApi)
void SetAlarm (const AlarmApi &aAlarmApi)
TimerScheduler (Instance &aInstance)
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Attributes inherited from TimerScheduler
LinkedList< Timer > mTimerList
Detailed Description
This class implements the millisecond timer scheduler.
Constructor & Destructor Documentation
TimerMilliScheduler()
TimerMilliScheduler (Instance & aInstance) inline explicit
This constructor initializes the object.
Parameters
[in] aInstance A reference to the instance object.
Member Function Documentation
Add()
void Add (TimerMilli & aTimer) inline
This method adds a timer instance to the timer scheduler.
Parameters
[in] aTimer A reference to the timer instance.
References TimerScheduler::Add().
Remove()
void Remove (TimerMilli & aTimer) inline
This method removes a timer instance to the timer scheduler.
Parameters
[in] aTimer A reference to the timer instance.
References TimerScheduler::Remove().
ProcessTimers()
void ProcessTimers (void) inline
This method processes the running timers.
References TimerScheduler::ProcessTimers().
Field Documentation
sAlarmMilliApi
const TimerScheduler::AlarmApi sAlarmMilliApi static private
Initial value:
= {&otPlatAlarmMilliStartAt, &otPlatAlarmMilliStop,
                                                                      &otPlatAlarmMilliGetNow}
The documentation for this class was generated from the following files:
timer.hpp
timer.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale