OpenThread: Sha256 Class Reference
Sha256 Class Reference
Core-security
#include <sha256.hpp>
Public Types
enum { kHashSize = 32 }
Public Member Functions
void Finish (uint8_t aHash[kHashSize])
Sha256 ()
void Start (void)
void Update (const uint8_t *aBuf, uint16_t aBufLength)
~Sha256 ()
Private Attributes
mbedtls_sha256_context mContext
Detailed Description
This class implements SHA-256 computation.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
kHashSize
SHA-256 hash size (bytes)
Constructor & Destructor Documentation
Sha256()
Sha256 ()
Constructor for initializing mbedtls_sha256_context.
References Sha256::mContext.
~Sha256()
~Sha256 ()
Destructor for freeing mbedtls_sha256_context.
References Sha256::mContext.
Member Function Documentation
Start()
void Start (void)
This method starts the SHA-256 computation.
References Sha256::mContext.
Referenced by ot::MeshCoP::ComputeJoinerId().
Update()
void Update (const uint8_t * aBuf, uint16_t aBufLength)
This method inputs bytes into the SHA-256 computation.
Parameters
[in] aBuf A pointer to the input buffer.
[in] aBufLength The length of aBuf in bytes.
References Sha256::mContext.
Referenced by ot::MeshCoP::ComputeJoinerId().
Finish()
void Finish (uint8_t aHash[kHashSize])
This method finalizes the hash computation.
Parameters
[out] aHash A pointer to the output buffer.
References Sha256::mContext.
Referenced by ot::MeshCoP::ComputeJoinerId().
Field Documentation
mContext
mbedtls_sha256_context mContext private
Referenced by Sha256::Finish(), Sha256::Sha256(), Sha256::Start(), Sha256::Update(), and Sha256::~Sha256().
The documentation for this class was generated from the following files:
sha256.hpp
sha256.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale