OpenThread: BufferWriter Class Reference
BufferWriter Class Reference
Core-6lowpan
#include <lowpan.hpp>
Public Member Functions
otError Advance (uint8_t aLength)
BufferWriter (uint8_t *aBuf, uint16_t aLength)
bool CanWrite (uint8_t aLength) const
uint8_t * GetWritePointer (void)
otError Write (uint8_t aByte)
otError Write (const void *aBuf, uint8_t aLength)
otError Write (const Message &aMessage, uint8_t aLength)
Private Attributes
uint8_t * mEndPointer
uint8_t * mWritePointer
Detailed Description
This class defines a buffer writer used by the 6LoWPAN compressor.
Constructor & Destructor Documentation
BufferWriter()
BufferWriter (uint8_t * aBuf, uint16_t aLength) inline
This constructor initializes the buffer writer.
Parameters
[in] aBuf A pointer to the write buffer.
[in] aLength The size of the write buffer.
Member Function Documentation
CanWrite()
bool CanWrite (uint8_t aLength) const inline
This method indicates whether there is buffer space available to write aLength bytes.
Parameters
[in] aLength Number of bytes to write.
Return values
TRUE Enough buffer space is available to write the requested number of bytes.
FALSE Insufficient buffer space to write the requested number of bytes.
GetWritePointer()
uint8_t* GetWritePointer (void) inline
This method returns the current write pointer value.
Returns
the current write pointer value.
Advance()
otError Advance (uint8_t aLength) inline
This method advances the write pointer.
Parameters
[in] aLength Number of bytes to advance.
Return values
OT_ERROR_NONE Enough buffer space is available to advance the requested number of bytes.
OT_ERROR_NO_BUFS Insufficient buffer space to advance the requested number of bytes.
References OT_ERROR_NO_BUFS, OT_ERROR_NONE, and VerifyOrExit.
Referenced by Lowpan::Compress().
Write() [1/3]
otError Write (uint8_t aByte) inline
This method writes a byte into the buffer and updates the write pointer, if space is available.
Parameters
[in] aByte Byte to write.
Return values
OT_ERROR_NONE Successfully wrote the byte and updated the pointer.
OT_ERROR_NO_BUFS Insufficient buffer space to write the byte.
References OT_ERROR_NO_BUFS, OT_ERROR_NONE, and VerifyOrExit.
Referenced by Lowpan::Compress(), Lowpan::CompressDestinationIid(), Lowpan::CompressExtensionHeader(), Lowpan::CompressMulticast(), Lowpan::CompressSourceIid(), and Lowpan::CompressUdp().
Write() [2/3]
otError Write (const void * aBuf, uint8_t aLength) inline
This method writes a byte sequence into the buffer and updates the write pointer, if space is available.
Parameters
[in] aBuf A pointer to the byte sequence.
[in] aLength Number of bytes to write.
Return values
OT_ERROR_NONE Successfully wrote the byte sequence and updated the pointer.
OT_ERROR_NO_BUFS Insufficient buffer space to write the byte sequence.
References OT_ERROR_NO_BUFS, OT_ERROR_NONE, and VerifyOrExit.
Write() [3/3]
otError Write (const Message & aMessage, uint8_t aLength) inline
This method writes a byte sequence into the buffer and updates the write pointer, if space is available.
The byte sequence is taken from a message buffer at the current message buffer's offset.
Parameters
[in] aMessage A message buffer.
[in] aLength Number of bytes to write.
Return values
OT_ERROR_NONE Successfully wrote the byte sequence and updated the pointer.
OT_ERROR_NO_BUFS Insufficient buffer space to write the byte sequence.
References Message::GetOffset(), OT_ASSERT, OT_ERROR_NO_BUFS, OT_ERROR_NONE, OT_UNUSED_VARIABLE, Message::Read(), and VerifyOrExit.
Field Documentation
mWritePointer
uint8_t* mWritePointer private
mEndPointer
uint8_t* mEndPointer private
The documentation for this class was generated from the following file:
lowpan.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale