OpenThread: SourceMatchController Class Reference
SourceMatchController Class Reference
Core-source-match-controller
#include <src_match_controller.hpp>
Public Member Functions
void DecrementMessageCount (Child &aChild)
void IncrementMessageCount (Child &aChild)
bool IsEnabled (void) const
void ResetMessageCount (Child &aChild)
void SetSrcMatchAsShort (Child &aChild, bool aUseShortAddress)
SourceMatchController (Instance &aInstance)
Public Member Functions inherited from InstanceLocator
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Private Member Functions
otError AddAddress (const Child &aChild)
void AddEntry (Child &aChild)
otError AddPendingEntries (void)
void ClearEntry (Child &aChild)
void ClearTable (void)
void Enable (bool aEnable)
Private Attributes
bool mEnabled
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Detailed Description
This class implements the "source address match" controller.
The source address match feature controls how the radio layer decides the "frame pending" bit for acks sent in response to data request commands from sleepy children.
This class updates the source match table and also controls when to enable or disable the source matching feature.
The source address match table provides the list of children for which there is a pending frame. Either a short address or an extended/long address can be added to the source address match table.
Constructor & Destructor Documentation
SourceMatchController()
SourceMatchController (Instance & aInstance) explicit
This constructor initializes the object.
Parameters
[in] aInstance A reference to the OpenThread instance
Member Function Documentation
IsEnabled()
bool IsEnabled (void) const inline
This method returns the current state of source address matching.
Returns
true if source address matching is enabled, false otherwise.
References SourceMatchController::AddAddress(), SourceMatchController::AddEntry(), SourceMatchController::AddPendingEntries(), SourceMatchController::ClearEntry(), SourceMatchController::ClearTable(), SourceMatchController::DecrementMessageCount(), SourceMatchController::Enable(), SourceMatchController::IncrementMessageCount(), SourceMatchController::mEnabled, SourceMatchController::ResetMessageCount(), and SourceMatchController::SetSrcMatchAsShort().
IncrementMessageCount()
void IncrementMessageCount (Child & aChild)
This method increments the message count for a child and updates the source match table.
Parameters
[in] aChild A reference to the child.
Referenced by SourceMatchController::IsEnabled().
DecrementMessageCount()
void DecrementMessageCount (Child & aChild)
This method decrements the message count for a child and updates the source match table.
Parameters
[in] aChild A reference to the child.
Referenced by SourceMatchController::IsEnabled().
ResetMessageCount()
void ResetMessageCount (Child & aChild)
This method resets the message count for a child to zero and updates the source match table.
Parameters
[in] aChild A reference to the child.
Referenced by SourceMatchController::IsEnabled().
SetSrcMatchAsShort()
void SetSrcMatchAsShort (Child & aChild, bool aUseShortAddress)
This method sets whether or not to perform source address matching on the extended or short address for a child.
Parameters
[in] aChild A reference to the child.
[in] aUseShortAddress true to match on short source address, false otherwise.
Referenced by SourceMatchController::IsEnabled().
ClearTable()
void ClearTable (void) private
This method clears the source match table.
Referenced by SourceMatchController::IsEnabled().
Enable()
void Enable (bool aEnable) private
This method enables or disables the source matching.
If enabled, the radio uses the source match table to determine whether to set or clear the "frame pending" bit in an acknowledgment to a MAC Data Request command. If disabled, the radio layer sets the "frame pending" on all acknowledgment frames in response to MAC Data Request commands.
Parameters
[in] aEnable true to enable, false to disable.
Referenced by SourceMatchController::IsEnabled().
AddEntry()
void AddEntry (Child & aChild) private
This method adds an entry to source match table for a given child and updates the state of source matching feature accordingly.
If the entry is added successfully, source matching feature is enabled (if not already enabled) after ensuring that there are no remaining pending entries. If the entry cannot be added (no space in source match table), the child is marked to remember the pending entry and source matching is disabled.
Parameters
[in] aChild A reference to the child.
Referenced by SourceMatchController::IsEnabled().
ClearEntry()
void ClearEntry (Child & aChild) private
This method clears an entry in source match table for a given child and updates the state of source matching feature accordingly.
If the entry is removed successfully and frees up space in the source match table, any remaining pending entries are added. If all pending entries are successfully added, source matching is enabled.
Parameters
[in] aChild A reference to the child.
Referenced by SourceMatchController::IsEnabled().
AddAddress()
otError AddAddress (const Child & aChild) private
This method adds a given child's address (short or extended address depending on child's setting) to the source source match table (
See also
SetSrcMatchAsShort.
Parameters
[in] aChild A reference to the child
Return values
OT_ERROR_NONE Child's address was added successfully to the source match table.
OT_ERROR_NO_BUFS No available space in the source match table.
Referenced by SourceMatchController::IsEnabled().
AddPendingEntries()
otError AddPendingEntries (void) private
This method adds all pending entries to the source match table.
Return values
OT_ERROR_NONE All pending entries were successfully added.
OT_ERROR_NO_BUFS No available space in the source match table.
Referenced by SourceMatchController::IsEnabled().
Field Documentation
mEnabled
bool mEnabled private
Referenced by SourceMatchController::IsEnabled().
The documentation for this class was generated from the following file:
src_match_controller.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale