OpenThread: RandomManager::Entropy Class Reference
RandomManager::Entropy Class Reference
Public Member Functions
void Deinit (void)
mbedtls_entropy_context * GetContext (void)
void Init (void)
Private Attributes
mbedtls_entropy_context mEntropyContext
Member Function Documentation
Init()
void Init (void)
Referenced by RandomManager::RandomManager().
Deinit()
void Deinit (void)
References OT_NOOP, OT_UNUSED_VARIABLE, otPlatEntropyGet(), SuccessOrExit, and VerifyOrExit.
Referenced by RandomManager::~RandomManager().
GetContext()
mbedtls_entropy_context* GetContext (void) inline
Referenced by RandomManager::GetMbedTlsEntropyContext().
Field Documentation
mEntropyContext
mbedtls_entropy_context mEntropyContext private
The documentation for this class was generated from the following files:
random_manager.hpp
random_manager.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale