OpenThread: RouteTlv Class Reference
RouteTlv Class Reference
MLE » TLVs
#include <mle_tlvs.hpp>
Public Member Functions
uint8_t GetLinkQualityIn (uint8_t aRouterIndex) const
uint8_t GetLinkQualityOut (uint8_t aRouterIndex) const
uint8_t GetRouteCost (uint8_t aRouterIndex) const
uint8_t GetRouteDataLength (void) const
const RouterIdSet & GetRouterIdMask (void) const
uint8_t GetRouterIdSequence (void) const
void Init (void)
bool IsRouterIdSet (uint8_t aRouterId) const
bool IsValid (void) const
void SetLinkQualityIn (uint8_t aRouterIndex, uint8_t aLinkQuality)
void SetLinkQualityOut (uint8_t aRouterIndex, uint8_t aLinkQuality)
void SetRouteCost (uint8_t aRouterIndex, uint8_t aRouteCost)
void SetRouteDataLength (uint8_t aLength)
void SetRouterIdMask (const RouterIdSet &aRouterIdSet)
void SetRouterIdSequence (uint8_t aSequence)
Public Member Functions inherited from Tlv
Type GetType (void) const
void SetType (Type aType)
Public Member Functions inherited from Tlv
otError AppendTo (Message &aMessage) const
uint8_t GetLength (void) const
Tlv * GetNext (void)
const Tlv * GetNext (void) const
uint32_t GetSize (void) const
uint8_t GetType (void) const
uint8_t * GetValue (void)
const uint8_t * GetValue (void) const
bool IsExtended (void) const
void SetLength (uint8_t aLength)
void SetType (uint8_t aType)
Private Types
enum {
kLinkQualityOutOffset = 6, kLinkQualityOutMask = 3 << kLinkQualityOutOffset, kLinkQualityInOffset = 4, kLinkQualityInMask = 3 << kLinkQualityInOffset,
kRouteCostOffset = 0, kRouteCostMask = 0xf << kRouteCostOffset
}
Private Attributes
uint8_t mRouteData [kMaxRouterId+1]
RouterIdSet mRouterIdMask
uint8_t mRouterIdSequence
Additional Inherited Members
Public Types inherited from Tlv
enum Type {
kSourceAddress = 0, kMode = 1, kTimeout = 2, kChallenge = 3,
kResponse = 4, kLinkFrameCounter = 5, kLinkQuality = 6, kNetworkParameter = 7,
kMleFrameCounter = 8, kRoute = 9, kAddress16 = 10, kLeaderData = 11,
kNetworkData = 12, kTlvRequest = 13, kScanMask = 14, kConnectivity = 15,
kLinkMargin = 16, kStatus = 17, kVersion = 18, kAddressRegistration = 19,
kChannel = 20, kPanId = 21, kActiveTimestamp = 22, kPendingTimestamp = 23,
kActiveDataset = 24, kPendingDataset = 25, kDiscovery = 26, kTimeRequest = 252,
kTimeParameter = 253, kXtalAccuracy = 254, kInvalid = 255
}
Public Types inherited from Tlv
enum { kBaseTlvMaxLength = OT_NETWORK_BASE_TLV_MAX_LENGTH }
Static Public Member Functions inherited from Tlv
static otError GetOffset (const Message &aMessage, Type aType, uint16_t &aOffset)
static otError GetTlv (const Message &aMessage, Type aType, uint16_t aMaxLength, Tlv &aTlv)
Static Public Member Functions inherited from Tlv
static otError AppendTlv (Message &aMessage, uint8_t aType, const uint8_t *aValue, uint8_t aLength)
static otError AppendUint16Tlv (Message &aMessage, uint8_t aType, uint16_t aValue)
static otError AppendUint32Tlv (Message &aMessage, uint8_t aType, uint32_t aValue)
static otError AppendUint8Tlv (Message &aMessage, uint8_t aType, uint8_t aValue)
static otError Get (const Message &aMessage, uint8_t aType, uint16_t aMaxSize, Tlv &aTlv)
static otError GetOffset (const Message &aMessage, uint8_t aType, uint16_t &aOffset)
static otError GetValueOffset (const Message &aMessage, uint8_t aType, uint16_t &aOffset, uint16_t &aLength)
static otError ReadTlv (const Message &aMessage, uint8_t aType, void *aValue, uint8_t aLength)
static otError ReadUint16Tlv (const Message &aMessage, uint8_t aType, uint16_t &aValue)
static otError ReadUint32Tlv (const Message &aMessage, uint8_t aType, uint32_t &aValue)
static otError ReadUint8Tlv (const Message &aMessage, uint8_t aType, uint8_t &aValue)
Protected Types inherited from Tlv
enum { kExtendedLength = 255 }
Detailed Description
This class implements Route TLV generation and parsing.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
kLinkQualityOutOffset
kLinkQualityOutMask
kLinkQualityInOffset
kLinkQualityInMask
kRouteCostOffset
kRouteCostMask
Member Function Documentation
Init()
void Init (void) inline
This method initializes the TLV.
References Tlv::kRoute, Tlv::SetLength(), and Tlv::SetType().
IsValid()
bool IsValid (void) const inline
This method indicates whether or not the TLV appears to be well-formed.
Return values
TRUE If the TLV appears to be well-formed.
FALSE If the TLV does not appear to be well-formed.
References Tlv::GetLength().
Referenced by Mle::HandleAdvertisement().
GetRouterIdSequence()
uint8_t GetRouterIdSequence (void) const inline
This method returns the Router ID Sequence value.
Returns
The Router ID Sequence value.
SetRouterIdSequence()
void SetRouterIdSequence (uint8_t aSequence) inline
This method sets the Router ID Sequence value.
Parameters
[in] aSequence The Router ID Sequence value.
GetRouterIdMask()
const RouterIdSet& GetRouterIdMask (void) const inline
This method gets the Router ID Mask.
SetRouterIdMask()
void SetRouterIdMask (const RouterIdSet & aRouterIdSet) inline
This method sets the Router ID Mask.
Parameters
[in] aRouterIdSet The Router ID Mask to set.
IsRouterIdSet()
bool IsRouterIdSet (uint8_t aRouterId) const inline
This method indicates whether or not a Router ID bit is set.
Parameters
[in] aRouterId The Router ID bit.
Return values
TRUE If the Router ID bit is set.
FALSE If the Router ID bit is not set.
GetRouteDataLength()
uint8_t GetRouteDataLength (void) const inline
This method returns the Route Data Length value.
Returns
The Route Data Length value.
References Tlv::GetLength().
SetRouteDataLength()
void SetRouteDataLength (uint8_t aLength) inline
This method sets the Route Data Length value.
Parameters
[in] aLength The Route Data Length value.
References Tlv::SetLength().
GetRouteCost()
uint8_t GetRouteCost (uint8_t aRouterIndex) const inline
This method returns the Route Cost value for a given Router index.
Parameters
[in] aRouterIndex The Router index.
Returns
The Route Cost value for a given Router index.
SetRouteCost()
void SetRouteCost (uint8_t aRouterIndex, uint8_t aRouteCost) inline
This method sets the Route Cost value for a given Router index.
Parameters
[in] aRouterIndex The Router index.
[in] aRouteCost The Route Cost value.
GetLinkQualityIn()
uint8_t GetLinkQualityIn (uint8_t aRouterIndex) const inline
This method returns the Link Quality In value for a given Router index.
Parameters
[in] aRouterIndex The Router index.
Returns
The Link Quality In value for a given Router index.
SetLinkQualityIn()
void SetLinkQualityIn (uint8_t aRouterIndex, uint8_t aLinkQuality) inline
This method sets the Link Quality In value for a given Router index.
Parameters
[in] aRouterIndex The Router index.
[in] aLinkQuality The Link Quality In value for a given Router index.
GetLinkQualityOut()
uint8_t GetLinkQualityOut (uint8_t aRouterIndex) const inline
This method returns the Link Quality Out value for a given Router index.
Parameters
[in] aRouterIndex The Router index.
Returns
The Link Quality Out value for a given Router index.
SetLinkQualityOut()
void SetLinkQualityOut (uint8_t aRouterIndex, uint8_t aLinkQuality) inline
This method sets the Link Quality Out value for a given Router index.
Parameters
[in] aRouterIndex The Router index.
[in] aLinkQuality The Link Quality Out value for a given Router index.
Field Documentation
mRouterIdSequence
uint8_t mRouterIdSequence private
mRouterIdMask
RouterIdSet mRouterIdMask private
mRouteData
uint8_t mRouteData[kMaxRouterId+1] private
The documentation for this class was generated from the following file:
mle_tlvs.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale