OpenThread: Commissioner Class Reference
Commissioner Class Reference
#include <commissioner.hpp>
Data Structures
struct Joiner
Public Types
enum JoinerOpFlag { kJoinerOpFlagDefault = 0, kJoinerOpFlagNotNotifyLeader = 1 << 0 }
Public Member Functions
otError AddJoiner (const Mac::ExtAddress *aEui64, const char *aPskd, uint32_t aTimeout)
void ApplyMeshLocalPrefix (void)
void ClearJoiners (void)
Commissioner (Instance &aInstance)
AnnounceBeginClient & GetAnnounceBeginClient (void)
EnergyScanClient & GetEnergyScanClient (void)
otError GetNextJoinerInfo (uint16_t &aIterator, otJoinerInfo &aJoiner) const
PanIdQueryClient & GetPanIdQueryClient (void)
const char * GetProvisioningUrl (void) const
uint16_t GetSessionId (void) const
otCommissionerState GetState (void) const
bool IsActive (void) const
bool IsDisabled (void) const
otError RemoveJoiner (const Mac::ExtAddress *aEui64, uint32_t aDelay, JoinerOpFlag aFlags=kJoinerOpFlagDefault)
otError SendMgmtCommissionerGetRequest (const uint8_t *aTlvs, uint8_t aLength)
otError SendMgmtCommissionerSetRequest (const otCommissioningDataset &aDataset, const uint8_t *aTlvs, uint8_t aLength)
otError SetProvisioningUrl (const char *aProvisioningUrl)
otError Start (otCommissionerStateCallback aStateCallback, otCommissionerJoinerCallback aJoinerCallback, void *aCallbackContext)
otError Stop (bool aResign)
Public Member Functions inherited from InstanceLocator
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Private Types
enum {
kPetitionAttemptDelay = 5, kPetitionRetryCount = 2, kPetitionRetryDelay = 1, kKeepAliveTimeout = 50,
kRemoveJoinerDelay = 20
}
Private Member Functions
void AddCoapResources (void)
void HandleCoapsConnected (bool aConnected)
void HandleDatasetChanged (Coap::Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
void HandleJoinerExpirationTimer (void)
void HandleJoinerFinalize (Coap::Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
void HandleLeaderKeepAliveResponse (Coap::Message *aMessage, const Ip6::MessageInfo *aMessageInfo, otError aResult)
void HandleLeaderPetitionResponse (Coap::Message *aMessage, const Ip6::MessageInfo *aMessageInfo, otError aResult)
void HandleMgmtCommissionerGetResponse (Coap::Message *aMessage, const Ip6::MessageInfo *aMessageInfo, otError aResult)
void HandleMgmtCommissionerSetResponse (Coap::Message *aMessage, const Ip6::MessageInfo *aMessageInfo, otError aResult)
void HandleRelayReceive (Coap::Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
void HandleTimer (void)
void RemoveCoapResources (void)
otError SendCommissionerSet (void)
void SendJoinFinalizeResponse (const Coap::Message &aRequest, StateTlv::State aState)
otError SendKeepAlive (void)
otError SendKeepAlive (uint16_t aSessionId)
otError SendPetition (void)
otError SendRelayTransmit (Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
void SetState (otCommissionerState aState)
void SignalJoinerEvent (otCommissionerJoinerEvent aEvent, const Mac::ExtAddress &aJoinerId)
void UpdateJoinerExpirationTimer (void)
Static Private Member Functions
static void HandleCoapsConnected (bool aConnected, void *aContext)
static void HandleDatasetChanged (void *aContext, otMessage *aMessage, const otMessageInfo *aMessageInfo)
static void HandleJoinerExpirationTimer (Timer &aTimer)
static void HandleJoinerFinalize (void *aContext, otMessage *aMessage, const otMessageInfo *aMessageInfo)
static void HandleLeaderKeepAliveResponse (void *aContext, otMessage *aMessage, const otMessageInfo *aMessageInfo, otError aResult)
static void HandleLeaderPetitionResponse (void *aContext, otMessage *aMessage, const otMessageInfo *aMessageInfo, otError aResult)
static void HandleMgmtCommissionerGetResponse (void *aContext, otMessage *aMessage, const otMessageInfo *aMessageInfo, otError aResult)
static void HandleMgmtCommissionerSetResponse (void *aContext, otMessage *aMessage, const otMessageInfo *aMessageInfo, otError aResult)
static void HandleRelayReceive (void *aContext, otMessage *aMessage, const otMessageInfo *aMessageInfo)
static void HandleTimer (Timer &aTimer)
static otError SendRelayTransmit (void *aContext, Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
static const char * StateToString (otCommissionerState aState)
Private Attributes
AnnounceBeginClient mAnnounceBegin
void * mCallbackContext
Ip6::NetifUnicastAddress mCommissionerAloc
Coap::Resource mDatasetChanged
EnergyScanClient mEnergyScan
otCommissionerJoinerCallback mJoinerCallback
TimerMilli mJoinerExpirationTimer
Coap::Resource mJoinerFinalize
uint8_t mJoinerIid [Ip6::Address::kInterfaceIdentifierSize]
uint8_t mJoinerIndex
uint16_t mJoinerPort
uint16_t mJoinerRloc
Joiner mJoiners [OPENTHREAD_CONFIG_COMMISSIONER_MAX_JOINER_ENTRIES]
PanIdQueryClient mPanIdQuery
char mProvisioningUrl [OT_PROVISIONING_URL_MAX_SIZE+1]
Coap::Resource mRelayReceive
uint16_t mSessionId
otCommissionerState mState
otCommissionerStateCallback mStateCallback
TimerMilli mTimer
uint8_t mTransmitAttempts
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Member Enumeration Documentation
JoinerOpFlag
enum JoinerOpFlag
Joiner operation flags.
Enumerator
kJoinerOpFlagDefault
The default flags.
kJoinerOpFlagNotNotifyLeader
Do not notify Leader.
anonymous enum
anonymous enum private
Enumerator
kPetitionAttemptDelay
COMM_PET_ATTEMPT_DELAY (seconds)
kPetitionRetryCount
COMM_PET_RETRY_COUNT.
kPetitionRetryDelay
COMM_PET_RETRY_DELAY (seconds)
kKeepAliveTimeout
TIMEOUT_COMM_PET (seconds)
kRemoveJoinerDelay
Delay to remove successfully joined joiner.
Constructor & Destructor Documentation
Commissioner()
Commissioner (Instance & aInstance) explicit
This constructor initializes the Commissioner object.
Parameters
[in] aInstance A reference to the OpenThread instance.
Member Function Documentation
Start()
otError Start (otCommissionerStateCallback aStateCallback, otCommissionerJoinerCallback aJoinerCallback, void * aCallbackContext)
This method starts the Commissioner service.
Parameters
[in] aStateCallback A pointer to a function that is called when the commissioner state changes.
[in] aJoinerCallback A pointer to a function that is called when a joiner event occurs.
[in] aCallbackContext A pointer to application-specific context.
Return values
OT_ERROR_NONE Successfully started the Commissioner service.
OT_ERROR_ALREADY Commissioner is already started.
OT_ERROR_INVALID_STATE Device is not currently attached to a network.
Stop()
otError Stop (bool aResign)
This method stops the Commissioner service.
Parameters
[in] aResign Whether send LEAD_KA.req to resign as Commissioner
Return values
OT_ERROR_NONE Successfully stopped the Commissioner service.
OT_ERROR_ALREADY Commissioner is already stopped.
ClearJoiners()
void ClearJoiners (void)
This method clears all Joiner entries.
AddJoiner()
otError AddJoiner (const Mac::ExtAddress * aEui64, const char * aPskd, uint32_t aTimeout)
This method adds a Joiner entry.
Parameters
[in] aEui64 A pointer to the Joiner's IEEE EUI-64 or NULL for any Joiner.
[in] aPskd A pointer to the PSKd.
[in] aTimeout A time after which a Joiner is automatically removed, in seconds.
Return values
OT_ERROR_NONE Successfully added the Joiner.
OT_ERROR_NO_BUFS No buffers available to add the Joiner.
OT_ERROR_INVALID_STATE Commissioner service is not started.
GetNextJoinerInfo()
otError GetNextJoinerInfo (uint16_t & aIterator, otJoinerInfo & aJoiner) const
This method get joiner info at aIterator position.
Parameters
[in,out] aIterator A iterator to the index of the joiner.
[out] aJoiner A reference to Joiner info.
Return values
OT_ERROR_NONE Successfully get the Joiner info.
OT_ERROR_NOT_FOUND Not found next Joiner.
RemoveJoiner()
otError RemoveJoiner (const Mac::ExtAddress * aEui64, uint32_t aDelay, JoinerOpFlag aFlags = kJoinerOpFlagDefault)
This method removes a Joiner entry.
Parameters
[in] aEui64 A pointer to the Joiner's IEEE EUI-64 or NULL for any Joiner.
[in] aDelay The delay to remove Joiner (in seconds).
[in] aFlags The flags for removing the Joiner.
Return values
OT_ERROR_NONE Successfully added the Joiner.
OT_ERROR_NOT_FOUND The Joiner specified by aEui64 was not found.
OT_ERROR_INVALID_STATE Commissioner service is not started.
See also
JoinerOpFlag
GetProvisioningUrl()
const char* GetProvisioningUrl (void) const inline
This method gets the Provisioning URL.
Returns
A pointer to char buffer containing the URL string.
References Commissioner::mProvisioningUrl, and Commissioner::SetProvisioningUrl().
SetProvisioningUrl()
otError SetProvisioningUrl (const char * aProvisioningUrl)
This method sets the Provisioning URL.
Parameters
[in] aProvisioningUrl A pointer to the Provisioning URL (may be NULL to set URL to empty string).
Return values
OT_ERROR_NONE Successfully set the Provisioning URL.
OT_ERROR_INVALID_ARGS aProvisioningUrl is invalid (too long).
Referenced by Commissioner::GetProvisioningUrl().
GetSessionId()
uint16_t GetSessionId (void) const inline
This method returns the Commissioner Session ID.
Returns
The Commissioner Session ID.
References Commissioner::mSessionId.
IsActive()
bool IsActive (void) const inline
This method indicates whether or not the Commissioner role is active.
Returns
TRUE if the Commissioner role is active, FALSE otherwise.
References Commissioner::mState, and OT_COMMISSIONER_STATE_ACTIVE.
IsDisabled()
bool IsDisabled (void) const inline
This method indicates whether or not the Commissioner role is disabled.
Returns
TRUE if the Commissioner role is disabled, FALSE otherwise.
References Commissioner::mState, and OT_COMMISSIONER_STATE_DISABLED.
GetState()
otCommissionerState GetState (void) const inline
This function returns the Commissioner State.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Return values
OT_COMMISSIONER_STATE_DISABLED Commissioner disabled.
OT_COMMISSIONER_STATE_PETITION Becoming the commissioner.
OT_COMMISSIONER_STATE_ACTIVE Commissioner enabled.
References Commissioner::mState, Commissioner::SendMgmtCommissionerGetRequest(), and Commissioner::SendMgmtCommissionerSetRequest().
SendMgmtCommissionerGetRequest()
otError SendMgmtCommissionerGetRequest (const uint8_t * aTlvs, uint8_t aLength)
This method sends MGMT_COMMISSIONER_GET.
Parameters
[in] aTlvs A pointer to Commissioning Data TLVs.
[in] aLength The length of requested TLVs in bytes.
Return values
OT_ERROR_NONE Send MGMT_COMMISSIONER_GET successfully.
OT_ERROR_NO_BUFS Insufficient buffer space to send.
OT_ERROR_INVALID_STATE Commissioner service is not started.
Referenced by Commissioner::GetState().
SendMgmtCommissionerSetRequest()
otError SendMgmtCommissionerSetRequest (const otCommissioningDataset & aDataset, const uint8_t * aTlvs, uint8_t aLength)
This method sends MGMT_COMMISSIONER_SET.
Parameters
[in] aDataset A reference to Commissioning Data.
[in] aTlvs A pointer to user specific Commissioning Data TLVs.
[in] aLength The length of user specific TLVs in bytes.
Return values
OT_ERROR_NONE Send MGMT_COMMISSIONER_SET successfully.
OT_ERROR_NO_BUFS Insufficient buffer space to send.
OT_ERROR_INVALID_STATE Commissioner service is not started.
Referenced by Commissioner::GetState().
GetAnnounceBeginClient()
AnnounceBeginClient& GetAnnounceBeginClient (void) inline
This method returns a reference to the AnnounceBeginClient instance.
Returns
A reference to the AnnounceBeginClient instance.
References Commissioner::mAnnounceBegin.
GetEnergyScanClient()
EnergyScanClient& GetEnergyScanClient (void) inline
This method returns a reference to the EnergyScanClient instance.
Returns
A reference to the EnergyScanClient instance.
References Commissioner::mEnergyScan.
GetPanIdQueryClient()
PanIdQueryClient& GetPanIdQueryClient (void) inline
This method returns a reference to the PanIdQueryClient instance.
Returns
A reference to the PanIdQueryClient instance.
References Commissioner::ApplyMeshLocalPrefix(), and Commissioner::mPanIdQuery.
ApplyMeshLocalPrefix()
void ApplyMeshLocalPrefix (void)
This method applies the Mesh Local Prefix.
Referenced by Commissioner::GetPanIdQueryClient().
AddCoapResources()
void AddCoapResources (void) private
RemoveCoapResources()
void RemoveCoapResources (void) private
HandleTimer() [1/2]
static void HandleTimer (Timer & aTimer) static private
HandleTimer() [2/2]
void HandleTimer (void) private
HandleJoinerExpirationTimer() [1/2]
static void HandleJoinerExpirationTimer (Timer & aTimer) static private
HandleJoinerExpirationTimer() [2/2]
void HandleJoinerExpirationTimer (void) private
UpdateJoinerExpirationTimer()
void UpdateJoinerExpirationTimer (void) private
HandleMgmtCommissionerSetResponse() [1/2]
static void HandleMgmtCommissionerSetResponse (void * aContext, otMessage * aMessage, const otMessageInfo * aMessageInfo, otError aResult) static private
HandleMgmtCommissionerSetResponse() [2/2]
void HandleMgmtCommissionerSetResponse (Coap::Message * aMessage, const Ip6::MessageInfo * aMessageInfo, otError aResult) private
HandleMgmtCommissionerGetResponse() [1/2]
static void HandleMgmtCommissionerGetResponse (void * aContext, otMessage * aMessage, const otMessageInfo * aMessageInfo, otError aResult) static private
HandleMgmtCommissionerGetResponse() [2/2]
void HandleMgmtCommissionerGetResponse (Coap::Message * aMessage, const Ip6::MessageInfo * aMessageInfo, otError aResult) private
HandleLeaderPetitionResponse() [1/2]
static void HandleLeaderPetitionResponse (void * aContext, otMessage * aMessage, const otMessageInfo * aMessageInfo, otError aResult) static private
HandleLeaderPetitionResponse() [2/2]
void HandleLeaderPetitionResponse (Coap::Message * aMessage, const Ip6::MessageInfo * aMessageInfo, otError aResult) private
HandleLeaderKeepAliveResponse() [1/2]
static void HandleLeaderKeepAliveResponse (void * aContext, otMessage * aMessage, const otMessageInfo * aMessageInfo, otError aResult) static private
HandleLeaderKeepAliveResponse() [2/2]
void HandleLeaderKeepAliveResponse (Coap::Message * aMessage, const Ip6::MessageInfo * aMessageInfo, otError aResult) private
HandleCoapsConnected() [1/2]
static void HandleCoapsConnected (bool aConnected, void * aContext) static private
HandleCoapsConnected() [2/2]
void HandleCoapsConnected (bool aConnected) private
HandleRelayReceive() [1/2]
static void HandleRelayReceive (void * aContext, otMessage * aMessage, const otMessageInfo * aMessageInfo) static private
HandleRelayReceive() [2/2]
void HandleRelayReceive (Coap::Message & aMessage, const Ip6::MessageInfo & aMessageInfo) private
HandleDatasetChanged() [1/2]
static void HandleDatasetChanged (void * aContext, otMessage * aMessage, const otMessageInfo * aMessageInfo) static private
HandleDatasetChanged() [2/2]
void HandleDatasetChanged (Coap::Message & aMessage, const Ip6::MessageInfo & aMessageInfo) private
HandleJoinerFinalize() [1/2]
static void HandleJoinerFinalize (void * aContext, otMessage * aMessage, const otMessageInfo * aMessageInfo) static private
HandleJoinerFinalize() [2/2]
void HandleJoinerFinalize (Coap::Message & aMessage, const Ip6::MessageInfo & aMessageInfo) private
SendJoinFinalizeResponse()
void SendJoinFinalizeResponse (const Coap::Message & aRequest, StateTlv::State aState) private
SendRelayTransmit() [1/2]
static otError SendRelayTransmit (void * aContext, Message & aMessage, const Ip6::MessageInfo & aMessageInfo) static private
SendRelayTransmit() [2/2]
otError SendRelayTransmit (Message & aMessage, const Ip6::MessageInfo & aMessageInfo) private
SendCommissionerSet()
otError SendCommissionerSet (void) private
SendPetition()
otError SendPetition (void) private
SendKeepAlive() [1/2]
otError SendKeepAlive (void) private
SendKeepAlive() [2/2]
otError SendKeepAlive (uint16_t aSessionId) private
SetState()
void SetState (otCommissionerState aState) private
SignalJoinerEvent()
void SignalJoinerEvent (otCommissionerJoinerEvent aEvent, const Mac::ExtAddress & aJoinerId) private
StateToString()
static const char* StateToString (otCommissionerState aState) static private
Field Documentation
mJoiners
Joiner mJoiners[OPENTHREAD_CONFIG_COMMISSIONER_MAX_JOINER_ENTRIES] private
mJoinerIid
uint8_t mJoinerIid[Ip6::Address::kInterfaceIdentifierSize] private
mJoinerPort
uint16_t mJoinerPort private
mJoinerRloc
uint16_t mJoinerRloc private
mSessionId
uint16_t mSessionId private
Referenced by Commissioner::GetSessionId().
mJoinerIndex
uint8_t mJoinerIndex private
mTransmitAttempts
uint8_t mTransmitAttempts private
mJoinerExpirationTimer
TimerMilli mJoinerExpirationTimer private
mTimer
TimerMilli mTimer private
mRelayReceive
Coap::Resource mRelayReceive private
mDatasetChanged
Coap::Resource mDatasetChanged private
mJoinerFinalize
Coap::Resource mJoinerFinalize private
mAnnounceBegin
AnnounceBeginClient mAnnounceBegin private
Referenced by Commissioner::GetAnnounceBeginClient().
mEnergyScan
EnergyScanClient mEnergyScan private
Referenced by Commissioner::GetEnergyScanClient().
mPanIdQuery
PanIdQueryClient mPanIdQuery private
Referenced by Commissioner::GetPanIdQueryClient().
mCommissionerAloc
Ip6::NetifUnicastAddress mCommissionerAloc private
mProvisioningUrl
char mProvisioningUrl[OT_PROVISIONING_URL_MAX_SIZE+1] private
Referenced by Commissioner::GetProvisioningUrl().
mStateCallback
otCommissionerStateCallback mStateCallback private
mJoinerCallback
otCommissionerJoinerCallback mJoinerCallback private
mCallbackContext
void* mCallbackContext private
mState
otCommissionerState mState private
Referenced by Commissioner::GetState(), Commissioner::IsActive(), and Commissioner::IsDisabled().
The documentation for this class was generated from the following file:
commissioner.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale