OpenThread: ExtendedPanId Class Reference
ExtendedPanId Class Reference
Core-mac
#include <mac_types.hpp>
Public Types
enum { kInfoStringSize = 17 }
typedef String< kInfoStringSize > InfoString
Public Member Functions
void Clear (void)
bool operator!= (const ExtendedPanId &aOther) const
bool operator== (const ExtendedPanId &aOther) const
InfoString ToString (void) const
Additional Inherited Members
Data Fields inherited from otExtendedPanId
uint8_t m8 [OT_EXT_PAN_ID_SIZE]
Byte values.
Detailed Description
This structure represents an IEEE 802.15.4 Extended PAN Identifier.
Member Typedef Documentation
InfoString
typedef String<kInfoStringSize> InfoString
This type defines the fixed-length String object returned from ToString().
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
kInfoStringSize
Member Function Documentation
Clear()
void Clear (void) inline
This method clears the Extended PAN Identifier (sets all bytes to zero).
References ExtAddress::operator==().
Referenced by Mac::Mac().
operator==()
bool operator== (const ExtendedPanId & aOther) const
This method evaluates whether or not the Extended PAN Identifiers match.
Parameters
[in] aOther The Extended PAN Id to compare.
Return values
TRUE If the Extended PAN Identifiers match.
FALSE If the Extended PAN Identifiers do not match.
References otExtendedPanId::m8, and otExtAddress::m8.
operator!=()
bool operator!= (const ExtendedPanId & aOther) const inline
This method evaluates whether or not the Extended PAN Identifiers match.
Parameters
[in] aOther The Extended PAN Id to compare.
Return values
TRUE If the Extended Addresses do not match.
FALSE If the Extended Addresses match.
References ot::Mac::OT_TOOL_PACKED_END, and ExtAddress::ToString().
ToString()
ExtendedPanId::InfoString ToString (void) const
This method converts an address to a string.
Returns
An InfoString containing the string representation of the Extended PAN Identifier.
References otExtAddress::m8.
The documentation for this class was generated from the following files:
mac_types.hpp
mac_types.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale