OpenThread: SettingsBase::ChildInfo Class Reference
SettingsBase::ChildInfo Class Reference
#include <settings.hpp>
Public Member Functions
const Mac::ExtAddress & GetExtAddress (void) const
uint8_t GetMode (void) const
uint16_t GetRloc16 (void) const
uint32_t GetTimeout (void) const
uint16_t GetVersion (void) const
void Init (void)
void SetExtAddress (const Mac::ExtAddress &aExtAddress)
void SetMode (uint8_t aMode)
void SetRloc16 (uint16_t aRloc16)
void SetTimeout (uint32_t aTimeout)
void SetVersion (uint16_t aVersion)
Private Attributes
Mac::ExtAddress mExtAddress
Extended Address.
uint8_t mMode
The MLE device mode.
uint16_t mRloc16
RLOC16.
uint32_t mTimeout
Timeout.
uint16_t mVersion
Version.
Detailed Description
This structure represents the child information for settings storage.
Member Function Documentation
Init()
void Init (void) inline
This method clears the struct object (setting all the fields to zero).
References OT_THREAD_VERSION_1_1.
Referenced by Settings::ChildInfoIterator::Read().
GetExtAddress()
const Mac::ExtAddress& GetExtAddress (void) const inline
This method returns the extended address.
Returns
The extended address.
SetExtAddress()
void SetExtAddress (const Mac::ExtAddress & aExtAddress) inline
This method sets the extended address.
Parameters
[in] aExtAddress The extended address.
GetTimeout()
uint32_t GetTimeout (void) const inline
This method returns the child timeout.
Returns
The child timeout.
References ot::Encoding::LittleEndian::HostSwap32().
SetTimeout()
void SetTimeout (uint32_t aTimeout) inline
This method sets the child timeout.
Parameters
[in] aTimeout The child timeout.
References ot::Encoding::LittleEndian::HostSwap32().
GetRloc16()
uint16_t GetRloc16 (void) const inline
This method returns the RLOC16.
Returns
The RLOC16.
References ot::Encoding::LittleEndian::HostSwap16().
SetRloc16()
void SetRloc16 (uint16_t aRloc16) inline
This method sets the RLOC16.
Parameters
[in] aRloc16 The RLOC16.
References ot::Encoding::LittleEndian::HostSwap16().
GetMode()
uint8_t GetMode (void) const inline
This method returns the Thread device mode.
Returns
The Thread device mode.
SetMode()
void SetMode (uint8_t aMode) inline
This method sets the Thread device mode.
Parameters
[in] aRloc16 The Thread device mode.
GetVersion()
uint16_t GetVersion (void) const inline
This method returns the Thread version.
Returns
The Thread version.
References ot::Encoding::LittleEndian::HostSwap16().
SetVersion()
void SetVersion (uint16_t aVersion) inline
This method sets the Thread version.
Parameters
[in] aVersion The Thread version.
References ot::Encoding::LittleEndian::HostSwap16().
Field Documentation
mExtAddress
Mac::ExtAddress mExtAddress private
Extended Address.
mTimeout
uint32_t mTimeout private
Timeout.
mRloc16
uint16_t mRloc16 private
RLOC16.
mMode
uint8_t mMode private
The MLE device mode.
mVersion
uint16_t mVersion private
Version.
The documentation for this class was generated from the following file:
settings.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale