OpenThread: IcmpHeader Class Reference
IcmpHeader Class Reference
Core-ipv6 » ICMPv6
#include <icmp6.hpp>
Public Types
enum Code { kCodeDstUnreachNoRoute = OT_ICMP6_CODE_DST_UNREACH_NO_ROUTE, kCodeFragmReasTimeEx = OT_ICMP6_CODE_FRAGM_REAS_TIME_EX }
enum Type {
kTypeDstUnreach = OT_ICMP6_TYPE_DST_UNREACH, kTypePacketToBig = OT_ICMP6_TYPE_PACKET_TO_BIG, kTypeTimeExceeded = OT_ICMP6_TYPE_TIME_EXCEEDED, kTypeEchoRequest = OT_ICMP6_TYPE_ECHO_REQUEST,
kTypeEchoReply = OT_ICMP6_TYPE_ECHO_REPLY
}
Public Member Functions
uint16_t GetChecksum (void) const
Code GetCode (void) const
uint16_t GetId (void) const
uint16_t GetSequence (void) const
Type GetType (void) const
void Init (void)
bool IsError (void) const
void SetChecksum (uint16_t aChecksum)
void SetCode (Code aCode)
void SetId (uint16_t aId)
void SetSequence (uint16_t aSequence)
void SetType (Type aType)
Static Public Member Functions
static uint8_t GetChecksumOffset (void)
static uint8_t GetDataOffset (void)
Additional Inherited Members
Data Fields inherited from otIcmp6Header
uint16_t mChecksum
Checksum.
uint8_t mCode
Code.
union otIcmp6Header::OT_TOOL_PACKED_FIELD mData
Message-specific data.
uint8_t mType
Type.
Member Enumeration Documentation
Type
enum Type
ICMPv6 Message Types
Enumerator
kTypeDstUnreach
Destination Unreachable.
kTypePacketToBig
Packet To Big.
kTypeTimeExceeded
Time Exceeded.
kTypeEchoRequest
Echo Request.
kTypeEchoReply
Echo Reply.
Code
enum Code
ICMPv6 Message Codes
Enumerator
kCodeDstUnreachNoRoute
Destination Unreachable No Route.
kCodeFragmReasTimeEx
Fragment Reassembly Time Exceeded.
Member Function Documentation
Init()
void Init (void) inline
This method initializes the ICMPv6 header to all zeros.
References otIcmp6Header::OT_TOOL_PACKED_FIELD::m32, otIcmp6Header::mChecksum, otIcmp6Header::mCode, otIcmp6Header::mData, and otIcmp6Header::mType.
Referenced by Icmp::HandleEchoRequest(), Icmp::SendEchoRequest(), and Icmp::SendError().
IsError()
bool IsError (void) const inline
This method indicates whether the ICMPv6 message is an error message.
Return values
TRUE if the ICMPv6 message is an error message.
FALSE if the ICMPv6 message is an informational message.
References otIcmp6Header::mType, and OT_ICMP6_TYPE_ECHO_REQUEST.
Referenced by Icmp::SendError().
GetType()
Type GetType (void) const inline
This method returns the ICMPv6 message type.
Returns
The ICMPv6 message type.
References otIcmp6Header::mType.
Referenced by Icmp::HandleMessage(), and Ip6::ProcessReceiveCallback().
SetType()
void SetType (Type aType) inline
This method sets the ICMPv6 message type.
Parameters
[in] aType The ICMPv6 message type.
References otIcmp6Header::mType.
Referenced by Icmp::HandleEchoRequest(), Icmp::SendEchoRequest(), and Icmp::SendError().
GetCode()
Code GetCode (void) const inline
This method returns the ICMPv6 message code.
Returns
The ICMPv6 message code.
References otIcmp6Header::mCode.
SetCode()
void SetCode (Code aCode) inline
This method sets the ICMPv6 message code.
Parameters
[in] aCode The ICMPv6 message code.
References otIcmp6Header::mCode.
Referenced by Icmp::SendError().
GetChecksum()
uint16_t GetChecksum (void) const inline
This method returns the ICMPv6 message checksum.
Returns
The ICMPv6 message checksum.
References ot::Encoding::BigEndian::HostSwap16(), and otIcmp6Header::mChecksum.
SetChecksum()
void SetChecksum (uint16_t aChecksum) inline
This method sets the ICMPv6 message checksum.
Parameters
[in] aChecksum The ICMPv6 message checksum.
References ot::Encoding::BigEndian::HostSwap16(), and otIcmp6Header::mChecksum.
GetId()
uint16_t GetId (void) const inline
This method returns the ICMPv6 message ID for Echo Requests and Replies.
Returns
The ICMPv6 message ID.
References ot::Encoding::BigEndian::HostSwap16(), otIcmp6Header::OT_TOOL_PACKED_FIELD::m16, and otIcmp6Header::mData.
SetId()
void SetId (uint16_t aId) inline
This method sets the ICMPv6 message ID for Echo Requests and Replies.
Parameters
[in] aId The ICMPv6 message ID.
References ot::Encoding::BigEndian::HostSwap16(), otIcmp6Header::OT_TOOL_PACKED_FIELD::m16, and otIcmp6Header::mData.
Referenced by Icmp::SendEchoRequest().
GetSequence()
uint16_t GetSequence (void) const inline
This method returns the ICMPv6 message sequence for Echo Requests and Replies.
Returns
The ICMPv6 message sequence.
References ot::Encoding::BigEndian::HostSwap16(), otIcmp6Header::OT_TOOL_PACKED_FIELD::m16, and otIcmp6Header::mData.
Referenced by Icmp::HandleEchoRequest(), and Icmp::SendEchoRequest().
SetSequence()
void SetSequence (uint16_t aSequence) inline
This method sets the ICMPv6 message sequence for Echo Requests and Replies.
Parameters
[in] aSequence The ICMPv6 message sequence.
References ot::Encoding::BigEndian::HostSwap16(), otIcmp6Header::OT_TOOL_PACKED_FIELD::m16, and otIcmp6Header::mData.
Referenced by Icmp::SendEchoRequest().
GetChecksumOffset()
static uint8_t GetChecksumOffset (void) inline static
This static method returns the byte offset of the Checksum field in the ICMPv6 header.
Returns
The byte offset of the Checksum field.
References otIcmp6Header::mChecksum.
Referenced by Icmp::UpdateChecksum().
GetDataOffset()
static uint8_t GetDataOffset (void) inline static
This static method returns the byte offset of the ICMPv6 payload.
Returns
The Byte offset of the ICMPv6 payload.
References otIcmp6Header::mData, and ot::Ip6::OT_TOOL_PACKED_END.
Referenced by Icmp::HandleEchoRequest().
The documentation for this class was generated from the following file:
icmp6.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale