OpenThread: Settings::ChildInfoIterator Class Reference
Settings::ChildInfoIterator Class Reference
#include <settings.hpp>
Public Member Functions
void Advance (void)
ChildInfoIterator (Instance &aInstance)
otError Delete (void)
const ChildInfo & GetChildInfo (void) const
bool IsDone (void) const
void operator++ (void)
void operator++ (int)
void Reset (void)
Public Member Functions inherited from InstanceLocator
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Private Member Functions
void Read (void)
Private Attributes
ChildInfo mChildInfo
uint16_t mIndex
bool mIsDone
Additional Inherited Members
Public Types inherited from SettingsBase
enum Key {
kKeyActiveDataset = 0x0001, kKeyPendingDataset = 0x0002, kKeyNetworkInfo = 0x0003, kKeyParentInfo = 0x0004,
kKeyChildInfo = 0x0005, kKeyReserved = 0x0006, kKeySlaacIidSecretKey = 0x0007
}
Data Fields inherited from SettingsBase
OT_TOOL_PACKED_BEGIN class ot::SettingsBase::NetworkInfo OT_TOOL_PACKED_END
OT_TOOL_PACKED_BEGIN class ot::SettingsBase::ParentInfo OT_TOOL_PACKED_END
OT_TOOL_PACKED_BEGIN class ot::SettingsBase::ChildInfo OT_TOOL_PACKED_END
Protected Member Functions inherited from SettingsBase
void LogChildInfo (const char *, const ChildInfo &) const
void LogFailure (otError, const char *, bool) const
void LogNetworkInfo (const char *, const NetworkInfo &) const
void LogParentInfo (const char *, const ParentInfo &) const
SettingsBase (Instance &aInstance)
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Detailed Description
This class defines an iterator to access all Child Info entries in the settings.
Constructor & Destructor Documentation
ChildInfoIterator()
ChildInfoIterator (Instance & aInstance) explicit
This constructor initializes a ChildInfoInterator object.
Parameters
[in] aInstance A reference to the OpenThread instance.
References Settings::ChildInfoIterator::Reset().
Member Function Documentation
Reset()
void Reset (void)
This method resets the iterator to start from the first Child Info entry in the list.
References Settings::ChildInfoIterator::mIndex, Settings::ChildInfoIterator::mIsDone, and Settings::ChildInfoIterator::Read().
Referenced by Settings::ChildInfoIterator::ChildInfoIterator().
IsDone()
bool IsDone (void) const inline
This method indicates whether there are no more Child Info entries in the list (iterator has reached end of the list), or the current entry is valid.
Return values
TRUE There are no more entries in the list (reached end of the list).
FALSE The current entry is valid.
Advance()
void Advance (void)
This method advances the iterator to move to the next Child Info entry in the list (if any).
References Settings::ChildInfoIterator::mIndex, Settings::ChildInfoIterator::mIsDone, and Settings::ChildInfoIterator::Read().
operator++() [1/2]
void operator++ (void) inline
This method overloads operator ++ (pre-increment) to advance the iterator to move to the next Child Info entry in the list (if any).
operator++() [2/2]
void operator++ (int) inline
This method overloads operator ++ (post-increment) to advance the iterator to move to the next Child Info entry in the list (if any).
GetChildInfo()
const ChildInfo& GetChildInfo (void) const inline
This method gets the Child Info corresponding to the current iterator entry in the list.
Note
This method should be used only if IsDone() is returning FALSE indicating that the iterator is pointing to a valid entry.
Returns
A reference to ChildInfo structure corresponding to current iterator entry.
Delete()
otError Delete (void)
This method deletes the current Child Info entry.
Return values
OT_ERROR_NONE The entry was deleted successfully.
OT_ERROR_INVALID_STATE The entry is not valid (iterator has reached end of list).
OT_ERROR_NOT_IMPLEMENTED The platform does not implement settings functionality.
References SettingsBase::kKeyChildInfo, SettingsBase::LogChildInfo(), SettingsBase::LogFailure(), Settings::ChildInfoIterator::mChildInfo, Settings::ChildInfoIterator::mIndex, Settings::ChildInfoIterator::mIsDone, OT_ERROR_INVALID_STATE, OT_ERROR_NONE, SuccessOrExit, and VerifyOrExit.
Referenced by Settings::Delete().
Read()
void Read (void) private
References InstanceLocator::Get(), SettingsBase::ChildInfo::Init(), SettingsBase::kKeyChildInfo, SettingsBase::LogChildInfo(), Settings::ChildInfoIterator::mChildInfo, Settings::ChildInfoIterator::mIndex, Settings::ChildInfoIterator::mIsDone, OT_ERROR_NONE, and SuccessOrExit.
Referenced by Settings::ChildInfoIterator::Advance(), and Settings::ChildInfoIterator::Reset().
Field Documentation
mChildInfo
ChildInfo mChildInfo private
Referenced by Settings::ChildInfoIterator::Delete(), and Settings::ChildInfoIterator::Read().
mIndex
uint16_t mIndex private
Referenced by Settings::ChildInfoIterator::Advance(), Settings::ChildInfoIterator::Delete(), Settings::ChildInfoIterator::Read(), and Settings::ChildInfoIterator::Reset().
mIsDone
bool mIsDone private
Referenced by Settings::ChildInfoIterator::Advance(), Settings::ChildInfoIterator::Delete(), Settings::ChildInfoIterator::Read(), and Settings::ChildInfoIterator::Reset().
The documentation for this class was generated from the following files:
settings.hpp
core/common/settings.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale