OpenThread: Dtls Class Reference
Dtls Class Reference
#include <dtls.hpp>
Public Types
enum { kPskMaxLength = 32, kGuardTimeNewConnectionMilli = 2000, kApplicationDataMaxLength = 512 }
typedef void(* ConnectedHandler) (void *aContext, bool aConnected)
typedef void(* ReceiveHandler) (void *aContext, uint8_t *aBuf, uint16_t aLength)
typedef otError(* SendHandler) (void *aContext, const uint8_t *aBuf, uint16_t aLength, uint8_t aMessageSubType)
enum State {
kStateClosed = 0, kStateOpen, kStateInitializing, kStateConnecting,
kStateConnected, kStateCloseNotify
}
typedef otError(* TransportCallback) (void *aContext, ot::Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
Public Member Functions
otError Bind (uint16_t aPort)
otError Bind (TransportCallback aCallback, void *aContext)
void Close (void)
otError Connect (const Ip6::SockAddr &aSockAddr)
void Disconnect (void)
Dtls (Instance &aInstance, bool aLayerTwoSecurity)
const Ip6::MessageInfo & GetPeerAddress (void) const
State GetState (void) const
void HandleUdpReceive (Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
bool IsConnected (void) const
bool IsConnectionActive (void) const
otError Open (ReceiveHandler aReceiveHandler, ConnectedHandler aConnectedHandler, void *aContext)
void Receive (Message &aMessage)
otError Send (Message &aMessage, uint16_t aLength)
void SetDefaultMessageSubType (uint8_t aMessageSubType)
otError SetPsk (const uint8_t *aPsk, uint8_t aPskLength)
Public Member Functions inherited from InstanceLocator
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Private Member Functions
void FreeMbedtls (void)
void HandleDtlsReceive (const uint8_t *aBuf, uint16_t aLength)
otError HandleDtlsSend (const uint8_t *aBuf, uint16_t aLength, uint8_t aMessageSubType)
int HandleMbedtlsExportKeys (const unsigned char *aMasterSecret, const unsigned char *aKeyBlock, size_t aMacLength, size_t aKeyLength, size_t aIvLength)
int HandleMbedtlsGetTimer (void)
int HandleMbedtlsReceive (unsigned char *aBuf, size_t aLength)
void HandleMbedtlsSetTimer (uint32_t aIntermediate, uint32_t aFinish)
int HandleMbedtlsTransmit (const unsigned char *aBuf, size_t aLength)
void HandleTimer (void)
void HandleUdpTransmit (void)
void Process (void)
otError Setup (bool aClient)
Static Private Member Functions
static void HandleMbedtlsDebug (void *ctx, int level, const char *file, int line, const char *str)
static int HandleMbedtlsExportKeys (void *aContext, const unsigned char *aMasterSecret, const unsigned char *aKeyBlock, size_t aMacLength, size_t aKeyLength, size_t aIvLength)
static int HandleMbedtlsGetTimer (void *aContext)
static int HandleMbedtlsReceive (void *aContext, unsigned char *aBuf, size_t aLength)
static void HandleMbedtlsSetTimer (void *aContext, uint32_t aIntermediate, uint32_t aFinish)
static int HandleMbedtlsTransmit (void *aContext, const unsigned char *aBuf, size_t aLength)
static void HandleTimer (Timer &aTimer)
static void HandleUdpReceive (void *aContext, otMessage *aMessage, const otMessageInfo *aMessageInfo)
static void HandleUdpTransmit (Tasklet &aTasklet)
Private Attributes
int mCipherSuites [2]
mbedtls_ssl_config mConf
ConnectedHandler mConnectedHandler
void * mContext
bool mLayerTwoSecurity: 1
uint8_t mMessageDefaultSubType
uint8_t mMessageSubType
Ip6::MessageInfo mPeerAddress
uint8_t mPsk [kPskMaxLength]
uint8_t mPskLength
ReceiveHandler mReceiveHandler
Message * mReceiveMessage
SendHandler mSendHandler
Ip6::UdpSocket mSocket
mbedtls_ssl_context mSsl
State mState
TimerMilliContext mTimer
TimeMilli mTimerIntermediate
bool mTimerSet: 1
TransportCallback mTransportCallback
void * mTransportContext
bool mVerifyPeerCertificate
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Member Typedef Documentation
ConnectedHandler
typedef void(* ConnectedHandler) (void *aContext, bool aConnected)
This function pointer is called when a connection is established or torn down.
Parameters
[in] aContext A pointer to application-specific context.
[in] aConnected TRUE if a connection was established, FALSE otherwise.
ReceiveHandler
typedef void(* ReceiveHandler) (void *aContext, uint8_t *aBuf, uint16_t aLength)
This function pointer is called when data is received from the DTLS session.
Parameters
[in] aContext A pointer to application-specific context.
[in] aBuf A pointer to the received data buffer.
[in] aLength Number of bytes in the received data buffer.
TransportCallback
typedef otError(* TransportCallback) (void *aContext, ot::Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
This function pointer is called when secure CoAP server want to send encrypted message.
Parameters
[in] aContext A pointer to arbitrary context information.
[in] aMessage A reference to the message to send.
[in] aMessageInfo A reference to the message info associated with aMessage.
SendHandler
typedef otError(* SendHandler) (void *aContext, const uint8_t *aBuf, uint16_t aLength, uint8_t aMessageSubType)
This function pointer is called when data is ready to transmit for the DTLS session.
Parameters
[in] aContext A pointer to application-specific context.
[in] aBuf A pointer to the transmit data buffer.
[in] aLength Number of bytes in the transmit data buffer.
[in] aMessageSubtype A message sub type information for the sender.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
kPskMaxLength
kGuardTimeNewConnectionMilli
kApplicationDataMaxLength
State
enum State
Enumerator
kStateClosed
kStateOpen
kStateInitializing
kStateConnecting
kStateConnected
kStateCloseNotify
Constructor & Destructor Documentation
Dtls()
Dtls (Instance & aInstance, bool aLayerTwoSecurity) explicit
This constructor initializes the DTLS object.
Parameters
[in] aNetif A reference to the Thread network interface.
[in] aLayerTwoSecurity Specifies whether to use layer two security or not.
Member Function Documentation
Open()
otError Open (ReceiveHandler aReceiveHandler, ConnectedHandler aConnectedHandler, void * aContext)
This method opens the DTLS socket.
Parameters
[in] aReceiveHandler A pointer to a function that is called to receive DTLS payload.
[in] aConnectedHandler A pointer to a function that is called when connected or disconnected.
[in] aContext A pointer to arbitrary context information.
Return values
OT_ERROR_NONE Successfully opened the socket.
OT_ERROR_ALREADY The DTLS is already open.
Bind() [1/2]
otError Bind (uint16_t aPort)
This method binds this DTLS to a UDP port.
Parameters
[in] aPort The port to bind.
Return values
OT_ERROR_NONE Successfully bound the DTLS socket.
OT_ERROR_INVALID_STATE The DTLS service is not in state kStateOpen.
OT_ERROR_ALREADY Already bound.
Bind() [2/2]
otError Bind (TransportCallback aCallback, void * aContext)
This method binds this DTLS with a transport callback.
Parameters
[in] aCallback A pointer to a function for sending messages.
[in] aContext A pointer to arbitrary context information.
Return values
OT_ERROR_NONE Successfully bound the DTLS socket.
OT_ERROR_INVALID_STATE The DTLS service is not in state kStateOpen.
OT_ERROR_ALREADY Already bound.
Connect()
otError Connect (const Ip6::SockAddr & aSockAddr)
This method establishes a DTLS session.
For CoAP Secure API do first: Set X509 Pk and Cert for use DTLS mode ECDHE ECDSA with AES 128 CCM 8 or set PreShared Key for use DTLS mode PSK with AES 128 CCM 8.
Parameters
[in] aSockAddr A reference to the remote sockaddr.
Return values
OT_ERROR_NONE Successfully started DTLS handshake.
OT_ERROR_INVALID_STATE The DTLS service is not in state kStateOpen.
IsConnectionActive()
bool IsConnectionActive (void) const inline
This method indicates whether or not the DTLS session is active.
In other words, the state is kStateConnecting, kStateConnected, or kStateCloseNotify.
Return values
TRUE If DTLS session is active.
FALSE If DTLS session is not active.
References Dtls::kStateConnecting, and Dtls::mState.
Referenced by CoapSecure::IsConnectionActive().
IsConnected()
bool IsConnected (void) const inline
This method indicates whether or not the DTLS session is connected.
In other words, the state is kStateConnected.
Return values
TRUE The DTLS session is connected.
FALSE The DTLS session is not connected.
References Dtls::Close(), Dtls::Disconnect(), Dtls::kStateConnected, and Dtls::mState.
Referenced by CoapSecure::IsConnected().
Disconnect()
void Disconnect (void)
This method disconnects the DTLS session.
Referenced by CoapSecure::Disconnect(), and Dtls::IsConnected().
Close()
void Close (void)
This method closes the DTLS socket.
Referenced by Dtls::IsConnected().
GetState()
State GetState (void) const inline
This method returns the DTLS connection state.
Return values
kStateClosed The UDP socket closed.
kStateOpen The UDP socket is open.
kStateConnecting The DTLS service is establishing a connection.
kStateConnected The DTLS service has a connection established.
kStateCloseNotify The DTLS service is closing a connection.
References Dtls::mState, Dtls::Receive(), Dtls::Send(), and Dtls::SetPsk().
SetPsk()
otError SetPsk (const uint8_t * aPsk, uint8_t aPskLength)
This method sets the PSK.
Parameters
[in] aPsk A pointer to the PSK.
Return values
OT_ERROR_NONE Successfully set the PSK.
OT_ERROR_INVALID_ARGS The PSK is invalid.
Referenced by Dtls::GetState().
Send()
otError Send (Message & aMessage, uint16_t aLength)
This method sends data within the DTLS session.
Parameters
[in] aMessage A message to send via DTLS.
[in] aLength Number of bytes in the data buffer.
Return values
OT_ERROR_NONE Successfully sent the data via the DTLS session.
OT_ERROR_NO_BUFS A message is too long.
Referenced by Dtls::GetState().
Receive()
void Receive (Message & aMessage)
This method provides a received DTLS message to the DTLS object.
Parameters
[in] aMessage A reference to the message.
Referenced by Dtls::GetState().
SetDefaultMessageSubType()
void SetDefaultMessageSubType (uint8_t aMessageSubType) inline
This method sets the default message sub-type that will be used for all messages without defined sub-type.
Parameters
[in] aMessageSubType The default message sub-type.
References Dtls::mMessageDefaultSubType.
GetPeerAddress()
const Ip6::MessageInfo& GetPeerAddress (void) const inline
This method returns the DTLS session's peer address.
Returns
DTLS session's message info.
References Dtls::FreeMbedtls(), Dtls::HandleDtlsReceive(), Dtls::HandleDtlsSend(), Dtls::HandleMbedtlsDebug(), Dtls::HandleMbedtlsExportKeys(), Dtls::HandleMbedtlsGetTimer(), Dtls::HandleMbedtlsReceive(), Dtls::HandleMbedtlsSetTimer(), Dtls::HandleMbedtlsTransmit(), Dtls::HandleTimer(), Dtls::HandleUdpReceive(), Dtls::HandleUdpTransmit(), Dtls::mPeerAddress, Dtls::Process(), and Dtls::Setup().
Referenced by CoapSecure::GetPeerAddress().
HandleUdpReceive() [1/2]
void HandleUdpReceive (Message & aMessage, const Ip6::MessageInfo & aMessageInfo)
Referenced by Dtls::GetPeerAddress(), and CoapSecure::HandleUdpReceive().
FreeMbedtls()
void FreeMbedtls (void) private
Referenced by Dtls::GetPeerAddress().
Setup()
otError Setup (bool aClient) private
Referenced by Dtls::GetPeerAddress().
HandleMbedtlsDebug()
static void HandleMbedtlsDebug (void * ctx, int level, const char * file, int line, const char * str) static private
Referenced by Dtls::GetPeerAddress().
HandleMbedtlsGetTimer() [1/2]
static int HandleMbedtlsGetTimer (void * aContext) static private
HandleMbedtlsGetTimer() [2/2]
int HandleMbedtlsGetTimer (void) private
Referenced by Dtls::GetPeerAddress().
HandleMbedtlsSetTimer() [1/2]
static void HandleMbedtlsSetTimer (void * aContext, uint32_t aIntermediate, uint32_t aFinish) static private
Referenced by Dtls::GetPeerAddress().
HandleMbedtlsSetTimer() [2/2]
void HandleMbedtlsSetTimer (uint32_t aIntermediate, uint32_t aFinish) private
HandleMbedtlsReceive() [1/2]
static int HandleMbedtlsReceive (void * aContext, unsigned char * aBuf, size_t aLength) static private
Referenced by Dtls::GetPeerAddress().
HandleMbedtlsReceive() [2/2]
int HandleMbedtlsReceive (unsigned char * aBuf, size_t aLength) private
HandleMbedtlsTransmit() [1/2]
static int HandleMbedtlsTransmit (void * aContext, const unsigned char * aBuf, size_t aLength) static private
Referenced by Dtls::GetPeerAddress().
HandleMbedtlsTransmit() [2/2]
int HandleMbedtlsTransmit (const unsigned char * aBuf, size_t aLength) private
HandleMbedtlsExportKeys() [1/2]
static int HandleMbedtlsExportKeys (void * aContext, const unsigned char * aMasterSecret, const unsigned char * aKeyBlock, size_t aMacLength, size_t aKeyLength, size_t aIvLength) static private
Referenced by Dtls::GetPeerAddress().
HandleMbedtlsExportKeys() [2/2]
int HandleMbedtlsExportKeys (const unsigned char * aMasterSecret, const unsigned char * aKeyBlock, size_t aMacLength, size_t aKeyLength, size_t aIvLength) private
HandleTimer() [1/2]
static void HandleTimer (Timer & aTimer) static private
HandleTimer() [2/2]
void HandleTimer (void) private
Referenced by Dtls::GetPeerAddress().
HandleUdpReceive() [2/2]
static void HandleUdpReceive (void * aContext, otMessage * aMessage, const otMessageInfo * aMessageInfo) static private
HandleDtlsReceive()
void HandleDtlsReceive (const uint8_t * aBuf, uint16_t aLength) private
Referenced by Dtls::GetPeerAddress().
HandleDtlsSend()
otError HandleDtlsSend (const uint8_t * aBuf, uint16_t aLength, uint8_t aMessageSubType) private
Referenced by Dtls::GetPeerAddress().
HandleUdpTransmit() [1/2]
static void HandleUdpTransmit (Tasklet & aTasklet) static private
HandleUdpTransmit() [2/2]
void HandleUdpTransmit (void) private
Referenced by Dtls::GetPeerAddress().
Process()
void Process (void) private
Referenced by Dtls::GetPeerAddress().
Field Documentation
mState
State mState private
Referenced by Dtls::GetState(), Dtls::IsConnected(), and Dtls::IsConnectionActive().
mCipherSuites
int mCipherSuites[2] private
mPsk
uint8_t mPsk[kPskMaxLength] private
mPskLength
uint8_t mPskLength private
mVerifyPeerCertificate
bool mVerifyPeerCertificate private
mSsl
mbedtls_ssl_context mSsl private
mConf
mbedtls_ssl_config mConf private
mTimer
TimerMilliContext mTimer private
mTimerIntermediate
TimeMilli mTimerIntermediate private
mTimerSet
bool mTimerSet private
mLayerTwoSecurity
bool mLayerTwoSecurity private
mReceiveMessage
Message* mReceiveMessage private
mConnectedHandler
ConnectedHandler mConnectedHandler private
mReceiveHandler
ReceiveHandler mReceiveHandler private
mSendHandler
SendHandler mSendHandler private
mContext
void* mContext private
mPeerAddress
Ip6::MessageInfo mPeerAddress private
Referenced by Dtls::GetPeerAddress().
mSocket
Ip6::UdpSocket mSocket private
mTransportCallback
TransportCallback mTransportCallback private
mTransportContext
void* mTransportContext private
mMessageSubType
uint8_t mMessageSubType private
mMessageDefaultSubType
uint8_t mMessageDefaultSubType private
Referenced by Dtls::SetDefaultMessageSubType().
The documentation for this class was generated from the following file:
dtls.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale