OpenThread: Timestamp Class Reference
Timestamp Class Reference
#include <timestamp.hpp>
Public Member Functions
int Compare (const Timestamp &aCompare) const
bool GetAuthoritative (void) const
uint64_t GetSeconds (void) const
uint16_t GetTicks (void) const
void Init (void)
void SetAuthoritative (bool aAuthoritative)
void SetSeconds (uint64_t aSeconds)
void SetTicks (uint16_t aTicks)
Private Types
enum { kTicksOffset = 1, kTicksMask = 0x7fff << kTicksOffset, kAuthoritativeOffset = 0, kAuthoritativeMask = 1 << kAuthoritativeOffset }
Private Attributes
uint16_t mSeconds16
uint32_t mSeconds32
uint16_t mTicks
Detailed Description
This class implements Timestamp generation and parsing.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
kTicksOffset
kTicksMask
kAuthoritativeOffset
kAuthoritativeMask
Member Function Documentation
Init()
void Init (void) inline
This method initializes the Timestamp
References Timestamp::Compare().
Referenced by DatasetLocal::Clear(), DatasetManager::Clear(), PendingDataset::ClearNetwork(), DatasetLocal::DatasetLocal(), DatasetManager::DatasetManager(), ActiveTimestampTlv::Init(), and PendingTimestampTlv::Init().
Compare()
int Compare (const Timestamp & aCompare) const
This method compares this timestamp to another.
Parameters
[in] aCompare A reference to the timestamp to compare.
Return values
-1 if aCompare is less than this timestamp.
0 if aCompare is equal to this timestamp.
1 if aCompare is greater than this timestamp.
References Timestamp::GetSeconds(), and Timestamp::GetTicks().
Referenced by DatasetManager::Compare(), DatasetLocal::Compare(), Mle::HandleAnnounce(), and Timestamp::Init().
GetSeconds()
uint64_t GetSeconds (void) const inline
This method returns the Seconds value.
Returns
The Seconds value.
References ot::Encoding::BigEndian::HostSwap16(), ot::Encoding::BigEndian::HostSwap32(), Timestamp::mSeconds16, and Timestamp::mSeconds32.
Referenced by Mle::AppendPendingTimestamp(), Timestamp::Compare(), and Mle::HandleAnnounce().
SetSeconds()
void SetSeconds (uint64_t aSeconds) inline
This method sets the Seconds value.
Parameters
[in] aSeconds The Seconds value.
References ot::Encoding::BigEndian::HostSwap16(), ot::Encoding::BigEndian::HostSwap32(), Timestamp::mSeconds16, and Timestamp::mSeconds32.
Referenced by Mle::SendAnnounce(), DatasetManager::SendSetRequest(), and Dataset::SetFrom().
GetTicks()
uint16_t GetTicks (void) const inline
This method returns the Ticks value.
Returns
The Ticks value.
References ot::Encoding::BigEndian::HostSwap16(), Timestamp::kTicksOffset, and Timestamp::mTicks.
Referenced by Timestamp::Compare().
SetTicks()
void SetTicks (uint16_t aTicks) inline
This method sets the Ticks value.
Parameters
[in] aTicks The Ticks value.
References ot::Encoding::BigEndian::HostSwap16(), Timestamp::kTicksMask, Timestamp::kTicksOffset, and Timestamp::mTicks.
Referenced by Mle::SendAnnounce(), DatasetManager::SendSetRequest(), and Dataset::SetFrom().
GetAuthoritative()
bool GetAuthoritative (void) const inline
This method returns the Authoritative value.
Returns
The Authoritative value.
References ot::Encoding::BigEndian::HostSwap16(), Timestamp::kAuthoritativeMask, and Timestamp::mTicks.
SetAuthoritative()
void SetAuthoritative (bool aAuthoritative) inline
This method sets the Authoritative value.
Parameters
[in] aAuthoritative The Authoritative value.
References ot::Encoding::BigEndian::HostSwap16(), Timestamp::kAuthoritativeMask, Timestamp::kAuthoritativeOffset, Timestamp::kTicksMask, and Timestamp::mTicks.
Referenced by Mle::SendAnnounce().
Field Documentation
mSeconds16
uint16_t mSeconds16 private
Referenced by Timestamp::GetSeconds(), and Timestamp::SetSeconds().
mSeconds32
uint32_t mSeconds32 private
Referenced by Timestamp::GetSeconds(), and Timestamp::SetSeconds().
mTicks
uint16_t mTicks private
Referenced by Timestamp::GetAuthoritative(), Timestamp::GetTicks(), Timestamp::SetAuthoritative(), and Timestamp::SetTicks().
The documentation for this class was generated from the following files:
timestamp.hpp
timestamp.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale