OpenThread: Instance Class Reference
Instance Class Reference
Core-instance
#include <instance.hpp>
Public Member Functions
void Finalize (void)
template<typename Type >
Type & Get (void)
template<>
Radio & Get (void)
template<>
Radio::Callbacks & Get (void)
template<>
TaskletScheduler & Get (void)
template<>
TimerMilliScheduler & Get (void)
otLogLevel GetLogLevel (void) const
bool IsInitialized (void) const
void Reset (void)
Static Public Member Functions
static Instance & Get (void)
static Instance & InitSingle (void)
Private Member Functions
void AfterInit (void)
Instance (void)
Private Attributes
bool mIsInitialized
Radio mRadio
RandomManager mRandomManager
TaskletScheduler mTaskletScheduler
TimerMilliScheduler mTimerMilliScheduler
Detailed Description
This class represents an OpenThread instance.
This class contains all the components used by OpenThread.
Constructor & Destructor Documentation
Instance()
Instance (void) private
Referenced by Instance::Get(), and Instance::InitSingle().
Member Function Documentation
InitSingle()
Instance & InitSingle (void) static
This static method initializes the single OpenThread instance.
This method initializes OpenThread and prepares it for subsequent OpenThread API calls. This function must be called before any other calls to OpenThread.
Returns
A reference to the single OpenThread instance.
References Instance::AfterInit(), Instance::Get(), ot::gInstanceRaw, Instance::Instance(), Instance::mIsInitialized, OT_NOOP, and VerifyOrExit.
Referenced by otInstanceInitSingle().
Get() [1/5]
Instance & Get (void) static
This static method returns a reference to the single OpenThread instance.
Returns
A reference to the single OpenThread instance.
References Instance::AfterInit(), ot::gInstanceRaw, Instance::Instance(), OT_NOOP, and VerifyOrExit.
Referenced by Dataset::ApplyConfiguration(), Notifier::Callback::Callback(), InstanceLocator::Get(), OwnerLocator::GetOwner(), Instance::InitSingle(), NcpBase::NcpBase(), otBackboneRouterGetPrimary(), otDatasetGetActive(), otDatasetGetPending(), otDatasetSendMgmtActiveGet(), otDatasetSendMgmtActiveSet(), otDatasetSendMgmtPendingGet(), otDatasetSendMgmtPendingSet(), otDatasetSetActive(), otDatasetSetPending(), otGetRadioVersionString(), otHeapCAlloc(), otHeapFree(), otIcmp6GetEchoMode(), otIcmp6RegisterHandler(), otIcmp6SendEchoRequest(), otIcmp6SetEchoMode(), otInstanceReset(), otIp6AddUnicastAddress(), otIp6AddUnsecurePort(), otIp6GetMulticastAddresses(), otIp6GetUnicastAddresses(), otIp6GetUnsecurePorts(), otIp6IsEnabled(), otIp6IsMulticastPromiscuousEnabled(), otIp6IsReceiveFilterEnabled(), otIp6NewMessage(), otIp6NewMessageFromBuffer(), otIp6RemoveAllUnsecurePorts(), otIp6RemoveUnicastAddress(), otIp6RemoveUnsecurePort(), otIp6SelectSourceAddress(), otIp6Send(), otIp6SetAddressCallback(), otIp6SetEnabled(), otIp6SetMulticastPromiscuousEnabled(), otIp6SetReceiveCallback(), otIp6SetReceiveFilterEnabled(), otIp6SubscribeMulticastAddress(), otIp6UnsubscribeMulticastAddress(), otLinkActiveScan(), otLinkEnergyScan(), otLinkGetCcaFailureRate(), otLinkGetChannel(), otLinkGetCounters(), otLinkGetExtendedAddress(), otLinkGetFactoryAssignedIeeeEui64(), otLinkGetMaxFrameRetriesDirect(), otLinkGetPanId(), otLinkGetPollPeriod(), otLinkGetShortAddress(), otLinkGetSupportedChannelMask(), otLinkIsActiveScanInProgress(), otLinkIsEnabled(), otLinkIsEnergyScanInProgress(), otLinkIsInTransmitState(), otLinkIsPromiscuous(), otLinkOutOfBandTransmitRequest(), otLinkResetCounters(), otLinkSendDataRequest(), otLinkSetChannel(), otLinkSetEnabled(), otLinkSetExtendedAddress(), otLinkSetMaxFrameRetriesDirect(), otLinkSetPanId(), otLinkSetPcapCallback(), otLinkSetPollPeriod(), otLinkSetPromiscuous(), otLinkSetSupportedChannelMask(), otLoggingGetLevel(), otMessageQueueGetNext(), otNetDataGet(), otNetDataGetNextOnMeshPrefix(), otNetDataGetNextRoute(), otNetDataGetNextService(), otNetDataGetStableVersion(), otNetDataGetVersion(), otPlatRadioEnergyScanDone(), otPlatRadioReceiveDone(), otPlatRadioTxDone(), otPlatRadioTxStarted(), otTaskletsArePending(), otTaskletsProcess(), otUdpAddReceiver(), otUdpNewMessage(), otUdpOpen(), otUdpRemoveReceiver(), otUdpSend(), and otUdpSendDatagram().
IsInitialized()
bool IsInitialized (void) const inline
This method indicates whether or not the instance is valid/initialized and not yet finalized.
Returns
TRUE if the instance is valid/initialized, FALSE otherwise.
Referenced by otInstanceIsInitialized(), otPlatRadioEnergyScanDone(), otPlatRadioReceiveDone(), otPlatRadioTxDone(), and otPlatRadioTxStarted().
Reset()
void Reset (void)
This method triggers a platform reset.
The reset process ensures that all the OpenThread state/info (stored in volatile memory) is erased. Note that this method does not erase any persistent state/info saved in non-volatile memory.
References otPlatReset().
Referenced by otInstanceReset().
GetLogLevel()
otLogLevel GetLogLevel (void) const inline
This method returns the active log level.
Returns
The log level.
References OPENTHREAD_CONFIG_LOG_LEVEL, OT_ASSERT, OT_LOG_LEVEL_NONE, otPlatCAlloc(), and otPlatFree().
Referenced by otLoggingGetLevel().
Finalize()
void Finalize (void)
This method finalizes the OpenThread instance.
This method should be called when OpenThread instance is no longer in use.
Object was created on buffer, so instead of deleting the object we call destructor explicitly.
References IgnoreReturnValue, Instance::mIsInitialized, OT_ERROR_INVALID_STATE, OT_ERROR_NONE, OT_NOOP, otIp6SetEnabled(), otLinkSetEnabled(), otPlatReset(), otThreadSetEnabled(), and VerifyOrExit.
Referenced by otInstanceFinalize().
Get() [2/5]
Type& Get (void) inline
This template method returns a reference to a given Type object belonging to the OpenThread instance.
For example, Get<MeshForwarder>() returns a reference to the MeshForwarder object of the instance.
Note that any Type for which the Get<Type> is defined MUST be uniquely accessible from the OpenThread Instance through the member variable property hierarchy.
Specializations of the Get<Type>() method are defined in this file after the Instance class definition.
Returns
A reference to the Type object of the instance.
AfterInit()
void AfterInit (void) private
References Instance::mIsInitialized.
Referenced by Instance::Get(), and Instance::InitSingle().
Get() [3/5]
Radio::Callbacks& Get (void) inline
References AnnounceBeginServer::mAnnounceBegin, EnergyScanServer::mEnergyScan, and PanIdQueryServer::mPanIdQuery.
Get() [4/5]
TaskletScheduler& Get (void) inline
Get() [5/5]
TimerMilliScheduler& Get (void) inline
Field Documentation
mTaskletScheduler
TaskletScheduler mTaskletScheduler private
mTimerMilliScheduler
TimerMilliScheduler mTimerMilliScheduler private
mRandomManager
RandomManager mRandomManager private
mRadio
Radio mRadio private
mIsInitialized
bool mIsInitialized private
Referenced by Instance::AfterInit(), Instance::Finalize(), and Instance::InitSingle().
The documentation for this class was generated from the following files:
instance.hpp
instance.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale