OpenThread: NameData Class Reference
NameData Class Reference
Core-mac
#include <mac_types.hpp>
Public Member Functions
uint8_t CopyTo (char *aBuffer, uint8_t aMaxSize) const
const char * GetBuffer (void) const
uint8_t GetLength (void) const
NameData (const char *aBuffer, uint8_t aLength)
Private Attributes
const char * mBuffer
uint8_t mLength
Detailed Description
This class represents a name string as data (pointer to a char buffer along with a length).
Note
The char array does NOT need to be null terminated.
Constructor & Destructor Documentation
NameData()
NameData (const char * aBuffer, uint8_t aLength) inline
This constructor initializes the NameData object.
Parameters
[in] aBuffer A pointer to a char buffer (does not need to be null terminated).
[in] aLength The length (number of chars) in the buffer.
Member Function Documentation
GetBuffer()
const char* GetBuffer (void) const inline
This method returns the pointer to char buffer (not necessarily null terminated).
Returns
The pointer to the char buffer.
Referenced by NetworkName::Set(), DomainName::Set(), and Dataset::SetFrom().
GetLength()
uint8_t GetLength (void) const inline
This method returns the length (number of chars in buffer).
Returns
The name length.
References ExtAddress::CopyTo().
Referenced by NetworkName::Set(), DomainName::Set(), and Dataset::SetFrom().
CopyTo()
uint8_t CopyTo (char * aBuffer, uint8_t aMaxSize) const
This method copies the name data into a given char buffer with a given size.
The given buffer is cleared (memset to zero) before copying the name into it. The copied string in aBuffer is NOT necessarily null terminated.
Parameters
[out] aBuffer A pointer to a buffer where to copy the name into.
[in] aMaxSize Size of aBuffer (maximum number of chars to write into aBuffer).
Returns
The actual number of chars copied into aBuffer.
Referenced by NetworkNameTlv::SetNetworkName(), and BeaconPayload::SetNetworkName().
Field Documentation
mBuffer
const char* mBuffer private
mLength
uint8_t mLength private
The documentation for this class was generated from the following files:
mac_types.hpp
mac_types.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale