OpenThread: BorderRouterEntry Class Reference
BorderRouterEntry Class Reference
Core-netdata » TLVs
#include <network_data_tlvs.hpp>
Public Types
enum {
kPreferenceOffset = 14, kPreferenceMask = 3 << kPreferenceOffset, kPreferredFlag = 1 << 13, kSlaacFlag = 1 << 12,
kDhcpFlag = 1 << 11, kConfigureFlag = 1 << 10, kDefaultRouteFlag = 1 << 9, kOnMeshFlag = 1 << 8,
kNdDnsFlag = 1 << 7, kDpFlag = 1 << 6
}
Public Member Functions
uint16_t GetFlags (void) const
BorderRouterEntry * GetNext (void)
const BorderRouterEntry * GetNext (void) const
int8_t GetPreference (void) const
uint16_t GetRloc (void) const
void Init (void)
bool IsConfigure (void) const
bool IsDefaultRoute (void) const
bool IsDhcp (void) const
bool IsDp (void) const
bool IsNdDns (void) const
bool IsOnMesh (void) const
bool IsPreferred (void) const
bool IsSlaac (void) const
bool operator== (const BorderRouterEntry &aOtherEntry) const
void SetFlags (uint16_t aFlags)
void SetPreference (int8_t aPrf)
void SetRloc (uint16_t aRloc16)
Private Attributes
uint16_t mFlags
uint16_t mRloc
Detailed Description
This class implements Border Router Entry generation and parsing.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
kPreferenceOffset
kPreferenceMask
kPreferredFlag
kSlaacFlag
kDhcpFlag
kConfigureFlag
kDefaultRouteFlag
kOnMeshFlag
kNdDnsFlag
kDpFlag
Member Function Documentation
Init()
void Init (void) inline
This method initializes the TLV.
References ot::Mac::kShortAddrInvalid.
GetRloc()
uint16_t GetRloc (void) const inline
This method returns the RLOC16 value.
Returns
The RLOC16 value.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by LeaderBase::DefaultRouteLookup(), and NetworkData::Iterate().
SetRloc()
void SetRloc (uint16_t aRloc16) inline
This method sets the RLOC16 value.
Parameters
[in] aRloc16 The RLOC16 value.
References ot::Encoding::BigEndian::HostSwap16().
GetFlags()
uint16_t GetFlags (void) const inline
This method returns the Flags value.
Returns
The Flags value.
References ot::Encoding::BigEndian::HostSwap16().
SetFlags()
void SetFlags (uint16_t aFlags) inline
This method sets the Flags value.
Parameters
[in] aFlags The Flags value.
References ot::Encoding::BigEndian::HostSwap16().
GetPreference()
int8_t GetPreference (void) const inline
This method returns the Preference value.
Returns
the Preference value.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by LeaderBase::DefaultRouteLookup(), and NetworkData::Iterate().
SetPreference()
void SetPreference (int8_t aPrf) inline
This method sets the Preference value.
Parameters
[in] aPrf The Preference value.
References ot::Encoding::BigEndian::HostSwap16().
IsPreferred()
bool IsPreferred (void) const inline
This method indicates whether or not the Preferred flag is set.
Return values
TRUE If the Preferred flag is set.
FALSE If the Preferred flag is not set.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by NetworkData::Iterate().
IsSlaac()
bool IsSlaac (void) const inline
This method indicates whether or not the SLAAC flag is set.
Return values
TRUE If the SLAAC flag is set.
FALSE If the SLAAC flag is not set.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by NetworkData::Iterate().
IsDhcp()
bool IsDhcp (void) const inline
This method indicates whether or not the DHCP flag is set.
Return values
TRUE If the DHCP flag is set.
FALSE If the DHCP flag is not set.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by NetworkData::Iterate().
IsConfigure()
bool IsConfigure (void) const inline
This method indicates whether or not the Configure flag is set.
Return values
TRUE If the Configure flag is set.
FALSE If the Configure flag is not set.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by NetworkData::Iterate().
IsDefaultRoute()
bool IsDefaultRoute (void) const inline
This method indicates whether or not the Default Route flag is set.
Return values
TRUE If the Default Route flag is set.
FALSE If the Default Route flag is not set.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by NetworkData::Iterate().
IsOnMesh()
bool IsOnMesh (void) const inline
This method indicates whether or not the On-Mesh flag is set.
Return values
TRUE If the On-Mesh flag is set.
FALSE If the On-Mesh flag is not set.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by NetworkData::Iterate().
IsNdDns()
bool IsNdDns (void) const inline
This method indicates whether or not the Nd-Dns flag is set.
Return values
TRUE If the Nd-Dns flag is set.
FALSE If the Nd-Dns flag is not set.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by NetworkData::Iterate().
IsDp()
bool IsDp (void) const inline
This method indicates whether or not the Domain Prefix flag is set.
Return values
TRUE If the Domain Prefix flag is set.
FALSE If the Domain Prefix flag is not set.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by NetworkData::Iterate().
GetNext() [1/2]
BorderRouterEntry* GetNext (void) inline
This method returns a pointer to the next BorderRouterEntry
Returns
A pointer to the next BorderRouterEntry.
Referenced by LeaderBase::DefaultRouteLookup(), and NetworkData::RemoveTemporaryData().
GetNext() [2/2]
const BorderRouterEntry* GetNext (void) const inline
This method returns a pointer to the next BorderRouterEntry
Returns
A pointer to the next BorderRouterEntry.
operator==()
bool operator== (const BorderRouterEntry & aOtherEntry) const inline
This method indicates whether two entries fully match.
Parameters
[in] aOtherEntry Another entry to compare with it.
Return values
TRUE The two entries are equal.
FALSE The two entries are not equal.
Field Documentation
mRloc
uint16_t mRloc private
mFlags
uint16_t mFlags private
The documentation for this class was generated from the following file:
network_data_tlvs.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale