OpenThread: Netif Class Reference
Netif Class Reference
Core-ipv6 » Network Interfaces
#include <netif.hpp>
Public Member Functions
otError AddExternalUnicastAddress (const NetifUnicastAddress &aAddress)
otError AddUnicastAddress (NetifUnicastAddress &aAddress)
const NetifMulticastAddress * GetMulticastAddresses (void) const
otError GetNextExternalMulticast (uint8_t &aIterator, Address &aAddress) const
const NetifUnicastAddress * GetUnicastAddresses (void) const
bool IsMulticastPromiscuousEnabled (void) const
bool IsMulticastSubscribed (const Address &aAddress) const
bool IsUnicastAddress (const Address &aAddress) const
Netif (Instance &aInstance)
void RemoveAllExternalUnicastAddresses (void)
otError RemoveExternalUnicastAddress (const Address &aAddress)
otError RemoveUnicastAddress (const NetifUnicastAddress &aAddress)
void SetAddressCallback (otIp6AddressCallback aCallback, void *aCallbackContext)
void SetMulticastPromiscuous (bool aEnabled)
otError SubscribeAllRoutersMulticast (void)
otError SubscribeExternalMulticast (const Address &aAddress)
otError SubscribeMulticast (NetifMulticastAddress &aAddress)
void UnsubscribeAllExternalMulticastAddresses (void)
otError UnsubscribeAllRoutersMulticast (void)
otError UnsubscribeExternalMulticast (const Address &aAddress)
otError UnsubscribeMulticast (const NetifMulticastAddress &aAddress)
Public Member Functions inherited from InstanceLocator
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Public Member Functions inherited from LinkedListEntry< Netif >
const Netif * GetNext (void) const
Netif * GetNext (void)
void SetNext (Netif *aNext)
Protected Member Functions
otError SubscribeAllNodesMulticast (void)
otError UnsubscribeAllNodesMulticast (void)
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Private Types
enum { kMulticastPrefixLength = 128 }
Private Attributes
otIp6AddressCallback mAddressCallback
void * mAddressCallbackContext
NetifMulticastAddress mExtMulticastAddresses [OPENTHREAD_CONFIG_IP6_MAX_EXT_MCAST_ADDRS]
NetifUnicastAddress mExtUnicastAddresses [OPENTHREAD_CONFIG_IP6_MAX_EXT_UCAST_ADDRS]
LinkedList< NetifMulticastAddress > mMulticastAddresses
bool mMulticastPromiscuous
LinkedList< NetifUnicastAddress > mUnicastAddresses
Static Private Attributes
static const otNetifMulticastAddress kLinkLocalAllNodesMulticastAddress
static const otNetifMulticastAddress kLinkLocalAllRoutersMulticastAddress
static const otNetifMulticastAddress kRealmLocalAllMplForwardersMulticastAddress
static const otNetifMulticastAddress kRealmLocalAllNodesMulticastAddress
static const otNetifMulticastAddress kRealmLocalAllRoutersMulticastAddress
Friends
class Address
class Ip6
Detailed Description
This class implements an IPv6 network interface.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
kMulticastPrefixLength
Multicast prefix length used to notify internal address changes.
Constructor & Destructor Documentation
Netif()
Netif (Instance & aInstance)
This constructor initializes the network interface.
Parameters
[in] aInstance A reference to the OpenThread instance.
References Netif::mExtMulticastAddresses, Netif::mExtUnicastAddresses, and OT_ARRAY_END.
Member Function Documentation
SetAddressCallback()
void SetAddressCallback (otIp6AddressCallback aCallback, void * aCallbackContext)
This method registers a callback to notify internal IPv6 address changes.
Parameters
[in] aCallback A pointer to a function that is called when an IPv6 address is added or removed.
[in] aCallbackContext A pointer to application-specific context.
References Netif::mAddressCallback, and Netif::mAddressCallbackContext.
GetUnicastAddresses()
const NetifUnicastAddress* GetUnicastAddresses (void) const inline
This method returns a pointer to the list of unicast addresses.
Returns
A pointer to the list of unicast addresses.
AddUnicastAddress()
otError AddUnicastAddress (NetifUnicastAddress & aAddress)
This method adds a unicast address to the network interface.
Parameters
[in] aAddress A reference to the unicast address.
Return values
OT_ERROR_NONE Successfully added the unicast address.
OT_ERROR_ALREADY The unicast address was already added.
References otNetifAddress::mAddress, Netif::mAddressCallback, Netif::mAddressCallbackContext, otNetifAddress::mPrefixLength, otNetifAddress::mRloc, Netif::mUnicastAddresses, OT_CHANGED_IP6_ADDRESS_ADDED, OT_CHANGED_THREAD_RLOC_ADDED, OT_NOOP, SuccessOrExit, and VerifyOrExit.
RemoveUnicastAddress()
otError RemoveUnicastAddress (const NetifUnicastAddress & aAddress)
This method removes a unicast address from the network interface.
Parameters
[in] aAddress A reference to the unicast address.
Return values
OT_ERROR_NONE Successfully removed the unicast address.
OT_ERROR_NOT_FOUND The unicast address wasn't found to be removed.
References otNetifAddress::mAddress, Netif::mAddressCallback, Netif::mAddressCallbackContext, otNetifAddress::mPrefixLength, otNetifAddress::mRloc, Netif::mUnicastAddresses, OT_CHANGED_IP6_ADDRESS_REMOVED, OT_CHANGED_THREAD_RLOC_REMOVED, OT_NOOP, SuccessOrExit, and VerifyOrExit.
AddExternalUnicastAddress()
otError AddExternalUnicastAddress (const NetifUnicastAddress & aAddress)
This method adds an external (to OpenThread) unicast address to the network interface.
Parameters
[in] aAddress A reference to the unicast address.
Return values
OT_ERROR_NONE Successfully added (or updated) the unicast address.
OT_ERROR_INVALID_ARGS The address indicated by aAddress is an internal address.
OT_ERROR_NO_BUFS The maximum number of allowed external addresses are already added.
References ExitNow, NetifUnicastAddress::GetAddress(), LinkedListEntry< Type >::GetNext(), NetifUnicastAddress::IsInUse(), Address::IsLinkLocal(), Netif::mExtUnicastAddresses, otNetifAddress::mPreferred, otNetifAddress::mPrefixLength, Netif::mUnicastAddresses, otNetifAddress::mValid, OT_ARRAY_END, OT_CHANGED_IP6_ADDRESS_ADDED, OT_ERROR_ALREADY, OT_ERROR_INVALID_ARGS, OT_ERROR_NO_BUFS, OT_ERROR_NONE, and VerifyOrExit.
RemoveExternalUnicastAddress()
otError RemoveExternalUnicastAddress (const Address & aAddress)
This method removes a external (to OpenThread) unicast address from the network interface.
Parameters
[in] aAddress A reference to the unicast address.
Return values
OT_ERROR_NONE Successfully removed the unicast address.
OT_ERROR_INVALID_ARGS The address indicated by aAddress is an internal address.
OT_ERROR_NOT_FOUND The unicast address was not found.
References NetifUnicastAddress::GetAddress(), LinkedListEntry< Type >::GetNext(), NetifUnicastAddress::MarkAsNotInUse(), Netif::mExtUnicastAddresses, Netif::mUnicastAddresses, OT_ARRAY_END, OT_CHANGED_IP6_ADDRESS_REMOVED, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, OT_ERROR_NOT_FOUND, and VerifyOrExit.
Referenced by Netif::RemoveAllExternalUnicastAddresses().
RemoveAllExternalUnicastAddresses()
void RemoveAllExternalUnicastAddresses (void)
This method removes all the previously added external (to OpenThread) unicast addresses from the network interface.
References Netif::mExtUnicastAddresses, OT_ARRAY_END, and Netif::RemoveExternalUnicastAddress().
Referenced by ThreadNetif::Down().
IsUnicastAddress()
bool IsUnicastAddress (const Address & aAddress) const
This method indicates whether or not an address is assigned to this interface.
Parameters
[in] aAddress A reference to the unicast address.
Returns
TRUE if aAddress is assigned to this interface, FALSE otherwise.
References ExitNow, and Netif::mUnicastAddresses.
IsMulticastSubscribed()
bool IsMulticastSubscribed (const Address & aAddress) const
This method indicates whether or not the network interface is subscribed to a multicast address.
Parameters
[in] aAddress The multicast address to check.
Return values
TRUE If the network interface is subscribed to aAddress.
FALSE If the network interface is not subscribed to aAddress.
References ExitNow, and Netif::mMulticastAddresses.
Referenced by Ip6::HandleDatagram(), and Netif::SubscribeExternalMulticast().
SubscribeAllRoutersMulticast()
otError SubscribeAllRoutersMulticast (void)
This method subscribes the network interface to the link-local and realm-local all routers addresses.
Note
This method MUST be called after SubscribeAllNodesMulticast() or its behavior is undefined.
Return values
OT_ERROR_NONE Successfully subscribed to the link-local and realm-local all routers addresses.
OT_ERROR_ALREADY The multicast addresses are already subscribed.
References NetifMulticastAddress::GetNext(), Netif::kLinkLocalAllNodesMulticastAddress, Netif::kLinkLocalAllRoutersMulticastAddress, Netif::kMulticastPrefixLength, Netif::kRealmLocalAllRoutersMulticastAddress, Netif::mAddressCallback, Netif::mAddressCallbackContext, Netif::mMulticastAddresses, OT_ASSERT, OT_CHANGED_IP6_MULTICAST_SUBSCRIBED, OT_ERROR_ALREADY, OT_ERROR_NONE, OT_NOOP, LinkedListEntry< Type >::SetNext(), and VerifyOrExit.
UnsubscribeAllRoutersMulticast()
otError UnsubscribeAllRoutersMulticast (void)
This method unsubscribes the network interface to the link-local and realm-local all routers address.
Return values
OT_ERROR_NONE Successfully unsubscribed from the link-local and realm-local all routers address
OT_ERROR_NOT_FOUND The multicast addresses were not found.
References NetifMulticastAddress::GetNext(), Netif::kLinkLocalAllNodesMulticastAddress, Netif::kLinkLocalAllRoutersMulticastAddress, Netif::kMulticastPrefixLength, Netif::mAddressCallback, Netif::mAddressCallbackContext, Netif::mMulticastAddresses, OT_CHANGED_IP6_MULTICAST_UNSUBSCRIBED, OT_NOOP, LinkedListEntry< Type >::SetNext(), SuccessOrExit, and VerifyOrExit.
Referenced by ThreadNetif::Down().
GetMulticastAddresses()
const NetifMulticastAddress* GetMulticastAddresses (void) const inline
This method returns a pointer to the list of multicast addresses.
Returns
A pointer to the list of multicast addresses.
SubscribeMulticast()
otError SubscribeMulticast (NetifMulticastAddress & aAddress)
This method subscribes the network interface to a multicast address.
Parameters
[in] aAddress A reference to the multicast address.
Return values
OT_ERROR_NONE Successfully subscribed to aAddress.
OT_ERROR_ALREADY The multicast address is already subscribed.
References Netif::kMulticastPrefixLength, otNetifMulticastAddress::mAddress, Netif::mAddressCallback, Netif::mAddressCallbackContext, Netif::mMulticastAddresses, OT_CHANGED_IP6_MULTICAST_SUBSCRIBED, OT_NOOP, SuccessOrExit, and VerifyOrExit.
UnsubscribeMulticast()
otError UnsubscribeMulticast (const NetifMulticastAddress & aAddress)
This method unsubscribes the network interface to a multicast address.
Parameters
[in] aAddress A reference to the multicast address.
Return values
OT_ERROR_NONE Successfully unsubscribed aAddress.
OT_ERROR_NOT_FOUND The multicast address was not found.
References Netif::kMulticastPrefixLength, otNetifMulticastAddress::mAddress, Netif::mAddressCallback, Netif::mAddressCallbackContext, Netif::mMulticastAddresses, OT_CHANGED_IP6_MULTICAST_UNSUBSCRIBED, OT_NOOP, SuccessOrExit, and VerifyOrExit.
GetNextExternalMulticast()
otError GetNextExternalMulticast (uint8_t & aIterator, Address & aAddress) const
This method provides the next external multicast address that the network interface subscribed. It is used to iterate through the entries of the external multicast address table.
Parameters
[in,out] aIterator A reference to the iterator context. To get the first external multicast address, it should be set to 0.
[out] aAddress A reference where to place the external multicast address.
Return values
OT_ERROR_NONE Successfully found the next external multicast address.
OT_ERROR_NOT_FOUND No subsequent external multicast address.
References ExitNow, NetifMulticastAddress::GetAddress(), NetifMulticastAddress::IsInUse(), Netif::mExtMulticastAddresses, OT_ARRAY_LENGTH, OT_ERROR_NONE, OT_ERROR_NOT_FOUND, OT_NOOP, and VerifyOrExit.
SubscribeExternalMulticast()
otError SubscribeExternalMulticast (const Address & aAddress)
This method subscribes the network interface to the external (to OpenThread) multicast address.
Parameters
[in] aAddress A reference to the multicast address.
Return values
OT_ERROR_NONE Successfully subscribed to aAddress.
OT_ERROR_ALREADY The multicast address is already subscribed.
OT_ERROR_INVALID_ARGS The address indicated by aAddress is an internal multicast address.
OT_ERROR_NO_BUFS The maximum number of allowed external multicast addresses are already added.
References ExitNow, NetifMulticastAddress::GetNext(), NetifMulticastAddress::IsInUse(), Netif::IsMulticastSubscribed(), Netif::kLinkLocalAllRoutersMulticastAddress, otNetifMulticastAddress::mAddress, Netif::mExtMulticastAddresses, Netif::mMulticastAddresses, OT_ARRAY_END, OT_CHANGED_IP6_MULTICAST_SUBSCRIBED, OT_ERROR_ALREADY, OT_ERROR_INVALID_ARGS, OT_ERROR_NO_BUFS, OT_ERROR_NONE, and VerifyOrExit.
UnsubscribeExternalMulticast()
otError UnsubscribeExternalMulticast (const Address & aAddress)
This method unsubscribes the network interface to the external (to OpenThread) multicast address.
Parameters
[in] aAddress A reference to the multicast address.
Return values
OT_ERROR_NONE Successfully unsubscribed to the unicast address.
OT_ERROR_INVALID_ARGS The address indicated by aAddress is an internal address.
OT_ERROR_NOT_FOUND The multicast address was not found.
References NetifMulticastAddress::GetAddress(), NetifMulticastAddress::GetNext(), NetifMulticastAddress::MarkAsNotInUse(), Netif::mExtMulticastAddresses, Netif::mMulticastAddresses, OT_ARRAY_END, OT_CHANGED_IP6_MULTICAST_UNSUBSCRIBED, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, OT_ERROR_NOT_FOUND, and VerifyOrExit.
Referenced by Netif::UnsubscribeAllExternalMulticastAddresses().
UnsubscribeAllExternalMulticastAddresses()
void UnsubscribeAllExternalMulticastAddresses (void)
This method unsubscribes the network interface from all previously added external (to OpenThread) multicast addresses.
References Netif::mExtMulticastAddresses, OT_ARRAY_END, and Netif::UnsubscribeExternalMulticast().
Referenced by ThreadNetif::Down().
IsMulticastPromiscuousEnabled()
bool IsMulticastPromiscuousEnabled (void) const inline
This method checks if multicast promiscuous mode is enabled on the network interface.
Return values
TRUE If the multicast promiscuous mode is enabled.
FALSE If the multicast promiscuous mode is disabled.
Referenced by Ip6::HandleDatagram().
SetMulticastPromiscuous()
void SetMulticastPromiscuous (bool aEnabled) inline
This method enables multicast promiscuous mode on the network interface.
Parameters
[in] aEnabled TRUE if Multicast Promiscuous mode is enabled, FALSE otherwise.
SubscribeAllNodesMulticast()
otError SubscribeAllNodesMulticast (void) protected
This method subscribes the network interface to the realm-local all MPL forwarders, link-local, and realm-local all nodes address.
Return values
OT_ERROR_NONE Successfully subscribed to all addresses.
OT_ERROR_ALREADY The multicast addresses are already subscribed.
References NetifMulticastAddress::GetNext(), Netif::kLinkLocalAllNodesMulticastAddress, Netif::kMulticastPrefixLength, Netif::mAddressCallback, Netif::mAddressCallbackContext, Netif::mMulticastAddresses, OT_CHANGED_IP6_MULTICAST_SUBSCRIBED, OT_ERROR_ALREADY, OT_ERROR_NONE, OT_NOOP, and VerifyOrExit.
Referenced by ThreadNetif::Up().
UnsubscribeAllNodesMulticast()
otError UnsubscribeAllNodesMulticast (void) protected
This method unsubscribes the network interface from the realm-local all MPL forwarders, link-local and realm-local all nodes address.
Note
This method MUST be called after UnsubscribeAllRoutersMulticast() or its behavior is undefined
Return values
OT_ERROR_NONE Successfully unsubscribed from all addresses.
OT_ERROR_NOT_FOUND The multicast addresses were not found.
References NetifMulticastAddress::GetNext(), Netif::kLinkLocalAllNodesMulticastAddress, Netif::kMulticastPrefixLength, Netif::kRealmLocalAllRoutersMulticastAddress, Netif::mAddressCallback, Netif::mAddressCallbackContext, Netif::mMulticastAddresses, OT_ASSERT, OT_CHANGED_IP6_MULTICAST_UNSUBSCRIBED, OT_ERROR_NONE, OT_NOOP, LinkedListEntry< Type >::SetNext(), SuccessOrExit, and VerifyOrExit.
Referenced by ThreadNetif::Down().
Friends And Related Function Documentation
Ip6
friend class Ip6 friend
Address
friend class Address friend
Field Documentation
mUnicastAddresses
LinkedList<NetifUnicastAddress> mUnicastAddresses private
Referenced by Netif::AddExternalUnicastAddress(), Netif::AddUnicastAddress(), Netif::IsUnicastAddress(), Netif::RemoveExternalUnicastAddress(), and Netif::RemoveUnicastAddress().
mMulticastAddresses
LinkedList<NetifMulticastAddress> mMulticastAddresses private
Referenced by Netif::IsMulticastSubscribed(), Netif::SubscribeAllNodesMulticast(), Netif::SubscribeAllRoutersMulticast(), Netif::SubscribeExternalMulticast(), Netif::SubscribeMulticast(), Netif::UnsubscribeAllNodesMulticast(), Netif::UnsubscribeAllRoutersMulticast(), Netif::UnsubscribeExternalMulticast(), and Netif::UnsubscribeMulticast().
mMulticastPromiscuous
bool mMulticastPromiscuous private
mAddressCallback
otIp6AddressCallback mAddressCallback private
Referenced by Netif::AddUnicastAddress(), Netif::RemoveUnicastAddress(), Netif::SetAddressCallback(), Netif::SubscribeAllNodesMulticast(), Netif::SubscribeAllRoutersMulticast(), Netif::SubscribeMulticast(), Netif::UnsubscribeAllNodesMulticast(), Netif::UnsubscribeAllRoutersMulticast(), and Netif::UnsubscribeMulticast().
mAddressCallbackContext
void* mAddressCallbackContext private
Referenced by Netif::AddUnicastAddress(), Netif::RemoveUnicastAddress(), Netif::SetAddressCallback(), Netif::SubscribeAllNodesMulticast(), Netif::SubscribeAllRoutersMulticast(), Netif::SubscribeMulticast(), Netif::UnsubscribeAllNodesMulticast(), Netif::UnsubscribeAllRoutersMulticast(), and Netif::UnsubscribeMulticast().
mExtUnicastAddresses
NetifUnicastAddress mExtUnicastAddresses[OPENTHREAD_CONFIG_IP6_MAX_EXT_UCAST_ADDRS] private
Referenced by Netif::AddExternalUnicastAddress(), Netif::Netif(), Netif::RemoveAllExternalUnicastAddresses(), and Netif::RemoveExternalUnicastAddress().
mExtMulticastAddresses
NetifMulticastAddress mExtMulticastAddresses[OPENTHREAD_CONFIG_IP6_MAX_EXT_MCAST_ADDRS] private
Referenced by Netif::GetNextExternalMulticast(), Netif::Netif(), Netif::SubscribeExternalMulticast(), Netif::UnsubscribeAllExternalMulticastAddresses(), and Netif::UnsubscribeExternalMulticast().
kRealmLocalAllMplForwardersMulticastAddress
const otNetifMulticastAddress kRealmLocalAllMplForwardersMulticastAddress static private
Initial value:
= {
    {{{0xff, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xfc}}},
    NULL}
Referenced by Address::GetRealmLocalAllMplForwarders().
kLinkLocalAllNodesMulticastAddress
const otNetifMulticastAddress kLinkLocalAllNodesMulticastAddress static private
Initial value:
= {
    {{{0xff, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01}}},
    &Netif::kRealmLocalAllNodesMulticastAddress}
Referenced by Address::GetLinkLocalAllNodesMulticast(), Netif::SubscribeAllNodesMulticast(), Netif::SubscribeAllRoutersMulticast(), Netif::UnsubscribeAllNodesMulticast(), and Netif::UnsubscribeAllRoutersMulticast().
kRealmLocalAllNodesMulticastAddress
const otNetifMulticastAddress kRealmLocalAllNodesMulticastAddress static private
Initial value:
= {
    {{{0xff, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01}}},
    &Netif::kRealmLocalAllMplForwardersMulticastAddress}
Referenced by Address::GetRealmLocalAllNodesMulticast().
kLinkLocalAllRoutersMulticastAddress
const otNetifMulticastAddress kLinkLocalAllRoutersMulticastAddress static private
Initial value:
= {
    {{{0xff, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02}}},
    &Netif::kRealmLocalAllRoutersMulticastAddress}
Referenced by Address::GetLinkLocalAllRoutersMulticast(), Netif::SubscribeAllRoutersMulticast(), Netif::SubscribeExternalMulticast(), and Netif::UnsubscribeAllRoutersMulticast().
kRealmLocalAllRoutersMulticastAddress
const otNetifMulticastAddress kRealmLocalAllRoutersMulticastAddress static private
Initial value:
= {
    {{{0xff, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02}}},
    &Netif::kLinkLocalAllNodesMulticastAddress}
Referenced by Address::GetRealmLocalAllRoutersMulticast(), Netif::SubscribeAllRoutersMulticast(), and Netif::UnsubscribeAllNodesMulticast().
The documentation for this class was generated from the following files:
netif.hpp
core/net/netif.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale