OpenThread: NetifMulticastAddress Class Reference
NetifMulticastAddress Class Reference
Core-ipv6 » Network Interfaces
#include <netif.hpp>
Public Member Functions
void Clear (void)
const Address & GetAddress (void) const
Address & GetAddress (void)
const NetifMulticastAddress * GetNext (void) const
NetifMulticastAddress * GetNext (void)
Public Member Functions inherited from LinkedListEntry< NetifMulticastAddress >
const NetifMulticastAddress * GetNext (void) const
NetifMulticastAddress * GetNext (void)
void SetNext (NetifMulticastAddress *aNext)
Private Member Functions
bool IsInUse (void) const
void MarkAsNotInUse (void)
Friends
class Netif
Additional Inherited Members
Data Fields inherited from otNetifMulticastAddress
otIp6Address mAddress
The IPv6 multicast address.
const struct otNetifMulticastAddress * mNext
A pointer to the next network interface multicast address.
Detailed Description
This class implements an IPv6 network interface multicast address.
Member Function Documentation
Clear()
void Clear (void) inline
This method clears the object (setting all fields to zero).
Referenced by Mle::Mle().
GetAddress() [1/2]
const Address& GetAddress (void) const inline
This method returns the multicast address.
Returns
The multicast address.
References otNetifAddress::mAddress.
Referenced by Mle::ApplyMeshLocalPrefix(), Netif::GetNextExternalMulticast(), Mle::Mle(), and Netif::UnsubscribeExternalMulticast().
GetAddress() [2/2]
Address& GetAddress (void) inline
This method returns the multicast address.
Returns
The multicast address.
References otNetifAddress::mAddress.
GetNext() [1/2]
const NetifMulticastAddress* GetNext (void) const inline
This method returns the next multicast address subscribed to the interface.
Returns
A pointer to the next multicast address.
References otNetifAddress::mNext.
Referenced by Netif::SubscribeAllNodesMulticast(), Netif::SubscribeAllRoutersMulticast(), Netif::SubscribeExternalMulticast(), Netif::UnsubscribeAllNodesMulticast(), Netif::UnsubscribeAllRoutersMulticast(), and Netif::UnsubscribeExternalMulticast().
GetNext() [2/2]
NetifMulticastAddress* GetNext (void) inline
This method returns the next multicast address subscribed to the interface.
Returns
A pointer to the next multicast address.
References otNetifAddress::mNext.
IsInUse()
bool IsInUse (void) const inline private
References LinkedListEntry< NetifUnicastAddress >::GetNext().
Referenced by Netif::GetNextExternalMulticast(), and Netif::SubscribeExternalMulticast().
MarkAsNotInUse()
void MarkAsNotInUse (void) inline private
References otNetifAddress::mNext.
Referenced by Netif::UnsubscribeExternalMulticast().
Friends And Related Function Documentation
Netif
friend class Netif friend
The documentation for this class was generated from the following file:
netif.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale