OpenThread: Slaac Class Reference
Slaac Class Reference
Core-slaac-address
#include <slaac_address.hpp>
Data Structures
struct IidSecretKey
Public Types
enum { kIidSecretKeySize = 32 }
Public Member Functions
void Disable (void)
void Enable (void)
otError GenerateIid (Ip6::NetifUnicastAddress &aAddress, uint8_t *aNetworkId=NULL, uint8_t aNetworkIdLength=0, uint8_t *aDadCounter=NULL) const
bool IsEnabled (void) const
void SetFilter (otIp6SlaacPrefixFilter aFilter)
Slaac (Instance &aInstance)
Public Member Functions inherited from InstanceLocator
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Private Types
enum { kMaxIidCreationAttempts = 256 }
enum { kModeNone = 0x0, kModeAdd = 1 << 0, kModeRemove = 1 << 1 }
typedef uint8_t UpdateMode
Private Member Functions
void GetIidSecretKey (IidSecretKey &aKey) const
void HandleStateChanged (otChangedFlags aFlags)
bool ShouldFilter (const otIp6Prefix &aPrefix) const
void Update (UpdateMode aMode)
Static Private Member Functions
static void HandleStateChanged (Notifier::Callback &aCallback, otChangedFlags aFlags)
Private Attributes
Ip6::NetifUnicastAddress mAddresses [OPENTHREAD_CONFIG_IP6_SLAAC_NUM_ADDRESSES]
bool mEnabled
otIp6SlaacPrefixFilter mFilter
Notifier::Callback mNotifierCallback
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Detailed Description
This class implements the SLAAC utility for Thread protocol.
Member Typedef Documentation
UpdateMode
typedef uint8_t UpdateMode private
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
kIidSecretKeySize
Number of bytes in secret key for generating semantically opaque IID.
anonymous enum
anonymous enum private
Enumerator
kMaxIidCreationAttempts
anonymous enum
anonymous enum private
Enumerator
kModeNone
kModeAdd
kModeRemove
Constructor & Destructor Documentation
Slaac()
Slaac (Instance & aInstance) explicit
This constructor initializes the SLAAC manager object.
Note that SLAAC module starts enabled.
Parameters
[in] aInstance A reference to the OpenThread instance.
Member Function Documentation
Enable()
void Enable (void)
This method enables the SLAAC module.
When enabled, new SLAAC addresses are generated and added from on-mesh prefixes in network data.
Disable()
void Disable (void)
This method disables the SLAAC module.
When disabled, any previously added SLAAC address by this module is removed.
IsEnabled()
bool IsEnabled (void) const inline
This method indicates whether SLAAC module is enabled or not.
Return values
TRUE SLAAC module is enabled.
FALSE SLAAC module is disabled.
References Slaac::GenerateIid(), Slaac::mEnabled, and Slaac::SetFilter().
SetFilter()
void SetFilter (otIp6SlaacPrefixFilter aFilter)
This method sets a SLAAC prefix filter handler.
The handler is invoked by SLAAC module when it is about to add a SLAAC address based on a prefix. The return boolean value from handler determines whether the address is filtered or added (TRUE to filter the address, FALSE to add address).
The filter can be set to NULL to disable filtering (i.e., allow SLAAC addresses for all prefixes).
Referenced by Slaac::IsEnabled().
GenerateIid()
otError GenerateIid (Ip6::NetifUnicastAddress & aAddress, uint8_t * aNetworkId = NULL, uint8_t aNetworkIdLength = 0, uint8_t * aDadCounter = NULL) const
This method generates the IID of an IPv6 address.
Parameters
[in,out] aAddress A reference to the address that will be filled with the IID generated. Note the prefix of the address must already be filled and will be used to generate the IID.
[in] aNetworkId A pointer to a byte array of Network_ID to generate IID.
[in] aNetworkIdLength The size of array aNetworkId.
[in,out] aDadCounter A pointer to the DAD_Counter that is employed to resolve Duplicate Address Detection connflicts.
Return values
OT_ERROR_NONE If successfully generated the IID.
OT_ERROR_FAILED If no valid IID was generated.
Referenced by Slaac::IsEnabled().
ShouldFilter()
bool ShouldFilter (const otIp6Prefix & aPrefix) const private
Update()
void Update (UpdateMode aMode) private
GetIidSecretKey()
void GetIidSecretKey (IidSecretKey & aKey) const private
HandleStateChanged() [1/2]
static void HandleStateChanged (Notifier::Callback & aCallback, otChangedFlags aFlags) static private
HandleStateChanged() [2/2]
void HandleStateChanged (otChangedFlags aFlags) private
Field Documentation
mEnabled
bool mEnabled private
Referenced by Slaac::IsEnabled().
mFilter
otIp6SlaacPrefixFilter mFilter private
mNotifierCallback
Notifier::Callback mNotifierCallback private
mAddresses
Ip6::NetifUnicastAddress mAddresses[OPENTHREAD_CONFIG_IP6_SLAAC_NUM_ADDRESSES] private
The documentation for this class was generated from the following file:
slaac_address.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale