OpenThread: ActiveDataset Class Reference
ActiveDataset Class Reference
#include <dataset_manager.hpp>
Public Member Functions
ActiveDataset (Instance &aInstance)
void Clear (void)
bool IsPartiallyComplete (void) const
void Save (const Dataset &aDataset)
otError Save (const Timestamp &aTimestamp, const Message &aMessage, uint16_t aOffset, uint8_t aLength)
otError Save (const otOperationalDataset &aDataset)
Public Member Functions inherited from DatasetManager
otError ApplyConfiguration (void) const
int Compare (const Timestamp &aTimestamp) const
otError GetChannelMask (Mac::ChannelMask &aChannelMask) const
const Timestamp * GetTimestamp (void) const
void HandleDetach (void)
otError Read (Dataset &aDataset) const
otError Read (otOperationalDataset &aDataset) const
otError Restore (void)
otError SendGetRequest (const otOperationalDatasetComponents &aDatasetComponents, const uint8_t *aTlvTypes, uint8_t aLength, const otIp6Address *aAddress) const
otError SendSetRequest (const otOperationalDataset &aDataset, const uint8_t *aTlvs, uint8_t aLength)
Public Member Functions inherited from InstanceLocator
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Private Member Functions
void HandleGet (Coap::Message &aMessage, const Ip6::MessageInfo &aMessageInfo) const
void HandleTimer (void)
Static Private Member Functions
static void HandleGet (void *aContext, otMessage *aMessage, const otMessageInfo *aMessageInfo)
static void HandleTimer (Timer &aTimer)
Private Attributes
Coap::Resource mResourceGet
Additional Inherited Members
Protected Member Functions inherited from DatasetManager
void Clear (void)
DatasetManager (Instance &aInstance, Dataset::Type aType, const char *aUriGet, const char *aUriSet, TimerMilli::Handler aTimerHandler)
void HandleGet (const Coap::Message &aMessage, const Ip6::MessageInfo &aMessageInfo) const
void HandleNetworkUpdate (void)
void HandleTimer (void)
otError Save (const Dataset &aDataset)
otError Save (const otOperationalDataset &aDataset)
otError Save (const Timestamp &aTimestamp, const Message &aMessage, uint16_t aOffset, uint8_t aLength)
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Attributes inherited from DatasetManager
DatasetLocal mLocal
Timestamp mTimestamp
bool mTimestampValid: 1
ot::MeshCoP::DatasetManager::DatasetTlv OT_TOOL_PACKED_END
Constructor & Destructor Documentation
ActiveDataset()
ActiveDataset (Instance & aInstance) explicit
Constructor.
Parameters
[in] aInstance A reference to the OpenThread instance.
References ActiveDataset::mResourceGet.
Member Function Documentation
IsPartiallyComplete()
bool IsPartiallyComplete (void) const
This method indicates whether the Active Dataset is partially complete.
This method is primarily used to determine whether a user has supplied a partial Active Dataset for use with joining a network.
Return values
TRUE if an Active Dataset is saved but does not include an Active Timestamp.
FALSE if an Active Dataset is not saved or does include an Active Timestamp.
References DatasetLocal::IsSaved(), DatasetManager::mLocal, and DatasetManager::mTimestampValid.
Clear()
void Clear (void) inline
This method clears the Active Operational Dataset.
References DatasetManager::Clear().
Save() [1/3]
void Save (const Dataset & aDataset) inline
This method saves the Operational Dataset in non-volatile memory.
This method also reconfigures the Thread interface.
Parameters
[in] aDataset The Operational Dataset.
References DatasetManager::Save().
Save() [2/3]
otError Save (const Timestamp & aTimestamp, const Message & aMessage, uint16_t aOffset, uint8_t aLength)
This method sets the Operational Dataset for the partition.
This method also reconfigures the Thread interface. This method also updates the non-volatile version if the partition's Operational Dataset is newer.
Parameters
[in] aTimestamp The timestamp for the Operational Dataset.
[in] aMessage The message buffer.
[in] aOffset The offset where the Operational Dataset begins.
[in] aLength The length of the Operational Dataset.
References DatasetLocal::GetType(), DatasetManager::mLocal, OT_ERROR_NONE, DatasetManager::Save(), and SuccessOrExit.
Save() [3/3]
otError Save (const otOperationalDataset & aDataset) inline
This method sets the Operational Dataset in non-volatile memory.
Parameters
[in] aDataset The Operational Dataset.
References DatasetManager::HandleTimer(), and DatasetManager::Save().
HandleTimer() [1/2]
void HandleTimer (Timer & aTimer) static private
References OwnerLocator::GetOwner(), and ActiveDataset::HandleTimer().
HandleTimer() [2/2]
void HandleTimer (void) inline private
References DatasetManager::HandleGet(), and DatasetManager::HandleTimer().
Referenced by ActiveDataset::HandleTimer().
HandleGet() [1/2]
void HandleGet (void * aContext, otMessage * aMessage, const otMessageInfo * aMessageInfo) static private
HandleGet() [2/2]
void HandleGet (Coap::Message & aMessage, const Ip6::MessageInfo & aMessageInfo) const private
References DatasetManager::HandleGet().
Field Documentation
mResourceGet
Coap::Resource mResourceGet private
Referenced by ActiveDataset::ActiveDataset().
The documentation for this class was generated from the following files:
dataset_manager.hpp
dataset_manager.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale