OpenThread: Tasklet Class Reference
Tasklet Class Reference
Core-tasklet
#include <tasklet.hpp>
Public Types
typedef void(* Handler) (Tasklet &aTasklet)
Public Member Functions
bool IsPosted (void) const
otError Post (void)
Tasklet (Instance &aInstance, Handler aHandler, void *aOwner)
Public Member Functions inherited from InstanceLocator
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Public Member Functions inherited from OwnerLocator
template<typename OwnerType >
OwnerType & GetOwner (void)
Private Member Functions
void RunTask (void)
Private Attributes
Handler mHandler
Tasklet * mNext
Friends
class TaskletScheduler
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from OwnerLocator
OwnerLocator (void *aOwner)
Detailed Description
This class is used to represent a tasklet.
Member Typedef Documentation
Handler
typedef void(* Handler) (Tasklet &aTasklet)
This function pointer is called when the tasklet is run.
Parameters
[in] aTasklet A reference to the tasklet being run.
Constructor & Destructor Documentation
Tasklet()
Tasklet (Instance & aInstance, Handler aHandler, void * aOwner)
This constructor creates a tasklet instance.
Parameters
[in] aInstance A reference to the OpenThread instance object.
[in] aHandler A pointer to a function that is called when the tasklet is run.
[in] aOwner A pointer to owner of this Tasklet object.
Member Function Documentation
Post()
otError Post (void)
This method puts the tasklet on the tasklet scheduler run queue.
References Tasklet::IsPosted(), OT_ERROR_ALREADY, OT_ERROR_NONE, and VerifyOrExit.
Referenced by NcpBase::CommandHandler_RESET(), Ip6::EnqueueDatagram(), MeshForwarder::HandleDiscoverTimer(), MeshForwarder::HandleSentFrame(), NcpBase::Log(), NcpBase::NcpBase(), Mac::SetRxOnWhenIdle(), Notifier::Signal(), Mac::StartOperation(), and NcpBase::StreamWrite().
IsPosted()
bool IsPosted (void) const inline
This method indicates whether the tasklet is posted or not.
Return values
TRUE The tasklet is posted.
FALSE The tasklet is not posted.
References Tasklet::mNext.
Referenced by Tasklet::Post().
RunTask()
void RunTask (void) inline private
References Tasklet::mHandler.
Referenced by TaskletScheduler::ProcessQueuedTasklets().
Friends And Related Function Documentation
TaskletScheduler
friend class TaskletScheduler friend
Field Documentation
mHandler
Handler mHandler private
Referenced by Tasklet::RunTask().
mNext
Tasklet* mNext private
Referenced by Tasklet::IsPosted(), TaskletScheduler::PostTasklet(), and TaskletScheduler::ProcessQueuedTasklets().
The documentation for this class was generated from the following files:
tasklet.hpp
tasklet.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale