OpenThread: RandomManager::CryptoCtrDrbg Class Reference
RandomManager::CryptoCtrDrbg Class Reference
Public Member Functions
void Deinit (void)
otError FillBuffer (uint8_t *aBuffer, uint16_t aSize)
mbedtls_ctr_drbg_context * GetContext (void)
void Init (void)
Private Attributes
mbedtls_ctr_drbg_context mCtrDrbg
Member Function Documentation
Init()
void Init (void)
References RandomManager::GetMbedTlsEntropyContext().
Referenced by RandomManager::RandomManager().
Deinit()
void Deinit (void)
Referenced by RandomManager::~RandomManager().
FillBuffer()
otError FillBuffer (uint8_t * aBuffer, uint16_t aSize)
References MbedTls::MapError().
Referenced by RandomManager::CryptoFillBuffer().
GetContext()
mbedtls_ctr_drbg_context* GetContext (void) inline
Referenced by RandomManager::GetMbedTlsCtrDrbgContext().
Field Documentation
mCtrDrbg
mbedtls_ctr_drbg_context mCtrDrbg private
The documentation for this class was generated from the following files:
random_manager.hpp
random_manager.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale