OpenThread: Udp Class Reference
Udp Class Reference
Core-udp
#include <udp6.hpp>
Public Member Functions
otError AddReceiver (UdpReceiver &aReceiver)
void AddSocket (UdpSocket &aSocket)
uint16_t GetEphemeralPort (void)
otError HandleMessage (Message &aMessage, MessageInfo &aMessageInfo)
void HandlePayload (Message &aMessage, MessageInfo &aMessageInfo)
Message * NewMessage (uint16_t aReserved, const otMessageSettings *aSettings=NULL)
otError RemoveReceiver (UdpReceiver &aReceiver)
void RemoveSocket (UdpSocket &aSocket)
otError SendDatagram (Message &aMessage, MessageInfo &aMessageInfo, uint8_t aIpProto)
Udp (Instance &aInstance)
void UpdateChecksum (Message &aMessage, uint16_t aChecksum)
Public Member Functions inherited from InstanceLocator
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Private Types
enum { kDynamicPortMin = 49152, kDynamicPortMax = 65535 }
Private Attributes
uint16_t mEphemeralPort
LinkedList< UdpReceiver > mReceivers
LinkedList< UdpSocket > mSockets
Friends
class UdpSocket
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Detailed Description
This class implements core UDP message handling.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
kDynamicPortMin
Service Name and Transport Protocol Port Number Registry.
kDynamicPortMax
Service Name and Transport Protocol Port Number Registry.
Constructor & Destructor Documentation
Udp()
Udp (Instance & aInstance) explicit
This constructor initializes the object.
Parameters
[in] aIp6 A reference to OpenThread instance.
Member Function Documentation
AddReceiver()
otError AddReceiver (UdpReceiver & aReceiver)
This method adds a UDP receiver.
Parameters
[in] aReceiver A reference to the UDP receiver.
Return values
OT_ERROR_NONE Successfully added the UDP receiver.
OT_ERROR_ALREADY The UDP receiver was already added.
References Udp::mReceivers.
RemoveReceiver()
otError RemoveReceiver (UdpReceiver & aReceiver)
This method removes a UDP receiver.
Parameters
[in] aReceiver A reference to the UDP receiver.
Return values
OT_ERROR_NONE Successfully removed the UDP receiver.
OT_ERROR_NOT_FOUND The UDP receiver was not added.
References Udp::mReceivers, LinkedListEntry< Type >::SetNext(), and SuccessOrExit.
AddSocket()
void AddSocket (UdpSocket & aSocket)
This method adds a UDP socket.
Parameters
[in] aSocket A reference to the UDP socket.
References Udp::mSockets.
RemoveSocket()
void RemoveSocket (UdpSocket & aSocket)
This method removes a UDP socket.
Parameters
[in] aSocket A reference to the UDP socket.
References Udp::mSockets, LinkedListEntry< Type >::SetNext(), and SuccessOrExit.
GetEphemeralPort()
uint16_t GetEphemeralPort (void)
This method returns a new ephemeral port.
Returns
A new ephemeral port.
References Udp::kDynamicPortMax, Udp::kDynamicPortMin, and Udp::mEphemeralPort.
NewMessage()
Message * NewMessage (uint16_t aReserved, const otMessageSettings * aSettings = NULL)
This method returns a new UDP message with sufficient header space reserved.
Parameters
[in] aReserved The number of header bytes to reserve after the UDP header.
[in] aPriority The priority of the message.
Returns
A pointer to the message or NULL if no buffers are available.
SendDatagram()
otError SendDatagram (Message & aMessage, MessageInfo & aMessageInfo, uint8_t aIpProto)
This method sends an IPv6 datagram.
Parameters
[in] aMessage A reference to the message.
[in] aMessageInfo A reference to the message info associated with aMessage.
[in] aIpProto The Internet Protocol value.
Return values
OT_ERROR_NONE Successfully enqueued the message into an output interface.
OT_ERROR_NO_BUFS Insufficient available buffer to add the IPv6 headers.
References Message::GetLength(), MessageInfo::GetPeerAddr(), MessageInfo::IsHostInterface(), otMessageInfo::mPeerPort, otMessageInfo::mSockPort, OT_ERROR_NO_ROUTE, OT_ERROR_NONE, Message::Prepend(), UdpHeader::SetChecksum(), UdpHeader::SetDestinationPort(), UdpHeader::SetLength(), Message::SetOffset(), UdpHeader::SetSourcePort(), SuccessOrExit, and VerifyOrExit.
HandleMessage()
otError HandleMessage (Message & aMessage, MessageInfo & aMessageInfo)
This method handles a received UDP message.
Parameters
[in] aMessage A reference to the UDP message to process.
[in] aMessageInfo A reference to the message info associated with aMessage.
Return values
OT_ERROR_NONE Successfully processed the UDP message.
OT_ERROR_DROP Could not fully process the UDP message.
References Ip6::ComputePseudoheaderChecksum(), UdpHeader::GetDestinationPort(), InstanceLocator::GetInstance(), Message::GetLength(), Message::GetOffset(), MessageInfo::GetPeerAddr(), MessageInfo::GetSockAddr(), UdpHeader::GetSourcePort(), Udp::HandlePayload(), ot::Ip6::kProtoUdp, Message::MoveOffset(), otMessageInfo::mPeerPort, Udp::mReceivers, otMessageInfo::mSockPort, OT_ERROR_DROP, OT_ERROR_NONE, OT_ERROR_PARSE, OT_NOOP, Message::Read(), Message::UpdateChecksum(), and VerifyOrExit.
Referenced by Ip6::HandlePayload().
HandlePayload()
void HandlePayload (Message & aMessage, MessageInfo & aMessageInfo)
This method handles a received UDP message with offset set to the payload.
Parameters
[in] aMessage A reference to the UDP message to process.
[in] aMessageInfo A reference to the message info associated with aMessage.
References Message::GetOffset(), MessageInfo::GetPeerAddr(), MessageInfo::GetPeerPort(), MessageInfo::GetSockAddr(), MessageInfo::GetSockPort(), Address::IsMulticast(), Udp::mSockets, OT_ASSERT, and Message::RemoveHeader().
Referenced by Udp::HandleMessage().
UpdateChecksum()
void UpdateChecksum (Message & aMessage, uint16_t aChecksum)
This method updates the UDP checksum.
Parameters
[in] aMessage A reference to the UDP message.
[in] aChecksum The pseudo-header checksum value.
References UdpHeader::GetChecksumOffset(), Message::GetLength(), Message::GetOffset(), ot::Encoding::BigEndian::HostSwap16(), Message::UpdateChecksum(), and Message::Write().
Referenced by Ip6::SendDatagram().
Friends And Related Function Documentation
UdpSocket
friend class UdpSocket friend
Field Documentation
mEphemeralPort
uint16_t mEphemeralPort private
Referenced by Udp::GetEphemeralPort().
mReceivers
LinkedList<UdpReceiver> mReceivers private
Referenced by Udp::AddReceiver(), Udp::HandleMessage(), and Udp::RemoveReceiver().
mSockets
LinkedList<UdpSocket> mSockets private
Referenced by Udp::AddSocket(), Udp::HandlePayload(), and Udp::RemoveSocket().
The documentation for this class was generated from the following files:
udp6.hpp
udp6.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale