OpenThread: TimerMilli Class Reference
TimerMilli Class Reference
Core-timer
#include <timer.hpp>
Public Member Functions
void FireAt (TimeMilli aFireTime)
void FireAtIfEarlier (TimeMilli aFireTime)
void Start (uint32_t aDelay)
void StartAt (TimeMilli sStartTime, uint32_t aDelay)
void Stop (void)
TimerMilli (Instance &aInstance, Handler aHandler, void *aOwner)
Public Member Functions inherited from Timer
Time GetFireTime (void) const
bool IsRunning (void) const
Timer (Instance &aInstance, Handler aHandler, void *aOwner)
Public Member Functions inherited from InstanceLocator
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Public Member Functions inherited from OwnerLocator
template<typename OwnerType >
OwnerType & GetOwner (void)
Public Member Functions inherited from LinkedListEntry< Timer >
const Timer * GetNext (void) const
Timer * GetNext (void)
void SetNext (Timer *aNext)
Static Public Member Functions
static TimeMilli GetNow (void)
Additional Inherited Members
Public Types inherited from Timer
typedef void(* Handler) (Timer &aTimer)
Static Public Attributes inherited from Timer
static const uint32_t kMaxDelay = (Time::kMaxDuration >> 1)
Protected Member Functions inherited from Timer
bool DoesFireBefore (const Timer &aSecondTimer, Time aNow)
void Fired (void)
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from OwnerLocator
OwnerLocator (void *aOwner)
Protected Attributes inherited from Timer
Time mFireTime
Handler mHandler
Timer * mNext
Detailed Description
This class implements the millisecond timer.
Constructor & Destructor Documentation
TimerMilli()
TimerMilli (Instance & aInstance, Handler aHandler, void * aOwner) inline
This constructor creates a millisecond timer instance.
Parameters
[in] aInstance A reference to the OpenThread instance.
[in] aHandler A pointer to a function that is called when the timer expires.
[in] aOwner A pointer to the owner of the TimerMilli object.
Member Function Documentation
Start()
void Start (uint32_t aDelay)
This method schedules the timer to fire after a given delay (in milliseconds) from now.
Parameters
[in] aDelay The delay in milliseconds. It must not be longer than kMaxDelay.
Referenced by Mle::BecomeChild(), SubMac::EnergyScan(), Mle::HandleAnnounce(), Mle::HandleAttachTimer(), TrickleTimer::HandleEndOfTimeInInterval(), MeshForwarder::HandleFragment(), PanIdQueryServer::HandleQuery(), EnergyScanServer::HandleRequest(), EnergyScanServer::HandleScanResult(), Mpl::HandleSeedSetTimer(), MeshForwarder::HandleSentFrame(), AnnounceSenderBase::HandleTimer(), DatasetManager::HandleTimer(), Mac::HandleTransmitDone(), SubMac::HandleTransmitStarted(), MeshForwarder::HandleUpdateTimer(), DatasetManager::Save(), Mle::ScheduleMessageTransmissionTimer(), AnnounceSenderBase::SendAnnounce(), SubMac::StartCsmaBackoff(), KeyManager::StartKeyRotationTimer(), TrickleTimer::StartNewInterval(), Mac::UpdateIdleMode(), and Mpl::UpdateSeedSet().
StartAt()
void StartAt (TimeMilli sStartTime, uint32_t aDelay)
This method schedules the timer to fire after a given delay (in milliseconds) from a given start time.
Parameters
[in] aStartTime The start time.
[in] aDelay The delay in milliseconds. It must not be longer than kMaxDelay.
References Timer::kMaxDelay, and OT_ASSERT.
Referenced by PendingDataset::HandleDelayTimer(), KeyManager::HandleKeyRotationTimer(), DataPollSender::ResetKeepAliveTimer(), SubMac::SampleRssi(), DataPollSender::ScheduleNextPoll(), and PendingDataset::StartDelayTimer().
FireAt()
void FireAt (TimeMilli aFireTime)
This method schedules the timer to fire at a given fire time.
Parameters
[in] aFireTime The fire time.
References Timer::mFireTime.
Referenced by Mle::HandleDelayedResponseTimer(), CoapBase::HandleRetransmissionTimer(), and ResponsesQueue::HandleTimer().
FireAtIfEarlier()
void FireAtIfEarlier (TimeMilli aFireTime)
This method (re-)schedules the timer with a given a fire time only if the timer is not running or the new given fire time is earlier than the current fire time.
Parameters
[in] aFireTime The fire time.
References Timer::IsRunning(), and Timer::mFireTime.
Referenced by Mle::AddDelayedResponse(), CoapBase::CopyAndEnqueueMessage(), and ResponsesQueue::EnqueueResponse().
Stop()
void Stop (void)
This method stops the timer.
Referenced by DatasetManager::Clear(), PendingDataset::Clear(), CoapBase::DequeueMessage(), SubMac::Disable(), MeshForwarder::HandleDiscoverComplete(), Mac::HandleReceivedFrame(), EnergyScanServer::HandleStateChanged(), SubMac::HandleTransmitDone(), Mac::PerformNextOperation(), DatasetManager::Restore(), Mle::ScheduleMessageTransmissionTimer(), DataPollSender::SendDataPoll(), Mac::SetRxOnWhenIdle(), Mle::SetStateChild(), Mle::SetStateDetached(), PendingDataset::StartDelayTimer(), Mac::StartOperation(), AnnounceSenderBase::Stop(), TrickleTimer::Stop(), MeshForwarder::Stop(), KeyManager::Stop(), and DataPollSender::StopPolling().
GetNow()
static TimeMilli GetNow (void) inline static
This static method returns the current time in milliseconds.
Returns
The current time in milliseconds.
References otPlatAlarmMilliGetNow().
Referenced by Mle::AddDelayedResponse(), Dataset::AppendMleDatasetTlv(), Mle::CheckReachability(), SubMac::EnergyScan(), ResponsesQueue::EnqueueResponse(), Mle::HandleAdvertisement(), Mle::HandleDelayedResponseTimer(), Mac::HandleReceivedFrame(), CoapBase::HandleRetransmissionTimer(), Mpl::HandleSeedSetTimer(), ResponsesQueue::HandleTimer(), DatasetLocal::Read(), DataPollSender::ResetKeepAliveTimer(), SubMac::SampleRssi(), DatasetLocal::Save(), DataPollSender::ScheduleNextPoll(), CoapBase::SendMessage(), Dataset::Set(), Dataset::SetFrom(), and Dataset::SetTlv().
The documentation for this class was generated from the following files:
timer.hpp
timer.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale