OpenThread: Leader Class Reference
Leader Class Reference
Core-netdata » Leader
#include <network_data_leader_ftd.hpp>
Data Structures
class ChangedFlags
Public Types
enum MatchMode { kMatchModeRloc16, kMatchModeRouterId }
Public Types inherited from NetworkData
enum { kMaxSize = 254 }
enum Type { kTypeLocal, kTypeLeader }
Public Member Functions
const ServiceTlv * FindServiceById (uint8_t aServiceId) const
uint32_t GetContextIdReuseDelay (void) const
void IncrementVersion (void)
void IncrementVersionAndStableVersion (void)
Leader (Instance &aInstance)
void RemoveBorderRouter (uint16_t aRloc16, MatchMode aMatchMode)
otError RemoveStaleChildEntries (Coap::ResponseHandler aHandler, void *aContext)
void Reset (void)
void SetContextIdReuseDelay (uint32_t aDelay)
void Start (void)
void Stop (void)
void UpdateContextsAfterReset (void)
Public Member Functions inherited from LeaderBase
otError GetBackboneRouterPrimary (BackboneRouter::BackboneRouterConfig &aConfig) const
CommissioningDataTlv * GetCommissioningData (void)
const CommissioningDataTlv * GetCommissioningData (void) const
MeshCoP::Tlv * GetCommissioningDataSubTlv (MeshCoP::Tlv::Type aType)
const MeshCoP::Tlv * GetCommissioningDataSubTlv (MeshCoP::Tlv::Type aType) const
otError GetContext (const Ip6::Address &aAddress, Lowpan::Context &aContext) const
otError GetContext (uint8_t aContextId, Lowpan::Context &aContext) const
otError GetRlocByContextId (uint8_t aContextId, uint16_t &aRloc16) const
otError GetServiceId (uint32_t aEnterpriseNumber, const uint8_t *aServiceData, uint8_t aServiceDataLength, bool aServerStable, uint8_t &aServiceId) const
uint8_t GetStableVersion (void) const
uint8_t GetVersion (void) const
bool IsJoiningEnabled (void) const
bool IsOnMesh (const Ip6::Address &aAddress) const
LeaderBase (Instance &aInstance)
void Reset (void)
otError RouteLookup (const Ip6::Address &aSource, const Ip6::Address &aDestination, uint8_t *aPrefixMatch, uint16_t *aRloc16) const
otError SendServerDataNotification (uint16_t aRloc16)
otError SetCommissioningData (const uint8_t *aValue, uint8_t aValueLength)
otError SetNetworkData (uint8_t aVersion, uint8_t aStableVersion, bool aStableOnly, const Message &aMessage, uint16_t aMessageOffset)
Public Member Functions inherited from NetworkData
void Clear (void)
bool ContainsExternalRoutes (const NetworkData &aCompare, uint16_t aRloc16) const
bool ContainsOnMeshPrefixes (const NetworkData &aCompare, uint16_t aRloc16) const
bool ContainsService (uint8_t aServiceId, uint16_t aRloc16) const
bool ContainsServices (const NetworkData &aCompare, uint16_t aRloc16) const
otError GetNetworkData (bool aStable, uint8_t *aData, uint8_t &aDataLength) const
otError GetNextExternalRoute (Iterator &aIterator, ExternalRouteConfig &aConfig) const
otError GetNextExternalRoute (Iterator &aIterator, uint16_t aRloc16, ExternalRouteConfig &aConfig) const
otError GetNextOnMeshPrefix (Iterator &aIterator, OnMeshPrefixConfig &aConfig) const
otError GetNextOnMeshPrefix (Iterator &aIterator, uint16_t aRloc16, OnMeshPrefixConfig &aConfig) const
otError GetNextServer (Iterator &aIterator, uint16_t &aRloc16) const
otError GetNextService (Iterator &aIterator, ServiceConfig &aConfig) const
otError GetNextService (Iterator &aIterator, uint16_t aRloc16, ServiceConfig &aConfig) const
otError GetNextServiceId (Iterator &aIterator, uint16_t aRloc16, uint8_t &aServiceId) const
NetworkData (Instance &aInstance, Type aType)
Public Member Functions inherited from InstanceLocator
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Private Types
enum { kMinContextId = 1, kNumContextIds = 15, kContextIdReuseDelay = 48 * 60 * 60, kStateUpdatePeriod = 60 * 1000 }
enum UpdateStatus { kTlvRemoved, kTlvUpdated }
Private Member Functions
otError AddBorderRouter (const BorderRouterTlv &aBorderRouter, PrefixTlv &aDstPrefix, ChangedFlags &aFlags)
otError AddHasRoute (const HasRouteTlv &aHasRoute, PrefixTlv &aDstPrefix, ChangedFlags &aChangedFlags)
otError AddPrefix (const PrefixTlv &aPrefix, ChangedFlags &aChangedFlags)
otError AddServer (const ServerTlv &aServer, ServiceTlv &aDstService, ChangedFlags &aChangedFlags)
otError AddService (const ServiceTlv &aService, ChangedFlags &aChangedFlags)
otError AllocateContextId (uint8_t &aConextId)
otError AllocateServiceId (uint8_t &aServiceId)
void FreeContextId (uint8_t aContextId)
void HandleCommissioningGet (Coap::Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
void HandleCommissioningSet (Coap::Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
void HandleServerData (Coap::Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
void HandleTimer (void)
void IncrementVersions (bool aIncludeStable)
void IncrementVersions (const ChangedFlags &aFlags)
otError RegisterNetworkData (uint16_t aRloc16, const uint8_t *aTlvs, uint8_t aTlvsLength)
void RemoveCommissioningData (void)
void RemoveContext (uint8_t aContextId)
void RemoveContext (PrefixTlv &aPrefix, uint8_t aContextId)
void RemoveRloc (uint16_t aRloc16, MatchMode aMatchMode, ChangedFlags &aChangedFlags)
void RemoveRloc (uint16_t aRloc16, MatchMode aMatchMode, const uint8_t *aExcludeTlvs, uint8_t aExcludeTlvsLength, ChangedFlags &aChangedFlags)
void RemoveRlocInBorderRouter (PrefixTlv &aPrefix, BorderRouterTlv &aBorderRouter, uint16_t aRloc16, MatchMode aMatchMode, const PrefixTlv *aExcludePrefix, ChangedFlags &aChangedFlags)
void RemoveRlocInHasRoute (PrefixTlv &aPrefix, HasRouteTlv &aHasRoute, uint16_t aRloc16, MatchMode aMatchMode, const PrefixTlv *aExcludePrefix, ChangedFlags &aChangedFlags)
void RemoveRlocInPrefix (PrefixTlv &aPrefix, uint16_t aRloc16, MatchMode aMatchMode, const PrefixTlv *aExcludePrefix, ChangedFlags &aChangedFlags)
void RemoveRlocInService (ServiceTlv &aService, uint16_t aRloc16, MatchMode aMatchMode, const ServiceTlv *aExcludeService, ChangedFlags &aChangedFlags)
void SendCommissioningGetResponse (const Coap::Message &aRequest, uint16_t aLength, const Ip6::MessageInfo &aMessageInfo)
void SendCommissioningSetResponse (const Coap::Message &aRequest, const Ip6::MessageInfo &aMessageInfo, MeshCoP::StateTlv::State aState)
void StartContextReuseTimer (uint8_t aContextId)
void StopContextReuseTimer (uint8_t aContextId)
UpdateStatus UpdatePrefix (PrefixTlv &aPrefix)
UpdateStatus UpdateService (ServiceTlv &aService)
UpdateStatus UpdateTlv (NetworkDataTlv &aTlv, const NetworkDataTlv *aSubTlvs)
Static Private Member Functions
static bool ContainsMatchingEntry (const PrefixTlv *aPrefix, bool aStable, const HasRouteEntry &aEntry)
static bool ContainsMatchingEntry (const HasRouteTlv *aHasRoute, const HasRouteEntry &aEntry)
static bool ContainsMatchingEntry (const PrefixTlv *aPrefix, bool aStable, const BorderRouterEntry &aEntry)
static bool ContainsMatchingEntry (const BorderRouterTlv *aBorderRouter, const BorderRouterEntry &aEntry)
static bool ContainsMatchingServer (const ServiceTlv *aService, const ServerTlv &aServer)
static void HandleCommissioningGet (void *aContext, otMessage *aMessage, const otMessageInfo *aMessageInfo)
static void HandleCommissioningSet (void *aContext, otMessage *aMessage, const otMessageInfo *aMessageInfo)
static void HandleServerData (void *aContext, otMessage *aMessage, const otMessageInfo *aMessageInfo)
static void HandleTimer (Timer &aTimer)
static bool RlocMatch (uint16_t aFirstRloc16, uint16_t aSecondRloc16, MatchMode aMatchMode)
static otError Validate (const uint8_t *aTlvs, uint8_t aTlvsLength, uint16_t aRloc16)
static otError ValidatePrefix (const PrefixTlv &aPrefix, uint16_t aRloc16)
static otError ValidateService (const ServiceTlv &aService, uint16_t aRloc16)
Private Attributes
Coap::Resource mCommissioningDataGet
Coap::Resource mCommissioningDataSet
uint32_t mContextIdReuseDelay
TimeMilli mContextLastUsed [kNumContextIds]
uint16_t mContextUsed
Coap::Resource mServerData
TimerMilli mTimer
Additional Inherited Members
Protected Member Functions inherited from NetworkData
NetworkDataTlv * AppendTlv (uint16_t aTlvSize)
bool CanInsert (uint16_t aSize) const
PrefixTlv * FindPrefix (const uint8_t *aPrefix, uint8_t aPrefixLength)
const PrefixTlv * FindPrefix (const uint8_t *aPrefix, uint8_t aPrefixLength) const
ServiceTlv * FindService (uint32_t aEnterpriseNumber, const uint8_t *aServiceData, uint8_t aServiceDataLength)
const ServiceTlv * FindService (uint32_t aEnterpriseNumber, const uint8_t *aServiceData, uint8_t aServiceDataLength) const
NetworkDataTlv * GetTlvsEnd (void)
const NetworkDataTlv * GetTlvsEnd (void) const
NetworkDataTlv * GetTlvsStart (void)
const NetworkDataTlv * GetTlvsStart (void) const
void Insert (void *aStart, uint8_t aLength)
void Remove (void *aRemoveStart, uint8_t aRemoveLength)
void RemoveTlv (NetworkDataTlv *aTlv)
otError SendServerDataNotification (uint16_t aRloc16, Coap::ResponseHandler aHandler, void *aContext)
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Static Protected Member Functions inherited from NetworkData
static BorderRouterTlv * FindBorderRouter (PrefixTlv &aPrefix)
static const BorderRouterTlv * FindBorderRouter (const PrefixTlv &aPrefix)
static BorderRouterTlv * FindBorderRouter (PrefixTlv &aPrefix, bool aStable)
static const BorderRouterTlv * FindBorderRouter (const PrefixTlv &aPrefix, bool aStable)
static ContextTlv * FindContext (PrefixTlv &aPrefix)
static const ContextTlv * FindContext (const PrefixTlv &aPrefix)
static HasRouteTlv * FindHasRoute (PrefixTlv &aPrefix)
static const HasRouteTlv * FindHasRoute (const PrefixTlv &aPrefix)
static HasRouteTlv * FindHasRoute (PrefixTlv &aPrefix, bool aStable)
static const HasRouteTlv * FindHasRoute (const PrefixTlv &aPrefix, bool aStable)
static PrefixTlv * FindPrefix (const uint8_t *aPrefix, uint8_t aPrefixLength, uint8_t *aTlvs, uint8_t aTlvsLength)
static const PrefixTlv * FindPrefix (const uint8_t *aPrefix, uint8_t aPrefixLength, const uint8_t *aTlvs, uint8_t aTlvsLength)
static ServiceTlv * FindService (uint32_t aEnterpriseNumber, const uint8_t *aServiceData, uint8_t aServiceDataLength, uint8_t *aTlvs, uint8_t aTlvsLength)
static const ServiceTlv * FindService (uint32_t aEnterpriseNumber, const uint8_t *aServiceData, uint8_t aServiceDataLength, const uint8_t *aTlvs, uint8_t aTlvsLength)
static NetworkDataTlv * FindTlv (NetworkDataTlv *aStart, NetworkDataTlv *aEnd, NetworkDataTlv::Type aType)
static const NetworkDataTlv * FindTlv (const NetworkDataTlv *aStart, const NetworkDataTlv *aEnd, NetworkDataTlv::Type aType)
template<typename TlvType >
static TlvType * FindTlv (NetworkDataTlv *aStart, NetworkDataTlv *aEnd)
template<typename TlvType >
static const TlvType * FindTlv (const NetworkDataTlv *aStart, const NetworkDataTlv *aEnd)
static NetworkDataTlv * FindTlv (NetworkDataTlv *aStart, NetworkDataTlv *aEnd, NetworkDataTlv::Type aType, bool aStable)
static const NetworkDataTlv * FindTlv (const NetworkDataTlv *aStart, const NetworkDataTlv *aEnd, NetworkDataTlv::Type aType, bool aStable)
template<typename TlvType >
static TlvType * FindTlv (NetworkDataTlv *aStart, NetworkDataTlv *aEnd, bool aStable)
template<typename TlvType >
static const TlvType * FindTlv (const NetworkDataTlv *aStart, const NetworkDataTlv *aEnd, bool aStable)
static int8_t PrefixMatch (const uint8_t *a, const uint8_t *b, uint8_t aLength)
static void RemoveTemporaryData (uint8_t *aData, uint8_t &aDataLength)
Protected Attributes inherited from LeaderBase
uint8_t mStableVersion
uint8_t mVersion
Protected Attributes inherited from NetworkData
uint8_t mTlvs [kMaxSize]
The Network Data buffer.
Detailed Description
This class implements the Thread Network Data maintained by the Leader.
Member Enumeration Documentation
MatchMode
enum MatchMode
This enumeration defines the match mode constants to compare two RLOC16 values.
Enumerator
kMatchModeRloc16
Perform exact RLOC16 match.
kMatchModeRouterId
Perform Router ID match (match the router and any of its children).
UpdateStatus
enum UpdateStatus private
Enumerator
kTlvRemoved
kTlvUpdated
anonymous enum
anonymous enum private
Thread Specification Constants.
Enumerator
kMinContextId
Minimum Context ID (0 is used for Mesh Local)
kNumContextIds
Maximum Context ID.
kContextIdReuseDelay
CONTEXT_ID_REUSE_DELAY (seconds)
kStateUpdatePeriod
State update period in milliseconds.
Constructor & Destructor Documentation
Leader()
Leader (Instance & aInstance) explicit
This constructor initializes the object.
Parameters
[in] aInstance A reference to the OpenThread instance.
Member Function Documentation
Reset()
void Reset (void)
This method reset the Thread Network Data.
Start()
void Start (void)
This method starts the Leader services.
Stop()
void Stop (void)
This method stops the Leader services.
IncrementVersion()
void IncrementVersion (void)
This method increments the Thread Network Data version.
IncrementVersionAndStableVersion()
void IncrementVersionAndStableVersion (void)
This method increments both the Thread Network Data version and stable version.
GetContextIdReuseDelay()
uint32_t GetContextIdReuseDelay (void) const inline
This method returns CONTEXT_ID_RESUSE_DELAY value.
Returns
The CONTEXT_ID_REUSE_DELAY value.
References Leader::mContextIdReuseDelay.
SetContextIdReuseDelay()
void SetContextIdReuseDelay (uint32_t aDelay) inline
This method sets CONTEXT_ID_RESUSE_DELAY value.
Warning
This method should only be used for testing.
Parameters
[in] aDelay The CONTEXT_ID_REUSE_DELAY value.
References Leader::FindServiceById(), Leader::mContextIdReuseDelay, Leader::RemoveBorderRouter(), Leader::RemoveStaleChildEntries(), and Leader::UpdateContextsAfterReset().
RemoveBorderRouter()
void RemoveBorderRouter (uint16_t aRloc16, MatchMode aMatchMode)
This method removes Network Data entries matching with a given RLOC16.
Parameters
[in] aRloc16 A RLOC16 value.
[in] aMatchMode A match mode (
See also
MatchMode).
Referenced by Leader::SetContextIdReuseDelay().
UpdateContextsAfterReset()
void UpdateContextsAfterReset (void)
This method synchronizes internal 6LoWPAN Context ID Set with recently obtained Thread Network Data.
Note that this method should be called only by the Leader once after reset.
Referenced by Leader::SetContextIdReuseDelay().
FindServiceById()
const ServiceTlv* FindServiceById (uint8_t aServiceId) const
This method scans network data for given Service ID and returns pointer to the respective TLV, if present.
Parameters
aServiceId Service ID to look for.
Returns
Pointer to the Service TLV for given Service ID, or NULL if not present.
Referenced by Leader::SetContextIdReuseDelay().
RemoveStaleChildEntries()
otError RemoveStaleChildEntries (Coap::ResponseHandler aHandler, void * aContext)
This method sends SVR_DATA.ntf message for any stale child entries that exist in the network data.
Parameters
[in] aHandler A function pointer that is called when the transaction ends.
[in] aContext A pointer to arbitrary context information.
Return values
OT_ERROR_NONE A stale child entry was found and successfully enqueued a SVR_DATA.ntf message.
OT_ERROR_NO_BUFS A stale child entry was found, but insufficient message buffers were available.
OT_ERROR_NOT_FOUND No stale child entries were found.
Referenced by Leader::SetContextIdReuseDelay().
HandleServerData() [1/2]
static void HandleServerData (void * aContext, otMessage * aMessage, const otMessageInfo * aMessageInfo) static private
HandleServerData() [2/2]
void HandleServerData (Coap::Message & aMessage, const Ip6::MessageInfo & aMessageInfo) private
HandleTimer() [1/2]
static void HandleTimer (Timer & aTimer) static private
HandleTimer() [2/2]
void HandleTimer (void) private
RegisterNetworkData()
otError RegisterNetworkData (uint16_t aRloc16, const uint8_t * aTlvs, uint8_t aTlvsLength) private
AddPrefix()
otError AddPrefix (const PrefixTlv & aPrefix, ChangedFlags & aChangedFlags) private
AddHasRoute()
otError AddHasRoute (const HasRouteTlv & aHasRoute, PrefixTlv & aDstPrefix, ChangedFlags & aChangedFlags) private
AddBorderRouter()
otError AddBorderRouter (const BorderRouterTlv & aBorderRouter, PrefixTlv & aDstPrefix, ChangedFlags & aFlags) private
AddService()
otError AddService (const ServiceTlv & aService, ChangedFlags & aChangedFlags) private
AddServer()
otError AddServer (const ServerTlv & aServer, ServiceTlv & aDstService, ChangedFlags & aChangedFlags) private
AllocateServiceId()
otError AllocateServiceId (uint8_t & aServiceId) private
AllocateContextId()
otError AllocateContextId (uint8_t & aConextId) private
FreeContextId()
void FreeContextId (uint8_t aContextId) private
StartContextReuseTimer()
void StartContextReuseTimer (uint8_t aContextId) private
StopContextReuseTimer()
void StopContextReuseTimer (uint8_t aContextId) private
RemoveContext() [1/2]
void RemoveContext (uint8_t aContextId) private
RemoveContext() [2/2]
void RemoveContext (PrefixTlv & aPrefix, uint8_t aContextId) private
RemoveCommissioningData()
void RemoveCommissioningData (void) private
RemoveRloc() [1/2]
void RemoveRloc (uint16_t aRloc16, MatchMode aMatchMode, ChangedFlags & aChangedFlags) private
RemoveRloc() [2/2]
void RemoveRloc (uint16_t aRloc16, MatchMode aMatchMode, const uint8_t * aExcludeTlvs, uint8_t aExcludeTlvsLength, ChangedFlags & aChangedFlags) private
RemoveRlocInPrefix()
void RemoveRlocInPrefix (PrefixTlv & aPrefix, uint16_t aRloc16, MatchMode aMatchMode, const PrefixTlv * aExcludePrefix, ChangedFlags & aChangedFlags) private
RemoveRlocInService()
void RemoveRlocInService (ServiceTlv & aService, uint16_t aRloc16, MatchMode aMatchMode, const ServiceTlv * aExcludeService, ChangedFlags & aChangedFlags) private
RemoveRlocInHasRoute()
void RemoveRlocInHasRoute (PrefixTlv & aPrefix, HasRouteTlv & aHasRoute, uint16_t aRloc16, MatchMode aMatchMode, const PrefixTlv * aExcludePrefix, ChangedFlags & aChangedFlags) private
RemoveRlocInBorderRouter()
void RemoveRlocInBorderRouter (PrefixTlv & aPrefix, BorderRouterTlv & aBorderRouter, uint16_t aRloc16, MatchMode aMatchMode, const PrefixTlv * aExcludePrefix, ChangedFlags & aChangedFlags) private
RlocMatch()
static bool RlocMatch (uint16_t aFirstRloc16, uint16_t aSecondRloc16, MatchMode aMatchMode) static private
Validate()
static otError Validate (const uint8_t * aTlvs, uint8_t aTlvsLength, uint16_t aRloc16) static private
ValidatePrefix()
static otError ValidatePrefix (const PrefixTlv & aPrefix, uint16_t aRloc16) static private
ValidateService()
static otError ValidateService (const ServiceTlv & aService, uint16_t aRloc16) static private
ContainsMatchingEntry() [1/4]
static bool ContainsMatchingEntry (const PrefixTlv * aPrefix, bool aStable, const HasRouteEntry & aEntry) static private
ContainsMatchingEntry() [2/4]
static bool ContainsMatchingEntry (const HasRouteTlv * aHasRoute, const HasRouteEntry & aEntry) static private
ContainsMatchingEntry() [3/4]
static bool ContainsMatchingEntry (const PrefixTlv * aPrefix, bool aStable, const BorderRouterEntry & aEntry) static private
ContainsMatchingEntry() [4/4]
static bool ContainsMatchingEntry (const BorderRouterTlv * aBorderRouter, const BorderRouterEntry & aEntry) static private
ContainsMatchingServer()
static bool ContainsMatchingServer (const ServiceTlv * aService, const ServerTlv & aServer) static private
UpdatePrefix()
UpdateStatus UpdatePrefix (PrefixTlv & aPrefix) private
UpdateService()
UpdateStatus UpdateService (ServiceTlv & aService) private
UpdateTlv()
UpdateStatus UpdateTlv (NetworkDataTlv & aTlv, const NetworkDataTlv * aSubTlvs) private
HandleCommissioningSet() [1/2]
static void HandleCommissioningSet (void * aContext, otMessage * aMessage, const otMessageInfo * aMessageInfo) static private
HandleCommissioningSet() [2/2]
void HandleCommissioningSet (Coap::Message & aMessage, const Ip6::MessageInfo & aMessageInfo) private
HandleCommissioningGet() [1/2]
static void HandleCommissioningGet (void * aContext, otMessage * aMessage, const otMessageInfo * aMessageInfo) static private
HandleCommissioningGet() [2/2]
void HandleCommissioningGet (Coap::Message & aMessage, const Ip6::MessageInfo & aMessageInfo) private
SendCommissioningGetResponse()
void SendCommissioningGetResponse (const Coap::Message & aRequest, uint16_t aLength, const Ip6::MessageInfo & aMessageInfo) private
SendCommissioningSetResponse()
void SendCommissioningSetResponse (const Coap::Message & aRequest, const Ip6::MessageInfo & aMessageInfo, MeshCoP::StateTlv::State aState) private
IncrementVersions() [1/2]
void IncrementVersions (bool aIncludeStable) private
IncrementVersions() [2/2]
void IncrementVersions (const ChangedFlags & aFlags) private
Field Documentation
mContextUsed
uint16_t mContextUsed private
mContextLastUsed
TimeMilli mContextLastUsed[kNumContextIds] private
mContextIdReuseDelay
uint32_t mContextIdReuseDelay private
Referenced by Leader::GetContextIdReuseDelay(), and Leader::SetContextIdReuseDelay().
mTimer
TimerMilli mTimer private
mServerData
Coap::Resource mServerData private
mCommissioningDataGet
Coap::Resource mCommissioningDataGet private
mCommissioningDataSet
Coap::Resource mCommissioningDataSet private
The documentation for this class was generated from the following file:
network_data_leader_ftd.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale