OpenThread: FragmentHeader Class Reference
FragmentHeader Class Reference
Core-6lowpan
#include <lowpan.hpp>
Public Types
enum { kFirstFragmentHeaderSize = 4, kSubsequentFragmentHeaderSize = 5 }
Public Member Functions
uint16_t GetDatagramOffset (void) const
uint16_t GetDatagramSize (void) const
uint16_t GetDatagramTag (void) const
void Init (uint16_t aSize, uint16_t aTag, uint16_t aOffset)
void InitFirstFragment (uint16_t aSize, uint16_t aTag)
otError ParseFrom (const uint8_t *aFrame, uint16_t aFrameLength, uint16_t &aHeaderLength)
otError ParseFrom (const Message &aMessage, uint16_t aOffset, uint16_t &aHeaderLength)
uint16_t WriteTo (uint8_t *aFrame) const
Static Public Member Functions
static bool IsFragmentHeader (const uint8_t *aFrame, uint16_t aFrameLength)
Private Types
enum {
kDispatch = 0xc0, kDispatchMask = 0xd8, kOffsetFlag = 1 << 5, kSizeMask = 0x7ff,
kOffsetMask = 0xfff8, kSizeIndex = 0, kTagIndex = 2, kOffsetIndex = 4
}
Private Attributes
uint16_t mOffset
uint16_t mSize
uint16_t mTag
Detailed Description
This class implements Fragment Header generation and parsing.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
kFirstFragmentHeaderSize
First fragment header size in octets.
kSubsequentFragmentHeaderSize
Subsequent fragment header size in octets.
anonymous enum
anonymous enum private
Enumerator
kDispatch
kDispatchMask
kOffsetFlag
kSizeMask
kOffsetMask
kSizeIndex
kTagIndex
kOffsetIndex
Member Function Documentation
InitFirstFragment()
void InitFirstFragment (uint16_t aSize, uint16_t aTag) inline
This method initializes the Fragment Header as a first fragment.
A first fragment header starts at offset zero.
Parameters
[in] aSize The Datagram Size value.
[in] aTag The Datagram Tag value.
Referenced by MeshForwarder::PrepareDataFrame().
Init()
void Init (uint16_t aSize, uint16_t aTag, uint16_t aOffset)
This method initializes the Fragment Header.
The aOffset value will be truncated to become a multiple of 8.
Parameters
[in] aSize The Datagram Size value.
[in] aTag The Datagram Tag value.
[in] aOffset The Datagram Offset value.
Referenced by MeshForwarder::PrepareDataFrame().
IsFragmentHeader()
bool IsFragmentHeader (const uint8_t * aFrame, uint16_t aFrameLength) static
This static method indicates whether or not the header (in a given frame) is a Fragment Header.
Note
This method checks whether the frame has the minimum required length and that the first byte in header (dispatch byte) matches the Fragment Header dispatch value. It does not fully parse and validate the Fragment Header. ParseFrom() method can be used to fully parse and validate the header.
Return values
TRUE If the header matches the Fragment Header dispatch value.
FALSE If the header does not match the Fragment Header dispatch value.
Referenced by MeshForwarder::HandleReceivedFrame().
ParseFrom() [1/2]
otError ParseFrom (const uint8_t * aFrame, uint16_t aFrameLength, uint16_t & aHeaderLength)
This method parses the Fragment Header from a frame aFrame.
Parameters
[in] aFrame The pointer to the frame.
[in] aFrameLength The length of the frame.
[out] aHeaderLength A reference to a variable to output the parsed header length (on success).
Return values
OT_ERROR_NONE Fragment Header parsed successfully.
OT_ERROR_PARSE Fragment header could not be parsed from aFrame.
References OT_ERROR_NONE, OT_ERROR_PARSE, OT_NOOP, ot::Encoding::BigEndian::ReadUint16(), and VerifyOrExit.
Referenced by MeshForwarder::DecompressIp6Header(), and MeshForwarder::HandleFragment().
ParseFrom() [2/2]
otError ParseFrom (const Message & aMessage, uint16_t aOffset, uint16_t & aHeaderLength)
This method parses the Fragment Header from a message.
Parameters
[in] aMessage The message to read from.
[in] aOffset The offset within the message to start reading from.
[out] aHeaderLength A reference to a variable to output the parsed header length (on success).
Return values
OT_ERROR_NONE Fragment Header parsed successfully.
OT_ERROR_PARSE Fragment header could not be parsed from aFrame.
References Message::Read().
GetDatagramSize()
uint16_t GetDatagramSize (void) const inline
This method returns the Datagram Size value.
Returns
The Datagram Size value.
Referenced by MeshForwarder::GetFramePriority(), and MeshForwarder::HandleFragment().
GetDatagramTag()
uint16_t GetDatagramTag (void) const inline
This method returns the Datagram Tag value.
Returns
The Datagram Tag value.
Referenced by MeshForwarder::GetFramePriority(), and MeshForwarder::HandleFragment().
GetDatagramOffset()
uint16_t GetDatagramOffset (void) const inline
This method returns the Datagram Offset value.
The returned offset value is always multiple of 8.
Returns
The Datagram Offset value (multiple of 8).
Referenced by MeshForwarder::DecompressIp6Header(), MeshForwarder::GetFramePriority(), and MeshForwarder::HandleFragment().
WriteTo()
uint16_t WriteTo (uint8_t * aFrame) const
This method writes the Fragment Header into a given frame.
Note
This method expects the frame buffer to have enough space for the entire Fragment Header
Parameters
[out] aFrame The pointer to the frame buffer to write to.
Returns
The header length (number of bytes written).
References ot::Encoding::BigEndian::WriteUint16().
Referenced by MeshForwarder::PrepareDataFrame().
Field Documentation
mSize
uint16_t mSize private
mTag
uint16_t mTag private
mOffset
uint16_t mOffset private
The documentation for this class was generated from the following files:
lowpan.hpp
lowpan.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale