OpenThread: QueryMetadata Class Reference
QueryMetadata Class Reference
#include <sntp_client.hpp>
Public Member Functions
otError AppendTo (Message &aMessage) const
QueryMetadata (void)
QueryMetadata (otSntpResponseHandler aHandler, void *aContext)
void ReadFrom (const Message &aMessage)
int UpdateIn (Message &aMessage) const
Private Attributes
Ip6::Address mDestinationAddress
IPv6 address of the message destination.
uint16_t mDestinationPort
UDP port of the message destination.
void * mResponseContext
A pointer to arbitrary context information.
otSntpResponseHandler mResponseHandler
A function pointer that is called on response reception.
uint8_t mRetransmissionCount
Number of retransmissions.
Ip6::Address mSourceAddress
IPv6 address of the message source.
TimeMilli mTransmissionTime
Time when the timer should shoot for this message.
uint32_t mTransmitTimestamp
Time at the client when the request departed for the server.
Friends
class Client
Detailed Description
This class implements metadata required for SNTP retransmission.
Constructor & Destructor Documentation
QueryMetadata() [1/2]
QueryMetadata (void)
Default constructor for the object.
QueryMetadata() [2/2]
QueryMetadata (otSntpResponseHandler aHandler, void * aContext)
This constructor initializes the object with specific values.
Parameters
[in] aHandler Pointer to a handler function for the response.
[in] aContext Context for the handler function.
Member Function Documentation
AppendTo()
otError AppendTo (Message & aMessage) const inline
This method appends request data to the message.
Parameters
[in] aMessage A reference to the message.
Return values
OT_ERROR_NONE Successfully appended the bytes.
OT_ERROR_NO_BUFS Insufficient available buffers to grow the message.
References Message::Append().
ReadFrom()
void ReadFrom (const Message & aMessage) inline
This method reads request data from the message.
Parameters
[in] aMessage A reference to the message.
References Message::GetLength(), OT_ASSERT, OT_UNUSED_VARIABLE, and Message::Read().
UpdateIn()
int UpdateIn (Message & aMessage) const inline
This method updates request data in the message.
Parameters
[in] aMessage A reference to the message.
Returns
The number of bytes updated.
References Message::GetLength(), and Message::Write().
Friends And Related Function Documentation
Client
friend class Client friend
Field Documentation
mTransmitTimestamp
uint32_t mTransmitTimestamp private
Time at the client when the request departed for the server.
mResponseHandler
otSntpResponseHandler mResponseHandler private
A function pointer that is called on response reception.
mResponseContext
void* mResponseContext private
A pointer to arbitrary context information.
mTransmissionTime
TimeMilli mTransmissionTime private
Time when the timer should shoot for this message.
mSourceAddress
Ip6::Address mSourceAddress private
IPv6 address of the message source.
mDestinationAddress
Ip6::Address mDestinationAddress private
IPv6 address of the message destination.
mDestinationPort
uint16_t mDestinationPort private
UDP port of the message destination.
mRetransmissionCount
uint8_t mRetransmissionCount private
Number of retransmissions.
The documentation for this class was generated from the following file:
sntp_client.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale