OpenThread: SteeringDataTlv Class Reference
SteeringDataTlv Class Reference
#include <meshcop_tlvs.hpp>
Public Types
enum { kType = kSteeringData }
Public Types inherited from Tlv
enum Type {
kChannel = OT_MESHCOP_TLV_CHANNEL, kPanId = OT_MESHCOP_TLV_PANID, kExtendedPanId = OT_MESHCOP_TLV_EXTPANID, kNetworkName = OT_MESHCOP_TLV_NETWORKNAME,
kPskc = OT_MESHCOP_TLV_PSKC, kNetworkMasterKey = OT_MESHCOP_TLV_MASTERKEY, kNetworkKeySequence = OT_MESHCOP_TLV_NETWORK_KEY_SEQUENCE, kMeshLocalPrefix = OT_MESHCOP_TLV_MESHLOCALPREFIX,
kSteeringData = OT_MESHCOP_TLV_STEERING_DATA, kBorderAgentLocator = OT_MESHCOP_TLV_BORDER_AGENT_RLOC, kCommissionerId = OT_MESHCOP_TLV_COMMISSIONER_ID, kCommissionerSessionId = OT_MESHCOP_TLV_COMM_SESSION_ID,
kSecurityPolicy = OT_MESHCOP_TLV_SECURITYPOLICY, kGet = OT_MESHCOP_TLV_GET, kActiveTimestamp = OT_MESHCOP_TLV_ACTIVETIMESTAMP, kCommissionerUdpPort = OT_MESHCOP_TLV_COMMISSIONER_UDP_PORT,
kState = OT_MESHCOP_TLV_STATE, kJoinerDtlsEncapsulation = OT_MESHCOP_TLV_JOINER_DTLS, kJoinerUdpPort = OT_MESHCOP_TLV_JOINER_UDP_PORT, kJoinerIid = OT_MESHCOP_TLV_JOINER_IID,
kJoinerRouterLocator = OT_MESHCOP_TLV_JOINER_RLOC, kJoinerRouterKek = OT_MESHCOP_TLV_JOINER_ROUTER_KEK, kProvisioningUrl = OT_MESHCOP_TLV_PROVISIONING_URL, kVendorName = OT_MESHCOP_TLV_VENDOR_NAME_TLV,
kVendorModel = OT_MESHCOP_TLV_VENDOR_MODEL_TLV, kVendorSwVersion = OT_MESHCOP_TLV_VENDOR_SW_VERSION_TLV, kVendorData = OT_MESHCOP_TLV_VENDOR_DATA_TLV, kVendorStackVersion = OT_MESHCOP_TLV_VENDOR_STACK_VERSION_TLV,
kUdpEncapsulation = OT_MESHCOP_TLV_UDP_ENCAPSULATION_TLV, kIPv6Address = OT_MESHCOP_TLV_IPV6_ADDRESS_TLV, kPendingTimestamp = OT_MESHCOP_TLV_PENDINGTIMESTAMP, kDelayTimer = OT_MESHCOP_TLV_DELAYTIMER,
kChannelMask = OT_MESHCOP_TLV_CHANNELMASK, kCount = OT_MESHCOP_TLV_COUNT, kPeriod = OT_MESHCOP_TLV_PERIOD, kScanDuration = OT_MESHCOP_TLV_SCAN_DURATION,
kEnergyList = OT_MESHCOP_TLV_ENERGY_LIST, kDiscoveryRequest = OT_MESHCOP_TLV_DISCOVERYREQUEST, kDiscoveryResponse = OT_MESHCOP_TLV_DISCOVERYRESPONSE
}
Public Types inherited from Tlv
enum { kBaseTlvMaxLength = OT_NETWORK_BASE_TLV_MAX_LENGTH }
Public Member Functions
void Clear (void)
void ClearBit (uint8_t aBit)
void ComputeBloomFilter (const otExtAddress &aJoinerId)
bool DoesAllowAny (void)
bool GetBit (uint8_t aBit) const
uint8_t GetNumBits (void) const
uint8_t GetSteeringDataLength (void) const
void Init (void)
bool IsCleared (void) const
bool IsValid (void) const
void Set (void)
void SetBit (uint8_t aBit)
Public Member Functions inherited from Tlv
Tlv * GetNext (void)
const Tlv * GetNext (void) const
Type GetType (void) const
void SetType (Type aType)
Public Member Functions inherited from Tlv
otError AppendTo (Message &aMessage) const
uint8_t GetLength (void) const
Tlv * GetNext (void)
const Tlv * GetNext (void) const
uint32_t GetSize (void) const
uint8_t GetType (void) const
uint8_t * GetValue (void)
const uint8_t * GetValue (void) const
bool IsExtended (void) const
void SetLength (uint8_t aLength)
void SetType (uint8_t aType)
Private Attributes
uint8_t mSteeringData [OT_STEERING_DATA_MAX_LENGTH]
Additional Inherited Members
Static Public Member Functions inherited from Tlv
static Tlv * FindTlv (uint8_t *aTlvsStart, uint16_t aTlvsLength, Type aType)
static const Tlv * FindTlv (const uint8_t *aTlvsStart, uint16_t aTlvsLength, Type aType)
template<typename TlvType >
static TlvType * FindTlv (uint8_t *aTlvsStart, uint16_t aTlvsLength)
template<typename TlvType >
static const TlvType * FindTlv (const uint8_t *aTlvsStart, uint16_t aTlvsLength)
static otError GetTlv (const Message &aMessage, Type aType, uint16_t aMaxLength, Tlv &aTlv)
static otError GetValueOffset (const Message &aMessage, Type aType, uint16_t &aOffset, uint16_t &aLength)
static bool IsValid (const Tlv &aTlv)
Static Public Member Functions inherited from Tlv
static otError AppendTlv (Message &aMessage, uint8_t aType, const uint8_t *aValue, uint8_t aLength)
static otError AppendUint16Tlv (Message &aMessage, uint8_t aType, uint16_t aValue)
static otError AppendUint32Tlv (Message &aMessage, uint8_t aType, uint32_t aValue)
static otError AppendUint8Tlv (Message &aMessage, uint8_t aType, uint8_t aValue)
static otError Get (const Message &aMessage, uint8_t aType, uint16_t aMaxSize, Tlv &aTlv)
static otError GetOffset (const Message &aMessage, uint8_t aType, uint16_t &aOffset)
static otError GetValueOffset (const Message &aMessage, uint8_t aType, uint16_t &aOffset, uint16_t &aLength)
static otError ReadTlv (const Message &aMessage, uint8_t aType, void *aValue, uint8_t aLength)
static otError ReadUint16Tlv (const Message &aMessage, uint8_t aType, uint16_t &aValue)
static otError ReadUint32Tlv (const Message &aMessage, uint8_t aType, uint32_t &aValue)
static otError ReadUint8Tlv (const Message &aMessage, uint8_t aType, uint8_t &aValue)
Protected Types inherited from Tlv
enum { kExtendedLength = 255 }
Detailed Description
This class implements Steering Data TLV generation and parsing.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
kType
The TLV Type.
Member Function Documentation
Init()
void Init (void) inline
This method initializes the TLV.
References Tlv::kSteeringData, Tlv::SetLength(), and Tlv::SetType().
IsValid()
bool IsValid (void) const inline
This method indicates whether or not the TLV appears to be well-formed.
Return values
TRUE If the TLV appears to be well-formed.
FALSE If the TLV does not appear to be well-formed.
References Tlv::GetLength().
Referenced by Mle::HandleDiscoveryResponse().
GetSteeringDataLength()
uint8_t GetSteeringDataLength (void) const inline
This method returns the Steering Data length.
Returns
The Steering Data length.
References Tlv::GetLength().
Referenced by Mle::HandleDiscoveryResponse().
Clear()
void Clear (void) inline
This method sets all bits in the Bloom Filter to zero.
Set()
void Set (void) inline
Ths method sets all bits in the Bloom Filter to one.
DoesAllowAny()
bool DoesAllowAny (void) inline
Ths method indicates whether or not the SteeringData allows all Joiners.
Return values
TRUE If the SteeringData allows all Joiners.
FALSE If the SteeringData doesn't allow any Joiner.
GetNumBits()
uint8_t GetNumBits (void) const inline
This method returns the number of bits in the Bloom Filter.
Returns
The number of bits in the Bloom Filter.
Referenced by Mle::HandleDiscoveryResponse().
GetBit()
bool GetBit (uint8_t aBit) const inline
This method indicates whether or not bit aBit is set.
Parameters
[in] aBit The bit offset.
Return values
TRUE If bit aBit is set.
FALSE If bit aBit is not set.
Referenced by Mle::HandleDiscoveryResponse().
ClearBit()
void ClearBit (uint8_t aBit) inline
This method clears bit aBit.
Parameters
[in] aBit The bit offset.
SetBit()
void SetBit (uint8_t aBit) inline
This method sets bit aBit.
Parameters
[in] aBit The bit offset.
IsCleared()
bool IsCleared (void) const
Ths method indicates whether or not the SteeringData is all zeros.
Return values
TRUE If the SteeringData is all zeros.
FALSE If the SteeringData isn't all zeros.
References Tlv::GetLength().
ComputeBloomFilter()
void ComputeBloomFilter (const otExtAddress & aJoinerId)
This method computes the Bloom Filter.
Parameters
[in] aJoinerId The Joiner ID.
References Crc16::Get(), Crc16::kAnsi, Crc16::kCcitt, otExtAddress::m8, and Crc16::Update().
Field Documentation
mSteeringData
uint8_t mSteeringData[OT_STEERING_DATA_MAX_LENGTH] private
The documentation for this class was generated from the following files:
meshcop_tlvs.hpp
meshcop_tlvs.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale