OpenThread: String< SIZE > Class Template Reference
String< SIZE > Class Template Reference
Core-string
#include <string.hpp>
Public Types
enum { kSize = SIZE }
Public Member Functions
otError Append (const char *aFormat,...)
const char * AsCString (void) const
void Clear (void)
uint16_t GetLength (void) const
uint16_t GetSize (void) const
otError Set (const char *aFormat,...)
String (void)
String (const char *aFormat,...)
Private Attributes
char mBuffer [kSize]
uint16_t mLength
Additional Inherited Members
Static Private Member Functions inherited from StringBase
static otError Write (char *aBuffer, uint16_t aSize, uint16_t &aLength, const char *aFormat, va_list aArgs)
Detailed Description
template<uint16_t SIZE>
class ot::String< SIZE >
This class defines a fixed-size string.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
kSize
Size (number of characters) in the buffer storage for the string.
Constructor & Destructor Documentation
String() [1/2]
String (void) inline
This constructor initializes the String object as empty.
String() [2/2]
String (const char * aFormat, ...) inline explicit
This constructor initializes the String object using printf() style formatted data.
Parameters
[in] aFormat A pointer to the format string.
[in] ... Arguments for the format specification.
References StringBase::Write().
Member Function Documentation
Clear()
void Clear (void) inline
This method clears the string.
GetLength()
uint16_t GetLength (void) const inline
This method gets the length of the string.
Similar to strlen() the length does not include the null character at the end of the string.
Returns
The string length.
GetSize()
uint16_t GetSize (void) const inline
This method returns the size (number of chars) in the buffer storage for the string.
Returns
The size of the buffer storage for the string.
AsCString()
const char* AsCString (void) const inline
This method returns the string as a null-terminated C string.
Returns
The null-terminated C string.
Referenced by MeshForwarder::GetFramePriority(), Ip6::HandleDatagram(), AnnounceSenderBase::HandleTimer(), Mle::LogMleMessage(), TxFrame::ProcessTransmitAesCcm(), Mle::SetDeviceMode(), SubMac::SetExtAddress(), and Mac::SetPromiscuous().
Set()
otError Set (const char * aFormat, ...) inline
This method sets the string using printf() style formatted data.
Parameters
[in] aFormat A pointer to the format string.
[in] ... Arguments for the format specification.
Return values
OT_ERROR_NONE Updated the string successfully.
OT_ERROR_NO_BUFS String could not fit in the storage.
OT_ERROR_INVALID_ARGS Arguments do not match the format string.
References StringBase::Write().
Append()
otError Append (const char * aFormat, ...) inline
This method appends printf() style formatted data to the String object.
Parameters
[in] aFormat A pointer to the format string.
[in] ... Arguments for the format specification.
Return values
OT_ERROR_NONE Updated the string successfully.
OT_ERROR_NO_BUFS String could not fit in the storage.
OT_ERROR_INVALID_ARGS Arguments do not match the format string.
References StringBase::Write().
Field Documentation
mLength
uint16_t mLength private
mBuffer
char mBuffer[kSize] private
The documentation for this class was generated from the following file:
string.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale