OpenThread: Buffer Class Reference
Buffer Class Reference
Core-message
#include <message.hpp>
Public Member Functions
class Buffer * GetNextBuffer (void) const
void SetNextBuffer (class Buffer *buf)
Protected Attributes
union {
uint8_t mData [kBufferDataSize]
struct {
uint8_t mData [kHeadBufferDataSize]
MessageInfo mInfo
} mHead
} mBuffer
Private Types
enum { kBufferDataSize = kBufferSize - sizeof(struct otMessage), kHeadBufferDataSize = kBufferDataSize - sizeof(struct MessageInfo) }
Private Member Functions
uint8_t * GetData (void)
const uint8_t * GetData (void) const
uint8_t * GetFirstData (void)
const uint8_t * GetFirstData (void) const
Friends
class Message
Additional Inherited Members
Data Fields inherited from otMessage
struct otMessage * mNext
A pointer to the next Message buffer.
Detailed Description
This class represents a Message buffer.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
kBufferDataSize
kHeadBufferDataSize
Member Function Documentation
GetNextBuffer()
class Buffer* GetNextBuffer (void) const inline
This method returns a pointer to the next message buffer.
Returns
A pointer to the next message buffer.
References MessageInfo::mNext.
Referenced by MessagePool::FreeBuffers(), Message::GetBufferCount(), MessagePool::NewBuffer(), Message::Read(), Message::ResizeMessage(), Message::UpdateChecksum(), and Message::Write().
SetNextBuffer()
void SetNextBuffer (class Buffer * buf) inline
This method sets the pointer to the next message buffer.
References MessageInfo::mNext.
Referenced by MessagePool::FreeBuffers(), MessagePool::MessagePool(), MessagePool::NewBuffer(), Message::Prepend(), and Message::ResizeMessage().
GetFirstData() [1/2]
uint8_t* GetFirstData (void) inline private
This method returns a pointer to the first byte of data in the first message buffer.
Returns
A pointer to the first data byte.
GetFirstData() [2/2]
const uint8_t* GetFirstData (void) const inline private
This method returns a pointer to the first byte of data in the first message buffer.
Returns
A pointer to the first data byte.
GetData() [1/2]
uint8_t* GetData (void) inline private
This method returns a pointer to the first data byte of a subsequent message buffer.
Returns
A pointer to the first data byte.
Referenced by Message::Read(), Message::UpdateChecksum(), and Message::Write().
GetData() [2/2]
const uint8_t* GetData (void) const inline private
This method returns a pointer to the first data byte of a subsequent message buffer.
Returns
A pointer to the first data byte.
Friends And Related Function Documentation
Message
friend class Message friend
Field Documentation
mInfo
MessageInfo mInfo
mData
uint8_t mData[kBufferDataSize]
mHead
struct { ... } mHead
Referenced by Message::Next(), Message::Prepend(), and Message::Prev().
mBuffer
union { ... } mBuffer
Referenced by Message::GetHelpData(), Message::ParseHeader(), and Message::Prepend().
The documentation for this class was generated from the following file:
message.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale