OpenThread: TimeoutTlv Class Reference
TimeoutTlv Class Reference
MLE » TLVs
#include <network_diagnostic_tlvs.hpp>
Public Member Functions
uint32_t GetTimeout (void) const
void Init (void)
bool IsValid (void) const
void SetTimeout (uint32_t aTimeout)
Public Member Functions inherited from NetworkDiagnosticTlv
Type GetType (void) const
void SetType (Type aType)
Public Member Functions inherited from Tlv
otError AppendTo (Message &aMessage) const
uint8_t GetLength (void) const
Tlv * GetNext (void)
const Tlv * GetNext (void) const
uint32_t GetSize (void) const
uint8_t GetType (void) const
uint8_t * GetValue (void)
const uint8_t * GetValue (void) const
bool IsExtended (void) const
void SetLength (uint8_t aLength)
void SetType (uint8_t aType)
Private Attributes
uint32_t mTimeout
Additional Inherited Members
Public Types inherited from NetworkDiagnosticTlv
enum Type {
kExtMacAddress = OT_NETWORK_DIAGNOSTIC_TLV_EXT_ADDRESS, kAddress16 = OT_NETWORK_DIAGNOSTIC_TLV_SHORT_ADDRESS, kMode = OT_NETWORK_DIAGNOSTIC_TLV_MODE, kTimeout = OT_NETWORK_DIAGNOSTIC_TLV_TIMEOUT,
kConnectivity = OT_NETWORK_DIAGNOSTIC_TLV_CONNECTIVITY, kRoute = OT_NETWORK_DIAGNOSTIC_TLV_ROUTE, kLeaderData = OT_NETWORK_DIAGNOSTIC_TLV_LEADER_DATA, kNetworkData = OT_NETWORK_DIAGNOSTIC_TLV_NETWORK_DATA,
kIp6AddressList = OT_NETWORK_DIAGNOSTIC_TLV_IP6_ADDR_LIST, kMacCounters = OT_NETWORK_DIAGNOSTIC_TLV_MAC_COUNTERS, kBatteryLevel = OT_NETWORK_DIAGNOSTIC_TLV_BATTERY_LEVEL, kSupplyVoltage = OT_NETWORK_DIAGNOSTIC_TLV_SUPPLY_VOLTAGE,
kChildTable = OT_NETWORK_DIAGNOSTIC_TLV_CHILD_TABLE, kChannelPages = OT_NETWORK_DIAGNOSTIC_TLV_CHANNEL_PAGES, kTypeList = OT_NETWORK_DIAGNOSTIC_TLV_TYPE_LIST, kMaxChildTimeout = OT_NETWORK_DIAGNOSTIC_TLV_MAX_CHILD_TIMEOUT
}
Public Types inherited from Tlv
enum { kBaseTlvMaxLength = OT_NETWORK_BASE_TLV_MAX_LENGTH }
Static Public Member Functions inherited from NetworkDiagnosticTlv
static otError GetOffset (const Message &aMessage, Type aType, uint16_t &aOffset)
static otError GetTlv (const Message &aMessage, Type aType, uint16_t aMaxLength, Tlv &aTlv)
Static Public Member Functions inherited from Tlv
static otError AppendTlv (Message &aMessage, uint8_t aType, const uint8_t *aValue, uint8_t aLength)
static otError AppendUint16Tlv (Message &aMessage, uint8_t aType, uint16_t aValue)
static otError AppendUint32Tlv (Message &aMessage, uint8_t aType, uint32_t aValue)
static otError AppendUint8Tlv (Message &aMessage, uint8_t aType, uint8_t aValue)
static otError Get (const Message &aMessage, uint8_t aType, uint16_t aMaxSize, Tlv &aTlv)
static otError GetOffset (const Message &aMessage, uint8_t aType, uint16_t &aOffset)
static otError GetValueOffset (const Message &aMessage, uint8_t aType, uint16_t &aOffset, uint16_t &aLength)
static otError ReadTlv (const Message &aMessage, uint8_t aType, void *aValue, uint8_t aLength)
static otError ReadUint16Tlv (const Message &aMessage, uint8_t aType, uint16_t &aValue)
static otError ReadUint32Tlv (const Message &aMessage, uint8_t aType, uint32_t &aValue)
static otError ReadUint8Tlv (const Message &aMessage, uint8_t aType, uint8_t &aValue)
Protected Types inherited from Tlv
enum { kExtendedLength = 255 }
Detailed Description
This class implements Timeout TLV generation and parsing.
Member Function Documentation
Init()
void Init (void) inline
This method initializes the TLV.
References NetworkDiagnosticTlv::kTimeout, Tlv::SetLength(), and NetworkDiagnosticTlv::SetType().
IsValid()
bool IsValid (void) const inline
This method indicates whether or not the TLV appears to be well-formed.
Return values
TRUE If the TLV appears to be well-formed.
FALSE If the TLV does not appear to be well-formed.
References Tlv::GetLength().
GetTimeout()
uint32_t GetTimeout (void) const inline
This method returns the Timeout value.
Returns
The Timeout value.
References ot::Encoding::BigEndian::HostSwap32().
SetTimeout()
void SetTimeout (uint32_t aTimeout) inline
This method sets the Timeout value.
Parameters
[in] aTimeout The Timeout value.
References ot::Encoding::BigEndian::HostSwap32().
Field Documentation
mTimeout
uint32_t mTimeout private
The documentation for this class was generated from the following file:
network_diagnostic_tlvs.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale