OpenThread: HeaderIe Class Reference
HeaderIe Class Reference
Core-mac
#include <mac_frame.hpp>
Public Types
enum { kIdOffset = 7, kIdMask = 0xff << kIdOffset, kLengthOffset = 0, kLengthMask = 0x7f << kLengthOffset }
Public Member Functions
uint16_t GetId (void) const
uint16_t GetLength (void) const
void Init (void)
void SetId (uint16_t aId)
void SetLength (uint16_t aLength)
Private Attributes
uint16_t mHeaderIe
Detailed Description
This class implements IEEE 802.15.4 IE (Information Element) generation and parsing.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
kIdOffset
kIdMask
kLengthOffset
kLengthMask
Member Function Documentation
Init()
void Init (void) inline
This method initializes the Header IE.
References HeaderIe::mHeaderIe.
Referenced by MeshForwarder::PrepareDataFrame().
GetId()
uint16_t GetId (void) const inline
This method returns the IE Element Id.
Returns
the IE Element Id.
References ot::Encoding::LittleEndian::HostSwap16(), HeaderIe::kIdMask, HeaderIe::kIdOffset, and HeaderIe::mHeaderIe.
Referenced by Frame::FindPayloadIndex(), and Frame::GetFooter().
SetId()
void SetId (uint16_t aId) inline
This method sets the IE Element Id.
Parameters
[in] aID The IE Element Id.
References ot::Encoding::LittleEndian::HostSwap16(), HeaderIe::kIdMask, HeaderIe::kIdOffset, and HeaderIe::mHeaderIe.
Referenced by MeshForwarder::PrepareDataFrame().
GetLength()
uint16_t GetLength (void) const inline
This method returns the IE content length.
Returns
the IE content length.
References ot::Encoding::LittleEndian::HostSwap16(), HeaderIe::kLengthMask, HeaderIe::kLengthOffset, and HeaderIe::mHeaderIe.
Referenced by Frame::FindPayloadIndex(), and Frame::GetFooter().
SetLength()
void SetLength (uint16_t aLength) inline
This method sets the IE content length.
Parameters
[in] aLength The IE content length.
References ot::Encoding::LittleEndian::HostSwap16(), HeaderIe::kLengthMask, HeaderIe::kLengthOffset, and HeaderIe::mHeaderIe.
Referenced by MeshForwarder::PrepareDataFrame().
Field Documentation
mHeaderIe
uint16_t mHeaderIe private
Referenced by HeaderIe::GetId(), HeaderIe::GetLength(), HeaderIe::Init(), HeaderIe::SetId(), and HeaderIe::SetLength().
The documentation for this class was generated from the following file:
mac_frame.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale