OpenThread: Lowpan Class Reference
Lowpan Class Reference
Core-6lowpan
#include <lowpan.hpp>
Public Member Functions
otError Compress (Message &aMessage, const Mac::Address &aMacSource, const Mac::Address &aMacDest, BufferWriter &aBuf)
int Decompress (Message &aMessage, const Mac::Address &aMacSource, const Mac::Address &aMacDest, const uint8_t *aBuf, uint16_t aBufLength, uint16_t aDatagramLength)
int DecompressBaseHeader (Ip6::Header &aIp6Header, bool &aCompressedNextHeader, const Mac::Address &aMacSource, const Mac::Address &aMacDest, const uint8_t *aBuf, uint16_t aBufLength)
int DecompressUdpHeader (Ip6::UdpHeader &aUdpHeader, const uint8_t *aBuf, uint16_t aBufLength)
Lowpan (Instance &aInstance)
Public Member Functions inherited from InstanceLocator
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Static Public Member Functions
static bool IsLowpanHc (const uint8_t *aHeader)
Private Types
enum {
kHcDispatch = 3 << 13, kHcDispatchMask = 7 << 13, kHcTrafficClass = 1 << 11, kHcFlowLabel = 2 << 11,
kHcTrafficFlow = 3 << 11, kHcTrafficFlowMask = 3 << 11, kHcNextHeader = 1 << 10, kHcHopLimit1 = 1 << 8,
kHcHopLimit64 = 2 << 8, kHcHopLimit255 = 3 << 8, kHcHopLimitMask = 3 << 8, kHcContextId = 1 << 7,
kHcSrcAddrContext = 1 << 6, kHcSrcAddrMode0 = 0 << 4, kHcSrcAddrMode1 = 1 << 4, kHcSrcAddrMode2 = 2 << 4,
kHcSrcAddrMode3 = 3 << 4, kHcSrcAddrModeMask = 3 << 4, kHcMulticast = 1 << 3, kHcDstAddrContext = 1 << 2,
kHcDstAddrMode0 = 0 << 0, kHcDstAddrMode1 = 1 << 0, kHcDstAddrMode2 = 2 << 0, kHcDstAddrMode3 = 3 << 0,
kHcDstAddrModeMask = 3 << 0, kExtHdrDispatch = 0xe0, kExtHdrDispatchMask = 0xf0, kExtHdrEidHbh = 0x00,
kExtHdrEidRouting = 0x02, kExtHdrEidFragment = 0x04, kExtHdrEidDst = 0x06, kExtHdrEidMobility = 0x08,
kExtHdrEidIp6 = 0x0e, kExtHdrEidMask = 0x0e, kExtHdrNextHeader = 0x01, kExtHdrMaxLength = 255,
kUdpDispatch = 0xf0, kUdpDispatchMask = 0xf8, kUdpChecksum = 1 << 2, kUdpPortMask = 3 << 0
}
Private Member Functions
otError Compress (Message &aMessage, const Mac::Address &aMacSource, const Mac::Address &aMacDest, BufferWriter &aBuf, uint8_t &aHeaderDepth)
otError CompressDestinationIid (const Mac::Address &aMacAddr, const Ip6::Address &aIpAddr, const Context &aContext, uint16_t &aHcCtl, BufferWriter &aBuf)
otError CompressExtensionHeader (Message &aMessage, BufferWriter &aBuf, uint8_t &aNextHeader)
otError CompressMulticast (const Ip6::Address &aIpAddr, uint16_t &aHcCtl, BufferWriter &aBuf)
otError CompressSourceIid (const Mac::Address &aMacAddr, const Ip6::Address &aIpAddr, const Context &aContext, uint16_t &aHcCtl, BufferWriter &aBuf)
otError CompressUdp (Message &aMessage, BufferWriter &aBuf)
int DecompressExtensionHeader (Message &aMessage, const uint8_t *aBuf, uint16_t aBufLength)
int DecompressUdpHeader (Message &aMessage, const uint8_t *aBuf, uint16_t aBufLength, uint16_t aDatagramLength)
otError DispatchToNextHeader (uint8_t aDispatch, uint8_t &aNextHeader)
Static Private Member Functions
static otError ComputeIid (const Mac::Address &aMacAddr, const Context &aContext, Ip6::Address &aIpAddress)
static void CopyContext (const Context &aContext, Ip6::Address &aAddress)
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Detailed Description
This class implements LOWPAN_IPHC header compression.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
kHcDispatch
kHcDispatchMask
kHcTrafficClass
kHcFlowLabel
kHcTrafficFlow
kHcTrafficFlowMask
kHcNextHeader
kHcHopLimit1
kHcHopLimit64
kHcHopLimit255
kHcHopLimitMask
kHcContextId
kHcSrcAddrContext
kHcSrcAddrMode0
kHcSrcAddrMode1
kHcSrcAddrMode2
kHcSrcAddrMode3
kHcSrcAddrModeMask
kHcMulticast
kHcDstAddrContext
kHcDstAddrMode0
kHcDstAddrMode1
kHcDstAddrMode2
kHcDstAddrMode3
kHcDstAddrModeMask
kExtHdrDispatch
kExtHdrDispatchMask
kExtHdrEidHbh
kExtHdrEidRouting
kExtHdrEidFragment
kExtHdrEidDst
kExtHdrEidMobility
kExtHdrEidIp6
kExtHdrEidMask
kExtHdrNextHeader
kExtHdrMaxLength
kUdpDispatch
kUdpDispatchMask
kUdpChecksum
kUdpPortMask
Constructor & Destructor Documentation
Lowpan()
Lowpan (Instance & aInstance) explicit
This constructor initializes the object.
Parameters
[in] aInstance A reference to the OpenThread instance.
Member Function Documentation
IsLowpanHc()
static bool IsLowpanHc (const uint8_t * aHeader) inline static
This method indicates whether or not the header is a LOWPAN_IPHC header.
Parameters
[in] aHeader A pointer to the header.
Return values
TRUE If the header matches the LOWPAN_IPHC dispatch value.
FALSE If the header does not match the LOWPAN_IPHC dispatch value.
References Lowpan::kHcDispatch, and Lowpan::kHcDispatchMask.
Referenced by MeshForwarder::DecompressIp6Header(), and MeshForwarder::HandleReceivedFrame().
Compress() [1/2]
otError Compress (Message & aMessage, const Mac::Address & aMacSource, const Mac::Address & aMacDest, BufferWriter & aBuf)
This method compresses an IPv6 header.
Parameters
[in] aMessage A reference to the IPv6 message.
[in] aMacSource The MAC source address.
[in] aMacDest The MAC destination address.
[out] aBuf A pointer where the compressed IPv6 header will be placed.
Returns
The size of the compressed header in bytes.
References OT_ERROR_NONE.
Referenced by Lowpan::Compress().
Decompress()
int Decompress (Message & aMessage, const Mac::Address & aMacSource, const Mac::Address & aMacDest, const uint8_t * aBuf, uint16_t aBufLength, uint16_t aDatagramLength)
This method decompresses a LOWPAN_IPHC header.
Parameters
[out] aMessage A reference where the IPv6 header will be placed.
[in] aMacSource The MAC source address.
[in] aMacDest The MAC destination address.
[in] aBuf A pointer to the LOWPAN_IPHC header.
[in] aBufLength The number of bytes in aBuf.
[in] aDatagramLength The IPv6 datagram length.
Returns
The size of the compressed header in bytes.
References Message::Append(), Lowpan::DecompressBaseHeader(), Lowpan::DecompressExtensionHeader(), Lowpan::DecompressUdpHeader(), ExitNow, Message::GetOffset(), Header::GetPayloadLengthOffset(), ot::Encoding::BigEndian::HostSwap16(), Lowpan::kExtHdrDispatch, Lowpan::kExtHdrDispatchMask, Lowpan::kExtHdrEidIp6, Lowpan::kExtHdrEidMask, Lowpan::kExtHdrNextHeader, Lowpan::kUdpDispatch, Lowpan::kUdpDispatchMask, Message::MoveOffset(), OT_ERROR_NONE, OT_ERROR_PARSE, OT_NOOP, SuccessOrExit, VerifyOrExit, and Message::Write().
DecompressBaseHeader()
int DecompressBaseHeader (Ip6::Header & aIp6Header, bool & aCompressedNextHeader, const Mac::Address & aMacSource, const Mac::Address & aMacDest, const uint8_t * aBuf, uint16_t aBufLength)
This method decompresses a LOWPAN_IPHC header.
Parameters
[out] aIp6Header A reference where the IPv6 header will be placed.
[out] aCommpressedNextHeader A boolean reference to output whether next header is compressed or not.
[in] aMacSource The MAC source address.
[in] aMacDest The MAC destination address.
[in] aBuf A pointer to the LOWPAN_IPHC header.
[in] aBufLength The number of bytes in aBuf.
Returns
The size of the compressed header in bytes or -1 if decompression fails.
References Lowpan::ComputeIid(), Lowpan::CopyContext(), Lowpan::DispatchToNextHeader(), ExitNow, LeaderBase::GetContext(), Header::GetDestination(), Header::GetSource(), ot::Encoding::BigEndian::HostSwap16(), Header::Init(), Lowpan::kHcContextId, Lowpan::kHcDispatch, Lowpan::kHcDispatchMask, Lowpan::kHcDstAddrContext, Lowpan::kHcDstAddrMode0, Lowpan::kHcDstAddrMode1, Lowpan::kHcDstAddrMode2, Lowpan::kHcDstAddrMode3, Lowpan::kHcDstAddrModeMask, Lowpan::kHcFlowLabel, Lowpan::kHcHopLimit1, Lowpan::kHcHopLimit255, Lowpan::kHcHopLimit64, Lowpan::kHcHopLimitMask, Lowpan::kHcMulticast, Lowpan::kHcNextHeader, Lowpan::kHcSrcAddrContext, Lowpan::kHcSrcAddrMode0, Lowpan::kHcSrcAddrMode1, Lowpan::kHcSrcAddrMode2, Lowpan::kHcSrcAddrMode3, Lowpan::kHcSrcAddrModeMask, Lowpan::kHcTrafficClass, Lowpan::kHcTrafficFlow, Lowpan::kHcTrafficFlowMask, Address::kInterfaceIdentifierSize, otIp6Address::OT_TOOL_PACKED_FIELD::m16, otIp6Address::OT_TOOL_PACKED_FIELD::m8, otIp6Address::mFields, Context::mPrefix, Context::mPrefixLength, OT_ERROR_NONE, OT_ERROR_PARSE, OT_NOOP, ot::Encoding::BigEndian::ReadUint16(), Header::SetHopLimit(), Address::SetIid(), Header::SetNextHeader(), SuccessOrExit, and VerifyOrExit.
Referenced by Lowpan::Decompress().
DecompressUdpHeader() [1/2]
int DecompressUdpHeader (Ip6::UdpHeader & aUdpHeader, const uint8_t * aBuf, uint16_t aBufLength)
This method decompresses a LOWPAN_NHC UDP header.
Parameters
[out] aUdpHeader A reference where the UDP header will be placed.
[in] aBuf A pointer to the LOWPAN_NHC header.
[in] aBufLength The number of bytes in aBuf.
Returns
The size of the compressed header in bytes or -1 if decompression fails.
References ExitNow, Lowpan::kUdpChecksum, Lowpan::kUdpDispatch, Lowpan::kUdpDispatchMask, Lowpan::kUdpPortMask, OT_ERROR_NONE, OT_ERROR_PARSE, OT_NOOP, ot::Encoding::BigEndian::ReadUint16(), UdpHeader::SetChecksum(), UdpHeader::SetDestinationPort(), UdpHeader::SetSourcePort(), and VerifyOrExit.
Referenced by Lowpan::Decompress(), and Lowpan::DecompressUdpHeader().
Compress() [2/2]
otError Compress (Message & aMessage, const Mac::Address & aMacSource, const Mac::Address & aMacDest, BufferWriter & aBuf, uint8_t & aHeaderDepth) private
References BufferWriter::Advance(), Lowpan::Compress(), Lowpan::CompressDestinationIid(), Lowpan::CompressExtensionHeader(), Lowpan::CompressMulticast(), Lowpan::CompressSourceIid(), Lowpan::CompressUdp(), ExitNow, LeaderBase::GetContext(), Header::GetDestination(), Header::GetHopLimit(), Header::GetNextHeader(), Message::GetOffset(), Header::GetSource(), IgnoreReturnValue, Address::IsLinkLocal(), Address::IsMulticast(), Address::IsUnspecified(), Lowpan::kExtHdrDispatch, Lowpan::kExtHdrEidIp6, Lowpan::kHcContextId, Lowpan::kHcDispatch, Lowpan::kHcDstAddrContext, Lowpan::kHcFlowLabel, Lowpan::kHcHopLimit1, Lowpan::kHcHopLimit255, Lowpan::kHcHopLimit64, Lowpan::kHcNextHeader, Lowpan::kHcSrcAddrContext, Lowpan::kHcTrafficClass, ot::Ip6::kProtoHopOpts, ot::Ip6::kProtoIp6, ot::Ip6::kProtoUdp, otIp6Address::OT_TOOL_PACKED_FIELD::m8, Context::mCompressFlag, Context::mContextId, otIp6Address::mFields, Message::MoveOffset(), OT_ERROR_NONE, OT_ERROR_PARSE, Message::Read(), Message::SetOffset(), SuccessOrExit, VerifyOrExit, and BufferWriter::Write().
CompressExtensionHeader()
otError CompressExtensionHeader (Message & aMessage, BufferWriter & aBuf, uint8_t & aNextHeader) private
References Message::GetLength(), ExtensionHeader::GetLength(), OptionHeader::GetLength(), ExtensionHeader::GetNextHeader(), Message::GetOffset(), OptionHeader::GetType(), Lowpan::kExtHdrDispatch, Lowpan::kExtHdrEidHbh, Lowpan::kExtHdrMaxLength, Lowpan::kExtHdrNextHeader, ot::Ip6::kProtoDstOpts, ot::Ip6::kProtoHopOpts, ot::Ip6::kProtoIp6, ot::Ip6::kProtoUdp, OptionPadN::kType, OptionPad1::kType, Message::MoveOffset(), OT_ERROR_FAILED, OT_ERROR_NONE, OT_ERROR_PARSE, Message::Read(), Message::SetOffset(), SuccessOrExit, VerifyOrExit, and BufferWriter::Write().
Referenced by Lowpan::Compress().
CompressSourceIid()
otError CompressSourceIid (const Mac::Address & aMacAddr, const Ip6::Address & aIpAddr, const Context & aContext, uint16_t & aHcCtl, BufferWriter & aBuf) private
References Lowpan::ComputeIid(), Address::GetIid(), Address::GetLocator(), Lowpan::kHcSrcAddrMode1, Lowpan::kHcSrcAddrMode2, Lowpan::kHcSrcAddrMode3, Address::kInterfaceIdentifierSize, otIp6Address::OT_TOOL_PACKED_FIELD::m8, otIp6Address::mFields, OT_ERROR_NONE, Address::SetShort(), SuccessOrExit, and BufferWriter::Write().
Referenced by Lowpan::Compress().
CompressDestinationIid()
otError CompressDestinationIid (const Mac::Address & aMacAddr, const Ip6::Address & aIpAddr, const Context & aContext, uint16_t & aHcCtl, BufferWriter & aBuf) private
References Lowpan::ComputeIid(), Address::GetIid(), Address::GetLocator(), Lowpan::kHcDstAddrMode1, Lowpan::kHcDstAddrMode2, Lowpan::kHcDstAddrMode3, Address::kInterfaceIdentifierSize, otIp6Address::OT_TOOL_PACKED_FIELD::m8, otIp6Address::mFields, OT_ERROR_NONE, Address::SetShort(), SuccessOrExit, and BufferWriter::Write().
Referenced by Lowpan::Compress().
CompressMulticast()
otError CompressMulticast (const Ip6::Address & aIpAddr, uint16_t & aHcCtl, BufferWriter & aBuf) private
References Lowpan::kHcDstAddrContext, Lowpan::kHcDstAddrMode0, Lowpan::kHcDstAddrMode1, Lowpan::kHcDstAddrMode2, Lowpan::kHcDstAddrMode3, Lowpan::kHcMulticast, otIp6Address::OT_TOOL_PACKED_FIELD::m8, otIp6Address::mFields, Context::mPrefix, Context::mPrefixLength, OT_ERROR_NONE, SuccessOrExit, and BufferWriter::Write().
Referenced by Lowpan::Compress().
CompressUdp()
otError CompressUdp (Message & aMessage, BufferWriter & aBuf) private
References UdpHeader::GetChecksumOffset(), UdpHeader::GetDestinationPort(), UdpHeader::GetLengthOffset(), Message::GetOffset(), UdpHeader::GetSourcePort(), Lowpan::kUdpDispatch, Message::MoveOffset(), OT_ERROR_NONE, OT_ERROR_PARSE, Message::Read(), Message::SetOffset(), SuccessOrExit, VerifyOrExit, and BufferWriter::Write().
Referenced by Lowpan::Compress().
DecompressExtensionHeader()
int DecompressExtensionHeader (Message & aMessage, const uint8_t * aBuf, uint16_t aBufLength) private
References Message::Append(), BitVectorBytes, Lowpan::DispatchToNextHeader(), OptionPadN::Init(), OptionPad1::Init(), Lowpan::kExtHdrNextHeader, Message::MoveOffset(), OT_ERROR_NONE, OT_ERROR_PARSE, OT_NOOP, SuccessOrExit, and VerifyOrExit.
Referenced by Lowpan::Decompress().
DecompressUdpHeader() [2/2]
int DecompressUdpHeader (Message & aMessage, const uint8_t * aBuf, uint16_t aBufLength, uint16_t aDatagramLength) private
References Message::Append(), Lowpan::DecompressUdpHeader(), Message::GetOffset(), Message::MoveOffset(), OT_ERROR_NONE, OT_NOOP, UdpHeader::SetLength(), and VerifyOrExit.
DispatchToNextHeader()
otError DispatchToNextHeader (uint8_t aDispatch, uint8_t & aNextHeader) private
References ExitNow, Lowpan::kExtHdrDispatch, Lowpan::kExtHdrDispatchMask, Lowpan::kExtHdrEidDst, Lowpan::kExtHdrEidFragment, Lowpan::kExtHdrEidHbh, Lowpan::kExtHdrEidIp6, Lowpan::kExtHdrEidMask, Lowpan::kExtHdrEidRouting, ot::Ip6::kProtoDstOpts, ot::Ip6::kProtoFragment, ot::Ip6::kProtoHopOpts, ot::Ip6::kProtoIp6, ot::Ip6::kProtoRouting, ot::Ip6::kProtoUdp, Lowpan::kUdpDispatch, Lowpan::kUdpDispatchMask, OT_ERROR_NONE, and OT_ERROR_PARSE.
Referenced by Lowpan::DecompressBaseHeader(), and Lowpan::DecompressExtensionHeader().
CopyContext()
void CopyContext (const Context & aContext, Ip6::Address & aAddress) static private
References Context::mPrefix, Context::mPrefixLength, and Address::SetPrefix().
Referenced by Lowpan::DecompressBaseHeader().
ComputeIid()
otError ComputeIid (const Mac::Address & aMacAddr, const Context & aContext, Ip6::Address & aIpAddress) static private
References ExitNow, Address::GetExtended(), Address::GetShort(), Address::GetType(), Address::kTypeExtended, Address::kTypeShort, otIp6Address::OT_TOOL_PACKED_FIELD::m8, otIp6Address::mFields, Context::mPrefix, Context::mPrefixLength, OT_ERROR_NONE, OT_ERROR_PARSE, Address::SetIid(), and Address::SetIidToLocator().
Referenced by Lowpan::CompressDestinationIid(), Lowpan::CompressSourceIid(), and Lowpan::DecompressBaseHeader().
The documentation for this class was generated from the following files:
lowpan.hpp
lowpan.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale