OpenThread: PendingDataset Class Reference
PendingDataset Class Reference
#include <dataset_manager.hpp>
Public Member Functions
void Clear (void)
void ClearNetwork (void)
PendingDataset (Instance &aInstance)
otError Save (const otOperationalDataset &aDataset)
otError Save (const Timestamp &aTimestamp, const Message &aMessage, uint16_t aOffset, uint8_t aLength)
Public Member Functions inherited from DatasetManager
otError ApplyConfiguration (void) const
int Compare (const Timestamp &aTimestamp) const
otError GetChannelMask (Mac::ChannelMask &aChannelMask) const
const Timestamp * GetTimestamp (void) const
void HandleDetach (void)
otError Read (Dataset &aDataset) const
otError Read (otOperationalDataset &aDataset) const
otError Restore (void)
otError SendGetRequest (const otOperationalDatasetComponents &aDatasetComponents, const uint8_t *aTlvTypes, uint8_t aLength, const otIp6Address *aAddress) const
otError SendSetRequest (const otOperationalDataset &aDataset, const uint8_t *aTlvs, uint8_t aLength)
Public Member Functions inherited from InstanceLocator
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Private Member Functions
void HandleDelayTimer (void)
void HandleGet (Coap::Message &aMessage, const Ip6::MessageInfo &aMessageInfo) const
void HandleTimer (void)
void StartDelayTimer (void)
Static Private Member Functions
static void HandleDelayTimer (Timer &aTimer)
static void HandleGet (void *aContext, otMessage *aMessage, const otMessageInfo *aMessageInfo)
static void HandleTimer (Timer &aTimer)
Private Attributes
TimerMilli mDelayTimer
Coap::Resource mResourceGet
Additional Inherited Members
Protected Member Functions inherited from DatasetManager
void Clear (void)
DatasetManager (Instance &aInstance, Dataset::Type aType, const char *aUriGet, const char *aUriSet, TimerMilli::Handler aTimerHandler)
void HandleGet (const Coap::Message &aMessage, const Ip6::MessageInfo &aMessageInfo) const
void HandleNetworkUpdate (void)
void HandleTimer (void)
otError Save (const Dataset &aDataset)
otError Save (const otOperationalDataset &aDataset)
otError Save (const Timestamp &aTimestamp, const Message &aMessage, uint16_t aOffset, uint8_t aLength)
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Attributes inherited from DatasetManager
DatasetLocal mLocal
Timestamp mTimestamp
bool mTimestampValid: 1
ot::MeshCoP::DatasetManager::DatasetTlv OT_TOOL_PACKED_END
Constructor & Destructor Documentation
PendingDataset()
PendingDataset (Instance & aInstance) explicit
Constructor.
Parameters
[in] The Thread network interface.
References PendingDataset::mResourceGet.
Member Function Documentation
Clear()
void Clear (void)
This method clears the Pending Operational Dataset.
This method also stops the Delay Timer if it was active.
References DatasetManager::Clear(), PendingDataset::mDelayTimer, and TimerMilli::Stop().
Referenced by PendingDataset::HandleDelayTimer().
ClearNetwork()
void ClearNetwork (void)
This method clears the network Pending Operational Dataset.
This method also stops the Delay Timer if it was active.
References DatasetLocal::GetType(), Timestamp::Init(), DatasetManager::mLocal, DatasetManager::mTimestamp, DatasetManager::mTimestampValid, and DatasetManager::Save().
Save() [1/2]
otError Save (const otOperationalDataset & aDataset)
This method saves the Operational Dataset in non-volatile memory.
This method also starts the Delay Timer.
Parameters
[in] aDataset The Operational Dataset.
References OT_ERROR_NONE, DatasetManager::Save(), PendingDataset::StartDelayTimer(), and SuccessOrExit.
Referenced by PendingDataset::HandleDelayTimer().
Save() [2/2]
otError Save (const Timestamp & aTimestamp, const Message & aMessage, uint16_t aOffset, uint8_t aLength)
This method sets the Operational Dataset for the partition.
This method also updates the non-volatile version if the partition's Operational Dataset is newer.
This method also starts the Delay Timer.
Parameters
[in] aTimestamp The timestamp for the Operational Dataset.
[in] aMessage The message buffer.
[in] aOffset The offset where the Operational Dataset begins.
[in] aLength The length of the Operational Dataset.
References DatasetLocal::GetType(), DatasetManager::mLocal, OT_ERROR_NONE, DatasetManager::Save(), PendingDataset::StartDelayTimer(), and SuccessOrExit.
StartDelayTimer()
void StartDelayTimer (void) private
References DelayTimerTlv::GetDelayTimer(), Tlv::GetTlv(), DatasetLocal::GetType(), Timer::kMaxDelay, PendingDataset::mDelayTimer, DatasetManager::mLocal, otLogInfoMeshCoP, DatasetLocal::Read(), TimerMilli::StartAt(), and TimerMilli::Stop().
Referenced by PendingDataset::Save().
HandleTimer() [1/2]
void HandleTimer (Timer & aTimer) static private
References OwnerLocator::GetOwner(), and PendingDataset::HandleTimer().
HandleTimer() [2/2]
void HandleTimer (void) inline private
References DatasetManager::HandleGet(), and DatasetManager::HandleTimer().
Referenced by PendingDataset::HandleTimer().
HandleDelayTimer() [1/2]
void HandleDelayTimer (Timer & aTimer) static private
References OwnerLocator::GetOwner(), and PendingDataset::HandleDelayTimer().
HandleDelayTimer() [2/2]
void HandleDelayTimer (void) private
References PendingDataset::Clear(), ExitNow, DelayTimerTlv::GetDelayTimer(), Timer::GetFireTime(), Tlv::GetTlv(), DatasetLocal::GetType(), PendingDataset::mDelayTimer, DatasetManager::mLocal, otLogInfoMeshCoP, DatasetLocal::Read(), PendingDataset::Save(), and TimerMilli::StartAt().
Referenced by PendingDataset::HandleDelayTimer().
HandleGet() [1/2]
void HandleGet (void * aContext, otMessage * aMessage, const otMessageInfo * aMessageInfo) static private
HandleGet() [2/2]
void HandleGet (Coap::Message & aMessage, const Ip6::MessageInfo & aMessageInfo) const private
References DatasetManager::HandleGet().
Field Documentation
mDelayTimer
TimerMilli mDelayTimer private
Referenced by PendingDataset::Clear(), PendingDataset::HandleDelayTimer(), and PendingDataset::StartDelayTimer().
mResourceGet
Coap::Resource mResourceGet private
Referenced by PendingDataset::PendingDataset().
The documentation for this class was generated from the following files:
dataset_manager.hpp
dataset_manager.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale