OpenThread: HmacSha256 Class Reference
HmacSha256 Class Reference
Core-security
#include <hmac_sha256.hpp>
Public Types
enum { kHashSize = 32 }
Public Member Functions
void Finish (uint8_t aHash[kHashSize])
HmacSha256 ()
void Start (const uint8_t *aKey, uint16_t aKeyLength)
void Update (const uint8_t *aBuf, uint16_t aBufLength)
~HmacSha256 ()
Private Attributes
mbedtls_md_context_t mContext
Detailed Description
This class implements HMAC SHA-256 computation.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
kHashSize
SHA-256 hash size (bytes)
Constructor & Destructor Documentation
HmacSha256()
HmacSha256 ()
Constructor for initialization of mbedtls_md_context_t.
References HmacSha256::mContext.
~HmacSha256()
~HmacSha256 ()
Destructor for freeing of mbedtls_md_context_t.
References HmacSha256::mContext.
Member Function Documentation
Start()
void Start (const uint8_t * aKey, uint16_t aKeyLength)
This method sets the key.
Parameters
[in] aKey A pointer to the key.
[in] aKeyLength The key length in bytes.
References HmacSha256::mContext.
Referenced by KeyManager::ComputeKey(), and otCryptoHmacSha256().
Update()
void Update (const uint8_t * aBuf, uint16_t aBufLength)
This method inputs bytes into the HMAC computation.
Parameters
[in] aBuf A pointer to the input buffer.
[in] aBufLength The length of aBuf in bytes.
References HmacSha256::mContext.
Referenced by KeyManager::ComputeKey(), and otCryptoHmacSha256().
Finish()
void Finish (uint8_t aHash[kHashSize])
This method finalizes the hash computation.
Parameters
[out] aHash A pointer to the output buffer.
References HmacSha256::mContext.
Referenced by KeyManager::ComputeKey(), and otCryptoHmacSha256().
Field Documentation
mContext
mbedtls_md_context_t mContext private
Referenced by HmacSha256::Finish(), HmacSha256::HmacSha256(), HmacSha256::Start(), HmacSha256::Update(), and HmacSha256::~HmacSha256().
The documentation for this class was generated from the following files:
hmac_sha256.hpp
hmac_sha256.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale