OpenThread: Leader Class Reference
Leader Class Reference
#include <leader.hpp>
Public Types
enum DomainPrefixState {
kDomainPrefixNone = 0, kDomainPrefixAdded, kDomainPrefixRemoved, kDomainPrefixRefreshed,
kDomainPrefixUnchanged
}
enum State {
kStateNone = 0, kStateAdded, kStateRemoved, kStateToTriggerRereg,
kStateRefreshed, kStateUnchanged
}
Public Member Functions
otError GetConfig (BackboneRouterConfig &aConfig) const
const otIp6Prefix * GetDomainPrefix (void) const
uint16_t GetServer16 (void) const
otError GetServiceId (uint8_t &aServiceId) const
bool HasDomainPrefix (void) const
bool HasPrimary (void) const
Leader (Instance &aInstance)
void Reset (void)
void Update (void)
Public Member Functions inherited from InstanceLocator
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Private Member Functions
void LogBackboneRouterPrimary (State, const BackboneRouterConfig &) const
void LogDomainPrefix (DomainPrefixState, const otIp6Prefix &) const
void UpdateBackboneRouterPrimary (void)
void UpdateDomainPrefixConfig (void)
Private Attributes
BackboneRouterConfig mConfig
Primary Backbone Router information.
otIp6Prefix mDomainPrefix
Domain Prefix on the Thread Network.
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Detailed Description
This class implements the basic Primary Backbone Router service operations.
Member Enumeration Documentation
State
enum State
Enumerator
kStateNone
Not exist (trigger Backbone Router register its service).
kStateAdded
Newly added.
kStateRemoved
Newly removed (trigger Backbone Router register its service).
kStateToTriggerRereg
Short address or sequence number changes (trigger re-registration). May also have ReregistrationDelay or MlrTimeout update.
kStateRefreshed
Only ReregistrationDelay or MlrTimeout changes.
kStateUnchanged
No change on Primary Backbone Router information (only for logging).
DomainPrefixState
enum DomainPrefixState
Enumerator
kDomainPrefixNone
Not available.
kDomainPrefixAdded
Added.
kDomainPrefixRemoved
Removed.
kDomainPrefixRefreshed
Changed.
kDomainPrefixUnchanged
Nothing changed.
Constructor & Destructor Documentation
Leader()
Leader (Instance & aInstance) explicit
This constructor initializes the Leader.
Parameters
[in] aInstance A reference to the OpenThread instance.
References Leader::Reset().
Member Function Documentation
Reset()
void Reset (void)
This method resets the cached Primary Backbone Router.
References ot::Mac::kShortAddrInvalid, Leader::mConfig, Leader::mDomainPrefix, otIp6Prefix::mLength, and otBackboneRouterConfig::mServer16.
Referenced by Leader::Leader().
Update()
void Update (void)
This method updates the cached Primary Backbone Router if any when new network data is available.
References Leader::UpdateBackboneRouterPrimary(), and Leader::UpdateDomainPrefixConfig().
GetConfig()
otError GetConfig (BackboneRouterConfig & aConfig) const
This method gets the Primary Backbone Router in the Thread Network.
Parameters
[out] aConfig The Primary Backbone Router information.
Return values
OT_ERROR_NONE Successfully got the Primary Backbone Router information.
OT_ERROR_NOT_FOUND No Backbone Router in the Thread Network.
References Leader::HasPrimary(), Leader::mConfig, OT_ERROR_NONE, OT_ERROR_NOT_FOUND, and VerifyOrExit.
GetServiceId()
otError GetServiceId (uint8_t & aServiceId) const
This method gets the Backbone Router Service ID.
Parameters
[out] aServiceId The reference whether to put the Backbone Router Service ID.
Return values
OT_ERROR_NONE Successfully got the Backbone Router Service ID.
OT_ERROR_NOT_FOUND Backbone Router service doesn't exist.
References Leader::HasPrimary(), Leader::kDomainPrefixAdded, Leader::kDomainPrefixNone, Leader::kDomainPrefixRefreshed, Leader::kDomainPrefixRemoved, Leader::kDomainPrefixUnchanged, ServiceTlv::kServiceDataBackboneRouter, Leader::kStateAdded, Leader::kStateNone, Leader::kStateRefreshed, Leader::kStateRemoved, Leader::kStateToTriggerRereg, Leader::kStateUnchanged, ServiceTlv::kThreadEnterpriseNumber, Leader::LogBackboneRouterPrimary(), Leader::LogDomainPrefix(), otIp6Prefix::mLength, otBackboneRouterConfig::mMlrTimeout, otIp6Prefix::mPrefix, otBackboneRouterConfig::mReregistrationDelay, otBackboneRouterConfig::mSequenceNumber, otBackboneRouterConfig::mServer16, OT_ERROR_NONE, OT_ERROR_NOT_FOUND, OT_UNUSED_VARIABLE, otLogInfoBbr, and VerifyOrExit.
GetServer16()
uint16_t GetServer16 (void) const inline
This method gets the short address of the Primary Backbone Router.
Returns
short address of Primary Backbone Router, or Mac::kShortAddrInvalid if no Primary Backbone Router.
References Leader::mConfig, and otBackboneRouterConfig::mServer16.
HasPrimary()
bool HasPrimary (void) const inline
This method indicates whether or not there is Primary Backbone Router.
Return values
TRUE if there is Primary Backbone Router, FALSE otherwise.
References ot::Mac::kShortAddrInvalid, Leader::mConfig, and otBackboneRouterConfig::mServer16.
Referenced by Leader::GetConfig(), and Leader::GetServiceId().
GetDomainPrefix()
const otIp6Prefix* GetDomainPrefix (void) const inline
This method gets the Domain Prefix in the Thread Network.
Return values
A pointer to the Domain Prefix or NULL if there is no Domain Prefix.
References Leader::mDomainPrefix, and otIp6Prefix::mLength.
HasDomainPrefix()
bool HasDomainPrefix (void) const inline
This method indicates whether or not the Domain Prefix is available in the Thread Network.
Return values
TRUE if there is Domain Prefix, FALSE otherwise.
References Leader::LogBackboneRouterPrimary(), Leader::LogDomainPrefix(), Leader::mDomainPrefix, otIp6Prefix::mLength, Leader::UpdateBackboneRouterPrimary(), and Leader::UpdateDomainPrefixConfig().
UpdateBackboneRouterPrimary()
void UpdateBackboneRouterPrimary (void) private
References ot::Mac::kShortAddrInvalid, Leader::kStateAdded, Leader::kStateNone, Leader::kStateRefreshed, Leader::kStateRemoved, Leader::kStateToTriggerRereg, Leader::kStateUnchanged, Leader::LogBackboneRouterPrimary(), Leader::mConfig, otBackboneRouterConfig::mMlrTimeout, otBackboneRouterConfig::mReregistrationDelay, otBackboneRouterConfig::mSequenceNumber, and otBackboneRouterConfig::mServer16.
Referenced by Leader::HasDomainPrefix(), and Leader::Update().
UpdateDomainPrefixConfig()
void UpdateDomainPrefixConfig (void) private
References BitVectorBytes, Leader::kDomainPrefixAdded, Leader::kDomainPrefixNone, Leader::kDomainPrefixRefreshed, Leader::kDomainPrefixRemoved, Leader::kDomainPrefixUnchanged, ot::NetworkData::kIteratorInit, Leader::LogDomainPrefix(), otIp6Address::OT_TOOL_PACKED_FIELD::m8, Leader::mDomainPrefix, otBorderRouterConfig::mDp, otIp6Address::mFields, otIp6Prefix::mLength, otBorderRouterConfig::mPrefix, otIp6Prefix::mPrefix, OT_ERROR_NONE, and Address::PrefixMatch().
Referenced by Leader::HasDomainPrefix(), and Leader::Update().
LogBackboneRouterPrimary()
void LogBackboneRouterPrimary (State , const BackboneRouterConfig &) const inline private
Referenced by Leader::GetServiceId(), Leader::HasDomainPrefix(), and Leader::UpdateBackboneRouterPrimary().
LogDomainPrefix()
void LogDomainPrefix (DomainPrefixState , const otIp6Prefix &) const inline private
Referenced by Leader::GetServiceId(), Leader::HasDomainPrefix(), and Leader::UpdateDomainPrefixConfig().
Field Documentation
mConfig
BackboneRouterConfig mConfig private
Primary Backbone Router information.
Referenced by Leader::GetConfig(), Leader::GetServer16(), Leader::HasPrimary(), Leader::Reset(), and Leader::UpdateBackboneRouterPrimary().
mDomainPrefix
otIp6Prefix mDomainPrefix private
Domain Prefix on the Thread Network.
Referenced by Leader::GetDomainPrefix(), Leader::HasDomainPrefix(), Leader::Reset(), and Leader::UpdateDomainPrefixConfig().
The documentation for this class was generated from the following files:
leader.hpp
leader.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale