OpenThread: LinkedListEntry< Type > Class Template Reference
LinkedListEntry< Type > Class Template Reference
Core-linked-list
#include <linked_list.hpp>
Public Member Functions
const Type * GetNext (void) const
Type * GetNext (void)
void SetNext (Type *aNext)
Detailed Description
template<class Type>
class ot::LinkedListEntry< Type >
This template class represents a linked list entry.
This class provides methods to GetNext() and SetNext() in the linked list entry.
Users of this class should follow CRTP-style inheritance, i.e., the Type class itself should publicly inherit from LinkedListEntry<Type>.
The template type Type should contain a mNext member variable. The mNext should be of a type that can be down-casted to Type itself.
Member Function Documentation
GetNext() [1/2]
const Type* GetNext (void) const inline
This method gets the next entry in the linked list.
Returns
A pointer to the next entry in the linked list or NULL if at the end of the list.
Referenced by TimerScheduler::Add(), Netif::AddExternalUnicastAddress(), Mle::AppendAddressRegistration(), Mle::HasUnregisteredAddress(), Ip6::IsOnLink(), Netif::RemoveExternalUnicastAddress(), and Ip6::SelectSourceAddress().
GetNext() [2/2]
Type* GetNext (void) inline
This method gets the next entry in the linked list.
Returns
A pointer to the next entry in the linked list or NULL if at the end of the list.
SetNext()
void SetNext (Type * aNext) inline
This method sets the next pointer on the entry.
Parameters
[in] aNext A pointer to the next entry.
Referenced by TimerScheduler::Remove(), Udp::RemoveReceiver(), CoapBase::RemoveResource(), Udp::RemoveSocket(), Netif::SubscribeAllRoutersMulticast(), Netif::UnsubscribeAllNodesMulticast(), and Netif::UnsubscribeAllRoutersMulticast().
The documentation for this class was generated from the following file:
linked_list.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale