OpenThread: Flash Class Reference
Flash Class Reference
#include <flash.hpp>
Data Structures
class Record
class RecordHeader
Public Member Functions
otError Add (uint16_t aKey, const uint8_t *aValue, uint16_t aValueLength)
otError Delete (uint16_t aKey, int aIndex)
Flash (Instance &aInstance)
otError Get (uint16_t aKey, int aIndex, uint8_t *aValue, uint16_t *aValueLength) const
void Init (void)
otError Set (uint16_t aKey, const uint8_t *aValue, uint16_t aValueLength)
void Wipe (void)
Public Member Functions inherited from InstanceLocator
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Private Types
enum { kSwapMarkerSize = 4 }
Private Member Functions
otError Add (uint16_t aKey, bool aFirst, const uint8_t *aValue, uint16_t aValueLength)
bool DoesValidRecordExist (uint32_t aOffset, uint16_t aKey) const
void SanitizeFreeSpace (void)
void Swap (void)
Private Attributes
uint8_t mSwapIndex
uint32_t mSwapSize
uint32_t mSwapUsed
OT_TOOL_PACKED_BEGIN class ot::Flash::RecordHeader OT_TOOL_PACKED_END
ot::Flash::Record OT_TOOL_PACKED_END
Static Private Attributes
static const uint32_t sSwapActive = 0xbe5cc5ee
static const uint32_t sSwapInactive = 0xbe5cc5ec
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Detailed Description
This class implements the flash storage driver.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
kSwapMarkerSize
Constructor & Destructor Documentation
Flash()
Flash (Instance & aInstance) inline
Constructor.
References Flash::Add(), Flash::Delete(), InstanceLocator::Get(), Flash::Init(), Flash::Set(), and Flash::Wipe().
Member Function Documentation
Init()
void Init (void)
This method initializes the flash storage driver.
References ExitNow, InstanceLocator::GetInstance(), Flash::RecordHeader::GetSize(), Flash::RecordHeader::IsAddBeginSet(), Flash::RecordHeader::IsAddCompleteSet(), Flash::kSwapMarkerSize, Flash::mSwapIndex, Flash::mSwapSize, Flash::mSwapUsed, otPlatFlashGetSwapSize(), otPlatFlashInit(), otPlatFlashRead(), Flash::SanitizeFreeSpace(), Flash::sSwapActive, and Flash::Wipe().
Referenced by Flash::Flash().
Get()
otError Get (uint16_t aKey, int aIndex, uint8_t * aValue, uint16_t * aValueLength) const
This method fetches the value identified by aKey.
Parameters
[in] aKey The key associated with the requested value.
[in] aIndex The index of the specific item to get.
[out] aValue A pointer to where the value of the setting should be written. May be NULL if just testing for the presence or length of a key.
[in,out] aValueLength A pointer to the length of the value. When called, this should point to an integer containing the maximum bytes that can be written to aValue. At return, the actual length of the setting is written. May be NULL if performing a presence check.
Return values
OT_ERROR_NONE The value was fetched successfully.
OT_ERROR_NOT_FOUND The key was not found.
References InstanceLocator::GetInstance(), Flash::RecordHeader::GetKey(), Flash::RecordHeader::GetLength(), Flash::RecordHeader::GetSize(), Flash::RecordHeader::IsFirst(), Flash::RecordHeader::IsValid(), Flash::kSwapMarkerSize, Flash::mSwapIndex, Flash::mSwapUsed, OT_ERROR_NONE, OT_ERROR_NOT_FOUND, and otPlatFlashRead().
Set()
otError Set (uint16_t aKey, const uint8_t * aValue, uint16_t aValueLength)
This method sets or replaces the value identified by aKey.
If there was more than one value previously associated with aKey, then they are all deleted and replaced with this single entry.
Parameters
[in] aKey The key associated with the value.
[in] aValue A pointer to where the new value of the setting should be read from. MUST NOT be NULL if aValueLength is non-zero.
[in] aValueLength The length of the data pointed to by aValue. May be zero.
Return values
OT_ERROR_NONE The value was changed.
OT_ERROR_NO_BUFS Not enough space to store the value.
References Flash::Add().
Referenced by Flash::Flash().
Add() [1/2]
otError Add (uint16_t aKey, const uint8_t * aValue, uint16_t aValueLength)
This method adds a value to aKey.
Parameters
[in] aKey The key associated with the value.
[in] aValue A pointer to where the new value of the setting should be read from. MUST NOT be NULL if aValueLength is non-zero.
[in] aValueLength The length of the data pointed to by aValue. May be zero.
Return values
OT_ERROR_NONE The value was added.
OT_ERROR_NO_BUFS Not enough space to store the value.
References InstanceLocator::Get(), and OT_ERROR_NOT_FOUND.
Referenced by Flash::Flash(), and Flash::Set().
Delete()
otError Delete (uint16_t aKey, int aIndex)
This method removes a value from aKey.
Parameters
[in] aKey The key associated with the value.
[in] aIndex The index of the value to be removed. If set to -1, all values for aKey will be removed.
Return values
OT_ERROR_NONE The given key and index was found and removed successfully.
OT_ERROR_NOT_FOUND The given key or index was not found.
References InstanceLocator::GetInstance(), Flash::RecordHeader::GetKey(), Flash::RecordHeader::GetSize(), Flash::RecordHeader::IsFirst(), Flash::RecordHeader::IsValid(), Flash::kSwapMarkerSize, Flash::mSwapIndex, Flash::mSwapUsed, OT_ERROR_NONE, OT_ERROR_NOT_FOUND, otPlatFlashRead(), otPlatFlashWrite(), Flash::RecordHeader::SetDeleted(), and Flash::RecordHeader::SetFirst().
Referenced by Flash::Flash().
Wipe()
void Wipe (void)
This method removes all values.
References InstanceLocator::GetInstance(), Flash::mSwapIndex, Flash::mSwapUsed, otPlatFlashErase(), otPlatFlashWrite(), and Flash::sSwapActive.
Referenced by Flash::Flash(), and Flash::Init().
Add() [2/2]
otError Add (uint16_t aKey, bool aFirst, const uint8_t * aValue, uint16_t aValueLength) private
References InstanceLocator::GetInstance(), Flash::RecordHeader::GetSize(), Flash::RecordHeader::Init(), Flash::kSwapMarkerSize, Flash::mSwapIndex, Flash::mSwapSize, Flash::mSwapUsed, OT_ASSERT, OT_ERROR_NO_BUFS, OT_ERROR_NONE, otPlatFlashWrite(), Flash::RecordHeader::SetAddCompleteFlag(), Flash::Record::SetData(), Flash::Swap(), and VerifyOrExit.
DoesValidRecordExist()
bool DoesValidRecordExist (uint32_t aOffset, uint16_t aKey) const private
References ExitNow, InstanceLocator::GetInstance(), Flash::RecordHeader::GetKey(), Flash::RecordHeader::GetSize(), Flash::RecordHeader::IsFirst(), Flash::RecordHeader::IsValid(), Flash::mSwapIndex, Flash::mSwapUsed, and otPlatFlashRead().
Referenced by Flash::Swap().
SanitizeFreeSpace()
void SanitizeFreeSpace (void) private
References ExitNow, InstanceLocator::GetInstance(), Flash::mSwapIndex, Flash::mSwapSize, Flash::mSwapUsed, otPlatFlashRead(), and Flash::Swap().
Referenced by Flash::Init().
Swap()
void Swap (void) private
References Flash::DoesValidRecordExist(), InstanceLocator::GetInstance(), Flash::RecordHeader::GetKey(), Flash::RecordHeader::GetSize(), Flash::RecordHeader::IsAddBeginSet(), Flash::RecordHeader::IsValid(), Flash::kSwapMarkerSize, Flash::mSwapIndex, Flash::mSwapUsed, OT_NOOP, otPlatFlashErase(), otPlatFlashRead(), otPlatFlashWrite(), Flash::sSwapActive, Flash::sSwapInactive, and VerifyOrExit.
Referenced by Flash::Add(), and Flash::SanitizeFreeSpace().
Field Documentation
sSwapActive
const uint32_t sSwapActive = 0xbe5cc5ee static private
Referenced by Flash::Init(), Flash::Swap(), and Flash::Wipe().
sSwapInactive
const uint32_t sSwapInactive = 0xbe5cc5ec static private
Referenced by Flash::Swap().
OT_TOOL_PACKED_END [1/2]
OT_TOOL_PACKED_BEGIN class ot::Flash::RecordHeader OT_TOOL_PACKED_END private
OT_TOOL_PACKED_END [2/2]
ot::Flash::Record OT_TOOL_PACKED_END private
mSwapSize
uint32_t mSwapSize private
Referenced by Flash::Add(), Flash::Init(), and Flash::SanitizeFreeSpace().
mSwapUsed
uint32_t mSwapUsed private
Referenced by Flash::Add(), Flash::Delete(), Flash::DoesValidRecordExist(), Flash::Get(), Flash::Init(), Flash::SanitizeFreeSpace(), Flash::Swap(), and Flash::Wipe().
mSwapIndex
uint8_t mSwapIndex private
Referenced by Flash::Add(), Flash::Delete(), Flash::DoesValidRecordExist(), Flash::Get(), Flash::Init(), Flash::SanitizeFreeSpace(), Flash::Swap(), and Flash::Wipe().
The documentation for this class was generated from the following files:
flash.hpp
flash.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale