OpenThread: ResourceRecordAaaa Class Reference
ResourceRecordAaaa Class Reference
Core-dns
#include <dns_headers.hpp>
Public Types
enum { kType = 0x1C, kClass = 0x01, kLength = 16 }
Public Member Functions
otIp6Address & GetAddress (void)
void Init (void)
void SetAddress (otIp6Address &aAddress)
Public Member Functions inherited from ResourceRecord
uint16_t GetClass (void) const
uint16_t GetLength (void) const
uint32_t GetTtl (void) const
uint16_t GetType (void) const
void SetClass (uint16_t aClass)
void SetLength (uint16_t aLength)
void SetTtl (uint32_t aTtl)
void SetType (uint16_t aType)
Private Attributes
otIp6Address mAddress
IPv6 Address of AAAA Resource Record.
Detailed Description
This class implements Resource Record body format of AAAA type.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
kType
AAAA Resource Record type.
kClass
The value of the Internet class.
kLength
Size of the AAAA Resource Record type.
Member Function Documentation
Init()
void Init (void) inline
This method initializes the AAAA Resource Record.
References ResourceRecord::SetClass(), ResourceRecord::SetLength(), ResourceRecord::SetTtl(), and ResourceRecord::SetType().
SetAddress()
void SetAddress (otIp6Address & aAddress) inline
This method sets the IPv6 address of the resource record.
Parameters
[in] aAddress The IPv6 address of the resource record.
GetAddress()
otIp6Address& GetAddress (void) inline
This method returns the reference to IPv6 address of the resource record.
Returns
The reference to IPv6 address of the resource record.
Field Documentation
mAddress
otIp6Address mAddress private
IPv6 Address of AAAA Resource Record.
The documentation for this class was generated from the following file:
dns_headers.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale