OpenThread: DeviceMode Class Reference
DeviceMode Class Reference
MLE » Core
#include <mle_types.hpp>
Public Types
enum {
kModeRxOnWhenIdle = 1 << 3, kModeSecureDataRequest = 1 << 2, kModeFullThreadDevice = 1 << 1, kModeFullNetworkData = 1 << 0,
kInfoStringSize = 45
}
typedef String< kInfoStringSize > InfoString
typedef otLinkModeConfig ModeConfig
Public Member Functions
DeviceMode (void)
DeviceMode (uint8_t aMode)
DeviceMode (ModeConfig aModeConfig)
uint8_t Get (void) const
void Get (ModeConfig &aModeConfig) const
bool IsFullNetworkData (void) const
bool IsFullThreadDevice (void) const
bool IsMinimalEndDevice (void) const
bool IsRxOnWhenIdle (void) const
bool IsSecureDataRequest (void) const
bool IsValid (void) const
bool operator!= (const DeviceMode &aOther) const
bool operator== (const DeviceMode &aOther) const
void Set (uint8_t aMode)
void Set (const ModeConfig &aModeConfig)
InfoString ToString (void) const
Private Attributes
uint8_t mMode
Detailed Description
This type represents a MLE device mode.
Member Typedef Documentation
InfoString
typedef String<kInfoStringSize> InfoString
This type defines the fixed-length String object returned from ToString().
ModeConfig
typedef otLinkModeConfig ModeConfig
This structure represents an MLE Mode configuration.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
kModeRxOnWhenIdle
If the device has its receiver on when not transmitting.
kModeSecureDataRequest
If the device uses link layer security for all data requests.
kModeFullThreadDevice
If the device is an FTD.
kModeFullNetworkData
If the device requires the full Network Data.
kInfoStringSize
String buffer size used for ToString().
Constructor & Destructor Documentation
DeviceMode() [1/3]
DeviceMode (void) inline
This is the default constructor for DeviceMode object.
DeviceMode() [2/3]
DeviceMode (uint8_t aMode) inline explicit
This constructor initializes a DeviceMode object from a given mode TLV bitmask.
Parameters
[in] aMode A mode TLV bitmask to initialize the DeviceMode object.
DeviceMode() [3/3]
DeviceMode (ModeConfig aModeConfig) inline explicit
This constructor initializes a DeviceMode object from a given mode configuration structure.
Parameters
[in] aModeConfig A mode configuration to initialize the DeviceMode object.
References DeviceMode::Set().
Member Function Documentation
Get() [1/2]
uint8_t Get (void) const inline
This method gets the device mode as a mode TLV bitmask.
Returns
The device mode as a mode TLV bitmask.
References DeviceMode::mMode.
Referenced by Mle::AppendMode(), DeviceMode::Set(), Neighbor::SetDeviceMode(), Mle::SetDeviceMode(), ModeTlv::SetMode(), ChildTableEntry::SetMode(), and Mle::Store().
Set() [1/2]
void Set (uint8_t aMode) inline
This method sets the device mode from a given mode TLV bitmask.
Parameters
[in] aMode A mode TLV bitmask.
References DeviceMode::Get(), and DeviceMode::mMode.
Referenced by DeviceMode::DeviceMode(), and Mle::Restore().
Get() [2/2]
void Get (ModeConfig & aModeConfig) const
This method gets the device mode as a mode configuration structure.
Parameters
[out] aModeConfig A reference to a mode configuration structure to output the device mode.
References DeviceMode::IsFullNetworkData(), DeviceMode::IsFullThreadDevice(), DeviceMode::IsRxOnWhenIdle(), DeviceMode::IsSecureDataRequest(), otLinkModeConfig::mDeviceType, otLinkModeConfig::mNetworkData, otLinkModeConfig::mRxOnWhenIdle, and otLinkModeConfig::mSecureDataRequests.
Set() [2/2]
void Set (const ModeConfig & aModeConfig)
this method sets the device mode from a given mode configuration structure.
Parameters
[in] aModeConfig A mode configuration structure.
References DeviceMode::kModeFullNetworkData, DeviceMode::kModeFullThreadDevice, DeviceMode::kModeRxOnWhenIdle, DeviceMode::kModeSecureDataRequest, otLinkModeConfig::mDeviceType, DeviceMode::mMode, otLinkModeConfig::mNetworkData, otLinkModeConfig::mRxOnWhenIdle, and otLinkModeConfig::mSecureDataRequests.
IsRxOnWhenIdle()
bool IsRxOnWhenIdle (void) const inline
This method indicates whether or not the device is rx-on-when-idle.
Return values
TRUE If the device is rx-on-when-idle (non-sleepy).
FALSE If the device is not rx-on-when-idle (sleepy).
References DeviceMode::kModeRxOnWhenIdle, and DeviceMode::mMode.
Referenced by DeviceMode::Get(), Neighbor::IsRxOnWhenIdle(), DeviceMode::IsValid(), and DeviceMode::ToString().
IsSecureDataRequest()
bool IsSecureDataRequest (void) const inline
This method indicates whether or not the device uses secure IEEE 802.15.4 Data Request messages.
Return values
TRUE If the device uses secure IEEE 802.15.4 Data Request (data poll) messages.
FALSE If the device uses any IEEE 802.15.4 Data Request (data poll) messages.
References DeviceMode::kModeSecureDataRequest, and DeviceMode::mMode.
Referenced by DeviceMode::Get(), Neighbor::IsSecureDataRequest(), and DeviceMode::ToString().
IsFullThreadDevice()
bool IsFullThreadDevice (void) const inline
This method indicates whether or not the device is a Full Thread Device.
Return values
TRUE If the device is Full Thread Device.
FALSE If the device if not Full Thread Device.
References DeviceMode::kModeFullThreadDevice, and DeviceMode::mMode.
Referenced by DeviceMode::Get(), Neighbor::IsFullThreadDevice(), DeviceMode::IsValid(), Mle::SetDeviceMode(), and DeviceMode::ToString().
IsFullNetworkData()
bool IsFullNetworkData (void) const inline
This method indicates whether or not the device requests Full Network Data.
Return values
TRUE If the device requests Full Network Data.
FALSE If the device does not request Full Network Data (only stable Network Data).
References DeviceMode::kModeFullNetworkData, and DeviceMode::mMode.
Referenced by DeviceMode::Get(), Neighbor::IsFullNetworkData(), and DeviceMode::ToString().
IsMinimalEndDevice()
bool IsMinimalEndDevice (void) const inline
This method indicates whether or not the device is a Minimal End Device.
Return values
TRUE If the device is a Minimal End Device.
FALSE If the device is not a Minimal End Device.
References DeviceMode::kModeFullThreadDevice, DeviceMode::kModeRxOnWhenIdle, and DeviceMode::mMode.
IsValid()
bool IsValid (void) const inline
This method indicates whether or not the device mode flags are valid.
An FTD which is not rx-on-when-idle (is sleepy) is considered invalid.
Returns
TRUE if , FALSE otherwise.
Return values
TRUE If the device mode flags are valid.
FALSE If the device mode flags are not valid.
References DeviceMode::IsFullThreadDevice(), and DeviceMode::IsRxOnWhenIdle().
Referenced by Mle::SetDeviceMode().
operator==()
bool operator== (const DeviceMode & aOther) const inline
This method overloads operator == to evaluate whether or not two device modes are equal
Parameters
[in] aOther The other device mode to compare with.
Return values
TRUE If the device modes are equal.
FALSE If the device modes are not equal.
References DeviceMode::mMode.
operator!=()
bool operator!= (const DeviceMode & aOther) const inline
This method overloads operator != to evaluate whether or not two device modes are not equal.
Parameters
[in] aOther The other device mode to compare with.
Return values
TRUE If the device modes are not equal.
FALSE If the device modes are equal.
References DeviceMode::ToString().
ToString()
DeviceMode::InfoString ToString (void) const
This method converts the device mode into a human-readable string.
Returns
An InfoString object representing the device mode.
References DeviceMode::IsFullNetworkData(), DeviceMode::IsFullThreadDevice(), DeviceMode::IsRxOnWhenIdle(), and DeviceMode::IsSecureDataRequest().
Referenced by DeviceMode::operator!=(), and Mle::SetDeviceMode().
Field Documentation
mMode
uint8_t mMode private
Referenced by DeviceMode::Get(), DeviceMode::IsFullNetworkData(), DeviceMode::IsFullThreadDevice(), DeviceMode::IsMinimalEndDevice(), DeviceMode::IsRxOnWhenIdle(), DeviceMode::IsSecureDataRequest(), DeviceMode::operator==(), and DeviceMode::Set().
The documentation for this class was generated from the following files:
mle_types.hpp
mle_types.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale