OpenThread: TcpHeader Class Reference
TcpHeader Class Reference
Core-tcp
#include <tcp.hpp>
Public Member Functions
uint32_t GetAcknowledgmentNumber (void) const
uint16_t GetChecksum (void) const
uint16_t GetDestinationPort (void) const
uint16_t GetFlags (void) const
uint32_t GetSequenceNumber (void) const
uint16_t GetSourcePort (void) const
uint16_t GetUrgentPointer (void) const
uint16_t GetWindow (void) const
Additional Inherited Members
Private Attributes inherited from TcpHeaderPoD
uint32_t mAckNumber
uint16_t mChecksum
uint16_t mDestination
uint16_t mFlags
uint32_t mSequenceNumber
uint16_t mSource
uint16_t mUrgentPointer
uint16_t mWindow
Detailed Description
This class implements TCP header parsing.
Member Function Documentation
GetSourcePort()
uint16_t GetSourcePort (void) const inline
This method returns the TCP Source Port.
Returns
The TCP Source Port.
References ot::Encoding::BigEndian::HostSwap16(), and TcpHeaderPoD::mSource.
GetDestinationPort()
uint16_t GetDestinationPort (void) const inline
This method returns the TCP Destination Port.
Returns
The TCP Destination Port.
References ot::Encoding::BigEndian::HostSwap16(), and TcpHeaderPoD::mDestination.
Referenced by Filter::Accept().
GetSequenceNumber()
uint32_t GetSequenceNumber (void) const inline
This method returns the TCP Sequence Number.
Returns
The TCP Sequence Number.
References ot::Encoding::BigEndian::HostSwap32(), and TcpHeaderPoD::mSequenceNumber.
GetAcknowledgmentNumber()
uint32_t GetAcknowledgmentNumber (void) const inline
This method returns the TCP Acknowledgment Sequence Number.
Returns
The TCP Acknowledgment Sequence Number.
References ot::Encoding::BigEndian::HostSwap32(), and TcpHeaderPoD::mAckNumber.
GetFlags()
uint16_t GetFlags (void) const inline
This method returns the TCP Flags.
Returns
The TCP Flags.
References ot::Encoding::BigEndian::HostSwap16(), and TcpHeaderPoD::mFlags.
GetWindow()
uint16_t GetWindow (void) const inline
This method returns the TCP Window.
Returns
The TCP Window.
References ot::Encoding::BigEndian::HostSwap16(), and TcpHeaderPoD::mWindow.
GetChecksum()
uint16_t GetChecksum (void) const inline
This method returns the TCP Checksum.
Returns
The TCP Checksum.
References ot::Encoding::BigEndian::HostSwap16(), and TcpHeaderPoD::mChecksum.
GetUrgentPointer()
uint16_t GetUrgentPointer (void) const inline
This method returns the TCP Urgent Pointer.
Returns
The TCP Urgent Pointer.
References ot::Encoding::BigEndian::HostSwap16(), TcpHeaderPoD::mUrgentPointer, and ot::Ip6::OT_TOOL_PACKED_END.
The documentation for this class was generated from the following file:
tcp.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale