OpenThread: StringBase Class Reference
StringBase Class Reference
Core-string
#include <string.hpp>
Static Protected Member Functions
static otError Write (char *aBuffer, uint16_t aSize, uint16_t &aLength, const char *aFormat, va_list aArgs)
Detailed Description
This class defines the base class for String.
Member Function Documentation
Write()
otError Write (char * aBuffer, uint16_t aSize, uint16_t & aLength, const char * aFormat, va_list aArgs) static protected
This method appends printf() style formatted data to a given character string buffer.
Parameters
[in] aBuffer A pointer to buffer containing the string.
[in] aSize The size of the buffer (in bytes).
[in,out] aLength A reference to variable containing current length of string. On exit length is updated.
[in] aFormat A pointer to the format string.
[in] aArgs Arguments for the format specification.
Return values
OT_ERROR_NONE Updated the string successfully.
OT_ERROR_NO_BUFS String could not fit in the storage.
OT_ERROR_INVALID_ARGS Arguments do not match the format string.
References OT_ERROR_INVALID_ARGS, OT_ERROR_NO_BUFS, and OT_ERROR_NONE.
Referenced by String< SIZE >::Append(), String< SIZE >::Set(), and String< SIZE >::String().
The documentation for this class was generated from the following files:
string.hpp
string.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale