OpenThread: MaxPowerTable Class Reference
MaxPowerTable Class Reference
#include <max_power_table.hpp>
Public Member Functions
uint32_t GetAllowedChannelMask (void) const
int8_t GetTransmitPower (uint8_t aChannel) const
MaxPowerTable (void)
void SetTransmitPower (uint8_t aChannel, int8_t aPower)
Static Public Attributes
static const int8_t kPowerDefault = 30
Default power 1 watt (30 dBm).
Private Attributes
int8_t mPowerTable [Radio::kChannelMax - Radio::kChannelMin+1]
Static Private Attributes
static const int8_t kPowerForbidden = 0x7f
Constructor & Destructor Documentation
MaxPowerTable()
MaxPowerTable (void) inline
References MaxPowerTable::kPowerForbidden, and MaxPowerTable::mPowerTable.
Member Function Documentation
GetTransmitPower()
int8_t GetTransmitPower (uint8_t aChannel) const inline
This method gets the max allowed transmit power of channel aChannel.
[in] aChannel The radio channel number.
Returns
The max allowed transmit power in dBm.
References MaxPowerTable::mPowerTable.
Referenced by otPlatRadioReceive().
SetTransmitPower()
void SetTransmitPower (uint8_t aChannel, int8_t aPower) inline
This method sets the max allowed transmit power of channel aChannel.
[in] aChannel The radio channel number. [in] aPower The max allowed transmit power in dBm.
References MaxPowerTable::mPowerTable.
Referenced by platformRadioInit().
GetAllowedChannelMask()
uint32_t GetAllowedChannelMask (void) const inline
This method gets the allowed channel masks.
All channels of max power value of 0x7f is considered forbidden.
References MaxPowerTable::kPowerForbidden, and MaxPowerTable::mPowerTable.
Referenced by otPlatRadioGetPreferredChannelMask(), and otPlatRadioGetSupportedChannelMask().
Field Documentation
kPowerDefault
const int8_t kPowerDefault = 30 static
Default power 1 watt (30 dBm).
Referenced by platformRadioInit().
kPowerForbidden
const int8_t kPowerForbidden = 0x7f static private
Referenced by MaxPowerTable::GetAllowedChannelMask(), and MaxPowerTable::MaxPowerTable().
mPowerTable
int8_t mPowerTable[Radio::kChannelMax - Radio::kChannelMin+1] private
Referenced by MaxPowerTable::GetAllowedChannelMask(), MaxPowerTable::GetTransmitPower(), MaxPowerTable::MaxPowerTable(), and MaxPowerTable::SetTransmitPower().
The documentation for this class was generated from the following file:
max_power_table.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale