OpenThread: EnergyScanServer Class Reference
EnergyScanServer Class Reference
#include <energy_scan_server.hpp>
Public Member Functions
EnergyScanServer (Instance &aInstance)
Public Member Functions inherited from InstanceLocator
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Private Types
enum { kScanDelay = 1000, kReportDelay = 500 }
Private Member Functions
void HandleRequest (Coap::Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
void HandleScanResult (Mac::EnergyScanResult *aResult)
void HandleStateChanged (otChangedFlags aFlags)
void HandleTimer (void)
otError SendReport (void)
Static Private Member Functions
static void HandleRequest (void *aContext, otMessage *aMessage, const otMessageInfo *aMessageInfo)
static void HandleScanResult (Mac::EnergyScanResult *aResult, void *aContext)
static void HandleStateChanged (Notifier::Callback &aCallback, otChangedFlags aFlags)
static void HandleTimer (Timer &aTimer)
Private Attributes
bool mActive
uint32_t mChannelMask
uint32_t mChannelMaskCurrent
Ip6::Address mCommissioner
uint8_t mCount
Coap::Resource mEnergyScan
Notifier::Callback mNotifierCallback
uint16_t mPeriod
uint16_t mScanDuration
int8_t mScanResults [OPENTHREAD_CONFIG_TMF_ENERGY_SCAN_MAX_RESULTS]
uint8_t mScanResultsLength
TimerMilli mTimer
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Detailed Description
This class implements handling Energy Scan Requests.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
kScanDelay
SCAN_DELAY (milliseconds)
kReportDelay
Delay before sending a report (milliseconds)
Constructor & Destructor Documentation
EnergyScanServer()
EnergyScanServer (Instance & aInstance) explicit
This constructor initializes the object.
References EnergyScanServer::mEnergyScan.
Member Function Documentation
HandleRequest() [1/2]
void HandleRequest (void * aContext, otMessage * aMessage, const otMessageInfo * aMessageInfo) static private
HandleRequest() [2/2]
void HandleRequest (Coap::Message & aMessage, const Ip6::MessageInfo & aMessageInfo) private
References ChannelMaskTlv::GetChannelMask(), Message::GetCode(), MessageInfo::GetPeerAddr(), MessageInfo::GetSockAddr(), Message::IsConfirmable(), Address::IsMulticast(), Tlv::kCount, Tlv::kPeriod, EnergyScanServer::kScanDelay, Tlv::kScanDuration, EnergyScanServer::mActive, EnergyScanServer::mChannelMask, EnergyScanServer::mChannelMaskCurrent, EnergyScanServer::mCommissioner, EnergyScanServer::mCount, EnergyScanServer::mPeriod, EnergyScanServer::mScanDuration, EnergyScanServer::mScanResultsLength, EnergyScanServer::mTimer, OT_COAP_CODE_POST, OT_NOOP, otLogInfoMeshCoP, Tlv::ReadUint16Tlv(), Tlv::ReadUint8Tlv(), TimerMilli::Start(), SuccessOrExit, and VerifyOrExit.
HandleScanResult() [1/2]
void HandleScanResult (Mac::EnergyScanResult * aResult, void * aContext) static private
Referenced by EnergyScanServer::HandleTimer().
HandleScanResult() [2/2]
void HandleScanResult (Mac::EnergyScanResult * aResult) private
References EnergyScanServer::kReportDelay, EnergyScanServer::mActive, EnergyScanServer::mChannelMask, EnergyScanServer::mChannelMaskCurrent, EnergyScanServer::mCount, otEnergyScanResult::mMaxRssi, EnergyScanServer::mPeriod, EnergyScanServer::mScanResults, EnergyScanServer::mScanResultsLength, EnergyScanServer::mTimer, OPENTHREAD_CONFIG_TMF_ENERGY_SCAN_MAX_RESULTS, OT_NOOP, TimerMilli::Start(), and VerifyOrExit.
HandleTimer() [1/2]
void HandleTimer (Timer & aTimer) static private
References OwnerLocator::GetOwner(), and EnergyScanServer::HandleTimer().
HandleTimer() [2/2]
void HandleTimer (void) private
References EnergyScanServer::HandleScanResult(), EnergyScanServer::mActive, EnergyScanServer::mChannelMaskCurrent, EnergyScanServer::mCount, EnergyScanServer::mScanDuration, OT_NOOP, EnergyScanServer::SendReport(), and VerifyOrExit.
Referenced by EnergyScanServer::HandleTimer().
HandleStateChanged() [1/2]
void HandleStateChanged (Notifier::Callback & aCallback, otChangedFlags aFlags) static private
References OwnerLocator::GetOwner().
HandleStateChanged() [2/2]
void HandleStateChanged (otChangedFlags aFlags) private
References EnergyScanServer::mActive, EnergyScanServer::mTimer, OT_CHANGED_THREAD_NETDATA, and TimerMilli::Stop().
SendReport()
otError SendReport (void) private
References Message::Append(), Tlv::AppendTo(), Message::Free(), Message::Init(), ChannelMaskTlv::Init(), EnergyListTlv::Init(), ot::kCoapUdpPort, EnergyScanServer::mActive, EnergyScanServer::mChannelMask, EnergyScanServer::mCommissioner, EnergyScanServer::mScanResults, EnergyScanServer::mScanResultsLength, ot::MeshCoP::NewMeshCoPMessage(), OT_COAP_CODE_POST, OT_COAP_TYPE_CONFIRMABLE, OT_ERROR_NO_BUFS, OT_ERROR_NONE, OT_URI_PATH_ENERGY_REPORT, otLogInfoMeshCoP, ChannelMaskTlv::SetChannelMask(), Tlv::SetLength(), Message::SetPayloadMarker(), MessageInfo::SetPeerAddr(), MessageInfo::SetPeerPort(), MessageInfo::SetSockAddr(), SuccessOrExit, and VerifyOrExit.
Referenced by EnergyScanServer::HandleTimer().
Field Documentation
mCommissioner
Ip6::Address mCommissioner private
Referenced by EnergyScanServer::HandleRequest(), and EnergyScanServer::SendReport().
mChannelMask
uint32_t mChannelMask private
Referenced by EnergyScanServer::HandleRequest(), EnergyScanServer::HandleScanResult(), and EnergyScanServer::SendReport().
mChannelMaskCurrent
uint32_t mChannelMaskCurrent private
Referenced by EnergyScanServer::HandleRequest(), EnergyScanServer::HandleScanResult(), and EnergyScanServer::HandleTimer().
mPeriod
uint16_t mPeriod private
Referenced by EnergyScanServer::HandleRequest(), and EnergyScanServer::HandleScanResult().
mScanDuration
uint16_t mScanDuration private
Referenced by EnergyScanServer::HandleRequest(), and EnergyScanServer::HandleTimer().
mCount
uint8_t mCount private
Referenced by EnergyScanServer::HandleRequest(), EnergyScanServer::HandleScanResult(), and EnergyScanServer::HandleTimer().
mActive
bool mActive private
Referenced by EnergyScanServer::HandleRequest(), EnergyScanServer::HandleScanResult(), EnergyScanServer::HandleStateChanged(), EnergyScanServer::HandleTimer(), and EnergyScanServer::SendReport().
mScanResults
int8_t mScanResults[OPENTHREAD_CONFIG_TMF_ENERGY_SCAN_MAX_RESULTS] private
Referenced by EnergyScanServer::HandleScanResult(), and EnergyScanServer::SendReport().
mScanResultsLength
uint8_t mScanResultsLength private
Referenced by EnergyScanServer::HandleRequest(), EnergyScanServer::HandleScanResult(), and EnergyScanServer::SendReport().
mTimer
TimerMilli mTimer private
Referenced by EnergyScanServer::HandleRequest(), EnergyScanServer::HandleScanResult(), and EnergyScanServer::HandleStateChanged().
mNotifierCallback
Notifier::Callback mNotifierCallback private
mEnergyScan
Coap::Resource mEnergyScan private
Referenced by EnergyScanServer::EnergyScanServer(), and Instance::Get().
The documentation for this class was generated from the following files:
energy_scan_server.hpp
energy_scan_server.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale