OpenThread: MessageQueue Class Reference
MessageQueue Class Reference
Core-coap
#include <coap_message.hpp>
Public Member Functions
otError Dequeue (Message &aMessage)
otError Enqueue (Message &aMessage)
otError Enqueue (Message &aMessage, QueuePosition aPosition)
Message * GetHead (void) const
MessageQueue (void)
Public Member Functions inherited from MessageQueue
otError Dequeue (Message &aMessage)
otError Enqueue (Message &aMessage)
otError Enqueue (Message &aMessage, QueuePosition aPosition)
Message * GetHead (void) const
void GetInfo (uint16_t &aMessageCount, uint16_t &aBufferCount) const
MessageQueue (void)
Additional Inherited Members
Public Types inherited from MessageQueue
enum QueuePosition { kQueuePositionHead, kQueuePositionTail }
Data Fields inherited from otMessageQueue
void * mData
Opaque data used by the implementation.
Detailed Description
This class implements a CoAP message queue.
Constructor & Destructor Documentation
MessageQueue()
MessageQueue (void) inline
This constructor initializes the message queue.
Member Function Documentation
GetHead()
Message* GetHead (void) const inline
This method returns a pointer to the first message.
Returns
A pointer to the first message.
References MessageQueue::GetHead().
Referenced by CoapBase::AbortTransaction(), CoapBase::ClearRequests(), ResponsesQueue::DequeueAllResponses(), CoapBase::DequeueMessage(), ResponsesQueue::FindMatchedResponse(), CoapBase::FindRelatedRequest(), CoapBase::HandleRetransmissionTimer(), ResponsesQueue::HandleTimer(), and ResponsesQueue::UpdateQueue().
Enqueue() [1/2]
otError Enqueue (Message & aMessage) inline
This method adds a message to the end of the queue.
Parameters
[in] aMessage The message to add.
Return values
OT_ERROR_NONE Successfully added the message to the queue.
OT_ERROR_ALREADY The message is already enqueued in a queue.
References MessageQueue::Enqueue().
Referenced by CoapBase::CopyAndEnqueueMessage(), MessageQueue::Enqueue(), and ResponsesQueue::EnqueueResponse().
Enqueue() [2/2]
otError Enqueue (Message & aMessage, QueuePosition aPosition) inline
This method adds a message at a given position (head/tail) of the queue.
Parameters
[in] aMessage The message to add.
[in] aPosition The position (head or tail) where to add the message.
Return values
OT_ERROR_NONE Successfully added the message to the queue.
OT_ERROR_ALREADY The message is already enqueued in a queue.
References MessageQueue::Enqueue().
Dequeue()
otError Dequeue (Message & aMessage) inline
This method removes a message from the queue.
Parameters
[in] aMessage The message to remove.
Return values
OT_ERROR_NONE Successfully removed the message from the queue.
OT_ERROR_NOT_FOUND The message is not enqueued in a queue.
References MessageQueue::Dequeue().
Referenced by CoapBase::DequeueMessage(), and ResponsesQueue::DequeueResponse().
The documentation for this class was generated from the following file:
coap_message.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale