OpenThread: InstanceLocator Class Reference
InstanceLocator Class Reference
Core-locator
#include <locator.hpp>
Inherited by AddressResolver, AnnounceBeginClient, AnnounceSenderBase, Leader, CoapBase, DataPollHandler, DataPollHandler::Callbacks, DataPollSender, Dhcp6Client, Dhcp6Server, DuaManager, EnergyScanClient, EnergyScanServer, Flash, IndirectSender, InstanceLocatorInit, Icmp, Ip6, Mpl, Netif, Udp, UdpSocket, KeyManager, Lowpan, Mac, SubMac, SubMac::Callbacks, BorderAgent, Commissioner, DatasetLocal, DatasetManager, Dtls, Joiner, JoinerRouter, Leader, MeshForwarder, MessagePool, Mle, NetworkData, NetworkDiagnostic, Notifier, PanIdQueryClient, PanIdQueryServer, Radio, Radio::Callbacks, SettingsBase, SettingsDriver, SourceMatchController, Tasklet, Timer, TimerScheduler, JamDetector, and Slaac.
Public Member Functions
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Protected Member Functions
InstanceLocator (Instance &aInstance)
Private Member Functions
InstanceLocator (void)
Friends
class InstanceLocatorInit
Detailed Description
This class implements a locator for an OpenThread Instance object.
The InstanceLocator is used as base class of almost all other OpenThread classes. It provides a way for an object to get to its owning/parent OpenThread Instance and also any other Type within the Instance member variable property hierarchy (using Get<Type>() method).
If multiple-instance feature is supported, the owning/parent OpenThread Instance is tracked as a reference. In the single-instance case, this class becomes an empty base class.
Constructor & Destructor Documentation
InstanceLocator() [1/2]
InstanceLocator (Instance & aInstance) inline explicit protected
This constructor initializes the object.
Parameters
[in] aInstance A reference to the OpenThread Instance.
References OT_UNUSED_VARIABLE.
InstanceLocator() [2/2]
InstanceLocator (void) inline private
Referenced by SettingsDriver::Wipe().
Member Function Documentation
GetInstance()
Instance& GetInstance (void) const inline
This method returns a reference to the parent OpenThread Instance.
Returns
A reference to the parent otInstance.
References InstanceLocator::Get(), and ot::gInstanceRaw.
Referenced by SettingsDriver::Add(), Flash::Add(), Radio::AddSrcMatchExtEntry(), Radio::AddSrcMatchShortEntry(), DatasetManager::ApplyConfiguration(), UdpSocket::Bind(), Child::Clear(), Router::Clear(), Radio::ClearSrcMatchExtEntries(), Radio::ClearSrcMatchExtEntry(), Radio::ClearSrcMatchShortEntries(), Radio::ClearSrcMatchShortEntry(), UdpSocket::Connect(), SettingsDriver::Deinit(), SettingsDriver::Delete(), Flash::Delete(), Radio::Disable(), Flash::DoesValidRecordExist(), Radio::Enable(), Radio::EnableSrcMatch(), Radio::EnergyScan(), MessagePool::FreeBuffers(), InstanceLocator::Get(), Flash::Get(), SettingsDriver::Get(), Radio::GetCaps(), Radio::GetCcaEnergyDetectThreshold(), MeshForwarder::GetFramePriority(), MessagePool::GetFreeBufferCount(), Radio::GetIeeeEui64(), Radio::GetInstance(), Radio::GetPreferredChannelMask(), Radio::GetPromiscuous(), Radio::GetReceiveSensitivity(), Radio::GetRssi(), Radio::GetState(), Radio::GetSupportedChannelMask(), Radio::GetTransmitBuffer(), Radio::GetTransmitPower(), Radio::GetVersionString(), Udp::HandleMessage(), SettingsDriver::Init(), Flash::Init(), Radio::IsEnabled(), MessagePool::MessagePool(), MessagePool::NewBuffer(), TaskletScheduler::PostTasklet(), Radio::Receive(), MeshForwarder::RemoveMessage(), DatasetManager::Restore(), Flash::SanitizeFreeSpace(), DatasetManager::Save(), UdpSocket::SendTo(), SettingsDriver::Set(), TimerScheduler::SetAlarm(), Radio::SetCcaEnergyDetectThreshold(), KeyManager::SetMasterKey(), Radio::SetPanId(), Radio::SetPromiscuous(), Radio::SetTransmitPower(), Radio::Sleep(), Flash::Swap(), Radio::Transmit(), Flash::Wipe(), and SettingsDriver::Wipe().
Get() [1/2]
Type & Get (void) const inline
This template method returns a reference to a given Type object belonging to the OpenThread instance.
For example, Get<MeshForwarder>() returns a reference to the MeshForwarder object of the instance.
Note that any Type for which the Get<Type> is defined MUST be uniquely accessible from the OpenThread Instance through the member variable property hierarchy.
Returns
A reference to the Type object of the instance.
References Instance::Get(), and InstanceLocator::GetInstance().
Referenced by Flash::Add(), Flash::Flash(), ot::MeshCoP::GetBorderAgentRloc(), InstanceLocator::GetInstance(), Settings::ChildInfoIterator::Read(), Settings::Read(), and SettingsDriver::Wipe().
Get() [2/2]
Instance& Get (void) const inline
This method returns a reference to the parent OpenThread Instance.
This definition is a specialization of template Get<Type> for Get<Instance>(),
Returns
A reference to Instance object.
References InstanceLocator::GetInstance().
Friends And Related Function Documentation
InstanceLocatorInit
friend class InstanceLocatorInit friend
The documentation for this class was generated from the following files:
locator.hpp
locator-getters.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale