OpenThread: Child Class Reference
Child Class Reference
#include <topology.hpp>
Data Structures
class Ip6AddressIterator
Public Types
enum { kMaxRequestTlvs = 5 }
Public Types inherited from Neighbor
enum State {
kStateInvalid, kStateRestored, kStateParentRequest, kStateParentResponse,
kStateChildIdRequest, kStateLinkRequest, kStateChildUpdateRequest, kStateValid
}
enum StateFilter {
kInStateValid, kInStateValidOrRestoring, kInStateChildIdRequest, kInStateValidOrAttaching,
kInStateAnyExceptInvalid, kInStateAnyExceptValidOrRestoring
}
Public Member Functions
otError AddIp6Address (const Ip6::Address &aAddress)
void Clear (void)
void ClearIp6Addresses (void)
void ClearRequestTlvs (void)
void GenerateChallenge (void)
const uint8_t * GetChallenge (void) const
uint8_t GetChallengeSize (void) const
const uint8_t * GetMeshLocalIid (void) const
otError GetMeshLocalIp6Address (Ip6::Address &aAddress) const
uint8_t GetNetworkDataVersion (void) const
otError GetNextIp6Address (Ip6AddressIterator &aIterator, Ip6::Address &aAddress) const
uint8_t GetRequestTlv (uint8_t aIndex) const
uint32_t GetTimeout (void) const
bool HasIp6Address (const Ip6::Address &aAddress) const
void Init (Instance &aInstance)
otError RemoveIp6Address (const Ip6::Address &aAddress)
void SetNetworkDataVersion (uint8_t aVersion)
void SetRequestTlv (uint8_t aIndex, uint8_t aType)
void SetTimeout (uint32_t aTimeout)
Public Member Functions inherited from Neighbor
void ClearExtAddress (void)
void GenerateChallenge (void)
const uint8_t * GetChallenge (void) const
uint8_t GetChallengeSize (void) const
Mle::DeviceMode GetDeviceMode (void) const
const Mac::ExtAddress & GetExtAddress (void) const
uint32_t GetKeySequence (void) const
TimeMilli GetLastHeard (void) const
uint8_t GetLinkFailures (void) const
uint32_t GetLinkFrameCounter (void) const
LinkQualityInfo & GetLinkInfo (void)
uint32_t GetMleFrameCounter (void) const
uint16_t GetRloc16 (void) const
uint8_t GetRouterId (void) const
State GetState (void) const
uint8_t GetVersion (void) const
void IncrementLinkFailures (void)
bool IsEnhancedKeepAliveSupported (void) const
bool IsFullNetworkData (void) const
bool IsFullThreadDevice (void) const
bool IsRxOnWhenIdle (void) const
bool IsSecureDataRequest (void) const
bool IsStateChildIdRequest (void) const
bool IsStateInvalid (void) const
bool IsStateLinkRequest (void) const
bool IsStateParentResponse (void) const
bool IsStateRestored (void) const
bool IsStateRestoring (void) const
bool IsStateValid (void) const
bool IsStateValidOrAttaching (void) const
bool IsStateValidOrRestoring (void) const
bool IsThreadVersion1p1 (void) const
bool MatchesFilter (StateFilter aFilter) const
void ResetLinkFailures (void)
void SetDeviceMode (Mle::DeviceMode aMode)
void SetExtAddress (const Mac::ExtAddress &aAddress)
void SetKeySequence (uint32_t aKeySequence)
void SetLastHeard (TimeMilli aLastHeard)
void SetLinkFrameCounter (uint32_t aFrameCounter)
void SetMleFrameCounter (uint32_t aFrameCounter)
void SetRloc16 (uint16_t aRloc16)
void SetState (State aState)
void SetVersion (uint8_t aVersion)
Public Member Functions inherited from InstanceLocator
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Public Member Functions inherited from IndirectSender::ChildInfo
uint16_t GetIndirectMessageCount (void) const
Private Types
enum { kNumIp6Addresses = OPENTHREAD_CONFIG_MLE_IP_ADDRS_PER_CHILD - 1 }
Private Member Functions
OT_STATIC_ASSERT (OPENTHREAD_CONFIG_NUM_MESSAGE_BUFFERS< 8192, "mQueuedMessageCount cannot fit max required!")
Private Attributes
union {
uint8_t mAttachChallenge [Mle::kMaxChallengeSize]
The challenge value.
uint8_t mRequestTlvs [kMaxRequestTlvs]
Requested MLE TLVs.
};
Ip6::Address mIp6Address [kNumIp6Addresses]
Registered IPv6 addresses.
uint8_t mMeshLocalIid [Ip6::Address::kInterfaceIdentifierSize]
IPv6 address IID for mesh-local address.
uint8_t mNetworkDataVersion
Current Network Data version.
uint32_t mTimeout
Child timeout.
Additional Inherited Members
Protected Member Functions inherited from Neighbor
void Init (Instance &aInstance)
Protected Member Functions inherited from InstanceLocatorInit
void Init (Instance &aInstance)
InstanceLocatorInit (void)
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Detailed Description
This class represents a Thread Child.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
kMaxRequestTlvs
anonymous enum
anonymous enum private
Enumerator
kNumIp6Addresses
Member Function Documentation
Init()
void Init (Instance & aInstance) inline
This method initializes the Child object.
Parameters
[in] aInstance A reference to OpenThread instance.
References Neighbor::Init().
Clear()
void Clear (void)
This method clears the child entry.
References InstanceLocator::GetInstance(), and Neighbor::Init().
ClearIp6Addresses()
void ClearIp6Addresses (void)
This method clears the IPv6 address list for the child.
GetMeshLocalIp6Address()
otError GetMeshLocalIp6Address (Ip6::Address & aAddress) const
This method gets the mesh-local IPv6 address.
Parameters
[out] aAddress A reference to an IPv6 address to provide address (if any).
Return values
OT_ERROR_NONE Successfully found the mesh-local address and updated aAddress.
OT_ERROR_NOT_FOUND No mesh-local IPv6 address in the IPv6 address list.
References ot::IsAllZero(), OT_ERROR_NONE, OT_ERROR_NOT_FOUND, Address::SetIid(), Address::SetPrefix(), and VerifyOrExit.
GetMeshLocalIid()
const uint8_t* GetMeshLocalIid (void) const inline
This method returns a pointer to the Mesh Local Interface Identifier.
Returns
a pointer to the Mesh Local Interface Identifier.
GetNextIp6Address()
otError GetNextIp6Address (Ip6AddressIterator & aIterator, Ip6::Address & aAddress) const
This method gets the next IPv6 address in the list.
Parameters
[in,out] aIterator A reference to an IPv6 address iterator.
[out] aAddress A reference to an IPv6 address to provide the next address (if any).
Return values
OT_ERROR_NONE Successfully found the next address and updated aAddress and aIterator.
OT_ERROR_NOT_FOUND No subsequent IPv6 address exists in the IPv6 address list.
References Child::Ip6AddressIterator::Get(), Child::Ip6AddressIterator::Increment(), OT_ERROR_NONE, OT_ERROR_NOT_FOUND, OT_NOOP, and VerifyOrExit.
AddIp6Address()
otError AddIp6Address (const Ip6::Address & aAddress)
This method adds an IPv6 address to the list.
Parameters
[in] aAddress A reference to IPv6 address to be added.
Return values
OT_ERROR_NONE Successfully added the new address.
OT_ERROR_ALREADY Address is already in the list.
OT_ERROR_NO_BUFS Already at maximum number of addresses. No entry available to add the new address.
OT_ERROR_INVALID_ARGS Address is invalid (it is the Unspecified Address).
References ExitNow, Address::GetIid(), ot::IsAllZero(), Address::IsUnspecified(), Address::kInterfaceIdentifierSize, OT_ERROR_ALREADY, OT_ERROR_INVALID_ARGS, OT_ERROR_NO_BUFS, OT_ERROR_NONE, and VerifyOrExit.
RemoveIp6Address()
otError RemoveIp6Address (const Ip6::Address & aAddress)
This method removes an IPv6 address from the list.
Parameters
[in] aAddress A reference to IPv6 address to be removed.
Return values
OT_ERROR_NONE Successfully removed the address.
OT_ERROR_NOT_FOUND Address was not found in the list.
OT_ERROR_INVALID_ARGS Address is invalid (it is the Unspecified Address).
References ExitNow, Address::GetIid(), Address::IsUnspecified(), Address::kInterfaceIdentifierSize, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, OT_ERROR_NOT_FOUND, OT_NOOP, SuccessOrExit, and VerifyOrExit.
HasIp6Address()
bool HasIp6Address (const Ip6::Address & aAddress) const
This method indicates whether an IPv6 address is in the list of IPv6 addresses of the child.
Parameters
[in] aAddress A reference to IPv6 address.
Return values
TRUE The address exists on the list.
FALSE Address was not found in the list.
References ExitNow, Address::GetIid(), Address::IsUnspecified(), Address::kInterfaceIdentifierSize, OT_NOOP, and VerifyOrExit.
GetTimeout()
uint32_t GetTimeout (void) const inline
This method gets the child timeout.
Returns
The child timeout.
SetTimeout()
void SetTimeout (uint32_t aTimeout) inline
This method sets the child timeout.
Parameters
[in] aTimeout The child timeout.
GetNetworkDataVersion()
uint8_t GetNetworkDataVersion (void) const inline
This method gets the network data version.
Returns
The network data version.
SetNetworkDataVersion()
void SetNetworkDataVersion (uint8_t aVersion) inline
This method sets the network data version.
Parameters
[in] aVersion The network data version.
References Neighbor::GenerateChallenge().
GenerateChallenge()
void GenerateChallenge (void)
This method generates a new challenge value to use during a child attach.
References ot::Random::Crypto::FillBuffer().
GetChallenge()
const uint8_t* GetChallenge (void) const inline
This method gets the current challenge value used during attach.
Returns
The current challenge value.
GetChallengeSize()
uint8_t GetChallengeSize (void) const inline
This method gets the challenge size (bytes) used during attach.
Returns
The challenge size (bytes).
ClearRequestTlvs()
void ClearRequestTlvs (void) inline
This method clears the requested TLV list.
References Tlv::kInvalid.
GetRequestTlv()
uint8_t GetRequestTlv (uint8_t aIndex) const inline
This method returns the requested TLV at index aIndex.
Parameters
[in] aIndex The index into the requested TLV list.
Returns
The requested TLV at index aIndex.
SetRequestTlv()
void SetRequestTlv (uint8_t aIndex, uint8_t aType) inline
This method sets the requested TLV at index aIndex.
Parameters
[in] aIndex The index into the requested TLV list.
[in] aType The TLV type.
OT_STATIC_ASSERT()
OT_STATIC_ASSERT () private
Field Documentation
mNetworkDataVersion
uint8_t mNetworkDataVersion private
Current Network Data version.
mMeshLocalIid
uint8_t mMeshLocalIid[Ip6::Address::kInterfaceIdentifierSize] private
IPv6 address IID for mesh-local address.
mIp6Address
Ip6::Address mIp6Address[kNumIp6Addresses] private
Registered IPv6 addresses.
mTimeout
uint32_t mTimeout private
Child timeout.
mRequestTlvs
uint8_t mRequestTlvs[kMaxRequestTlvs]
Requested MLE TLVs.
mAttachChallenge
uint8_t mAttachChallenge[Mle::kMaxChallengeSize]
The challenge value.
@210
union { ... }
The documentation for this class was generated from the following files:
topology.hpp
topology.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale