OpenThread: CoapSecure Class Reference
CoapSecure Class Reference
#include <coap_secure.hpp>
Public Types
typedef void(* ConnectedCallback) (bool aConnected, void *aContext)
Public Types inherited from CoapBase
typedef otError(* Interceptor) (const Message &aMessage, const Ip6::MessageInfo &aMessageInfo, void *aContext)
Public Member Functions
CoapSecure (Instance &aInstance, bool aLayerTwoSecurity=false)
otError Connect (const Ip6::SockAddr &aSockAddr, ConnectedCallback aCallback, void *aContext)
void Disconnect (void)
MeshCoP::Dtls & GetDtls (void)
const Ip6::MessageInfo & GetPeerAddress (void) const
void HandleUdpReceive (ot::Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
bool IsConnected (void) const
bool IsConnectionActive (void) const
otError SendMessage (Message &aMessage, ResponseHandler aHandler=NULL, void *aContext=NULL)
otError SendMessage (Message &aMessage, const Ip6::MessageInfo &aMessageInfo, ResponseHandler aHandler=NULL, void *aContext=NULL)
void SetConnectedCallback (ConnectedCallback aCallback, void *aContext)
otError SetPsk (const uint8_t *aPsk, uint8_t aPskLength)
otError Start (uint16_t aPort)
otError Start (MeshCoP::Dtls::TransportCallback aCallback, void *aContext)
void Stop (void)
Public Member Functions inherited from CoapBase
otError AbortTransaction (ResponseHandler aHandler, void *aContext)
otError AddResource (Resource &aResource)
void ClearRequests (const Ip6::Address &aAddress)
void ClearRequestsAndResponses (void)
const MessageQueue & GetCachedResponses (void) const
const MessageQueue & GetRequestMessages (void) const
Message * NewMessage (const otMessageSettings *aSettings=NULL)
void RemoveResource (Resource &aResource)
otError SendAck (const Message &aRequest, const Ip6::MessageInfo &aMessageInfo)
otError SendEmptyAck (const Message &aRequest, const Ip6::MessageInfo &aMessageInfo)
otError SendHeaderResponse (Message::Code aCode, const Message &aRequest, const Ip6::MessageInfo &aMessageInfo)
otError SendMessage (Message &aMessage, const Ip6::MessageInfo &aMessageInfo, const TxParameters &aTxParameters, ResponseHandler aHandler=NULL, void *aContext=NULL)
otError SendMessage (Message &aMessage, const Ip6::MessageInfo &aMessageInfo, ResponseHandler aHandler=NULL, void *aContext=NULL)
otError SendNotFound (const Message &aRequest, const Ip6::MessageInfo &aMessageInfo)
otError SendReset (Message &aRequest, const Ip6::MessageInfo &aMessageInfo)
void SetDefaultHandler (RequestHandler aHandler, void *aContext)
void SetInterceptor (Interceptor aInterceptor, void *aContext)
Public Member Functions inherited from InstanceLocator
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Private Member Functions
void HandleDtlsConnected (bool aConnected)
void HandleDtlsReceive (uint8_t *aBuf, uint16_t aLength)
void HandleTransmit (void)
otError Send (ot::Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
Static Private Member Functions
static void HandleDtlsConnected (void *aContext, bool aConnected)
static void HandleDtlsReceive (void *aContext, uint8_t *aBuf, uint16_t aLength)
static void HandleTransmit (Tasklet &aTasklet)
static otError Send (CoapBase &aCoapBase, ot::Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
Private Attributes
ConnectedCallback mConnectedCallback
void * mConnectedContext
MeshCoP::Dtls mDtls
ot::MessageQueue mTransmitQueue
TaskletContext mTransmitTask
Additional Inherited Members
Protected Types inherited from CoapBase
typedef otError(* Sender) (CoapBase &aCoapBase, ot::Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
Protected Member Functions inherited from CoapBase
CoapBase (Instance &aInstance, Sender aSender)
void Receive (ot::Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Member Typedef Documentation
ConnectedCallback
typedef void(* ConnectedCallback) (bool aConnected, void *aContext)
This function pointer is called once DTLS connection is established.
Parameters
[in] aConnected TRUE if a connection was established, FALSE otherwise.
[in] aContext A pointer to arbitrary context information.
Constructor & Destructor Documentation
CoapSecure()
CoapSecure (Instance & aInstance, bool aLayerTwoSecurity = false) explicit
This constructor initializes the object.
Parameters
[in] aInstance A reference to the OpenThread instance.
[in] aLayerTwoSecurity Specifies whether to use layer two security or not.
Member Function Documentation
Start() [1/2]
otError Start (uint16_t aPort)
This method starts the secure CoAP agent.
Parameters
[in] aPort The local UDP port to bind to.
Return values
OT_ERROR_NONE Successfully started the CoAP agent.
OT_ERROR_ALREADY Already started.
Start() [2/2]
otError Start (MeshCoP::Dtls::TransportCallback aCallback, void * aContext)
This method starts the secure CoAP agent, but do not use socket to transmit/receive messages.
Parameters
[in] aCallback A pointer to a function for sending messages.
[in] aContext A pointer to arbitrary context information.
Return values
OT_ERROR_NONE Successfully started the CoAP agent.
OT_ERROR_ALREADY Already started.
SetConnectedCallback()
void SetConnectedCallback (ConnectedCallback aCallback, void * aContext)
This method sets connected callback of this secure CoAP agent.
Parameters
[in] aCallback A pointer to a function to get called when connection state changes.
[in] aContext A pointer to arbitrary context information.
Stop()
void Stop (void)
This method stops the secure CoAP agent.
Connect()
otError Connect (const Ip6::SockAddr & aSockAddr, ConnectedCallback aCallback, void * aContext)
This method initializes DTLS session with a peer.
Parameters
[in] aSockAddr A reference to the remote socket address,
[in] aCallback A pointer to a function that will be called once DTLS connection is established.
Return values
OT_ERROR_NONE Successfully started DTLS connection.
IsConnectionActive()
bool IsConnectionActive (void) const inline
This method indicates whether or not the DTLS session is active.
Return values
TRUE If DTLS session is active.
FALSE If DTLS session is not active.
References Dtls::IsConnectionActive(), and CoapSecure::mDtls.
IsConnected()
bool IsConnected (void) const inline
This method indicates whether or not the DTLS session is connected.
Return values
TRUE The DTLS session is connected.
FALSE The DTLS session is not connected.
References Dtls::IsConnected(), and CoapSecure::mDtls.
Disconnect()
void Disconnect (void) inline
This method stops the DTLS connection.
References Dtls::Disconnect(), and CoapSecure::mDtls.
GetDtls()
MeshCoP::Dtls& GetDtls (void) inline
This method returns a reference to the DTLS object.
Returns
A reference to the DTLS object.
References CoapSecure::mDtls, CoapSecure::SendMessage(), and CoapSecure::SetPsk().
SetPsk()
otError SetPsk (const uint8_t * aPsk, uint8_t aPskLength)
This method sets the PSK.
Parameters
[in] aPsk A pointer to the PSK.
[in] aPskLength The PSK length.
Return values
OT_ERROR_NONE Successfully set the PSK.
OT_ERROR_INVALID_ARGS The PSK is invalid.
Referenced by CoapSecure::GetDtls().
SendMessage() [1/2]
otError SendMessage (Message & aMessage, ResponseHandler aHandler = NULL, void * aContext = NULL)
This method sends a CoAP message over secure DTLS connection.
If a response for a request is expected, respective function and context information should be provided. If no response is expected, these arguments should be NULL pointers. If Message Id was not set in the header (equal to 0), this function will assign unique Message Id to the message.
Parameters
[in] aMessage A reference to the message to send.
[in] aHandler A function pointer that shall be called on response reception or time-out.
[in] aContext A pointer to arbitrary context information.
Return values
OT_ERROR_NONE Successfully sent CoAP message.
OT_ERROR_NO_BUFS Failed to allocate retransmission data.
OT_ERROR_INVALID_STATE DTLS connection was not initialized.
Referenced by CoapSecure::GetDtls().
SendMessage() [2/2]
otError SendMessage (Message & aMessage, const Ip6::MessageInfo & aMessageInfo, ResponseHandler aHandler = NULL, void * aContext = NULL)
This method sends a CoAP message over secure DTLS connection.
If a response for a request is expected, respective function and context information should be provided. If no response is expected, these arguments should be NULL pointers. If Message Id was not set in the header (equal to 0), this function will assign unique Message Id to the message.
Parameters
[in] aMessage A reference to the message to send.
[in] aMessageInfo A reference to the message info associated with aMessage.
[in] aHandler A function pointer that shall be called on response reception or time-out.
[in] aContext A pointer to arbitrary context information.
Return values
OT_ERROR_NONE Successfully sent CoAP message.
OT_ERROR_NO_BUFS Failed to allocate retransmission data.
OT_ERROR_INVALID_STATE DTLS connection was not initialized.
HandleUdpReceive()
void HandleUdpReceive (ot::Message & aMessage, const Ip6::MessageInfo & aMessageInfo) inline
This method is used to pass UDP messages to the secure CoAP server.
Parameters
[in] aMessage A reference to the received message.
[in] aMessageInfo A reference to the message info associated with aMessage.
References Dtls::HandleUdpReceive(), and CoapSecure::mDtls.
GetPeerAddress()
const Ip6::MessageInfo& GetPeerAddress (void) const inline
This method returns the DTLS session's peer address.
Returns
DTLS session's message info.
References Dtls::GetPeerAddress(), and CoapSecure::mDtls.
Send() [1/2]
static otError Send (CoapBase & aCoapBase, ot::Message & aMessage, const Ip6::MessageInfo & aMessageInfo) inline static private
References CoapSecure::HandleDtlsConnected(), CoapSecure::HandleDtlsReceive(), and CoapSecure::HandleTransmit().
Send() [2/2]
otError Send (ot::Message & aMessage, const Ip6::MessageInfo & aMessageInfo) private
HandleDtlsConnected() [1/2]
static void HandleDtlsConnected (void * aContext, bool aConnected) static private
Referenced by CoapSecure::Send().
HandleDtlsConnected() [2/2]
void HandleDtlsConnected (bool aConnected) private
HandleDtlsReceive() [1/2]
static void HandleDtlsReceive (void * aContext, uint8_t * aBuf, uint16_t aLength) static private
Referenced by CoapSecure::Send().
HandleDtlsReceive() [2/2]
void HandleDtlsReceive (uint8_t * aBuf, uint16_t aLength) private
HandleTransmit() [1/2]
static void HandleTransmit (Tasklet & aTasklet) static private
HandleTransmit() [2/2]
void HandleTransmit (void) private
Referenced by CoapSecure::Send().
Field Documentation
mDtls
MeshCoP::Dtls mDtls private
Referenced by CoapSecure::Disconnect(), CoapSecure::GetDtls(), CoapSecure::GetPeerAddress(), CoapSecure::HandleUdpReceive(), CoapSecure::IsConnected(), and CoapSecure::IsConnectionActive().
mConnectedCallback
ConnectedCallback mConnectedCallback private
mConnectedContext
void* mConnectedContext private
mTransmitQueue
ot::MessageQueue mTransmitQueue private
mTransmitTask
TaskletContext mTransmitTask private
The documentation for this class was generated from the following file:
coap_secure.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale