OpenThread: NetworkDiagnosticTlv Class Reference
NetworkDiagnosticTlv Class Reference
MLE » TLVs
#include <network_diagnostic_tlvs.hpp>
Public Types
enum Type {
kExtMacAddress = OT_NETWORK_DIAGNOSTIC_TLV_EXT_ADDRESS, kAddress16 = OT_NETWORK_DIAGNOSTIC_TLV_SHORT_ADDRESS, kMode = OT_NETWORK_DIAGNOSTIC_TLV_MODE, kTimeout = OT_NETWORK_DIAGNOSTIC_TLV_TIMEOUT,
kConnectivity = OT_NETWORK_DIAGNOSTIC_TLV_CONNECTIVITY, kRoute = OT_NETWORK_DIAGNOSTIC_TLV_ROUTE, kLeaderData = OT_NETWORK_DIAGNOSTIC_TLV_LEADER_DATA, kNetworkData = OT_NETWORK_DIAGNOSTIC_TLV_NETWORK_DATA,
kIp6AddressList = OT_NETWORK_DIAGNOSTIC_TLV_IP6_ADDR_LIST, kMacCounters = OT_NETWORK_DIAGNOSTIC_TLV_MAC_COUNTERS, kBatteryLevel = OT_NETWORK_DIAGNOSTIC_TLV_BATTERY_LEVEL, kSupplyVoltage = OT_NETWORK_DIAGNOSTIC_TLV_SUPPLY_VOLTAGE,
kChildTable = OT_NETWORK_DIAGNOSTIC_TLV_CHILD_TABLE, kChannelPages = OT_NETWORK_DIAGNOSTIC_TLV_CHANNEL_PAGES, kTypeList = OT_NETWORK_DIAGNOSTIC_TLV_TYPE_LIST, kMaxChildTimeout = OT_NETWORK_DIAGNOSTIC_TLV_MAX_CHILD_TIMEOUT
}
Public Types inherited from Tlv
enum { kBaseTlvMaxLength = OT_NETWORK_BASE_TLV_MAX_LENGTH }
Public Member Functions
Type GetType (void) const
void SetType (Type aType)
Public Member Functions inherited from Tlv
otError AppendTo (Message &aMessage) const
uint8_t GetLength (void) const
Tlv * GetNext (void)
const Tlv * GetNext (void) const
uint32_t GetSize (void) const
uint8_t GetType (void) const
uint8_t * GetValue (void)
const uint8_t * GetValue (void) const
bool IsExtended (void) const
void SetLength (uint8_t aLength)
void SetType (uint8_t aType)
Static Public Member Functions
static otError GetOffset (const Message &aMessage, Type aType, uint16_t &aOffset)
static otError GetTlv (const Message &aMessage, Type aType, uint16_t aMaxLength, Tlv &aTlv)
Static Public Member Functions inherited from Tlv
static otError AppendTlv (Message &aMessage, uint8_t aType, const uint8_t *aValue, uint8_t aLength)
static otError AppendUint16Tlv (Message &aMessage, uint8_t aType, uint16_t aValue)
static otError AppendUint32Tlv (Message &aMessage, uint8_t aType, uint32_t aValue)
static otError AppendUint8Tlv (Message &aMessage, uint8_t aType, uint8_t aValue)
static otError Get (const Message &aMessage, uint8_t aType, uint16_t aMaxSize, Tlv &aTlv)
static otError GetOffset (const Message &aMessage, uint8_t aType, uint16_t &aOffset)
static otError GetValueOffset (const Message &aMessage, uint8_t aType, uint16_t &aOffset, uint16_t &aLength)
static otError ReadTlv (const Message &aMessage, uint8_t aType, void *aValue, uint8_t aLength)
static otError ReadUint16Tlv (const Message &aMessage, uint8_t aType, uint16_t &aValue)
static otError ReadUint32Tlv (const Message &aMessage, uint8_t aType, uint32_t &aValue)
static otError ReadUint8Tlv (const Message &aMessage, uint8_t aType, uint8_t &aValue)
Additional Inherited Members
Protected Types inherited from Tlv
enum { kExtendedLength = 255 }
Detailed Description
This class implements MLE TLV generation and parsing.
Member Enumeration Documentation
Type
enum Type
MLE TLV Types.
Enumerator
kExtMacAddress
kAddress16
kMode
kTimeout
kConnectivity
kRoute
kLeaderData
kNetworkData
kIp6AddressList
kMacCounters
kBatteryLevel
kSupplyVoltage
kChildTable
kChannelPages
kTypeList
kMaxChildTimeout
Member Function Documentation
GetType()
Type GetType (void) const inline
This method returns the Type value.
Returns
The Type value.
References Tlv::GetType().
SetType()
void SetType (Type aType) inline
This method sets the Type value.
Parameters
[in] aType The Type value.
References Tlv::SetType().
Referenced by ExtMacAddressTlv::Init(), Address16Tlv::Init(), ModeTlv::Init(), TimeoutTlv::Init(), ConnectivityTlv::Init(), RouteTlv::Init(), LeaderDataTlv::Init(), NetworkDataTlv::Init(), Ip6AddressListTlv::Init(), MacCountersTlv::Init(), BatteryLevelTlv::Init(), SupplyVoltageTlv::Init(), ChildTableTlv::Init(), ChannelPagesTlv::Init(), TypeListTlv::Init(), and MaxChildTimeoutTlv::Init().
GetTlv()
static otError GetTlv (const Message & aMessage, Type aType, uint16_t aMaxLength, Tlv & aTlv) inline static
This static method reads the requested TLV out of aMessage.
Parameters
[in] aMessage A reference to the message.
[in] aType The Type value to search for.
[in] aMaxLength Maximum number of bytes to read.
[out] aTlv A reference to the TLV that will be copied to.
Return values
OT_ERROR_NONE Successfully copied the TLV.
OT_ERROR_NOT_FOUND Could not find the TLV with Type aType.
References Tlv::Get().
GetOffset()
static otError GetOffset (const Message & aMessage, Type aType, uint16_t & aOffset) inline static
This static method obtains the offset of a TLV within aMessage.
Parameters
[in] aMessage A reference to the message.
[in] aType The Type value to search for.
[out] aOffset A reference to the offset of the TLV.
Return values
OT_ERROR_NONE Successfully copied the TLV.
OT_ERROR_NOT_FOUND Could not find the TLV with Type aType.
References Tlv::GetOffset(), OT_TOOL_PACKED_BEGIN, and ot::NetworkDiagnostic::OT_TOOL_PACKED_END.
The documentation for this class was generated from the following file:
network_diagnostic_tlvs.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale