OpenThread: SubMac::Callbacks Class Reference
SubMac::Callbacks Class Reference
#include <sub_mac.hpp>
Public Member Functions
Callbacks (Instance &aInstance)
void EnergyScanDone (int8_t aMaxRssi)
void ReceiveDone (RxFrame *aFrame, otError aError)
void RecordCcaStatus (bool aCcaSuccess, uint8_t aChannel)
void RecordFrameTransmitStatus (const TxFrame &aFrame, const RxFrame *aAckFrame, otError aError, uint8_t aRetryCount, bool aWillRetx)
void TransmitDone (TxFrame &aFrame, RxFrame *aAckFrame, otError aError)
Public Member Functions inherited from InstanceLocator
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Detailed Description
This class defines the callbacks notifying SubMac user of changes and events.
Constructor & Destructor Documentation
Callbacks()
Callbacks (Instance & aInstance) explicit
This constructor initializes the Callbacks object.
Parameters
[in] aInstance A reference to the OpenThread instance.
References SubMac::Callbacks::EnergyScanDone(), SubMac::HandleTransmitDone(), SubMac::Callbacks::ReceiveDone(), SubMac::Callbacks::RecordCcaStatus(), SubMac::Callbacks::RecordFrameTransmitStatus(), and SubMac::Callbacks::TransmitDone().
Member Function Documentation
ReceiveDone()
void ReceiveDone (RxFrame * aFrame, otError aError)
This method notifies user of SubMac of a received frame.
Parameters
[in] aFrame A pointer to the received frame or NULL if the receive operation failed.
[in] aError OT_ERROR_NONE when successfully received a frame, OT_ERROR_ABORT when reception was aborted and a frame was not received, OT_ERROR_NO_BUFS when a frame could not be received due to lack of rx buffer space.
Referenced by SubMac::Callbacks::Callbacks(), and SubMac::HandleReceiveDone().
RecordCcaStatus()
void RecordCcaStatus (bool aCcaSuccess, uint8_t aChannel)
This method notifies user of SubMac of CCA status (success/failure) for a frame transmission attempt.
This is intended for updating counters, logging, and/or tracking CCA failure rate statistics.
Parameters
[in] aCcaSuccess TRUE if the CCA succeeded, FALSE otherwise.
[in] aChannel The channel on which CCA was performed.
Referenced by SubMac::Callbacks::Callbacks(), and SubMac::HandleTransmitDone().
RecordFrameTransmitStatus()
void RecordFrameTransmitStatus (const TxFrame & aFrame, const RxFrame * aAckFrame, otError aError, uint8_t aRetryCount, bool aWillRetx)
This method notifies user of SubMac of the status of a frame transmission attempt.
This is intended for updating counters, logging, and/or collecting statistics.
Note
Unlike TransmitDone which is invoked after all re-transmission attempts to indicate the final status of a frame transmission, this method is invoked on all frame transmission attempts.
Parameters
[in] aFrame The transmitted frame.
[in] aAckFrame A pointer to the ACK frame, or NULL if no ACK was received.
[in] aError OT_ERROR_NONE when the frame was transmitted successfully, OT_ERROR_NO_ACK when the frame was transmitted but no ACK was received, OT_ERROR_CHANNEL_ACCESS_FAILURE tx failed due to activity on the channel, OT_ERROR_ABORT when transmission was aborted for other reasons.
[in] aRetryCount Current retry count. This is valid only when sub-mac handles frame re-transmissions.
[in] aWillRetx Indicates whether frame will be retransmitted or not. This is applicable only when there was an error in current transmission attempt.
Referenced by SubMac::Callbacks::Callbacks(), and SubMac::HandleTransmitDone().
TransmitDone()
void TransmitDone (TxFrame & aFrame, RxFrame * aAckFrame, otError aError)
The method notifies user of SubMac that the transmit operation has completed, providing, if applicable, the received ACK frame.
Parameters
[in] aFrame The transmitted frame.
[in] aAckFrame A pointer to the ACK frame, NULL if no ACK was received.
[in] aError OT_ERROR_NONE when the frame was transmitted, OT_ERROR_NO_ACK when the frame was transmitted but no ACK was received, OT_ERROR_CHANNEL_ACCESS_FAILURE tx failed due to activity on the channel, OT_ERROR_ABORT when transmission was aborted for other reasons.
Referenced by SubMac::Callbacks::Callbacks(), and SubMac::HandleTransmitDone().
EnergyScanDone()
void EnergyScanDone (int8_t aMaxRssi)
This method notifies user of SubMac that energy scan is complete.
Parameters
[in] aMaxRssi Maximum RSSI seen on the channel, or SubMac::kInvalidRssiValue if failed.
Referenced by SubMac::Callbacks::Callbacks(), and SubMac::HandleEnergyScanDone().
The documentation for this class was generated from the following files:
sub_mac.hpp
sub_mac_callbacks.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale