OpenThread: TrickleTimer Class Reference
TrickleTimer Class Reference
Core-timer-trickle
#include <trickle_timer.hpp>
Public Types
typedef bool(* Handler) (TrickleTimer &aTimer)
enum Mode { kModeNormal, kModePlainTimer, kModeMPL }
Public Types inherited from Timer
typedef void(* Handler) (Timer &aTimer)
Public Member Functions
void IndicateInconsistent (void)
bool IsRunning (void) const
otError Start (uint32_t aIntervalMin, uint32_t aIntervalMax, Mode aMode)
void Stop (void)
TrickleTimer (Instance &aInstance, Handler aTransmitHandler, Handler aIntervalExpiredHandler, void *aOwner)
Public Member Functions inherited from TimerMilli
void FireAt (TimeMilli aFireTime)
void FireAtIfEarlier (TimeMilli aFireTime)
void Start (uint32_t aDelay)
void StartAt (TimeMilli sStartTime, uint32_t aDelay)
void Stop (void)
TimerMilli (Instance &aInstance, Handler aHandler, void *aOwner)
Public Member Functions inherited from Timer
Time GetFireTime (void) const
bool IsRunning (void) const
Timer (Instance &aInstance, Handler aHandler, void *aOwner)
Public Member Functions inherited from InstanceLocator
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Public Member Functions inherited from OwnerLocator
template<typename OwnerType >
OwnerType & GetOwner (void)
Public Member Functions inherited from LinkedListEntry< Timer >
const Timer * GetNext (void) const
Timer * GetNext (void)
void SetNext (Timer *aNext)
Private Member Functions
void HandleEndOfInterval (void)
void HandleEndOfTimeInInterval (void)
void HandleTimer (void)
void StartAt (void)
void StartNewInterval (void)
Static Private Member Functions
static void HandleTimer (Timer &aTimer)
Private Attributes
uint32_t mInterval
Handler mIntervalExpiredHandler
uint32_t mIntervalMax
uint32_t mIntervalMin
bool mInTransmitPhase: 1
bool mIsRunning: 1
Mode mMode
uint32_t mTimeInInterval
Handler mTransmitHandler
Additional Inherited Members
Static Public Member Functions inherited from TimerMilli
static TimeMilli GetNow (void)
Static Public Attributes inherited from Timer
static const uint32_t kMaxDelay = (Time::kMaxDuration >> 1)
Protected Member Functions inherited from Timer
bool DoesFireBefore (const Timer &aSecondTimer, Time aNow)
void Fired (void)
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Protected Member Functions inherited from OwnerLocator
OwnerLocator (void *aOwner)
Protected Attributes inherited from Timer
Time mFireTime
Handler mHandler
Timer * mNext
Detailed Description
This class implements a trickle timer.
Member Typedef Documentation
Handler
typedef bool(* Handler) (TrickleTimer &aTimer)
This function pointer is called when the timer expires.
Parameters
[in] aTimer A reference to the trickle timer.
Return values
TRUE If the trickle timer should continue running.
FALSE If the trickle timer should stop running.
Member Enumeration Documentation
Mode
enum Mode
This enumeration defines the modes of operation for the TrickleTimer.
Enumerator
kModeNormal
Runs the normal trickle logic (as per RFC6206).
kModePlainTimer
Runs a plain timer with random interval selected between min/max intervals.
kModeMPL
Runs the trickle logic modified for MPL.
Constructor & Destructor Documentation
TrickleTimer()
TrickleTimer (Instance & aInstance, Handler aTransmitHandler, Handler aIntervalExpiredHandler, void * aOwner)
This constructor initializes a TrickleTimer instance.
Parameters
[in] aInstance A reference to the OpenThread instance.
[in] aRedundancyConstant The redundancy constant for the timer, also known as k.
[in] aTransmitHandler A pointer to a function that is called when transmission should occur.
[in] aIntervalExpiredHandler An optional pointer to a function that is called when the interval expires.
[in] aOwner A pointer to owner of the TrickleTimer object.
References OT_ASSERT.
Member Function Documentation
IsRunning()
bool IsRunning (void) const inline
This method indicates whether or not the trickle timer instance is running.
Return values
TRUE If the trickle timer is running.
FALSE If the trickle timer is not running.
References TrickleTimer::HandleEndOfInterval(), TrickleTimer::HandleEndOfTimeInInterval(), TrickleTimer::HandleTimer(), TrickleTimer::IndicateInconsistent(), TrickleTimer::mIsRunning, TrickleTimer::Start(), TrickleTimer::StartNewInterval(), and TrickleTimer::Stop().
Start()
otError Start (uint32_t aIntervalMin, uint32_t aIntervalMax, Mode aMode)
This method starts the trickle timer.
Parameters
[in] aIntervalMin The minimum interval for the timer in milliseconds.
[in] aIntervalMax The maximum interval for the timer in milliseconds.
[in] aMode The operating mode for the timer.
Return values
OT_ERROR_NONE The timer started successfully.
OT_ERROR_INVALID_ARGS The given parameters are invalid (i.e., max interval is smaller than min).
References ot::Random::NonCrypto::GetUint32InRange(), TrickleTimer::mInterval, TrickleTimer::mIntervalMax, TrickleTimer::mIntervalMin, TrickleTimer::mIsRunning, TrickleTimer::mMode, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, TrickleTimer::StartNewInterval(), and VerifyOrExit.
Referenced by TrickleTimer::IsRunning().
Stop()
void Stop (void)
This method stops the trickle timer.
References TrickleTimer::mIsRunning, and TimerMilli::Stop().
Referenced by TrickleTimer::HandleEndOfInterval(), TrickleTimer::HandleEndOfTimeInInterval(), and TrickleTimer::IsRunning().
IndicateInconsistent()
void IndicateInconsistent (void)
This method indicates to the trickle timer an 'inconsistent' state.
References TrickleTimer::mInterval, TrickleTimer::mIntervalMin, TrickleTimer::mIsRunning, OT_NOOP, TrickleTimer::StartNewInterval(), and VerifyOrExit.
Referenced by TrickleTimer::IsRunning().
StartNewInterval()
void StartNewInterval (void) private
References ot::Random::NonCrypto::GetUint32InRange(), TrickleTimer::kModeMPL, TrickleTimer::kModeNormal, TrickleTimer::kModePlainTimer, TrickleTimer::mInterval, TrickleTimer::mInTransmitPhase, TrickleTimer::mMode, TrickleTimer::mTimeInInterval, TimerMilli::Start(), and VerifyOrExit.
Referenced by TrickleTimer::HandleEndOfInterval(), TrickleTimer::HandleEndOfTimeInInterval(), TrickleTimer::IndicateInconsistent(), TrickleTimer::IsRunning(), and TrickleTimer::Start().
HandleTimer() [1/2]
void HandleTimer (Timer & aTimer) static private
References TrickleTimer::HandleTimer().
HandleTimer() [2/2]
void HandleTimer (void) private
References TrickleTimer::HandleEndOfInterval(), TrickleTimer::HandleEndOfTimeInInterval(), and TrickleTimer::mInTransmitPhase.
Referenced by TrickleTimer::HandleTimer(), and TrickleTimer::IsRunning().
HandleEndOfTimeInInterval()
void HandleEndOfTimeInInterval (void) private
References ot::Random::NonCrypto::GetUint32InRange(), TrickleTimer::kModeMPL, TrickleTimer::kModeNormal, TrickleTimer::kModePlainTimer, TrickleTimer::mInterval, TrickleTimer::mIntervalMax, TrickleTimer::mIntervalMin, TrickleTimer::mInTransmitPhase, TrickleTimer::mMode, TrickleTimer::mTimeInInterval, TrickleTimer::mTransmitHandler, TimerMilli::Start(), TrickleTimer::StartNewInterval(), TrickleTimer::Stop(), and VerifyOrExit.
Referenced by TrickleTimer::HandleTimer(), and TrickleTimer::IsRunning().
HandleEndOfInterval()
void HandleEndOfInterval (void) private
References TrickleTimer::mInterval, TrickleTimer::mIntervalExpiredHandler, TrickleTimer::mIntervalMax, TrickleTimer::StartNewInterval(), TrickleTimer::Stop(), and VerifyOrExit.
Referenced by TrickleTimer::HandleTimer(), and TrickleTimer::IsRunning().
StartAt()
void StartAt (void) inline private
Field Documentation
mIntervalMin
uint32_t mIntervalMin private
Referenced by TrickleTimer::HandleEndOfTimeInInterval(), TrickleTimer::IndicateInconsistent(), and TrickleTimer::Start().
mIntervalMax
uint32_t mIntervalMax private
Referenced by TrickleTimer::HandleEndOfInterval(), TrickleTimer::HandleEndOfTimeInInterval(), and TrickleTimer::Start().
mInterval
uint32_t mInterval private
Referenced by TrickleTimer::HandleEndOfInterval(), TrickleTimer::HandleEndOfTimeInInterval(), TrickleTimer::IndicateInconsistent(), TrickleTimer::Start(), and TrickleTimer::StartNewInterval().
mTimeInInterval
uint32_t mTimeInInterval private
Referenced by TrickleTimer::HandleEndOfTimeInInterval(), and TrickleTimer::StartNewInterval().
mTransmitHandler
Handler mTransmitHandler private
Referenced by TrickleTimer::HandleEndOfTimeInInterval().
mIntervalExpiredHandler
Handler mIntervalExpiredHandler private
Referenced by TrickleTimer::HandleEndOfInterval().
mMode
Mode mMode private
Referenced by TrickleTimer::HandleEndOfTimeInInterval(), TrickleTimer::Start(), and TrickleTimer::StartNewInterval().
mIsRunning
bool mIsRunning private
Referenced by TrickleTimer::IndicateInconsistent(), TrickleTimer::IsRunning(), TrickleTimer::Start(), and TrickleTimer::Stop().
mInTransmitPhase
bool mInTransmitPhase private
Referenced by TrickleTimer::HandleEndOfTimeInInterval(), TrickleTimer::HandleTimer(), and TrickleTimer::StartNewInterval().
The documentation for this class was generated from the following files:
trickle_timer.hpp
trickle_timer.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale