OpenThread: SettingsBase Class Reference
SettingsBase Class Reference
#include <settings.hpp>
Data Structures
class ChildInfo
class NetworkInfo
class ParentInfo
Public Types
enum Key {
kKeyActiveDataset = 0x0001, kKeyPendingDataset = 0x0002, kKeyNetworkInfo = 0x0003, kKeyParentInfo = 0x0004,
kKeyChildInfo = 0x0005, kKeyReserved = 0x0006, kKeySlaacIidSecretKey = 0x0007
}
Data Fields
OT_TOOL_PACKED_BEGIN class ot::SettingsBase::NetworkInfo OT_TOOL_PACKED_END
OT_TOOL_PACKED_BEGIN class ot::SettingsBase::ParentInfo OT_TOOL_PACKED_END
OT_TOOL_PACKED_BEGIN class ot::SettingsBase::ChildInfo OT_TOOL_PACKED_END
Protected Member Functions
void LogChildInfo (const char *, const ChildInfo &) const
void LogFailure (otError, const char *, bool) const
void LogNetworkInfo (const char *, const NetworkInfo &) const
void LogParentInfo (const char *, const ParentInfo &) const
SettingsBase (Instance &aInstance)
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Additional Inherited Members
Public Member Functions inherited from InstanceLocator
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Detailed Description
This class defines the base class used by Settings and Settings::ChildInfoIterator.
This class provides structure definitions for different settings keys.
Member Enumeration Documentation
Key
enum Key
This enumeration defines the keys of settings.
Enumerator
kKeyActiveDataset
Active Operational Dataset.
kKeyPendingDataset
Pending Operational Dataset.
kKeyNetworkInfo
Thread network information.
kKeyParentInfo
Parent information.
kKeyChildInfo
Child information.
kKeyReserved
Reserved (previously auto-start)
kKeySlaacIidSecretKey
Secret key used by SLAAC module for generating semantically opaque IID.
Constructor & Destructor Documentation
SettingsBase()
SettingsBase (Instance & aInstance) inline explicit protected
Member Function Documentation
LogNetworkInfo()
void LogNetworkInfo (const char * , const NetworkInfo &) const inline protected
LogParentInfo()
void LogParentInfo (const char * , const ParentInfo &) const inline protected
LogChildInfo()
void LogChildInfo (const char * , const ChildInfo &) const inline protected
Referenced by Settings::ChildInfoIterator::Delete(), and Settings::ChildInfoIterator::Read().
LogFailure()
void LogFailure (otError , const char * , bool) const inline protected
Referenced by Settings::ChildInfoIterator::Delete().
Field Documentation
OT_TOOL_PACKED_END [1/3]
OT_TOOL_PACKED_BEGIN class ot::SettingsBase::NetworkInfo OT_TOOL_PACKED_END
OT_TOOL_PACKED_END [2/3]
OT_TOOL_PACKED_BEGIN class ot::SettingsBase::ParentInfo OT_TOOL_PACKED_END
OT_TOOL_PACKED_END [3/3]
OT_TOOL_PACKED_BEGIN class ot::SettingsBase::ChildInfo OT_TOOL_PACKED_END
The documentation for this class was generated from the following file:
settings.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale