OpenThread: Tlv Class Reference
Tlv Class Reference
MLE » TLVs
#include <mle_tlvs.hpp>
Public Types
enum Type {
kSourceAddress = 0, kMode = 1, kTimeout = 2, kChallenge = 3,
kResponse = 4, kLinkFrameCounter = 5, kLinkQuality = 6, kNetworkParameter = 7,
kMleFrameCounter = 8, kRoute = 9, kAddress16 = 10, kLeaderData = 11,
kNetworkData = 12, kTlvRequest = 13, kScanMask = 14, kConnectivity = 15,
kLinkMargin = 16, kStatus = 17, kVersion = 18, kAddressRegistration = 19,
kChannel = 20, kPanId = 21, kActiveTimestamp = 22, kPendingTimestamp = 23,
kActiveDataset = 24, kPendingDataset = 25, kDiscovery = 26, kTimeRequest = 252,
kTimeParameter = 253, kXtalAccuracy = 254, kInvalid = 255
}
Public Types inherited from Tlv
enum { kBaseTlvMaxLength = OT_NETWORK_BASE_TLV_MAX_LENGTH }
Public Member Functions
Type GetType (void) const
void SetType (Type aType)
Public Member Functions inherited from Tlv
otError AppendTo (Message &aMessage) const
uint8_t GetLength (void) const
Tlv * GetNext (void)
const Tlv * GetNext (void) const
uint32_t GetSize (void) const
uint8_t GetType (void) const
uint8_t * GetValue (void)
const uint8_t * GetValue (void) const
bool IsExtended (void) const
void SetLength (uint8_t aLength)
void SetType (uint8_t aType)
Static Public Member Functions
static otError GetOffset (const Message &aMessage, Type aType, uint16_t &aOffset)
static otError GetTlv (const Message &aMessage, Type aType, uint16_t aMaxLength, Tlv &aTlv)
Static Public Member Functions inherited from Tlv
static otError AppendTlv (Message &aMessage, uint8_t aType, const uint8_t *aValue, uint8_t aLength)
static otError AppendUint16Tlv (Message &aMessage, uint8_t aType, uint16_t aValue)
static otError AppendUint32Tlv (Message &aMessage, uint8_t aType, uint32_t aValue)
static otError AppendUint8Tlv (Message &aMessage, uint8_t aType, uint8_t aValue)
static otError Get (const Message &aMessage, uint8_t aType, uint16_t aMaxSize, Tlv &aTlv)
static otError GetOffset (const Message &aMessage, uint8_t aType, uint16_t &aOffset)
static otError GetValueOffset (const Message &aMessage, uint8_t aType, uint16_t &aOffset, uint16_t &aLength)
static otError ReadTlv (const Message &aMessage, uint8_t aType, void *aValue, uint8_t aLength)
static otError ReadUint16Tlv (const Message &aMessage, uint8_t aType, uint16_t &aValue)
static otError ReadUint32Tlv (const Message &aMessage, uint8_t aType, uint32_t &aValue)
static otError ReadUint8Tlv (const Message &aMessage, uint8_t aType, uint8_t &aValue)
Additional Inherited Members
Protected Types inherited from Tlv
enum { kExtendedLength = 255 }
Detailed Description
This class implements MLE TLV generation and parsing.
Member Enumeration Documentation
Type
enum Type
MLE TLV Types.
Enumerator
kSourceAddress
Source Address TLV.
kMode
Mode TLV.
kTimeout
Timeout TLV.
kChallenge
Challenge TLV.
kResponse
Response TLV.
kLinkFrameCounter
Link-Layer Frame Counter TLV.
kLinkQuality
Link Quality TLV.
kNetworkParameter
Network Parameter TLV.
kMleFrameCounter
MLE Frame Counter TLV.
kRoute
Route64 TLV.
kAddress16
Address16 TLV.
kLeaderData
Leader Data TLV.
kNetworkData
Network Data TLV.
kTlvRequest
TLV Request TLV.
kScanMask
Scan Mask TLV.
kConnectivity
Connectivity TLV.
kLinkMargin
Link Margin TLV.
kStatus
Status TLV.
kVersion
Version TLV.
kAddressRegistration
Address Registration TLV.
kChannel
Channel TLV.
kPanId
PAN ID TLV.
kActiveTimestamp
Active Timestamp TLV.
kPendingTimestamp
Pending Timestamp TLV.
kActiveDataset
Active Operational Dataset TLV.
kPendingDataset
Pending Operational Dataset TLV.
kDiscovery
Thread Discovery TLV.
kTimeRequest
Time Request TLV.
Applicable/Required only when time synchronization service (OPENTHREAD_CONFIG_TIME_SYNC_ENABLE) is enabled.
kTimeParameter
Time Parameter TLV.
kXtalAccuracy
XTAL Accuracy TLV.
kInvalid
Member Function Documentation
GetType()
Type GetType (void) const inline
This method returns the Type value.
Returns
The Type value.
References Tlv::GetType().
SetType()
void SetType (Type aType) inline
This method sets the Type value.
Parameters
[in] aType The Type value.
References Tlv::SetType().
Referenced by Mle::AppendAddressRegistration(), Dataset::AppendMleDatasetTlv(), Mle::Discover(), RouteTlv::Init(), LeaderDataTlv::Init(), ConnectivityTlv::Init(), ChannelTlv::Init(), ActiveTimestampTlv::Init(), and PendingTimestampTlv::Init().
GetTlv()
static otError GetTlv (const Message & aMessage, Type aType, uint16_t aMaxLength, Tlv & aTlv) inline static
This static method reads the requested TLV out of aMessage.
Parameters
[in] aMessage A reference to the message.
[in] aType The Type value to search for.
[in] aMaxLength Maximum number of bytes to read.
[out] aTlv A reference to the TLV that will be copied to.
Return values
OT_ERROR_NONE Successfully copied the TLV.
OT_ERROR_NOT_FOUND Could not find the TLV with Type aType.
References Tlv::Get().
Referenced by Mle::HandleAdvertisement(), Mle::HandleAnnounce(), Mle::HandleChildIdResponse(), Mle::HandleLeaderData(), Mle::HandleParentResponse(), and Mle::ReadLeaderData().
GetOffset()
static otError GetOffset (const Message & aMessage, Type aType, uint16_t & aOffset) inline static
This static method obtains the offset of a TLV within aMessage.
Parameters
[in] aMessage A reference to the message.
[in] aType The Type value to search for.
[out] aOffset A reference to the offset of the TLV.
Return values
OT_ERROR_NONE Successfully copied the TLV.
OT_ERROR_NOT_FOUND Could not find the TLV with Type aType.
References Tlv::GetOffset(), OT_TOOL_PACKED_BEGIN, and ot::Mle::OT_TOOL_PACKED_END.
Referenced by Mle::HandleChildIdResponse(), Mle::HandleDiscoveryResponse(), and Mle::HandleLeaderData().
The documentation for this class was generated from the following file:
mle_tlvs.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale