OpenThread: JamDetector Class Reference
JamDetector Class Reference
#include <jam_detector.hpp>
Public Types
typedef void(* Handler) (bool aJamState, void *aContext)
Public Member Functions
uint8_t GetBusyPeriod (void) const
uint64_t GetHistoryBitmap (void) const
int8_t GetRssiThreshold (void) const
bool GetState (void) const
uint8_t GetWindow (void) const
bool IsEnabled (void) const
JamDetector (Instance &aInstance)
otError SetBusyPeriod (uint8_t aBusyPeriod)
void SetRssiThreshold (int8_t aThreshold)
otError SetWindow (uint8_t aWindow)
otError Start (Handler aHandler, void *aContext)
otError Stop (void)
Public Member Functions inherited from InstanceLocator
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Private Types
enum {
kMaxWindow = 63, kDefaultRssiThreshold = 0, kMaxSampleInterval = 256, kMinSampleInterval = 2,
kMaxRandomDelay = 4, kOneSecondInterval = 1000
}
Private Member Functions
void CheckState (void)
void HandleStateChanged (otChangedFlags aFlags)
void HandleTimer (void)
void SetJamState (bool aNewState)
void UpdateHistory (bool aDidExceedThreshold)
void UpdateJamState (void)
Static Private Member Functions
static void HandleStateChanged (Notifier::Callback &aCallback, otChangedFlags aFlags)
static void HandleTimer (Timer &aTimer)
Private Attributes
bool mAlwaysAboveThreshold: 1
uint8_t mBusyPeriod: 6
void * mContext
TimeMilli mCurSecondStartTime
bool mEnabled: 1
Handler mHandler
uint64_t mHistoryBitmap
bool mJamState: 1
Notifier::Callback mNotifierCallback
int8_t mRssiThreshold
uint16_t mSampleInterval
TimerMilli mTimer
uint8_t mWindow: 6
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Member Typedef Documentation
Handler
typedef void(* Handler) (bool aJamState, void *aContext)
This function pointer is called if jam state changes (assuming jamming detection is enabled).
Parameters
[in] aJamState true if jam is detected, false if jam is cleared.
[in] aContext A pointer to application-specific context.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
kMaxWindow
kDefaultRssiThreshold
kMaxSampleInterval
kMinSampleInterval
kMaxRandomDelay
kOneSecondInterval
Constructor & Destructor Documentation
JamDetector()
JamDetector (Instance & aInstance) explicit
This constructor initializes the object.
Parameters
[in] aInstance A reference to the OpenThread instance.
Member Function Documentation
Start()
otError Start (Handler aHandler, void * aContext)
Start the jamming detection.
Parameters
[in] aHandler A pointer to a function called when jamming is detected.
[in] aContext A pointer to application-specific context.
Return values
OT_ERROR_NONE Successfully started the jamming detection.
OT_ERROR_ALREADY Jam detection has been started before.
Stop()
otError Stop (void)
Stop the jamming detection.
Return values
OT_ERROR_NONE Successfully stopped the jamming detection.
OT_ERROR_ALREADY Jam detection is already stopped.
IsEnabled()
bool IsEnabled (void) const inline
Get the Jam Detection Status
Returns
The Jam Detection status (true if enabled, false otherwise).
References JamDetector::mEnabled.
GetState()
bool GetState (void) const inline
Get the current jam state.
Returns
The jamming state (true if jam is detected, false otherwise).
References JamDetector::mJamState, and JamDetector::SetRssiThreshold().
SetRssiThreshold()
void SetRssiThreshold (int8_t aThreshold)
Set the Jam Detection RSSI Threshold (in dBm).
Parameters
[in] aRssiThreshold The RSSI threshold.
Referenced by JamDetector::GetState().
GetRssiThreshold()
int8_t GetRssiThreshold (void) const inline
Get the Jam Detection RSSI Threshold (in dBm).
Returns
The Jam Detection RSSI Threshold.
References JamDetector::mRssiThreshold, and JamDetector::SetWindow().
SetWindow()
otError SetWindow (uint8_t aWindow)
Set the Jam Detection Detection Window (in seconds).
Parameters
[in] aWindow The Jam Detection window (valid range is 1 to 63)
Return values
OT_ERROR_NONE Successfully set the window.
OT_ERROR_INVALID_ARGS The given input parameter not within valid range (1-63)
Referenced by JamDetector::GetRssiThreshold().
GetWindow()
uint8_t GetWindow (void) const inline
Get the Jam Detection Detection Window (in seconds).
Returns
The Jam Detection Window.
References JamDetector::mWindow, and JamDetector::SetBusyPeriod().
SetBusyPeriod()
otError SetBusyPeriod (uint8_t aBusyPeriod)
Set the Jam Detection Busy Period (in seconds).
The number of aggregate seconds within the detection window where the RSSI must be above threshold to trigger detection.
Parameters
[in] aBusyPeriod The Jam Detection busy period (should be non-zero and less than or equal to Jam Detection Window)
Return values
OT_ERROR_NONE Successfully set the window.
OT_ERROR_INVALID_ARGS The given input is not within the valid range.
Referenced by JamDetector::GetWindow().
GetBusyPeriod()
uint8_t GetBusyPeriod (void) const inline
Get the Jam Detection Busy Period (in seconds)
Returns
The Jam Detection Busy Period
References JamDetector::mBusyPeriod.
GetHistoryBitmap()
uint64_t GetHistoryBitmap (void) const inline
Get the current history bitmap.
This value provides information about current state of jamming detection module for monitoring/debugging purpose. It provides a 64-bit value where each bit corresponds to one second interval starting with bit 0 for the most recent interval and bit 63 for the oldest intervals (63 earlier). The bit is set to 1 if the jamming detection module observed/detected high signal level during the corresponding one second interval.
Returns
The current history bitmap.
References JamDetector::mHistoryBitmap.
CheckState()
void CheckState (void) private
SetJamState()
void SetJamState (bool aNewState) private
HandleTimer() [1/2]
static void HandleTimer (Timer & aTimer) static private
HandleTimer() [2/2]
void HandleTimer (void) private
UpdateHistory()
void UpdateHistory (bool aDidExceedThreshold) private
UpdateJamState()
void UpdateJamState (void) private
HandleStateChanged() [1/2]
static void HandleStateChanged (Notifier::Callback & aCallback, otChangedFlags aFlags) static private
HandleStateChanged() [2/2]
void HandleStateChanged (otChangedFlags aFlags) private
Field Documentation
mHandler
Handler mHandler private
mContext
void* mContext private
mNotifierCallback
Notifier::Callback mNotifierCallback private
mTimer
TimerMilli mTimer private
mHistoryBitmap
uint64_t mHistoryBitmap private
Referenced by JamDetector::GetHistoryBitmap().
mCurSecondStartTime
TimeMilli mCurSecondStartTime private
mSampleInterval
uint16_t mSampleInterval private
mWindow
uint8_t mWindow private
Referenced by JamDetector::GetWindow().
mBusyPeriod
uint8_t mBusyPeriod private
Referenced by JamDetector::GetBusyPeriod().
mEnabled
bool mEnabled private
Referenced by JamDetector::IsEnabled().
mAlwaysAboveThreshold
bool mAlwaysAboveThreshold private
mJamState
bool mJamState private
Referenced by JamDetector::GetState().
mRssiThreshold
int8_t mRssiThreshold private
Referenced by JamDetector::GetRssiThreshold().
The documentation for this class was generated from the following file:
jam_detector.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale