OpenThread: BorderAgent Class Reference
BorderAgent Class Reference
#include <border_agent.hpp>
Public Member Functions
void ApplyMeshLocalPrefix (void)
BorderAgent (Instance &aInstance)
otBorderAgentState GetState (void) const
otError Start (void)
otError Stop (void)
Public Member Functions inherited from InstanceLocator
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Private Types
enum { kKeepAliveTimeout = 50 * 1000, kRestartDelay = 1 * 1000 }
Private Member Functions
otError ForwardToCommissioner (Coap::Message &aForwardMessage, const Message &aMessage)
otError ForwardToLeader (const Coap::Message &aMessage, const Ip6::MessageInfo &aMessageInfo, const char *aPath, bool aPetition, bool aSeparate)
void HandleConnected (bool aConnected)
void HandleKeepAlive (const Coap::Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
void HandleProxyTransmit (const Coap::Message &aMessage)
void HandleRelayReceive (const Coap::Message &aMessage)
void HandleRelayTransmit (const Coap::Message &aMessage)
void HandleStateChanged (otChangedFlags aFlags)
void HandleTimeout (void)
bool HandleUdpReceive (const Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
void SetState (otBorderAgentState aState)
Static Private Member Functions
static void HandleCoapResponse (void *aContext, otMessage *aMessage, const otMessageInfo *aMessageInfo, otError aResult)
static void HandleConnected (bool aConnected, void *aContext)
template<Coap::Resource BorderAgent::* aResource>
static void HandleRequest (void *aContext, otMessage *aMessage, const otMessageInfo *aMessageInfo)
static void HandleStateChanged (Notifier::Callback &aCallback, otChangedFlags aFlags)
static void HandleTimeout (Timer &aTimer)
static bool HandleUdpReceive (void *aContext, const otMessage *aMessage, const otMessageInfo *aMessageInfo)
Private Attributes
Coap::Resource mActiveGet
Coap::Resource mActiveSet
Ip6::NetifUnicastAddress mCommissionerAloc
Coap::Resource mCommissionerGet
Coap::Resource mCommissionerKeepAlive
Coap::Resource mCommissionerPetition
Coap::Resource mCommissionerSet
Ip6::MessageInfo mMessageInfo
Notifier::Callback mNotifierCallback
Coap::Resource mPendingGet
Coap::Resource mPendingSet
Coap::Resource mProxyTransmit
Coap::Resource mRelayReceive
Coap::Resource mRelayTransmit
otBorderAgentState mState
TimerMilli mTimer
Ip6::UdpReceiver mUdpReceiver
The UDP receiver to receive packets from external commissioner.
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
kKeepAliveTimeout
Timeout to reject a commissioner.
kRestartDelay
Delay to restart border agent service.
Constructor & Destructor Documentation
BorderAgent()
BorderAgent (Instance & aInstance) explicit
This constructor initializes the BorderAgent object.
Parameters
[in] aInstance A reference to the OpenThread instance.
Member Function Documentation
Start()
otError Start (void)
This method starts the Border Agent service.
Return values
OT_ERROR_NONE Successfully started the Border Agent service.
OT_ERROR_ALREADY Border Agent is already started.
Stop()
otError Stop (void)
This method stops the Border Agent service.
Return values
OT_ERROR_NONE Successfully stopped the Border Agent service.
OT_ERROR_ALREADY Border Agent is already stopped.
GetState()
otBorderAgentState GetState (void) const inline
This method gets the state of the Border Agent service.
Returns
The state of the Border Agent service.
References BorderAgent::ApplyMeshLocalPrefix(), BorderAgent::HandleStateChanged(), and BorderAgent::mState.
ApplyMeshLocalPrefix()
void ApplyMeshLocalPrefix (void)
This method applies the Mesh Local Prefix.
Referenced by BorderAgent::GetState().
HandleStateChanged() [1/2]
static void HandleStateChanged (Notifier::Callback & aCallback, otChangedFlags aFlags) static private
Referenced by BorderAgent::GetState().
HandleStateChanged() [2/2]
void HandleStateChanged (otChangedFlags aFlags) private
HandleConnected() [1/2]
static void HandleConnected (bool aConnected, void * aContext) inline static private
HandleConnected() [2/2]
void HandleConnected (bool aConnected) private
HandleRequest()
static void HandleRequest (void * aContext, otMessage * aMessage, const otMessageInfo * aMessageInfo) inline static private
References BorderAgent::ForwardToCommissioner(), BorderAgent::ForwardToLeader(), BorderAgent::HandleCoapResponse(), BorderAgent::HandleKeepAlive(), BorderAgent::HandleProxyTransmit(), BorderAgent::HandleRelayReceive(), BorderAgent::HandleRelayTransmit(), and BorderAgent::HandleTimeout().
HandleTimeout() [1/2]
static void HandleTimeout (Timer & aTimer) static private
HandleTimeout() [2/2]
void HandleTimeout (void) private
Referenced by BorderAgent::HandleRequest().
HandleCoapResponse()
static void HandleCoapResponse (void * aContext, otMessage * aMessage, const otMessageInfo * aMessageInfo, otError aResult) static private
Referenced by BorderAgent::HandleRequest().
ForwardToLeader()
otError ForwardToLeader (const Coap::Message & aMessage, const Ip6::MessageInfo & aMessageInfo, const char * aPath, bool aPetition, bool aSeparate) private
Referenced by BorderAgent::HandleRequest().
ForwardToCommissioner()
otError ForwardToCommissioner (Coap::Message & aForwardMessage, const Message & aMessage) private
Referenced by BorderAgent::HandleRequest().
HandleKeepAlive()
void HandleKeepAlive (const Coap::Message & aMessage, const Ip6::MessageInfo & aMessageInfo) private
Referenced by BorderAgent::HandleRequest().
HandleRelayTransmit()
void HandleRelayTransmit (const Coap::Message & aMessage) private
Referenced by BorderAgent::HandleRequest().
HandleRelayReceive()
void HandleRelayReceive (const Coap::Message & aMessage) private
Referenced by BorderAgent::HandleRequest().
HandleProxyTransmit()
void HandleProxyTransmit (const Coap::Message & aMessage) private
Referenced by BorderAgent::HandleRequest().
HandleUdpReceive() [1/2]
static bool HandleUdpReceive (void * aContext, const otMessage * aMessage, const otMessageInfo * aMessageInfo) inline static private
References BorderAgent::SetState().
HandleUdpReceive() [2/2]
bool HandleUdpReceive (const Message & aMessage, const Ip6::MessageInfo & aMessageInfo) private
SetState()
void SetState (otBorderAgentState aState) private
Referenced by BorderAgent::HandleUdpReceive().
Field Documentation
mMessageInfo
Ip6::MessageInfo mMessageInfo private
mCommissionerPetition
Coap::Resource mCommissionerPetition private
mCommissionerKeepAlive
Coap::Resource mCommissionerKeepAlive private
mRelayTransmit
Coap::Resource mRelayTransmit private
mRelayReceive
Coap::Resource mRelayReceive private
mCommissionerGet
Coap::Resource mCommissionerGet private
mCommissionerSet
Coap::Resource mCommissionerSet private
mActiveGet
Coap::Resource mActiveGet private
mActiveSet
Coap::Resource mActiveSet private
mPendingGet
Coap::Resource mPendingGet private
mPendingSet
Coap::Resource mPendingSet private
mProxyTransmit
Coap::Resource mProxyTransmit private
mUdpReceiver
Ip6::UdpReceiver mUdpReceiver private
The UDP receiver to receive packets from external commissioner.
mCommissionerAloc
Ip6::NetifUnicastAddress mCommissionerAloc private
mTimer
TimerMilli mTimer private
mState
otBorderAgentState mState private
Referenced by BorderAgent::GetState().
mNotifierCallback
Notifier::Callback mNotifierCallback private
The documentation for this class was generated from the following file:
border_agent.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale