OpenThread: LeaderBase Class Reference
LeaderBase Class Reference
Core-netdata » Leader
#include <network_data_leader.hpp>
Public Member Functions
otError GetBackboneRouterPrimary (BackboneRouter::BackboneRouterConfig &aConfig) const
CommissioningDataTlv * GetCommissioningData (void)
const CommissioningDataTlv * GetCommissioningData (void) const
MeshCoP::Tlv * GetCommissioningDataSubTlv (MeshCoP::Tlv::Type aType)
const MeshCoP::Tlv * GetCommissioningDataSubTlv (MeshCoP::Tlv::Type aType) const
otError GetContext (const Ip6::Address &aAddress, Lowpan::Context &aContext) const
otError GetContext (uint8_t aContextId, Lowpan::Context &aContext) const
otError GetRlocByContextId (uint8_t aContextId, uint16_t &aRloc16) const
otError GetServiceId (uint32_t aEnterpriseNumber, const uint8_t *aServiceData, uint8_t aServiceDataLength, bool aServerStable, uint8_t &aServiceId) const
uint8_t GetStableVersion (void) const
uint8_t GetVersion (void) const
bool IsJoiningEnabled (void) const
bool IsOnMesh (const Ip6::Address &aAddress) const
LeaderBase (Instance &aInstance)
void Reset (void)
otError RouteLookup (const Ip6::Address &aSource, const Ip6::Address &aDestination, uint8_t *aPrefixMatch, uint16_t *aRloc16) const
otError SendServerDataNotification (uint16_t aRloc16)
otError SetCommissioningData (const uint8_t *aValue, uint8_t aValueLength)
otError SetNetworkData (uint8_t aVersion, uint8_t aStableVersion, bool aStableOnly, const Message &aMessage, uint16_t aMessageOffset)
Public Member Functions inherited from NetworkData
void Clear (void)
bool ContainsExternalRoutes (const NetworkData &aCompare, uint16_t aRloc16) const
bool ContainsOnMeshPrefixes (const NetworkData &aCompare, uint16_t aRloc16) const
bool ContainsService (uint8_t aServiceId, uint16_t aRloc16) const
bool ContainsServices (const NetworkData &aCompare, uint16_t aRloc16) const
otError GetNetworkData (bool aStable, uint8_t *aData, uint8_t &aDataLength) const
otError GetNextExternalRoute (Iterator &aIterator, ExternalRouteConfig &aConfig) const
otError GetNextExternalRoute (Iterator &aIterator, uint16_t aRloc16, ExternalRouteConfig &aConfig) const
otError GetNextOnMeshPrefix (Iterator &aIterator, OnMeshPrefixConfig &aConfig) const
otError GetNextOnMeshPrefix (Iterator &aIterator, uint16_t aRloc16, OnMeshPrefixConfig &aConfig) const
otError GetNextServer (Iterator &aIterator, uint16_t &aRloc16) const
otError GetNextService (Iterator &aIterator, ServiceConfig &aConfig) const
otError GetNextService (Iterator &aIterator, uint16_t aRloc16, ServiceConfig &aConfig) const
otError GetNextServiceId (Iterator &aIterator, uint16_t aRloc16, uint8_t &aServiceId) const
NetworkData (Instance &aInstance, Type aType)
Public Member Functions inherited from InstanceLocator
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Protected Attributes
uint8_t mStableVersion
uint8_t mVersion
Protected Attributes inherited from NetworkData
uint8_t mTlvs [kMaxSize]
The Network Data buffer.
Private Member Functions
otError DefaultRouteLookup (const PrefixTlv &aPrefix, uint16_t *aRloc16) const
otError ExternalRouteLookup (uint8_t aDomainId, const Ip6::Address &aDestination, uint8_t *aPrefixMatch, uint16_t *aRloc16) const
const PrefixTlv * FindNextMatchingPrefix (const Ip6::Address &aAddress, const PrefixTlv *aPrevTlv) const
otError RemoveCommissioningData (void)
Additional Inherited Members
Public Types inherited from NetworkData
enum { kMaxSize = 254 }
enum Type { kTypeLocal, kTypeLeader }
Protected Member Functions inherited from NetworkData
NetworkDataTlv * AppendTlv (uint16_t aTlvSize)
bool CanInsert (uint16_t aSize) const
PrefixTlv * FindPrefix (const uint8_t *aPrefix, uint8_t aPrefixLength)
const PrefixTlv * FindPrefix (const uint8_t *aPrefix, uint8_t aPrefixLength) const
ServiceTlv * FindService (uint32_t aEnterpriseNumber, const uint8_t *aServiceData, uint8_t aServiceDataLength)
const ServiceTlv * FindService (uint32_t aEnterpriseNumber, const uint8_t *aServiceData, uint8_t aServiceDataLength) const
NetworkDataTlv * GetTlvsEnd (void)
const NetworkDataTlv * GetTlvsEnd (void) const
NetworkDataTlv * GetTlvsStart (void)
const NetworkDataTlv * GetTlvsStart (void) const
void Insert (void *aStart, uint8_t aLength)
void Remove (void *aRemoveStart, uint8_t aRemoveLength)
void RemoveTlv (NetworkDataTlv *aTlv)
otError SendServerDataNotification (uint16_t aRloc16, Coap::ResponseHandler aHandler, void *aContext)
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Static Protected Member Functions inherited from NetworkData
static BorderRouterTlv * FindBorderRouter (PrefixTlv &aPrefix)
static const BorderRouterTlv * FindBorderRouter (const PrefixTlv &aPrefix)
static BorderRouterTlv * FindBorderRouter (PrefixTlv &aPrefix, bool aStable)
static const BorderRouterTlv * FindBorderRouter (const PrefixTlv &aPrefix, bool aStable)
static ContextTlv * FindContext (PrefixTlv &aPrefix)
static const ContextTlv * FindContext (const PrefixTlv &aPrefix)
static HasRouteTlv * FindHasRoute (PrefixTlv &aPrefix)
static const HasRouteTlv * FindHasRoute (const PrefixTlv &aPrefix)
static HasRouteTlv * FindHasRoute (PrefixTlv &aPrefix, bool aStable)
static const HasRouteTlv * FindHasRoute (const PrefixTlv &aPrefix, bool aStable)
static PrefixTlv * FindPrefix (const uint8_t *aPrefix, uint8_t aPrefixLength, uint8_t *aTlvs, uint8_t aTlvsLength)
static const PrefixTlv * FindPrefix (const uint8_t *aPrefix, uint8_t aPrefixLength, const uint8_t *aTlvs, uint8_t aTlvsLength)
static ServiceTlv * FindService (uint32_t aEnterpriseNumber, const uint8_t *aServiceData, uint8_t aServiceDataLength, uint8_t *aTlvs, uint8_t aTlvsLength)
static const ServiceTlv * FindService (uint32_t aEnterpriseNumber, const uint8_t *aServiceData, uint8_t aServiceDataLength, const uint8_t *aTlvs, uint8_t aTlvsLength)
static NetworkDataTlv * FindTlv (NetworkDataTlv *aStart, NetworkDataTlv *aEnd, NetworkDataTlv::Type aType)
static const NetworkDataTlv * FindTlv (const NetworkDataTlv *aStart, const NetworkDataTlv *aEnd, NetworkDataTlv::Type aType)
template<typename TlvType >
static TlvType * FindTlv (NetworkDataTlv *aStart, NetworkDataTlv *aEnd)
template<typename TlvType >
static const TlvType * FindTlv (const NetworkDataTlv *aStart, const NetworkDataTlv *aEnd)
static NetworkDataTlv * FindTlv (NetworkDataTlv *aStart, NetworkDataTlv *aEnd, NetworkDataTlv::Type aType, bool aStable)
static const NetworkDataTlv * FindTlv (const NetworkDataTlv *aStart, const NetworkDataTlv *aEnd, NetworkDataTlv::Type aType, bool aStable)
template<typename TlvType >
static TlvType * FindTlv (NetworkDataTlv *aStart, NetworkDataTlv *aEnd, bool aStable)
template<typename TlvType >
static const TlvType * FindTlv (const NetworkDataTlv *aStart, const NetworkDataTlv *aEnd, bool aStable)
static int8_t PrefixMatch (const uint8_t *a, const uint8_t *b, uint8_t aLength)
static void RemoveTemporaryData (uint8_t *aData, uint8_t &aDataLength)
Detailed Description
This class implements the Thread Network Data maintained by the Leader.
Constructor & Destructor Documentation
LeaderBase()
LeaderBase (Instance & aInstance) explicit
This constructor initializes the object.
Parameters
[in] aInstance A reference to the OpenThread instance.
References LeaderBase::Reset().
Member Function Documentation
Reset()
void Reset (void)
This method reset the Thread Network Data.
References ot::Random::NonCrypto::GetUint8(), LeaderBase::mStableVersion, LeaderBase::mVersion, and OT_CHANGED_THREAD_NETDATA.
Referenced by LeaderBase::LeaderBase().
GetVersion()
uint8_t GetVersion (void) const inline
This method returns the Thread Network Data version.
Returns
The Thread Network Data version.
References LeaderBase::mVersion.
GetStableVersion()
uint8_t GetStableVersion (void) const inline
This method returns the Thread Network Data stable version.
Returns
The Thread Network Data stable version.
References LeaderBase::GetContext(), LeaderBase::IsOnMesh(), LeaderBase::mStableVersion, LeaderBase::RouteLookup(), LeaderBase::SendServerDataNotification(), and LeaderBase::SetNetworkData().
GetContext() [1/2]
otError GetContext (const Ip6::Address & aAddress, Lowpan::Context & aContext) const
This method retrieves the 6LoWPAN Context information based on a given IPv6 address.
Parameters
[in] aAddress A reference to an IPv6 address.
[out] aContext A reference to 6LoWPAN Context information.
Return values
OT_ERROR_NONE Successfully retrieved 6LoWPAN Context information.
OT_ERROR_NOT_FOUND Could not find the 6LoWPAN Context information.
References NetworkData::FindContext(), LeaderBase::FindNextMatchingPrefix(), ContextTlv::GetContextId(), PrefixTlv::GetPrefix(), PrefixTlv::GetPrefixLength(), ContextTlv::IsCompress(), MeshLocalPrefix::kLength, ot::Mle::kMeshLocalPrefixContextId, Context::mCompressFlag, Context::mContextId, Context::mPrefix, Context::mPrefixLength, OT_ERROR_NONE, and OT_ERROR_NOT_FOUND.
Referenced by Lowpan::Compress(), Lowpan::DecompressBaseHeader(), LeaderBase::GetRlocByContextId(), and LeaderBase::GetStableVersion().
GetContext() [2/2]
otError GetContext (uint8_t aContextId, Lowpan::Context & aContext) const
This method retrieves the 6LoWPAN Context information based on a given Context ID.
Parameters
[in] aContextId The Context ID value.
[out] aContext A reference to the 6LoWPAN Context information.
Return values
OT_ERROR_NONE Successfully retrieved 6LoWPAN Context information.
OT_ERROR_NOT_FOUND Could not find the 6LoWPAN Context information.
References ExitNow, NetworkData::FindContext(), ContextTlv::GetContextId(), NetworkDataTlv::GetNext(), PrefixTlv::GetPrefix(), PrefixTlv::GetPrefixLength(), NetworkData::GetTlvsEnd(), NetworkData::GetTlvsStart(), ContextTlv::IsCompress(), MeshLocalPrefix::kLength, ot::Mle::kMeshLocalPrefixContextId, Context::mCompressFlag, Context::mContextId, Context::mPrefix, Context::mPrefixLength, OT_ERROR_NONE, and OT_ERROR_NOT_FOUND.
IsOnMesh()
bool IsOnMesh (const Ip6::Address & aAddress) const
This method indicates whether or not the given IPv6 address is on-mesh.
Parameters
[in] aAddress A reference to an IPv6 address.
Return values
TRUE If aAddress is on-link.
FALSE If aAddress if not on-link.
References ExitNow, NetworkData::FindBorderRouter(), LeaderBase::FindNextMatchingPrefix(), and VerifyOrExit.
Referenced by LeaderBase::GetStableVersion().
RouteLookup()
otError RouteLookup (const Ip6::Address & aSource, const Ip6::Address & aDestination, uint8_t * aPrefixMatch, uint16_t * aRloc16) const
This method performs a route lookup using the Network Data.
Parameters
[in] aSource A reference to the IPv6 source address.
[in] aDestination A reference to the IPv6 destination address.
[out] aPrefixMatch A pointer to the longest prefix match length in bits.
[out] aRloc16 A pointer to the RLOC16 for the selected route.
Return values
OT_ERROR_NONE Successfully found a route.
OT_ERROR_NO_ROUTE No valid route was found.
References LeaderBase::DefaultRouteLookup(), ExitNow, LeaderBase::ExternalRouteLookup(), LeaderBase::FindNextMatchingPrefix(), PrefixTlv::GetDomainId(), OT_ERROR_NO_ROUTE, and OT_ERROR_NONE.
Referenced by LeaderBase::GetStableVersion().
SetNetworkData()
otError SetNetworkData (uint8_t aVersion, uint8_t aStableVersion, bool aStableOnly, const Message & aMessage, uint16_t aMessageOffset)
This method is used by non-Leader devices to set newly received Network Data from the Leader.
Parameters
[in] aVersion The Version value.
[in] aStableVersion The Stable Version value.
[in] aStableOnly TRUE if storing only the stable data, FALSE otherwise.
[in] aMessage A reference to the MLE message.
[in] aMessageOffset The offset in aMessage for the Network Data TLV.
Return values
OT_ERROR_NONE Successfully set the network data.
OT_ERROR_PARSE Network Data TLV in aMessage is not valid.
References Tlv::GetLength(), LeaderBase::mStableVersion, NetworkData::mTlvs, LeaderBase::mVersion, OT_CHANGED_THREAD_NETDATA, OT_ERROR_NONE, OT_ERROR_PARSE, otDumpDebgNetData, Message::Read(), NetworkData::RemoveTemporaryData(), and VerifyOrExit.
Referenced by LeaderBase::GetStableVersion().
SendServerDataNotification()
otError SendServerDataNotification (uint16_t aRloc16)
This method sends a Server Data Notification message to the Leader indicating an invalid RLOC16.
Parameters
[in] aRloc16 The invalid RLOC16 to notify.
Return values
OT_ERROR_NONE Successfully enqueued the notification message.
OT_ERROR_NO_BUFS Insufficient message buffers to generate the notification message.
Referenced by LeaderBase::GetStableVersion().
GetCommissioningData() [1/2]
CommissioningDataTlv* GetCommissioningData (void) inline
This method returns a pointer to the Commissioning Data.
Returns
A pointer to the Commissioning Data or NULL if no Commissioning Data exists.
Referenced by LeaderBase::GetCommissioningDataSubTlv(), and LeaderBase::RemoveCommissioningData().
GetCommissioningData() [2/2]
const CommissioningDataTlv * GetCommissioningData (void) const
This method returns a pointer to the Commissioning Data.
Returns
A pointer to the Commissioning Data or NULL if no Commissioning Data exists.
References NetworkData::GetTlvsEnd(), and NetworkData::GetTlvsStart().
GetCommissioningDataSubTlv() [1/2]
MeshCoP::Tlv* GetCommissioningDataSubTlv (MeshCoP::Tlv::Type aType) inline
This method returns a pointer to the Commissioning Data Sub-TLV.
Parameters
[in] aType The TLV type value.
Returns
A pointer to the Commissioning Data Sub-TLV or NULL if no Sub-TLV exists.
References LeaderBase::GetBackboneRouterPrimary(), LeaderBase::GetRlocByContextId(), LeaderBase::GetServiceId(), LeaderBase::IsJoiningEnabled(), and LeaderBase::SetCommissioningData().
Referenced by LeaderBase::IsJoiningEnabled().
GetCommissioningDataSubTlv() [2/2]
const MeshCoP::Tlv * GetCommissioningDataSubTlv (MeshCoP::Tlv::Type aType) const
This method returns a pointer to the Commissioning Data Sub-TLV.
Parameters
[in] aType The TLV type value.
Returns
A pointer to the Commissioning Data Sub-TLV or NULL if no Sub-TLV exists.
References Tlv::FindTlv(), LeaderBase::GetCommissioningData(), NetworkDataTlv::GetLength(), NetworkDataTlv::GetValue(), OT_NOOP, and VerifyOrExit.
IsJoiningEnabled()
bool IsJoiningEnabled (void) const
This method indicates whether or not the Commissioning Data TLV indicates Joining is enabled.
Joining is enabled if a Border Agent Locator TLV exist and the Steering Data TLV is non-zero.
Returns
TRUE if the Commissioning Data TLV says Joining is enabled, FALSE otherwise.
References ExitNow, LeaderBase::GetCommissioningDataSubTlv(), Tlv::GetLength(), Tlv::GetValue(), Tlv::kBorderAgentLocator, Tlv::kSteeringData, OT_NOOP, and VerifyOrExit.
Referenced by LeaderBase::GetCommissioningDataSubTlv().
SetCommissioningData()
otError SetCommissioningData (const uint8_t * aValue, uint8_t aValueLength)
This method adds Commissioning Data to the Thread Network Data.
Parameters
[in] aValue A pointer to the Commissioning Data value.
[in] aValueLength The length of aValue.
Return values
OT_ERROR_NONE Successfully added the Commissioning Data.
OT_ERROR_NO_BUFS Insufficient space to add the Commissioning Data.
References NetworkData::AppendTlv(), NetworkDataTlv::GetValue(), CommissioningDataTlv::Init(), NetworkData::kMaxSize, LeaderBase::mVersion, OT_CHANGED_THREAD_NETDATA, OT_ERROR_NO_BUFS, OT_ERROR_NONE, LeaderBase::RemoveCommissioningData(), NetworkDataTlv::SetLength(), and VerifyOrExit.
Referenced by LeaderBase::GetCommissioningDataSubTlv().
GetRlocByContextId()
otError GetRlocByContextId (uint8_t aContextId, uint16_t & aRloc16) const
This method gets the Rloc of Dhcp Agent of specified contextId.
Parameters
[in] aContextId A pointer to the Commissioning Data value.
[out] aRloc16 The reference of which for output the Rloc16.
Return values
OT_ERROR_NONE Successfully get the Rloc of Dhcp Agent.
OT_ERROR_NOT_FOUND The specified aContextId could not be found.
References ExitNow, LeaderBase::GetContext(), NetworkData::GetNextOnMeshPrefix(), ot::NetworkData::kIteratorInit, otIp6Prefix::mLength, otBorderRouterConfig::mPrefix, Context::mPrefix, otIp6Prefix::mPrefix, otBorderRouterConfig::mRloc16, OT_ERROR_NONE, OT_ERROR_NOT_FOUND, and otIp6PrefixMatch().
Referenced by LeaderBase::GetCommissioningDataSubTlv().
GetServiceId()
otError GetServiceId (uint32_t aEnterpriseNumber, const uint8_t * aServiceData, uint8_t aServiceDataLength, bool aServerStable, uint8_t & aServiceId) const
This method gets the Service ID for the specified service.
Parameters
[in] aEnterpriseNumber Enterprise Number (IANA-assigned) for Service TLV
[in] aServiceData A pointer to the Service Data
[in] aServiceDataLength The length of aServiceData in bytes.
[in] aServerStable The Stable flag value for Server TLV
[out] aServiceId A reference where to put the Service ID.
Return values
OT_ERROR_NONE Successfully got the Service ID.
OT_ERROR_NOT_FOUND The specified service was not found.
References ExitNow, NetworkData::GetNextService(), ot::NetworkData::kIteratorInit, otServiceConfig::mEnterpriseNumber, otServiceConfig::mServerConfig, otServiceConfig::mServiceData, otServiceConfig::mServiceDataLength, otServiceConfig::mServiceId, otServerConfig::mStable, OT_ERROR_NONE, and OT_ERROR_NOT_FOUND.
Referenced by LeaderBase::GetCommissioningDataSubTlv().
GetBackboneRouterPrimary()
otError GetBackboneRouterPrimary (BackboneRouter::BackboneRouterConfig & aConfig) const
This method gets the Primary Backbone Router (PBBR) in the Thread Network.
Parameters
[out] aConfig The Primary Backbone Router configuration.
Return values
OT_ERROR_NONE Successfully got the Primary Backbone Router configuration.
OT_ERROR_NOT_FOUND No Backbone Router Service in the Thread Network.
References NetworkData::FindService(), BackboneRouterServerData::GetMlrTimeout(), NetworkDataTlv::GetNext(), BackboneRouterServerData::GetReregistrationDelay(), BackboneRouterServerData::GetSequenceNumber(), ServerTlv::GetServer16(), ServerTlv::GetServerData(), ServiceTlv::GetSubTlvs(), ServiceTlv::kServiceDataBackboneRouter, ot::Mac::kShortAddrInvalid, ServiceTlv::kThreadEnterpriseNumber, otBackboneRouterConfig::mMlrTimeout, otBackboneRouterConfig::mReregistrationDelay, otBackboneRouterConfig::mSequenceNumber, otBackboneRouterConfig::mServer16, OT_ERROR_NONE, OT_ERROR_NOT_FOUND, OT_NOOP, Mle::Rloc16FromRouterId(), and VerifyOrExit.
Referenced by LeaderBase::GetCommissioningDataSubTlv().
FindNextMatchingPrefix()
const PrefixTlv * FindNextMatchingPrefix (const Ip6::Address & aAddress, const PrefixTlv * aPrevTlv) const private
References ExitNow, NetworkDataTlv::GetNext(), PrefixTlv::GetPrefix(), PrefixTlv::GetPrefixLength(), NetworkData::GetTlvsEnd(), NetworkData::GetTlvsStart(), otIp6Address::OT_TOOL_PACKED_FIELD::m8, otIp6Address::mFields, and NetworkData::PrefixMatch().
Referenced by LeaderBase::GetContext(), LeaderBase::IsOnMesh(), and LeaderBase::RouteLookup().
RemoveCommissioningData()
otError RemoveCommissioningData (void) private
References LeaderBase::GetCommissioningData(), OT_ERROR_NONE, OT_ERROR_NOT_FOUND, NetworkData::RemoveTlv(), and VerifyOrExit.
Referenced by LeaderBase::SetCommissioningData().
ExternalRouteLookup()
otError ExternalRouteLookup (uint8_t aDomainId, const Ip6::Address & aDestination, uint8_t * aPrefixMatch, uint16_t * aRloc16) const private
References PrefixTlv::GetDomainId(), HasRouteTlv::GetFirstEntry(), HasRouteTlv::GetLastEntry(), NetworkDataTlv::GetNext(), HasRouteEntry::GetNext(), HasRouteEntry::GetPreference(), PrefixTlv::GetPrefix(), PrefixTlv::GetPrefixLength(), HasRouteEntry::GetRloc(), PrefixTlv::GetSubTlvs(), NetworkData::GetTlvsEnd(), NetworkData::GetTlvsStart(), otIp6Address::OT_TOOL_PACKED_FIELD::m8, otIp6Address::mFields, OT_ERROR_NO_ROUTE, OT_ERROR_NONE, and NetworkData::PrefixMatch().
Referenced by LeaderBase::RouteLookup().
DefaultRouteLookup()
otError DefaultRouteLookup (const PrefixTlv & aPrefix, uint16_t * aRloc16) const private
References BorderRouterTlv::GetFirstEntry(), BorderRouterTlv::GetLastEntry(), NetworkDataTlv::GetNext(), BorderRouterEntry::GetNext(), BorderRouterEntry::GetPreference(), BorderRouterEntry::GetRloc(), PrefixTlv::GetSubTlvs(), OT_ERROR_NO_ROUTE, and OT_ERROR_NONE.
Referenced by LeaderBase::RouteLookup().
Field Documentation
mStableVersion
uint8_t mStableVersion protected
Referenced by LeaderBase::GetStableVersion(), LeaderBase::Reset(), and LeaderBase::SetNetworkData().
mVersion
uint8_t mVersion protected
Referenced by LeaderBase::GetVersion(), LeaderBase::Reset(), LeaderBase::SetCommissioningData(), and LeaderBase::SetNetworkData().
The documentation for this class was generated from the following files:
network_data_leader.hpp
network_data_leader.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale