OpenThread: ThreadTlv Class Reference
ThreadTlv Class Reference
#include <thread_tlvs.hpp>
Public Types
enum Type {
kTarget = 0, kExtMacAddress = 1, kRloc16 = 2, kMeshLocalEid = 3,
kStatus = 4, kLastTransactionTime = 6, kRouterMask = 7, kNDOption = 8,
kNDData = 9, kThreadNetworkData = 10
}
Public Types inherited from Tlv
enum { kBaseTlvMaxLength = OT_NETWORK_BASE_TLV_MAX_LENGTH }
Public Member Functions
Type GetType (void) const
void SetType (Type aType)
Public Member Functions inherited from Tlv
otError AppendTo (Message &aMessage) const
uint8_t GetLength (void) const
Tlv * GetNext (void)
const Tlv * GetNext (void) const
uint32_t GetSize (void) const
uint8_t GetType (void) const
uint8_t * GetValue (void)
const uint8_t * GetValue (void) const
bool IsExtended (void) const
void SetLength (uint8_t aLength)
void SetType (uint8_t aType)
Static Public Member Functions
static otError GetTlv (const Message &aMessage, Type aType, uint16_t aMaxLength, Tlv &aTlv)
Static Public Member Functions inherited from Tlv
static otError AppendTlv (Message &aMessage, uint8_t aType, const uint8_t *aValue, uint8_t aLength)
static otError AppendUint16Tlv (Message &aMessage, uint8_t aType, uint16_t aValue)
static otError AppendUint32Tlv (Message &aMessage, uint8_t aType, uint32_t aValue)
static otError AppendUint8Tlv (Message &aMessage, uint8_t aType, uint8_t aValue)
static otError Get (const Message &aMessage, uint8_t aType, uint16_t aMaxSize, Tlv &aTlv)
static otError GetOffset (const Message &aMessage, uint8_t aType, uint16_t &aOffset)
static otError GetValueOffset (const Message &aMessage, uint8_t aType, uint16_t &aOffset, uint16_t &aLength)
static otError ReadTlv (const Message &aMessage, uint8_t aType, void *aValue, uint8_t aLength)
static otError ReadUint16Tlv (const Message &aMessage, uint8_t aType, uint16_t &aValue)
static otError ReadUint32Tlv (const Message &aMessage, uint8_t aType, uint32_t &aValue)
static otError ReadUint8Tlv (const Message &aMessage, uint8_t aType, uint8_t &aValue)
Additional Inherited Members
Protected Types inherited from Tlv
enum { kExtendedLength = 255 }
Detailed Description
This class implements Network Layer TLV generation and parsing.
Member Enumeration Documentation
Type
enum Type
Network Layer TLV Types.
Enumerator
kTarget
Target EID TLV.
kExtMacAddress
Extended MAC Address TLV.
kRloc16
RLOC16 TLV.
kMeshLocalEid
ML-EID TLV.
kStatus
Status TLV.
kLastTransactionTime
Time Since Last Transaction TLV.
kRouterMask
Router Mask TLV.
kNDOption
ND Option TLV.
kNDData
ND Data TLV.
kThreadNetworkData
Thread Network Data TLV.
Member Function Documentation
GetType()
Type GetType (void) const inline
This method returns the Type value.
Returns
The Type value.
References Tlv::GetType().
SetType()
void SetType (Type aType) inline
This method sets the Type value.
Parameters
[in] aType The Type value.
References Tlv::SetType().
Referenced by ThreadRouterMaskTlv::Init(), ThreadNetworkDataTlv::Init(), and NetworkData::SendServerDataNotification().
GetTlv()
static otError GetTlv (const Message & aMessage, Type aType, uint16_t aMaxLength, Tlv & aTlv) inline static
This static method reads the requested TLV out of aMessage.
Parameters
[in] aMessage A reference to the message.
[in] aType The Type value to search for.
[in] aMaxLength Maximum number of bytes to read.
[out] aTlv A reference to the TLV that will be copied to.
Return values
OT_ERROR_NONE Successfully copied the TLV.
OT_ERROR_NOT_FOUND Could not find the TLV with Type aType.
References Tlv::Get(), and ot::OT_TOOL_PACKED_END.
The documentation for this class was generated from the following file:
thread_tlvs.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale