OpenThread: KeyManager Class Reference
KeyManager Class Reference
Core-security
#include <key_manager.hpp>
Public Types
enum { kNonceSize = 13 }
Public Member Functions
uint32_t GetCurrentKeySequence (void) const
const uint8_t * GetCurrentMacKey (void) const
const uint8_t * GetCurrentMleKey (void) const
const Kek & GetKek (void) const
uint32_t GetKekFrameCounter (void) const
uint32_t GetKeyRotation (void) const
uint32_t GetKeySwitchGuardTime (void) const
uint32_t GetMacFrameCounter (void) const
const MasterKey & GetMasterKey (void) const
uint32_t GetMleFrameCounter (void) const
uint8_t GetSecurityPolicyFlags (void) const
const uint8_t * GetTemporaryMacKey (uint32_t aKeySequence)
const uint8_t * GetTemporaryMleKey (uint32_t aKeySequence)
void IncrementKekFrameCounter (void)
void IncrementMacFrameCounter (void)
void IncrementMleFrameCounter (void)
bool IsExternalCommissionerAllowed (void) const
bool IsNativeCommissioningAllowed (void) const
bool IsObtainMasterKeyEnabled (void) const
bool IsRouterEnabled (void) const
bool IsThreadBeaconEnabled (void) const
KeyManager (Instance &aInstance)
void SetCurrentKeySequence (uint32_t aKeySequence)
void SetKek (const Kek &aKek)
void SetKek (const uint8_t *aKek)
otError SetKeyRotation (uint32_t aKeyRotation)
void SetKeySwitchGuardTime (uint32_t aKeySwitchGuardTime)
void SetMacFrameCounter (uint32_t aMacFrameCounter)
otError SetMasterKey (const MasterKey &aKey)
void SetMleFrameCounter (uint32_t aMleFrameCounter)
void SetSecurityPolicyFlags (uint8_t aSecurityPolicyFlags)
void SetStoredMacFrameCounter (uint32_t aStoredMacFrameCounter)
void SetStoredMleFrameCounter (uint32_t aStoredMleFrameCounter)
void Start (void)
void Stop (void)
Public Member Functions inherited from InstanceLocator
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Static Public Member Functions
static void GenerateNonce (const Mac::ExtAddress &aAddress, uint32_t aFrameCounter, uint8_t aSecurityLevel, uint8_t *aNonce)
Private Types
enum {
kMinKeyRotationTime = 1, kDefaultKeyRotationTime = 672, kDefaultKeySwitchGuardTime = 624, kMacKeyOffset = 16,
kOneHourIntervalInMsec = 3600u * 1000u
}
Private Member Functions
void ComputeKey (uint32_t aKeySequence, uint8_t *aKey)
void HandleKeyRotationTimer (void)
void StartKeyRotationTimer (void)
Static Private Member Functions
static void HandleKeyRotationTimer (Timer &aTimer)
Private Attributes
uint32_t mHoursSinceKeyRotation
bool mIsPskcSet: 1
Kek mKek
uint32_t mKekFrameCounter
uint8_t mKey [Crypto::HmacSha256::kHashSize]
uint32_t mKeyRotationTime
TimerMilli mKeyRotationTimer
uint32_t mKeySequence
bool mKeySwitchGuardEnabled
uint32_t mKeySwitchGuardTime
uint32_t mMacFrameCounter
MasterKey mMasterKey
uint32_t mMleFrameCounter
uint8_t mSecurityPolicyFlags
uint32_t mStoredMacFrameCounter
uint32_t mStoredMleFrameCounter
uint8_t mTemporaryKey [Crypto::HmacSha256::kHashSize]
Static Private Attributes
static const otMasterKey kDefaultMasterKey
static const uint8_t kThreadString []
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Detailed Description
This class defines Thread Key Manager.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
kNonceSize
Size of IEEE 802.15.4 Nonce (bytes).
anonymous enum
anonymous enum private
Enumerator
kMinKeyRotationTime
kDefaultKeyRotationTime
kDefaultKeySwitchGuardTime
kMacKeyOffset
kOneHourIntervalInMsec
Constructor & Destructor Documentation
KeyManager()
KeyManager (Instance & aInstance) explicit
This constructor initializes the object.
Parameters
[in] aInstance A reference to the OpenThread instance.
References KeyManager::ComputeKey(), KeyManager::kDefaultMasterKey, KeyManager::mKey, KeyManager::mKeySequence, and KeyManager::mMasterKey.
Member Function Documentation
Start()
void Start (void)
This method starts KeyManager rotation timer and sets guard timer to initial value.
References KeyManager::mKeySwitchGuardEnabled, and KeyManager::StartKeyRotationTimer().
Stop()
void Stop (void)
This method stops KeyManager timers.
References KeyManager::mIsPskcSet, KeyManager::mKeyRotationTimer, OT_CHANGED_PSKC, and TimerMilli::Stop().
GetMasterKey()
const MasterKey& GetMasterKey (void) const inline
This method returns the Thread Master Key.
Returns
The Thread Master Key.
SetMasterKey()
otError SetMasterKey (const MasterKey & aKey)
This method sets the Thread Master Key.
Parameters
[in] aKey A Thread Master Key.
Return values
OT_ERROR_NONE Successfully set the Thread Master Key.
OT_ERROR_INVALID_ARGS The aKeyLength value was invalid.
References KeyManager::ComputeKey(), InstanceLocator::GetInstance(), Neighbor::kInStateAnyExceptInvalid, KeyManager::mKey, KeyManager::mKeySequence, KeyManager::mMasterKey, OT_CHANGED_MASTER_KEY, OT_CHANGED_THREAD_KEY_SEQUENCE_COUNTER, OT_ERROR_NONE, Neighbor::SetKeySequence(), Neighbor::SetLinkFrameCounter(), Neighbor::SetMleFrameCounter(), and SuccessOrExit.
GetCurrentKeySequence()
uint32_t GetCurrentKeySequence (void) const inline
This method returns the current key sequence value.
Returns
The current key sequence value.
Referenced by Mac::ProcessReceiveSecurity(), and Mac::ProcessTransmitSecurity().
SetCurrentKeySequence()
void SetCurrentKeySequence (uint32_t aKeySequence)
This method sets the current key sequence value.
Parameters
[in] aKeySequence The key sequence value.
References KeyManager::ComputeKey(), Timer::IsRunning(), KeyManager::mHoursSinceKeyRotation, KeyManager::mKey, KeyManager::mKeyRotationTimer, KeyManager::mKeySequence, KeyManager::mKeySwitchGuardEnabled, KeyManager::mKeySwitchGuardTime, KeyManager::mMacFrameCounter, KeyManager::mMleFrameCounter, OT_CHANGED_THREAD_KEY_SEQUENCE_COUNTER, OT_NOOP, KeyManager::StartKeyRotationTimer(), and VerifyOrExit.
Referenced by KeyManager::HandleKeyRotationTimer(), and Mac::ProcessReceiveSecurity().
GetCurrentMacKey()
const uint8_t* GetCurrentMacKey (void) const inline
This method returns a pointer to the current MAC key.
Returns
A pointer to the current MAC key.
Referenced by Mac::ProcessReceiveSecurity(), and Mac::ProcessTransmitSecurity().
GetCurrentMleKey()
const uint8_t* GetCurrentMleKey (void) const inline
This method returns a pointer to the current MLE key.
Returns
A pointer to the current MLE key.
GetTemporaryMacKey()
const uint8_t * GetTemporaryMacKey (uint32_t aKeySequence)
This method returns a pointer to a temporary MAC key computed from the given key sequence.
Parameters
[in] aKeySequence The key sequence value.
Returns
A pointer to the temporary MAC key.
References KeyManager::ComputeKey(), KeyManager::kMacKeyOffset, and KeyManager::mTemporaryKey.
Referenced by Mac::ProcessReceiveSecurity().
GetTemporaryMleKey()
const uint8_t * GetTemporaryMleKey (uint32_t aKeySequence)
This method returns a pointer to a temporary MLE key computed from the given key sequence.
Parameters
[in] aKeySequence The key sequence value.
Returns
A pointer to the temporary MLE key.
References KeyManager::ComputeKey(), and KeyManager::mTemporaryKey.
GetMacFrameCounter()
uint32_t GetMacFrameCounter (void) const inline
This method returns the current MAC Frame Counter value.
Returns
The current MAC Frame Counter value.
Referenced by Mac::ProcessTransmitSecurity().
SetMacFrameCounter()
void SetMacFrameCounter (uint32_t aMacFrameCounter) inline
This method sets the current MAC Frame Counter value.
Parameters
[in] aMacFrameCounter The MAC Frame Counter value.
SetStoredMacFrameCounter()
void SetStoredMacFrameCounter (uint32_t aStoredMacFrameCounter) inline
This method sets the MAC Frame Counter value which is stored in non-volatile memory.
Parameters
[in] aStoredMacFrameCounter The stored MAC Frame Counter value.
IncrementMacFrameCounter()
void IncrementMacFrameCounter (void)
This method increments the current MAC Frame Counter value.
References KeyManager::mMacFrameCounter, and KeyManager::mStoredMacFrameCounter.
Referenced by Mac::ProcessTransmitSecurity().
GetMleFrameCounter()
uint32_t GetMleFrameCounter (void) const inline
This method returns the current MLE Frame Counter value.
Returns
The current MLE Frame Counter value.
SetMleFrameCounter()
void SetMleFrameCounter (uint32_t aMleFrameCounter) inline
This method sets the current MLE Frame Counter value.
Parameters
[in] aMleFrameCounter The MLE Frame Counter value.
SetStoredMleFrameCounter()
void SetStoredMleFrameCounter (uint32_t aStoredMleFrameCounter) inline
This method sets the MLE Frame Counter value which is stored in non-volatile memory.
Parameters
[in] aStoredMleFrameCounter The stored MLE Frame Counter value.
IncrementMleFrameCounter()
void IncrementMleFrameCounter (void)
This method increments the current MLE Frame Counter value.
References KeyManager::mMleFrameCounter, and KeyManager::mStoredMleFrameCounter.
GetKek()
const Kek& GetKek (void) const inline
This method returns the KEK.
Returns
A pointer to the KEK.
Referenced by Mac::ProcessReceiveSecurity(), and Mac::ProcessTransmitSecurity().
SetKek() [1/2]
void SetKek (const Kek & aKek)
This method sets the KEK.
Parameters
[in] aKek A KEK.
References KeyManager::mKek, and KeyManager::mKekFrameCounter.
SetKek() [2/2]
void SetKek (const uint8_t * aKek)
This method sets the KEK.
Parameters
[in] aKek A pointer to the KEK.
References Kek::m8, KeyManager::mKek, and KeyManager::mKekFrameCounter.
GetKekFrameCounter()
uint32_t GetKekFrameCounter (void) const inline
This method returns the current KEK Frame Counter value.
Returns
The current KEK Frame Counter value.
Referenced by Mac::ProcessTransmitSecurity().
IncrementKekFrameCounter()
void IncrementKekFrameCounter (void) inline
This method increments the current KEK Frame Counter value.
Referenced by Mac::ProcessTransmitSecurity().
GetKeyRotation()
uint32_t GetKeyRotation (void) const inline
This method returns the KeyRotation time.
The KeyRotation time is the time interval after witch security key will be automatically rotated.
Returns
The KeyRotation value in hours.
SetKeyRotation()
otError SetKeyRotation (uint32_t aKeyRotation)
This method sets the KeyRotation time.
The KeyRotation time is the time interval after witch security key will be automatically rotated. Its value shall be larger than or equal to kMinKeyRotationTime.
Parameters
[in] aKeyRotation The KeyRotation value in hours.
Return values
OT_ERROR_NONE KeyRotation time updated.
OT_ERROR_INVALID_ARGS aKeyRotation is out of range.
References KeyManager::kMinKeyRotationTime, KeyManager::mKeyRotationTime, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, and VerifyOrExit.
GetKeySwitchGuardTime()
uint32_t GetKeySwitchGuardTime (void) const inline
This method returns the KeySwitchGuardTime.
The KeySwitchGuardTime is the time interval during which key rotation procedure is prevented.
Returns
The KeySwitchGuardTime value in hours.
SetKeySwitchGuardTime()
void SetKeySwitchGuardTime (uint32_t aKeySwitchGuardTime) inline
This method sets the KeySwitchGuardTime.
The KeySwitchGuardTime is the time interval during which key rotation procedure is prevented.
Parameters
[in] aKeySwitchGuardTime The KeySwitchGuardTime value in hours.
GetSecurityPolicyFlags()
uint8_t GetSecurityPolicyFlags (void) const inline
This method returns the Security Policy Flags.
The Security Policy Flags specifies network administrator preferences for which security-related operations are allowed or disallowed.
Returns
The SecurityPolicy Flags.
SetSecurityPolicyFlags()
void SetSecurityPolicyFlags (uint8_t aSecurityPolicyFlags)
This method sets the Security Policy Flags.
The Security Policy Flags specifies network administrator preferences for which security-related operations are allowed or disallowed.
Parameters
[in] aSecurityPolicyFlags The Security Policy Flags.
References KeyManager::mSecurityPolicyFlags, and OT_CHANGED_SECURITY_POLICY.
IsObtainMasterKeyEnabled()
bool IsObtainMasterKeyEnabled (void) const inline
This method indicates whether or not obtaining Master key for out-of-band is enabled.
Return values
TRUE If obtaining Master key for out-of-band is enabled.
FALSE If obtaining Master key for out-of-band is not enabled.
References OT_SECURITY_POLICY_OBTAIN_MASTER_KEY.
IsNativeCommissioningAllowed()
bool IsNativeCommissioningAllowed (void) const inline
This method indicates whether or not Native Commissioning using PSKc is allowed.
Return values
TRUE If Native Commissioning using PSKc is allowed.
FALSE If Native Commissioning using PSKc is not allowed.
References OT_SECURITY_POLICY_NATIVE_COMMISSIONING.
IsRouterEnabled()
bool IsRouterEnabled (void) const inline
This method indicates whether or not Thread 1.1 Routers are enabled.
Return values
TRUE If Thread 1.1 Routers are enabled.
FALSE If Thread 1.1 Routers are not enabled.
References OT_SECURITY_POLICY_ROUTERS.
IsExternalCommissionerAllowed()
bool IsExternalCommissionerAllowed (void) const inline
This method indicates whether or not external Commissioner authentication is allowed using PSKc.
Return values
TRUE If the commissioning sessions by an external Commissioner based on the PSKc are allowed to be established and that changes to the Commissioner Dataset by on-mesh nodes are allowed.
FALSE If the commissioning sessions by an external Commissioner based on the PSKc are not allowed to be established and that changes to the Commissioner Dataset by on-mesh nodes are not allowed.
References OT_SECURITY_POLICY_EXTERNAL_COMMISSIONER.
IsThreadBeaconEnabled()
bool IsThreadBeaconEnabled (void) const inline
This method indicates whether or not Thread Beacons are enabled.
Return values
TRUE If Thread Beacons are enabled.
FALSE If Thread Beacons are not enabled.
References OT_SECURITY_POLICY_BEACONS.
GenerateNonce()
void GenerateNonce (const Mac::ExtAddress & aAddress, uint32_t aFrameCounter, uint8_t aSecurityLevel, uint8_t * aNonce) static
This static method generates IEEE 802.15.4 nonce byte sequence.
Parameters
[in] aAddress An extended address.
[in] aFrameCounter A frame counter.
[in] aSecurityLevel A security level.
[out] aNonce A buffer (with kNonceSize bytes) to place the generated nonce.
References otExtAddress::m8, and ot::Encoding::BigEndian::WriteUint32().
Referenced by Mle::HandleUdpReceive(), Mac::ProcessReceiveSecurity(), TxFrame::ProcessTransmitAesCcm(), and Mle::SendMessage().
ComputeKey()
void ComputeKey (uint32_t aKeySequence, uint8_t * aKey) private
References HmacSha256::Finish(), KeyManager::kThreadString, otMasterKey::m8, KeyManager::mMasterKey, HmacSha256::Start(), HmacSha256::Update(), and ot::Encoding::BigEndian::WriteUint32().
Referenced by KeyManager::GetTemporaryMacKey(), KeyManager::GetTemporaryMleKey(), KeyManager::KeyManager(), KeyManager::SetCurrentKeySequence(), and KeyManager::SetMasterKey().
StartKeyRotationTimer()
void StartKeyRotationTimer (void) private
References KeyManager::kOneHourIntervalInMsec, KeyManager::mHoursSinceKeyRotation, KeyManager::mKeyRotationTimer, and TimerMilli::Start().
Referenced by KeyManager::SetCurrentKeySequence(), and KeyManager::Start().
HandleKeyRotationTimer() [1/2]
void HandleKeyRotationTimer (Timer & aTimer) static private
References OwnerLocator::GetOwner(), and KeyManager::HandleKeyRotationTimer().
HandleKeyRotationTimer() [2/2]
void HandleKeyRotationTimer (void) private
References Timer::GetFireTime(), KeyManager::kOneHourIntervalInMsec, KeyManager::mHoursSinceKeyRotation, KeyManager::mKeyRotationTime, KeyManager::mKeyRotationTimer, KeyManager::mKeySequence, KeyManager::SetCurrentKeySequence(), and TimerMilli::StartAt().
Referenced by KeyManager::HandleKeyRotationTimer().
Field Documentation
kThreadString
const uint8_t kThreadString static private
Initial value:
= {
    'T', 'h', 'r', 'e', 'a', 'd',
}
Referenced by KeyManager::ComputeKey().
kDefaultMasterKey
const otMasterKey kDefaultMasterKey static private
Initial value:
= {{
    0x00,
    0x11,
    0x22,
    0x33,
    0x44,
    0x55,
    0x66,
    0x77,
    0x88,
    0x99,
    0xaa,
    0xbb,
    0xcc,
    0xdd,
    0xee,
    0xff,
}}
Referenced by KeyManager::KeyManager().
mMasterKey
MasterKey mMasterKey private
Referenced by KeyManager::ComputeKey(), KeyManager::KeyManager(), and KeyManager::SetMasterKey().
mKeySequence
uint32_t mKeySequence private
Referenced by KeyManager::HandleKeyRotationTimer(), KeyManager::KeyManager(), KeyManager::SetCurrentKeySequence(), and KeyManager::SetMasterKey().
mKey
uint8_t mKey[Crypto::HmacSha256::kHashSize] private
Referenced by KeyManager::KeyManager(), KeyManager::SetCurrentKeySequence(), and KeyManager::SetMasterKey().
mTemporaryKey
uint8_t mTemporaryKey[Crypto::HmacSha256::kHashSize] private
Referenced by KeyManager::GetTemporaryMacKey(), and KeyManager::GetTemporaryMleKey().
mMacFrameCounter
uint32_t mMacFrameCounter private
Referenced by KeyManager::IncrementMacFrameCounter(), and KeyManager::SetCurrentKeySequence().
mMleFrameCounter
uint32_t mMleFrameCounter private
Referenced by KeyManager::IncrementMleFrameCounter(), and KeyManager::SetCurrentKeySequence().
mStoredMacFrameCounter
uint32_t mStoredMacFrameCounter private
Referenced by KeyManager::IncrementMacFrameCounter().
mStoredMleFrameCounter
uint32_t mStoredMleFrameCounter private
Referenced by KeyManager::IncrementMleFrameCounter().
mHoursSinceKeyRotation
uint32_t mHoursSinceKeyRotation private
Referenced by KeyManager::HandleKeyRotationTimer(), KeyManager::SetCurrentKeySequence(), and KeyManager::StartKeyRotationTimer().
mKeyRotationTime
uint32_t mKeyRotationTime private
Referenced by KeyManager::HandleKeyRotationTimer(), and KeyManager::SetKeyRotation().
mKeySwitchGuardTime
uint32_t mKeySwitchGuardTime private
Referenced by KeyManager::SetCurrentKeySequence().
mKeySwitchGuardEnabled
bool mKeySwitchGuardEnabled private
Referenced by KeyManager::SetCurrentKeySequence(), and KeyManager::Start().
mKeyRotationTimer
TimerMilli mKeyRotationTimer private
Referenced by KeyManager::HandleKeyRotationTimer(), KeyManager::SetCurrentKeySequence(), KeyManager::StartKeyRotationTimer(), and KeyManager::Stop().
mKek
Kek mKek private
Referenced by KeyManager::SetKek().
mKekFrameCounter
uint32_t mKekFrameCounter private
Referenced by KeyManager::SetKek().
mSecurityPolicyFlags
uint8_t mSecurityPolicyFlags private
Referenced by KeyManager::SetSecurityPolicyFlags().
mIsPskcSet
bool mIsPskcSet private
Referenced by KeyManager::Stop().
The documentation for this class was generated from the following files:
key_manager.hpp
key_manager.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale