OpenThread: Flash::RecordHeader Class Reference
Flash::RecordHeader Class Reference
Public Member Functions
uint16_t GetKey (void) const
uint16_t GetLength (void) const
uint16_t GetSize (void) const
void Init (uint16_t aKey, bool aFirst)
bool IsAddBeginSet (void) const
bool IsAddCompleteSet (void) const
bool IsDeleted (void) const
bool IsFirst (void) const
bool IsValid (void) const
void SetAddBeginFlag (void)
void SetAddCompleteFlag (void)
void SetDeleted (void)
void SetFirst (void)
void SetKey (uint16_t aKey)
void SetLength (uint16_t aLength)
Private Types
enum {
kFlagsInit = 0xffff, kFlagAddBegin = 1 << 0, kFlagAddComplete = 1 << 1, kFlagDelete = 1 << 2,
kFlagFirst = 1 << 3
}
Private Attributes
uint16_t mFlags
uint16_t mKey
uint16_t mLength
uint16_t mReserved
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
kFlagsInit
Flags initialize to all-ones.
kFlagAddBegin
0 indicates record write has started, 1 otherwise.
kFlagAddComplete
0 indicates record write has completed, 1 otherwise.
kFlagDelete
0 indicates record was deleted, 1 otherwise.
kFlagFirst
0 indicates first record for key, 1 otherwise.
Member Function Documentation
Init()
void Init (uint16_t aKey, bool aFirst) inline
References Flash::RecordHeader::kFlagAddBegin, Flash::RecordHeader::kFlagFirst, Flash::RecordHeader::kFlagsInit, Flash::RecordHeader::mFlags, Flash::RecordHeader::mKey, Flash::RecordHeader::mLength, and Flash::RecordHeader::mReserved.
Referenced by Flash::Add().
GetKey()
uint16_t GetKey (void) const inline
References Flash::RecordHeader::mKey.
Referenced by Flash::Delete(), Flash::DoesValidRecordExist(), Flash::Get(), and Flash::Swap().
SetKey()
void SetKey (uint16_t aKey) inline
References Flash::RecordHeader::mKey.
GetLength()
uint16_t GetLength (void) const inline
References Flash::RecordHeader::mLength.
Referenced by Flash::Get().
SetLength()
void SetLength (uint16_t aLength) inline
References Flash::RecordHeader::mLength.
Referenced by Flash::Record::SetData().
GetSize()
uint16_t GetSize (void) const inline
References Flash::RecordHeader::mLength.
Referenced by Flash::Add(), Flash::Delete(), Flash::DoesValidRecordExist(), Flash::Get(), Flash::Init(), and Flash::Swap().
IsValid()
bool IsValid (void) const inline
References Flash::RecordHeader::kFlagAddComplete, Flash::RecordHeader::kFlagDelete, and Flash::RecordHeader::mFlags.
Referenced by Flash::Delete(), Flash::DoesValidRecordExist(), Flash::Get(), and Flash::Swap().
IsAddBeginSet()
bool IsAddBeginSet (void) const inline
References Flash::RecordHeader::kFlagAddBegin, and Flash::RecordHeader::mFlags.
Referenced by Flash::Init(), and Flash::Swap().
SetAddBeginFlag()
void SetAddBeginFlag (void) inline
References Flash::RecordHeader::kFlagAddBegin, and Flash::RecordHeader::mFlags.
IsAddCompleteSet()
bool IsAddCompleteSet (void) const inline
References Flash::RecordHeader::kFlagAddComplete, and Flash::RecordHeader::mFlags.
Referenced by Flash::Init().
SetAddCompleteFlag()
void SetAddCompleteFlag (void) inline
References Flash::RecordHeader::kFlagAddComplete, and Flash::RecordHeader::mFlags.
Referenced by Flash::Add().
IsDeleted()
bool IsDeleted (void) const inline
References Flash::RecordHeader::kFlagDelete, and Flash::RecordHeader::mFlags.
SetDeleted()
void SetDeleted (void) inline
References Flash::RecordHeader::kFlagDelete, and Flash::RecordHeader::mFlags.
Referenced by Flash::Delete().
IsFirst()
bool IsFirst (void) const inline
References Flash::RecordHeader::kFlagFirst, and Flash::RecordHeader::mFlags.
Referenced by Flash::Delete(), Flash::DoesValidRecordExist(), and Flash::Get().
SetFirst()
void SetFirst (void) inline
References Flash::RecordHeader::kFlagFirst, and Flash::RecordHeader::mFlags.
Referenced by Flash::Delete().
Field Documentation
mKey
uint16_t mKey private
Referenced by Flash::RecordHeader::GetKey(), Flash::RecordHeader::Init(), and Flash::RecordHeader::SetKey().
mFlags
uint16_t mFlags private
Referenced by Flash::RecordHeader::Init(), Flash::RecordHeader::IsAddBeginSet(), Flash::RecordHeader::IsAddCompleteSet(), Flash::RecordHeader::IsDeleted(), Flash::RecordHeader::IsFirst(), Flash::RecordHeader::IsValid(), Flash::RecordHeader::SetAddBeginFlag(), Flash::RecordHeader::SetAddCompleteFlag(), Flash::RecordHeader::SetDeleted(), and Flash::RecordHeader::SetFirst().
mLength
uint16_t mLength private
Referenced by Flash::RecordHeader::GetLength(), Flash::RecordHeader::GetSize(), Flash::RecordHeader::Init(), and Flash::RecordHeader::SetLength().
mReserved
uint16_t mReserved private
Referenced by Flash::RecordHeader::Init().
The documentation for this class was generated from the following file:
flash.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale