OpenThread: AnnounceSenderBase Class Reference
AnnounceSenderBase Class Reference
#include <announce_sender.hpp>
Protected Member Functions
AnnounceSenderBase (Instance &aInstance, Timer::Handler aHandler)
const Mac::ChannelMask GetChannelMask (void) const
uint32_t GetPeriod (void) const
void HandleTimer (void)
bool IsRunning (void) const
otError SendAnnounce (Mac::ChannelMask aChannelMask, uint8_t aCount, uint32_t aPeriod, uint16_t aJitter)
void Stop (void)
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Private Attributes
uint8_t mChannel
Mac::ChannelMask mChannelMask
uint8_t mCount
uint16_t mJitter
uint32_t mPeriod
TimerMilli mTimer
Additional Inherited Members
Public Member Functions inherited from InstanceLocator
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Detailed Description
This class implements the base class for an AnnounceSender and AnnounceBeginSever.
This class provides APIs to schedule periodic transmission of MLE Announcement messages for a given number transmissions per channel.
Constructor & Destructor Documentation
AnnounceSenderBase()
AnnounceSenderBase (Instance & aInstance, Timer::Handler aHandler) protected
This constructor initializes the object.
Parameters
[in] aInstance A reference to the OpenThread instance.
[in] aHandler A timer handler provided by sub-class.
Referenced by AnnounceSenderBase::HandleTimer().
Member Function Documentation
SendAnnounce()
otError SendAnnounce (Mac::ChannelMask aChannelMask, uint8_t aCount, uint32_t aPeriod, uint16_t aJitter) protected
This method schedules the MLE Announce transmissions.
This method schedules aCount MLE Announcement transmission cycles. Each cycle covers all the channel in the aChannelMask, with aPeriod time interval between any two successive MLE Announcement transmissions (possibly) on different channels from the given mask. The aJitter can be used to add a random jitter of [-aJitter, aJitter] to aPeriod interval. A zero value for aCount indicates non-stop MLE Announcement transmission cycles.
Parameters
[in] aChannelMask The channel mask providing the list of channels to use for transmission.
[in] aCount The number of transmissions per channel. Zero indicates non-stop transmissions.
[in] aPeriod The time between two successive MLE Announce transmissions (in milliseconds).
[in] aJitter Maximum random jitter added to per transmission (in milliseconds).
Return values
OT_ERROR_NONE Successfully started the transmission process.
OT_ERROR_INVALID_ARGS aChanelMask is empty, or aPeriod is zero or smaller than .
References ot::Random::NonCrypto::AddJitter(), ChannelMask::Intersect(), ChannelMask::IsEmpty(), ChannelMask::kChannelIteratorFirst, AnnounceSenderBase::mChannel, AnnounceSenderBase::mChannelMask, AnnounceSenderBase::mCount, AnnounceSenderBase::mJitter, AnnounceSenderBase::mPeriod, AnnounceSenderBase::mTimer, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, TimerMilli::Start(), and VerifyOrExit.
Referenced by AnnounceSenderBase::HandleTimer(), and AnnounceBeginServer::SendAnnounce().
Stop()
void Stop (void) inline protected
This method stops the ongoing MLE Announce transmissions.
References AnnounceSenderBase::mTimer, and TimerMilli::Stop().
Referenced by AnnounceSenderBase::HandleTimer().
IsRunning()
bool IsRunning (void) const inline protected
This method indicates whether the latest scheduled MLE Announce transmission is currently in progress or is finished.
Returns
TRUE if the MLE Announce transmission is in progress, FALSE otherwise.
References Timer::IsRunning(), and AnnounceSenderBase::mTimer.
Referenced by AnnounceSenderBase::HandleTimer().
GetPeriod()
uint32_t GetPeriod (void) const inline protected
This method gets the period for the latest scheduled MLE Announce transmission (the one in progress or the last finished one).
Returns
The period interval (in milliseconds) between two successive MLE Announcement transmissions.
References AnnounceSenderBase::mPeriod.
Referenced by AnnounceSenderBase::HandleTimer().
GetChannelMask()
const Mac::ChannelMask GetChannelMask (void) const inline protected
This method gets the channel mask for the latest scheduled MLE Announce transmission (the one in progress or the last finished one).
Returns
A constant reference to channel mask
References AnnounceSenderBase::HandleTimer(), and AnnounceSenderBase::mChannelMask.
Referenced by AnnounceSenderBase::HandleTimer().
HandleTimer()
void HandleTimer (void) protected
This method is the timer handler and must be invoked by sub-class when the timer expires from the aHandler callback function provided in the constructor.
References ot::Random::NonCrypto::AddJitter(), AnnounceSenderBase::AnnounceSenderBase(), String< SIZE >::AsCString(), ExitNow, AnnounceSenderBase::GetChannelMask(), ChannelMask::GetNextChannel(), ChannelMask::GetNumberOfChannels(), OwnerLocator::GetOwner(), AnnounceSenderBase::GetPeriod(), AnnounceSenderBase::IsRunning(), ChannelMask::kChannelIteratorFirst, ot::Mle::kRoleChild, ot::Mle::kRoleDetached, ot::Mle::kRoleDisabled, ot::Mle::kRoleLeader, ot::Mle::kRoleRouter, AnnounceSenderBase::mChannel, AnnounceSenderBase::mChannelMask, AnnounceSenderBase::mCount, AnnounceSenderBase::mJitter, AnnounceSenderBase::mPeriod, AnnounceSenderBase::mTimer, OT_ASSERT, OT_CHANGED_THREAD_ROLE, OT_ERROR_NONE, OT_ERROR_NOT_FOUND, OT_NOOP, otLogInfoMle, AnnounceSenderBase::SendAnnounce(), TimerMilli::Start(), AnnounceSenderBase::Stop(), ChannelMask::ToString(), and VerifyOrExit.
Referenced by AnnounceSenderBase::GetChannelMask(), and AnnounceBeginServer::HandleTimer().
Field Documentation
mChannelMask
Mac::ChannelMask mChannelMask private
Referenced by AnnounceSenderBase::GetChannelMask(), AnnounceSenderBase::HandleTimer(), and AnnounceSenderBase::SendAnnounce().
mPeriod
uint32_t mPeriod private
Referenced by AnnounceSenderBase::GetPeriod(), AnnounceSenderBase::HandleTimer(), and AnnounceSenderBase::SendAnnounce().
mJitter
uint16_t mJitter private
Referenced by AnnounceSenderBase::HandleTimer(), and AnnounceSenderBase::SendAnnounce().
mCount
uint8_t mCount private
Referenced by AnnounceSenderBase::HandleTimer(), and AnnounceSenderBase::SendAnnounce().
mChannel
uint8_t mChannel private
Referenced by AnnounceSenderBase::HandleTimer(), and AnnounceSenderBase::SendAnnounce().
mTimer
TimerMilli mTimer private
Referenced by AnnounceSenderBase::HandleTimer(), AnnounceSenderBase::IsRunning(), AnnounceSenderBase::SendAnnounce(), and AnnounceSenderBase::Stop().
The documentation for this class was generated from the following files:
announce_sender.hpp
announce_sender.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale