OpenThread: SubMac Class Reference
SubMac Class Reference
Core-mac
#include <sub_mac.hpp>
Data Structures
class Callbacks
Public Types
enum { kInvalidRssiValue = 127 }
Public Member Functions
otError Disable (void)
otError Enable (void)
otError EnergyScan (uint8_t aScanChannel, uint16_t aScanDuration)
otRadioCaps GetCaps (void) const
const ExtAddress & GetExtAddress (void) const
int8_t GetNoiseFloor (void)
otRadioCaps GetRadioCaps (void) const
int8_t GetRssi (void) const
ShortAddress GetShortAddress (void) const
TxFrame & GetTransmitFrame (void)
uint8_t GetTransmitRetries (void) const
otError Receive (uint8_t aChannel)
otError Send (void)
void SetExtAddress (const ExtAddress &aExtAddress)
void SetPanId (PanId aPanId)
void SetPcapCallback (otLinkPcapCallback aPcapCallback, void *aCallbackContext)
void SetRxOnWhenBackoff (bool aRxOnWhenBackoff)
void SetShortAddress (ShortAddress aShortAddress)
otError Sleep (void)
SubMac (Instance &aInstance)
Public Member Functions inherited from InstanceLocator
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Private Types
enum {
kMinBE = 3, kMaxBE = 5, kUnitBackoffPeriod = 20, kMinBackoff = 1,
kAckTimeout = 16, kEnergyScanRssiSampleInterval = 1
}
enum State {
kStateDisabled, kStateSleep, kStateReceive, kStateCsmaBackoff,
kStateTransmit, kStateEnergyScan
}
Private Member Functions
void BeginTransmit (void)
void HandleEnergyScanDone (int8_t aMaxRssi)
void HandleReceiveDone (RxFrame *aFrame, otError aError)
void HandleTimer (void)
void HandleTransmitDone (TxFrame &aTxFrame, RxFrame *aAckFrame, otError aError)
void HandleTransmitStarted (TxFrame &aFrame)
bool RadioSupportsAckTimeout (void) const
bool RadioSupportsCsmaBackoff (void) const
bool RadioSupportsEnergyScan (void) const
bool RadioSupportsRetries (void) const
void SampleRssi (void)
void SetState (State aState)
bool ShouldHandleAckTimeout (void) const
bool ShouldHandleCsmaBackOff (void) const
bool ShouldHandleEnergyScan (void) const
bool ShouldHandleRetries (void) const
void StartCsmaBackoff (void)
Static Private Member Functions
static void HandleTimer (Timer &aTimer)
static const char * StateToString (State aState)
Private Attributes
Callbacks mCallbacks
uint8_t mCsmaBackoffs
TimeMilli mEnergyScanEndTime
int8_t mEnergyScanMaxRssi
ExtAddress mExtAddress
otLinkPcapCallback mPcapCallback
void * mPcapCallbackContext
otRadioCaps mRadioCaps
bool mRxOnWhenBackoff
ShortAddress mShortAddress
State mState
TimerMilli mTimer
TxFrame & mTransmitFrame
uint8_t mTransmitRetries
Friends
class Radio::Callbacks
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Detailed Description
This class implements the IEEE 802.15.4 MAC (sub-MAC).
Sub-MAC layer implements a subset of IEEE802.15.4 MAC primitives which are shared by both MAC layer (in FTD/MTD modes) and Raw Link (Radio only mode).
The sub-MAC layer handles the following (if not provided by radio platform):
Ack timeout for frame transmission,
CSMA backoff logic,
Frame re-transmissions,
Energy scan on a single channel and RSSI sampling.
It also act as the interface (to radio platform) for setting/getting radio configurations such as short or extended addresses and PAN Id.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
kInvalidRssiValue
Invalid Received Signal Strength Indicator (RSSI) value.
anonymous enum
anonymous enum private
Enumerator
kMinBE
macMinBE (IEEE 802.15.4-2006).
kMaxBE
macMaxBE (IEEE 802.15.4-2006).
kUnitBackoffPeriod
Number of symbols (IEEE 802.15.4-2006).
kMinBackoff
Minimum backoff (milliseconds).
kAckTimeout
Timeout for waiting on an ACK (milliseconds).
kEnergyScanRssiSampleInterval
RSSI sample interval during energy scan, 1 ms.
State
enum State private
Enumerator
kStateDisabled
Radio is disabled.
kStateSleep
Radio is in sleep.
kStateReceive
Radio in in receive.
kStateCsmaBackoff
CSMA backoff before transmission.
kStateTransmit
Radio is transmitting.
kStateEnergyScan
Energy scan.
Constructor & Destructor Documentation
SubMac()
SubMac (Instance & aInstance) explicit
This constructor initializes the SubMac object.
Parameters
[in] aInstance A reference to the OpenThread instance.
References ExtAddress::Clear(), and SubMac::mExtAddress.
Member Function Documentation
GetRadioCaps()
otRadioCaps GetRadioCaps (void) const inline
This method gets the capabilities provided by platform radio.
Returns
The capability bit vector (see OT_RADIO_CAP_* definitions).
References SubMac::GetCaps(), SubMac::mRadioCaps, and SubMac::SetPanId().
GetCaps()
otRadioCaps GetCaps (void) const
This method gets the capabilities provided by SubMac layer.
Returns
The capability bit vector (see OT_RADIO_CAP_* definitions).
References SubMac::mRadioCaps, OT_RADIO_CAPS_ACK_TIMEOUT, OT_RADIO_CAPS_CSMA_BACKOFF, OT_RADIO_CAPS_ENERGY_SCAN, and OT_RADIO_CAPS_TRANSMIT_RETRIES.
Referenced by SubMac::GetRadioCaps().
SetPanId()
void SetPanId (PanId aPanId)
This method sets the PAN ID.
Parameters
[in] aPanId The PAN ID.
References otLogDebgMac.
Referenced by Mac::BeginTransmit(), SubMac::GetRadioCaps(), Mac::PerformActiveScan(), and Mac::SetPanId().
GetShortAddress()
ShortAddress GetShortAddress (void) const inline
This method gets the short address.
Returns
The short address.
References SubMac::mShortAddress, and SubMac::SetShortAddress().
Referenced by Mac::GetShortAddress().
SetShortAddress()
void SetShortAddress (ShortAddress aShortAddress)
This method sets the short address.
Parameters
[in] aShortAddress The short address.
References SubMac::mShortAddress, and otLogDebgMac.
Referenced by SubMac::GetShortAddress(), and Mac::SetShortAddress().
GetExtAddress()
const ExtAddress& GetExtAddress (void) const inline
This function gets the extended address.
Returns
A reference to the extended address.
References SubMac::mExtAddress, SubMac::SetExtAddress(), and SubMac::SetPcapCallback().
Referenced by Mac::GetExtAddress().
SetExtAddress()
void SetExtAddress (const ExtAddress & aExtAddress)
This method sets extended address.
Parameters
[in] aExtAddress The extended address.
References String< SIZE >::AsCString(), ExtAddress::kReverseByteOrder, otExtAddress::m8, SubMac::mExtAddress, otLogDebgMac, ExtAddress::Set(), and ExtAddress::ToString().
Referenced by SubMac::GetExtAddress(), and Mac::SetExtAddress().
SetPcapCallback()
void SetPcapCallback (otLinkPcapCallback aPcapCallback, void * aCallbackContext)
This method registers a callback to provide received packet capture for IEEE 802.15.4 frames.
Parameters
[in] aPcapCallback A pointer to a function that is called when receiving an IEEE 802.15.4 link frame or NULL to disable the callback.
[in] aCallbackContext A pointer to application-specific context.
References SubMac::mPcapCallback, and SubMac::mPcapCallbackContext.
Referenced by SubMac::GetExtAddress(), and Mac::SetPcapCallback().
SetRxOnWhenBackoff()
void SetRxOnWhenBackoff (bool aRxOnWhenBackoff) inline
This method indicates whether radio should stay in Receive or Sleep during CSMA backoff.
Parameters
[in] aRxOnWhenBackoff TRUE to keep radio in Receive, FALSE to put to Sleep during CSMA backoff.
References SubMac::Disable(), SubMac::Enable(), SubMac::mRxOnWhenBackoff, SubMac::Receive(), and SubMac::Sleep().
Referenced by Mac::SetPromiscuous(), and Mac::SetRxOnWhenIdle().
Enable()
otError Enable (void)
This method enables the radio.
Return values
OT_ERROR_NONE Successfully enabled.
OT_ERROR_FAILED The radio could not be enabled.
References SubMac::kStateDisabled, SubMac::kStateSleep, SubMac::mState, OT_ASSERT, OT_ERROR_NONE, OT_NOOP, SubMac::SetState(), SubMac::Sleep(), SuccessOrExit, and VerifyOrExit.
Referenced by Mac::Mac(), and SubMac::SetRxOnWhenBackoff().
Disable()
otError Disable (void)
This method disables the radio.
Return values
OT_ERROR_NONE Successfully disabled the radio.
References SubMac::kStateDisabled, SubMac::mTimer, SubMac::SetState(), SubMac::Sleep(), TimerMilli::Stop(), and SuccessOrExit.
Referenced by SubMac::SetRxOnWhenBackoff().
Sleep()
otError Sleep (void)
This method transitions the radio to Sleep.
Return values
OT_ERROR_NONE Successfully transitioned to Sleep.
OT_ERROR_BUSY The radio was transmitting.
OT_ERROR_INVALID_STATE The radio was disabled.
References ExitNow, SubMac::kStateSleep, OT_ERROR_NONE, otLogWarnMac, otThreadErrorToString(), and SubMac::SetState().
Referenced by SubMac::Disable(), SubMac::Enable(), SubMac::SetRxOnWhenBackoff(), SubMac::StartCsmaBackoff(), and Mac::UpdateIdleMode().
Receive()
otError Receive (uint8_t aChannel)
This method transitions the radio to Receive.
Parameters
[in] aChannel The channel to use for receiving.
Return values
OT_ERROR_NONE Successfully transitioned to Receive.
OT_ERROR_INVALID_STATE The radio was disabled or transmitting.
References ExitNow, SubMac::kStateReceive, OT_ERROR_NONE, otLogWarnMac, otThreadErrorToString(), and SubMac::SetState().
Referenced by SubMac::BeginTransmit(), SubMac::EnergyScan(), SubMac::HandleTimer(), Mac::PerformEnergyScan(), Mac::PerformNextOperation(), SubMac::SetRxOnWhenBackoff(), SubMac::StartCsmaBackoff(), and Mac::UpdateIdleMode().
GetTransmitFrame()
TxFrame& GetTransmitFrame (void) inline
This method gets the radio transmit frame.
Returns
The transmit frame.
References SubMac::mTransmitFrame, and SubMac::Send().
Referenced by Mac::BeginTransmit().
Send()
otError Send (void)
This method sends a prepared frame.
The frame should be placed in GetTransmitFrame() frame.
The SubMac layer handles Ack timeout, CSMA backoff, and frame retransmission.
Return values
OT_ERROR_NONE Successfully started the frame transmission
OT_ERROR_INVALID_STATE The radio was disabled or transmitting.
References ExitNow, SubMac::kStateCsmaBackoff, SubMac::kStateDisabled, SubMac::kStateEnergyScan, SubMac::kStateReceive, SubMac::kStateSleep, SubMac::kStateTransmit, SubMac::mCsmaBackoffs, SubMac::mState, SubMac::mTransmitRetries, OT_ERROR_INVALID_STATE, OT_ERROR_NONE, OT_UNREACHABLE_CODE, and SubMac::StartCsmaBackoff().
Referenced by Mac::BeginTransmit(), SubMac::GetTransmitFrame(), and Mac::HandleTransmitDone().
GetTransmitRetries()
uint8_t GetTransmitRetries (void) const inline
This method gets the number of transmit retries of last transmit packet.
Returns
Number of transmit retries.
References SubMac::EnergyScan(), SubMac::GetNoiseFloor(), SubMac::GetRssi(), and SubMac::mTransmitRetries.
Referenced by Mac::HandleTransmitDone().
GetRssi()
int8_t GetRssi (void) const
This method gets the most recent RSSI measurement.
Returns
The RSSI in dBm when it is valid. kInvalidRssiValue when RSSI is invalid.
Referenced by SubMac::GetTransmitRetries(), Mac::PerformEnergyScan(), and SubMac::SampleRssi().
EnergyScan()
otError EnergyScan (uint8_t aScanChannel, uint16_t aScanDuration)
This method begins energy scan.
Parameters
[in] aScanChannel The channel to perform the energy scan on.
[in] aScanDuration The duration, in milliseconds, for the channel to be scanned.
Return values
OT_ERROR_NONE Successfully started scanning the channel.
OT_ERROR_INVALID_STATE The radio was disabled or transmitting.
OT_ERROR_NOT_IMPLEMENTED Energy scan is not supported (applicable in link-raw/radio mode only).
References ExitNow, TimerMilli::GetNow(), SubMac::kInvalidRssiValue, SubMac::kStateCsmaBackoff, SubMac::kStateDisabled, SubMac::kStateEnergyScan, SubMac::kStateReceive, SubMac::kStateSleep, SubMac::kStateTransmit, SubMac::mEnergyScanEndTime, SubMac::mEnergyScanMaxRssi, SubMac::mState, SubMac::mTimer, OT_ASSERT, OT_ERROR_INVALID_STATE, OT_ERROR_NONE, OT_ERROR_NOT_IMPLEMENTED, SubMac::RadioSupportsEnergyScan(), SubMac::Receive(), SubMac::SetState(), SubMac::ShouldHandleEnergyScan(), and TimerMilli::Start().
Referenced by SubMac::GetTransmitRetries(), and Mac::PerformEnergyScan().
GetNoiseFloor()
int8_t GetNoiseFloor (void)
This method returns the noise floor value (currently use the radio receive sensitivity value).
Returns
The noise floor value in dBm.
Referenced by Mac::GetNoiseFloor(), and SubMac::GetTransmitRetries().
RadioSupportsCsmaBackoff()
bool RadioSupportsCsmaBackoff (void) const inline private
References SubMac::mRadioCaps, OT_RADIO_CAPS_CSMA_BACKOFF, and OT_RADIO_CAPS_TRANSMIT_RETRIES.
Referenced by SubMac::ShouldHandleCsmaBackOff().
RadioSupportsRetries()
bool RadioSupportsRetries (void) const inline private
References SubMac::mRadioCaps, and OT_RADIO_CAPS_TRANSMIT_RETRIES.
Referenced by SubMac::ShouldHandleRetries().
RadioSupportsAckTimeout()
bool RadioSupportsAckTimeout (void) const inline private
References SubMac::mRadioCaps, and OT_RADIO_CAPS_ACK_TIMEOUT.
Referenced by SubMac::ShouldHandleAckTimeout().
RadioSupportsEnergyScan()
bool RadioSupportsEnergyScan (void) const inline private
References SubMac::BeginTransmit(), SubMac::HandleEnergyScanDone(), SubMac::HandleReceiveDone(), SubMac::HandleTimer(), SubMac::HandleTransmitDone(), SubMac::HandleTransmitStarted(), SubMac::mRadioCaps, OT_RADIO_CAPS_ENERGY_SCAN, SubMac::SampleRssi(), SubMac::SetState(), SubMac::ShouldHandleAckTimeout(), SubMac::ShouldHandleCsmaBackOff(), SubMac::ShouldHandleEnergyScan(), SubMac::ShouldHandleRetries(), SubMac::StartCsmaBackoff(), and SubMac::StateToString().
Referenced by SubMac::EnergyScan(), SubMac::SampleRssi(), and SubMac::ShouldHandleEnergyScan().
ShouldHandleCsmaBackOff()
bool ShouldHandleCsmaBackOff (void) const private
References OPENTHREAD_CONFIG_SOFTWARE_CSMA_BACKOFF_ENABLE, OT_NOOP, SubMac::RadioSupportsCsmaBackoff(), and VerifyOrExit.
Referenced by SubMac::HandleTransmitDone(), SubMac::RadioSupportsEnergyScan(), and SubMac::StartCsmaBackoff().
ShouldHandleAckTimeout()
bool ShouldHandleAckTimeout (void) const private
References OPENTHREAD_CONFIG_SOFTWARE_ACK_TIMEOUT_ENABLE, OT_NOOP, SubMac::RadioSupportsAckTimeout(), and VerifyOrExit.
Referenced by SubMac::HandleTransmitStarted(), and SubMac::RadioSupportsEnergyScan().
ShouldHandleRetries()
bool ShouldHandleRetries (void) const private
References OPENTHREAD_CONFIG_SOFTWARE_RETRANSMIT_ENABLE, OT_NOOP, SubMac::RadioSupportsRetries(), and VerifyOrExit.
Referenced by SubMac::HandleTransmitDone(), and SubMac::RadioSupportsEnergyScan().
ShouldHandleEnergyScan()
bool ShouldHandleEnergyScan (void) const private
References OPENTHREAD_CONFIG_SOFTWARE_ENERGY_SCAN_ENABLE, OT_NOOP, SubMac::RadioSupportsEnergyScan(), and VerifyOrExit.
Referenced by SubMac::EnergyScan(), and SubMac::RadioSupportsEnergyScan().
StartCsmaBackoff()
void StartCsmaBackoff (void) private
References SubMac::BeginTransmit(), Frame::GetChannel(), ot::Random::NonCrypto::GetUint32InRange(), SubMac::kMaxBE, SubMac::kMinBE, SubMac::kStateCsmaBackoff, SubMac::kUnitBackoffPeriod, SubMac::mCsmaBackoffs, SubMac::mRxOnWhenBackoff, SubMac::mTimer, SubMac::mTransmitFrame, SubMac::mTransmitRetries, OT_RADIO_SYMBOL_TIME, SubMac::Receive(), SubMac::SetState(), SubMac::ShouldHandleCsmaBackOff(), SubMac::Sleep(), TimerMilli::Start(), and VerifyOrExit.
Referenced by SubMac::HandleTransmitDone(), SubMac::RadioSupportsEnergyScan(), and SubMac::Send().
BeginTransmit()
void BeginTransmit (void) private
References Frame::GetChannel(), SubMac::kStateCsmaBackoff, SubMac::kStateTransmit, SubMac::mPcapCallback, SubMac::mPcapCallbackContext, SubMac::mRadioCaps, SubMac::mState, SubMac::mTransmitFrame, OT_ASSERT, OT_ERROR_NONE, OT_NOOP, OT_RADIO_CAPS_SLEEP_TO_TX, OT_UNUSED_VARIABLE, SubMac::Receive(), TxFrame::SetCsmaCaEnabled(), SubMac::SetState(), and VerifyOrExit.
Referenced by SubMac::HandleTimer(), SubMac::RadioSupportsEnergyScan(), and SubMac::StartCsmaBackoff().
SampleRssi()
void SampleRssi (void) private
References Timer::GetFireTime(), TimerMilli::GetNow(), SubMac::GetRssi(), SubMac::HandleEnergyScanDone(), SubMac::kEnergyScanRssiSampleInterval, SubMac::kInvalidRssiValue, SubMac::mEnergyScanEndTime, SubMac::mEnergyScanMaxRssi, SubMac::mTimer, OT_ASSERT, SubMac::RadioSupportsEnergyScan(), and TimerMilli::StartAt().
Referenced by SubMac::HandleTimer(), and SubMac::RadioSupportsEnergyScan().
HandleReceiveDone()
void HandleReceiveDone (RxFrame * aFrame, otError aError) private
References SubMac::mCallbacks, SubMac::mPcapCallback, SubMac::mPcapCallbackContext, OT_ERROR_NONE, and SubMac::Callbacks::ReceiveDone().
Referenced by SubMac::RadioSupportsEnergyScan().
HandleTransmitStarted()
void HandleTransmitStarted (TxFrame & aFrame) private
References Frame::GetAckRequest(), SubMac::kAckTimeout, SubMac::mTimer, SubMac::ShouldHandleAckTimeout(), and TimerMilli::Start().
Referenced by SubMac::RadioSupportsEnergyScan().
HandleTransmitDone()
void HandleTransmitDone (TxFrame & aTxFrame, RxFrame * aAckFrame, otError aError) private
References ExitNow, Frame::GetChannel(), TxFrame::GetMaxCsmaBackoffs(), TxFrame::GetMaxFrameRetries(), TxFrame::IsCsmaCaEnabled(), SubMac::kStateReceive, SubMac::mCallbacks, SubMac::mCsmaBackoffs, SubMac::mTimer, SubMac::mTransmitRetries, OT_ASSERT, OT_ERROR_ABORT, OT_ERROR_CHANNEL_ACCESS_FAILURE, OT_ERROR_NO_ACK, OT_ERROR_NONE, OT_UNREACHABLE_CODE, SubMac::Callbacks::RecordCcaStatus(), SubMac::Callbacks::RecordFrameTransmitStatus(), TxFrame::SetIsARetransmission(), SubMac::SetState(), SubMac::ShouldHandleCsmaBackOff(), SubMac::ShouldHandleRetries(), SubMac::StartCsmaBackoff(), TimerMilli::Stop(), and SubMac::Callbacks::TransmitDone().
Referenced by SubMac::Callbacks::Callbacks(), SubMac::HandleTimer(), and SubMac::RadioSupportsEnergyScan().
HandleEnergyScanDone()
void HandleEnergyScanDone (int8_t aMaxRssi) private
References SubMac::Callbacks::EnergyScanDone(), SubMac::kStateReceive, SubMac::mCallbacks, and SubMac::SetState().
Referenced by SubMac::RadioSupportsEnergyScan(), and SubMac::SampleRssi().
HandleTimer() [1/2]
void HandleTimer (Timer & aTimer) static private
References OwnerLocator::GetOwner(), and SubMac::HandleTimer().
HandleTimer() [2/2]
void HandleTimer (void) private
References SubMac::BeginTransmit(), Frame::GetChannel(), SubMac::HandleTransmitDone(), SubMac::kStateCsmaBackoff, SubMac::kStateEnergyScan, SubMac::kStateTransmit, SubMac::mState, SubMac::mTransmitFrame, OT_ERROR_NO_ACK, otLogDebgMac, SubMac::Receive(), and SubMac::SampleRssi().
Referenced by SubMac::HandleTimer(), and SubMac::RadioSupportsEnergyScan().
SetState()
void SetState (State aState) private
References SubMac::mState, otLogDebgMac, and SubMac::StateToString().
Referenced by SubMac::BeginTransmit(), SubMac::Disable(), SubMac::Enable(), SubMac::EnergyScan(), SubMac::HandleEnergyScanDone(), SubMac::HandleTransmitDone(), SubMac::RadioSupportsEnergyScan(), SubMac::Receive(), SubMac::Sleep(), and SubMac::StartCsmaBackoff().
StateToString()
const char * StateToString (State aState) static private
References SubMac::kStateCsmaBackoff, SubMac::kStateDisabled, SubMac::kStateEnergyScan, SubMac::kStateReceive, SubMac::kStateSleep, and SubMac::kStateTransmit.
Referenced by SubMac::RadioSupportsEnergyScan(), and SubMac::SetState().
Friends And Related Function Documentation
Radio::Callbacks
friend class Radio::Callbacks friend
Field Documentation
mRadioCaps
otRadioCaps mRadioCaps private
Referenced by SubMac::BeginTransmit(), SubMac::GetCaps(), SubMac::GetRadioCaps(), SubMac::RadioSupportsAckTimeout(), SubMac::RadioSupportsCsmaBackoff(), SubMac::RadioSupportsEnergyScan(), and SubMac::RadioSupportsRetries().
mState
State mState private
Referenced by SubMac::BeginTransmit(), SubMac::Enable(), SubMac::EnergyScan(), SubMac::HandleTimer(), SubMac::Send(), and SubMac::SetState().
mCsmaBackoffs
uint8_t mCsmaBackoffs private
Referenced by SubMac::HandleTransmitDone(), SubMac::Send(), and SubMac::StartCsmaBackoff().
mTransmitRetries
uint8_t mTransmitRetries private
Referenced by SubMac::GetTransmitRetries(), SubMac::HandleTransmitDone(), SubMac::Send(), and SubMac::StartCsmaBackoff().
mShortAddress
ShortAddress mShortAddress private
Referenced by SubMac::GetShortAddress(), and SubMac::SetShortAddress().
mExtAddress
ExtAddress mExtAddress private
Referenced by SubMac::GetExtAddress(), SubMac::SetExtAddress(), and SubMac::SubMac().
mRxOnWhenBackoff
bool mRxOnWhenBackoff private
Referenced by SubMac::SetRxOnWhenBackoff(), and SubMac::StartCsmaBackoff().
mEnergyScanMaxRssi
int8_t mEnergyScanMaxRssi private
Referenced by SubMac::EnergyScan(), and SubMac::SampleRssi().
mEnergyScanEndTime
TimeMilli mEnergyScanEndTime private
Referenced by SubMac::EnergyScan(), and SubMac::SampleRssi().
mTransmitFrame
TxFrame& mTransmitFrame private
Referenced by SubMac::BeginTransmit(), SubMac::GetTransmitFrame(), SubMac::HandleTimer(), and SubMac::StartCsmaBackoff().
mCallbacks
Callbacks mCallbacks private
Referenced by SubMac::HandleEnergyScanDone(), SubMac::HandleReceiveDone(), and SubMac::HandleTransmitDone().
mPcapCallback
otLinkPcapCallback mPcapCallback private
Referenced by SubMac::BeginTransmit(), SubMac::HandleReceiveDone(), and SubMac::SetPcapCallback().
mPcapCallbackContext
void* mPcapCallbackContext private
Referenced by SubMac::BeginTransmit(), SubMac::HandleReceiveDone(), and SubMac::SetPcapCallback().
mTimer
TimerMilli mTimer private
Referenced by SubMac::Disable(), SubMac::EnergyScan(), SubMac::HandleTransmitDone(), SubMac::HandleTransmitStarted(), SubMac::SampleRssi(), and SubMac::StartCsmaBackoff().
The documentation for this class was generated from the following files:
sub_mac.hpp
sub_mac.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale