OpenThread: IndirectSender Class Reference
IndirectSender Class Reference
Core-mesh-forwarding
#include <indirect_sender.hpp>
Data Structures
class ChildInfo
Public Member Functions
otError AddMessageForSleepyChild (Message &aMessage, Child &aChild)
void ClearAllMessagesForSleepyChild (Child &aChild)
void HandleChildModeChange (Child &aChild, Mle::DeviceMode aOldMode)
IndirectSender (Instance &aInstance)
otError RemoveMessageFromSleepyChild (Message &aMessage, Child &aChild)
void SetChildUseShortAddress (Child &aChild, bool aUseShortAddress)
void Start (void)
void Stop (void)
Public Member Functions inherited from InstanceLocator
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Private Types
enum { kSupervisionMsgAckRequest = (OPENTHREAD_CONFIG_CHILD_SUPERVISION_MSG_NO_ACK_REQUEST == 0) ? true : false }
Private Member Functions
void ClearMessagesForRemovedChildren (void)
Message * FindIndirectMessage (Child &aChild)
void HandleFrameChangeDone (Child &aChild)
void HandleSentFrameToChild (const Mac::TxFrame &aFrame, const FrameContext &aContext, otError aError, Child &aChild)
uint16_t PrepareDataFrame (Mac::TxFrame &aFrame, Child &aChild, Message &aMessage)
void PrepareEmptyFrame (Mac::TxFrame &aFrame, Child &aChild, bool aAckRequest)
otError PrepareFrameForChild (Mac::TxFrame &aFrame, FrameContext &aContext, Child &aChild)
void RequestMessageUpdate (Child &aChild)
void UpdateIndirectMessage (Child &aChild)
Private Attributes
DataPollHandler mDataPollHandler
bool mEnabled
SourceMatchController mSourceMatchController
Friends
class DataPollHandler::Callbacks
class Instance
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Detailed Description
This class implements indirect transmission.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
kSupervisionMsgAckRequest
Indicates whether to set/enable 15.4 ack request in the MAC header of a supervision message.
Constructor & Destructor Documentation
IndirectSender()
IndirectSender (Instance & aInstance) explicit
This constructor initializes the object.
Parameters
[in] aInstance A reference to the OpenThread instance.
Member Function Documentation
Start()
void Start (void) inline
This method enables indirect transmissions.
References IndirectSender::AddMessageForSleepyChild(), IndirectSender::ClearAllMessagesForSleepyChild(), IndirectSender::HandleChildModeChange(), IndirectSender::mEnabled, IndirectSender::RemoveMessageFromSleepyChild(), IndirectSender::SetChildUseShortAddress(), and IndirectSender::Stop().
Stop()
void Stop (void)
This method disables indirect transmission.
Any previously scheduled indirect transmission is canceled.
Referenced by IndirectSender::Start().
AddMessageForSleepyChild()
otError AddMessageForSleepyChild (Message & aMessage, Child & aChild)
This method adds a message for indirect transmission to a sleepy child.
Parameters
[in] aMessage The message to add.
[in] aChild The (sleepy) child for indirect transmission.
Return values
OT_ERROR_NONE Successfully added the message for indirect transmission.
OT_ERROR_ALREADY The message was already added for indirect transmission to same child.
OT_ERROR_INVALID_STATE The child is not sleepy.
Referenced by IndirectSender::Start().
RemoveMessageFromSleepyChild()
otError RemoveMessageFromSleepyChild (Message & aMessage, Child & aChild)
This method removes a message for indirect transmission to a sleepy child.
Parameters
[in] aMessage The message to update.
[in] aChild The (sleepy) child for indirect transmission.
Return values
OT_ERROR_NONE Successfully removed the message for indirect transmission.
OT_ERROR_NOT_FOUND The message was not scheduled for indirect transmission to the child.
Referenced by IndirectSender::Start().
ClearAllMessagesForSleepyChild()
void ClearAllMessagesForSleepyChild (Child & aChild)
This method removes all added messages for a specific child and frees message (with no indirect/direct tx).
Parameters
[in] aChild A reference to a child whose messages shall be removed.
Referenced by IndirectSender::Start().
SetChildUseShortAddress()
void SetChildUseShortAddress (Child & aChild, bool aUseShortAddress)
This method sets whether to use the extended or short address for a child.
Parameters
[in] aChild A reference to the child.
[in] aUseShortAddress true to use short address, false to use extended address.
Referenced by IndirectSender::Start().
HandleChildModeChange()
void HandleChildModeChange (Child & aChild, Mle::DeviceMode aOldMode)
This method handles a child mode change and updates any queued messages for the child accordingly.
Parameters
[in] aChild The child whose device mode was changed.
[in] aOldMode The old device mode of the child.
Referenced by IndirectSender::Start().
PrepareFrameForChild()
otError PrepareFrameForChild (Mac::TxFrame & aFrame, FrameContext & aContext, Child & aChild) private
HandleSentFrameToChild()
void HandleSentFrameToChild (const Mac::TxFrame & aFrame, const FrameContext & aContext, otError aError, Child & aChild) private
HandleFrameChangeDone()
void HandleFrameChangeDone (Child & aChild) private
UpdateIndirectMessage()
void UpdateIndirectMessage (Child & aChild) private
FindIndirectMessage()
Message* FindIndirectMessage (Child & aChild) private
RequestMessageUpdate()
void RequestMessageUpdate (Child & aChild) private
PrepareDataFrame()
uint16_t PrepareDataFrame (Mac::TxFrame & aFrame, Child & aChild, Message & aMessage) private
PrepareEmptyFrame()
void PrepareEmptyFrame (Mac::TxFrame & aFrame, Child & aChild, bool aAckRequest) private
ClearMessagesForRemovedChildren()
void ClearMessagesForRemovedChildren (void) private
Friends And Related Function Documentation
Instance
friend class Instance friend
DataPollHandler::Callbacks
friend class DataPollHandler::Callbacks friend
Field Documentation
mEnabled
bool mEnabled private
Referenced by IndirectSender::Start().
mSourceMatchController
SourceMatchController mSourceMatchController private
mDataPollHandler
DataPollHandler mDataPollHandler private
The documentation for this class was generated from the following file:
indirect_sender.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale