OpenThread: ChildSupervisor Class Reference
ChildSupervisor Class Reference
#include <child_supervision.hpp>
Public Member Functions
ChildSupervisor (otInstance &)
Child * GetDestination (const Message &) const
uint16_t GetSupervisionInterval (void) const
void SetSupervisionInterval (uint16_t)
void Start (void)
void Stop (void)
void UpdateOnSend (Child &)
Detailed Description
Child supervision feature provides a mechanism for parent to ensure that a message is sent to each sleepy child within a fixed interval, namely the supervision interval. If there is no transmission to the child within the supervision interval, child supervisor enqueues and sends a supervision message (a data message with empty payload) to the child.
On the child side, this is used to check the connectivity to the parent. If the child does not hear from its parent for a pre-specified timeout interval it assumes that it may be disconnected and tries to re-attach to the parent.
The child supervision provides an alternative, more energy-efficient solution compared to requiring the sleepy child to periodically perform an MLE Child Update Request/Response exchange with the parent (as a way of verifying that it is still connected to the parent). The child supervision solution puts the burden of message transmissions on the parent instead of the typically more energy-constrained child.
Note that most radios generate an auto-ack in hardware in response to a received frame, so the child cannot solely rely on the 15.4 acknowledgments it receives from parent as an indicator that it is still connected and is in parent's child table.
Constructor & Destructor Documentation
ChildSupervisor()
ChildSupervisor (otInstance &) inline explicit
Member Function Documentation
Start()
void Start (void) inline
Referenced by ChildSupervisor::UpdateOnSend().
Stop()
void Stop (void) inline
Referenced by ChildSupervisor::UpdateOnSend().
SetSupervisionInterval()
void SetSupervisionInterval (uint16_t) inline
GetSupervisionInterval()
uint16_t GetSupervisionInterval (void) const inline
GetDestination()
Child* GetDestination (const Message &) const inline
UpdateOnSend()
void UpdateOnSend (Child &) inline
References OPENTHREAD_CONFIG_CHILD_SUPERVISION_CHECK_TIMEOUT, ChildSupervisor::Start(), and ChildSupervisor::Stop().
The documentation for this class was generated from the following file:
child_supervision.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale