OpenThread: Icmp Class Reference
Icmp Class Reference
Core-ipv6 » ICMPv6
#include <icmp6.hpp>
Public Member Functions
otIcmp6EchoMode GetEchoMode (void) const
otError HandleMessage (Message &aMessage, MessageInfo &aMessageInfo)
Icmp (Instance &aInstance)
Message * NewMessage (uint16_t aReserved)
otError RegisterHandler (IcmpHandler &aHandler)
otError SendEchoRequest (Message &aMessage, const MessageInfo &aMessageInfo, uint16_t aIdentifier)
otError SendError (IcmpHeader::Type aType, IcmpHeader::Code aCode, const MessageInfo &aMessageInfo, const Message &aMessage)
void SetEchoMode (otIcmp6EchoMode aMode)
bool ShouldHandleEchoRequest (const MessageInfo &aMessageInfo)
void UpdateChecksum (Message &aMessage, uint16_t aChecksum)
Public Member Functions inherited from InstanceLocator
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Private Member Functions
otError HandleEchoRequest (Message &aRequestMessage, const MessageInfo &aMessageInfo)
Private Attributes
otIcmp6EchoMode mEchoMode
uint16_t mEchoSequence
LinkedList< IcmpHandler > mHandlers
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Detailed Description
This class implements ICMPv6.
Constructor & Destructor Documentation
Icmp()
Icmp (Instance & aInstance) explicit
This constructor initializes the object.
Parameters
[in] aInstance A reference to the OpenThread instance.
Member Function Documentation
NewMessage()
Message * NewMessage (uint16_t aReserved)
This method returns a new ICMP message with sufficient header space reserved.
Parameters
[in] aReserved The number of header bytes to reserve after the ICMP header.
Returns
A pointer to the message or NULL if no buffers are available.
Referenced by Icmp::HandleEchoRequest(), and Icmp::SendError().
RegisterHandler()
otError RegisterHandler (IcmpHandler & aHandler)
This method registers ICMPv6 handler.
Parameters
[in] aHandler A reference to the ICMPv6 handler.
Return values
OT_ERROR_NONE Successfully registered the ICMPv6 handler.
OT_ERROR_ALREADY The ICMPv6 handler is already registered.
References Icmp::mHandlers.
SendEchoRequest()
otError SendEchoRequest (Message & aMessage, const MessageInfo & aMessageInfo, uint16_t aIdentifier)
This method sends an ICMPv6 Echo Request message.
Parameters
[in] aMessage A reference to the Echo Request payload.
[in] aMessageInfo A reference to the message info associated with aMessage.
[in] aIdentifier An identifier to aid in matching Echo Replies to this Echo Request. May be zero.
Return values
OT_ERROR_NONE Successfully enqueued the ICMPv6 Echo Request message.
OT_ERROR_NO_BUFS Insufficient buffers available to generate an ICMPv6 Echo Request message.
References IcmpHeader::GetSequence(), IcmpHeader::Init(), ot::Ip6::kProtoIcmp6, IcmpHeader::kTypeEchoRequest, Icmp::mEchoSequence, OT_ERROR_NONE, otLogInfoIcmp, Message::Prepend(), IcmpHeader::SetId(), Message::SetOffset(), IcmpHeader::SetSequence(), IcmpHeader::SetType(), and SuccessOrExit.
SendError()
otError SendError (IcmpHeader::Type aType, IcmpHeader::Code aCode, const MessageInfo & aMessageInfo, const Message & aMessage)
This method sends an ICMPv6 error message.
Parameters
[in] aType The ICMPv6 message type.
[in] aCode The ICMPv6 message code.
[in] aMessageInfo A reference to the message info.
[in] aMessage The error-causing IPv6 message.
Return values
OT_ERROR_NONE Successfully enqueued the ICMPv6 error message.
OT_ERROR_NO_BUFS Insufficient buffers available.
References Message::Free(), Message::GetLength(), Header::GetNextHeader(), IcmpHeader::Init(), IcmpHeader::IsError(), ot::Ip6::kProtoIcmp6, Icmp::NewMessage(), OT_ERROR_INVALID_ARGS, OT_ERROR_NO_BUFS, OT_ERROR_NONE, OT_NOOP, otLogInfoIcmp, Message::Read(), IcmpHeader::SetCode(), Message::SetLength(), IcmpHeader::SetType(), SuccessOrExit, VerifyOrExit, and Message::Write().
Referenced by Ip6::HandleOptions().
HandleMessage()
otError HandleMessage (Message & aMessage, MessageInfo & aMessageInfo)
This method handles an ICMPv6 message.
Parameters
[in] aMessage A reference to the ICMPv6 message.
[in] aMessageInfo A reference to the message info associated with aMessage.
Return values
OT_ERROR_NONE Successfully processed the ICMPv6 message.
OT_ERROR_NO_BUFS Insufficient buffers available to generate the reply.
OT_ERROR_DROP The ICMPv6 message was invalid and dropped.
References Ip6::ComputePseudoheaderChecksum(), Message::GetLength(), Message::GetOffset(), MessageInfo::GetPeerAddr(), MessageInfo::GetSockAddr(), IcmpHeader::GetType(), Icmp::HandleEchoRequest(), ot::Ip6::kProtoIcmp6, IcmpHeader::kTypeEchoRequest, Icmp::mHandlers, Message::MoveOffset(), OT_ERROR_NONE, OT_ERROR_PARSE, Message::Read(), SuccessOrExit, Message::UpdateChecksum(), and VerifyOrExit.
Referenced by Ip6::HandlePayload().
UpdateChecksum()
void UpdateChecksum (Message & aMessage, uint16_t aChecksum)
This method updates the ICMPv6 checksum.
Parameters
[in] aMessage A reference to the ICMPv6 message.
[in] aChecksum The pseudo-header checksum value.
References IcmpHeader::GetChecksumOffset(), Message::GetLength(), Message::GetOffset(), ot::Encoding::BigEndian::HostSwap16(), Message::UpdateChecksum(), and Message::Write().
Referenced by Ip6::SendDatagram().
GetEchoMode()
otIcmp6EchoMode GetEchoMode (void) const inline
This method indicates whether or not ICMPv6 Echo processing is enabled.
Return values
TRUE ICMPv6 Echo processing is enabled.
FALSE ICMPv6 Echo processing is disabled.
SetEchoMode()
void SetEchoMode (otIcmp6EchoMode aMode) inline
This method sets whether or not ICMPv6 Echo processing is enabled.
Parameters
[in] aEnabled TRUE to enable ICMPv6 Echo processing, FALSE otherwise.
ShouldHandleEchoRequest()
bool ShouldHandleEchoRequest (const MessageInfo & aMessageInfo)
This method indicates whether or not the ICMPv6 Echo Request should be handled.
Return values
TRUE if OpenThread should respond with an ICMPv6 Echo Reply.
FALSE if OpenThread should not respond with an ICMPv6 Echo Reply.
References MessageInfo::GetSockAddr(), Address::IsMulticast(), Icmp::mEchoMode, OT_ICMP6_ECHO_HANDLER_ALL, OT_ICMP6_ECHO_HANDLER_DISABLED, OT_ICMP6_ECHO_HANDLER_MULTICAST_ONLY, and OT_ICMP6_ECHO_HANDLER_UNICAST_ONLY.
Referenced by Icmp::HandleEchoRequest(), and Ip6::ProcessReceiveCallback().
HandleEchoRequest()
otError HandleEchoRequest (Message & aRequestMessage, const MessageInfo & aMessageInfo) private
References Message::CopyTo(), ExitNow, Message::Free(), IcmpHeader::GetDataOffset(), Message::GetLength(), Message::GetOffset(), MessageInfo::GetPeerAddr(), IcmpHeader::GetSequence(), MessageInfo::GetSockAddr(), IcmpHeader::Init(), Address::IsIidLocator(), Address::IsMulticast(), ot::Ip6::kProtoIcmp6, IcmpHeader::kTypeEchoReply, Icmp::NewMessage(), OT_ERROR_NONE, OT_NOOP, otLogDebgIcmp, otLogInfoIcmp, Message::Read(), Message::SetLength(), MessageInfo::SetPeerAddr(), MessageInfo::SetSockAddr(), IcmpHeader::SetType(), Icmp::ShouldHandleEchoRequest(), SuccessOrExit, VerifyOrExit, and Message::Write().
Referenced by Icmp::HandleMessage().
Field Documentation
mHandlers
LinkedList<IcmpHandler> mHandlers private
Referenced by Icmp::HandleMessage(), and Icmp::RegisterHandler().
mEchoSequence
uint16_t mEchoSequence private
Referenced by Icmp::SendEchoRequest().
mEchoMode
otIcmp6EchoMode mEchoMode private
Referenced by Icmp::ShouldHandleEchoRequest().
The documentation for this class was generated from the following files:
icmp6.hpp
icmp6.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale