OpenThread: RandomManager Class Reference
RandomManager Class Reference
#include <random_manager.hpp>
Data Structures
class CryptoCtrDrbg
class Entropy
class NonCryptoPrng
Public Member Functions
RandomManager (void)
~RandomManager (void)
Static Public Member Functions
static otError CryptoFillBuffer (uint8_t *aBuffer, uint16_t aSize)
static mbedtls_ctr_drbg_context * GetMbedTlsCtrDrbgContext (void)
static mbedtls_entropy_context * GetMbedTlsEntropyContext (void)
static uint32_t NonCryptoGetUint32 (void)
Static Private Attributes
static CryptoCtrDrbg sCtrDrbg
static Entropy sEntropy
static uint16_t sInitCount = 0
static NonCryptoPrng sPrng
Detailed Description
This class manages random number generator initialization/deinitialization.
Constructor & Destructor Documentation
RandomManager()
RandomManager (void)
This constructor initializes the object.
References ot::Random::Crypto::FillBuffer(), RandomManager::NonCryptoPrng::Init(), RandomManager::Entropy::Init(), RandomManager::CryptoCtrDrbg::Init(), OT_ASSERT, OT_ERROR_NONE, OT_NOOP, OT_UNUSED_VARIABLE, otPlatEntropyGet(), RandomManager::sCtrDrbg, RandomManager::sEntropy, RandomManager::sInitCount, RandomManager::sPrng, and VerifyOrExit.
~RandomManager()
~RandomManager (void)
This destructor deinitializes the object.
References RandomManager::Entropy::Deinit(), RandomManager::CryptoCtrDrbg::Deinit(), OT_ASSERT, OT_NOOP, RandomManager::sCtrDrbg, RandomManager::sEntropy, RandomManager::sInitCount, and VerifyOrExit.
Member Function Documentation
NonCryptoGetUint32()
uint32_t NonCryptoGetUint32 (void) static
This static method generates and returns a random value using a non-crypto Pseudo Random Number Generator.
Returns
A random uint32_t value.
References RandomManager::NonCryptoPrng::GetNext(), OT_ASSERT, RandomManager::sInitCount, and RandomManager::sPrng.
Referenced by ot::Random::NonCrypto::GetUint32().
GetMbedTlsEntropyContext()
static mbedtls_entropy_context* GetMbedTlsEntropyContext (void) inline static
This static method returns the initialized mbedtls_entropy_context.
Returns
A pointer to initialized mbedtls_entropy_context.
References RandomManager::Entropy::GetContext(), and RandomManager::sEntropy.
Referenced by RandomManager::CryptoCtrDrbg::Init(), and otEntropyMbedTlsContextGet().
CryptoFillBuffer()
static otError CryptoFillBuffer (uint8_t * aBuffer, uint16_t aSize) inline static
This static method fills a given buffer with cryptographically secure random bytes.
Parameters
[out] aBuffer A pointer to a buffer to fill with the random bytes.
[in] aSize Size of buffer (number of bytes to fill).
Return values
OT_ERROR_NONE Successfully filled buffer with random values.
References RandomManager::CryptoCtrDrbg::FillBuffer(), and RandomManager::sCtrDrbg.
Referenced by ot::Random::Crypto::FillBuffer().
GetMbedTlsCtrDrbgContext()
static mbedtls_ctr_drbg_context* GetMbedTlsCtrDrbgContext (void) inline static
This static method returns the initialized mbedtls_ctr_drbg_context.
Returns
A pointer to the initialized mbedtls_ctr_drbg_context.
References RandomManager::CryptoCtrDrbg::GetContext(), and RandomManager::sCtrDrbg.
Referenced by ot::Random::Crypto::MbedTlsContextGet().
Field Documentation
sInitCount
uint16_t sInitCount = 0 static private
Referenced by RandomManager::NonCryptoGetUint32(), RandomManager::RandomManager(), and RandomManager::~RandomManager().
sPrng
RandomManager::NonCryptoPrng sPrng static private
Referenced by RandomManager::NonCryptoGetUint32(), and RandomManager::RandomManager().
sEntropy
RandomManager::Entropy sEntropy static private
Referenced by RandomManager::GetMbedTlsEntropyContext(), RandomManager::RandomManager(), and RandomManager::~RandomManager().
sCtrDrbg
RandomManager::CryptoCtrDrbg sCtrDrbg static private
Referenced by RandomManager::CryptoFillBuffer(), RandomManager::GetMbedTlsCtrDrbgContext(), RandomManager::RandomManager(), and RandomManager::~RandomManager().
The documentation for this class was generated from the following files:
random_manager.hpp
random_manager.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale