OpenThread: Mac Class Reference
Mac Class Reference
Core-mac
#include <mac.hpp>
Public Member Functions
otError ActiveScan (uint32_t aScanChannels, uint16_t aScanDuration, ActiveScanHandler aHandler, void *aContext)
void ClearTemporaryChannel (void)
otError EnergyScan (uint32_t aScanChannels, uint16_t aScanDuration, EnergyScanHandler aHandler, void *aContext)
void EnergyScanDone (int8_t aEnergyScanMaxRssi)
uint16_t GetCcaFailureRate (void) const
otMacCounters & GetCounters (void)
const DomainName & GetDomainName (void) const
const ExtAddress & GetExtAddress (void) const
const ExtendedPanId & GetExtendedPanId (void) const
uint8_t GetMaxFrameRetriesDirect (void) const
const NetworkName & GetNetworkName (void) const
int8_t GetNoiseFloor (void)
uint8_t GetPanChannel (void) const
PanId GetPanId (void) const
bool GetRxOnWhenIdle (void) const
ShortAddress GetShortAddress (void) const
const ChannelMask & GetSupportedChannelMask (void) const
void HandleReceivedFrame (RxFrame *aFrame, otError aError)
void HandleTransmitDone (TxFrame &aFrame, RxFrame *aAckFrame, otError aError)
bool IsActiveScanInProgress (void) const
bool IsBeaconEnabled (void) const
bool IsEnabled (void) const
bool IsEnergyScanInProgress (void) const
bool IsInTransmitState (void) const
bool IsPromiscuous (void) const
Mac (Instance &aInstance)
void RecordCcaStatus (bool aCcaSuccess, uint8_t aChannel)
void RecordFrameTransmitStatus (const TxFrame &aFrame, const RxFrame *aAckFrame, otError aError, uint8_t aRetryCount, bool aWillRetx)
otError RequestDataPollTransmission (void)
otError RequestDirectFrameTransmission (void)
otError RequestOutOfBandFrameTransmission (otRadioFrame *aOobFrame)
void ResetCounters (void)
void SetBeaconEnabled (bool aEnabled)
otError SetDomainName (const char *aNameString)
otError SetDomainName (const NameData &aNameData)
void SetEnabled (bool aEnable)
void SetExtAddress (const ExtAddress &aExtAddress)
void SetExtendedPanId (const ExtendedPanId &aExtendedPanId)
void SetMaxFrameRetriesDirect (uint8_t aMaxFrameRetriesDirect)
otError SetNetworkName (const char *aNameString)
otError SetNetworkName (const NameData &aNameData)
otError SetPanChannel (uint8_t aChannel)
void SetPanId (PanId aPanId)
void SetPcapCallback (otLinkPcapCallback aPcapCallback, void *aCallbackContext)
void SetPromiscuous (bool aPromiscuous)
void SetRxOnWhenIdle (bool aRxOnWhenIdle)
void SetShortAddress (ShortAddress aShortAddress)
void SetSupportedChannelMask (const ChannelMask &aMask)
otError SetTemporaryChannel (uint8_t aChannel)
Public Member Functions inherited from InstanceLocator
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Private Types
enum { kInvalidRssiValue = SubMac::kInvalidRssiValue, kMaxCcaSampleCount = OPENTHREAD_CONFIG_CCA_FAILURE_RATE_AVERAGING_WINDOW, kMaxAcquisitionId = 0xffff }
enum Operation {
kOperationIdle = 0, kOperationActiveScan, kOperationEnergyScan, kOperationTransmitBeacon,
kOperationTransmitDataDirect, kOperationTransmitPoll, kOperationWaitingForData, kOperationTransmitOutOfBandFrame
}
Private Member Functions
void BeginTransmit (void)
otError ConvertBeaconToActiveScanResult (const RxFrame *aBeaconFrame, ActiveScanResult &aResult)
void FinishOperation (void)
bool HandleMacCommand (RxFrame &aFrame)
void HandleTimer (void)
bool IsJoinable (void) const
void LogBeacon (const char *aActionText, const BeaconPayload &aBeaconPayload) const
void LogFrameRxFailure (const RxFrame *aFrame, otError aError) const
void LogFrameTxFailure (const TxFrame &aFrame, otError aError, uint8_t aRetryCount, bool aWillRetx) const
void PerformActiveScan (void)
void PerformEnergyScan (void)
void PerformNextOperation (void)
void PrepareBeacon (TxFrame &aFrame)
void PrepareBeaconRequest (TxFrame &aFrame)
otError PrepareDataRequest (TxFrame &aFrame)
otError ProcessReceiveSecurity (RxFrame &aFrame, const Address &aSrcAddr, Neighbor *aNeighbor)
void ProcessTransmitSecurity (TxFrame &aFrame, bool aProcessAesCcm)
void ReportActiveScanResult (const RxFrame *aBeaconFrame)
void ReportEnergyScanResult (int8_t aRssi)
void Scan (Operation aScanOperation, uint32_t aScanChannels, uint16_t aScanDuration)
bool ShouldSendBeacon (void) const
void StartOperation (Operation aOperation)
void UpdateIdleMode (void)
otError UpdateScanChannel (void)
Static Private Member Functions
static void HandleOperationTask (Tasklet &aTasklet)
static void HandleTimer (Timer &aTimer)
static const char * OperationToString (Operation aOperation)
Private Attributes
union {
ActiveScanHandler mActiveScanHandler
EnergyScanHandler mEnergyScanHandler
};
bool mBeaconsEnabled: 1
uint8_t mBeaconSequence
uint8_t mBroadcastTransmitCount
uint16_t mCcaSampleCount
SuccessRateTracker mCcaSuccessRateTracker
otMacCounters mCounters
uint8_t mDataSequence
DomainName mDomainName
bool mEnabled: 1
ExtendedPanId mExtendedPanId
uint32_t mKeyIdMode2FrameCounter
uint8_t mMaxFrameRetriesDirect
NetworkName mNetworkName
TxFrame * mOobFrame
Operation mOperation
Tasklet mOperationTask
uint8_t mPanChannel
PanId mPanId
bool mPendingActiveScan: 1
bool mPendingEnergyScan: 1
bool mPendingTransmitBeacon: 1
bool mPendingTransmitDataDirect: 1
bool mPendingTransmitOobFrame: 1
bool mPendingTransmitPoll: 1
bool mPendingWaitingForData: 1
bool mPromiscuous: 1
uint8_t mRadioChannel
bool mRxOnWhenIdle: 1
uint8_t mScanChannel
ChannelMask mScanChannelMask
uint16_t mScanDuration
void * mScanHandlerContext
bool mShouldTxPollBeforeData: 1
SubMac mSubMac
ChannelMask mSupportedChannelMask
TimerMilli mTimer
bool mUsingTemporaryChannel: 1
Static Private Attributes
static const char sDomainNameInit [] = "Thread"
static const otExtendedPanId sExtendedPanidInit
static const otExtAddress sMode2ExtAddress
static const uint8_t sMode2Key []
static const char sNetworkNameInit [] = "OpenThread"
Friends
class ot::Instance
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Detailed Description
This class implements the IEEE 802.15.4 MAC.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
kInvalidRssiValue
kMaxCcaSampleCount
kMaxAcquisitionId
Operation
enum Operation private
Enumerator
kOperationIdle
kOperationActiveScan
kOperationEnergyScan
kOperationTransmitBeacon
kOperationTransmitDataDirect
kOperationTransmitPoll
kOperationWaitingForData
kOperationTransmitOutOfBandFrame
Constructor & Destructor Documentation
Mac()
Mac (Instance & aInstance) explicit
This constructor initializes the MAC object.
Parameters
[in] aInstance A reference to the OpenThread instance.
References ExtendedPanId::Clear(), SubMac::Enable(), ExtAddress::GenerateRandom(), Mac::GetShortAddress(), Mac::mCcaSuccessRateTracker, Mac::mExtendedPanId, Mac::mPanId, Mac::mSubMac, SuccessRateTracker::Reset(), Mac::ResetCounters(), Mac::sDomainNameInit, Mac::SetDomainName(), Mac::SetEnabled(), Mac::SetExtAddress(), Mac::SetExtendedPanId(), Mac::SetNetworkName(), Mac::SetPanId(), Mac::SetShortAddress(), Mac::sExtendedPanidInit, and Mac::sNetworkNameInit.
Member Function Documentation
ActiveScan()
otError ActiveScan (uint32_t aScanChannels, uint16_t aScanDuration, ActiveScanHandler aHandler, void * aContext)
This method starts an IEEE 802.15.4 Active Scan.
Parameters
[in] aScanChannels A bit vector indicating which channels to scan. Zero is mapped to all channels.
[in] aScanDuration The time in milliseconds to spend scanning each channel. Zero duration maps to default value kScanDurationDefault = 300 ms.
[in] aHandler A pointer to a function that is called on receiving an IEEE 802.15.4 Beacon.
[in] aContext A pointer to an arbitrary context (used when invoking aHandler callback).
Return values
OT_ERROR_NONE Successfully scheduled the Active Scan request.
OT_ERROR_BUSY Could not schedule the scan (a scan is ongoing or scheduled).
References Mac::IsActiveScanInProgress(), Mac::IsEnabled(), Mac::IsEnergyScanInProgress(), Mac::kOperationActiveScan, ot::Mac::kScanDurationDefault, Mac::mActiveScanHandler, Mac::mScanHandlerContext, OT_ERROR_BUSY, OT_ERROR_INVALID_STATE, OT_ERROR_NONE, Mac::Scan(), and VerifyOrExit.
EnergyScan()
otError EnergyScan (uint32_t aScanChannels, uint16_t aScanDuration, EnergyScanHandler aHandler, void * aContext)
This method starts an IEEE 802.15.4 Energy Scan.
Parameters
[in] aScanChannels A bit vector indicating on which channels to scan. Zero is mapped to all channels.
[in] aScanDuration The time in milliseconds to spend scanning each channel. If the duration is set to zero, a single RSSI sample will be taken per channel.
[in] aHandler A pointer to a function called to pass on scan result or indicate scan completion.
[in] aContext A pointer to an arbitrary context (used when invoking aHandler callback).
Return values
OT_ERROR_NONE Accepted the Energy Scan request.
OT_ERROR_BUSY Could not start the energy scan.
References Mac::IsActiveScanInProgress(), Mac::IsEnabled(), Mac::IsEnergyScanInProgress(), Mac::kOperationEnergyScan, Mac::mEnergyScanHandler, Mac::mScanHandlerContext, OT_ERROR_BUSY, OT_ERROR_INVALID_STATE, OT_ERROR_NONE, Mac::Scan(), and VerifyOrExit.
EnergyScanDone()
void EnergyScanDone (int8_t aEnergyScanMaxRssi)
This method indicates the energy scan for the current channel is complete.
Parameters
[in] aEnergyScanMaxRssi The maximum RSSI encountered on the scanned channel.
References Mac::PerformEnergyScan(), and Mac::ReportEnergyScanResult().
IsBeaconEnabled()
bool IsBeaconEnabled (void) const inline
This method indicates whether or not IEEE 802.15.4 Beacon transmissions are enabled.
Return values
TRUE if IEEE 802.15.4 Beacon transmissions are enabled, FALSE otherwise.
References Mac::mBeaconsEnabled.
Referenced by Mac::ShouldSendBeacon().
SetBeaconEnabled()
void SetBeaconEnabled (bool aEnabled) inline
This method enables/disables IEEE 802.15.4 Beacon transmissions.
Parameters
[in] aEnabled TRUE to enable IEEE 802.15.4 Beacon transmissions, FALSE otherwise.
References Mac::mBeaconsEnabled.
GetRxOnWhenIdle()
bool GetRxOnWhenIdle (void) const inline
This method indicates whether or not rx-on-when-idle is enabled.
Return values
TRUE If rx-on-when-idle is enabled.
FALSE If rx-on-when-idle is not enabled.
References Mac::mRxOnWhenIdle, Mac::RequestDataPollTransmission(), Mac::RequestDirectFrameTransmission(), Mac::RequestOutOfBandFrameTransmission(), and Mac::SetRxOnWhenIdle().
SetRxOnWhenIdle()
void SetRxOnWhenIdle (bool aRxOnWhenIdle)
This method sets the rx-on-when-idle mode.
Parameters
[in] aRxOnWhenIdle The rx-on-when-idle mode.
References Mac::FinishOperation(), Mac::kOperationWaitingForData, Mac::mOperation, Mac::mOperationTask, Mac::mPendingWaitingForData, Mac::mPromiscuous, Mac::mRxOnWhenIdle, Mac::mSubMac, Mac::mTimer, OT_NOOP, Tasklet::Post(), SubMac::SetRxOnWhenBackoff(), TimerMilli::Stop(), Mac::UpdateIdleMode(), and VerifyOrExit.
Referenced by Mac::GetRxOnWhenIdle().
RequestDirectFrameTransmission()
otError RequestDirectFrameTransmission (void)
This method requests a direct data frame transmission.
Return values
OT_ERROR_NONE Frame transmission request is scheduled successfully.
OT_ERROR_ALREADY MAC is busy sending earlier transmission request.
OT_ERROR_INVALID_STATE The MAC layer is not enabled.
References Mac::IsEnabled(), Mac::kOperationTransmitDataDirect, Mac::mOperation, Mac::mPendingTransmitDataDirect, OT_ERROR_ALREADY, OT_ERROR_INVALID_STATE, OT_ERROR_NONE, Mac::StartOperation(), and VerifyOrExit.
Referenced by Mac::GetRxOnWhenIdle().
RequestOutOfBandFrameTransmission()
otError RequestOutOfBandFrameTransmission (otRadioFrame * aOobFrame)
This method requests an Out of Band frame for MAC Transmission.
An Out of Band frame is one that was generated outside of OpenThread.
Parameters
[in] aOobFrame A pointer to the frame.
Return values
OT_ERROR_NONE Successfully scheduled the frame transmission.
OT_ERROR_ALREADY MAC layer is busy sending a previously requested frame.
OT_ERROR_INVALID_STATE The MAC layer is not enabled.
OT_ERROR_INVALID_ARGS The argument aOobFrame is NULL.
References Mac::IsEnabled(), Mac::kOperationTransmitOutOfBandFrame, Mac::mOobFrame, Mac::mOperation, Mac::mPendingTransmitOobFrame, OT_ERROR_ALREADY, OT_ERROR_INVALID_ARGS, OT_ERROR_INVALID_STATE, OT_ERROR_NONE, Mac::StartOperation(), and VerifyOrExit.
Referenced by Mac::GetRxOnWhenIdle().
RequestDataPollTransmission()
otError RequestDataPollTransmission (void)
This method requests transmission of a data poll (MAC Data Request) frame.
Return values
OT_ERROR_NONE Data poll transmission request is scheduled successfully.
OT_ERROR_ALREADY MAC is busy sending earlier poll transmission request.
OT_ERROR_INVALID_STATE The MAC layer is not enabled.
References Mac::IsEnabled(), Mac::kOperationTransmitPoll, Mac::mOperation, Mac::mPendingTransmitDataDirect, Mac::mPendingTransmitPoll, Mac::mShouldTxPollBeforeData, OT_ERROR_ALREADY, OT_ERROR_INVALID_STATE, OT_ERROR_NONE, Mac::StartOperation(), and VerifyOrExit.
Referenced by Mac::GetRxOnWhenIdle().
GetExtAddress()
const ExtAddress& GetExtAddress (void) const inline
This method returns a reference to the IEEE 802.15.4 Extended Address.
Returns
A pointer to the IEEE 802.15.4 Extended Address.
References SubMac::GetExtAddress(), and Mac::mSubMac.
Referenced by Mac::HandleReceivedFrame(), Mac::PrepareBeacon(), Mac::PrepareDataRequest(), and Mac::ProcessTransmitSecurity().
SetExtAddress()
void SetExtAddress (const ExtAddress & aExtAddress) inline
This method sets the IEEE 802.15.4 Extended Address.
Parameters
[in] aExtAddress A reference to the IEEE 802.15.4 Extended Address.
References Mac::mSubMac, and SubMac::SetExtAddress().
Referenced by Mac::Mac().
GetShortAddress()
ShortAddress GetShortAddress (void) const inline
This method returns the IEEE 802.15.4 Short Address.
Returns
The IEEE 802.15.4 Short Address.
References SubMac::GetShortAddress(), and Mac::mSubMac.
Referenced by Mac::HandleReceivedFrame(), Mac::Mac(), and Mac::PrepareDataRequest().
SetShortAddress()
void SetShortAddress (ShortAddress aShortAddress) inline
This method sets the IEEE 802.15.4 Short Address.
Parameters
[in] aShortAddress The IEEE 802.15.4 Short Address.
References Mac::mSubMac, and SubMac::SetShortAddress().
Referenced by Mac::Mac().
GetPanChannel()
uint8_t GetPanChannel (void) const inline
This method returns the IEEE 802.15.4 PAN Channel.
Returns
The IEEE 802.15.4 PAN Channel.
References Mac::ClearTemporaryChannel(), Mac::mPanChannel, Mac::SetPanChannel(), and Mac::SetTemporaryChannel().
SetPanChannel()
otError SetPanChannel (uint8_t aChannel)
This method sets the IEEE 802.15.4 PAN Channel.
Parameters
[in] aChannel The IEEE 802.15.4 PAN Channel.
Return values
OT_ERROR_NONE Successfully set the IEEE 802.15.4 PAN Channel.
OT_ERROR_INVALID_ARGS The aChannel is not in the supported channel mask.
References ChannelMask::ContainsChannel(), Mac::mCcaSuccessRateTracker, Mac::mPanChannel, Mac::mRadioChannel, Mac::mSupportedChannelMask, Mac::mUsingTemporaryChannel, OT_CHANGED_THREAD_CHANNEL, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, OT_NOOP, SuccessRateTracker::Reset(), SuccessOrExit, Mac::UpdateIdleMode(), and VerifyOrExit.
Referenced by Dataset::ApplyConfiguration(), Mac::GetPanChannel(), and otLinkSetChannel().
SetTemporaryChannel()
otError SetTemporaryChannel (uint8_t aChannel)
This method sets the temporary IEEE 802.15.4 radio channel.
This method allows user to temporarily change the radio channel and use a different channel (during receive) instead of the PAN channel (from SetPanChannel()). A call to ClearTemporaryChannel() would clear the temporary channel and adopt the PAN channel again. The SetTemporaryChannel() can be used multiple times in row (before a call to ClearTemporaryChannel()) to change the temporary channel.
Parameters
[in] aChannel A IEEE 802.15.4 channel.
Return values
OT_ERROR_NONE Successfully set the temporary channel
OT_ERROR_INVALID_ARGS The aChannel is not in the supported channel mask.
References ChannelMask::ContainsChannel(), Mac::mRadioChannel, Mac::mSupportedChannelMask, Mac::mUsingTemporaryChannel, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, Mac::UpdateIdleMode(), and VerifyOrExit.
Referenced by Mac::GetPanChannel().
ClearTemporaryChannel()
void ClearTemporaryChannel (void)
This method clears the use of a previously set temporary channel and adopts the PAN channel.
References Mac::mPanChannel, Mac::mRadioChannel, Mac::mUsingTemporaryChannel, and Mac::UpdateIdleMode().
Referenced by Mac::GetPanChannel().
GetSupportedChannelMask()
const ChannelMask& GetSupportedChannelMask (void) const inline
This method returns the supported channel mask.
Returns
The supported channel mask.
References Mac::mSupportedChannelMask, and Mac::SetSupportedChannelMask().
Referenced by Mac::Scan(), and Mac::SetSupportedChannelMask().
SetSupportedChannelMask()
void SetSupportedChannelMask (const ChannelMask & aMask)
This method sets the supported channel mask
Parameters
[in] aMask The supported channel mask.
References Mac::GetSupportedChannelMask(), ChannelMask::Intersect(), Mac::mSupportedChannelMask, and OT_CHANGED_SUPPORTED_CHANNEL_MASK.
Referenced by Mac::GetSupportedChannelMask().
GetNetworkName()
const NetworkName& GetNetworkName (void) const inline
This method returns the IEEE 802.15.4 Network Name.
Returns
The IEEE 802.15.4 Network Name.
References Mac::mNetworkName, and Mac::SetNetworkName().
SetNetworkName() [1/2]
otError SetNetworkName (const char * aNameString)
This method sets the IEEE 802.15.4 Network Name.
Parameters
[in] aNameString A pointer to a string character array. Must be null terminated.
Return values
OT_ERROR_NONE Successfully set the IEEE 802.15.4 Network Name.
OT_ERROR_INVALID_ARGS Given name is too long.
References NetworkName::kMaxSize.
Referenced by Dataset::ApplyConfiguration(), Mac::GetNetworkName(), and Mac::Mac().
SetNetworkName() [2/2]
otError SetNetworkName (const NameData & aNameData)
This method sets the IEEE 802.15.4 Network Name.
Parameters
[in] aNameData A name data (pointer to char buffer and length).
Return values
OT_ERROR_NONE Successfully set the IEEE 802.15.4 Network Name.
OT_ERROR_INVALID_ARGS Given name is too long.
References ExitNow, Mac::mNetworkName, OT_CHANGED_THREAD_NETWORK_NAME, OT_ERROR_ALREADY, OT_ERROR_NONE, NetworkName::Set(), and SuccessOrExit.
GetDomainName()
const DomainName& GetDomainName (void) const inline
This method returns the Thread Domain Name.
Returns
The Thread Domain Name.
References Mac::mDomainName, and Mac::SetDomainName().
SetDomainName() [1/2]
otError SetDomainName (const char * aNameString)
This method sets the Thread Domain Name.
Parameters
[in] aNameString A pointer to a string character array. Must be null terminated.
Return values
OT_ERROR_NONE Successfully set the Thread Domain Name.
OT_ERROR_INVALID_ARGS Given name is too long.
References DomainName::kMaxSize.
Referenced by Mac::GetDomainName(), and Mac::Mac().
SetDomainName() [2/2]
otError SetDomainName (const NameData & aNameData)
This method sets the Thread Domain Name.
Parameters
[in] aNameData A name data (pointer to char buffer and length).
Return values
OT_ERROR_NONE Successfully set the Thread Domain Name.
OT_ERROR_INVALID_ARGS Given name is too long.
References Mac::mDomainName, OT_ERROR_ALREADY, OT_ERROR_NONE, and DomainName::Set().
GetPanId()
PanId GetPanId (void) const inline
This method returns the IEEE 802.15.4 PAN ID.
Returns
The IEEE 802.15.4 PAN ID.
References Mac::mPanId, and Mac::SetPanId().
Referenced by Mac::PrepareDataRequest().
SetPanId()
void SetPanId (PanId aPanId)
This method sets the IEEE 802.15.4 PAN ID.
Parameters
[in] aPanId The IEEE 802.15.4 PAN ID.
References Mac::mPanId, Mac::mSubMac, OT_CHANGED_THREAD_PANID, SubMac::SetPanId(), and SuccessOrExit.
Referenced by Dataset::ApplyConfiguration(), Mac::GetPanId(), and Mac::Mac().
GetExtendedPanId()
const ExtendedPanId& GetExtendedPanId (void) const inline
This method returns the IEEE 802.15.4 Extended PAN Identifier.
Returns
The IEEE 802.15.4 Extended PAN Identifier.
References Mac::mExtendedPanId, and Mac::SetExtendedPanId().
SetExtendedPanId()
void SetExtendedPanId (const ExtendedPanId & aExtendedPanId)
This method sets the IEEE 802.15.4 Extended PAN Identifier.
Parameters
[in] aExtendedPanId The IEEE 802.15.4 Extended PAN Identifier.
References Mac::mExtendedPanId, and OT_CHANGED_THREAD_EXT_PANID.
Referenced by Dataset::ApplyConfiguration(), Mac::GetExtendedPanId(), and Mac::Mac().
GetMaxFrameRetriesDirect()
uint8_t GetMaxFrameRetriesDirect (void) const inline
This method returns the maximum number of frame retries during direct transmission.
Returns
The maximum number of retries during direct transmission.
References Mac::mMaxFrameRetriesDirect.
SetMaxFrameRetriesDirect()
void SetMaxFrameRetriesDirect (uint8_t aMaxFrameRetriesDirect) inline
This method sets the maximum number of frame retries during direct transmission.
Parameters
[in] aMaxFrameRetriesDirect The maximum number of retries during direct transmission.
References Mac::HandleReceivedFrame(), Mac::HandleTransmitDone(), Mac::mMaxFrameRetriesDirect, Mac::RecordCcaStatus(), and Mac::RecordFrameTransmitStatus().
HandleReceivedFrame()
void HandleReceivedFrame (RxFrame * aFrame, otError aError)
This method is called to handle a received frame.
Parameters
[in] aFrame A pointer to the received frame, or NULL if the receive operation was aborted.
[in] aError OT_ERROR_NONE when successfully received a frame, OT_ERROR_ABORT when reception was aborted and a frame was not received.
References LinkQualityInfo::AddRss(), LinkQualityInfo::Clear(), ExitNow, Mac::FinishOperation(), Frame::GetDstAddr(), Frame::GetDstPanId(), Neighbor::GetExtAddress(), Mac::GetExtAddress(), Address::GetExtended(), Frame::GetFramePending(), Frame::GetHeader(), Frame::GetLength(), Neighbor::GetLinkInfo(), TimerMilli::GetNow(), RxFrame::GetRssi(), Frame::GetSecurityEnabled(), Address::GetShort(), Mac::GetShortAddress(), Frame::GetSrcAddr(), Neighbor::GetState(), Address::GetType(), Frame::GetType(), Mac::HandleMacCommand(), Address::IsBroadcast(), Frame::IsDataRequestCommand(), Mac::IsEnabled(), Neighbor::IsEnhancedKeepAliveSupported(), Address::IsNone(), Neighbor::IsRxOnWhenIdle(), Frame::kFcfFrameBeacon, Frame::kFcfFrameData, Frame::kFcfFrameMacCmd, Mac::kOperationActiveScan, Mac::kOperationEnergyScan, Mac::kOperationWaitingForData, ot::Mac::kShortAddrBroadcast, Neighbor::kStateChildUpdateRequest, Neighbor::kStateRestored, Neighbor::kStateValid, Address::kTypeExtended, Address::kTypeNone, Address::kTypeShort, Mac::LogFrameRxFailure(), Mac::mCounters, Mac::mOperation, Mac::mPanChannel, Mac::mPanId, Mac::mPromiscuous, otMacCounters::mRxAddressFiltered, otMacCounters::mRxBeacon, otMacCounters::mRxBroadcast, otMacCounters::mRxData, otMacCounters::mRxDestAddrFiltered, otMacCounters::mRxDuplicated, otMacCounters::mRxErrFcs, otMacCounters::mRxErrInvalidSrcAddr, otMacCounters::mRxErrNoFrame, otMacCounters::mRxErrOther, otMacCounters::mRxErrSec, otMacCounters::mRxErrUnknownNeighbor, Mac::mRxOnWhenIdle, otMacCounters::mRxOther, otMacCounters::mRxTotal, otMacCounters::mRxUnicast, Mac::mScanChannel, Mac::mTimer, OT_ERROR_ADDRESS_FILTERED, OT_ERROR_DESTINATION_ADDRESS_FILTERED, OT_ERROR_DROP, OT_ERROR_DUPLICATED, OT_ERROR_FCS, OT_ERROR_INVALID_SOURCE_ADDRESS, OT_ERROR_INVALID_STATE, OT_ERROR_NO_FRAME_RECEIVED, OT_ERROR_NONE, OT_ERROR_SECURITY, OT_ERROR_UNKNOWN_NEIGHBOR, OT_NOOP, otDumpDebgMac, otLogDebgMac, Mac::PerformNextOperation(), Mac::ProcessReceiveSecurity(), Mac::ReportActiveScanResult(), Address::SetExtended(), Neighbor::SetLastHeard(), RxFrame::SetRssi(), TimerMilli::Stop(), SuccessOrExit, Frame::ValidatePsdu(), and VerifyOrExit.
Referenced by Mac::SetMaxFrameRetriesDirect().
RecordCcaStatus()
void RecordCcaStatus (bool aCcaSuccess, uint8_t aChannel)
This method records CCA status (success/failure) for a frame transmission attempt.
Parameters
[in] aCcaSuccess TRUE if the CCA succeeded, FALSE otherwise.
[in] aChannel The channel on which CCA was performed.
References SuccessRateTracker::AddSample(), Mac::kMaxCcaSampleCount, Mac::mCcaSampleCount, Mac::mCcaSuccessRateTracker, Mac::mCounters, Mac::mPanChannel, and otMacCounters::mTxErrCca.
Referenced by Mac::SetMaxFrameRetriesDirect().
RecordFrameTransmitStatus()
void RecordFrameTransmitStatus (const TxFrame & aFrame, const RxFrame * aAckFrame, otError aError, uint8_t aRetryCount, bool aWillRetx)
This method records the status of a frame transmission attempt, updating MAC counters.
Unlike HandleTransmitDone which is called after all transmission attempts of frame to indicate final status of a frame transmission request, this method is invoked on all frame transmission attempts.
Parameters
[in] aFrame The transmitted frame.
[in] aAckFrame A pointer to the ACK frame, or NULL if no ACK was received.
[in] aError OT_ERROR_NONE when the frame was transmitted successfully, OT_ERROR_NO_ACK when the frame was transmitted but no ACK was received, OT_ERROR_CHANNEL_ACCESS_FAILURE tx failed due to activity on the channel, OT_ERROR_ABORT when transmission was aborted for other reasons.
[in] aRetryCount Indicates number of transmission retries for this frame.
[in] aWillRetx Indicates whether frame will be retransmitted or not. This is applicable only when there was an error in transmission (i.e., aError is not NONE).
References LinkQualityInfo::AddFrameTxStatus(), LinkQualityInfo::AddRss(), ExitNow, Frame::GetAckRequest(), Frame::GetDstAddr(), Frame::GetHeader(), Neighbor::GetLinkInfo(), RxFrame::GetRssi(), Address::IsBroadcast(), Frame::IsEmpty(), Mac::LogFrameTxFailure(), Mac::mCounters, otMacCounters::mTxAcked, otMacCounters::mTxAckRequested, otMacCounters::mTxBroadcast, otMacCounters::mTxErrAbort, otMacCounters::mTxErrBusyChannel, otMacCounters::mTxNoAckRequested, otMacCounters::mTxRetry, otMacCounters::mTxTotal, otMacCounters::mTxUnicast, OT_ERROR_ABORT, OT_ERROR_CHANNEL_ACCESS_FAILURE, OT_ERROR_NO_ACK, OT_ERROR_NONE, OT_NOOP, otDumpDebgMac, and VerifyOrExit.
Referenced by Mac::SetMaxFrameRetriesDirect().
HandleTransmitDone()
void HandleTransmitDone (TxFrame & aFrame, RxFrame * aAckFrame, otError aError)
This method is called to handle transmit events.
Parameters
[in] aFrame The frame that was transmitted.
[in] aAckFrame A pointer to the ACK frame, NULL if no ACK was received.
[in] aError OT_ERROR_NONE when the frame was transmitted successfully, OT_ERROR_NO_ACK when the frame was transmitted but no ACK was received, OT_ERROR_CHANNEL_ACCESS_FAILURE when the tx failed due to activity on the channel, OT_ERROR_ABORT when transmission was aborted for other reasons.
References ExitNow, Mac::FinishOperation(), Frame::GetAckRequest(), Frame::GetDstAddr(), Frame::GetFramePending(), Frame::GetHeader(), Frame::GetLength(), Frame::GetSecurityEnabled(), SubMac::GetTransmitRetries(), Address::IsBroadcast(), Frame::IsEmpty(), Mac::IsEnabled(), ot::Mac::kDataPollTimeout, Mac::kOperationActiveScan, Mac::kOperationTransmitBeacon, Mac::kOperationTransmitDataDirect, Mac::kOperationTransmitOutOfBandFrame, Mac::kOperationTransmitPoll, Mac::kOperationWaitingForData, ot::Mac::kTxNumBcast, Mac::mBroadcastTransmitCount, Mac::mCounters, Mac::mOperation, Mac::mScanDuration, Mac::mSubMac, Mac::mTimer, otMacCounters::mTxBeacon, otMacCounters::mTxBeaconRequest, otMacCounters::mTxData, otMacCounters::mTxDataPoll, otMacCounters::mTxDirectMaxRetryExpiry, otMacCounters::mTxIndirectMaxRetryExpiry, OPENTHREAD_CONFIG_MAC_RETRY_SUCCESS_HISTOGRAM_MAX_SIZE_COUNT_DIRECT, OPENTHREAD_CONFIG_MAC_RETRY_SUCCESS_HISTOGRAM_MAX_SIZE_COUNT_INDIRECT, OT_ASSERT, OT_ERROR_NONE, OT_UNREACHABLE_CODE, otDumpDebgMac, otLogInfoMac, Mac::PerformNextOperation(), SubMac::Send(), TimerMilli::Start(), and Mac::StartOperation().
Referenced by Mac::BeginTransmit(), and Mac::SetMaxFrameRetriesDirect().
IsActiveScanInProgress()
bool IsActiveScanInProgress (void) const inline
This method returns if an active scan is in progress.
References Mac::kOperationActiveScan, Mac::mOperation, and Mac::mPendingActiveScan.
Referenced by Mac::ActiveScan(), and Mac::EnergyScan().
IsEnergyScanInProgress()
bool IsEnergyScanInProgress (void) const inline
This method returns if an energy scan is in progress.
References Mac::IsInTransmitState(), Mac::kOperationEnergyScan, Mac::mOperation, and Mac::mPendingEnergyScan.
Referenced by Mac::ActiveScan(), and Mac::EnergyScan().
IsInTransmitState()
bool IsInTransmitState (void) const
This method returns if the MAC layer is in transmit state.
The MAC layer is in transmit state during CSMA/CA, CCA, transmission of Data, Beacon or Data Request frames and receiving of ACK frames. The MAC layer is not in transmit state during transmission of ACK frames or Beacon Requests.
References Mac::kOperationActiveScan, Mac::kOperationEnergyScan, Mac::kOperationIdle, Mac::kOperationTransmitBeacon, Mac::kOperationTransmitDataDirect, Mac::kOperationTransmitOutOfBandFrame, Mac::kOperationTransmitPoll, Mac::kOperationWaitingForData, and Mac::mOperation.
Referenced by Mac::IsEnergyScanInProgress().
SetPcapCallback()
void SetPcapCallback (otLinkPcapCallback aPcapCallback, void * aCallbackContext) inline
This method registers a callback to provide received raw IEEE 802.15.4 frames.
Parameters
[in] aPcapCallback A pointer to a function that is called when receiving an IEEE 802.15.4 link frame or NULL to disable the callback.
[in] aCallbackContext A pointer to application-specific context.
References Mac::mSubMac, and SubMac::SetPcapCallback().
IsPromiscuous()
bool IsPromiscuous (void) const inline
This method indicates whether or not promiscuous mode is enabled at the link layer.
Return values
true Promiscuous mode is enabled.
false Promiscuous mode is not enabled.
References Mac::mPromiscuous, and Mac::SetPromiscuous().
SetPromiscuous()
void SetPromiscuous (bool aPromiscuous)
This method enables or disables the link layer promiscuous mode.
Promiscuous mode keeps the receiver enabled, overriding the value of mRxOnWhenIdle.
Parameters
[in] aPromiscuous true to enable promiscuous mode, or false otherwise.
References String< SIZE >::AsCString(), TxFrame::GetMaxFrameRetries(), Mac::kOperationActiveScan, Mac::kOperationEnergyScan, Mac::kOperationIdle, Mac::kOperationTransmitBeacon, Mac::kOperationTransmitDataDirect, Mac::kOperationTransmitOutOfBandFrame, Mac::kOperationTransmitPoll, Mac::kOperationWaitingForData, Mac::LogBeacon(), Mac::LogFrameRxFailure(), Mac::LogFrameTxFailure(), Mac::mMaxFrameRetriesDirect, Mac::mPromiscuous, Mac::mRxOnWhenIdle, Mac::mSubMac, OPENTHREAD_CONFIG_MAC_RETRY_SUCCESS_HISTOGRAM_MAX_SIZE_COUNT_DIRECT, OPENTHREAD_CONFIG_MAC_RETRY_SUCCESS_HISTOGRAM_MAX_SIZE_COUNT_INDIRECT, Mac::OperationToString(), OT_ERROR_ABORT, OT_ERROR_DESTINATION_ADDRESS_FILTERED, OT_ERROR_NO_FRAME_RECEIVED, OT_LOG_LEVEL_DEBG, OT_LOG_LEVEL_INFO, otLogInfoMac, otLogMac, otThreadErrorToString(), SubMac::SetRxOnWhenBackoff(), Frame::ToInfoString(), BeaconPayload::ToInfoString(), and Mac::UpdateIdleMode().
Referenced by Mac::IsPromiscuous().
ResetCounters()
void ResetCounters (void) inline
This method resets mac counters
References Mac::mCounters.
Referenced by Mac::Mac().
GetCounters()
otMacCounters& GetCounters (void) inline
This method returns the MAC counter.
Returns
A reference to the MAC counter.
References Mac::mCounters.
GetNoiseFloor()
int8_t GetNoiseFloor (void) inline
This method returns the noise floor value (currently use the radio receive sensitivity value).
Returns
The noise floor value in dBm.
References SubMac::GetNoiseFloor(), and Mac::mSubMac.
Referenced by otLinkSetMaxFrameRetriesDirect().
GetCcaFailureRate()
uint16_t GetCcaFailureRate (void) const inline
This method returns the current CCA (Clear Channel Assessment) failure rate.
The rate is maintained over a window of (roughly) last OPENTHREAD_CONFIG_CCA_FAILURE_RATE_AVERAGING_WINDOW frame transmissions.
Returns
The CCA failure rate with maximum value 0xffff corresponding to 100% failure rate.
References SuccessRateTracker::GetFailureRate(), and Mac::mCcaSuccessRateTracker.
SetEnabled()
void SetEnabled (bool aEnable) inline
This method Starts/Stops the Link layer. It may only be used when the Netif Interface is down.
Parameters
[in] aEnable The requested State for the MAC layer. true - Start, false - Stop.
References Mac::mEnabled.
Referenced by Mac::Mac().
IsEnabled()
bool IsEnabled (void) const inline
This method indicates whether or not the link layer is enabled.
Return values
true Link layer is enabled.
false Link layer is not enabled.
References Mac::mEnabled.
Referenced by Mac::ActiveScan(), Mac::BeginTransmit(), Mac::EnergyScan(), Mac::HandleReceivedFrame(), Mac::HandleTransmitDone(), Mac::PerformNextOperation(), Mac::RequestDataPollTransmission(), Mac::RequestDirectFrameTransmission(), Mac::RequestOutOfBandFrameTransmission(), Mac::ShouldSendBeacon(), and Mac::UpdateScanChannel().
ProcessTransmitSecurity()
void ProcessTransmitSecurity (TxFrame & aFrame, bool aProcessAesCcm) private
This method processes transmit security on the frame which is going to be sent.
This method prepares the frame, fills Mac auxiliary header, and perform AES CCM immediately in most cases (depends on aProcessAesCcm). If aProcessAesCcm is False, it probably means that some content in the frame will be updated just before transmission, so AES CCM will be performed after that (before transmission).
Parameters
[in] aFrame A reference to the MAC frame buffer which is going to be sent.
[in] aProcessAesCcm TRUE to perform AES CCM immediately, FALSE otherwise.
References KeyManager::GetCurrentKeySequence(), KeyManager::GetCurrentMacKey(), Mac::GetExtAddress(), KeyManager::GetKek(), KeyManager::GetKekFrameCounter(), Kek::GetKey(), Frame::GetKeyIdMode(), KeyManager::GetMacFrameCounter(), Frame::GetSecurityEnabled(), KeyManager::IncrementKekFrameCounter(), KeyManager::IncrementMacFrameCounter(), TxFrame::IsARetransmission(), Frame::kKeyIdMode0, Frame::kKeyIdMode1, Frame::kKeyIdMode2, Mac::mKeyIdMode2FrameCounter, OT_ASSERT, OT_NOOP, OT_UNREACHABLE_CODE, TxFrame::ProcessTransmitAesCcm(), TxFrame::SetAesKey(), Frame::SetFrameCounter(), Frame::SetKeyId(), Frame::SetKeySource(), Mac::sMode2ExtAddress, Mac::sMode2Key, and VerifyOrExit.
Referenced by Mac::BeginTransmit().
ProcessReceiveSecurity()
otError ProcessReceiveSecurity (RxFrame & aFrame, const Address & aSrcAddr, Neighbor * aNeighbor) private
References ExitNow, AesCcm::Finalize(), KeyManager::GenerateNonce(), KeyManager::GetCurrentKeySequence(), KeyManager::GetCurrentMacKey(), Address::GetExtended(), Frame::GetFooter(), Frame::GetFooterLength(), Frame::GetFrameCounter(), Frame::GetHeader(), Frame::GetHeaderLength(), KeyManager::GetKek(), Kek::GetKey(), Frame::GetKeyId(), Frame::GetKeyIdMode(), Neighbor::GetKeySequence(), Neighbor::GetLinkFrameCounter(), Frame::GetPayload(), Frame::GetPayloadLength(), Frame::GetSecurityEnabled(), Frame::GetSecurityLevel(), KeyManager::GetTemporaryMacKey(), AesCcm::Header(), AesCcm::Init(), Neighbor::IsStateValid(), Frame::kFcsSize, Frame::kKeyIdMode0, Frame::kKeyIdMode1, Frame::kKeyIdMode2, Frame::kMaxMicSize, KeyManager::kNonceSize, Frame::kSecEncMic32, OT_ERROR_DUPLICATED, OT_ERROR_NONE, OT_ERROR_SECURITY, OT_NOOP, OT_RADIO_FRAME_MAX_SIZE, OT_UNREACHABLE_CODE, otLogDebgMac, AesCcm::Payload(), KeyManager::SetCurrentKeySequence(), AesCcm::SetKey(), Neighbor::SetKeySequence(), Neighbor::SetLinkFrameCounter(), Neighbor::SetMleFrameCounter(), Mac::sMode2ExtAddress, Mac::sMode2Key, SuccessOrExit, and VerifyOrExit.
Referenced by Mac::HandleReceivedFrame().
UpdateIdleMode()
void UpdateIdleMode (void) private
References Mac::kOperationIdle, ot::Mac::kSleepDelay, Mac::mOperation, Mac::mPromiscuous, Mac::mRadioChannel, Mac::mRxOnWhenIdle, Mac::mSubMac, Mac::mTimer, OT_NOOP, otLogDebgMac, SubMac::Receive(), SubMac::Sleep(), TimerMilli::Start(), and VerifyOrExit.
Referenced by Mac::ClearTemporaryChannel(), Mac::HandleTimer(), Mac::PerformNextOperation(), Mac::SetPanChannel(), Mac::SetPromiscuous(), Mac::SetRxOnWhenIdle(), and Mac::SetTemporaryChannel().
StartOperation()
void StartOperation (Operation aOperation) private
References Mac::kOperationActiveScan, Mac::kOperationEnergyScan, Mac::kOperationIdle, Mac::kOperationTransmitBeacon, Mac::kOperationTransmitDataDirect, Mac::kOperationTransmitOutOfBandFrame, Mac::kOperationTransmitPoll, Mac::kOperationWaitingForData, Mac::mOperation, Mac::mOperationTask, Mac::mPendingActiveScan, Mac::mPendingEnergyScan, Mac::mPendingTransmitBeacon, Mac::mPendingTransmitDataDirect, Mac::mPendingTransmitOobFrame, Mac::mPendingTransmitPoll, Mac::mPendingWaitingForData, Mac::mTimer, Mac::OperationToString(), otLogDebgMac, Tasklet::Post(), and TimerMilli::Stop().
Referenced by Mac::HandleMacCommand(), Mac::HandleTransmitDone(), Mac::RequestDataPollTransmission(), Mac::RequestDirectFrameTransmission(), Mac::RequestOutOfBandFrameTransmission(), and Mac::Scan().
FinishOperation()
void FinishOperation (void) private
References Mac::kOperationIdle, Mac::mOperation, Mac::OperationToString(), and otLogDebgMac.
Referenced by Mac::HandleReceivedFrame(), Mac::HandleTimer(), Mac::HandleTransmitDone(), Mac::PerformActiveScan(), Mac::PerformEnergyScan(), and Mac::SetRxOnWhenIdle().
PerformNextOperation()
void PerformNextOperation (void) private
References Mac::BeginTransmit(), ExitNow, Mac::IsEnabled(), Mac::kOperationActiveScan, Mac::kOperationEnergyScan, Mac::kOperationIdle, Mac::kOperationTransmitBeacon, Mac::kOperationTransmitDataDirect, Mac::kOperationTransmitOutOfBandFrame, Mac::kOperationTransmitPoll, Mac::kOperationWaitingForData, Mac::mOperation, Mac::mPendingActiveScan, Mac::mPendingEnergyScan, Mac::mPendingTransmitBeacon, Mac::mPendingTransmitDataDirect, Mac::mPendingTransmitOobFrame, Mac::mPendingTransmitPoll, Mac::mPendingWaitingForData, Mac::mRadioChannel, Mac::mShouldTxPollBeforeData, Mac::mSubMac, Mac::mTimer, Mac::OperationToString(), OT_NOOP, otLogDebgMac, Mac::PerformActiveScan(), Mac::PerformEnergyScan(), SubMac::Receive(), TimerMilli::Stop(), Mac::UpdateIdleMode(), and VerifyOrExit.
Referenced by Mac::HandleOperationTask(), Mac::HandleReceivedFrame(), Mac::HandleTimer(), Mac::HandleTransmitDone(), Mac::PerformActiveScan(), and Mac::PerformEnergyScan().
PrepareDataRequest()
otError PrepareDataRequest (TxFrame & aFrame) private
References Mac::GetExtAddress(), Mac::GetPanId(), Mac::GetShortAddress(), Frame::InitMacHeader(), Address::IsExtended(), Address::IsNone(), Frame::kFcfAckRequest, Frame::kFcfDstAddrExt, Frame::kFcfDstAddrShort, Frame::kFcfFrameMacCmd, Frame::kFcfFrameVersion2006, Frame::kFcfPanidCompression, Frame::kFcfSecurityEnabled, Frame::kFcfSrcAddrExt, Frame::kFcfSrcAddrShort, Frame::kKeyIdMode1, Frame::kMacCmdDataRequest, Frame::kSecEncMic32, OT_ERROR_ABORT, OT_ERROR_NONE, Frame::SetCommandId(), Frame::SetDstAddr(), Frame::SetDstPanId(), Address::SetExtended(), Address::SetShort(), Frame::SetSrcAddr(), SuccessOrExit, and VerifyOrExit.
Referenced by Mac::BeginTransmit().
PrepareBeaconRequest()
void PrepareBeaconRequest (TxFrame & aFrame) private
References Frame::InitMacHeader(), Frame::kFcfDstAddrShort, Frame::kFcfFrameMacCmd, Frame::kFcfSrcAddrNone, Frame::kMacCmdBeaconRequest, Frame::kSecNone, ot::Mac::kShortAddrBroadcast, otLogInfoMac, Frame::SetCommandId(), Frame::SetDstAddr(), and Frame::SetDstPanId().
Referenced by Mac::BeginTransmit().
PrepareBeacon()
void PrepareBeacon (TxFrame & aFrame) private
References BeaconPayload::ClearJoiningPermitted(), NetworkName::GetAsData(), Mac::GetExtAddress(), Frame::GetPayload(), Beacon::GetPayload(), Beacon::Init(), BeaconPayload::Init(), Frame::InitMacHeader(), Mac::IsJoinable(), Frame::kFcfDstAddrNone, Frame::kFcfFrameBeacon, Frame::kFcfSrcAddrExt, Frame::kSecNone, Mac::LogBeacon(), Mac::mExtendedPanId, Mac::mNetworkName, Mac::mPanId, BeaconPayload::SetExtendedPanId(), BeaconPayload::SetJoiningPermitted(), BeaconPayload::SetNetworkName(), Frame::SetPayloadLength(), Frame::SetSrcAddr(), and Frame::SetSrcPanId().
Referenced by Mac::BeginTransmit().
ShouldSendBeacon()
bool ShouldSendBeacon (void) const private
References Mac::IsBeaconEnabled(), Mac::IsEnabled(), Mac::IsJoinable(), OT_NOOP, and VerifyOrExit.
Referenced by Mac::HandleMacCommand().
IsJoinable()
bool IsJoinable (void) const private
Referenced by Mac::PrepareBeacon(), and Mac::ShouldSendBeacon().
BeginTransmit()
void BeginTransmit (void) private
References TxFrame::CopyFrom(), Frame::GetFramePending(), SubMac::GetTransmitFrame(), Mac::HandleTransmitDone(), TxFrame::IsARetransmission(), Mac::IsEnabled(), ot::Mac::kMaxCsmaBackoffsDirect, ot::Mac::kMaxCsmaBackoffsIndirect, Mac::kOperationActiveScan, Mac::kOperationTransmitBeacon, Mac::kOperationTransmitDataDirect, Mac::kOperationTransmitOutOfBandFrame, Mac::kOperationTransmitPoll, ot::Mac::kPanIdBroadcast, Mac::mBeaconSequence, Mac::mBroadcastTransmitCount, Mac::mDataSequence, Mac::mMaxFrameRetriesDirect, Mac::mOobFrame, Mac::mOperation, Mac::mPromiscuous, Mac::mRadioChannel, Mac::mRxOnWhenIdle, Mac::mScanChannel, Mac::mSubMac, OT_ASSERT, OT_ERROR_ABORT, OT_ERROR_NONE, OT_UNREACHABLE_CODE, otLogDebgMac, Mac::PrepareBeacon(), Mac::PrepareBeaconRequest(), Mac::PrepareDataRequest(), Mac::ProcessTransmitSecurity(), SubMac::Send(), Frame::SetChannel(), TxFrame::SetIsARetransmission(), Frame::SetLength(), TxFrame::SetMaxCsmaBackoffs(), TxFrame::SetMaxFrameRetries(), SubMac::SetPanId(), Frame::SetSequence(), SuccessOrExit, and VerifyOrExit.
Referenced by Mac::PerformActiveScan(), and Mac::PerformNextOperation().
HandleMacCommand()
bool HandleMacCommand (RxFrame & aFrame) private
References Frame::GetCommandId(), Frame::kMacCmdBeaconRequest, Frame::kMacCmdDataRequest, Mac::kOperationTransmitBeacon, Mac::mCounters, otMacCounters::mRxBeaconRequest, otMacCounters::mRxDataPoll, otMacCounters::mRxOther, otLogInfoMac, Mac::ShouldSendBeacon(), and Mac::StartOperation().
Referenced by Mac::HandleReceivedFrame().
HandleTimer() [1/2]
void HandleTimer (Timer & aTimer) static private
References OwnerLocator::GetOwner(), and Mac::HandleTimer().
HandleTimer() [2/2]
void HandleTimer (void) private
References Mac::FinishOperation(), Mac::kOperationActiveScan, Mac::kOperationIdle, Mac::kOperationWaitingForData, Mac::mOperation, OT_ASSERT, OT_UNREACHABLE_CODE, otLogDebgMac, Mac::PerformActiveScan(), Mac::PerformNextOperation(), and Mac::UpdateIdleMode().
Referenced by Mac::HandleTimer().
HandleOperationTask()
void HandleOperationTask (Tasklet & aTasklet) static private
References OwnerLocator::GetOwner(), and Mac::PerformNextOperation().
Scan()
void Scan (Operation aScanOperation, uint32_t aScanChannels, uint16_t aScanDuration) private
References ChannelMask::GetMask(), Mac::GetSupportedChannelMask(), ChannelMask::Intersect(), ChannelMask::kChannelIteratorFirst, Mac::mScanChannel, Mac::mScanChannelMask, Mac::mScanDuration, Mac::mSupportedChannelMask, ChannelMask::SetMask(), and Mac::StartOperation().
Referenced by Mac::ActiveScan(), and Mac::EnergyScan().
UpdateScanChannel()
otError UpdateScanChannel (void) private
References ChannelMask::GetNextChannel(), Mac::IsEnabled(), Mac::mScanChannel, Mac::mScanChannelMask, OT_ERROR_ABORT, and VerifyOrExit.
Referenced by Mac::PerformActiveScan(), and Mac::PerformEnergyScan().
PerformActiveScan()
void PerformActiveScan (void) private
References Mac::BeginTransmit(), Mac::FinishOperation(), Mac::mPanId, Mac::mSubMac, OT_ERROR_NONE, Mac::PerformNextOperation(), Mac::ReportActiveScanResult(), SubMac::SetPanId(), and Mac::UpdateScanChannel().
Referenced by Mac::HandleTimer(), and Mac::PerformNextOperation().
ReportActiveScanResult()
void ReportActiveScanResult (const RxFrame * aBeaconFrame) private
References Mac::ConvertBeaconToActiveScanResult(), Mac::mActiveScanHandler, Mac::mScanHandlerContext, OT_NOOP, SuccessOrExit, and VerifyOrExit.
Referenced by Mac::HandleReceivedFrame(), and Mac::PerformActiveScan().
ConvertBeaconToActiveScanResult()
otError ConvertBeaconToActiveScanResult (const RxFrame * aBeaconFrame, ActiveScanResult & aResult) private
References Frame::GetChannel(), Address::GetExtended(), BeaconPayload::GetExtendedPanId(), RxFrame::GetLqi(), BeaconPayload::GetNetworkName(), Frame::GetPayload(), Beacon::GetPayload(), Frame::GetPayloadLength(), BeaconPayload::GetProtocolVersion(), RxFrame::GetRssi(), Frame::GetSrcAddr(), Frame::GetSrcPanId(), Frame::GetType(), Address::IsExtended(), BeaconPayload::IsJoiningPermitted(), BeaconPayload::IsNative(), Beacon::IsValid(), BeaconPayload::IsValid(), Frame::kFcfFrameBeacon, Mac::LogBeacon(), otActiveScanResult::mChannel, otActiveScanResult::mExtAddress, otActiveScanResult::mExtendedPanId, otActiveScanResult::mIsJoinable, otActiveScanResult::mIsNative, otActiveScanResult::mLqi, otActiveScanResult::mNetworkName, otActiveScanResult::mPanId, otActiveScanResult::mRssi, otActiveScanResult::mVersion, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, OT_ERROR_PARSE, SuccessOrExit, and VerifyOrExit.
Referenced by Mac::ReportActiveScanResult().
PerformEnergyScan()
void PerformEnergyScan (void) private
References SubMac::EnergyScan(), Mac::FinishOperation(), SubMac::GetRssi(), Mac::mEnergyScanHandler, Mac::mScanChannel, Mac::mScanDuration, Mac::mScanHandlerContext, Mac::mSubMac, OT_ERROR_NONE, Mac::PerformNextOperation(), SubMac::Receive(), Mac::ReportEnergyScanResult(), SuccessOrExit, and Mac::UpdateScanChannel().
Referenced by Mac::EnergyScanDone(), and Mac::PerformNextOperation().
ReportEnergyScanResult()
void ReportEnergyScanResult (int8_t aRssi) private
References Mac::kInvalidRssiValue, otEnergyScanResult::mChannel, Mac::mEnergyScanHandler, otEnergyScanResult::mMaxRssi, Mac::mScanChannel, Mac::mScanHandlerContext, OT_NOOP, and VerifyOrExit.
Referenced by Mac::EnergyScanDone(), and Mac::PerformEnergyScan().
LogFrameRxFailure()
void LogFrameRxFailure (const RxFrame * aFrame, otError aError) const private
Referenced by Mac::HandleReceivedFrame(), and Mac::SetPromiscuous().
LogFrameTxFailure()
void LogFrameTxFailure (const TxFrame & aFrame, otError aError, uint8_t aRetryCount, bool aWillRetx) const private
References Frame::GetPsdu(), OT_NOOP, and VerifyOrExit.
Referenced by Mac::RecordFrameTransmitStatus(), and Mac::SetPromiscuous().
LogBeacon()
void LogBeacon (const char * aActionText, const BeaconPayload & aBeaconPayload) const private
Referenced by Mac::ConvertBeaconToActiveScanResult(), Mac::PrepareBeacon(), and Mac::SetPromiscuous().
OperationToString()
static const char* OperationToString (Operation aOperation) static private
Referenced by Mac::FinishOperation(), Mac::PerformNextOperation(), Mac::SetPromiscuous(), and Mac::StartOperation().
Friends And Related Function Documentation
ot::Instance
friend class ot::Instance friend
Field Documentation
sMode2Key
const uint8_t sMode2Key static private
Initial value:
= {0x78, 0x58, 0x16, 0x86, 0xfd, 0xb4, 0x58, 0x0f,
                                  0xb0, 0x92, 0x54, 0x6a, 0xec, 0xbd, 0x15, 0x66}
Referenced by Mac::ProcessReceiveSecurity(), and Mac::ProcessTransmitSecurity().
sMode2ExtAddress
const otExtAddress sMode2ExtAddress static private
Initial value:
= {
    {0x35, 0x06, 0xfe, 0xb8, 0x23, 0xd4, 0x87, 0x12},
}
Referenced by Mac::ProcessReceiveSecurity(), and Mac::ProcessTransmitSecurity().
sExtendedPanidInit
const otExtendedPanId sExtendedPanidInit static private
Initial value:
= {
    {0xde, 0xad, 0x00, 0xbe, 0xef, 0x00, 0xca, 0xfe},
}
Referenced by Mac::Mac().
sNetworkNameInit
const char sNetworkNameInit = "OpenThread" static private
Referenced by Mac::Mac().
sDomainNameInit
const char sDomainNameInit = "Thread" static private
Referenced by Mac::Mac().
mEnabled
bool mEnabled private
Referenced by Mac::IsEnabled(), and Mac::SetEnabled().
mPendingActiveScan
bool mPendingActiveScan private
Referenced by Mac::IsActiveScanInProgress(), Mac::PerformNextOperation(), and Mac::StartOperation().
mPendingEnergyScan
bool mPendingEnergyScan private
Referenced by Mac::IsEnergyScanInProgress(), Mac::PerformNextOperation(), and Mac::StartOperation().
mPendingTransmitBeacon
bool mPendingTransmitBeacon private
Referenced by Mac::PerformNextOperation(), and Mac::StartOperation().
mPendingTransmitDataDirect
bool mPendingTransmitDataDirect private
Referenced by Mac::PerformNextOperation(), Mac::RequestDataPollTransmission(), Mac::RequestDirectFrameTransmission(), and Mac::StartOperation().
mPendingTransmitPoll
bool mPendingTransmitPoll private
Referenced by Mac::PerformNextOperation(), Mac::RequestDataPollTransmission(), and Mac::StartOperation().
mPendingTransmitOobFrame
bool mPendingTransmitOobFrame private
Referenced by Mac::PerformNextOperation(), Mac::RequestOutOfBandFrameTransmission(), and Mac::StartOperation().
mPendingWaitingForData
bool mPendingWaitingForData private
Referenced by Mac::PerformNextOperation(), Mac::SetRxOnWhenIdle(), and Mac::StartOperation().
mShouldTxPollBeforeData
bool mShouldTxPollBeforeData private
Referenced by Mac::PerformNextOperation(), and Mac::RequestDataPollTransmission().
mRxOnWhenIdle
bool mRxOnWhenIdle private
Referenced by Mac::BeginTransmit(), Mac::GetRxOnWhenIdle(), Mac::HandleReceivedFrame(), Mac::SetPromiscuous(), Mac::SetRxOnWhenIdle(), and Mac::UpdateIdleMode().
mPromiscuous
bool mPromiscuous private
Referenced by Mac::BeginTransmit(), Mac::HandleReceivedFrame(), Mac::IsPromiscuous(), Mac::SetPromiscuous(), Mac::SetRxOnWhenIdle(), and Mac::UpdateIdleMode().
mBeaconsEnabled
bool mBeaconsEnabled private
Referenced by Mac::IsBeaconEnabled(), and Mac::SetBeaconEnabled().
mUsingTemporaryChannel
bool mUsingTemporaryChannel private
Referenced by Mac::ClearTemporaryChannel(), Mac::SetPanChannel(), and Mac::SetTemporaryChannel().
mOperation
Operation mOperation private
Referenced by Mac::BeginTransmit(), Mac::FinishOperation(), Mac::HandleReceivedFrame(), Mac::HandleTimer(), Mac::HandleTransmitDone(), Mac::IsActiveScanInProgress(), Mac::IsEnergyScanInProgress(), Mac::IsInTransmitState(), Mac::PerformNextOperation(), Mac::RequestDataPollTransmission(), Mac::RequestDirectFrameTransmission(), Mac::RequestOutOfBandFrameTransmission(), Mac::SetRxOnWhenIdle(), Mac::StartOperation(), and Mac::UpdateIdleMode().
mBeaconSequence
uint8_t mBeaconSequence private
Referenced by Mac::BeginTransmit().
mDataSequence
uint8_t mDataSequence private
Referenced by Mac::BeginTransmit().
mBroadcastTransmitCount
uint8_t mBroadcastTransmitCount private
Referenced by Mac::BeginTransmit(), and Mac::HandleTransmitDone().
mPanId
PanId mPanId private
Referenced by Mac::GetPanId(), Mac::HandleReceivedFrame(), Mac::Mac(), Mac::PerformActiveScan(), Mac::PrepareBeacon(), and Mac::SetPanId().
mPanChannel
uint8_t mPanChannel private
Referenced by Mac::ClearTemporaryChannel(), Mac::GetPanChannel(), Mac::HandleReceivedFrame(), Mac::RecordCcaStatus(), and Mac::SetPanChannel().
mRadioChannel
uint8_t mRadioChannel private
Referenced by Mac::BeginTransmit(), Mac::ClearTemporaryChannel(), Mac::PerformNextOperation(), Mac::SetPanChannel(), Mac::SetTemporaryChannel(), and Mac::UpdateIdleMode().
mSupportedChannelMask
ChannelMask mSupportedChannelMask private
Referenced by Mac::GetSupportedChannelMask(), Mac::Scan(), Mac::SetPanChannel(), Mac::SetSupportedChannelMask(), and Mac::SetTemporaryChannel().
mExtendedPanId
ExtendedPanId mExtendedPanId private
Referenced by Mac::GetExtendedPanId(), Mac::Mac(), Mac::PrepareBeacon(), and Mac::SetExtendedPanId().
mNetworkName
NetworkName mNetworkName private
Referenced by Mac::GetNetworkName(), Mac::PrepareBeacon(), and Mac::SetNetworkName().
mDomainName
DomainName mDomainName private
Referenced by Mac::GetDomainName(), and Mac::SetDomainName().
mScanChannel
uint8_t mScanChannel private
Referenced by Mac::BeginTransmit(), Mac::HandleReceivedFrame(), Mac::PerformEnergyScan(), Mac::ReportEnergyScanResult(), Mac::Scan(), and Mac::UpdateScanChannel().
mScanDuration
uint16_t mScanDuration private
Referenced by Mac::HandleTransmitDone(), Mac::PerformEnergyScan(), and Mac::Scan().
mScanChannelMask
ChannelMask mScanChannelMask private
Referenced by Mac::Scan(), and Mac::UpdateScanChannel().
mMaxFrameRetriesDirect
uint8_t mMaxFrameRetriesDirect private
Referenced by Mac::BeginTransmit(), Mac::GetMaxFrameRetriesDirect(), Mac::SetMaxFrameRetriesDirect(), and Mac::SetPromiscuous().
mActiveScanHandler
ActiveScanHandler mActiveScanHandler
Referenced by Mac::ActiveScan(), and Mac::ReportActiveScanResult().
mEnergyScanHandler
EnergyScanHandler mEnergyScanHandler
Referenced by Mac::EnergyScan(), Mac::PerformEnergyScan(), and Mac::ReportEnergyScanResult().
@38
union { ... }
mScanHandlerContext
void* mScanHandlerContext private
Referenced by Mac::ActiveScan(), Mac::EnergyScan(), Mac::PerformEnergyScan(), Mac::ReportActiveScanResult(), and Mac::ReportEnergyScanResult().
mSubMac
SubMac mSubMac private
Referenced by Mac::BeginTransmit(), Mac::GetExtAddress(), Mac::GetNoiseFloor(), Mac::GetShortAddress(), Mac::HandleTransmitDone(), Mac::Mac(), Mac::PerformActiveScan(), Mac::PerformEnergyScan(), Mac::PerformNextOperation(), Mac::SetExtAddress(), Mac::SetPanId(), Mac::SetPcapCallback(), Mac::SetPromiscuous(), Mac::SetRxOnWhenIdle(), Mac::SetShortAddress(), and Mac::UpdateIdleMode().
mOperationTask
Tasklet mOperationTask private
Referenced by Mac::SetRxOnWhenIdle(), and Mac::StartOperation().
mTimer
TimerMilli mTimer private
Referenced by Mac::HandleReceivedFrame(), Mac::HandleTransmitDone(), Mac::PerformNextOperation(), Mac::SetRxOnWhenIdle(), Mac::StartOperation(), and Mac::UpdateIdleMode().
mOobFrame
TxFrame* mOobFrame private
Referenced by Mac::BeginTransmit(), and Mac::RequestOutOfBandFrameTransmission().
mCounters
otMacCounters mCounters private
Referenced by Mac::GetCounters(), Mac::HandleMacCommand(), Mac::HandleReceivedFrame(), Mac::HandleTransmitDone(), Mac::RecordCcaStatus(), Mac::RecordFrameTransmitStatus(), and Mac::ResetCounters().
mKeyIdMode2FrameCounter
uint32_t mKeyIdMode2FrameCounter private
Referenced by Mac::ProcessTransmitSecurity().
mCcaSuccessRateTracker
SuccessRateTracker mCcaSuccessRateTracker private
Referenced by Mac::GetCcaFailureRate(), Mac::Mac(), Mac::RecordCcaStatus(), and Mac::SetPanChannel().
mCcaSampleCount
uint16_t mCcaSampleCount private
Referenced by Mac::RecordCcaStatus().
The documentation for this class was generated from the following files:
mac.hpp
mac.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale