OpenThread: Ip6 Class Reference
Ip6 Class Reference
Core-ipv6 » IPv6
#include <ip6.hpp>
Public Types
enum {
kDefaultHopLimit = OPENTHREAD_CONFIG_IP6_HOP_LIMIT_DEFAULT, kMaxDatagramLength = OPENTHREAD_CONFIG_IP6_MAX_DATAGRAM_LENGTH, kMaxAssembledDatagramLength = OPENTHREAD_CONFIG_IP6_MAX_ASSEMBLED_DATAGRAM, kIp6ReassemblyTimeout = OPENTHREAD_CONFIG_IP6_REASSEMBLY_TIMEOUT,
kMinimalMtu = 1280, kStateUpdatePeriod = 1000
}
Public Member Functions
void EnqueueDatagram (Message &aMessage)
const PriorityQueue & GetSendQueue (void) const
otError HandleDatagram (Message &aMessage, Netif *aNetif, const void *aLinkMessageInfo, bool aFromNcpHost)
Ip6 (Instance &aInstance)
bool IsForwardingEnabled (void) const
bool IsReceiveIp6FilterEnabled (void) const
Message * NewMessage (uint16_t aReserved, const otMessageSettings *aSettings=NULL)
Message * NewMessage (const uint8_t *aData, uint16_t aDataLength, const otMessageSettings *aSettings)
const NetifUnicastAddress * SelectSourceAddress (MessageInfo &aMessageInfo)
otError SendDatagram (Message &aMessage, MessageInfo &aMessageInfo, uint8_t aIpProto)
otError SendRaw (Message &aMessage)
void SetForwardingEnabled (bool aEnable)
void SetReceiveDatagramCallback (otIp6ReceiveCallback aCallback, void *aCallbackContext)
void SetReceiveIp6FilterEnabled (bool aEnabled)
Public Member Functions inherited from InstanceLocator
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Static Public Member Functions
static uint16_t ComputePseudoheaderChecksum (const Address &aSource, const Address &aDestination, uint16_t aLength, uint8_t aProto)
static uint8_t DscpToPriority (uint8_t aDscp)
static const char * IpProtoToString (uint8_t aIpProto)
static uint8_t PriorityToDscp (uint8_t aPriority)
static uint16_t UpdateChecksum (uint16_t aChecksum, const Address &aAddress)
Private Types
enum { kDefaultIp6MessagePriority = Message::kPriorityNormal }
Private Member Functions
otError AddMplOption (Message &aMessage, Header &aHeader)
otError AddTunneledMplOption (Message &aMessage, Header &aHeader, MessageInfo &aMessageInfo)
otError FragmentDatagram (Message &aMessage, uint8_t aIpProto)
otError HandleExtensionHeaders (Message &aMessage, Netif *aNetif, MessageInfo &aMessageInfo, Header &aHeader, uint8_t &aNextHeader, bool aForward, bool aFromNcpHost, bool aReceive)
otError HandleFragment (Message &aMessage, Netif *aNetif, MessageInfo &aMessageInfo, bool aFromNcpHost)
otError HandleOptions (Message &aMessage, Header &aHeader, bool &aForward)
otError HandlePayload (Message &aMessage, MessageInfo &aMessageInfo, uint8_t aIpProto)
void HandleSendQueue (void)
otError InsertMplOption (Message &aMessage, Header &aHeader, MessageInfo &aMessageInfo)
bool IsOnLink (const Address &aAddress) const
otError ProcessReceiveCallback (const Message &aMessage, const MessageInfo &aMessageInfo, uint8_t aIpProto, bool aFromNcpHost)
otError RemoveMplOption (Message &aMessage)
bool ShouldForwardToThread (const MessageInfo &aMessageInfo) const
Static Private Member Functions
static otError GetDatagramPriority (const uint8_t *aData, uint16_t aDataLen, uint8_t &aPriority)
static void HandleSendQueue (Tasklet &aTasklet)
Private Attributes
bool mForwardingEnabled
Icmp mIcmp
bool mIsReceiveIp6FilterEnabled
Mpl mMpl
otIp6ReceiveCallback mReceiveIp6DatagramCallback
void * mReceiveIp6DatagramCallbackContext
PriorityQueue mSendQueue
Tasklet mSendQueueTask
Udp mUdp
Friends
class ot::Instance
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Detailed Description
This class implements the core IPv6 message processing.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
kDefaultHopLimit
kMaxDatagramLength
kMaxAssembledDatagramLength
kIp6ReassemblyTimeout
kMinimalMtu
kStateUpdatePeriod
anonymous enum
anonymous enum private
Enumerator
kDefaultIp6MessagePriority
Constructor & Destructor Documentation
Ip6()
Ip6 (Instance & aInstance) explicit
This constructor initializes the object.
Parameters
[in] aInstance A reference to the otInstance object.
Member Function Documentation
NewMessage() [1/2]
Message * NewMessage (uint16_t aReserved, const otMessageSettings * aSettings = NULL)
This method allocates a new message buffer from the buffer pool.
Note
If aSettings is 'NULL', the link layer security is enabled and the message priority is set to OT_MESSAGE_PRIORITY_NORMAL by default.
Parameters
[in] aReserved The number of header bytes to reserve following the IPv6 header.
[in] aSettings A pointer to the message settings or NULL to set default settings.
Returns
A pointer to the message or NULL if insufficient message buffers are available.
References Message::kTypeIp6.
Referenced by Ip6::HandleOptions(), and otIp6NewMessageFromBuffer().
NewMessage() [2/2]
Message * NewMessage (const uint8_t * aData, uint16_t aDataLength, const otMessageSettings * aSettings)
This method allocates a new message buffer from the buffer pool and writes the IPv6 datagram to the message.
Note
If aSettings is NULL, the link layer security is enabled and the message priority is obtained from IPv6 message itself. If aSettings is not NULL, the aSetting->mPriority is ignored and obtained from IPv6 message itself.
Parameters
[in] aData A pointer to the IPv6 datagram buffer.
[in] aDataLength The size of the IPV6 datagram buffer pointed by aData.
[in] aSettings A pointer to the message settings or NULL to set default settings.
Returns
A pointer to the message or NULL if malformed IPv6 header or insufficient message buffers are available.
References Message::Append(), Message::Free(), Ip6::GetDatagramPriority(), Message::kTypeIp6, otMessageSettings::mPriority, OT_ERROR_NONE, OT_MESSAGE_PRIORITY_NORMAL, OT_NOOP, SuccessOrExit, and VerifyOrExit.
PriorityToDscp()
uint8_t PriorityToDscp (uint8_t aPriority) static
This method converts the message priority level to IPv6 DSCP value.
Parameters
[in] aPriority The message priority level.
Returns
The IPv6 DSCP value.
References ot::Ip6::kDscpCs0, ot::Ip6::kDscpCs1, ot::Ip6::kDscpCs4, Message::kPriorityHigh, Message::kPriorityLow, and Message::kPriorityNormal.
Referenced by Ip6::SendDatagram().
DscpToPriority()
uint8_t DscpToPriority (uint8_t aDscp) static
This method converts the IPv6 DSCP value to message priority level.
Parameters
[in] aDscp The IPv6 DSCP value.
Returns
The message priority level.
References ot::Ip6::kDscpCs0, ot::Ip6::kDscpCs1, ot::Ip6::kDscpCs2, ot::Ip6::kDscpCs3, ot::Ip6::kDscpCs4, ot::Ip6::kDscpCs5, ot::Ip6::kDscpCs6, ot::Ip6::kDscpCs7, ot::Ip6::kDscpCsMask, Message::kPriorityHigh, Message::kPriorityLow, and Message::kPriorityNormal.
Referenced by Ip6::GetDatagramPriority(), and MeshForwarder::GetFramePriority().
SendDatagram()
otError SendDatagram (Message & aMessage, MessageInfo & aMessageInfo, uint8_t aIpProto)
This method sends an IPv6 datagram.
Parameters
[in] aMessage A reference to the message.
[in] aMessageInfo A reference to the message info associated with aMessage.
[in] aIpProto The Internet Protocol value.
Return values
OT_ERROR_NONE Successfully enqueued the message into an output interface.
OT_ERROR_NO_BUFS Insufficient available buffer to add the IPv6 headers.
References Ip6::AddMplOption(), Ip6::AddTunneledMplOption(), Message::Clone(), Ip6::ComputePseudoheaderChecksum(), Ip6::EnqueueDatagram(), Ip6::FragmentDatagram(), NetifUnicastAddress::GetAddress(), Header::GetDestination(), MessageInfo::GetHopLimit(), Message::GetLength(), MessageInfo::GetPeerAddr(), Message::GetPriority(), MessageInfo::GetSockAddr(), Header::GetSource(), Header::Init(), Address::IsMulticast(), Address::IsMulticastLargerThanRealmLocal(), Address::IsRealmLocalMulticast(), Address::IsUnspecified(), Ip6::kDefaultHopLimit, Ip6::kMaxDatagramLength, ot::Ip6::kProtoIcmp6, ot::Ip6::kProtoUdp, Ip6::mIcmp, Ip6::mUdp, OT_ERROR_INVALID_SOURCE_ADDRESS, OT_ERROR_NONE, otLogInfoIp6, otLogWarnIp6, Message::Prepend(), Ip6::PriorityToDscp(), Ip6::SelectSourceAddress(), Header::SetDestination(), Header::SetDscp(), Header::SetHopLimit(), Header::SetNextHeader(), Header::SetPayloadLength(), Header::SetSource(), MessageInfo::ShouldAllowZeroHopLimit(), SuccessOrExit, Udp::UpdateChecksum(), Icmp::UpdateChecksum(), and VerifyOrExit.
SendRaw()
otError SendRaw (Message & aMessage)
This method sends a raw IPv6 datagram with a fully formed IPv6 header.
The caller transfers ownership of aMessage when making this call. OpenThread will free aMessage when processing is complete, including when a value other than OT_ERROR_NONE is returned.
Parameters
[in] aMessage A reference to the message.
Return values
OT_ERROR_NONE Successfully processed the message.
OT_ERROR_DROP Message was well-formed but not fully processed due to packet processing rules.
OT_ERROR_NO_BUFS Could not allocate necessary message buffers when processing the datagram.
OT_ERROR_NO_ROUTE No route to host.
OT_ERROR_PARSE Encountered a malformed header when processing the message.
References Message::Free(), Header::GetDestination(), Header::GetHopLimit(), Header::GetSource(), Ip6::HandleDatagram(), Header::Init(), Ip6::InsertMplOption(), Address::IsMulticast(), OT_ERROR_NONE, MessageInfo::SetHopLimit(), MessageInfo::SetLinkInfo(), MessageInfo::SetPeerAddr(), MessageInfo::SetSockAddr(), and SuccessOrExit.
HandleDatagram()
otError HandleDatagram (Message & aMessage, Netif * aNetif, const void * aLinkMessageInfo, bool aFromNcpHost)
This method processes a received IPv6 datagram.
Parameters
[in] aMessage A reference to the message.
[in] aNetif A pointer to the network interface that received the message.
[in] aLinkMessageInfo A pointer to link-specific message information.
[in] aFromNcpHost TRUE if the message was submitted by the NCP host, FALSE otherwise.
Return values
OT_ERROR_NONE Successfully processed the message.
OT_ERROR_DROP Message was well-formed but not fully processed due to packet processing rules.
OT_ERROR_NO_BUFS Could not allocate necessary message buffers when processing the datagram.
OT_ERROR_NO_ROUTE No route to host.
OT_ERROR_PARSE Encountered a malformed header when processing the message.
References String< SIZE >::AsCString(), ExitNow, Message::Free(), Header::GetDestination(), Header::GetHopLimit(), Header::GetHopLimitOffset(), Header::GetHopLimitSize(), Header::GetNextHeader(), Message::GetOffset(), Header::GetSource(), Ip6::HandleExtensionHeaders(), Ip6::HandlePayload(), ot::Encoding::BigEndian::HostSwap16(), Header::Init(), Address::IsLinkLocal(), Message::IsLinkSecurityEnabled(), Address::IsMulticast(), Address::IsMulticastLargerThanRealmLocal(), Netif::IsMulticastPromiscuousEnabled(), Netif::IsMulticastSubscribed(), ot::Ip6::kProtoIp6, ot::Ip6::kProtoTcp, ot::Ip6::kProtoUdp, Ip6::mForwardingEnabled, OT_ERROR_DROP, OT_ERROR_NONE, OT_ERROR_PARSE, otLogInfoIp6, Ip6::ProcessReceiveCallback(), Message::Read(), Message::RemoveHeader(), MessageInfo::SetHopLimit(), Header::SetHopLimit(), MessageInfo::SetLinkInfo(), Message::SetLinkSecurityEnabled(), Message::SetOffset(), MessageInfo::SetPeerAddr(), MessageInfo::SetSockAddr(), Ip6::ShouldForwardToThread(), SuccessOrExit, Address::ToString(), VerifyOrExit, and Message::Write().
Referenced by Ip6::HandleOptions(), Ip6::HandleSendQueue(), Ip6::InsertMplOption(), and Ip6::SendRaw().
EnqueueDatagram()
void EnqueueDatagram (Message & aMessage)
This methods adds a full IPv6 packet to the transmit queue.
Parameters
aMessage A reference to the message.
References PriorityQueue::Enqueue(), Ip6::mSendQueue, Ip6::mSendQueueTask, and Tasklet::Post().
Referenced by Ip6::FragmentDatagram(), Ip6::HandleOptions(), and Ip6::SendDatagram().
UpdateChecksum()
uint16_t UpdateChecksum (uint16_t aChecksum, const Address & aAddress) static
This static method updates a checksum.
Parameters
[in] aChecksum The checksum value to update.
[in] aAddress A reference to an IPv6 address.
Returns
The updated checksum.
References otIp6Address::OT_TOOL_PACKED_FIELD::m8, otIp6Address::mFields, and Message::UpdateChecksum().
Referenced by Ip6::ComputePseudoheaderChecksum().
ComputePseudoheaderChecksum()
uint16_t ComputePseudoheaderChecksum (const Address & aSource, const Address & aDestination, uint16_t aLength, uint8_t aProto) static
This static method computes the pseudoheader checksum.
Parameters
[in] aSource A reference to the IPv6 source address.
[in] aDestination A reference to the IPv6 destination address.
[in] aLength The IPv6 Payload Length value.
[in] aProto The IPv6 Next Header value.
Returns
The pseudoheader checksum.
References Ip6::UpdateChecksum(), and Message::UpdateChecksum().
Referenced by Udp::HandleMessage(), Icmp::HandleMessage(), and Ip6::SendDatagram().
SetReceiveDatagramCallback()
void SetReceiveDatagramCallback (otIp6ReceiveCallback aCallback, void * aCallbackContext)
This method registers a callback to provide received raw IPv6 datagrams.
By default, this callback does not pass Thread control traffic. See SetReceiveIp6FilterEnabled() to change the Thread control traffic filter setting.
Parameters
[in] aCallback A pointer to a function that is called when an IPv6 datagram is received or NULL to disable the callback.
[in] aCallbackContext A pointer to application-specific context.
See also
IsReceiveIp6FilterEnabled
SetReceiveIp6FilterEnabled
References Ip6::mReceiveIp6DatagramCallback, and Ip6::mReceiveIp6DatagramCallbackContext.
IsReceiveIp6FilterEnabled()
bool IsReceiveIp6FilterEnabled (void) const inline
This method indicates whether or not Thread control traffic is filtered out when delivering IPv6 datagrams via the callback specified in SetReceiveIp6DatagramCallback().
Returns
TRUE if Thread control traffic is filtered out, FALSE otherwise.
See also
SetReceiveDatagramCallback
SetReceiveIp6FilterEnabled
References Ip6::mIsReceiveIp6FilterEnabled.
SetReceiveIp6FilterEnabled()
void SetReceiveIp6FilterEnabled (bool aEnabled) inline
This method sets whether or not Thread control traffic is filtered out when delivering IPv6 datagrams via the callback specified in SetReceiveIp6DatagramCallback().
Parameters
[in] aEnabled TRUE if Thread control traffic is filtered out, FALSE otherwise.
See also
SetReceiveDatagramCallback
IsReceiveIp6FilterEnabled
References Ip6::mIsReceiveIp6FilterEnabled.
IsForwardingEnabled()
bool IsForwardingEnabled (void) const inline
This method indicates whether or not IPv6 forwarding is enabled.
Returns
TRUE if IPv6 forwarding is enabled, FALSE otherwise.
References Ip6::mForwardingEnabled.
SetForwardingEnabled()
void SetForwardingEnabled (bool aEnable) inline
This method enables/disables IPv6 forwarding.
Parameters
[in] aEnable TRUE to enable IPv6 forwarding, FALSE otherwise.
References Ip6::mForwardingEnabled, and Ip6::SelectSourceAddress().
SelectSourceAddress()
const NetifUnicastAddress * SelectSourceAddress (MessageInfo & aMessageInfo)
This method perform default source address selection.
Parameters
[in] aMessageInfo A reference to the message information.
Returns
A pointer to the selected IPv6 source address or NULL if no source address was found.
References ExitNow, LinkedListEntry< Type >::GetNext(), MessageInfo::GetPeerAddr(), NetifUnicastAddress::GetScope(), Address::GetScope(), Address::IsIidAnycastLocator(), Address::IsIidRoutingLocator(), otNetifAddress::mPreferred, otNetifAddress::mPrefixLength, and Address::PrefixMatch().
Referenced by Ip6::AddTunneledMplOption(), Ip6::SendDatagram(), and Ip6::SetForwardingEnabled().
GetSendQueue()
const PriorityQueue& GetSendQueue (void) const inline
This method returns a reference to the send queue.
Returns
A reference to the send queue.
References Ip6::IpProtoToString(), and Ip6::mSendQueue.
IpProtoToString()
const char * IpProtoToString (uint8_t aIpProto) static
This static method converts an IpProto enumeration to a string.
Returns
The string representation of an IP protocol enumeration.
References ot::Ip6::kProtoDstOpts, ot::Ip6::kProtoFragment, ot::Ip6::kProtoHopOpts, ot::Ip6::kProtoIcmp6, ot::Ip6::kProtoIp6, ot::Ip6::kProtoNone, ot::Ip6::kProtoRouting, ot::Ip6::kProtoTcp, and ot::Ip6::kProtoUdp.
Referenced by MeshForwarder::GetFramePriority(), and Ip6::GetSendQueue().
HandleSendQueue() [1/2]
void HandleSendQueue (Tasklet & aTasklet) static private
References OwnerLocator::GetOwner(), and Ip6::HandleSendQueue().
HandleSendQueue() [2/2]
void HandleSendQueue (void) private
References PriorityQueue::Dequeue(), PriorityQueue::GetHead(), Ip6::HandleDatagram(), and Ip6::mSendQueue.
Referenced by Ip6::HandleSendQueue().
GetDatagramPriority()
otError GetDatagramPriority (const uint8_t * aData, uint16_t aDataLen, uint8_t & aPriority) static private
References Ip6::DscpToPriority(), Header::GetDscp(), Header::GetPayloadLength(), Header::IsValid(), OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, OT_ERROR_PARSE, and VerifyOrExit.
Referenced by Ip6::NewMessage().
ProcessReceiveCallback()
otError ProcessReceiveCallback (const Message & aMessage, const MessageInfo & aMessageInfo, uint8_t aIpProto, bool aFromNcpHost) private
References Message::Clone(), ExitNow, UdpHeader::GetDestinationPort(), Message::GetLength(), Message::GetOffset(), MessageInfo::GetSockAddr(), IcmpHeader::GetType(), Address::IsIidAnycastServiceLocator(), Address::IsIidLocator(), Address::IsLinkLocal(), Address::IsLinkLocalMulticast(), ot::kCoapUdpPort, ot::Ip6::kProtoIcmp6, ot::Ip6::kProtoUdp, IcmpHeader::kTypeEchoRequest, ot::Mle::kUdpPort, Ip6::mIcmp, Ip6::mIsReceiveIp6FilterEnabled, Ip6::mReceiveIp6DatagramCallback, Ip6::mReceiveIp6DatagramCallbackContext, OT_ERROR_DROP, OT_ERROR_NO_BUFS, OT_ERROR_NO_ROUTE, OT_ERROR_NONE, otLogNoteIp6, otLogWarnIp6, Message::Read(), Ip6::RemoveMplOption(), Icmp::ShouldHandleEchoRequest(), and VerifyOrExit.
Referenced by Ip6::HandleDatagram().
HandleExtensionHeaders()
otError HandleExtensionHeaders (Message & aMessage, Netif * aNetif, MessageInfo & aMessageInfo, Header & aHeader, uint8_t & aNextHeader, bool aForward, bool aFromNcpHost, bool aReceive) private
References ExitNow, ExtensionHeader::GetNextHeader(), Message::GetOffset(), Ip6::HandleFragment(), Ip6::HandleOptions(), ot::Ip6::kProtoDstOpts, ot::Ip6::kProtoFragment, ot::Ip6::kProtoHopOpts, ot::Ip6::kProtoIp6, ot::Ip6::kProtoNone, ot::Ip6::kProtoRouting, OT_ERROR_DROP, OT_ERROR_NONE, OT_ERROR_PARSE, Message::Read(), SuccessOrExit, and VerifyOrExit.
Referenced by Ip6::HandleDatagram().
FragmentDatagram()
otError FragmentDatagram (Message & aMessage, uint8_t aIpProto) private
References Ip6::EnqueueDatagram(), OT_ERROR_NONE, and OT_UNUSED_VARIABLE.
Referenced by Ip6::HandleOptions(), and Ip6::SendDatagram().
HandleFragment()
otError HandleFragment (Message & aMessage, Netif * aNetif, MessageInfo & aMessageInfo, bool aFromNcpHost) private
References Message::GetOffset(), FragmentHeader::GetOffset(), FragmentHeader::IsMoreFlagSet(), Message::MoveOffset(), OT_ERROR_DROP, OT_ERROR_NONE, OT_ERROR_PARSE, OT_UNUSED_VARIABLE, Message::Read(), and VerifyOrExit.
Referenced by Ip6::HandleExtensionHeaders(), and Ip6::HandleOptions().
AddMplOption()
otError AddMplOption (Message & aMessage, Header & aHeader) private
References Header::GetNextHeader(), Header::GetPayloadLength(), Header::GetSource(), OptionMpl::GetTotalLength(), OptionPadN::GetTotalLength(), OptionPadN::Init(), Mpl::InitOption(), ot::Ip6::kProtoHopOpts, Ip6::mMpl, OT_ERROR_NONE, Message::Prepend(), ExtensionHeader::SetLength(), Header::SetNextHeader(), ExtensionHeader::SetNextHeader(), Header::SetPayloadLength(), and SuccessOrExit.
Referenced by Ip6::AddTunneledMplOption(), Ip6::InsertMplOption(), and Ip6::SendDatagram().
AddTunneledMplOption()
otError AddTunneledMplOption (Message & aMessage, Header & aHeader, MessageInfo & aMessageInfo) private
References Ip6::AddMplOption(), NetifUnicastAddress::GetAddress(), Header::GetPayloadLength(), MessageInfo::GetPeerAddr(), Header::Init(), Ip6::kDefaultHopLimit, ot::Ip6::kProtoIp6, OT_ERROR_INVALID_SOURCE_ADDRESS, OT_ERROR_NONE, Message::Prepend(), Ip6::SelectSourceAddress(), Header::SetDestination(), Header::SetHopLimit(), Header::SetNextHeader(), Header::SetPayloadLength(), Header::SetSource(), Address::SetToRealmLocalAllMplForwarders(), SuccessOrExit, and VerifyOrExit.
Referenced by Ip6::InsertMplOption(), and Ip6::SendDatagram().
InsertMplOption()
otError InsertMplOption (Message & aMessage, Header & aHeader, MessageInfo & aMessageInfo) private
References Ip6::AddMplOption(), Ip6::AddTunneledMplOption(), Message::Clone(), Message::CopyTo(), Header::GetDestination(), ExtensionHeader::GetLength(), Header::GetNextHeader(), Header::GetPayloadLength(), Address::GetScope(), Header::GetSource(), OptionMpl::GetTotalLength(), OptionPadN::GetTotalLength(), Ip6::HandleDatagram(), OptionPadN::Init(), Mpl::InitOption(), Address::IsMulticast(), Address::IsMulticastLargerThanRealmLocal(), Address::IsRealmLocalMulticast(), ot::Ip6::kProtoHopOpts, Address::kRealmLocalScope, Ip6::mMpl, OT_ERROR_NONE, OT_ERROR_PARSE, OT_NOOP, otLogInfoIp6, otLogWarnIp6, Message::Prepend(), Message::Read(), Message::RemoveHeader(), ExtensionHeader::SetLength(), Header::SetPayloadLength(), SuccessOrExit, VerifyOrExit, and Message::Write().
Referenced by Ip6::SendRaw().
RemoveMplOption()
otError RemoveMplOption (Message & aMessage) private
References Message::GetLength(), ExtensionHeader::GetLength(), OptionHeader::GetLength(), Header::GetNextHeader(), ExtensionHeader::GetNextHeader(), Header::GetPayloadLength(), OptionPadN::GetTotalLength(), OptionHeader::GetType(), OptionPadN::Init(), ot::Ip6::kProtoHopOpts, OptionMpl::kType, OptionPadN::kType, OptionPad1::kType, OT_ERROR_NONE, OT_ERROR_PARSE, OT_NOOP, Message::Read(), Message::RemoveHeader(), ExtensionHeader::SetLength(), Header::SetNextHeader(), Header::SetPayloadLength(), VerifyOrExit, and Message::Write().
Referenced by Ip6::ProcessReceiveCallback().
HandleOptions()
otError HandleOptions (Message & aMessage, Header & aHeader, bool & aForward) private
References FragmentHeader::BytesToFragmentOffset(), FragmentHeader::ClearMoreFlag(), Message::CopyTo(), Message::DecrementTimeout(), Ip6::EnqueueDatagram(), ExitNow, Ip6::FragmentDatagram(), FragmentHeader::FragmentOffsetToBytes(), Message::Free(), OptionHeader::GetAction(), Message::GetDatagramTag(), Header::GetDestination(), Header::GetHopLimit(), FragmentHeader::GetIdentification(), Message::GetLength(), ExtensionHeader::GetLength(), OptionHeader::GetLength(), Message::GetNext(), FragmentHeader::GetNextHeader(), Message::GetOffset(), FragmentHeader::GetOffset(), OwnerLocator::GetOwner(), Header::GetSource(), OptionHeader::GetType(), ot::Random::NonCrypto::GetUint32(), Ip6::HandleDatagram(), Ip6::HandleFragment(), FragmentHeader::Init(), FragmentHeader::IsMoreFlagSet(), OptionHeader::kActionDiscard, OptionHeader::kActionForceIcmp, OptionHeader::kActionIcmp, OptionHeader::kActionSkip, IcmpHeader::kCodeFragmReasTimeEx, Ip6::kIp6ReassemblyTimeout, Ip6::kMaxAssembledDatagramLength, Ip6::kMinimalMtu, ot::Ip6::kProtoFragment, Ip6::kStateUpdatePeriod, OptionMpl::kType, OptionPad1::kType, IcmpHeader::kTypeTimeExceeded, FragmentHeader::MakeDivisibleByEight(), Ip6::mIcmp, otMessageInfo::mLinkInfo, Ip6::mMpl, Message::MoveOffset(), Ip6::NewMessage(), OT_ASSERT, OT_ERROR_DROP, OT_ERROR_NO_BUFS, OT_ERROR_NONE, OT_ERROR_PARSE, OT_UNUSED_VARIABLE, otLogDebgIp6, otLogInfoIp6, otLogNoteIp6, otLogWarnIp6, otThreadErrorToString(), Mpl::ProcessOption(), Message::Read(), Icmp::SendError(), Message::SetDatagramTag(), MessageInfo::SetHopLimit(), FragmentHeader::SetIdentification(), Message::SetLength(), MessageInfo::SetLinkInfo(), FragmentHeader::SetMoreFlag(), Header::SetNextHeader(), FragmentHeader::SetNextHeader(), Message::SetOffset(), FragmentHeader::SetOffset(), Header::SetPayloadLength(), MessageInfo::SetPeerAddr(), MessageInfo::SetSockAddr(), Message::SetTimeout(), SuccessOrExit, VerifyOrExit, and Message::Write().
Referenced by Ip6::HandleExtensionHeaders().
HandlePayload()
otError HandlePayload (Message & aMessage, MessageInfo & aMessageInfo, uint8_t aIpProto) private
References ExitNow, Udp::HandleMessage(), Icmp::HandleMessage(), ot::Ip6::kProtoIcmp6, ot::Ip6::kProtoUdp, Ip6::mIcmp, Ip6::mUdp, OT_ERROR_DROP, OT_ERROR_NONE, and otLogNoteIp6.
Referenced by Ip6::HandleDatagram().
ShouldForwardToThread()
bool ShouldForwardToThread (const MessageInfo & aMessageInfo) const private
References ExitNow, MessageInfo::GetPeerAddr(), MessageInfo::GetSockAddr(), Address::IsLinkLocal(), Address::IsMulticast(), Ip6::IsOnLink(), and OT_ERROR_NONE.
Referenced by Ip6::HandleDatagram().
IsOnLink()
bool IsOnLink (const Address & aAddress) const private
References ExitNow, and LinkedListEntry< Type >::GetNext().
Referenced by Ip6::ShouldForwardToThread().
Friends And Related Function Documentation
ot::Instance
friend class ot::Instance friend
Field Documentation
mForwardingEnabled
bool mForwardingEnabled private
Referenced by Ip6::HandleDatagram(), Ip6::IsForwardingEnabled(), and Ip6::SetForwardingEnabled().
mIsReceiveIp6FilterEnabled
bool mIsReceiveIp6FilterEnabled private
Referenced by Ip6::IsReceiveIp6FilterEnabled(), Ip6::ProcessReceiveCallback(), and Ip6::SetReceiveIp6FilterEnabled().
mReceiveIp6DatagramCallback
otIp6ReceiveCallback mReceiveIp6DatagramCallback private
Referenced by Ip6::ProcessReceiveCallback(), and Ip6::SetReceiveDatagramCallback().
mReceiveIp6DatagramCallbackContext
void* mReceiveIp6DatagramCallbackContext private
Referenced by Ip6::ProcessReceiveCallback(), and Ip6::SetReceiveDatagramCallback().
mSendQueue
PriorityQueue mSendQueue private
Referenced by Ip6::EnqueueDatagram(), Ip6::GetSendQueue(), and Ip6::HandleSendQueue().
mSendQueueTask
Tasklet mSendQueueTask private
Referenced by Ip6::EnqueueDatagram().
mIcmp
Icmp mIcmp private
Referenced by Ip6::HandleOptions(), Ip6::HandlePayload(), Ip6::ProcessReceiveCallback(), and Ip6::SendDatagram().
mUdp
Udp mUdp private
Referenced by Ip6::HandlePayload(), and Ip6::SendDatagram().
mMpl
Mpl mMpl private
Referenced by Ip6::AddMplOption(), Ip6::HandleOptions(), and Ip6::InsertMplOption().
The documentation for this class was generated from the following files:
ip6.hpp
ip6.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale