OpenThread: Uart Class Reference
Uart Class Reference
#include <cli_uart.hpp>
Public Member Functions
virtual int Output (const char *aBuf, uint16_t aBufLength)
void ReceiveTask (const uint8_t *aBuf, uint16_t aBufLength)
void SendDoneTask (void)
Uart (Instance *aInstance)
Public Member Functions inherited from Server
Interpreter & GetInterpreter (void)
int OutputFormat (const char *aFormat,...)
int OutputFormatV (const char *aFormat, va_list aArguments)
Server (Instance *aInstance)
Private Types
enum { kRxBufferSize = OPENTHREAD_CONFIG_CLI_UART_RX_BUFFER_SIZE, kTxBufferSize = OPENTHREAD_CONFIG_CLI_UART_TX_BUFFER_SIZE }
Private Member Functions
otError ProcessCommand (void)
void Send (void)
Private Attributes
char mRxBuffer [kRxBufferSize]
uint16_t mRxLength
uint16_t mSendLength
char mTxBuffer [kTxBufferSize]
uint16_t mTxHead
uint16_t mTxLength
Friends
class Interpreter
Additional Inherited Members
Static Public Attributes inherited from Server
static Server * sServer = NULL
Protected Types inherited from Server
enum { kMaxLineLength = OPENTHREAD_CONFIG_CLI_MAX_LINE_LENGTH }
Protected Attributes inherited from Server
Interpreter mInterpreter
Detailed Description
This class implements the CLI server on top of the UART platform abstraction.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
kRxBufferSize
kTxBufferSize
Constructor & Destructor Documentation
Uart()
Uart (Instance * aInstance) explicit
Constructor
Parameters
[in] aInstance The OpenThread instance structure.
References Uart::mRxLength, Uart::mSendLength, Uart::mTxHead, Uart::mTxLength, and otPlatUartEnable().
Referenced by otPlatUartReceived(), and otPlatUartSendDone().
Member Function Documentation
Output()
int Output (const char * aBuf, uint16_t aBufLength) virtual
This method delivers raw characters to the client.
Parameters
[in] aBuf A pointer to a buffer.
[in] aBufLength Number of bytes in the buffer.
Returns
The number of bytes placed in the output queue.
Reimplemented from Server.
References Uart::kTxBufferSize, Uart::mTxBuffer, Uart::mTxHead, Uart::mTxLength, OT_CLI_UART_OUTPUT_LOCK, OT_CLI_UART_OUTPUT_UNLOCK, OT_ERROR_NONE, otPlatUartFlush(), Uart::Send(), and Uart::SendDoneTask().
Referenced by Uart::ReceiveTask().
ReceiveTask()
void ReceiveTask (const uint8_t * aBuf, uint16_t aBufLength)
References Uart::kRxBufferSize, Uart::mRxBuffer, Uart::mRxLength, Uart::Output(), and Uart::ProcessCommand().
Referenced by otPlatUartReceived().
SendDoneTask()
void SendDoneTask (void)
References Uart::kTxBufferSize, Uart::mSendLength, Uart::mTxHead, Uart::mTxLength, and Uart::Send().
Referenced by otPlatUartSendDone(), and Uart::Output().
ProcessCommand()
otError ProcessCommand (void) private
References Server::mInterpreter, Uart::mRxBuffer, Uart::mRxLength, OT_ERROR_NONE, and otLogInfoCli.
Referenced by Uart::ReceiveTask().
Send()
void Send (void) private
References Uart::kTxBufferSize, Uart::mSendLength, Uart::mTxBuffer, Uart::mTxHead, Uart::mTxLength, OT_NOOP, otPlatDebugUart_write_bytes(), otPlatUartSend(), and VerifyOrExit.
Referenced by Uart::Output(), and Uart::SendDoneTask().
Friends And Related Function Documentation
Interpreter
friend class Interpreter friend
Field Documentation
mRxBuffer
char mRxBuffer[kRxBufferSize] private
Referenced by Uart::ProcessCommand(), and Uart::ReceiveTask().
mRxLength
uint16_t mRxLength private
Referenced by Uart::ProcessCommand(), Uart::ReceiveTask(), and Uart::Uart().
mTxBuffer
char mTxBuffer[kTxBufferSize] private
Referenced by Uart::Output(), and Uart::Send().
mTxHead
uint16_t mTxHead private
Referenced by Uart::Output(), Uart::Send(), Uart::SendDoneTask(), and Uart::Uart().
mTxLength
uint16_t mTxLength private
Referenced by Uart::Output(), Uart::Send(), Uart::SendDoneTask(), and Uart::Uart().
mSendLength
uint16_t mSendLength private
Referenced by Uart::Send(), Uart::SendDoneTask(), and Uart::Uart().
The documentation for this class was generated from the following files:
cli_uart.hpp
cli_uart.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale