OpenThread: PriorityQueue Class Reference
PriorityQueue Class Reference
Core-message
#include <message.hpp>
Public Member Functions
otError Dequeue (Message &aMessage)
otError Enqueue (Message &aMessage)
Message * GetHead (void) const
Message * GetHeadForPriority (uint8_t aPriority) const
void GetInfo (uint16_t &aMessageCount, uint16_t &aBufferCount) const
Message * GetTail (void) const
PriorityQueue (void)
Private Member Functions
Message * FindFirstNonNullTail (uint8_t aStartPriorityLevel) const
uint8_t PrevPriority (uint8_t aPriority) const
Private Attributes
Message * mTails [Message::kNumPriorities]
Tail pointers associated with different priority levels.
Friends
class Message
class MessagePool
class MessageQueue
Detailed Description
This class implements a priority queue.
Constructor & Destructor Documentation
PriorityQueue()
PriorityQueue (void)
This constructor initializes the priority queue.
References Message::kNumPriorities.
Member Function Documentation
GetHead()
Message * GetHead (void) const
This method returns a pointer to the first message.
Returns
A pointer to the first message.
References Message::Next().
Referenced by MeshForwarder::GetDirectTransmission(), Ip6::HandleSendQueue(), and MeshForwarder::Stop().
GetHeadForPriority()
Message * GetHeadForPriority (uint8_t aPriority) const
This method returns a pointer to the first message for a given priority level.
Parameters
[in] aPriority Priority level.
Returns
A pointer to the first message with given priority level or NULL if there is no messages with this priority level.
References Message::Next(), and OT_ASSERT.
Enqueue()
otError Enqueue (Message & aMessage)
This method adds a message to the queue.
Parameters
[in] aMessage The message to add.
Return values
OT_ERROR_NONE Successfully added the message to the list.
OT_ERROR_ALREADY The message is already enqueued in a list.
References Message::GetPriority(), Message::IsInAQueue(), Message::Next(), OT_ERROR_ALREADY, OT_ERROR_NONE, Message::Prev(), Message::SetPriorityQueue(), and VerifyOrExit.
Referenced by Ip6::EnqueueDatagram(), and Message::SetPriority().
Dequeue()
otError Dequeue (Message & aMessage)
This method removes a message from the list.
Parameters
[in] aMessage The message to remove.
Return values
OT_ERROR_NONE Successfully removed the message from the list.
OT_ERROR_NOT_FOUND The message is not enqueued in a list.
References Message::GetPriority(), Message::GetPriorityQueue(), Message::Next(), OT_ERROR_NONE, OT_ERROR_NOT_FOUND, Message::Prev(), Message::SetMessageQueue(), and VerifyOrExit.
Referenced by MeshForwarder::GetDirectTransmission(), MeshForwarder::HandleDiscoverTimer(), Ip6::HandleSendQueue(), MeshForwarder::HandleSentFrame(), MeshForwarder::RemoveMessage(), Message::SetPriority(), and MeshForwarder::Stop().
GetInfo()
void GetInfo (uint16_t & aMessageCount, uint16_t & aBufferCount) const
This method returns the number of messages and buffers enqueued.
Parameters
[out] aMessageCount Returns the number of messages enqueued.
[out] aBufferCount Returns the number of buffers enqueued.
References Message::GetNext().
GetTail()
Message * GetTail (void) const
This method returns the tail of the list (last message in the list)
Returns
A pointer to the tail of the list.
Referenced by Message::GetNext().
PrevPriority()
uint8_t PrevPriority (uint8_t aPriority) const inline private
This method increases (moves forward) the given priority while ensuring to wrap from priority value kNumPriorities -1 back to 0.
Parameters
[in] aPriority A given priority level
Returns
Increased/Moved forward priority level
References Message::kNumPriorities.
FindFirstNonNullTail()
Message * FindFirstNonNullTail (uint8_t aStartPriorityLevel) const private
This private method finds the first non-NULL tail starting from the given priority level and moving forward. It wraps from priority value kNumPriorities -1 back to 0.
aStartPriorityLevel Starting priority level.
Returns
The first non-NULL tail pointer, or NULL if all the
Friends And Related Function Documentation
Message
friend class Message friend
MessageQueue
friend class MessageQueue friend
MessagePool
friend class MessagePool friend
Field Documentation
mTails
Message* mTails[Message::kNumPriorities] private
Tail pointers associated with different priority levels.
The documentation for this class was generated from the following files:
message.hpp
message.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale