OpenThread: AddressResolver::CacheEntry Class Reference
AddressResolver::CacheEntry Class Reference
Public Member Functions
bool CanEvict (void) const
void DecrementTimeout (void)
uint32_t GetLastTransactionTime (void) const
const uint8_t * GetMeshLocalIid (void) const
CacheEntry * GetNext (void)
const CacheEntry * GetNext (void) const
uint16_t GetRetryDelay (void) const
Mac::ShortAddress GetRloc16 (void) const
const Ip6::Address & GetTarget (void) const
uint16_t GetTimeout (void) const
bool HasMeshLocalIid (const uint8_t *aIid) const
void Init (Instance &aInstance)
bool IsLastTransactionTimeValid (void) const
bool IsTimeoutZero (void) const
void MarkLastTransactionTimeAsInvalid (void)
void SetCanEvict (bool aCanEvict)
void SetLastTransactionTime (uint32_t aTime)
void SetMeshLocalIid (const uint8_t *aIid)
void SetNext (CacheEntry *aEntry)
void SetRetryDelay (uint16_t aDelay)
void SetRloc16 (Mac::ShortAddress aRloc16)
void SetTarget (const Ip6::Address &aTarget)
void SetTimeout (uint16_t aTimeout)
Public Member Functions inherited from InstanceLocator
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Private Types
enum { kNoNextIndex = 0xffff, kInvalidLastTransTime = 0xffffffff }
Private Attributes
union {
struct {
uint32_t mLastTransactionTime
uint8_t mMeshLocalIid [Ip6::Address::kInterfaceIdentifierSize]
} mCached
struct {
bool mCanEvict
uint16_t mRetryDelay
uint16_t mTimeout
} mOther
} mInfo
uint16_t mNextIndex
Mac::ShortAddress mRloc16
Ip6::Address mTarget
Additional Inherited Members
Protected Member Functions inherited from InstanceLocatorInit
void Init (Instance &aInstance)
InstanceLocatorInit (void)
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
kNoNextIndex
kInvalidLastTransTime
Member Function Documentation
Init()
void Init (Instance & aInstance)
GetNext() [1/2]
CacheEntry* GetNext (void)
GetNext() [2/2]
const CacheEntry* GetNext (void) const
SetNext()
void SetNext (CacheEntry * aEntry)
GetTarget()
const Ip6::Address& GetTarget (void) const inline
References AddressResolver::CacheEntry::mTarget.
SetTarget()
void SetTarget (const Ip6::Address & aTarget) inline
References AddressResolver::CacheEntry::mTarget.
GetRloc16()
Mac::ShortAddress GetRloc16 (void) const inline
References AddressResolver::CacheEntry::mRloc16.
SetRloc16()
void SetRloc16 (Mac::ShortAddress aRloc16) inline
References AddressResolver::CacheEntry::mRloc16.
GetMeshLocalIid()
const uint8_t* GetMeshLocalIid (void) const inline
References AddressResolver::CacheEntry::HasMeshLocalIid(), AddressResolver::CacheEntry::mInfo, and AddressResolver::CacheEntry::SetMeshLocalIid().
HasMeshLocalIid()
bool HasMeshLocalIid (const uint8_t * aIid) const
Referenced by AddressResolver::CacheEntry::GetMeshLocalIid().
SetMeshLocalIid()
void SetMeshLocalIid (const uint8_t * aIid)
Referenced by AddressResolver::CacheEntry::GetMeshLocalIid().
GetLastTransactionTime()
uint32_t GetLastTransactionTime (void) const inline
References AddressResolver::CacheEntry::mInfo.
Referenced by AddressResolver::CacheEntry::IsLastTransactionTimeValid().
SetLastTransactionTime()
void SetLastTransactionTime (uint32_t aTime) inline
References AddressResolver::CacheEntry::mInfo.
Referenced by AddressResolver::CacheEntry::MarkLastTransactionTimeAsInvalid().
IsLastTransactionTimeValid()
bool IsLastTransactionTimeValid (void) const inline
References AddressResolver::CacheEntry::GetLastTransactionTime(), and AddressResolver::CacheEntry::kInvalidLastTransTime.
MarkLastTransactionTimeAsInvalid()
void MarkLastTransactionTimeAsInvalid (void) inline
References AddressResolver::CacheEntry::kInvalidLastTransTime, and AddressResolver::CacheEntry::SetLastTransactionTime().
DecrementTimeout()
void DecrementTimeout (void) inline
References AddressResolver::CacheEntry::mInfo.
IsTimeoutZero()
bool IsTimeoutZero (void) const inline
References AddressResolver::CacheEntry::mInfo.
GetTimeout()
uint16_t GetTimeout (void) const inline
References AddressResolver::CacheEntry::mInfo.
SetTimeout()
void SetTimeout (uint16_t aTimeout) inline
References AddressResolver::CacheEntry::mInfo.
GetRetryDelay()
uint16_t GetRetryDelay (void) const inline
References AddressResolver::CacheEntry::mInfo.
SetRetryDelay()
void SetRetryDelay (uint16_t aDelay) inline
References AddressResolver::CacheEntry::mInfo.
CanEvict()
bool CanEvict (void) const inline
References AddressResolver::CacheEntry::mInfo.
SetCanEvict()
void SetCanEvict (bool aCanEvict) inline
References AddressResolver::CacheEntry::mInfo.
Field Documentation
mTarget
Ip6::Address mTarget private
Referenced by AddressResolver::CacheEntry::GetTarget(), and AddressResolver::CacheEntry::SetTarget().
mRloc16
Mac::ShortAddress mRloc16 private
Referenced by AddressResolver::CacheEntry::GetRloc16(), and AddressResolver::CacheEntry::SetRloc16().
mNextIndex
uint16_t mNextIndex private
mLastTransactionTime
uint32_t mLastTransactionTime
mMeshLocalIid
uint8_t mMeshLocalIid[Ip6::Address::kInterfaceIdentifierSize]
mCached
struct { ... } mCached
mTimeout
uint16_t mTimeout
mRetryDelay
uint16_t mRetryDelay
mCanEvict
bool mCanEvict
mOther
struct { ... } mOther
mInfo
union { ... } mInfo
Referenced by AddressResolver::CacheEntry::CanEvict(), AddressResolver::CacheEntry::DecrementTimeout(), AddressResolver::CacheEntry::GetLastTransactionTime(), AddressResolver::CacheEntry::GetMeshLocalIid(), AddressResolver::CacheEntry::GetRetryDelay(), AddressResolver::CacheEntry::GetTimeout(), AddressResolver::CacheEntry::IsTimeoutZero(), AddressResolver::CacheEntry::SetCanEvict(), AddressResolver::CacheEntry::SetLastTransactionTime(), AddressResolver::CacheEntry::SetRetryDelay(), and AddressResolver::CacheEntry::SetTimeout().
The documentation for this class was generated from the following file:
address_resolver.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale