OpenThread: UdpSocket Class Reference
UdpSocket Class Reference
Core-udp
#include <udp6.hpp>
Public Member Functions
otError Bind (const SockAddr &aSockAddr)
otError Close (void)
otError Connect (const SockAddr &aSockAddr)
SockAddr & GetPeerName (void)
SockAddr & GetSockName (void)
bool IsBound (void) const
Message * NewMessage (uint16_t aReserved, const otMessageSettings *aSettings=NULL)
otError Open (otUdpReceive aHandler, void *aContext)
otError SendTo (Message &aMessage, const MessageInfo &aMessageInfo)
UdpSocket (Udp &aUdp)
Public Member Functions inherited from InstanceLocator
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Public Member Functions inherited from LinkedListEntry< UdpSocket >
const UdpSocket * GetNext (void) const
UdpSocket * GetNext (void)
void SetNext (UdpSocket *aNext)
Private Member Functions
void HandleUdpReceive (Message &aMessage, const MessageInfo &aMessageInfo)
Friends
class Udp
Additional Inherited Members
Data Fields inherited from otUdpSocket
void * mContext
A pointer to application-specific context.
void * mHandle
A handle to platform's UDP.
otUdpReceive mHandler
A function pointer to the application callback.
struct otUdpSocket * mNext
A pointer to the next UDP socket (internal use only).
otSockAddr mPeerName
The peer IPv6 socket address.
otSockAddr mSockName
The local IPv6 socket address.
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Detailed Description
This class implements a UDP/IPv6 socket.
Constructor & Destructor Documentation
UdpSocket()
UdpSocket (Udp & aUdp) explicit
This constructor initializes the object.
Parameters
[in] aUdp A reference to the UDP transport object.
References otUdpSocket::mHandle.
Member Function Documentation
NewMessage()
Message * NewMessage (uint16_t aReserved, const otMessageSettings * aSettings = NULL)
This method returns a new UDP message with sufficient header space reserved.
Note
If aSettings is 'NULL', the link layer security is enabled and the message priority is set to OT_MESSAGE_PRIORITY_NORMAL by default.
Parameters
[in] aReserved The number of header bytes to reserve after the UDP header.
[in] aSettings A pointer to the message settings or NULL to set default settings.
Returns
A pointer to the message or NULL if no buffers are available.
Referenced by Mle::NewMleMessage().
Open()
otError Open (otUdpReceive aHandler, void * aContext)
This method opens the UDP socket.
Parameters
[in] aHandler A pointer to a function that is called when receiving UDP messages.
[in] aContext A pointer to arbitrary context information.
Return values
OT_ERROR_NONE Successfully opened the socket.
OT_ERROR_ALREADY The socket is already open.
References SockAddr::Clear(), UdpSocket::GetPeerName(), UdpSocket::GetSockName(), otUdpSocket::mContext, otUdpSocket::mHandler, OT_ERROR_NONE, otPlatUdpSocket(), and SuccessOrExit.
Referenced by Mle::Enable(), otUdpOpen(), and Coap::Start().
Bind()
otError Bind (const SockAddr & aSockAddr)
This method binds the UDP socket.
Parameters
[in] aSockAddr A reference to the socket address.
Return values
OT_ERROR_NONE Successfully bound the socket.
OT_ERROR_FAILED Failed to bind UDP Socket.
References InstanceLocator::GetInstance(), UdpSocket::IsBound(), otSockAddr::mPort, otUdpSocket::mSockName, OT_ERROR_NONE, and otPlatUdpBind().
Referenced by Mle::Enable(), otUdpBind(), UdpSocket::SendTo(), and Coap::Start().
IsBound()
bool IsBound (void) const inline
This method indicates whether or not the socket is bound.
Return values
TRUE if the socket is bound (i.e. source port is non-zero).
FALSE if the socket is not bound (source port is zero).
Referenced by UdpSocket::Bind(), Coap::Send(), and UdpSocket::SendTo().
Connect()
otError Connect (const SockAddr & aSockAddr)
This method connects the UDP socket.
Parameters
[in] aSockAddr A reference to the socket address.
Return values
OT_ERROR_NONE Successfully connected the socket.
OT_ERROR_FAILED Failed to connect UDP Socket.
References InstanceLocator::GetInstance(), otUdpSocket::mPeerName, otSockAddr::mPort, otUdpSocket::mSockName, OT_ERROR_NONE, and otPlatUdpConnect().
Referenced by otUdpConnect().
Close()
otError Close (void)
This method closes the UDP socket.
Return values
OT_ERROR_NONE Successfully closed the UDP socket.
OT_ERROR_FAILED Failed to close UDP Socket.
References SockAddr::Clear(), UdpSocket::GetPeerName(), UdpSocket::GetSockName(), OT_ERROR_NONE, otPlatUdpClose(), and SuccessOrExit.
Referenced by Mle::Disable(), otUdpClose(), Coap::Start(), and Coap::Stop().
SendTo()
otError SendTo (Message & aMessage, const MessageInfo & aMessageInfo)
This method sends a UDP message.
Parameters
[in] aMessage The message to send.
[in] aMessageInfo The message info associated with aMessage.
Return values
OT_ERROR_NONE Successfully sent the UDP message.
OT_ERROR_INVALID_ARGS If no peer is specified in aMessageInfo or by connect().
OT_ERROR_NO_BUFS Insufficient available buffer to add the UDP and IPv6 headers.
References UdpSocket::Bind(), InstanceLocator::GetInstance(), MessageInfo::GetPeerAddr(), UdpSocket::GetPeerName(), MessageInfo::GetSockAddr(), UdpSocket::GetSockName(), MessageInfo::GetSockPort(), Message::GetSubType(), UdpSocket::IsBound(), Address::IsUnspecified(), ot::kCoapUdpPort, ot::Ip6::kProtoUdp, Message::kSubTypeJoinerEntrust, otMessageInfo::mPeerPort, otSockAddr::mPort, otUdpSocket::mSockName, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, otPlatUdpSend(), MessageInfo::SetPeerAddr(), MessageInfo::SetSockAddr(), MessageInfo::SetSockPort(), SuccessOrExit, and VerifyOrExit.
Referenced by otUdpSend(), Coap::Send(), and Mle::SendMessage().
GetSockName()
SockAddr& GetSockName (void) inline
This method returns the local socket address.
Returns
A reference to the local socket address.
Referenced by UdpSocket::Close(), UdpSocket::Open(), and UdpSocket::SendTo().
GetPeerName()
SockAddr& GetPeerName (void) inline
This method returns the peer's socket address.
Returns
A reference to the peer's socket address.
Referenced by UdpSocket::Close(), UdpSocket::Open(), and UdpSocket::SendTo().
HandleUdpReceive()
void HandleUdpReceive (Message & aMessage, const MessageInfo & aMessageInfo) inline private
References otUdpReceiver::mContext, and otUdpReceiver::mHandler.
Friends And Related Function Documentation
Udp
friend class Udp friend
The documentation for this class was generated from the following files:
udp6.hpp
udp6.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale