OpenThread: AesEcb Class Reference
AesEcb Class Reference
Core-security
#include <aes_ecb.hpp>
Public Types
enum { kBlockSize = 16 }
Public Member Functions
AesEcb ()
void Encrypt (const uint8_t aInput[kBlockSize], uint8_t aOutput[kBlockSize])
void SetKey (const uint8_t *aKey, uint16_t aKeyLength)
~AesEcb ()
Private Attributes
mbedtls_aes_context mContext
Detailed Description
This class implements AES ECB computation.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
kBlockSize
AES-128 block size (bytes).
Constructor & Destructor Documentation
AesEcb()
AesEcb ()
Constructor to initialize the mbedtls_aes_context.
References AesEcb::mContext.
~AesEcb()
~AesEcb ()
Destructor to free the mbedtls_aes_context.
References AesEcb::mContext.
Member Function Documentation
SetKey()
void SetKey (const uint8_t * aKey, uint16_t aKeyLength)
This method sets the key.
Parameters
[in] aKey A pointer to the key.
[in] aKeyLength The key length in bytes.
References AesEcb::mContext.
Referenced by AesCcm::SetKey().
Encrypt()
void Encrypt (const uint8_t aInput[kBlockSize], uint8_t aOutput[kBlockSize])
This method encrypts data.
Parameters
[in] aInput A pointer to the input buffer.
[out] aOutput A pointer to the output buffer.
References AesEcb::mContext.
Referenced by AesCcm::Finalize(), AesCcm::Header(), AesCcm::Init(), and AesCcm::Payload().
Field Documentation
mContext
mbedtls_aes_context mContext private
Referenced by AesEcb::AesEcb(), AesEcb::Encrypt(), AesEcb::SetKey(), and AesEcb::~AesEcb().
The documentation for this class was generated from the following files:
aes_ecb.hpp
aes_ecb.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale