OpenThread: Dataset Class Reference
Dataset Class Reference
#include <cli_dataset.hpp>
Data Structures
struct Command
Public Member Functions
Dataset (Interpreter &aInterpreter)
otError Process (uint8_t aArgsLength, char *aArgs[])
Private Member Functions
void OutputBytes (const uint8_t *aBytes, uint8_t aLength)
otError Print (otOperationalDataset &aDataset)
otError ProcessActive (uint8_t aArgsLength, char *aArgs[])
otError ProcessActiveTimestamp (uint8_t aArgsLength, char *aArgs[])
otError ProcessChannel (uint8_t aArgsLength, char *aArgs[])
otError ProcessChannelMask (uint8_t aArgsLength, char *aArgs[])
otError ProcessClear (uint8_t aArgsLength, char *aArgs[])
otError ProcessCommit (uint8_t aArgsLength, char *aArgs[])
otError ProcessDelay (uint8_t aArgsLength, char *aArgs[])
otError ProcessExtPanId (uint8_t aArgsLength, char *aArgs[])
otError ProcessHelp (uint8_t aArgsLength, char *aArgs[])
otError ProcessInit (uint8_t aArgsLength, char *aArgs[])
otError ProcessMasterKey (uint8_t aArgsLength, char *aArgs[])
otError ProcessMeshLocalPrefix (uint8_t aArgsLength, char *aArgs[])
otError ProcessMgmtGetCommand (uint8_t aArgsLength, char *aArgs[])
otError ProcessMgmtSetCommand (uint8_t aArgsLength, char *aArgs[])
otError ProcessNetworkName (uint8_t aArgsLength, char *aArgs[])
otError ProcessPanId (uint8_t aArgsLength, char *aArgs[])
otError ProcessPending (uint8_t aArgsLength, char *aArgs[])
otError ProcessPendingTimestamp (uint8_t aArgsLength, char *aArgs[])
otError ProcessPskc (uint8_t aArgsLength, char *aArgs[])
otError ProcessSecurityPolicy (uint8_t aArgsLength, char *aArgs[])
Private Attributes
Interpreter & mInterpreter
Static Private Attributes
static const Command sCommands []
static otOperationalDataset sDataset
Detailed Description
This class implements the Dataset CLI interpreter.
Constructor & Destructor Documentation
Dataset()
Dataset (Interpreter & aInterpreter) inline explicit
References Dataset::Process().
Member Function Documentation
Process()
otError Process (uint8_t aArgsLength, char * aArgs[])
This method interprets a list of CLI arguments.
Parameters
[in] aArgsLength The number of elements in aArgs.
[in] aArgs An array of command line arguments.
References ExitNow, Dataset::Command::mCommand, OT_ARRAY_LENGTH, OT_ERROR_INVALID_COMMAND, Dataset::Print(), Dataset::sCommands, and Dataset::sDataset.
Referenced by Dataset::Dataset().
OutputBytes()
void OutputBytes (const uint8_t * aBytes, uint8_t aLength) private
References Dataset::mInterpreter.
Referenced by Dataset::Print().
Print()
otError Print (otOperationalDataset & aDataset) private
References otMasterKey::m8, otNetworkName::m8, otExtendedPanId::m8, otMeshLocalPrefix::m8, otPskc::m8, otOperationalDataset::mActiveTimestamp, otOperationalDataset::mChannel, otOperationalDataset::mChannelMask, otOperationalDataset::mComponents, otOperationalDataset::mDelay, otOperationalDataset::mExtendedPanId, otSecurityPolicy::mFlags, Dataset::mInterpreter, otOperationalDatasetComponents::mIsActiveTimestampPresent, otOperationalDatasetComponents::mIsChannelMaskPresent, otOperationalDatasetComponents::mIsChannelPresent, otOperationalDatasetComponents::mIsDelayPresent, otOperationalDatasetComponents::mIsExtendedPanIdPresent, otOperationalDatasetComponents::mIsMasterKeyPresent, otOperationalDatasetComponents::mIsMeshLocalPrefixPresent, otOperationalDatasetComponents::mIsNetworkNamePresent, otOperationalDatasetComponents::mIsPanIdPresent, otOperationalDatasetComponents::mIsPendingTimestampPresent, otOperationalDatasetComponents::mIsPskcPresent, otOperationalDatasetComponents::mIsSecurityPolicyPresent, otOperationalDataset::mMasterKey, otOperationalDataset::mMeshLocalPrefix, otOperationalDataset::mNetworkName, otOperationalDataset::mPanId, otOperationalDataset::mPendingTimestamp, otOperationalDataset::mPskc, otSecurityPolicy::mRotationTime, otOperationalDataset::mSecurityPolicy, OT_ERROR_NONE, OT_SECURITY_POLICY_BEACONS, OT_SECURITY_POLICY_EXTERNAL_COMMISSIONER, OT_SECURITY_POLICY_NATIVE_COMMISSIONING, OT_SECURITY_POLICY_OBTAIN_MASTER_KEY, OT_SECURITY_POLICY_ROUTERS, and Dataset::OutputBytes().
Referenced by Dataset::Process(), Dataset::ProcessActive(), and Dataset::ProcessPending().
ProcessHelp()
otError ProcessHelp (uint8_t aArgsLength, char * aArgs[]) private
References Dataset::mInterpreter, OT_ARRAY_LENGTH, OT_ERROR_NONE, OT_UNUSED_VARIABLE, and Dataset::sCommands.
ProcessActive()
otError ProcessActive (uint8_t aArgsLength, char * aArgs[]) private
References Dataset::mInterpreter, OT_UNUSED_VARIABLE, otDatasetGetActive(), Dataset::Print(), and SuccessOrExit.
ProcessActiveTimestamp()
otError ProcessActiveTimestamp (uint8_t aArgsLength, char * aArgs[]) private
References otOperationalDataset::mActiveTimestamp, otOperationalDataset::mComponents, otOperationalDatasetComponents::mIsActiveTimestampPresent, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, Dataset::sDataset, SuccessOrExit, and VerifyOrExit.
ProcessChannel()
otError ProcessChannel (uint8_t aArgsLength, char * aArgs[]) private
References otOperationalDataset::mChannel, otOperationalDataset::mComponents, otOperationalDatasetComponents::mIsChannelPresent, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, Dataset::sDataset, SuccessOrExit, and VerifyOrExit.
ProcessChannelMask()
otError ProcessChannelMask (uint8_t aArgsLength, char * aArgs[]) private
References otOperationalDataset::mChannelMask, otOperationalDataset::mComponents, otOperationalDatasetComponents::mIsChannelMaskPresent, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, Dataset::sDataset, SuccessOrExit, and VerifyOrExit.
ProcessClear()
otError ProcessClear (uint8_t aArgsLength, char * aArgs[]) private
References OT_ERROR_NONE, OT_UNUSED_VARIABLE, and Dataset::sDataset.
ProcessCommit()
otError ProcessCommit (uint8_t aArgsLength, char * aArgs[]) private
References ExitNow, Dataset::mInterpreter, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, otDatasetSetActive(), otDatasetSetPending(), Dataset::sDataset, SuccessOrExit, and VerifyOrExit.
ProcessDelay()
otError ProcessDelay (uint8_t aArgsLength, char * aArgs[]) private
References otOperationalDataset::mComponents, otOperationalDataset::mDelay, otOperationalDatasetComponents::mIsDelayPresent, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, Dataset::sDataset, SuccessOrExit, and VerifyOrExit.
ProcessExtPanId()
otError ProcessExtPanId (uint8_t aArgsLength, char * aArgs[]) private
References otExtendedPanId::m8, otOperationalDataset::mComponents, otOperationalDataset::mExtendedPanId, otOperationalDatasetComponents::mIsExtendedPanIdPresent, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, OT_EXT_PAN_ID_SIZE, Dataset::sDataset, and VerifyOrExit.
ProcessInit()
otError ProcessInit (uint8_t aArgsLength, char * aArgs[]) private
References ExitNow, Dataset::mInterpreter, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, otDatasetCreateNewNetwork(), otDatasetGetActive(), otDatasetGetPending(), Dataset::sDataset, SuccessOrExit, and VerifyOrExit.
ProcessMasterKey()
otError ProcessMasterKey (uint8_t aArgsLength, char * aArgs[]) private
References otMasterKey::m8, otOperationalDataset::mComponents, otOperationalDatasetComponents::mIsMasterKeyPresent, otOperationalDataset::mMasterKey, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, OT_MASTER_KEY_SIZE, Dataset::sDataset, and VerifyOrExit.
ProcessMeshLocalPrefix()
otError ProcessMeshLocalPrefix (uint8_t aArgsLength, char * aArgs[]) private
References otIp6Address::OT_TOOL_PACKED_FIELD::m8, otMeshLocalPrefix::m8, otOperationalDataset::mComponents, otIp6Address::mFields, otOperationalDatasetComponents::mIsMeshLocalPrefixPresent, otOperationalDataset::mMeshLocalPrefix, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, otIp6AddressFromString(), Dataset::sDataset, SuccessOrExit, and VerifyOrExit.
ProcessNetworkName()
otError ProcessNetworkName (uint8_t aArgsLength, char * aArgs[]) private
References otNetworkName::m8, otOperationalDataset::mComponents, otOperationalDatasetComponents::mIsNetworkNamePresent, otOperationalDataset::mNetworkName, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, OT_NETWORK_NAME_MAX_SIZE, Dataset::sDataset, and VerifyOrExit.
ProcessPanId()
otError ProcessPanId (uint8_t aArgsLength, char * aArgs[]) private
References otOperationalDataset::mComponents, otOperationalDatasetComponents::mIsPanIdPresent, otOperationalDataset::mPanId, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, Dataset::sDataset, SuccessOrExit, and VerifyOrExit.
ProcessPending()
otError ProcessPending (uint8_t aArgsLength, char * aArgs[]) private
References Dataset::mInterpreter, OT_UNUSED_VARIABLE, otDatasetGetPending(), Dataset::Print(), and SuccessOrExit.
ProcessPendingTimestamp()
otError ProcessPendingTimestamp (uint8_t aArgsLength, char * aArgs[]) private
References otOperationalDataset::mComponents, otOperationalDatasetComponents::mIsPendingTimestampPresent, otOperationalDataset::mPendingTimestamp, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, Dataset::sDataset, SuccessOrExit, and VerifyOrExit.
ProcessMgmtSetCommand()
otError ProcessMgmtSetCommand (uint8_t aArgsLength, char * aArgs[]) private
References ExitNow, otMasterKey::m8, otIp6Address::OT_TOOL_PACKED_FIELD::m8, otNetworkName::m8, otExtendedPanId::m8, otMeshLocalPrefix::m8, otOperationalDataset::mActiveTimestamp, otOperationalDataset::mChannel, otOperationalDataset::mChannelMask, otOperationalDataset::mComponents, otOperationalDataset::mDelay, otOperationalDataset::mExtendedPanId, otIp6Address::mFields, Dataset::mInterpreter, otOperationalDatasetComponents::mIsActiveTimestampPresent, otOperationalDatasetComponents::mIsChannelMaskPresent, otOperationalDatasetComponents::mIsChannelPresent, otOperationalDatasetComponents::mIsDelayPresent, otOperationalDatasetComponents::mIsExtendedPanIdPresent, otOperationalDatasetComponents::mIsMasterKeyPresent, otOperationalDatasetComponents::mIsMeshLocalPrefixPresent, otOperationalDatasetComponents::mIsNetworkNamePresent, otOperationalDatasetComponents::mIsPanIdPresent, otOperationalDatasetComponents::mIsPendingTimestampPresent, otOperationalDataset::mMasterKey, otOperationalDataset::mMeshLocalPrefix, otOperationalDataset::mNetworkName, otOperationalDataset::mPanId, otOperationalDataset::mPendingTimestamp, OT_ERROR_INVALID_ARGS, OT_ERROR_NO_BUFS, OT_ERROR_NONE, OT_MASTER_KEY_SIZE, OT_NETWORK_NAME_MAX_SIZE, otDatasetSendMgmtActiveSet(), otDatasetSendMgmtPendingSet(), otIp6AddressFromString(), Dataset::sDataset, SuccessOrExit, and VerifyOrExit.
ProcessMgmtGetCommand()
otError ProcessMgmtGetCommand (uint8_t aArgsLength, char * aArgs[]) private
References ExitNow, Dataset::mInterpreter, otOperationalDatasetComponents::mIsActiveTimestampPresent, otOperationalDatasetComponents::mIsChannelPresent, otOperationalDatasetComponents::mIsDelayPresent, otOperationalDatasetComponents::mIsExtendedPanIdPresent, otOperationalDatasetComponents::mIsMasterKeyPresent, otOperationalDatasetComponents::mIsMeshLocalPrefixPresent, otOperationalDatasetComponents::mIsNetworkNamePresent, otOperationalDatasetComponents::mIsPanIdPresent, otOperationalDatasetComponents::mIsPendingTimestampPresent, OT_ERROR_INVALID_ARGS, OT_ERROR_NO_BUFS, OT_ERROR_NONE, otDatasetSendMgmtActiveGet(), otDatasetSendMgmtPendingGet(), otIp6AddressFromString(), SuccessOrExit, and VerifyOrExit.
ProcessPskc()
otError ProcessPskc (uint8_t aArgsLength, char * aArgs[]) private
References ExitNow, otPskc::m8, otOperationalDataset::mComponents, otOperationalDataset::mExtendedPanId, Dataset::mInterpreter, otOperationalDatasetComponents::mIsExtendedPanIdPresent, otOperationalDatasetComponents::mIsNetworkNamePresent, otOperationalDatasetComponents::mIsPskcPresent, otOperationalDataset::mNetworkName, otOperationalDataset::mPskc, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, otDatasetGeneratePskc(), otThreadGetExtendedPanId(), otThreadGetNetworkName(), Dataset::sDataset, SuccessOrExit, and VerifyOrExit.
ProcessSecurityPolicy()
otError ProcessSecurityPolicy (uint8_t aArgsLength, char * aArgs[]) private
References ExitNow, otOperationalDataset::mComponents, otSecurityPolicy::mFlags, otOperationalDatasetComponents::mIsSecurityPolicyPresent, otSecurityPolicy::mRotationTime, otOperationalDataset::mSecurityPolicy, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, OT_SECURITY_POLICY_BEACONS, OT_SECURITY_POLICY_EXTERNAL_COMMISSIONER, OT_SECURITY_POLICY_NATIVE_COMMISSIONING, OT_SECURITY_POLICY_OBTAIN_MASTER_KEY, OT_SECURITY_POLICY_ROUTERS, Dataset::sDataset, SuccessOrExit, and VerifyOrExit.
Field Documentation
mInterpreter
Interpreter& mInterpreter private
Referenced by Dataset::OutputBytes(), Dataset::Print(), Dataset::ProcessActive(), Dataset::ProcessCommit(), Dataset::ProcessHelp(), Dataset::ProcessInit(), Dataset::ProcessMgmtGetCommand(), Dataset::ProcessMgmtSetCommand(), Dataset::ProcessPending(), and Dataset::ProcessPskc().
sCommands
const Dataset::Command sCommands static private
Initial value:
= {
    {"help", &Dataset::ProcessHelp},
    {"active", &Dataset::ProcessActive},
    {"activetimestamp", &Dataset::ProcessActiveTimestamp},
    {"channel", &Dataset::ProcessChannel},
    {"channelmask", &Dataset::ProcessChannelMask},
    {"clear", &Dataset::ProcessClear},
    {"commit", &Dataset::ProcessCommit},
    {"delay", &Dataset::ProcessDelay},
    {"extpanid", &Dataset::ProcessExtPanId},
    {"init", &Dataset::ProcessInit},
    {"masterkey", &Dataset::ProcessMasterKey},
    {"meshlocalprefix", &Dataset::ProcessMeshLocalPrefix},
    {"mgmtgetcommand", &Dataset::ProcessMgmtGetCommand},
    {"mgmtsetcommand", &Dataset::ProcessMgmtSetCommand},
    {"networkname", &Dataset::ProcessNetworkName},
    {"panid", &Dataset::ProcessPanId},
    {"pending", &Dataset::ProcessPending},
    {"pendingtimestamp", &Dataset::ProcessPendingTimestamp},
    {"pskc", &Dataset::ProcessPskc},
    {"securitypolicy", &Dataset::ProcessSecurityPolicy},
}
Referenced by Dataset::Process(), and Dataset::ProcessHelp().
sDataset
otOperationalDataset sDataset static private
Referenced by Dataset::Process(), Dataset::ProcessActiveTimestamp(), Dataset::ProcessChannel(), Dataset::ProcessChannelMask(), Dataset::ProcessClear(), Dataset::ProcessCommit(), Dataset::ProcessDelay(), Dataset::ProcessExtPanId(), Dataset::ProcessInit(), Dataset::ProcessMasterKey(), Dataset::ProcessMeshLocalPrefix(), Dataset::ProcessMgmtSetCommand(), Dataset::ProcessNetworkName(), Dataset::ProcessPanId(), Dataset::ProcessPendingTimestamp(), Dataset::ProcessPskc(), and Dataset::ProcessSecurityPolicy().
The documentation for this class was generated from the following files:
cli_dataset.hpp
cli_dataset.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale