OpenThread: LinkQualityInfo Class Reference
LinkQualityInfo Class Reference
Core-link-quality
#include <link_quality.hpp>
Public Types
enum { kInfoStringSize = 50 }
typedef String< kInfoStringSize > InfoString
Public Member Functions
void AddFrameTxStatus (bool aTxStatus)
void AddMessageTxStatus (bool aTxStatus)
void AddRss (int8_t aRss)
void Clear (void)
int8_t GetAverageRss (void) const
uint16_t GetAverageRssRaw (void) const
uint16_t GetFrameErrorRate (void) const
int8_t GetLastRss (void) const
uint8_t GetLinkMargin (void) const
uint8_t GetLinkQuality (void) const
uint16_t GetMessageErrorRate (void) const
void Init (Instance &aInstance)
InfoString ToInfoString (void) const
Public Member Functions inherited from InstanceLocator
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Static Public Member Functions
static uint8_t ConvertLinkMarginToLinkQuality (uint8_t aLinkMargin)
static int8_t ConvertLinkQualityToRss (int8_t aNoiseFloor, uint8_t aLinkQuality)
static uint8_t ConvertRssToLinkMargin (int8_t aNoiseFloor, int8_t aRss)
static uint8_t ConvertRssToLinkQuality (int8_t aNoiseFloor, int8_t aRss)
Private Types
enum {
kThreshold3 = 20, kThreshold2 = 10, kThreshold1 = 2, kHysteresisThreshold = 2,
kLinkQuality3LinkMargin = 50, kLinkQuality2LinkMargin = 15, kLinkQuality1LinkMargin = 5, kLinkQuality0LinkMargin = 0,
kNoLinkQuality = 0xff
}
Private Member Functions
void SetLinkQuality (uint8_t aLinkQuality)
Static Private Member Functions
static uint8_t CalculateLinkQuality (uint8_t aLinkMargin, uint8_t aLastLinkQuality)
Private Attributes
SuccessRateTracker mFrameErrorRate
int8_t mLastRss
uint8_t mLinkQuality
SuccessRateTracker mMessageErrorRate
RssAverager mRssAverager
Additional Inherited Members
Protected Member Functions inherited from InstanceLocatorInit
void Init (Instance &aInstance)
InstanceLocatorInit (void)
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Detailed Description
This class encapsulates/stores all relevant information about quality of a link, including average received signal strength (RSS), last RSS, link margin, and link quality.
Member Typedef Documentation
InfoString
typedef String<kInfoStringSize> InfoString
This type defines the fixed-length String object returned from ToInfoString().
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
kInfoStringSize
Max chars needed for the info string representation (.
See also
ToInfoString())
anonymous enum
anonymous enum private
Enumerator
kThreshold3
Link margin threshold for quality 3 link.
kThreshold2
Link margin threshold for quality 2 link.
kThreshold1
Link margin threshold for quality 1 link.
kHysteresisThreshold
Link margin hysteresis threshold.
kLinkQuality3LinkMargin
link margin for Link Quality 3 (21 - 255)
kLinkQuality2LinkMargin
link margin for Link Quality 3 (21 - 255)
kLinkQuality1LinkMargin
link margin for Link Quality 3 (21 - 255)
kLinkQuality0LinkMargin
link margin for Link Quality 3 (21 - 255)
kNoLinkQuality
Member Function Documentation
Init()
void Init (Instance & aInstance) inline
This method initializes the LinkQualityInfo object.
Parameters
[in] aInstance A reference to the OpenThread instance.
References InstanceLocatorInit::Init().
Referenced by Neighbor::Init().
Clear()
void Clear (void)
This method clears the all the data in the object.
References OT_RADIO_RSSI_INVALID.
Referenced by Mle::HandleParentResponse(), and Mac::HandleReceivedFrame().
AddRss()
void AddRss (int8_t aRss)
This method adds a new received signal strength (RSS) value to the average.
Parameters
[in] aRss A new received signal strength value (in dBm) to be added to the average.
References OT_NOOP, OT_RADIO_RSSI_INVALID, SuccessOrExit, and VerifyOrExit.
Referenced by Mle::HandleParentResponse(), Mac::HandleReceivedFrame(), and Mac::RecordFrameTransmitStatus().
GetAverageRss()
int8_t GetAverageRss (void) const inline
This method returns the current average received signal strength value.
Returns
The current average value or OT_RADIO_RSSI_INVALID if no average is available.
Referenced by Mle::CheckReachability().
GetAverageRssRaw()
uint16_t GetAverageRssRaw (void) const inline
This method returns an encoded version of current average signal strength value. The encoded value is the average multiplied by a precision factor (currently -8).
Returns
The current average multiplied by precision factor or zero if no average is available.
ToInfoString()
LinkQualityInfo::InfoString ToInfoString (void) const
This method converts the link quality info to info/debug human-readable string.
Returns
An InfoString representing the link quality info.
GetLinkMargin()
uint8_t GetLinkMargin (void) const
This method returns the link margin. The link margin is calculated using the link's current average received signal strength (RSS) and average noise floor.
Returns
Link margin derived from average received signal strength and average noise floor.
GetLinkQuality()
uint8_t GetLinkQuality (void) const inline
Returns the current one-way link quality value. The link quality value is a number 0-3.
The link quality is calculated by comparing the current link margin with a set of thresholds (per Thread spec). More specifically, link margin > 20 dB gives link quality 3, link margin > 10 dB gives link quality 2, link margin > 2 dB gives link quality 1, and link margin below or equal to 2 dB yields link quality of 0.
In order to ensure that a link margin near the boundary of two different link quality values does not cause frequent changes, a hysteresis of 2 dB is applied when determining the link quality. For example, the average link margin must be at least 12 dB to change a quality 1 link to a quality 2 link.
Returns
The current link quality value (value 0-3 as per Thread specification).
Referenced by Mle::HandleAttachTimer(), and Mle::IsBetterParent().
GetLastRss()
int8_t GetLastRss (void) const inline
Returns the most recent RSS value.
Returns
The most recent RSS
AddFrameTxStatus()
void AddFrameTxStatus (bool aTxStatus) inline
This method adds a MAC frame transmission status (success/failure) and updates the frame tx error rate.
Parameters
[in] aTxStatus Success/Failure of MAC frame transmission (true -> success, false -> failure).
References OPENTHREAD_CONFIG_FRAME_TX_ERR_RATE_AVERAGING_WINDOW.
Referenced by Mac::RecordFrameTransmitStatus().
AddMessageTxStatus()
void AddMessageTxStatus (bool aTxStatus) inline
This method adds a message transmission status (success/failure) and updates the message error rate.
Parameters
[in] aTxStatus Success/Failure of message (true -> success, false -> message tx failed). A larger (IPv6) message may be fragmented and sent as multiple MAC frames. The message transmission is considered a failure, if any of its fragments fail after all MAC retry attempts.
References OPENTHREAD_CONFIG_IPV6_TX_ERR_RATE_AVERAGING_WINDOW.
Referenced by MeshForwarder::HandleSentFrame().
GetFrameErrorRate()
uint16_t GetFrameErrorRate (void) const inline
This method returns the MAC frame transmission error rate for the link.
The rate is maintained over a window of (roughly) last OPENTHREAD_CONFIG_FRAME_TX_ERR_RATE_AVERAGING_WINDOW frame transmissions.
Returns
The error rate with maximum value 0xffff corresponding to 100% failure rate.
GetMessageErrorRate()
uint16_t GetMessageErrorRate (void) const inline
This method returns the message error rate for the link.
The rate is maintained over a window of (roughly) last OPENTHREAD_CONFIG_IPV6_TX_ERR_RATE_AVERAGING_WINDOW (IPv6) messages.
Note that a larger (IPv6) message can be fragmented and sent as multiple MAC frames. The message transmission is considered a failure, if any of its fragments fail after all MAC retry attempts.
Returns
The error rate with maximum value 0xffff corresponding to 100% failure rate.
ConvertRssToLinkMargin()
uint8_t ConvertRssToLinkMargin (int8_t aNoiseFloor, int8_t aRss) static
This method converts a received signal strength value to a link margin value.
Parameters
[in] aNoiseFloor The noise floor value (in dBm).
[in] aRss The received signal strength value (in dBm).
Returns
The link margin value.
References OT_RADIO_RSSI_INVALID.
Referenced by Mle::HandleParentResponse().
ConvertLinkMarginToLinkQuality()
uint8_t ConvertLinkMarginToLinkQuality (uint8_t aLinkMargin) static
This method converts a link margin value to a link quality value.
Parameters
[in] aLinkMargin The Link Margin in dB.
Returns
The link quality value (0-3).
Referenced by Mle::HandleParentResponse().
ConvertRssToLinkQuality()
uint8_t ConvertRssToLinkQuality (int8_t aNoiseFloor, int8_t aRss) static
This method converts a received signal strength value to a link quality value.
Parameters
[in] aNoiseFloor The noise floor value (in dBm).
[in] aRss The received signal strength value (in dBm).
Returns
The link quality value (0-3).
Referenced by otLinkSetMaxFrameRetriesDirect().
ConvertLinkQualityToRss()
int8_t ConvertLinkQualityToRss (int8_t aNoiseFloor, uint8_t aLinkQuality) static
This method converts a link quality value to a typical received signal strength value .
Note
only for test
Parameters
[in] aNoiseFloor The noise floor value (in dBm).
[in] aLinkQuality The link quality value in [0, 3].
Returns
The typical platform rssi.
Referenced by otLinkSetMaxFrameRetriesDirect().
SetLinkQuality()
void SetLinkQuality (uint8_t aLinkQuality) inline private
CalculateLinkQuality()
uint8_t CalculateLinkQuality (uint8_t aLinkMargin, uint8_t aLastLinkQuality) static private
Field Documentation
mRssAverager
RssAverager mRssAverager private
mLinkQuality
uint8_t mLinkQuality private
mLastRss
int8_t mLastRss private
mFrameErrorRate
SuccessRateTracker mFrameErrorRate private
mMessageErrorRate
SuccessRateTracker mMessageErrorRate private
The documentation for this class was generated from the following files:
link_quality.hpp
link_quality.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale