OpenThread: MessagePool Class Reference
MessagePool Class Reference
Core-message
#include <message.hpp>
Public Member Functions
void Free (Message *aMessage)
uint16_t GetFreeBufferCount (void) const
MessagePool (Instance &aInstance)
Message * New (uint8_t aType, uint16_t aReserveHeader, uint8_t aPriority=kDefaultMessagePriority)
Message * New (uint8_t aType, uint16_t aReserveHeader, const otMessageSettings *aSettings)
Public Member Functions inherited from InstanceLocator
template<>
Instance & Get (void) const
template<typename Type >
Type & Get (void) const
Instance & GetInstance (void) const
Private Types
enum { kDefaultMessagePriority = Message::kPriorityNormal }
Private Member Functions
void FreeBuffers (Buffer *aBuffer)
Buffer * NewBuffer (uint8_t aPriority)
otError ReclaimBuffers (int aNumBuffers, uint8_t aPriority)
Private Attributes
Buffer mBuffers [kNumBuffers]
Buffer * mFreeBuffers
uint16_t mNumFreeBuffers
Friends
class Message
class MessageQueue
class PriorityQueue
Additional Inherited Members
Protected Member Functions inherited from InstanceLocator
InstanceLocator (Instance &aInstance)
Detailed Description
This class represents a message pool
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
kDefaultMessagePriority
Constructor & Destructor Documentation
MessagePool()
MessagePool (Instance & aInstance) explicit
This constructor initializes the object.
References InstanceLocator::GetInstance(), ot::kNumBuffers, MessagePool::mBuffers, MessagePool::mFreeBuffers, MessagePool::mNumFreeBuffers, otPlatMessagePoolInit(), and Buffer::SetNextBuffer().
Member Function Documentation
New() [1/2]
Message * New (uint8_t aType, uint16_t aReserveHeader, uint8_t aPriority = kDefaultMessagePriority)
This method is used to obtain a new message. The default priority kDefaultMessagePriority is assigned to the message.
Parameters
[in] aType The message type.
[in] aReserveHeader The number of header bytes to reserve.
[in] aPriority The priority level of the message.
Returns
A pointer to the message or NULL if no message buffers are available.
References MessagePool::Free(), MessagePool::NewBuffer(), OT_ERROR_NONE, OT_NOOP, Message::SetLength(), Message::SetLinkSecurityEnabled(), Message::SetMessagePool(), Message::SetPriority(), Message::SetReserved(), Message::SetType(), SuccessOrExit, and VerifyOrExit.
Referenced by Message::Clone(), and MessagePool::New().
New() [2/2]
Message * New (uint8_t aType, uint16_t aReserveHeader, const otMessageSettings * aSettings)
This method is used to obtain a new message with specified settings.
Note
If aSettings is 'NULL', the link layer security is enabled and the message priority is set to OT_MESSAGE_PRIORITY_NORMAL by default.
Parameters
[in] aType The message type.
[in] aReserveHeader The number of header bytes to reserve.
[in] aSettings A pointer to the message settings or NULL to set default settings.
Returns
A pointer to the message or NULL if no message buffers are available.
References otMessageSettings::mLinkSecurityEnabled, otMessageSettings::mPriority, MessagePool::New(), OT_MESSAGE_PRIORITY_NORMAL, and Message::SetLinkSecurityEnabled().
Free()
void Free (Message * aMessage)
This method is used to free a message and return all message buffers to the buffer pool.
Parameters
[in] aMessage The message to free.
References MessagePool::FreeBuffers(), Message::Next(), OT_ASSERT, and Message::Prev().
Referenced by MessagePool::New().
GetFreeBufferCount()
uint16_t GetFreeBufferCount (void) const
This method returns the number of free buffers.
Returns
The number of free buffers.
References InstanceLocator::GetInstance(), MessagePool::mNumFreeBuffers, and otPlatMessagePoolNumFreeBuffers().
Referenced by MessagePool::ReclaimBuffers().
NewBuffer()
Buffer * NewBuffer (uint8_t aPriority) private
References InstanceLocator::GetInstance(), Buffer::GetNextBuffer(), MessagePool::mFreeBuffers, MessagePool::mNumFreeBuffers, otLogInfoMem, otPlatMessagePoolNew(), MessagePool::ReclaimBuffers(), Buffer::SetNextBuffer(), and SuccessOrExit.
Referenced by MessagePool::New(), Message::Prepend(), and Message::ResizeMessage().
FreeBuffers()
void FreeBuffers (Buffer * aBuffer) private
References InstanceLocator::GetInstance(), Buffer::GetNextBuffer(), MessagePool::mFreeBuffers, MessagePool::mNumFreeBuffers, otPlatMessagePoolFree(), and Buffer::SetNextBuffer().
Referenced by MessagePool::Free().
ReclaimBuffers()
otError ReclaimBuffers (int aNumBuffers, uint8_t aPriority) private
References MessagePool::GetFreeBufferCount(), OT_ERROR_NO_BUFS, OT_ERROR_NONE, OT_UNUSED_VARIABLE, and SuccessOrExit.
Referenced by MessagePool::NewBuffer(), and Message::SetLength().
Friends And Related Function Documentation
Message
friend class Message friend
MessageQueue
friend class MessageQueue friend
PriorityQueue
friend class PriorityQueue friend
Field Documentation
mNumFreeBuffers
uint16_t mNumFreeBuffers private
Referenced by MessagePool::FreeBuffers(), MessagePool::GetFreeBufferCount(), MessagePool::MessagePool(), and MessagePool::NewBuffer().
mBuffers
Buffer mBuffers[kNumBuffers] private
Referenced by MessagePool::MessagePool().
mFreeBuffers
Buffer* mFreeBuffers private
Referenced by MessagePool::FreeBuffers(), MessagePool::MessagePool(), and MessagePool::NewBuffer().
The documentation for this class was generated from the following files:
message.hpp
message.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale