OpenThread: ActiveTimestampTlv Class Reference
ActiveTimestampTlv Class Reference
MLE » TLVs
#include <mle_tlvs.hpp>
Public Member Functions
void Init (void)
bool IsValid (void) const
Public Member Functions inherited from Tlv
Type GetType (void) const
void SetType (Type aType)
Public Member Functions inherited from Tlv
otError AppendTo (Message &aMessage) const
uint8_t GetLength (void) const
Tlv * GetNext (void)
const Tlv * GetNext (void) const
uint32_t GetSize (void) const
uint8_t GetType (void) const
uint8_t * GetValue (void)
const uint8_t * GetValue (void) const
bool IsExtended (void) const
void SetLength (uint8_t aLength)
void SetType (uint8_t aType)
Public Member Functions inherited from Timestamp
int Compare (const Timestamp &aCompare) const
bool GetAuthoritative (void) const
uint64_t GetSeconds (void) const
uint16_t GetTicks (void) const
void Init (void)
void SetAuthoritative (bool aAuthoritative)
void SetSeconds (uint64_t aSeconds)
void SetTicks (uint16_t aTicks)
Additional Inherited Members
Public Types inherited from Tlv
enum Type {
kSourceAddress = 0, kMode = 1, kTimeout = 2, kChallenge = 3,
kResponse = 4, kLinkFrameCounter = 5, kLinkQuality = 6, kNetworkParameter = 7,
kMleFrameCounter = 8, kRoute = 9, kAddress16 = 10, kLeaderData = 11,
kNetworkData = 12, kTlvRequest = 13, kScanMask = 14, kConnectivity = 15,
kLinkMargin = 16, kStatus = 17, kVersion = 18, kAddressRegistration = 19,
kChannel = 20, kPanId = 21, kActiveTimestamp = 22, kPendingTimestamp = 23,
kActiveDataset = 24, kPendingDataset = 25, kDiscovery = 26, kTimeRequest = 252,
kTimeParameter = 253, kXtalAccuracy = 254, kInvalid = 255
}
Public Types inherited from Tlv
enum { kBaseTlvMaxLength = OT_NETWORK_BASE_TLV_MAX_LENGTH }
Static Public Member Functions inherited from Tlv
static otError GetOffset (const Message &aMessage, Type aType, uint16_t &aOffset)
static otError GetTlv (const Message &aMessage, Type aType, uint16_t aMaxLength, Tlv &aTlv)
Static Public Member Functions inherited from Tlv
static otError AppendTlv (Message &aMessage, uint8_t aType, const uint8_t *aValue, uint8_t aLength)
static otError AppendUint16Tlv (Message &aMessage, uint8_t aType, uint16_t aValue)
static otError AppendUint32Tlv (Message &aMessage, uint8_t aType, uint32_t aValue)
static otError AppendUint8Tlv (Message &aMessage, uint8_t aType, uint8_t aValue)
static otError Get (const Message &aMessage, uint8_t aType, uint16_t aMaxSize, Tlv &aTlv)
static otError GetOffset (const Message &aMessage, uint8_t aType, uint16_t &aOffset)
static otError GetValueOffset (const Message &aMessage, uint8_t aType, uint16_t &aOffset, uint16_t &aLength)
static otError ReadTlv (const Message &aMessage, uint8_t aType, void *aValue, uint8_t aLength)
static otError ReadUint16Tlv (const Message &aMessage, uint8_t aType, uint16_t &aValue)
static otError ReadUint32Tlv (const Message &aMessage, uint8_t aType, uint32_t &aValue)
static otError ReadUint8Tlv (const Message &aMessage, uint8_t aType, uint8_t &aValue)
Protected Types inherited from Tlv
enum { kExtendedLength = 255 }
Detailed Description
This class implements Active Timestamp TLV generation and parsing.
Member Function Documentation
Init()
void Init (void) inline
This method initializes the TLV.
References Tlv::kActiveTimestamp, Tlv::SetLength(), and Tlv::SetType().
Referenced by Mle::AppendActiveTimestamp(), and Mle::SendAnnounce().
IsValid()
bool IsValid (void) const inline
This method indicates whether or not the TLV appears to be well-formed.
Return values
TRUE If the TLV appears to be well-formed.
FALSE If the TLV does not appear to be well-formed.
References Tlv::GetLength(), OT_TOOL_PACKED_BEGIN, and ot::Mle::OT_TOOL_PACKED_END.
Referenced by Mle::HandleAnnounce(), Mle::HandleChildIdResponse(), and Mle::HandleLeaderData().
The documentation for this class was generated from the following file:
mle_tlvs.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale