OpenThread: AddressRegistrationEntry Class Reference
AddressRegistrationEntry Class Reference
MLE » TLVs
#include <mle_tlvs.hpp>
Public Member Functions
uint8_t GetContextId (void) const
const uint8_t * GetIid (void) const
const Ip6::Address * GetIp6Address (void) const
uint8_t GetLength (void) const
bool IsCompressed (void) const
void SetContextId (uint8_t aContextId)
void SetIid (const uint8_t *aIid)
void SetIp6Address (const Ip6::Address &aAddress)
void SetUncompressed (void)
Private Types
enum { kCompressed = 1 << 7, kCidMask = 0xf }
Private Attributes
uint8_t mControl
union {
uint8_t mIid [Ip6::Address::kInterfaceIdentifierSize]
Ip6::Address mIp6Address
} OT_TOOL_PACKED_FIELD
Detailed Description
This class implements Source Address TLV generation and parsing.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
kCompressed
kCidMask
Member Function Documentation
GetLength()
uint8_t GetLength (void) const inline
This method returns the IPv6 address or IID length.
Returns
The IPv6 address length if the Compressed bit is clear, or the IID length if the Compressed bit is set.
Referenced by Mle::AppendAddressRegistration().
IsCompressed()
bool IsCompressed (void) const inline
This method indicates whether or not the Compressed flag is set.
Return values
TRUE If the Compressed flag is set.
FALSE If the Compressed flag is not set.
SetUncompressed()
void SetUncompressed (void) inline
This method sets the Uncompressed flag.
Referenced by Mle::AppendAddressRegistration().
GetContextId()
uint8_t GetContextId (void) const inline
This method returns the Context ID for the compressed form.
Returns
The Context ID value.
SetContextId()
void SetContextId (uint8_t aContextId) inline
This method sets the Context ID value.
Parameters
[in] aContextId The Context ID value.
Referenced by Mle::AppendAddressRegistration().
GetIid()
const uint8_t* GetIid (void) const inline
This method returns a pointer to the IID value.
Returns
A pointer to the IID value.
SetIid()
void SetIid (const uint8_t * aIid) inline
This method sets the IID value.
Parameters
[in] aIid A pointer to the IID value.
Referenced by Mle::AppendAddressRegistration().
GetIp6Address()
const Ip6::Address* GetIp6Address (void) const inline
This method returns a pointer to the IPv6 Address value.
Returns
A pointer to the IPv6 Address value.
SetIp6Address()
void SetIp6Address (const Ip6::Address & aAddress) inline
This method sets the IPv6 Address value.
Parameters
[in] aAddress A reference to the IPv6 Address value.
Referenced by Mle::AppendAddressRegistration().
Field Documentation
mControl
uint8_t mControl private
mIid
uint8_t mIid[Ip6::Address::kInterfaceIdentifierSize]
mIp6Address
Ip6::Address mIp6Address
OT_TOOL_PACKED_FIELD
union { ... } OT_TOOL_PACKED_FIELD
The documentation for this class was generated from the following file:
mle_tlvs.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale