OpenThread: ServerTlv Class Reference
ServerTlv Class Reference
Core-netdata » TLVs
#include <network_data_tlvs.hpp>
Public Types
enum { kType = kTypeServer }
Public Types inherited from NetworkDataTlv
enum Type {
kTypeHasRoute = 0, kTypePrefix = 1, kTypeBorderRouter = 2, kTypeContext = 3,
kTypeCommissioningData = 4, kTypeService = 5, kTypeServer = 6
}
Public Member Functions
uint16_t GetServer16 (void) const
const uint8_t * GetServerData (void) const
uint8_t GetServerDataLength (void) const
void Init (uint16_t aServer16, const uint8_t *aServerData, uint8_t aServerDataLength)
bool IsValid (void) const
bool operator== (const ServerTlv &aOther) const
void SetServer16 (uint16_t aServer16)
Public Member Functions inherited from NetworkDataTlv
void ClearStable (void)
void DecreaseLength (uint8_t aDecrement)
uint8_t GetLength (void) const
NetworkDataTlv * GetNext (void)
const NetworkDataTlv * GetNext (void) const
uint8_t GetSize (void) const
Type GetType (void) const
uint8_t * GetValue (void)
const uint8_t * GetValue (void) const
void IncreaseLength (uint8_t aIncrement)
void Init (void)
bool IsStable (void) const
void SetLength (uint8_t aLength)
void SetStable (void)
void SetType (Type aType)
Static Public Member Functions
static uint16_t CalculateSize (uint8_t aServerDataLength)
Private Attributes
uint16_t mServer16
Detailed Description
This class implements Server Data TLV generation and parsing.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
kType
The TLV Type.
Member Function Documentation
Init()
void Init (uint16_t aServer16, const uint8_t * aServerData, uint8_t aServerDataLength) inline
This method initializes the Server TLV.
Parameters
[in] aServer16 The Server16 value.
[in] aServerData The Server Data.
[in] aServerDataLength Server Data length in bytes.
References NetworkDataTlv::Init(), NetworkDataTlv::kTypeServer, NetworkDataTlv::SetLength(), and NetworkDataTlv::SetType().
IsValid()
bool IsValid (void) const inline
This method indicates whether or not the TLV appears to be well-formed.
Return values
TRUE If the TLV appears to be well-formed.
FALSE If the TLV does not appear to be well-formed.
References NetworkDataTlv::GetLength().
GetServer16()
uint16_t GetServer16 (void) const inline
This method returns the Server16 value.
Returns
The Server16 value.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by LeaderBase::GetBackboneRouterPrimary(), and NetworkData::Iterate().
SetServer16()
void SetServer16 (uint16_t aServer16) inline
References ot::Encoding::BigEndian::HostSwap16().
Referenced by NetworkData::RemoveTemporaryData().
GetServerData()
const uint8_t* GetServerData (void) const inline
This method returns the Server Data.
Returns
A pointer to the Server Data.
Referenced by LeaderBase::GetBackboneRouterPrimary(), and NetworkData::Iterate().
GetServerDataLength()
uint8_t GetServerDataLength (void) const inline
This method returns the Server Data length in bytes.
Returns
The Server Data length in bytes.
References NetworkDataTlv::GetLength().
Referenced by NetworkData::Iterate().
operator==()
bool operator== (const ServerTlv & aOther) const inline
This method indicates whether two Server TLVs fully match.
Parameters
[in] aOther Another Server TLV to compare with it.
Return values
TRUE The two TLVs are equal.
FALSE The two TLVs are not equal.
References NetworkDataTlv::GetLength(), and NetworkDataTlv::GetValue().
CalculateSize()
static uint16_t CalculateSize (uint8_t aServerDataLength) inline static
This static method calculates the total size (number of bytes) of a Service TLV with a given Server Data length.
Note that the returned size does include the Type and Length fields in the TLV.
Parameters
[in] aServerDataLength Server Data length in bytes.
Returns
The size (number of bytes) of the Server TLV.
Field Documentation
mServer16
uint16_t mServer16 private
The documentation for this class was generated from the following file:
network_data_tlvs.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale