OpenThread: ChannelMask Class Reference
ChannelMask Class Reference
Core-mac
#include <channel_mask.hpp>
Public Types
enum { kChannelIteratorFirst = 0xff, kInfoStringSize = 45 }
typedef String< kInfoStringSize > InfoString
Public Member Functions
void AddChannel (uint8_t aChannel)
ChannelMask (void)
ChannelMask (uint32_t aMask)
uint8_t ChooseRandomChannel (void) const
void Clear (void)
bool ContainsChannel (uint8_t aChannel) const
uint32_t GetMask (void) const
otError GetNextChannel (uint8_t &aChannel) const
uint8_t GetNumberOfChannels (void) const
void Intersect (const ChannelMask &aOtherMask)
bool IsEmpty (void) const
bool IsSingleChannel (void) const
bool operator!= (const ChannelMask &aAnother) const
bool operator== (const ChannelMask &aAnother) const
void RemoveChannel (uint8_t aChannel)
void SetMask (uint32_t aMask)
InfoString ToString (void) const
Private Member Functions
OT_STATIC_ASSERT ((Radio::kChannelMin< 32) &&(Radio::kChannelMax< 32), "The channel number is larger than 32. `ChannelMask` uses 32 bit mask.")
Private Attributes
uint32_t mMask
Detailed Description
This class defines a channel mask.
It is a wrapper class around a uint32_t bit vector representing a set of channels.
Member Typedef Documentation
InfoString
typedef String<kInfoStringSize> InfoString
This type defines the fixed-length String object returned from ToString().
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
kChannelIteratorFirst
Value to pass in GetNextChannel() to get the first channel in the mask.
kInfoStringSize
Recommended buffer size to use with ToString().
Constructor & Destructor Documentation
ChannelMask() [1/2]
ChannelMask (void) inline
This constructor initializes a ChannelMask instance.
ChannelMask() [2/2]
ChannelMask (uint32_t aMask) inline explicit
This constructor initializes a ChannelMask instance with a given mask.
Parameters
[in] aMask A channel mask (as a uint32_t bit-vector mask with bit 0 (lsb) -> channel 0, and so on).
Member Function Documentation
Clear()
void Clear (void) inline
This method clears the channel mask.
References ChannelMask::mMask.
GetMask()
uint32_t GetMask (void) const inline
This method gets the channel mask (as a uint32_t bit-vector mask with bit 0 (lsb) -> channel 0, and so on).
Returns
The channel mask.
References ChannelMask::mMask.
Referenced by Mac::Scan(), and MeshForwarder::SetDiscoverParameters().
SetMask()
void SetMask (uint32_t aMask) inline
This method sets the channel mask.
Parameters
[in] aMask A channel mask (as a uint32_t bit-vector mask with bit 0 (lsb) -> channel 0, and so on).
References ChannelMask::mMask.
Referenced by DatasetManager::GetChannelMask(), Mac::Scan(), and MeshForwarder::SetDiscoverParameters().
IsEmpty()
bool IsEmpty (void) const inline
This method indicates if the mask is empty.
Returns
TRUE if the mask is empty, FALSE otherwise.
References ChannelMask::mMask.
Referenced by ChannelMask::ChooseRandomChannel(), DatasetManager::GetChannelMask(), AnnounceSenderBase::SendAnnounce(), and MeshForwarder::SetDiscoverParameters().
IsSingleChannel()
bool IsSingleChannel (void) const inline
This method indicates if the mask contains only a single channel.
Returns
TRUE if channel mask contains a single channel, FALSE otherwise
References ChannelMask::mMask.
ContainsChannel()
bool ContainsChannel (uint8_t aChannel) const inline
This method indicates if the mask contains a given channel.
Parameters
[in] aChannel A channel.
Returns
TRUE if the channel aChannel is included in the mask, FALSE otherwise.
References ChannelMask::mMask.
Referenced by ChannelMask::GetNextChannel(), Mac::SetPanChannel(), and Mac::SetTemporaryChannel().
AddChannel()
void AddChannel (uint8_t aChannel) inline
This method adds a channel to the channel mask.
Parameters
[in] aChannel A channel
References ChannelMask::mMask.
RemoveChannel()
void RemoveChannel (uint8_t aChannel) inline
This method removes a channel from the channel mask.
Parameters
[in] aChannel A channel
References ChannelMask::mMask.
Intersect()
void Intersect (const ChannelMask & aOtherMask) inline
This method updates the channel mask by intersecting it with another mask.
Parameters
[in] aOtherMask Another channel mask.
References ChannelMask::ChooseRandomChannel(), ChannelMask::GetNextChannel(), ChannelMask::GetNumberOfChannels(), and ChannelMask::mMask.
Referenced by Mac::Scan(), AnnounceSenderBase::SendAnnounce(), and Mac::SetSupportedChannelMask().
GetNumberOfChannels()
uint8_t GetNumberOfChannels (void) const
This method returns the number of channels in the mask.
Returns
Number of channels in the mask.
References ChannelMask::GetNextChannel(), ChannelMask::kChannelIteratorFirst, and OT_ERROR_NONE.
Referenced by ChannelMask::ChooseRandomChannel(), AnnounceSenderBase::HandleTimer(), ChannelMask::Intersect(), and Mle::PrepareAnnounceState().
GetNextChannel()
otError GetNextChannel (uint8_t & aChannel) const
This method gets the next channel in the channel mask.
This method can be used to iterate over all channels in the channel mask. To get the first channel (channel with lowest number) in the mask the aChannel should be set to kChannelIteratorFirst.
Parameters
[in,out] aChannel A reference to a uint8_t. On entry it should contain the previous channel or kChannelIteratorFirst. On exit it contains the next channel.
Return values
OT_ERROR_NONE Got the next channel, aChannel updated successfully.
OT_ERROR_NOT_FOUND No next channel in the channel mask (note: aChannel may be changed).
References ChannelMask::ContainsChannel(), ExitNow, ChannelMask::kChannelIteratorFirst, OT_ERROR_NONE, and OT_ERROR_NOT_FOUND.
Referenced by ChannelMask::ChooseRandomChannel(), ChannelMask::GetNumberOfChannels(), MeshForwarder::HandleDiscoverTimer(), AnnounceSenderBase::HandleTimer(), ChannelMask::Intersect(), MeshForwarder::PrepareDiscoverRequest(), Mle::SendOrphanAnnounce(), ChannelMask::ToString(), and Mac::UpdateScanChannel().
ChooseRandomChannel()
uint8_t ChooseRandomChannel (void) const
This method randomly chooses a channel from the channel mask.
Returns
A randomly chosen channel from the given mask, or kChannelIteratorFirst if the mask is empty.
References ChannelMask::GetNextChannel(), ChannelMask::GetNumberOfChannels(), ot::Random::NonCrypto::GetUint8InRange(), ChannelMask::IsEmpty(), ChannelMask::kChannelIteratorFirst, OT_NOOP, SuccessOrExit, and VerifyOrExit.
Referenced by ChannelMask::Intersect().
operator==()
bool operator== (const ChannelMask & aAnother) const inline
This method overloads == operator to indicate whether two masks are equal.
Parameters
[in] aAnother A reference to another mask to compare with the current one.
Returns
TRUE if the two masks are equal, FALSE otherwise.
References ChannelMask::mMask.
operator!=()
bool operator!= (const ChannelMask & aAnother) const inline
This method overloads != operator to indicate whether two masks are different.
Parameters
[in] aAnother A reference to another mask to compare with the current one.
Returns
TRUE if the two masks are different, FALSE otherwise.
References ChannelMask::OT_STATIC_ASSERT(), and ChannelMask::ToString().
ToString()
ChannelMask::InfoString ToString (void) const
This method converts the channel mask into a human-readable string.
Examples of possible output:
empty mask -> "{ }"
all channels -> "{ 11-26 }"
single channel -> "{ 20 }"
multiple ranges -> "{ 11, 14-17, 20-22, 24, 25 }"
no range -> "{ 14, 21, 26 }"
Returns
An InfoString object representing the channel mask.
References ChannelMask::GetNextChannel(), ChannelMask::kChannelIteratorFirst, and OT_ERROR_NONE.
Referenced by AnnounceSenderBase::HandleTimer(), and ChannelMask::operator!=().
OT_STATIC_ASSERT()
OT_STATIC_ASSERT ((Radio::kChannelMin< 32) &&(Radio::kChannelMax< 32) , "The channel number is larger than 32. `ChannelMask` uses 32 bit mask.") private
Referenced by ChannelMask::operator!=().
Field Documentation
mMask
uint32_t mMask private
Referenced by ChannelMask::AddChannel(), ChannelMask::Clear(), ChannelMask::ContainsChannel(), ChannelMask::GetMask(), ChannelMask::Intersect(), ChannelMask::IsEmpty(), ChannelMask::IsSingleChannel(), ChannelMask::operator==(), ChannelMask::RemoveChannel(), and ChannelMask::SetMask().
The documentation for this class was generated from the following files:
channel_mask.hpp
channel_mask.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale