OpenThread: Header Class Reference
Header Class Reference
#include <sntp_client.hpp>
Public Types
enum { kKissCodeLength = 4 }
enum Mode { kModeClient = 3, kModeServer = 4 }
Public Member Functions
uint8_t GetFlags (void) const
char * GetKissCode (void)
Mode GetMode (void) const
uint32_t GetOriginateTimestampFraction (void) const
uint32_t GetOriginateTimestampSeconds (void) const
uint8_t GetPoll (void) const
uint8_t GetPrecision (void) const
uint32_t GetReceiveTimestampFraction (void) const
uint32_t GetReceiveTimestampSeconds (void) const
uint32_t GetReferenceId (void) const
uint32_t GetReferenceTimestampFraction (void) const
uint32_t GetReferenceTimestampSeconds (void) const
uint32_t GetRootDelay (void) const
uint32_t GetRootDispersion (void) const
uint8_t GetStratum (void) const
uint32_t GetTransmitTimestampFraction (void) const
uint32_t GetTransmitTimestampSeconds (void) const
Header (void)
void SetFlags (uint8_t aFlags)
void SetOriginateTimestampFraction (uint32_t aOriginateTimestampFraction)
void SetOriginateTimestampSeconds (uint32_t aOriginateTimestampSeconds)
void SetPoll (uint8_t aPoll)
void SetPrecision (uint8_t aPrecision)
void SetReceiveTimestampFraction (uint32_t aReceiveTimestampFraction)
void SetReceiveTimestampSeconds (uint32_t aReceiveTimestampSeconds)
void SetReferenceId (uint32_t aReferenceId)
void SetReferenceTimestampFraction (uint32_t aReferenceTimestampFraction)
void SetReferenceTimestampSeconds (uint32_t aReferenceTimestampSeconds)
void SetRootDelay (uint32_t aRootDelay)
void SetRootDispersion (uint32_t aRootDispersion)
void SetStratum (uint8_t aStratum)
void SetTransmitTimestampFraction (uint32_t aTransmitTimestampFraction)
void SetTransmitTimestampSeconds (uint32_t aTransmitTimestampSeconds)
Private Types
enum {
kNtpVersion = 4, kLeapOffset = 6, kLeapMask = 0x03 << kLeapOffset, kVersionOffset = 3,
kVersionMask = 0x07 << kVersionOffset, kModeOffset = 0, kModeMask = 0x07 << kModeOffset
}
Private Attributes
uint8_t mFlags
SNTP flags: LI Leap Indicator, VN Version Number and Mode.
uint32_t mOriginateTimestampFraction
Fraction part of above value.
uint32_t mOriginateTimestampSeconds
uint8_t mPoll
Maximum interval between successive messages, in log2 seconds.
uint8_t mPrecision
The precision of the system clock, in log2 seconds.
uint32_t mReceiveTimestampFraction
Fraction part of above value.
uint32_t mReceiveTimestampSeconds
uint32_t mReferenceId
ID identifying the particular server or reference clock.
uint32_t mReferenceTimestampFraction
Fraction part of above value.
uint32_t mReferenceTimestampSeconds
uint32_t mRootDelay
Total round-trip delay to the reference clock, in NTP short format.
uint32_t mRootDispersion
Total dispersion to the reference clock.
uint8_t mStratum
Packet Stratum.
uint32_t mTransmitTimestampFraction
Fraction part of above value.
uint32_t mTransmitTimestampSeconds
Detailed Description
This class implements SNTP header generation and parsing.
Member Enumeration Documentation
Mode
enum Mode
Defines supported SNTP modes.
Enumerator
kModeClient
kModeServer
anonymous enum
anonymous enum
Kiss code length.
Enumerator
kKissCodeLength
Length of the kiss code in ASCII format.
anonymous enum
anonymous enum private
Protocol Constants (RFC 5905).
Enumerator
kNtpVersion
Current NTP version.
kLeapOffset
Leap Indicator field offset.
Flags offsets and masks.
kLeapMask
Leap Indicator field mask.
kVersionOffset
Version field offset.
kVersionMask
Version field mask.
kModeOffset
Mode field offset.
kModeMask
Mode filed mask.
Constructor & Destructor Documentation
Header()
Header (void)
Default constructor for SNTP Header.
Member Function Documentation
GetFlags()
uint8_t GetFlags (void) const inline
This method returns the flags field value.
Returns
Value of the flags field (LI, VN and Mode).
References Header::mFlags.
SetFlags()
void SetFlags (uint8_t aFlags) inline
This method sets the flags field.
Parameters
[in] aFlags The value of the flags field.
References Header::mFlags.
GetMode()
Mode GetMode (void) const inline
This method returns the SNTP operational mode.
Returns
SNTP operational mode.
References Header::kModeMask, Header::kModeOffset, and Header::mFlags.
GetStratum()
uint8_t GetStratum (void) const inline
This method returns the packet stratum field value.
Returns
Value of the packet stratum.
References Header::mStratum.
SetStratum()
void SetStratum (uint8_t aStratum) inline
This method sets the packet stratum field value.
Parameters
[in] aStratum The value of the packet stratum field.
References Header::mStratum.
GetPoll()
uint8_t GetPoll (void) const inline
This method returns the poll field value.
Returns
Value of the poll field.
References Header::mPoll.
SetPoll()
void SetPoll (uint8_t aPoll) inline
This method sets the poll field.
Parameters
[in] aPoll The value of the poll field.
References Header::mPoll.
GetPrecision()
uint8_t GetPrecision (void) const inline
This method returns the precision field value.
Returns
Value of the precision field.
References Header::mPrecision.
SetPrecision()
void SetPrecision (uint8_t aPrecision) inline
This method sets the precision field.
Parameters
[in] aPrecision The value of the precision field.
References Header::mPrecision.
GetRootDelay()
uint32_t GetRootDelay (void) const inline
This method returns the root delay field value.
Returns
Value of the root delay field.
References ot::Encoding::BigEndian::HostSwap32(), and Header::mRootDelay.
SetRootDelay()
void SetRootDelay (uint32_t aRootDelay) inline
This method sets the root delay field.
Parameters
[in] aRootDelay The value of the root delay field.
References ot::Encoding::BigEndian::HostSwap32(), and Header::mRootDelay.
GetRootDispersion()
uint32_t GetRootDispersion (void) const inline
This method returns the root dispersion field value.
Returns
Value of the root dispersion field.
References ot::Encoding::BigEndian::HostSwap32(), and Header::mRootDispersion.
SetRootDispersion()
void SetRootDispersion (uint32_t aRootDispersion) inline
This method sets the root dispersion field.
Parameters
[in] aRootDispersion The value of the root dispersion field.
References ot::Encoding::BigEndian::HostSwap32(), and Header::mRootDispersion.
GetReferenceId()
uint32_t GetReferenceId (void) const inline
This method returns the reference identifier field value.
Returns
Value of the reference identifier field.
References ot::Encoding::BigEndian::HostSwap32(), and Header::mReferenceId.
SetReferenceId()
void SetReferenceId (uint32_t aReferenceId) inline
This method sets the reference identifier field.
Parameters
[in] aReferenceId The value of the reference identifier field.
References ot::Encoding::BigEndian::HostSwap32(), and Header::mReferenceId.
GetKissCode()
char* GetKissCode (void) inline
This method returns the kiss code in ASCII format.
Returns
Value of the reference identifier field in ASCII format.
References Header::mReferenceId.
GetReferenceTimestampSeconds()
uint32_t GetReferenceTimestampSeconds (void) const inline
This method returns the reference timestamp seconds field.
Returns
Value of the reference timestamp seconds field.
References ot::Encoding::BigEndian::HostSwap32(), and Header::mReferenceTimestampSeconds.
SetReferenceTimestampSeconds()
void SetReferenceTimestampSeconds (uint32_t aReferenceTimestampSeconds) inline
This method sets the reference timestamp seconds field.
Parameters
[in] aReferenceTimestampSeconds Value of the reference timestamp seconds field.
References ot::Encoding::BigEndian::HostSwap32(), and Header::mReferenceTimestampSeconds.
GetReferenceTimestampFraction()
uint32_t GetReferenceTimestampFraction (void) const inline
This method returns the reference timestamp fraction field.
Returns
Value of the reference timestamp fraction field.
References ot::Encoding::BigEndian::HostSwap32(), and Header::mReferenceTimestampFraction.
SetReferenceTimestampFraction()
void SetReferenceTimestampFraction (uint32_t aReferenceTimestampFraction) inline
This method sets the reference timestamp fraction field.
Parameters
[in] aReferenceTimestampFraction Value of the reference timestamp fraction field.
References ot::Encoding::BigEndian::HostSwap32(), and Header::mReferenceTimestampFraction.
GetOriginateTimestampSeconds()
uint32_t GetOriginateTimestampSeconds (void) const inline
This method returns the originate timestamp seconds field.
Returns
Value of the originate timestamp seconds field.
References ot::Encoding::BigEndian::HostSwap32(), and Header::mOriginateTimestampSeconds.
SetOriginateTimestampSeconds()
void SetOriginateTimestampSeconds (uint32_t aOriginateTimestampSeconds) inline
This method sets the originate timestamp seconds field.
Parameters
[in] aOriginateTimestampSeconds Value of the originate timestamp seconds field.
References ot::Encoding::BigEndian::HostSwap32(), and Header::mOriginateTimestampSeconds.
GetOriginateTimestampFraction()
uint32_t GetOriginateTimestampFraction (void) const inline
This method returns the originate timestamp fraction field.
Returns
Value of the originate timestamp fraction field.
References ot::Encoding::BigEndian::HostSwap32(), and Header::mOriginateTimestampFraction.
SetOriginateTimestampFraction()
void SetOriginateTimestampFraction (uint32_t aOriginateTimestampFraction) inline
This method sets the originate timestamp fraction field.
Parameters
[in] aOriginateTimestampFraction Value of the originate timestamp fraction field.
References ot::Encoding::BigEndian::HostSwap32(), and Header::mOriginateTimestampFraction.
GetReceiveTimestampSeconds()
uint32_t GetReceiveTimestampSeconds (void) const inline
This method returns the receive timestamp seconds field.
Returns
Value of the receive timestamp seconds field.
References ot::Encoding::BigEndian::HostSwap32(), and Header::mReceiveTimestampSeconds.
SetReceiveTimestampSeconds()
void SetReceiveTimestampSeconds (uint32_t aReceiveTimestampSeconds) inline
This method sets the receive timestamp seconds field.
Parameters
[in] aReceiveTimestampSeconds Value of the receive timestamp seconds field.
References ot::Encoding::BigEndian::HostSwap32(), and Header::mReceiveTimestampSeconds.
GetReceiveTimestampFraction()
uint32_t GetReceiveTimestampFraction (void) const inline
This method returns the receive timestamp fraction field.
Returns
Value of the receive timestamp fraction field.
References ot::Encoding::BigEndian::HostSwap32(), and Header::mReceiveTimestampFraction.
SetReceiveTimestampFraction()
void SetReceiveTimestampFraction (uint32_t aReceiveTimestampFraction) inline
This method sets the receive timestamp fraction field.
Parameters
[in] aReceiveTimestampFraction Value of the receive timestamp fraction field.
References ot::Encoding::BigEndian::HostSwap32(), and Header::mReceiveTimestampFraction.
GetTransmitTimestampSeconds()
uint32_t GetTransmitTimestampSeconds (void) const inline
This method returns the transmit timestamp seconds field.
Returns
Value of the transmit timestamp seconds field.
References ot::Encoding::BigEndian::HostSwap32(), and Header::mTransmitTimestampSeconds.
SetTransmitTimestampSeconds()
void SetTransmitTimestampSeconds (uint32_t aTransmitTimestampSeconds) inline
This method sets the transmit timestamp seconds field.
Parameters
[in] aTransmitTimestampSeconds Value of the transmit timestamp seconds field.
References ot::Encoding::BigEndian::HostSwap32(), and Header::mTransmitTimestampSeconds.
GetTransmitTimestampFraction()
uint32_t GetTransmitTimestampFraction (void) const inline
This method returns the transmit timestamp fraction field.
Returns
Value of the transmit timestamp fraction field.
References ot::Encoding::BigEndian::HostSwap32(), and Header::mTransmitTimestampFraction.
SetTransmitTimestampFraction()
void SetTransmitTimestampFraction (uint32_t aTransmitTimestampFraction) inline
This method sets the transmit timestamp fraction field.
Parameters
[in] aTransmitTimestampFraction Value of the transmit timestamp fraction field.
References ot::Encoding::BigEndian::HostSwap32(), and Header::mTransmitTimestampFraction.
Field Documentation
mFlags
uint8_t mFlags private
SNTP flags: LI Leap Indicator, VN Version Number and Mode.
SNTP Header fields.
Referenced by Header::GetFlags(), Header::GetMode(), and Header::SetFlags().
mStratum
uint8_t mStratum private
Packet Stratum.
Referenced by Header::GetStratum(), and Header::SetStratum().
mPoll
uint8_t mPoll private
Maximum interval between successive messages, in log2 seconds.
Referenced by Header::GetPoll(), and Header::SetPoll().
mPrecision
uint8_t mPrecision private
The precision of the system clock, in log2 seconds.
Referenced by Header::GetPrecision(), and Header::SetPrecision().
mRootDelay
uint32_t mRootDelay private
Total round-trip delay to the reference clock, in NTP short format.
Referenced by Header::GetRootDelay(), and Header::SetRootDelay().
mRootDispersion
uint32_t mRootDispersion private
Total dispersion to the reference clock.
Referenced by Header::GetRootDispersion(), and Header::SetRootDispersion().
mReferenceId
uint32_t mReferenceId private
ID identifying the particular server or reference clock.
Referenced by Header::GetKissCode(), Header::GetReferenceId(), and Header::SetReferenceId().
mReferenceTimestampSeconds
uint32_t mReferenceTimestampSeconds private
Time when the system clock was last set or corrected, in NTP timestamp format.
Referenced by Header::GetReferenceTimestampSeconds(), and Header::SetReferenceTimestampSeconds().
mReferenceTimestampFraction
uint32_t mReferenceTimestampFraction private
Fraction part of above value.
Referenced by Header::GetReferenceTimestampFraction(), and Header::SetReferenceTimestampFraction().
mOriginateTimestampSeconds
uint32_t mOriginateTimestampSeconds private
Time at the client when the request departed for the server, in NTP timestamp format.
Referenced by Header::GetOriginateTimestampSeconds(), and Header::SetOriginateTimestampSeconds().
mOriginateTimestampFraction
uint32_t mOriginateTimestampFraction private
Fraction part of above value.
Referenced by Header::GetOriginateTimestampFraction(), and Header::SetOriginateTimestampFraction().
mReceiveTimestampSeconds
uint32_t mReceiveTimestampSeconds private
Time at the server when the request arrived from the client, in NTP timestamp format.
Referenced by Header::GetReceiveTimestampSeconds(), and Header::SetReceiveTimestampSeconds().
mReceiveTimestampFraction
uint32_t mReceiveTimestampFraction private
Fraction part of above value.
Referenced by Header::GetReceiveTimestampFraction(), and Header::SetReceiveTimestampFraction().
mTransmitTimestampSeconds
uint32_t mTransmitTimestampSeconds private
Time at the server when the response left for the client, in NTP timestamp format.
Referenced by Header::GetTransmitTimestampSeconds(), and Header::SetTransmitTimestampSeconds().
mTransmitTimestampFraction
uint32_t mTransmitTimestampFraction private
Fraction part of above value.
Referenced by Header::GetTransmitTimestampFraction(), and Header::SetTransmitTimestampFraction().
The documentation for this class was generated from the following file:
sntp_client.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale