OpenThread: Tlv Class Reference
Tlv Class Reference
#include <tlvs.hpp>
Public Types
enum { kBaseTlvMaxLength = OT_NETWORK_BASE_TLV_MAX_LENGTH }
Public Member Functions
otError AppendTo (Message &aMessage) const
uint8_t GetLength (void) const
Tlv * GetNext (void)
const Tlv * GetNext (void) const
uint32_t GetSize (void) const
uint8_t GetType (void) const
uint8_t * GetValue (void)
const uint8_t * GetValue (void) const
bool IsExtended (void) const
void SetLength (uint8_t aLength)
void SetType (uint8_t aType)
Static Public Member Functions
static otError AppendTlv (Message &aMessage, uint8_t aType, const uint8_t *aValue, uint8_t aLength)
static otError AppendUint16Tlv (Message &aMessage, uint8_t aType, uint16_t aValue)
static otError AppendUint32Tlv (Message &aMessage, uint8_t aType, uint32_t aValue)
static otError AppendUint8Tlv (Message &aMessage, uint8_t aType, uint8_t aValue)
static otError Get (const Message &aMessage, uint8_t aType, uint16_t aMaxSize, Tlv &aTlv)
static otError GetOffset (const Message &aMessage, uint8_t aType, uint16_t &aOffset)
static otError GetValueOffset (const Message &aMessage, uint8_t aType, uint16_t &aOffset, uint16_t &aLength)
static otError ReadTlv (const Message &aMessage, uint8_t aType, void *aValue, uint8_t aLength)
static otError ReadUint16Tlv (const Message &aMessage, uint8_t aType, uint16_t &aValue)
static otError ReadUint32Tlv (const Message &aMessage, uint8_t aType, uint32_t &aValue)
static otError ReadUint8Tlv (const Message &aMessage, uint8_t aType, uint8_t &aValue)
Protected Types
enum { kExtendedLength = 255 }
Static Private Member Functions
static otError Find (const Message &aMessage, uint8_t aType, uint16_t *aOffset, uint16_t *aSize, bool *aIsExtendedTlv)
Private Attributes
uint8_t mLength
uint8_t mType
Detailed Description
This class implements TLV generation and parsing.
Member Enumeration Documentation
anonymous enum
anonymous enum
Length values.
Enumerator
kBaseTlvMaxLength
The maximum length of the Base TLV format.
anonymous enum
anonymous enum protected
Enumerator
kExtendedLength
Extended Length value.
Member Function Documentation
GetType()
uint8_t GetType (void) const inline
This method returns the Type value.
Returns
The Type value.
References Tlv::mType.
Referenced by Tlv::Find(), ThreadTlv::GetType(), NetworkDiagnosticTlv::GetType(), Tlv::GetType(), and ExtendedTlv::GetType().
SetType()
void SetType (uint8_t aType) inline
This method sets the Type value.
Parameters
[in] aType The Type value.
References Tlv::mType.
Referenced by Tlv::AppendTlv(), TlvUint8::Init(), TlvUint16::Init(), TlvUint32::Init(), ThreadTlv::SetType(), NetworkDiagnosticTlv::SetType(), Tlv::SetType(), and ExtendedTlv::SetType().
IsExtended()
bool IsExtended (void) const inline
This method indicates whether the TLV is an Extended TLV.
Return values
TRUE If the TLV is an Extended TLV.
FALSE If the TLV is not an Extended TLV.
References Tlv::kExtendedLength, and Tlv::mLength.
Referenced by Tlv::FindTlv(), Tlv::GetSize(), Tlv::GetValue(), and Ip6AddressListTlv::IsValid().
GetLength()
uint8_t GetLength (void) const inline
This method returns the Length value.
Note
This method should be used when TLV is not an Extended TLV, otherwise the returned length from this method would not be correct. When TLV is an Extended TLV, the TLV should be down-casted to the ExtendedTlv type and the ExtendedTlv::GetLength() should be used instead.
Returns
The Length value.
References Tlv::mLength.
Referenced by ChannelMaskTlv::GetChannelMask(), CommissionerIdTlv::GetCommissionerIdLength(), ChannelMaskBaseTlv::GetFirstEntry(), CommissioningData::GetLength(), NetworkNameTlv::GetNetworkName(), ChildTableTlv::GetNumEntries(), ProvisioningUrlTlv::GetProvisioningUrlLength(), RouteTlv::GetRouteDataLength(), Tlv::GetSize(), SteeringDataTlv::GetSteeringDataLength(), UdpEncapsulationTlv::GetUdpLength(), VendorDataTlv::GetVendorDataLength(), VendorModelTlv::GetVendorModelLength(), VendorNameTlv::GetVendorNameLength(), VendorSwVersionTlv::GetVendorSwVersionLength(), Mle::HandleChildIdResponse(), Mle::HandleDiscoveryResponse(), DatasetManager::HandleGet(), Mle::HandleLeaderData(), SteeringDataTlv::IsCleared(), LeaderBase::IsJoiningEnabled(), ConnectivityTlv::IsSedBufferingIncluded(), ThreadRouterMaskTlv::IsValid(), ExtMacAddressTlv::IsValid(), RouteTlv::IsValid(), Address16Tlv::IsValid(), ModeTlv::IsValid(), ChannelTlv::IsValid(), TimeoutTlv::IsValid(), PanIdTlv::IsValid(), ExtendedPanIdTlv::IsValid(), TlvUint8::IsValid(), TlvUint16::IsValid(), PskcTlv::IsValid(), TlvUint32::IsValid(), NetworkMasterKeyTlv::IsValid(), LeaderDataTlv::IsValid(), NetworkKeySequenceTlv::IsValid(), MeshLocalPrefixTlv::IsValid(), ConnectivityTlv::IsValid(), SteeringDataTlv::IsValid(), NetworkDataTlv::IsValid(), BorderAgentLocatorTlv::IsValid(), Ip6AddressListTlv::IsValid(), MacCountersTlv::IsValid(), CommissionerSessionIdTlv::IsValid(), SecurityPolicyTlv::IsValid(), ActiveTimestampTlv::IsValid(), BatteryLevelTlv::IsValid(), StateTlv::IsValid(), SupplyVoltageTlv::IsValid(), JoinerUdpPortTlv::IsValid(), PendingTimestampTlv::IsValid(), DelayTimerTlv::IsValid(), ChildTableTlv::IsValid(), ChannelPagesTlv::IsValid(), MaxChildTimeoutTlv::IsValid(), VendorStackVersionTlv::IsValid(), UdpEncapsulationTlv::IsValid(), DiscoveryRequestTlv::IsValid(), DiscoveryResponseTlv::IsValid(), Dataset::RemoveTlv(), LeaderBase::SetNetworkData(), NetworkDataTlv::SetNetworkData(), and Dataset::SetTlv().
SetLength()
void SetLength (uint8_t aLength) inline
This method sets the Length value.
Parameters
[in] aLength The Length value.
References Tlv::GetSize(), Tlv::GetValue(), and Tlv::mLength.
Referenced by Mle::AppendAddressRegistration(), Dataset::AppendMleDatasetTlv(), Tlv::AppendTlv(), Mle::Discover(), Mle::HandleLeaderData(), ThreadRouterMaskTlv::Init(), ExtMacAddressTlv::Init(), RouteTlv::Init(), Address16Tlv::Init(), ThreadNetworkDataTlv::Init(), ModeTlv::Init(), ChannelTlv::Init(), TimeoutTlv::Init(), PanIdTlv::Init(), ExtendedPanIdTlv::Init(), TlvUint8::Init(), NetworkNameTlv::Init(), TlvUint16::Init(), PskcTlv::Init(), TlvUint32::Init(), NetworkMasterKeyTlv::Init(), LeaderDataTlv::Init(), NetworkKeySequenceTlv::Init(), MeshLocalPrefixTlv::Init(), ConnectivityTlv::Init(), SteeringDataTlv::Init(), NetworkDataTlv::Init(), BorderAgentLocatorTlv::Init(), Ip6AddressListTlv::Init(), CommissionerIdTlv::Init(), MacCountersTlv::Init(), CommissionerSessionIdTlv::Init(), SecurityPolicyTlv::Init(), ActiveTimestampTlv::Init(), BatteryLevelTlv::Init(), StateTlv::Init(), SupplyVoltageTlv::Init(), JoinerUdpPortTlv::Init(), PendingTimestampTlv::Init(), DelayTimerTlv::Init(), ChildTableTlv::Init(), ChannelPagesTlv::Init(), TypeListTlv::Init(), MaxChildTimeoutTlv::Init(), ChannelMaskBaseTlv::Init(), ChannelMaskTlv::Init(), EnergyListTlv::Init(), ProvisioningUrlTlv::Init(), VendorNameTlv::Init(), VendorModelTlv::Init(), VendorSwVersionTlv::Init(), VendorDataTlv::Init(), VendorStackVersionTlv::Init(), UdpEncapsulationTlv::Init(), DiscoveryRequestTlv::Init(), DiscoveryResponseTlv::Init(), DatasetManager::SendGetRequest(), EnergyScanServer::SendReport(), NetworkData::SendServerDataNotification(), ChannelMaskTlv::SetChannelMask(), CommissionerIdTlv::SetCommissionerId(), ExtendedTlv::SetLength(), NetworkNameTlv::SetNetworkName(), ProvisioningUrlTlv::SetProvisioningUrl(), RouteTlv::SetRouteDataLength(), Dataset::SetTlv(), UdpEncapsulationTlv::SetUdpLength(), VendorDataTlv::SetVendorData(), VendorModelTlv::SetVendorModel(), VendorNameTlv::SetVendorName(), and VendorSwVersionTlv::SetVendorSwVersion().
GetSize()
uint32_t GetSize (void) const
This method returns the TLV's total size (number of bytes) including Type, Length, and Value fields.
This method correctly returns the TLV size independent of whether the TLV is an Extended TLV or not.
Returns
The total size include Type, Length, and Value fields.
References Tlv::GetLength(), and Tlv::IsExtended().
Referenced by Tlv::AppendTo(), Tlv::Find(), Tlv::GetNext(), and Tlv::SetLength().
GetValue() [1/2]
uint8_t * GetValue (void)
This method returns a pointer to the Value.
This method can be used independent of whether the TLV is an Extended TLV or not.
Returns
A pointer to the value.
References Tlv::IsExtended().
Referenced by ChannelMaskTlv::GetChannelMask(), ChildTableTlv::GetEntry(), ChannelMaskBaseTlv::GetFirstEntry(), Ip6AddressListTlv::GetIp6Address(), Mle::HandleDiscoveryResponse(), LeaderBase::IsJoiningEnabled(), Tlv::SetLength(), and Dataset::SetTlv().
GetValue() [2/2]
const uint8_t * GetValue (void) const
This method returns a pointer to the Value.
This method can be used independent of whether the TLV is an Extended TLV or not.
Returns
A pointer to the value.
References Tlv::IsExtended().
GetNext() [1/2]
Tlv* GetNext (void) inline
This method returns a pointer to the next TLV.
This method correctly returns the next TLV independent of whether the current TLV is an Extended TLV or not.
Returns
A pointer to the next TLV.
References Tlv::GetSize().
Referenced by Tlv::GetNext().
GetNext() [2/2]
const Tlv* GetNext (void) const inline
This method returns a pointer to the next TLV.
This method correctly returns the next TLV independent of whether the current TLV is an Extended TLV or not.
Returns
A pointer to the next TLV.
References Tlv::AppendTlv(), Tlv::AppendTo(), Tlv::AppendUint16Tlv(), Tlv::AppendUint32Tlv(), Tlv::AppendUint8Tlv(), Tlv::Get(), Tlv::GetOffset(), Tlv::GetSize(), Tlv::GetValueOffset(), Tlv::ReadTlv(), Tlv::ReadUint16Tlv(), Tlv::ReadUint32Tlv(), and Tlv::ReadUint8Tlv().
AppendTo()
otError AppendTo (Message & aMessage) const
This method appends a TLV to the end of the message.
On success, this method grows the message by the size of the TLV.
Parameters
[in] aMessage A reference to the message to append to.
Return values
OT_ERROR_NONE Successfully appended the TLV to the message.
OT_ERROR_NO_BUFS Insufficient available buffers to grow the message.
References Message::Append(), Tlv::GetSize(), and OT_ASSERT.
Referenced by Mle::AppendActiveTimestamp(), Mle::AppendLeaderData(), Dataset::AppendMleDatasetTlv(), Mle::AppendPendingTimestamp(), Tlv::AppendUint16Tlv(), Tlv::AppendUint32Tlv(), Tlv::AppendUint8Tlv(), Mle::Discover(), Tlv::GetNext(), Mle::SendAnnounce(), PanIdQueryServer::SendConflict(), DatasetManager::SendGetResponse(), EnergyScanServer::SendReport(), and DatasetManager::SendSetRequest().
Get()
otError Get (const Message & aMessage, uint8_t aType, uint16_t aMaxSize, Tlv & aTlv) static
This static method reads the requested TLV out of aMessage.
This method can be used independent of whether the read TLV (from message) is an Extended TLV or not.
Parameters
[in] aMessage A reference to the message.
[in] aType The Type value to search for.
[in] aMaxSize Maximum number of bytes to read.
[out] aTlv A reference to the TLV that will be copied to.
Return values
OT_ERROR_NONE Successfully copied the TLV.
OT_ERROR_NOT_FOUND Could not find the TLV with Type aType.
References Tlv::Find(), Message::Read(), and SuccessOrExit.
Referenced by Tlv::GetNext(), ThreadTlv::GetTlv(), NetworkDiagnosticTlv::GetTlv(), Tlv::GetTlv(), Tlv::ReadUint16Tlv(), Tlv::ReadUint32Tlv(), and Tlv::ReadUint8Tlv().
GetOffset()
otError GetOffset (const Message & aMessage, uint8_t aType, uint16_t & aOffset) static
This static method obtains the offset of a TLV within aMessage.
This method can be used independent of whether the read TLV (from message) is an Extended TLV or not.
Parameters
[in] aMessage A reference to the message.
[in] aType The Type value to search for.
[out] aOffset A reference to the offset of the TLV.
Return values
OT_ERROR_NONE Successfully copied the TLV.
OT_ERROR_NOT_FOUND Could not find the TLV with Type aType.
References Tlv::Find().
Referenced by Tlv::GetNext(), NetworkDiagnosticTlv::GetOffset(), and Tlv::GetOffset().
GetValueOffset()
otError GetValueOffset (const Message & aMessage, uint8_t aType, uint16_t & aOffset, uint16_t & aLength) static
This static method finds the offset and length of a given TLV type.
This method can be used independent of whether the read TLV (from message) is an Extended TLV or not.
Parameters
[in] aMessage A reference to the message.
[in] aType The Type value to search for.
[out] aOffset The offset where the value starts.
[out] aLength The length of the value.
Return values
OT_ERROR_NONE Successfully found the TLV.
OT_ERROR_NOT_FOUND Could not find the TLV with Type aType.
References Tlv::Find(), and SuccessOrExit.
Referenced by Tlv::GetNext(), Tlv::GetValueOffset(), Mle::ReadChallengeOrResponse(), Tlv::ReadTlv(), and Mle::ReadTlvRequest().
ReadUint8Tlv()
otError ReadUint8Tlv (const Message & aMessage, uint8_t aType, uint8_t & aValue) static
This static method searches for a TLV with a given type in a message and reads its value as an uint8_t.
Parameters
[in] aMessage A reference to the message.
[in] aType The TLV type to search for.
[out] aValue A reference to a uint8_t to output the TLV's value.
Return values
OT_ERROR_NONE Successfully found the TLV and updated aValue.
OT_ERROR_NOT_FOUND Could not find the TLV with Type aType.
OT_ERROR_PARSE TLV was found but it was not well-formed and could not be parsed.
References Tlv::Get(), TlvUint8::GetUint8Value(), TlvUint8::IsValid(), OT_ERROR_NONE, OT_ERROR_PARSE, SuccessOrExit, and VerifyOrExit.
Referenced by Tlv::GetNext(), Mle::HandleChildUpdateRequest(), Mle::HandleChildUpdateResponse(), Mle::HandleParentResponse(), EnergyScanServer::HandleRequest(), and AnnounceBeginServer::HandleRequest().
ReadUint16Tlv()
otError ReadUint16Tlv (const Message & aMessage, uint8_t aType, uint16_t & aValue) static
This static method searches for a TLV with a given type in a message and reads its value as an uint16_t.
Parameters
[in] aMessage A reference to the message.
[in] aType The TLV type to search for.
[out] aValue A reference to a uint16_t to output the TLV's value.
Return values
OT_ERROR_NONE Successfully found the TLV and updated aValue.
OT_ERROR_NOT_FOUND Could not find the TLV with Type aType.
OT_ERROR_PARSE TLV was found but it was not well-formed and could not be parsed.
References Tlv::Get(), TlvUint16::GetUint16Value(), TlvUint16::IsValid(), OT_ERROR_NONE, OT_ERROR_PARSE, SuccessOrExit, and VerifyOrExit.
Referenced by Tlv::GetNext(), Mle::HandleAdvertisement(), Mle::HandleAnnounce(), Mle::HandleChildIdResponse(), Mle::HandleChildUpdateRequest(), Mle::HandleChildUpdateResponse(), Mle::HandleParentResponse(), PanIdQueryServer::HandleQuery(), EnergyScanServer::HandleRequest(), and AnnounceBeginServer::HandleRequest().
ReadUint32Tlv()
otError ReadUint32Tlv (const Message & aMessage, uint8_t aType, uint32_t & aValue) static
This static method searches for a TLV with a given type in a message and reads its value as an uint32_t.
Parameters
[in] aMessage A reference to the message.
[in] aType The TLV type to search for.
[out] aValue A reference to a uint32_t to output the TLV's value.
Return values
OT_ERROR_NONE Successfully found the TLV and updated aValue.
OT_ERROR_NOT_FOUND Could not find the TLV with Type aType.
OT_ERROR_PARSE TLV was found but it was not well-formed and could not be parsed.
References Tlv::Get(), TlvUint32::GetUint32Value(), TlvUint32::IsValid(), OT_ERROR_NONE, OT_ERROR_PARSE, SuccessOrExit, and VerifyOrExit.
Referenced by Tlv::GetNext(), Mle::HandleChildUpdateResponse(), and Mle::HandleParentResponse().
ReadTlv()
otError ReadTlv (const Message & aMessage, uint8_t aType, void * aValue, uint8_t aLength) static
This static method searches for a TLV with a given type in a message, ensures its length is same or larger than an expected minimum value, and then reads its value into a given buffer.
If the TLV length is smaller than the minimum length aLength, the TLV is considered invalid. In this case, this method returns OT_ERROR_PARSE and the aValue buffer is not updated.
If the TLV is length is larger than aLength, the TLV is considered valid, but only the first bytes of the value are read and copied into the aValue buffer.
Parameters
[in] aMessage A reference to the message.
[in] aType The TLV type to search for.
[out] aValue A buffer to output the value (must contain at least aLength bytes).
[in] aLength The expected (minimum) length of the TLV value.
Return values
OT_ERROR_NONE The TLV was found and read successfully. is updated.
OT_ERROR_NOT_FOUND Could not find the TLV with Type aType.
OT_ERROR_PARSE TLV was found but it was not well-formed and could not be parsed.
References Tlv::GetValueOffset(), OT_ERROR_PARSE, Message::Read(), SuccessOrExit, and VerifyOrExit.
Referenced by Tlv::GetNext().
AppendUint8Tlv()
otError AppendUint8Tlv (Message & aMessage, uint8_t aType, uint8_t aValue) static
This static method appends a simple TLV with a given type and an uint8_t value to a message.
On success this method grows the message by the size of the TLV.
Parameters
[in] aMessage A reference to the message to append to.
[in] aType The TLV type.
[in] aValue The TLV value (uint8_t).
Return values
OT_ERROR_NONE Successfully appended the TLV to the message.
OT_ERROR_NO_BUFS Insufficient available buffers to grow the message.
References Tlv::AppendTo(), TlvUint8::Init(), and TlvUint8::SetUint8Value().
Referenced by Mle::AppendLinkMargin(), Mle::AppendMode(), Mle::AppendScanMask(), Mle::AppendStatus(), and Tlv::GetNext().
AppendUint16Tlv()
otError AppendUint16Tlv (Message & aMessage, uint8_t aType, uint16_t aValue) static
This static method appends a simple TLV with a given type and an uint16_t value to a message.
On success this method grows the message by the size of the TLV.
Parameters
[in] aMessage A reference to the message to append to.
[in] aType The TLV type.
[in] aValue The TLV value (uint16_t).
Return values
OT_ERROR_NONE Successfully appended the TLV to the message.
OT_ERROR_NO_BUFS Insufficient available buffers to grow the message.
References Tlv::AppendTo(), TlvUint16::Init(), and TlvUint16::SetUint16Value().
Referenced by Mle::AppendAddress16(), Mle::AppendAddressRegistration(), Mle::AppendSourceAddress(), Mle::AppendVersion(), Tlv::GetNext(), Mle::SendAnnounce(), PanIdQueryServer::SendConflict(), NetworkData::SendServerDataNotification(), and DatasetManager::SendSetRequest().
AppendUint32Tlv()
otError AppendUint32Tlv (Message & aMessage, uint8_t aType, uint32_t aValue) static
This static method appends a (simple) TLV with a given type and an uint32_t value to a message.
On success this method grows the message by the size of the TLV.
Parameters
[in] aMessage A reference to the message to append to.
[in] aType The TLV type.
[in] aValue The TLV value (uint32_t).
Return values
OT_ERROR_NONE Successfully appended the TLV to the message.
OT_ERROR_NO_BUFS Insufficient available buffers to grow the message.
References Tlv::AppendTo(), TlvUint32::Init(), and TlvUint32::SetUint32Value().
Referenced by Mle::AppendLinkFrameCounter(), Mle::AppendMleFrameCounter(), Mle::AppendTimeout(), Tlv::GetNext(), and DatasetManager::SendSetRequest().
AppendTlv()
otError AppendTlv (Message & aMessage, uint8_t aType, const uint8_t * aValue, uint8_t aLength) static
This static method appends a TLV with a given type and value to a message.
On success this method grows the message by the size of the TLV.
Parameters
[in] aMessage A reference to the message to append to.
[in] aType The TLV type.
[in] aValue A buffer containing the TLV value.
[in] aLength The value length (in bytes).
Return values
OT_ERROR_NONE Successfully appended the TLV to the message.
OT_ERROR_NO_BUFS Insufficient available buffers to grow the message.
References Message::Append(), Tlv::kBaseTlvMaxLength, OT_ASSERT, OT_ERROR_NONE, OT_NOOP, Tlv::SetLength(), Tlv::SetType(), SuccessOrExit, and VerifyOrExit.
Referenced by Mle::AppendChallenge(), Mle::AppendNetworkData(), Mle::AppendResponse(), Mle::AppendTlvRequest(), Tlv::GetNext(), and DatasetManager::SendSetRequest().
Find()
otError Find (const Message & aMessage, uint8_t aType, uint16_t * aOffset, uint16_t * aSize, bool * aIsExtendedTlv) static private
This private static method searches within a given message for TLV type and outputs the TLV offset, size and whether it is an Extended TLV.
A NULL pointer can be used for output parameters aOffset, aSize, or aIsExtendedTlv if the parameter is not required.
Parameters
[in] aMessage A reference to the message to search within.
[in] aType The TLV type to search for.
[out] aOffset A pointer to a variable to output the offset to the start of the TLV.
[out] aSize A pointer to a variable to output the size (total number of bytes) of the TLV.
[out] aIsExtendedTlv A pointer to a boolean variable to output whether the found TLV is extended or not.
Return values
OT_ERROR_NONE Successfully found the TLV.
OT_ERROR_NOT_FOUND Could not find the TLV with Type aType.
References ExitNow, Message::GetLength(), ExtendedTlv::GetLength(), Message::GetOffset(), Tlv::GetSize(), Tlv::GetType(), Tlv::kExtendedLength, Tlv::mLength, OT_ERROR_NONE, OT_ERROR_NOT_FOUND, OT_NOOP, Message::Read(), and VerifyOrExit.
Referenced by Tlv::Get(), Tlv::GetOffset(), and Tlv::GetValueOffset().
Field Documentation
mType
uint8_t mType private
Referenced by Tlv::GetType(), and Tlv::SetType().
mLength
uint8_t mLength private
Referenced by Tlv::Find(), Tlv::GetLength(), ExtendedTlv::GetLength(), Tlv::IsExtended(), Tlv::SetLength(), and ExtendedTlv::SetLength().
The documentation for this class was generated from the following files:
tlvs.hpp
tlvs.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale