OpenThread: Message Class Reference
Message Class Reference
Core-coap
#include <coap_message.hpp>
Data Structures
struct Header
struct HelpData
Public Types
enum {
kVersion1 = 1, kMinHeaderLength = 4, kMaxHeaderLength = 512, kDefaultTokenLength = 2,
kTypeOffset = 4
}
enum { kBlockSzxBase = 4 }
enum BlockType { kBlockType1 = 1, kBlockType2 = 2 }
typedef otCoapCode Code
typedef otCoapType Type
Public Types inherited from Message
enum { kTypeIp6 = 0, kType6lowpan = 1, kTypeSupervision = 2, kTypeOther = 3 }
enum {
kSubTypeNone = 0, kSubTypeMleAnnounce = 1, kSubTypeMleDiscoverRequest = 2, kSubTypeMleDiscoverResponse = 3,
kSubTypeJoinerEntrust = 4, kSubTypeMplRetransmission = 5, kSubTypeMleGeneral = 6, kSubTypeJoinerFinalizeResponse = 7,
kSubTypeMleChildUpdateRequest = 8, kSubTypeMleDataResponse = 9, kSubTypeMleChildIdRequest = 10
}
enum {
kPriorityLow = OT_MESSAGE_PRIORITY_LOW, kPriorityNormal = OT_MESSAGE_PRIORITY_NORMAL, kPriorityHigh = OT_MESSAGE_PRIORITY_HIGH, kPriorityNet = OT_MESSAGE_PRIORITY_HIGH + 1,
kNumPriorities = 4
}
Public Member Functions
otError AppendBlockOption (BlockType aType, uint32_t aNum, bool aMore, otCoapBlockSize aSize)
otError AppendContentFormatOption (otCoapOptionContentFormat aContentFormat)
otError AppendMaxAgeOption (uint32_t aMaxAge)
otError AppendObserveOption (uint32_t aObserve)
otError AppendOption (uint16_t aNumber, uint16_t aLength, const void *aValue)
otError AppendProxyUriOption (const char *aProxyUri)
otError AppendStringOption (uint16_t aNumber, const char *aValue)
otError AppendUintOption (uint16_t aNumber, uint32_t aValue)
otError AppendUriPathOptions (const char *aUriPath)
otError AppendUriQueryOption (const char *aUriQuery)
Message * Clone (uint16_t aLength) const
Message * Clone (void) const
void Finish (void)
Code GetCode (void) const
uint16_t GetMessageId (void) const
Message * GetNextCoapMessage (void)
const Message * GetNextCoapMessage (void) const
uint16_t GetOptionStart (void) const
const uint8_t * GetToken (void) const
uint8_t GetTokenLength (void) const
Type GetType (void) const
uint8_t GetVersion (void) const
void Init (void)
void Init (Type aType, Code aCode)
otError Init (Type aType, Code aCode, const char *aUriPath)
bool IsAck (void) const
bool IsConfirmable (void) const
bool IsEmpty (void) const
bool IsNonConfirmable (void) const
bool IsRequest (void) const
bool IsReset (void) const
bool IsResponse (void) const
bool IsTokenEqual (const Message &aMessage) const
otError ParseHeader (void)
void SetCode (Code aCode)
otError SetDefaultResponseHeader (const Message &aRequest)
void SetMessageId (uint16_t aMessageId)
otError SetPayloadMarker (void)
otError SetToken (const uint8_t *aToken, uint8_t aTokenLength)
otError SetToken (uint8_t aTokenLength)
void SetType (Type aType)
void SetVersion (uint8_t aVersion)
Public Member Functions inherited from Message
void AddRss (int8_t aRss)
otError Append (const void *aBuf, uint16_t aLength)
void ClearChildMask (uint16_t aChildIndex)
void ClearDirectTransmission (void)
Message * Clone (uint16_t aLength) const
Message * Clone (void) const
int CopyTo (uint16_t aSourceOffset, uint16_t aDestinationOffset, uint16_t aLength, Message &aMessage) const
void DecrementTimeout (void)
void Free (void)
int8_t GetAverageRss (void) const
uint8_t GetBufferCount (void) const
uint8_t GetChannel (void) const
bool GetChildMask (uint16_t aChildIndex) const
uint32_t GetDatagramTag (void) const
bool GetDirectTransmission (void) const
bool GetDoNotEvict (void) const
uint16_t GetLength (void) const
uint16_t GetMeshDest (void) const
MessageQueue * GetMessageQueue (void) const
Message * GetNext (void) const
uint16_t GetOffset (void) const
uint16_t GetPanId (void) const
uint8_t GetPriority (void) const
PriorityQueue * GetPriorityQueue (void) const
const RssAverager & GetRssAverager (void) const
uint8_t GetSubType (void) const
uint8_t GetTimeout (void) const
bool GetTxSuccess (void) const
uint8_t GetType (void) const
bool IsChildPending (void) const
bool IsLinkSecurityEnabled (void) const
bool IsSubTypeMle (void) const
otError MoveOffset (int aDelta)
otError Prepend (const void *aBuf, uint16_t aLength)
uint16_t Read (uint16_t aOffset, uint16_t aLength, void *aBuf) const
void RemoveHeader (uint16_t aLength)
void SetChannel (uint8_t aChannel)
void SetChildMask (uint16_t aChildIndex)
void SetDatagramTag (uint32_t aTag)
void SetDirectTransmission (void)
void SetDoNotEvict (bool aDoNotEvict)
otError SetLength (uint16_t aLength)
void SetLinkSecurityEnabled (bool aEnabled)
void SetMeshDest (uint16_t aMeshDest)
otError SetOffset (uint16_t aOffset)
void SetPanId (uint16_t aPanId)
otError SetPriority (uint8_t aPriority)
void SetSubType (uint8_t aSubType)
void SetTimeout (uint8_t aTimeout)
void SetTxSuccess (bool aTxSuccess)
void SetType (uint8_t aType)
uint16_t UpdateChecksum (uint16_t aChecksum, uint16_t aOffset, uint16_t aLength) const
int Write (uint16_t aOffset, uint16_t aLength, const void *aBuf)
Public Member Functions inherited from Buffer
class Buffer * GetNextBuffer (void) const
void SetNextBuffer (class Buffer *buf)
Static Public Member Functions
static uint16_t GetHelpDataReserved (void)
Static Public Member Functions inherited from Message
static uint16_t UpdateChecksum (uint16_t aChecksum, uint16_t aValue)
static uint16_t UpdateChecksum (uint16_t aChecksum, const void *aBuf, uint16_t aLength)
Private Types
enum { kBlockNumMax = 0xFFFFF }
enum {
kOptionDeltaOffset = 4, kOptionDeltaMask = 0xf << kOptionDeltaOffset, kMaxTokenLength = OT_COAP_MAX_TOKEN_LENGTH, kVersionMask = 0xc0,
kVersionOffset = 6, kTypeMask = 0x30, kTokenLengthMask = 0x0f, kTokenLengthOffset = 0,
kTokenOffset = 4, kMaxOptionHeaderSize = 5, kOption1ByteExtension = 13, kOption2ByteExtension = 14,
kOption1ByteExtensionOffset = 13, kOption2ByteExtensionOffset = 269, kHelpDataAlignment = sizeof(uint16_t)
}
enum { kBlockSzxOffset = 0, kBlockMOffset = 3, kBlockNumOffset = 4 }
Private Member Functions
const HelpData & GetHelpData (void) const
HelpData & GetHelpData (void)
Private Attributes
OT_TOOL_PACKED_BEGIN struct ot::Coap::Message::Header OT_TOOL_PACKED_END
Friends
class OptionIterator
Additional Inherited Members
Data Fields inherited from otMessage
struct otMessage * mNext
A pointer to the next Message buffer.
Protected Attributes inherited from Buffer
union {
uint8_t mData [kBufferDataSize]
struct {
uint8_t mData [kHeadBufferDataSize]
MessageInfo mInfo
} mHead
} mBuffer
Detailed Description
This class implements CoAP message generation and parsing.
Member Typedef Documentation
Type
typedef otCoapType Type
CoAP Type values.
Code
typedef otCoapCode Code
CoAP Code values.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
kVersion1
Version 1.
kMinHeaderLength
Minimum header length.
kMaxHeaderLength
Maximum header length.
kDefaultTokenLength
Default token length.
kTypeOffset
The type offset in the first byte of a CoAP header.
BlockType
enum BlockType
CoAP Block1/Block2 Types
Enumerator
kBlockType1
kBlockType2
anonymous enum
anonymous enum
Enumerator
kBlockSzxBase
anonymous enum
anonymous enum private
Protocol Constants (RFC 7252).
Enumerator
kOptionDeltaOffset
Delta Offset.
kOptionDeltaMask
Delta Mask.
kMaxTokenLength
kVersionMask
Version mask as specified (RFC 7252).
kVersionOffset
Version offset as specified (RFC 7252).
kTypeMask
Type mask as specified (RFC 7252).
kTokenLengthMask
Token Length mask as specified (RFC 7252).
kTokenLengthOffset
Token Length offset as specified (RFC 7252).
kTokenOffset
Token offset as specified (RFC 7252).
kMaxOptionHeaderSize
Maximum size of an Option header.
kOption1ByteExtension
Indicates a 1 byte extension (RFC 7252).
kOption2ByteExtension
Indicates a 1 byte extension (RFC 7252).
kOption1ByteExtensionOffset
Delta/Length offset as specified (RFC 7252).
kOption2ByteExtensionOffset
Delta/Length offset as specified (RFC 7252).
kHelpDataAlignment
Alignment of help data.
anonymous enum
anonymous enum private
Enumerator
kBlockSzxOffset
kBlockMOffset
kBlockNumOffset
anonymous enum
anonymous enum private
Enumerator
kBlockNumMax
Member Function Documentation
Init() [1/3]
void Init (void)
This method initializes the CoAP header.
References Message::HelpData::Clear(), Message::GetHelpData(), Message::kMinHeaderLength, Message::kVersion1, Message::HelpData::mHeaderLength, Message::SetLength(), Message::SetOffset(), and Message::SetVersion().
Referenced by Message::Init(), DatasetManager::Register(), PanIdQueryServer::SendConflict(), CoapBase::SendEmptyMessage(), DatasetManager::SendGetRequest(), CoapBase::SendHeaderResponse(), EnergyScanServer::SendReport(), NetworkData::SendServerDataNotification(), DatasetManager::SendSetRequest(), and Message::SetDefaultResponseHeader().
Init() [2/3]
void Init (Type aType, Code aCode)
This method initializes the CoAP header with specific Type and Code.
Parameters
[in] aType The Type value.
[in] aCode The Code value.
References Message::Init(), Message::SetCode(), and Message::SetType().
Init() [3/3]
otError Init (Type aType, Code aCode, const char * aUriPath)
This method initializes the CoAP header with specific Type and Code.
Parameters
[in] aType The Type value.
[in] aCode The Code value.
[in] aUriPath A pointer to a NULL-terminated string.
Return values
OT_ERROR_NONE Successfully appended the option.
OT_ERROR_NO_BUFS The option length exceeds the buffer size.
References Message::AppendUriPathOptions(), Message::Init(), Message::kDefaultTokenLength, Message::SetToken(), and SuccessOrExit.
Finish()
void Finish (void)
This method writes header to the message. This must be called before sending the message.
References Message::GetHelpData(), Message::GetOptionStart(), and Message::Write().
Referenced by CoapBase::ProcessReceivedRequest(), CoapBase::SendEmptyMessage(), and CoapBase::SendMessage().
GetVersion()
uint8_t GetVersion (void) const inline
This method returns the Version value.
Returns
The Version value.
References Message::GetHelpData(), Message::kVersionMask, and Message::kVersionOffset.
SetVersion()
void SetVersion (uint8_t aVersion) inline
This method sets the Version value.
Parameters
[in] aVersion The Version value.
References Message::GetHelpData(), Message::kVersionMask, Message::kVersionOffset, Message::HelpData::mHeader, and Message::Header::mVersionTypeToken.
Referenced by Message::Init().
GetType()
Type GetType (void) const inline
This method returns the Type value.
Returns
The Type value.
References Message::GetHelpData(), Message::kTypeMask, Message::HelpData::mHeader, and Message::Header::mVersionTypeToken.
Referenced by CoapBase::FindRelatedRequest(), Message::IsAck(), Message::IsConfirmable(), Message::IsNonConfirmable(), Message::IsReset(), CoapBase::ProcessReceivedResponse(), CoapBase::SendHeaderResponse(), and CoapBase::SendMessage().
SetType()
void SetType (Type aType) inline
This method sets the Type value.
Parameters
[in] aType The Type value.
References Message::GetHelpData(), Message::kTypeMask, Message::HelpData::mHeader, and Message::Header::mVersionTypeToken.
Referenced by Message::Init().
GetCode()
Code GetCode (void) const inline
This method returns the Code value.
Returns
The Code value.
References Message::GetHelpData(), Message::Header::mCode, and Message::HelpData::mHeader.
Referenced by Message::Clone(), PanIdQueryServer::HandleQuery(), EnergyScanServer::HandleRequest(), AnnounceBeginServer::HandleRequest(), Message::IsEmpty(), Message::IsRequest(), Message::IsResponse(), and CoapBase::SendMessage().
SetCode()
void SetCode (Code aCode) inline
This method sets the Code value.
Parameters
[in] aCode The Code value.
References Message::GetHelpData(), Message::Header::mCode, and Message::HelpData::mHeader.
Referenced by Message::Init().
GetMessageId()
uint16_t GetMessageId (void) const inline
This method returns the Message ID value.
Returns
The Message ID value.
References Message::GetHelpData(), and ot::Encoding::BigEndian::HostSwap16().
Referenced by ResponsesQueue::FindMatchedResponse(), CoapBase::FindRelatedRequest(), CoapBase::SendEmptyMessage(), CoapBase::SendHeaderResponse(), and Message::SetDefaultResponseHeader().
SetMessageId()
void SetMessageId (uint16_t aMessageId) inline
This method sets the Message ID value.
Parameters
[in] aMessageId The Message ID value.
References Message::GetHelpData(), ot::Encoding::BigEndian::HostSwap16(), Message::HelpData::mHeader, and Message::Header::mMessageId.
Referenced by CoapBase::SendEmptyMessage(), CoapBase::SendHeaderResponse(), CoapBase::SendMessage(), and Message::SetDefaultResponseHeader().
GetTokenLength()
uint8_t GetTokenLength (void) const inline
This method returns the Token length.
Returns
The Token length.
References Message::GetHelpData(), Message::kTokenLengthMask, and Message::kTokenLengthOffset.
Referenced by Message::GetOptionStart(), Message::IsTokenEqual(), Message::ParseHeader(), CoapBase::SendHeaderResponse(), and Message::SetDefaultResponseHeader().
GetToken()
const uint8_t* GetToken (void) const inline
This method returns a pointer to the Token value.
Returns
A pointer to the Token value.
References Message::GetHelpData(), Message::HelpData::mHeader, Message::Header::mToken, and Message::SetToken().
Referenced by Message::IsTokenEqual(), CoapBase::SendHeaderResponse(), and Message::SetDefaultResponseHeader().
SetToken() [1/2]
otError SetToken (const uint8_t * aToken, uint8_t aTokenLength)
This method sets the Token value and length.
Parameters
[in] aToken A pointer to the Token value.
[in] aTokenLength The Length of aToken.
Return values
OT_ERROR_NONE Successfully set the token value.
OT_ERROR_NO_BUFS Insufficient message buffers available to set the token value.
References Message::GetHelpData(), Message::kTokenLengthMask, Message::kTokenLengthOffset, Message::HelpData::mHeader, Message::HelpData::mHeaderLength, Message::Header::mVersionTypeToken, and Message::SetLength().
Referenced by Message::GetToken(), Message::Init(), CoapBase::SendHeaderResponse(), Message::SetDefaultResponseHeader(), and Message::SetToken().
SetToken() [2/2]
otError SetToken (uint8_t aTokenLength)
This method sets the Token length and randomizes its value.
Parameters
[in] aTokenLength The Length of a Token to set.
Return values
OT_ERROR_NONE Successfully set the token value.
OT_ERROR_NO_BUFS Insufficient message buffers available to set the token value.
References ot::Random::Crypto::FillBuffer(), Message::kMaxTokenLength, OT_ASSERT, and Message::SetToken().
IsTokenEqual()
bool IsTokenEqual (const Message & aMessage) const inline
This method checks if Tokens in two CoAP headers are equal.
Parameters
[in] aMessage A header to compare.
Return values
TRUE If two Tokens are equal.
FALSE If Tokens differ in length or value.
References Message::AppendBlockOption(), Message::AppendContentFormatOption(), Message::AppendMaxAgeOption(), Message::AppendObserveOption(), Message::AppendOption(), Message::AppendProxyUriOption(), Message::AppendStringOption(), Message::AppendUintOption(), Message::AppendUriPathOptions(), Message::AppendUriQueryOption(), Message::GetToken(), Message::GetTokenLength(), and Message::SetPayloadMarker().
Referenced by CoapBase::FindRelatedRequest(), and CoapBase::ProcessReceivedResponse().
AppendOption()
otError AppendOption (uint16_t aNumber, uint16_t aLength, const void * aValue)
This method appends a CoAP option.
Parameters
[in] aOption The CoAP Option.
Return values
OT_ERROR_NONE Successfully appended the option.
OT_ERROR_INVALID_ARGS The option type is not equal or greater than the last option type.
OT_ERROR_NO_BUFS The option length exceeds the buffer size.
References Message::Append(), Message::GetHelpData(), Message::GetLength(), Message::kMaxHeaderLength, Message::kMaxOptionHeaderSize, Message::kOption1ByteExtension, Message::kOption1ByteExtensionOffset, Message::kOption2ByteExtension, Message::kOption2ByteExtensionOffset, Message::kOptionDeltaMask, Message::kOptionDeltaOffset, Message::HelpData::mHeaderLength, Message::HelpData::mOptionLast, OT_ERROR_INVALID_ARGS, OT_ERROR_NO_BUFS, OT_ERROR_NONE, SuccessOrExit, and VerifyOrExit.
Referenced by Message::AppendStringOption(), Message::AppendUintOption(), Message::AppendUriPathOptions(), and Message::IsTokenEqual().
AppendUintOption()
otError AppendUintOption (uint16_t aNumber, uint32_t aValue)
This method appends an unsigned integer CoAP option as specified in https://tools.ietf.org/html/rfc7252#section-3.2
Parameters
[in] aNumber The CoAP Option number.
[in] aValue The CoAP Option unsigned integer value.
Return values
OT_ERROR_NONE Successfully appended the option.
OT_ERROR_INVALID_ARGS The option type is not equal or greater than the last option type.
OT_ERROR_NO_BUFS The option length exceeds the buffer size.
References Message::AppendOption(), and ot::Encoding::BigEndian::HostSwap32().
Referenced by Message::AppendBlockOption(), Message::AppendContentFormatOption(), Message::AppendMaxAgeOption(), Message::AppendObserveOption(), and Message::IsTokenEqual().
AppendStringOption()
otError AppendStringOption (uint16_t aNumber, const char * aValue)
This method appends a string CoAP option.
Parameters
[in] aNumber The CoAP Option number.
[in] aValue The CoAP Option string value.
Return values
OT_ERROR_NONE Successfully appended the option.
OT_ERROR_INVALID_ARGS The option type is not equal or greater than the last option type.
OT_ERROR_NO_BUFS The option length exceeds the buffer size.
References Message::AppendOption().
Referenced by Message::AppendProxyUriOption(), Message::AppendUriPathOptions(), Message::AppendUriQueryOption(), and Message::IsTokenEqual().
AppendObserveOption()
otError AppendObserveOption (uint32_t aObserve)
This method appends an Observe option.
Parameters
[in] aObserve Observe field value.
Return values
OT_ERROR_NONE Successfully appended the option.
OT_ERROR_INVALID_ARGS The option type is not equal or greater than the last option type.
OT_ERROR_NO_BUFS The option length exceeds the buffer size.
References Message::AppendUintOption(), and OT_COAP_OPTION_OBSERVE.
Referenced by Message::IsTokenEqual().
AppendUriPathOptions()
otError AppendUriPathOptions (const char * aUriPath)
This method appends a Uri-Path option.
Parameters
[in] aUriPath A pointer to a NULL-terminated string.
Return values
OT_ERROR_NONE Successfully appended the option.
OT_ERROR_INVALID_ARGS The option type is not equal or greater than the last option type.
OT_ERROR_NO_BUFS The option length exceeds the buffer size.
References Message::AppendOption(), Message::AppendStringOption(), OT_COAP_OPTION_URI_PATH, OT_ERROR_NONE, and SuccessOrExit.
Referenced by Message::Init(), and Message::IsTokenEqual().
AppendBlockOption()
otError AppendBlockOption (Message::BlockType aType, uint32_t aNum, bool aMore, otCoapBlockSize aSize)
This method appends a Block option
Parameters
[in] aType Type of block option, 1 or 2.
[in] aNum Current block number.
[in] aMore Boolean to indicate more blocks are to be sent.
[in] aSize Maximum block size.
Return values
OT_ERROR_NONE Successfully appended the option.
OT_ERROR_INVALID_ARGS The option type is not equal or greater than the last option type.
OT_ERROR_NO_BUFS The option length exceeds the buffer size.
References Message::AppendUintOption(), Message::kBlockMOffset, Message::kBlockNumMax, Message::kBlockNumOffset, Message::kBlockType1, Message::kBlockType2, OT_COAP_BLOCK_SIZE_1024, OT_COAP_OPTION_BLOCK1, OT_COAP_OPTION_BLOCK2, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, and VerifyOrExit.
Referenced by Message::IsTokenEqual().
AppendProxyUriOption()
otError AppendProxyUriOption (const char * aProxyUri)
This method appends a Proxy-Uri option.
Parameters
[in] aProxyUri A pointer to a NULL-terminated string.
Return values
OT_ERROR_NONE Successfully appended the option.
OT_ERROR_INVALID_ARGS The option type is not equal or greater than the last option type.
OT_ERROR_NO_BUFS The option length exceeds the buffer size.
References Message::AppendStringOption(), and OT_COAP_OPTION_PROXY_URI.
Referenced by Message::IsTokenEqual().
AppendContentFormatOption()
otError AppendContentFormatOption (otCoapOptionContentFormat aContentFormat)
This method appends a Content-Format option.
Parameters
[in] aContentFormat The Content Format value.
Return values
OT_ERROR_NONE Successfully appended the option.
OT_ERROR_INVALID_ARGS The option type is not equal or greater than the last option type.
OT_ERROR_NO_BUFS The option length exceeds the buffer size.
References Message::AppendUintOption(), and OT_COAP_OPTION_CONTENT_FORMAT.
Referenced by Message::IsTokenEqual().
AppendMaxAgeOption()
otError AppendMaxAgeOption (uint32_t aMaxAge)
This method appends a Max-Age option.
Parameters
[in] aMaxAge The Max-Age value.
Return values
OT_ERROR_NONE Successfully appended the option.
OT_ERROR_INVALID_ARGS The option type is not equal or greater than the last option type.
OT_ERROR_NO_BUFS The option length exceeds the buffer size.
References Message::AppendUintOption(), and OT_COAP_OPTION_MAX_AGE.
Referenced by Message::IsTokenEqual().
AppendUriQueryOption()
otError AppendUriQueryOption (const char * aUriQuery)
This method appends a single Uri-Query option.
Parameters
[in] aUriQuery A pointer to NULL-terminated string, which should contain a single key=value pair.
Return values
OT_ERROR_NONE Successfully appended the option.
OT_ERROR_INVALID_ARGS The option type is not equal or greater than the last option type.
OT_ERROR_NO_BUFS The option length exceeds the buffer size.
References Message::AppendStringOption(), and OT_COAP_OPTION_URI_QUERY.
Referenced by Message::IsTokenEqual().
SetPayloadMarker()
otError SetPayloadMarker (void)
This method adds Payload Marker indicating beginning of the payload to the CoAP header.
It also set offset to the start of payload.
Return values
OT_ERROR_NONE Payload Marker successfully added.
OT_ERROR_NO_BUFS Message Payload Marker exceeds the buffer size.
References Message::Append(), Message::GetHelpData(), Message::GetLength(), Message::kMaxHeaderLength, Message::HelpData::mHeaderLength, OT_ERROR_NO_BUFS, OT_ERROR_NONE, Message::SetOffset(), SuccessOrExit, and VerifyOrExit.
Referenced by Message::IsTokenEqual(), DatasetManager::Register(), PanIdQueryServer::SendConflict(), DatasetManager::SendGetRequest(), DatasetManager::SendGetResponse(), EnergyScanServer::SendReport(), NetworkData::SendServerDataNotification(), and DatasetManager::SendSetRequest().
GetOptionStart()
uint16_t GetOptionStart (void) const inline
This method returns the offset of the first CoAP option.
Returns
The offset of the first CoAP option.
References Message::GetTokenLength(), Message::kMinHeaderLength, Message::ParseHeader(), and Message::SetDefaultResponseHeader().
Referenced by Message::Finish(), OptionIterator::GetFirstOption(), OptionIterator::Init(), and CoapBase::SendMessage().
ParseHeader()
otError ParseHeader (void)
This method parses CoAP header and moves offset end of CoAP header.
Return values
OT_ERROR_NONE Successfully parsed CoAP header from the message.
OT_ERROR_PARSE Failed to parse the CoAP header.
References Message::HelpData::Clear(), OptionIterator::GetFirstOption(), Message::GetHelpData(), OptionIterator::GetNextOption(), Message::GetOffset(), Message::GetTokenLength(), OptionIterator::Init(), Message::kMaxTokenLength, Buffer::mBuffer, Message::HelpData::mHeaderLength, Message::HelpData::mHeaderOffset, otCoapOptionIterator::mNextOptionOffset, Message::MoveOffset(), OT_ASSERT, OT_ERROR_NONE, OT_ERROR_PARSE, Message::Read(), SuccessOrExit, and VerifyOrExit.
Referenced by Message::GetOptionStart(), and CoapBase::Receive().
SetDefaultResponseHeader()
otError SetDefaultResponseHeader (const Message & aRequest)
This method sets a default response header based on request header.
Parameters
[in] aRequest The request message.
Return values
OT_ERROR_NONE Successfully set the default response header.
OT_ERROR_NO_BUFS Insufficient message buffers available to set the default response header.
References Message::GetMessageId(), Message::GetToken(), Message::GetTokenLength(), Message::Init(), OT_COAP_CODE_CHANGED, OT_COAP_TYPE_ACKNOWLEDGMENT, Message::SetMessageId(), and Message::SetToken().
Referenced by Message::GetOptionStart(), and DatasetManager::SendGetResponse().
IsEmpty()
bool IsEmpty (void) const inline
This method checks if a header is an empty message header.
Return values
TRUE Message is an empty message header.
FALSE Message is not an empty message header.
References Message::GetCode().
Referenced by CoapBase::ProcessReceivedResponse().
IsRequest()
bool IsRequest (void) const inline
This method checks if a header is a request header.
Return values
TRUE Message is a request header.
FALSE Message is not a request header.
References Message::GetCode(), OT_COAP_CODE_DELETE, and OT_COAP_CODE_GET.
Referenced by CoapBase::ProcessReceivedResponse(), CoapBase::Receive(), and CoapBase::SendHeaderResponse().
IsResponse()
bool IsResponse (void) const inline
This method checks if a header is a response header.
Return values
TRUE Message is a response header.
FALSE Message is not a response header.
References Message::GetCode(), and OT_COAP_CODE_RESPONSE_MIN.
Referenced by CoapBase::ProcessReceivedResponse().
IsConfirmable()
bool IsConfirmable (void) const inline
This method checks if a header is a CON message header.
Return values
TRUE Message is a CON message header.
FALSE Message is not is a CON message header.
References Message::GetType(), and OT_COAP_TYPE_CONFIRMABLE.
Referenced by PanIdQueryServer::HandleQuery(), EnergyScanServer::HandleRequest(), AnnounceBeginServer::HandleRequest(), CoapBase::ProcessReceivedResponse(), CoapBase::Receive(), CoapBase::SendEmptyAck(), CoapBase::SendEmptyMessage(), and CoapBase::SendMessage().
IsNonConfirmable()
bool IsNonConfirmable (void) const inline
This method checks if a header is a NON message header.
Return values
TRUE Message is a NON message header.
FALSE Message is not is a NON message header.
References Message::GetType(), and OT_COAP_TYPE_NON_CONFIRMABLE.
Referenced by CoapBase::ProcessReceivedResponse(), and CoapBase::SendMessage().
IsAck()
bool IsAck (void) const inline
This method checks if a header is a ACK message header.
Return values
TRUE Message is a ACK message header.
FALSE Message is not is a ACK message header.
References Message::GetType(), and OT_COAP_TYPE_ACKNOWLEDGMENT.
IsReset()
bool IsReset (void) const inline
This method checks if a header is a RST message header.
Return values
TRUE Message is a RST message header.
FALSE Message is not is a RST message header.
References Message::Clone(), Message::GetType(), and OT_COAP_TYPE_RESET.
Clone() [1/2]
Message * Clone (uint16_t aLength) const
This method creates a copy of this CoAP message.
It allocates the new message from the same message pool as the original one and copies aLength octets of the payload. The Type, SubType, LinkSecurity, Offset, InterfaceId, and Priority fields on the cloned message are also copied from the original one.
Parameters
[in] aLength Number of payload bytes to copy.
Returns
A pointer to the message or NULL if insufficient message buffers are available.
References Message::Clone(), Message::GetCode(), Message::GetHelpData(), OT_COAP_CODE_BAD_GATEWAY, OT_COAP_CODE_BAD_OPTION, OT_COAP_CODE_BAD_REQUEST, OT_COAP_CODE_CHANGED, OT_COAP_CODE_CONTENT, OT_COAP_CODE_CREATED, OT_COAP_CODE_DELETE, OT_COAP_CODE_DELETED, OT_COAP_CODE_EMPTY, OT_COAP_CODE_FORBIDDEN, OT_COAP_CODE_GATEWAY_TIMEOUT, OT_COAP_CODE_GET, OT_COAP_CODE_INTERNAL_ERROR, OT_COAP_CODE_METHOD_NOT_ALLOWED, OT_COAP_CODE_NOT_ACCEPTABLE, OT_COAP_CODE_NOT_FOUND, OT_COAP_CODE_NOT_IMPLEMENTED, OT_COAP_CODE_POST, OT_COAP_CODE_PRECONDITION_FAILED, OT_COAP_CODE_PROXY_NOT_SUPPORTED, OT_COAP_CODE_PUT, OT_COAP_CODE_REQUEST_TOO_LARGE, OT_COAP_CODE_RESPONSE_MIN, OT_COAP_CODE_SERVICE_UNAVAILABLE, OT_COAP_CODE_UNAUTHORIZED, OT_COAP_CODE_UNSUPPORTED_FORMAT, OT_COAP_CODE_VALID, OT_NOOP, and VerifyOrExit.
Referenced by CoapBase::CopyAndEnqueueMessage(), ResponsesQueue::EnqueueResponse(), ResponsesQueue::GetMatchedResponseCopy(), and CoapBase::SendCopy().
Clone() [2/2]
Message* Clone (void) const inline
This method creates a copy of the message.
It allocates the new message from the same message pool as the original one and copies the entire payload. The Type, SubType, LinkSecurity, Offset, InterfaceId, and Priority fields on the cloned message are also copied from the original one.
Returns
A pointer to the message or NULL if insufficient message buffers are available.
References Message::Clone(), and Message::GetLength().
Referenced by Message::Clone(), and Message::IsReset().
GetHelpDataReserved()
static uint16_t GetHelpDataReserved (void) inline static
This method returns the minimal reserved bytes required for CoAP message.
References Message::kHelpDataAlignment.
GetNextCoapMessage() [1/2]
Message* GetNextCoapMessage (void) inline
This method returns a pointer to the next message after this as a Coap::Message.
This method should be used when the message is in a Coap::MessageQueue (i.e., a queue containing only CoAP messages).
Returns
A pointer to the next message in the queue or NULL if at the end of the queue.
References Message::GetNext().
Referenced by CoapBase::AbortTransaction(), CoapBase::ClearRequests(), ResponsesQueue::FindMatchedResponse(), CoapBase::FindRelatedRequest(), CoapBase::HandleRetransmissionTimer(), ResponsesQueue::HandleTimer(), and ResponsesQueue::UpdateQueue().
GetNextCoapMessage() [2/2]
const Message* GetNextCoapMessage (void) const inline
This method returns a pointer to the next message after this as a Coap::Message.
This method should be used when the message is in a Coap::MessageQueue (i.e., a queue containing only CoAP messages).
Returns
A pointer to the next message in the queue or NULL if at the end of the queue.
References Message::GetNext().
GetHelpData() [1/2]
const HelpData& GetHelpData (void) const inline private
References Message::kHelpDataAlignment, Buffer::mBuffer, OT_ALIGN, and OT_STATIC_ASSERT().
Referenced by Message::AppendOption(), Message::Clone(), Message::Finish(), Message::GetCode(), OptionIterator::GetFirstOption(), Message::GetMessageId(), Message::GetToken(), Message::GetTokenLength(), Message::GetType(), Message::GetVersion(), Message::Init(), OptionIterator::Init(), Message::ParseHeader(), Message::SetCode(), Message::SetMessageId(), Message::SetPayloadMarker(), Message::SetToken(), Message::SetType(), and Message::SetVersion().
GetHelpData() [2/2]
HelpData& GetHelpData (void) inline private
References Message::GetHelpData().
Referenced by Message::GetHelpData().
Friends And Related Function Documentation
OptionIterator
friend class OptionIterator friend
Field Documentation
OT_TOOL_PACKED_END
OT_TOOL_PACKED_BEGIN struct ot::Coap::Message::Header OT_TOOL_PACKED_END private
The documentation for this class was generated from the following files:
coap_message.hpp
coap_message.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale