OpenThread: DomainName Class Reference
DomainName Class Reference
Core-mac
#include <mac_types.hpp>
Public Types
enum { kMaxSize = 16 }
Public Member Functions
DomainName (void)
const char * GetAsCString (void) const
NameData GetAsData (void) const
otError Set (const NameData &aNameData)
Private Attributes
char m8 [kMaxSize+1]
Byte values.
Detailed Description
This structure represents a Thread Domain Name.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
kMaxSize
Constructor & Destructor Documentation
DomainName()
DomainName (void) inline
This constructor initializes the Thread Domain Name as an empty string.
References otExtAddress::m8.
Member Function Documentation
GetAsCString()
const char* GetAsCString (void) const inline
This method gets the Thread Domain Name as a null terminated C string.
Returns
The Domain Name as a null terminated C string array.
References otExtAddress::m8, and ExtAddress::Set().
GetAsData()
NameData GetAsData (void) const
This method gets the Thread Domain Name as NameData.
Returns
The Domain Name as NameData.
References otExtAddress::m8, and ot::StringLength().
Set()
otError Set (const NameData & aNameData)
This method sets the Thread Domain Name.
Parameters
[in] aNameData A reference to name data.
Return values
OT_ERROR_NONE Successfully set the Thread Domain Name.
OT_ERROR_ALREADY The name is already set to the same string.
OT_ERROR_INVALID_ARGS Given name is too long.
References NameData::GetBuffer(), NameData::GetLength(), otExtAddress::m8, OT_ERROR_ALREADY, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, ot::StringLength(), and VerifyOrExit.
Referenced by Mac::SetDomainName().
Field Documentation
m8
char m8[kMaxSize+1] private
Byte values.
The documentation for this class was generated from the following files:
mac_types.hpp
mac_types.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale