OpenThread: OptionIterator Class Reference
OptionIterator Class Reference
Core-coap
#include <coap_message.hpp>
Public Member Functions
const otCoapOption * GetFirstOption (void)
const otCoapOption * GetFirstOptionMatching (uint16_t aOption)
const otCoapOption * GetNextOption (void)
const otCoapOption * GetNextOptionMatching (uint16_t aOption)
otError GetOptionValue (uint64_t &aValue) const
otError GetOptionValue (void *aValue) const
otError Init (const Message *aMessage)
Private Member Functions
void ClearOption (void)
const Message & GetMessage (void) const
Additional Inherited Members
Data Fields inherited from otCoapOptionIterator
const otMessage * mMessage
CoAP message.
uint16_t mNextOptionOffset
Byte offset of next option.
otCoapOption mOption
CoAP message option.
Detailed Description
This class acts as an iterator for CoAP options.
Member Function Documentation
Init()
otError Init (const Message * aMessage)
Initialize the state of the iterator to iterate over the given message.
Return values
OT_ERROR_NONE Successfully initialized
OT_ERROR_PARSE Message state is inconsistent
References Message::GetHelpData(), Message::GetLength(), Message::GetOptionStart(), Message::HelpData::mHeaderOffset, OT_ERROR_NONE, OT_ERROR_PARSE, and VerifyOrExit.
Referenced by Message::ParseHeader(), CoapBase::ProcessReceivedRequest(), CoapBase::ProcessReceivedResponse(), and CoapBase::SendMessage().
GetFirstOptionMatching()
const otCoapOption * GetFirstOptionMatching (uint16_t aOption)
This method returns a pointer to the first option matching the given option number.
The internal option pointer is advanced until matching option is seen, if no matching option is seen, the iterator will advance to the end of the options block.
Parameters
[in] aOption Option number to look for.
Returns
A pointer to the first matching option. If no option matching aOption is seen, NULL pointer is returned.
Referenced by CoapBase::ProcessReceivedResponse(), and CoapBase::SendMessage().
GetFirstOption()
const otCoapOption * GetFirstOption (void)
This method returns a pointer to the first option.
Returns
A pointer to the first option. If no option is present NULL pointer is returned.
References Message::GetHelpData(), Message::GetLength(), Message::GetOptionStart(), and Message::HelpData::mHeaderOffset.
Referenced by Message::ParseHeader(), and CoapBase::ProcessReceivedRequest().
GetNextOptionMatching()
const otCoapOption * GetNextOptionMatching (uint16_t aOption)
This method returns a pointer to the next option matching the given option number.
The internal option pointer is advanced until matching option is seen, if no matching option is seen, the iterator will advance to the end of the options block.
Parameters
[in] aOption Option number to look for.
Returns
A pointer to the next matching option (relative to current iterator position). If no option matching aOption is seen, NULL pointer is returned.
GetNextOption()
const otCoapOption * GetNextOption (void)
This method returns a pointer to the next option.
Returns
A pointer to the next option. If no more options are present NULL pointer is returned.
References ExitNow, Message::GetLength(), Message::kMaxOptionHeaderSize, Message::kOption1ByteExtension, Message::kOption1ByteExtensionOffset, Message::kOption2ByteExtension, Message::kOption2ByteExtensionOffset, otCoapOption::mNumber, OT_ERROR_NONE, OT_ERROR_NOT_FOUND, OT_ERROR_PARSE, Message::Read(), and VerifyOrExit.
Referenced by Message::ParseHeader(), and CoapBase::ProcessReceivedRequest().
GetOptionValue() [1/2]
otError GetOptionValue (uint64_t & aValue) const
This function fills current option value into aValue. The option is assumed to be an unsigned integer.
Parameters
[out] aValue Buffer to store the option value.
Return values
OT_ERROR_NONE Successfully filled value.
OT_ERROR_NOT_FOUND No more options, aIterator->mNextOptionOffset is set to offset of payload.
OT_ERROR_NO_BUFS Value is too long to fit in a uint64_t.
References OT_ERROR_NO_BUFS, OT_ERROR_NONE, SuccessOrExit, and VerifyOrExit.
Referenced by CoapBase::ProcessReceivedRequest(), and CoapBase::SendMessage().
GetOptionValue() [2/2]
otError GetOptionValue (void * aValue) const
This function fills current option value into aValue.
Parameters
[out] aValue Buffer to store the option value. This buffer is assumed to be sufficiently large (see otCoapOption::mLength).
Return values
OT_ERROR_NONE Successfully filled value.
OT_ERROR_NOT_FOUND No more options, mNextOptionOffset is set to offset of payload.
References OT_ERROR_NONE, OT_ERROR_NOT_FOUND, OT_ERROR_PARSE, Message::Read(), and VerifyOrExit.
ClearOption()
void ClearOption (void) inline private
GetMessage()
const Message& GetMessage (void) const inline private
The documentation for this class was generated from the following files:
coap_message.hpp
coap_message.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale