OpenThread: UdpHeader Class Reference
UdpHeader Class Reference
Core-udp
#include <udp6.hpp>
Public Member Functions
uint16_t GetChecksum (void) const
uint16_t GetDestinationPort (void) const
uint16_t GetLength (void) const
uint16_t GetSourcePort (void) const
void SetChecksum (uint16_t aChecksum)
void SetDestinationPort (uint16_t aPort)
void SetLength (uint16_t aLength)
void SetSourcePort (uint16_t aPort)
Static Public Member Functions
static uint8_t GetChecksumOffset (void)
static uint8_t GetLengthOffset (void)
Additional Inherited Members
Private Attributes inherited from UdpHeaderPoD
uint16_t mChecksum
uint16_t mDestination
uint16_t mLength
uint16_t mSource
Detailed Description
This class implements UDP header generation and parsing.
Member Function Documentation
GetSourcePort()
uint16_t GetSourcePort (void) const inline
This method returns the UDP Source Port.
Returns
The UDP Source Port.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by Lowpan::CompressUdp(), and Udp::HandleMessage().
SetSourcePort()
void SetSourcePort (uint16_t aPort) inline
This method sets the UDP Source Port.
Parameters
[in] aPort The UDP Source Port.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by Lowpan::DecompressUdpHeader(), and Udp::SendDatagram().
GetDestinationPort()
uint16_t GetDestinationPort (void) const inline
This method returns the UDP Destination Port.
Returns
The UDP Destination Port.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by Filter::Accept(), Lowpan::CompressUdp(), MeshForwarder::GetFramePriority(), Udp::HandleMessage(), and Ip6::ProcessReceiveCallback().
SetDestinationPort()
void SetDestinationPort (uint16_t aPort) inline
This method sets the UDP Destination Port.
Parameters
[in] aPort The UDP Destination Port.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by Lowpan::DecompressUdpHeader(), and Udp::SendDatagram().
GetLength()
uint16_t GetLength (void) const inline
This method returns the UDP Length.
Returns
The UDP Length.
References ot::Encoding::BigEndian::HostSwap16().
SetLength()
void SetLength (uint16_t aLength) inline
This method sets the UDP Length.
Parameters
[in] aLength The UDP Length.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by Lowpan::DecompressUdpHeader(), and Udp::SendDatagram().
GetChecksum()
uint16_t GetChecksum (void) const inline
This method returns the UDP Checksum.
Returns
The UDP Checksum.
References ot::Encoding::BigEndian::HostSwap16().
SetChecksum()
void SetChecksum (uint16_t aChecksum) inline
This method sets the UDP Checksum.
Parameters
[in] aChecksum The UDP Checksum.
References ot::Encoding::BigEndian::HostSwap16().
Referenced by Lowpan::DecompressUdpHeader(), and Udp::SendDatagram().
GetLengthOffset()
static uint8_t GetLengthOffset (void) inline static
This static method returns the byte offset for the UDP Length.
Returns
The byte offset for the UDP Length.
Referenced by Lowpan::CompressUdp().
GetChecksumOffset()
static uint8_t GetChecksumOffset (void) inline static
This static method returns the byte offset for the UDP Checksum.
Returns
The byte offset for the UDP Checksum.
References ot::Ip6::OT_TOOL_PACKED_END.
Referenced by Lowpan::CompressUdp(), and Udp::UpdateChecksum().
The documentation for this class was generated from the following file:
udp6.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale