OpenThread: AesCcm Class Reference
AesCcm Class Reference
Core-security
#include <aes_ccm.hpp>
Public Member Functions
void Finalize (void *aTag, uint8_t *aTagLength)
void Header (const void *aHeader, uint32_t aHeaderLength)
otError Init (uint32_t aHeaderLength, uint32_t aPlainTextLength, uint8_t aTagLength, const void *aNonce, uint8_t aNonceLength)
void Payload (void *aPlainText, void *aCipherText, uint32_t aLength, bool aEncrypt)
void SetKey (const uint8_t *aKey, uint16_t aKeyLength)
Private Types
enum { kTagLengthMin = 4 }
Private Attributes
uint8_t mBlock [AesEcb::kBlockSize]
uint16_t mBlockLength
uint8_t mCtr [AesEcb::kBlockSize]
uint16_t mCtrLength
uint8_t mCtrPad [AesEcb::kBlockSize]
AesEcb mEcb
uint32_t mHeaderCur
uint32_t mHeaderLength
uint8_t mNonceLength
uint32_t mPlainTextCur
uint32_t mPlainTextLength
uint8_t mTagLength
Detailed Description
This class implements AES CCM computation.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
kTagLengthMin
Member Function Documentation
SetKey()
void SetKey (const uint8_t * aKey, uint16_t aKeyLength)
This method sets the key.
Parameters
[in] aKey A pointer to the key.
[in] aKeyLength Length of the key in bytes.
References AesCcm::mEcb, and AesEcb::SetKey().
Referenced by Mle::HandleUdpReceive(), otCryptoAesCcm(), Mac::ProcessReceiveSecurity(), TxFrame::ProcessTransmitAesCcm(), and Mle::SendMessage().
Init()
otError Init (uint32_t aHeaderLength, uint32_t aPlainTextLength, uint8_t aTagLength, const void * aNonce, uint8_t aNonceLength)
This method initializes the AES CCM computation.
Parameters
[in] aHeaderLength Length of header in bytes.
[in] aPlainTextLength Length of plaintext in bytes.
[in] aTagLength Length of tag in bytes.
[in] aNonce A pointer to the nonce.
[in] aNonceLength Length of nonce in bytes.
Return values
OT_ERROR_NONE Initialization was successful.
OT_ERROR_INVALID_ARGS Initialization failed.
References AesEcb::Encrypt(), ExitNow, AesCcm::kTagLengthMin, AesCcm::mBlock, AesCcm::mBlockLength, AesCcm::mCtr, AesCcm::mCtrLength, AesCcm::mCtrPad, AesCcm::mEcb, AesCcm::mHeaderCur, AesCcm::mHeaderLength, AesCcm::mNonceLength, AesCcm::mPlainTextCur, AesCcm::mPlainTextLength, AesCcm::mTagLength, OT_ERROR_INVALID_ARGS, and OT_ERROR_NONE.
Referenced by Mle::HandleUdpReceive(), otCryptoAesCcm(), Mac::ProcessReceiveSecurity(), TxFrame::ProcessTransmitAesCcm(), and Mle::SendMessage().
Header()
void Header (const void * aHeader, uint32_t aHeaderLength)
This method processes the header.
Parameters
[in] aHeader A pointer to the header.
[in] aHeaderLength Length of header in bytes.
References AesEcb::Encrypt(), AesCcm::mBlock, AesCcm::mBlockLength, AesCcm::mEcb, AesCcm::mHeaderCur, AesCcm::mHeaderLength, and OT_ASSERT.
Referenced by Mle::HandleUdpReceive(), otCryptoAesCcm(), Mac::ProcessReceiveSecurity(), TxFrame::ProcessTransmitAesCcm(), and Mle::SendMessage().
Payload()
void Payload (void * aPlainText, void * aCipherText, uint32_t aLength, bool aEncrypt)
This method processes the payload.
Parameters
[in,out] aPlainText A pointer to the plaintext.
[in,out] aCipherText A pointer to the ciphertext.
[in] aLength Payload length in bytes.
[in] aEncrypt TRUE on encrypt and FALSE on decrypt.
References AesEcb::Encrypt(), AesCcm::mBlock, AesCcm::mBlockLength, AesCcm::mCtr, AesCcm::mCtrLength, AesCcm::mCtrPad, AesCcm::mEcb, AesCcm::mNonceLength, AesCcm::mPlainTextCur, AesCcm::mPlainTextLength, and OT_ASSERT.
Referenced by Mle::HandleUdpReceive(), otCryptoAesCcm(), Mac::ProcessReceiveSecurity(), TxFrame::ProcessTransmitAesCcm(), and Mle::SendMessage().
Finalize()
void Finalize (void * aTag, uint8_t * aTagLength)
This method generates the tag.
Parameters
[out] aTag A pointer to the tag.
[out] aTagLength Length of the tag in bytes.
References AesEcb::Encrypt(), AesCcm::mBlock, AesCcm::mCtr, AesCcm::mCtrPad, AesCcm::mEcb, AesCcm::mPlainTextCur, AesCcm::mPlainTextLength, AesCcm::mTagLength, and OT_ASSERT.
Referenced by Mle::HandleUdpReceive(), otCryptoAesCcm(), Mac::ProcessReceiveSecurity(), TxFrame::ProcessTransmitAesCcm(), and Mle::SendMessage().
Field Documentation
mEcb
AesEcb mEcb private
Referenced by AesCcm::Finalize(), AesCcm::Header(), AesCcm::Init(), AesCcm::Payload(), and AesCcm::SetKey().
mBlock
uint8_t mBlock[AesEcb::kBlockSize] private
Referenced by AesCcm::Finalize(), AesCcm::Header(), AesCcm::Init(), and AesCcm::Payload().
mCtr
uint8_t mCtr[AesEcb::kBlockSize] private
Referenced by AesCcm::Finalize(), AesCcm::Init(), and AesCcm::Payload().
mCtrPad
uint8_t mCtrPad[AesEcb::kBlockSize] private
Referenced by AesCcm::Finalize(), AesCcm::Init(), and AesCcm::Payload().
mNonceLength
uint8_t mNonceLength private
Referenced by AesCcm::Init(), and AesCcm::Payload().
mHeaderLength
uint32_t mHeaderLength private
Referenced by AesCcm::Header(), and AesCcm::Init().
mHeaderCur
uint32_t mHeaderCur private
Referenced by AesCcm::Header(), and AesCcm::Init().
mPlainTextLength
uint32_t mPlainTextLength private
Referenced by AesCcm::Finalize(), AesCcm::Init(), and AesCcm::Payload().
mPlainTextCur
uint32_t mPlainTextCur private
Referenced by AesCcm::Finalize(), AesCcm::Init(), and AesCcm::Payload().
mBlockLength
uint16_t mBlockLength private
Referenced by AesCcm::Header(), AesCcm::Init(), and AesCcm::Payload().
mCtrLength
uint16_t mCtrLength private
Referenced by AesCcm::Init(), and AesCcm::Payload().
mTagLength
uint8_t mTagLength private
Referenced by AesCcm::Finalize(), and AesCcm::Init().
The documentation for this class was generated from the following files:
aes_ccm.hpp
aes_ccm.cpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale