OpenThread: cli_uart.cpp File Reference
cli_uart.cpp File Reference
Detailed Description
This file implements the CLI server on the UART service.
#include "cli_uart.hpp"
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <openthread/cli.h>
#include <openthread/platform/logging.h>
#include <openthread/platform/uart.h>
#include "cli/cli.hpp"
#include "common/code_utils.hpp"
#include "common/encoding.hpp"
#include "common/logging.hpp"
#include "common/new.hpp"
#include "common/tasklet.hpp"
#include "utils/static_assert.hpp"
Namespaces
ot
ot::Cli
This namespace contains definitions for the CLI interpreter.
Macros
#define OT_CLI_UART_OUTPUT_LOCK()
#define OT_CLI_UART_OUTPUT_UNLOCK()
Functions
static OT_DEFINE_ALIGNED_VAR (sCliUartRaw, sizeof(Uart), uint64_t)
OT_STATIC_ASSERT (OPENTHREAD_CONFIG_CLI_MAX_LINE_LENGTH<=OPENTHREAD_CONFIG_CLI_UART_RX_BUFFER_SIZE, "command line should be should be smaller than CLI rx buffer")
void otCliUartInit (otInstance *aInstance)
void otPlatUartReceived (const uint8_t *aBuf, uint16_t aBufLength)
void otPlatUartSendDone (void)
Macro Definition Documentation
OT_CLI_UART_OUTPUT_LOCK
#define OT_CLI_UART_OUTPUT_LOCK ()
Value:
do                            \
    {                             \
    } while (0)
Macro to acquire an exclusive lock of uart cli output Default implementation does nothing
Referenced by Uart::Output().
OT_CLI_UART_OUTPUT_UNLOCK
#define OT_CLI_UART_OUTPUT_UNLOCK ()
Value:
do                              \
    {                               \
    } while (0)
Macro to release the exclusive lock of uart cli output Default implementation does nothing
Referenced by Uart::Output().
Function Documentation
OT_STATIC_ASSERT()
OT_STATIC_ASSERT (OPENTHREAD_CONFIG_CLI_MAX_LINE_LENGTH<= OPENTHREAD_CONFIG_CLI_UART_RX_BUFFER_SIZE, "command line should be should be smaller than CLI rx buffer")
Referenced by Message::GetHelpData(), ChangedPropsSet::GetNumEntries(), and NcpBase::PrepareLastStatusResponse().
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale