OpenThread: client.cpp File Reference
client.cpp File Reference
#include "platform/openthread-posix-config.h"
#include <openthread/platform/toolchain.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <unistd.h>
#include "common/code_utils.hpp"
#include "platform-posix.h"
Macros
#define HAVE_LIBEDIT 0
#define HAVE_LIBREADLINE 0
#define OPENTHREAD_USE_READLINE (HAVE_LIBEDIT || HAVE_LIBREADLINE)
Functions
static bool DoWrite (int aFile, const void *aBuffer, size_t aSize)
static bool FindDone (int *aDoneState, char aNowCharacter)
static bool FindError (int *aErrorState, char aNowCharacter)
int main (int argc, char *argv[])
static void SendBlockingCommand (int aArgc, char *aArgv[])
Variables
static int sSessionFd = -1
Macro Definition Documentation
HAVE_LIBEDIT
#define HAVE_LIBEDIT 0
HAVE_LIBREADLINE
#define HAVE_LIBREADLINE 0
OPENTHREAD_USE_READLINE
#define OPENTHREAD_USE_READLINE (HAVE_LIBEDIT || HAVE_LIBREADLINE)
Function Documentation
FindDone()
static bool FindDone (int * aDoneState, char aNowCharacter) static
Referenced by SendBlockingCommand().
FindError()
static bool FindError (int * aErrorState, char aNowCharacter) static
Referenced by SendBlockingCommand().
DoWrite()
static bool DoWrite (int aFile, const void * aBuffer, size_t aSize) static
References VerifyOrExit.
Referenced by main(), and SendBlockingCommand().
SendBlockingCommand()
static void SendBlockingCommand (int aArgc, char * aArgv[]) static
References DoWrite(), ExitNow, FindDone(), FindError(), OPENTHREAD_CONFIG_DIAG_CMD_LINE_BUFFER_SIZE, OT_NOOP, sSessionFd, and VerifyOrExit.
Referenced by main().
main()
int main (int argc, char * argv[])
References DoWrite(), ExitNow, OPENTHREAD_CONFIG_DIAG_CMD_LINE_BUFFER_SIZE, OPENTHREAD_POSIX_DAEMON_SOCKET_NAME, OT_EXIT_FAILURE, OT_EXIT_SUCCESS, OT_UNUSED_VARIABLE, SendBlockingCommand(), sSessionFd, and VerifyOrExit.
Referenced by spinel_capability_to_cstr().
Variable Documentation
sSessionFd
int sSessionFd = -1 static
Referenced by main(), and SendBlockingCommand().
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale