OpenThread: console_cli.h File Reference
console_cli.h File Reference
#include "platform/openthread-posix-config.h"
#include <stdint.h>
#include <openthread/openthread-system.h>
Functions
void otxConsoleDeinit (void)
void otxConsoleInit (otInstance *aInstance)
void otxConsoleProcess (const otSysMainloopContext *aMainloop)
void otxConsoleUpdate (otSysMainloopContext *aMainloop)
Function Documentation
otxConsoleInit()
void otxConsoleInit (otInstance * aInstance)
This function initializes CLI console.
Parameters
[in] aInstance A pointer to the OpenThread instance.
Referenced by main().
otxConsoleDeinit()
void otxConsoleDeinit (void)
This function deinitializes CLI console
Referenced by main().
otxConsoleUpdate()
void otxConsoleUpdate (otSysMainloopContext * aMainloop)
This function updates the file descriptor sets with file descriptors used by console.
Parameters
[in,out] aMainloop A pointer to the mainloop context.
Referenced by main().
otxConsoleProcess()
void otxConsoleProcess (const otSysMainloopContext * aMainloop)
This function performs console driver processing.
Parameters
[in] aMainloop A pointer to the mainloop context.
Referenced by main().
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale