OpenThread: UART
UART
Platform Abstraction
This module includes the platform abstraction for UART communication.
Functions
otError otPlatUartDisable (void)
otError otPlatUartEnable (void)
otError otPlatUartFlush (void)
void otPlatUartReceived (const uint8_t *aBuf, uint16_t aBufLength)
otError otPlatUartSend (const uint8_t *aBuf, uint16_t aBufLength)
void otPlatUartSendDone (void)
Detailed Description
This module includes the platform abstraction for UART communication.
Function Documentation
otPlatUartEnable()
otError otPlatUartEnable (void)
Enable the UART.
Return values
OT_ERROR_NONE Successfully enabled the UART.
OT_ERROR_FAILED Failed to enabled the UART.
References DieNow, DieNowWithMessage, kSocketNonBlock, OPENTHREAD_POSIX_DAEMON_SOCKET_LOCK, OPENTHREAD_POSIX_DAEMON_SOCKET_NAME, OT_ERROR_NONE, OT_EXIT_ERROR_ERRNO, OT_EXIT_FAILURE, OT_NOOP, sEnabled, SocketWithCloseExec(), and VerifyOrExit.
Referenced by Uart::Uart().
otPlatUartDisable()
otError otPlatUartDisable (void)
Disable the UART.
Return values
OT_ERROR_NONE Successfully disabled the UART.
OT_ERROR_FAILED Failed to disable the UART.
References OT_ERROR_NONE, and sEnabled.
otPlatUartSend()
otError otPlatUartSend (const uint8_t * aBuf, uint16_t aBufLength)
Send bytes over the UART.
Parameters
[in] aBuf A pointer to the data buffer.
[in] aBufLength Number of bytes to transmit.
Return values
OT_ERROR_NONE Successfully started transmission.
OT_ERROR_FAILED Failed to start the transmission.
References OT_ERROR_BUSY, OT_ERROR_NONE, sEnabled, sWriteBuffer, sWriteLength, and VerifyOrExit.
Referenced by Uart::Send().
otPlatUartFlush()
otError otPlatUartFlush (void)
Flush the outgoing transmit buffer and wait for the data to be sent. This is called when the CLI UART interface has a full buffer but still wishes to send more data.
Return values
OT_ERROR_NONE Flush succeeded, we can proceed to write more data to the buffer.
OT_ERROR_NOT_IMPLEMENTED Driver does not support synchronous flush.
OT_ERROR_INVALID_STATE Driver has no data to flush.
References OT_ERROR_NOT_IMPLEMENTED.
Referenced by Uart::Output().
otPlatUartSendDone()
void otPlatUartSendDone (void)
The UART driver calls this method to notify OpenThread that the requested bytes have been sent.
References Uart::SendDoneTask(), Server::sServer, and Uart::Uart().
Referenced by platformUartProcess().
otPlatUartReceived()
void otPlatUartReceived (const uint8_t * aBuf, uint16_t aBufLength)
The UART driver calls this method to notify OpenThread that bytes have been received.
Parameters
[in] aBuf A pointer to the received bytes.
[in] aBufLength The number of bytes received.
References Uart::ReceiveTask(), Server::sServer, and Uart::Uart().
Referenced by platformUartProcess().
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale