OpenThread: Core-ipv6
Core-ipv6
This module includes definitions for the IPv6 network layer.
Modules
ICMPv6
This module includes definitions for ICMPv6.
IPv6
This module includes definitions for core IPv6 networking.
MPL
This module includes definitions for MPL.
Network Interfaces
This module includes definitions for IPv6 network interfaces.
Data Structures
class Filter
Enumerations
enum { kMaxUnsecurePorts = 2 }
Functions
bool Accept (Message &aMessage) const
otError AddUnsecurePort (uint16_t aPort)
void AllowNativeCommissioner (bool aAllow)
Filter (void)
const uint16_t * GetUnsecurePorts (uint8_t &aNumEntries) const
bool IsUnsecurePort (uint16_t aPort)
void RemoveAllUnsecurePorts (void)
otError RemoveUnsecurePort (uint16_t aPort)
Variables
bool mAllowNativeCommissioner
uint16_t mUnsecurePorts [kMaxUnsecurePorts]
Detailed Description
This module includes definitions for the IPv6 network layer.
This module includes definitions for IPv6 datagram filtering.
Enumeration Type Documentation
anonymous enum
anonymous enum private
Enumerator
kMaxUnsecurePorts
Function Documentation
Filter()
Filter (void)
This constructor initializes the Filter object.
References Filter::mUnsecurePorts.
Accept()
bool Accept (Message & aMessage) const
This method indicates whether or not the IPv6 datagram passes the filter.
Parameters
[in] aMessage The IPv6 datagram to process.
Return values
TRUE Accept the IPv6 datagram.
FALSE Reject the IPv6 datagram.
References ExitNow, Header::GetDestination(), TcpHeader::GetDestinationPort(), UdpHeader::GetDestinationPort(), Header::GetNextHeader(), Address::IsLinkLocal(), Address::IsLinkLocalMulticast(), Message::IsLinkSecurityEnabled(), ot::MeshCoP::kBorderAgentUdpPort, Filter::kMaxUnsecurePorts, ot::Ip6::kProtoTcp, ot::Ip6::kProtoUdp, ot::Mle::kUdpPort, Filter::mAllowNativeCommissioner, Filter::mUnsecurePorts, OT_NOOP, Message::Read(), and VerifyOrExit.
AddUnsecurePort()
otError AddUnsecurePort (uint16_t aPort)
This method adds a port to the allowed unsecured port list.
Parameters
[in] aPort The port value.
Return values
OT_ERROR_NONE The port was successfully added to the allowed unsecure port list.
OT_ERROR_INVALID_ARGS The port is invalid (value 0 is reserved for internal use).
OT_ERROR_NO_BUFS The unsecure port list is full.
References ExitNow, Filter::kMaxUnsecurePorts, Filter::mUnsecurePorts, OT_ERROR_INVALID_ARGS, OT_ERROR_NO_BUFS, OT_ERROR_NONE, otLogInfoIp6, and VerifyOrExit.
RemoveUnsecurePort()
otError RemoveUnsecurePort (uint16_t aPort)
This method removes a port from the allowed unsecure port list.
Parameters
[in] aPort The port value.
Return values
OT_ERROR_NONE The port was successfully removed from the allowed unsecure port list.
OT_ERROR_INVALID_ARGS The port is invalid (value 0 is reserved for internal use).
OT_ERROR_NOT_FOUND The port was not found in the unsecure port list.
References ExitNow, Filter::kMaxUnsecurePorts, Filter::mUnsecurePorts, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, OT_ERROR_NOT_FOUND, otLogInfoIp6, and VerifyOrExit.
IsUnsecurePort()
bool IsUnsecurePort (uint16_t aPort)
This method checks whether a port is in the unsecure port list.
Parameters
[in] aPort The port value.
Returns
Whether the given port is in the unsecure port list.
References Filter::kMaxUnsecurePorts, and Filter::mUnsecurePorts.
RemoveAllUnsecurePorts()
void RemoveAllUnsecurePorts (void)
This method removes all ports from the allowed unsecure port list.
References Filter::mUnsecurePorts.
GetUnsecurePorts()
const uint16_t * GetUnsecurePorts (uint8_t & aNumEntries) const
This method returns a pointer to the unsecure port list.
Note
Port value 0 is used to indicate an invalid entry.
Parameters
[out] aNumEntries The number of entries in the list.
Returns
A pointer to the unsecure port list.
References Filter::kMaxUnsecurePorts, and Filter::mUnsecurePorts.
AllowNativeCommissioner()
void AllowNativeCommissioner (bool aAllow) inline
This method sets whether to allow native commissioner traffic.
Parameters
[in] aAllow Whether to allow native commissioner traffic.
References Filter::mAllowNativeCommissioner.
Variable Documentation
mUnsecurePorts
uint16_t mUnsecurePorts[kMaxUnsecurePorts] private
Referenced by Filter::Accept(), Filter::AddUnsecurePort(), Filter::Filter(), Filter::GetUnsecurePorts(), Filter::IsUnsecurePort(), Filter::RemoveAllUnsecurePorts(), and Filter::RemoveUnsecurePort().
mAllowNativeCommissioner
bool mAllowNativeCommissioner private
Referenced by Filter::Accept(), and Filter::AllowNativeCommissioner().
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale