OpenThread: Settings
Settings
Platform Abstraction
This module includes the platform abstraction for non-volatile storage of settings.
Functions
otError otPlatSettingsAdd (otInstance *aInstance, uint16_t aKey, const uint8_t *aValue, uint16_t aValueLength)
Adds a value to a setting.
void otPlatSettingsDeinit (otInstance *aInstance)
otError otPlatSettingsDelete (otInstance *aInstance, uint16_t aKey, int aIndex)
Removes a setting from the setting store.
otError otPlatSettingsGet (otInstance *aInstance, uint16_t aKey, int aIndex, uint8_t *aValue, uint16_t *aValueLength)
Fetches the value of a setting.
void otPlatSettingsInit (otInstance *aInstance)
otError otPlatSettingsSet (otInstance *aInstance, uint16_t aKey, const uint8_t *aValue, uint16_t aValueLength)
Sets or replaces the value of a setting.
void otPlatSettingsWipe (otInstance *aInstance)
Removes all settings from the setting store.
Detailed Description
This module includes the platform abstraction for non-volatile storage of settings.
Function Documentation
otPlatSettingsInit()
void otPlatSettingsInit (otInstance * aInstance)
Performs any initialization for the settings subsystem, if necessary.
Parameters
[in] aInstance The OpenThread instance structure.
References getSettingsFileName(), kMaxFileNameSize, OPENTHREAD_CONFIG_POSIX_SETTINGS_PATH, OT_ERROR_NONE, OT_ERROR_PARSE, OT_EXIT_ERROR_ERRNO, sSettingsFd, VerifyOrDie, and VerifyOrExit.
Referenced by SettingsDriver::Init(), and RadioSpinel< InterfaceType, ProcessContextType >::RestoreDatasetFromNcp().
otPlatSettingsDeinit()
void otPlatSettingsDeinit (otInstance * aInstance)
Performs any de-initialization for the settings subsystem, if necessary.
Parameters
[in] aInstance The OpenThread instance structure.
References OT_EXIT_ERROR_ERRNO, OT_UNUSED_VARIABLE, sSettingsFd, and VerifyOrDie.
Referenced by SettingsDriver::Deinit(), and RadioSpinel< InterfaceType, ProcessContextType >::RestoreDatasetFromNcp().
otPlatSettingsGet()
otError otPlatSettingsGet (otInstance * aInstance, uint16_t aKey, int aIndex, uint8_t * aValue, uint16_t * aValueLength)
Fetches the value of a setting.
This function fetches the value of the setting identified by aKey and write it to the memory pointed to by aValue. It then writes the length to the integer pointed to by aValueLength. The initial value of aValueLength is the maximum number of bytes to be written to aValue.
This function can be used to check for the existence of a key without fetching the value by setting aValue and aValueLength to NULL. You can also check the length of the setting without fetching it by setting only aValue to NULL.
Note that the underlying storage implementation is not required to maintain the order of settings with multiple values. The order of such values MAY change after ANY write operation to the store.
Parameters
[in] aInstance The OpenThread instance structure.
[in] aKey The key associated with the requested setting.
[in] aIndex The index of the specific item to get.
[out] aValue A pointer to where the value of the setting should be written. May be set to NULL if just testing for the presence or length of a setting.
[in,out] aValueLength A pointer to the length of the value. When called, this pointer should point to an integer containing the maximum value size that can be written to aValue. At return, the actual length of the setting is written. This may be set to NULL if performing a presence check.
Return values
OT_ERROR_NONE The given setting was found and fetched successfully.
OT_ERROR_NOT_FOUND The given setting was not found in the setting store.
OT_ERROR_NOT_IMPLEMENTED This function is not implemented on this platform.
References OT_ERROR_NONE, OT_ERROR_NOT_FOUND, OT_ERROR_PARSE, OT_EXIT_FAILURE, OT_UNUSED_VARIABLE, sSettingsFd, VerifyOrDie, and VerifyOrExit.
Referenced by SettingsDriver::Get().
otPlatSettingsSet()
otError otPlatSettingsSet (otInstance * aInstance, uint16_t aKey, const uint8_t * aValue, uint16_t aValueLength)
Sets or replaces the value of a setting.
This function sets or replaces the value of a setting identified by aKey. If there was more than one value previously associated with aKey, then they are all deleted and replaced with this single entry.
Calling this function successfully may cause unrelated settings with multiple values to be reordered.
Parameters
[in] aInstance The OpenThread instance structure.
[in] aKey The key associated with the setting to change.
[in] aValue A pointer to where the new value of the setting should be read from. MUST NOT be NULL if aValueLength is non-zero.
[in] aValueLength The length of the data pointed to by aValue. May be zero.
Return values
OT_ERROR_NONE The given setting was changed or staged.
OT_ERROR_NOT_IMPLEMENTED This function is not implemented on this platform.
OT_ERROR_NO_BUFS No space remaining to store the given setting.
References OT_ERROR_NONE, OT_ERROR_NOT_FOUND, OT_EXIT_FAILURE, platformSettingsDelete(), swapPersist(), and VerifyOrDie.
Referenced by SettingsDriver::Set(), and RadioSpinel< InterfaceType, ProcessContextType >::ThreadDatasetHandler().
otPlatSettingsAdd()
otError otPlatSettingsAdd (otInstance * aInstance, uint16_t aKey, const uint8_t * aValue, uint16_t aValueLength)
Adds a value to a setting.
This function adds the value to a setting identified by aKey, without replacing any existing values.
Note that the underlying implementation is not required to maintain the order of the items associated with a specific key. The added value may be added to the end, the beginning, or even somewhere in the middle. The order of any pre-existing values may also change.
Calling this function successfully may cause unrelated settings with multiple values to be reordered.
Parameters
[in] aInstance The OpenThread instance structure.
[in] aKey The key associated with the setting to change.
[in] aValue A pointer to where the new value of the setting should be read from. MUST NOT be NULL if aValueLength is non-zero.
[in] aValueLength The length of the data pointed to by aValue. May be zero.
Return values
OT_ERROR_NONE The given setting was added or staged to be added.
OT_ERROR_NOT_IMPLEMENTED This function is not implemented on this platform.
OT_ERROR_NO_BUFS No space remaining to store the given setting.
References OT_ERROR_NONE, OT_EXIT_ERROR_ERRNO, OT_EXIT_FAILURE, OT_UNUSED_VARIABLE, sSettingsFd, swapOpen(), swapPersist(), swapWrite(), and VerifyOrDie.
Referenced by SettingsDriver::Add().
otPlatSettingsDelete()
otError otPlatSettingsDelete (otInstance * aInstance, uint16_t aKey, int aIndex)
Removes a setting from the setting store.
This function deletes a specific value from the setting identified by aKey from the settings store.
Note that the underlying implementation is not required to maintain the order of the items associated with a specific key.
Parameters
[in] aInstance The OpenThread instance structure.
[in] aKey The key associated with the requested setting.
[in] aIndex The index of the value to be removed. If set to -1, all values for this aKey will be removed.
Return values
OT_ERROR_NONE The given key and index was found and removed successfully.
OT_ERROR_NOT_FOUND The given key or index was not found in the setting store.
OT_ERROR_NOT_IMPLEMENTED This function is not implemented on this platform.
References platformSettingsDelete().
Referenced by SettingsDriver::Delete().
otPlatSettingsWipe()
void otPlatSettingsWipe (otInstance * aInstance)
Removes all settings from the setting store.
This function deletes all settings from the settings store, resetting it to its initial factory state.
Parameters
[in] aInstance The OpenThread instance structure.
References OT_EXIT_ERROR_ERRNO, OT_UNUSED_VARIABLE, sSettingsFd, and VerifyOrDie.
Referenced by SettingsDriver::Wipe().
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale