OpenThread: Core-string
Core-string
This module includes definitions for OpenThread String class.
Data Structures
class String< SIZE >
class StringBase
Functions
uint16_t StringLength (const char *aString, uint16_t aMaxLength)
Detailed Description
This module includes definitions for OpenThread String class.
Function Documentation
StringLength()
uint16_t StringLength (const char * aString, uint16_t aMaxLength)
This function returns the number of characters that precede the terminating NULL character.
Parameters
[in] aString A pointer to the string.
[in] aMaxLength The maximum length in bytes.
Returns
The number of characters that precede the terminating NULL character or aMaxLength, whichever is smaller.
Referenced by NetworkName::GetAsData(), DomainName::GetAsData(), ot::MeshCoP::GetBorderAgentRloc(), Decoder::ReadUtf8(), NetworkName::Set(), DomainName::Set(), CommissionerIdTlv::SetCommissionerId(), ProvisioningUrlTlv::SetProvisioningUrl(), VendorDataTlv::SetVendorData(), VendorModelTlv::SetVendorModel(), VendorNameTlv::SetVendorName(), VendorSwVersionTlv::SetVendorSwVersion(), and RadioSpinel< InterfaceType, ProcessContextType >::ThreadDatasetHandler().
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale