OpenThread: Core
Core
Core-netdata
This module includes definitions for managing Thread Network Data.
Data Structures
struct NetworkData::Config
class NetworkData
class NetworkData::NetworkDataIterator
Typedefs
typedef otExternalRouteConfig ExternalRouteConfig
typedef otNetworkDataIterator Iterator
typedef otBorderRouterConfig OnMeshPrefixConfig
typedef otServiceConfig ServiceConfig
Enumerations
enum { kIteratorInit = OT_NETWORK_DATA_ITERATOR_INIT }
enum { kMaxSize = 254 }
enum { kDataResubmitDelay = 300000, kProxyResubmitDelay = 5000 }
enum { kTlvPosition = 0, kSubTlvPosition = 1, kEntryPosition = 2 }
enum Type { kTypeLocal, kTypeLeader }
Functions
void AdvaceSubTlv (const NetworkDataTlv *aSubTlvs)
void AdvanceTlv (const uint8_t *aTlvs)
NetworkDataTlv * AppendTlv (uint16_t aTlvSize)
bool CanInsert (uint16_t aSize) const
void Clear (void)
bool ContainsExternalRoutes (const NetworkData &aCompare, uint16_t aRloc16) const
bool ContainsOnMeshPrefixes (const NetworkData &aCompare, uint16_t aRloc16) const
bool ContainsService (uint8_t aServiceId, uint16_t aRloc16) const
bool ContainsServices (const NetworkData &aCompare, uint16_t aRloc16) const
static BorderRouterTlv * FindBorderRouter (PrefixTlv &aPrefix)
static const BorderRouterTlv * FindBorderRouter (const PrefixTlv &aPrefix)
static BorderRouterTlv * FindBorderRouter (PrefixTlv &aPrefix, bool aStable)
static const BorderRouterTlv * FindBorderRouter (const PrefixTlv &aPrefix, bool aStable)
static ContextTlv * FindContext (PrefixTlv &aPrefix)
static const ContextTlv * FindContext (const PrefixTlv &aPrefix)
static HasRouteTlv * FindHasRoute (PrefixTlv &aPrefix)
static const HasRouteTlv * FindHasRoute (const PrefixTlv &aPrefix)
static HasRouteTlv * FindHasRoute (PrefixTlv &aPrefix, bool aStable)
static const HasRouteTlv * FindHasRoute (const PrefixTlv &aPrefix, bool aStable)
PrefixTlv * FindPrefix (const uint8_t *aPrefix, uint8_t aPrefixLength)
const PrefixTlv * FindPrefix (const uint8_t *aPrefix, uint8_t aPrefixLength) const
static PrefixTlv * FindPrefix (const uint8_t *aPrefix, uint8_t aPrefixLength, uint8_t *aTlvs, uint8_t aTlvsLength)
static const PrefixTlv * FindPrefix (const uint8_t *aPrefix, uint8_t aPrefixLength, const uint8_t *aTlvs, uint8_t aTlvsLength)
ServiceTlv * FindService (uint32_t aEnterpriseNumber, const uint8_t *aServiceData, uint8_t aServiceDataLength)
const ServiceTlv * FindService (uint32_t aEnterpriseNumber, const uint8_t *aServiceData, uint8_t aServiceDataLength) const
static ServiceTlv * FindService (uint32_t aEnterpriseNumber, const uint8_t *aServiceData, uint8_t aServiceDataLength, uint8_t *aTlvs, uint8_t aTlvsLength)
static const ServiceTlv * FindService (uint32_t aEnterpriseNumber, const uint8_t *aServiceData, uint8_t aServiceDataLength, const uint8_t *aTlvs, uint8_t aTlvsLength)
static NetworkDataTlv * FindTlv (NetworkDataTlv *aStart, NetworkDataTlv *aEnd, NetworkDataTlv::Type aType)
static const NetworkDataTlv * FindTlv (const NetworkDataTlv *aStart, const NetworkDataTlv *aEnd, NetworkDataTlv::Type aType)
template<typename TlvType >
static TlvType * FindTlv (NetworkDataTlv *aStart, NetworkDataTlv *aEnd)
template<typename TlvType >
static const TlvType * FindTlv (const NetworkDataTlv *aStart, const NetworkDataTlv *aEnd)
static NetworkDataTlv * FindTlv (NetworkDataTlv *aStart, NetworkDataTlv *aEnd, NetworkDataTlv::Type aType, bool aStable)
static const NetworkDataTlv * FindTlv (const NetworkDataTlv *aStart, const NetworkDataTlv *aEnd, NetworkDataTlv::Type aType, bool aStable)
template<typename TlvType >
static TlvType * FindTlv (NetworkDataTlv *aStart, NetworkDataTlv *aEnd, bool aStable)
template<typename TlvType >
static const TlvType * FindTlv (const NetworkDataTlv *aStart, const NetworkDataTlv *aEnd, bool aStable)
uint8_t GetAndAdvanceIndex (void)
uint8_t GetEntryIndex (void) const
otError GetNetworkData (bool aStable, uint8_t *aData, uint8_t &aDataLength) const
otError GetNextExternalRoute (Iterator &aIterator, ExternalRouteConfig &aConfig) const
otError GetNextExternalRoute (Iterator &aIterator, uint16_t aRloc16, ExternalRouteConfig &aConfig) const
otError GetNextOnMeshPrefix (Iterator &aIterator, OnMeshPrefixConfig &aConfig) const
otError GetNextOnMeshPrefix (Iterator &aIterator, uint16_t aRloc16, OnMeshPrefixConfig &aConfig) const
otError GetNextServer (Iterator &aIterator, uint16_t &aRloc16) const
otError GetNextService (Iterator &aIterator, ServiceConfig &aConfig) const
otError GetNextService (Iterator &aIterator, uint16_t aRloc16, ServiceConfig &aConfig) const
otError GetNextServiceId (Iterator &aIterator, uint16_t aRloc16, uint8_t &aServiceId) const
const NetworkDataTlv * GetSubTlv (const NetworkDataTlv *aSubTlvs) const
uint8_t GetSubTlvOffset (void) const
const NetworkDataTlv * GetTlv (const uint8_t *aTlvs) const
uint8_t GetTlvOffset (void) const
NetworkDataTlv * GetTlvsEnd (void)
const NetworkDataTlv * GetTlvsEnd (void) const
NetworkDataTlv * GetTlvsStart (void)
const NetworkDataTlv * GetTlvsStart (void) const
void Insert (void *aStart, uint8_t aLength)
bool IsNewEntry (void) const
otError Iterate (Iterator &aIterator, uint16_t aRloc16, Config &aConfig) const
void MarkEntryAsNotNew (void)
NetworkData (Instance &aInstance, Type aType)
NetworkDataIterator (Iterator &aIterator)
static int8_t PrefixMatch (const uint8_t *a, const uint8_t *b, uint8_t aLength)
void Remove (void *aRemoveStart, uint8_t aRemoveLength)
static void Remove (uint8_t *aData, uint8_t &aDataLength, uint8_t *aRemoveStart, uint8_t aRemoveLength)
static void RemoveTemporaryData (uint8_t *aData, uint8_t &aDataLength)
static void RemoveTemporaryData (uint8_t *aData, uint8_t &aDataLength, PrefixTlv &aPrefix)
static void RemoveTemporaryData (uint8_t *aData, uint8_t &aDataLength, ServiceTlv &aService)
void RemoveTlv (NetworkDataTlv *aTlv)
static void RemoveTlv (uint8_t *aData, uint8_t &aDataLength, NetworkDataTlv *aTlv)
void SaveSubTlvOffset (const NetworkDataTlv *aSubTlv, const NetworkDataTlv *aSubTlvs)
void SaveTlvOffset (const NetworkDataTlv *aTlv, const uint8_t *aTlvs)
otError SendServerDataNotification (uint16_t aRloc16, Coap::ResponseHandler aHandler, void *aContext)
void SetEntryIndex (uint8_t aIndex)
void SetSubTlvOffset (uint8_t aOffset)
void SetTlvOffset (uint8_t aOffset)
Variables
ExternalRouteConfig * mExternalRoute
uint8_t * mIteratorBuffer
OnMeshPrefixConfig * mOnMeshPrefix
ServiceConfig * mService
uint8_t mTlvs [kMaxSize]
The Network Data buffer.
const Type mType
Detailed Description
This module includes definitions for managing Thread Network Data.
Typedef Documentation
Iterator
typedef otNetworkDataIterator Iterator
This type represents a Iterator used to iterate through Network Data info (e.g., see GetNextOnMeshPrefix())
OnMeshPrefixConfig
typedef otBorderRouterConfig OnMeshPrefixConfig
This type represents an On Mesh Prefix (Border Router) configuration.
ExternalRouteConfig
typedef otExternalRouteConfig ExternalRouteConfig
This type represents an External Route configuration.
ServiceConfig
typedef otServiceConfig ServiceConfig
This type represents a Service configuration.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
kIteratorInit
Initializer for Iterator type.
anonymous enum
anonymous enum
Enumerator
kMaxSize
Maximum size of Thread Network Data in bytes.
Type
enum Type
This enumeration specifies the type of Network Data (local or leader).
Enumerator
kTypeLocal
Local Network Data.
kTypeLeader
Leader Network Data.
anonymous enum
anonymous enum private
Enumerator
kDataResubmitDelay
DATA_RESUBMIT_DELAY (milliseconds) if the device itself is the server.
kProxyResubmitDelay
Resubmit delay (milliseconds) if deregister as the child server proxy.
anonymous enum
anonymous enum private
Enumerator
kTlvPosition
kSubTlvPosition
kEntryPosition
Function Documentation
NetworkData()
NetworkData (Instance & aInstance, Type aType)
This constructor initializes the object.
Parameters
[in] aInstance A reference to the OpenThread instance.
[in] aType Network data type
Clear()
void Clear (void)
This method clears the network data.
GetNetworkData()
otError GetNetworkData (bool aStable, uint8_t * aData, uint8_t & aDataLength) const
This method provides a full or stable copy of the Thread Network Data.
Parameters
[in] aStable TRUE when copying the stable version, FALSE when copying the full version.
[out] aData A pointer to the data buffer.
[in,out] aDataLength On entry, size of the data buffer pointed to by aData. On exit, number of copied bytes.
Return values
OT_ERROR_NONE Successfully copied full Thread Network Data.
OT_ERROR_NO_BUFS Not enough space to fully copy Thread Network Data.
References NetworkData::mTlvs, OT_ASSERT, OT_ERROR_NO_BUFS, OT_ERROR_NONE, NetworkData::RemoveTemporaryData(), and VerifyOrExit.
GetNextOnMeshPrefix() [1/2]
otError GetNextOnMeshPrefix (Iterator & aIterator, OnMeshPrefixConfig & aConfig) const
This method provides the next On Mesh prefix in the Thread Network Data.
Parameters
[in,out] aIterator A reference to the Network Data iterator.
[out] aConfig A reference to a config variable where the On Mesh Prefix information will be placed.
Return values
OT_ERROR_NONE Successfully found the next On Mesh prefix.
OT_ERROR_NOT_FOUND No subsequent On Mesh prefix exists in the Thread Network Data.
References ot::Mac::kShortAddrBroadcast.
Referenced by NetworkData::ContainsOnMeshPrefixes(), and LeaderBase::GetRlocByContextId().
GetNextOnMeshPrefix() [2/2]
otError GetNextOnMeshPrefix (Iterator & aIterator, uint16_t aRloc16, OnMeshPrefixConfig & aConfig) const
This method provides the next On Mesh prefix in the Thread Network Data for a given RLOC16.
Parameters
[in,out] aIterator A reference to the Network Data iterator.
[in] aRloc16 The RLOC16 value.
[out] aConfig A reference to a config variable where the On Mesh Prefix information will be placed.
Return values
OT_ERROR_NONE Successfully found the next On Mesh prefix.
OT_ERROR_NOT_FOUND No subsequent On Mesh prefix exists in the Thread Network Data.
References NetworkData::Iterate(), NetworkData::Config::mExternalRoute, NetworkData::Config::mOnMeshPrefix, and NetworkData::Config::mService.
GetNextExternalRoute() [1/2]
otError GetNextExternalRoute (Iterator & aIterator, ExternalRouteConfig & aConfig) const
This method provides the next external route in the Thread Network Data.
Parameters
[in,out] aIterator A reference to the Network Data iterator.
[out] aConfig A reference to a config variable where the external route information will be placed.
Return values
OT_ERROR_NONE Successfully found the next external route.
OT_ERROR_NOT_FOUND No subsequent external route exists in the Thread Network Data.
References ot::Mac::kShortAddrBroadcast.
Referenced by NetworkData::ContainsExternalRoutes().
GetNextExternalRoute() [2/2]
otError GetNextExternalRoute (Iterator & aIterator, uint16_t aRloc16, ExternalRouteConfig & aConfig) const
This method provides the next external route in the Thread Network Data for a given RLOC16.
Parameters
[in,out] aIterator A reference to the Network Data iterator.
[in] aRloc16 The RLOC16 value.
[out] aConfig A reference to a config variable where the external route information will be placed.
Return values
OT_ERROR_NONE Successfully found the next external route.
OT_ERROR_NOT_FOUND No subsequent external route exists in the Thread Network Data.
References NetworkData::Iterate(), NetworkData::Config::mExternalRoute, NetworkData::Config::mOnMeshPrefix, and NetworkData::Config::mService.
GetNextService() [1/2]
otError GetNextService (Iterator & aIterator, ServiceConfig & aConfig) const
This method provides the next service in the Thread Network Data.
Parameters
[in,out] aIterator A reference to the Network Data iterator.
[out] aConfig A reference to a config variable where the service information will be placed.
Return values
OT_ERROR_NONE Successfully found the next service.
OT_ERROR_NOT_FOUND No subsequent service exists in the Thread Network Data.
References ot::Mac::kShortAddrBroadcast.
Referenced by NetworkData::ContainsServices(), NetworkData::GetNextServiceId(), and LeaderBase::GetServiceId().
GetNextService() [2/2]
otError GetNextService (Iterator & aIterator, uint16_t aRloc16, ServiceConfig & aConfig) const
This method provides the next service in the Thread Network Data for a given RLOC16.
Parameters
[in,out] aIterator A reference to the Network Data iterator.
[in] aRloc16 The RLOC16 value.
[out] aConfig A reference to a config variable where the service information will be placed.
Return values
OT_ERROR_NONE Successfully found the next service.
OT_ERROR_NOT_FOUND No subsequent service exists in the Thread Network Data.
References NetworkData::Iterate(), NetworkData::Config::mExternalRoute, NetworkData::Config::mOnMeshPrefix, and NetworkData::Config::mService.
GetNextServiceId()
otError GetNextServiceId (Iterator & aIterator, uint16_t aRloc16, uint8_t & aServiceId) const
This method provides the next Service ID in the Thread Network Data for a given RLOC16.
Parameters
[in,out] aIterator A reference to the Network Data iterator.
[in] aRloc16 The RLOC16 value.
[out] aServiceId A reference to variable where the Service ID will be placed.
Return values
OT_ERROR_NONE Successfully found the next service.
OT_ERROR_NOT_FOUND No subsequent service exists in the Thread Network Data.
References NetworkData::GetNextService(), otServiceConfig::mServiceId, and SuccessOrExit.
Referenced by NetworkData::ContainsService().
ContainsOnMeshPrefixes()
bool ContainsOnMeshPrefixes (const NetworkData & aCompare, uint16_t aRloc16) const
This method indicates whether or not the Thread Network Data contains all of the on mesh prefix information in aCompare associated with aRloc16.
Parameters
[in] aCompare The Network Data to use for the query.
[in] aRloc16 The RLOC16 to consider.
Returns
TRUE if this object contains all on mesh prefix information in aCompare associated with aRloc16, FALSE otherwise.
References ExitNow, NetworkData::GetNextOnMeshPrefix(), ot::NetworkData::kIteratorInit, and OT_ERROR_NONE.
ContainsExternalRoutes()
bool ContainsExternalRoutes (const NetworkData & aCompare, uint16_t aRloc16) const
This method indicates whether or not the Thread Network Data contains all of the external route information in aCompare associated with aRloc16.
Parameters
[in] aCompare The Network Data to use for the query.
[in] aRloc16 The RLOC16 to consider.
Returns
TRUE if this object contains all external route information in aCompare associated with aRloc16, FALSE otherwise.
References ExitNow, NetworkData::GetNextExternalRoute(), ot::NetworkData::kIteratorInit, and OT_ERROR_NONE.
ContainsServices()
bool ContainsServices (const NetworkData & aCompare, uint16_t aRloc16) const
This method indicates whether or not the Thread Network Data contains all of the service information in aCompare associated with aRloc16.
Parameters
[in] aCompare The Network Data to use for the query.
[in] aRloc16 The RLOC16 to consider.
Returns
TRUE if this object contains all service information in aCompare associated with aRloc16, FALSE otherwise.
References ExitNow, NetworkData::GetNextService(), ot::NetworkData::kIteratorInit, otServiceConfig::mEnterpriseNumber, otServiceConfig::mServerConfig, otServerConfig::mServerData, otServerConfig::mServerDataLength, otServiceConfig::mServiceData, otServiceConfig::mServiceDataLength, otServerConfig::mStable, and OT_ERROR_NONE.
ContainsService()
bool ContainsService (uint8_t aServiceId, uint16_t aRloc16) const
This method indicates whether or not the Thread Network Data contains the service with given Service ID associated with aRloc16.
Parameters
[in] aServiceId The Service ID to search for.
[in] aRloc16 The RLOC16 to consider.
Returns
TRUE if this object contains the service with given ID associated with aRloc16, FALSE otherwise.
References ExitNow, NetworkData::GetNextServiceId(), ot::NetworkData::kIteratorInit, and OT_ERROR_NONE.
GetNextServer()
otError GetNextServer (Iterator & aIterator, uint16_t & aRloc16) const
This method provides the next server RLOC16 in the Thread Network Data.
Parameters
[in,out] aIterator A reference to the Network Data iterator.
[out] aRloc16 The RLOC16 value.
Return values
OT_ERROR_NONE Successfully found the next server.
OT_ERROR_NOT_FOUND No subsequent server exists in the Thread Network Data.
References NetworkData::Iterate(), ot::Mac::kShortAddrBroadcast, NetworkData::Config::mExternalRoute, NetworkData::Config::mOnMeshPrefix, otBorderRouterConfig::mRloc16, otExternalRouteConfig::mRloc16, otServerConfig::mRloc16, otServiceConfig::mServerConfig, NetworkData::Config::mService, OT_ASSERT, and SuccessOrExit.
GetTlvsStart() [1/2]
NetworkDataTlv* GetTlvsStart (void) inline protected
This method returns a pointer to the start of Network Data TLV sequence.
Returns
A pointer to the start of Network Data TLV sequence.
References NetworkData::mTlvs.
Referenced by LeaderBase::ExternalRouteLookup(), LeaderBase::FindNextMatchingPrefix(), LeaderBase::GetCommissioningData(), and LeaderBase::GetContext().
GetTlvsStart() [2/2]
const NetworkDataTlv* GetTlvsStart (void) const inline protected
This method returns a pointer to the start of Network Data TLV sequence.
Returns
A pointer to the start of Network Data TLV sequence.
References NetworkData::mTlvs.
GetTlvsEnd() [1/2]
NetworkDataTlv* GetTlvsEnd (void) inline protected
This method returns a pointer to the end of Network Data TLV sequence.
Returns
A pointer to the end of Network Data TLV sequence.
References NetworkData::mTlvs.
Referenced by NetworkData::AppendTlv(), LeaderBase::ExternalRouteLookup(), LeaderBase::FindNextMatchingPrefix(), LeaderBase::GetCommissioningData(), LeaderBase::GetContext(), and NetworkData::Iterate().
GetTlvsEnd() [2/2]
const NetworkDataTlv* GetTlvsEnd (void) const inline protected
This method returns a pointer to the end of Network Data TLV sequence.
Returns
A pointer to the end of Network Data TLV sequence.
References NetworkData::mTlvs.
FindBorderRouter() [1/4]
static BorderRouterTlv* FindBorderRouter (PrefixTlv & aPrefix) inline static protected
This method returns a pointer to the Border Router TLV within a given Prefix TLV.
Parameters
[in] aPrefix A reference to the Prefix TLV.
Returns
A pointer to the Border Router TLV if one is found or NULL if no Border Router TLV exists.
Referenced by NetworkData::FindBorderRouter(), and LeaderBase::IsOnMesh().
FindBorderRouter() [2/4]
const BorderRouterTlv * FindBorderRouter (const PrefixTlv & aPrefix) static protected
This method returns a pointer to the Border Router TLV within a given Prefix TLV.
Parameters
[in] aPrefix A reference to the Prefix TLV.
Returns
A pointer to the Border Router TLV if one is found or NULL if no Border Router TLV exists.
References NetworkDataTlv::GetNext(), and PrefixTlv::GetSubTlvs().
FindBorderRouter() [3/4]
static BorderRouterTlv* FindBorderRouter (PrefixTlv & aPrefix, bool aStable) inline static protected
This method returns a pointer to the stable or non-stable Border Router TLV within a given Prefix TLV.
Parameters
[in] aPrefix A reference to the Prefix TLV.
[in] aStable TRUE to find a stable TLV, FALSE to find a TLV not marked as stable..
Returns
A pointer to the Border Router TLV if one is found or NULL if no Border Router TLV exists.
References NetworkData::FindBorderRouter().
FindBorderRouter() [4/4]
const BorderRouterTlv * FindBorderRouter (const PrefixTlv & aPrefix, bool aStable) static protected
This method returns a pointer to the stable or non-stable Border Router TLV within a given Prefix TLV.
Parameters
[in] aPrefix A reference to the Prefix TLV.
[in] aStable TRUE to find a stable TLV, FALSE to find a TLV not marked as stable..
Returns
A pointer to the Border Router TLV if one is found or NULL if no Border Router TLV exists.
References NetworkDataTlv::GetNext(), and PrefixTlv::GetSubTlvs().
FindHasRoute() [1/4]
static HasRouteTlv* FindHasRoute (PrefixTlv & aPrefix) inline static protected
This method returns a pointer to the Has Route TLV within a given Prefix TLV.
Parameters
[in] aPrefix A reference to the Prefix TLV.
Returns
A pointer to the Has Route TLV if one is found or NULL if no Has Route TLV exists.
Referenced by NetworkData::FindHasRoute().
FindHasRoute() [2/4]
const HasRouteTlv * FindHasRoute (const PrefixTlv & aPrefix) static protected
This method returns a pointer to the Has Route TLV within a given Prefix TLV.
Parameters
[in] aPrefix A reference to the Prefix TLV.
Returns
A pointer to the Has Route TLV if one is found or NULL if no Has Route TLV exists.
References NetworkDataTlv::GetNext(), and PrefixTlv::GetSubTlvs().
FindHasRoute() [3/4]
static HasRouteTlv* FindHasRoute (PrefixTlv & aPrefix, bool aStable) inline static protected
This method returns a pointer to the stable or non-stable Has Route TLV within a given Prefix TLV.
Parameters
[in] aPrefix A reference to the Prefix TLV.
[in] aStable TRUE to find a stable TLV, FALSE to find a TLV not marked as stable.
Returns
A pointer to the Has Route TLV if one is found or NULL if no Has Route TLV exists.
References NetworkData::FindHasRoute().
FindHasRoute() [4/4]
const HasRouteTlv * FindHasRoute (const PrefixTlv & aPrefix, bool aStable) static protected
This method returns a pointer to the stable or non-stable Has Route TLV within a given Prefix TLV.
Parameters
[in] aPrefix A reference to the Prefix TLV.
[in] aStable TRUE to find a stable TLV, FALSE to find a TLV not marked as stable.
Returns
A pointer to the Has Route TLV if one is found or NULL if no Has Route TLV exists.
References NetworkDataTlv::GetNext(), and PrefixTlv::GetSubTlvs().
FindContext() [1/2]
static ContextTlv* FindContext (PrefixTlv & aPrefix) inline static protected
This method returns a pointer to the Context TLV within a given Prefix TLV.
Parameters
[in] aPrefix A reference to the Prefix TLV.
Returns
A pointer to the Context TLV is one is found or NULL if no Context TLV exists.
Referenced by LeaderBase::GetContext(), and NetworkData::RemoveTemporaryData().
FindContext() [2/2]
const ContextTlv * FindContext (const PrefixTlv & aPrefix) static protected
This method returns a pointer to the Context TLV within a given Prefix TLV.
Parameters
[in] aPrefix A reference to the Prefix TLV.
Returns
A pointer to the Context TLV is one is found or NULL if no Context TLV exists.
References NetworkDataTlv::GetNext(), and PrefixTlv::GetSubTlvs().
FindPrefix() [1/4]
PrefixTlv* FindPrefix (const uint8_t * aPrefix, uint8_t aPrefixLength) inline protected
This method returns a pointer to a Prefix TLV.
Parameters
[in] aPrefix A pointer to an IPv6 prefix.
[in] aPrefixLength The prefix length pointed to by aPrefix.
Returns
A pointer to the Prefix TLV is one is found or NULL if no matching Prefix TLV exists.
Referenced by NetworkData::FindPrefix().
FindPrefix() [2/4]
const PrefixTlv * FindPrefix (const uint8_t * aPrefix, uint8_t aPrefixLength) const protected
This method returns a pointer to a Prefix TLV.
Parameters
[in] aPrefix A pointer to an IPv6 prefix.
[in] aPrefixLength The prefix length pointed to by aPrefix.
Returns
A pointer to the Prefix TLV is one is found or NULL if no matching Prefix TLV exists.
References NetworkData::FindPrefix(), and NetworkData::mTlvs.
FindPrefix() [3/4]
static PrefixTlv* FindPrefix (const uint8_t * aPrefix, uint8_t aPrefixLength, uint8_t * aTlvs, uint8_t aTlvsLength) inline static protected
This method returns a pointer to a Prefix TLV in a specified tlvs buffer.
Parameters
[in] aPrefix A pointer to an IPv6 prefix.
[in] aPrefixLength The prefix length pointed to by aPrefix (in bits).
[in] aTlvs A pointer to a specified tlvs buffer.
[in] aTlvsLength The specified tlvs buffer length pointed to by aTlvs.
Returns
A pointer to the Prefix TLV is one is found or NULL if no matching Prefix TLV exists.
References NetworkData::FindPrefix().
FindPrefix() [4/4]
const PrefixTlv * FindPrefix (const uint8_t * aPrefix, uint8_t aPrefixLength, const uint8_t * aTlvs, uint8_t aTlvsLength) static protected
This method returns a pointer to a Prefix TLV in a specified tlvs buffer.
Parameters
[in] aPrefix A pointer to an IPv6 prefix.
[in] aPrefixLength The prefix length pointed to by aPrefix (in bits).
[in] aTlvs A pointer to a specified tlvs buffer.
[in] aTlvsLength The specified tlvs buffer length pointed to by aTlvs.
Returns
A pointer to the Prefix TLV is one is found or NULL if no matching Prefix TLV exists.
References ExitNow, NetworkDataTlv::GetNext(), PrefixTlv::GetPrefix(), PrefixTlv::GetPrefixLength(), OT_NOOP, NetworkData::PrefixMatch(), and VerifyOrExit.
FindService() [1/4]
ServiceTlv* FindService (uint32_t aEnterpriseNumber, const uint8_t * aServiceData, uint8_t aServiceDataLength) inline protected
This method returns a pointer to a matching Service TLV.
Parameters
[in] aEnterpriseNumber Enterprise Number.
[in] aServiceData A pointer to a Service Data.
[in] aServiceDataLength The Service Data length pointed to by aServiceData.
Returns
A pointer to the Service TLV is one is found or NULL if no matching Service TLV exists.
Referenced by NetworkData::FindService(), and LeaderBase::GetBackboneRouterPrimary().
FindService() [2/4]
const ServiceTlv * FindService (uint32_t aEnterpriseNumber, const uint8_t * aServiceData, uint8_t aServiceDataLength) const protected
This method returns a pointer to a matching Service TLV.
Parameters
[in] aEnterpriseNumber Enterprise Number.
[in] aServiceData A pointer to a Service Data.
[in] aServiceDataLength The Service Data length pointed to by aServiceData.
Returns
A pointer to the Service TLV is one is found or NULL if no matching Service TLV exists.
References NetworkData::FindService(), and NetworkData::mTlvs.
FindService() [3/4]
static ServiceTlv* FindService (uint32_t aEnterpriseNumber, const uint8_t * aServiceData, uint8_t aServiceDataLength, uint8_t * aTlvs, uint8_t aTlvsLength) inline static protected
This method returns a pointer to a Service TLV in a specified tlvs buffer.
Parameters
[in] aEnterpriseNumber Enterprise Number.
[in] aServiceData A pointer to an Service Data.
[in] aServiceDataLength The Service Data length pointed to by aServiceData.
[in] aTlvs A pointer to a specified tlvs buffer.
[in] aTlvsLength The specified tlvs buffer length pointed to by aTlvs.
Returns
A pointer to the Service TLV is one is found or NULL if no matching Service TLV exists.
References NetworkData::FindService().
FindService() [4/4]
const ServiceTlv * FindService (uint32_t aEnterpriseNumber, const uint8_t * aServiceData, uint8_t aServiceDataLength, const uint8_t * aTlvs, uint8_t aTlvsLength) static protected
This method returns a pointer to a Service TLV in a specified tlvs buffer.
Parameters
[in] aEnterpriseNumber Enterprise Number.
[in] aServiceData A pointer to an Service Data.
[in] aServiceDataLength The Service Data length pointed to by aServiceData.
[in] aTlvs A pointer to a specified tlvs buffer.
[in] aTlvsLength The specified tlvs buffer length pointed to by aTlvs.
Returns
A pointer to the Service TLV is one is found or NULL if no matching Service TLV exists.
References ExitNow, ServiceTlv::GetEnterpriseNumber(), NetworkDataTlv::GetNext(), ServiceTlv::GetServiceData(), ServiceTlv::GetServiceDataLength(), OT_NOOP, and VerifyOrExit.
CanInsert()
bool CanInsert (uint16_t aSize) const inline protected
This method indicates whether there is space in Network Data to insert/append new info and grow it by a given number of bytes.
Parameters
[in] aSize The number of bytes to grow the Network Data.
Return values
TRUE There is space to grow Network Data by aSize bytes.
FALSE There is no space left to grow Network Data by aSize bytes.
References NetworkData::AppendTlv(), NetworkData::Insert(), NetworkData::kMaxSize, NetworkData::PrefixMatch(), NetworkData::Remove(), NetworkData::RemoveTemporaryData(), NetworkData::RemoveTlv(), and NetworkData::SendServerDataNotification().
Referenced by NetworkData::AppendTlv(), and NetworkData::Insert().
AppendTlv()
NetworkDataTlv * AppendTlv (uint16_t aTlvSize) protected
This method grows the Network Data to append a TLV with a requested size.
On success, the returned TLV is not initialized (i.e., the TLV Length field is not set) but the requested size for it (aTlvSize number of bytes) is reserved in the Network Data.
Parameters
[in] aTlvSize The size of TLV (total number of bytes including Type, Length, and Value fields)
Returns
A pointer to the TLV if there is space to grow Network Data, or NULL if no space to grow the Network Data with requested aTlvSize number of bytes.
References NetworkData::CanInsert(), NetworkData::GetTlvsEnd(), and VerifyOrExit.
Referenced by NetworkData::CanInsert(), and LeaderBase::SetCommissioningData().
Insert()
void Insert (void * aStart, uint8_t aLength) protected
This method inserts bytes into the Network Data.
Parameters
[in] aStart A pointer to the beginning of the insertion.
[in] aLength The number of bytes to insert.
References NetworkData::CanInsert(), NetworkData::mTlvs, and OT_ASSERT.
Referenced by NetworkData::CanInsert().
Remove() [1/2]
void Remove (void * aRemoveStart, uint8_t aRemoveLength) protected
This method removes bytes from the Network Data.
Parameters
[in] aRemoveStart A pointer to the beginning of the removal.
[in] aRemoveLength The number of bytes to remove.
References NetworkData::mTlvs.
Referenced by NetworkData::CanInsert(), and NetworkData::RemoveTlv().
RemoveTlv() [1/2]
void RemoveTlv (NetworkDataTlv * aTlv) protected
This method removes a TLV from the Network Data.
Parameters
[in] aTlv The TLV to remove.
References NetworkData::mTlvs.
Referenced by NetworkData::CanInsert(), LeaderBase::RemoveCommissioningData(), and NetworkData::RemoveTemporaryData().
RemoveTemporaryData() [1/3]
void RemoveTemporaryData (uint8_t * aData, uint8_t & aDataLength) static protected
This method strips non-stable data from the Thread Network Data.
Parameters
[in,out] aData A pointer to the Network Data to modify.
[in,out] aDataLength On entry, the size of the Network Data in bytes. On exit, the size of the resulting Network Data in bytes.
References NetworkDataTlv::GetNext(), PrefixTlv::GetSubTlvsLength(), ServiceTlv::GetSubTlvsLength(), NetworkDataTlv::GetType(), NetworkDataTlv::IsStable(), NetworkDataTlv::kTypePrefix, NetworkDataTlv::kTypeService, otDumpDebgNetData, and NetworkData::RemoveTlv().
Referenced by NetworkData::CanInsert(), NetworkData::GetNetworkData(), and LeaderBase::SetNetworkData().
PrefixMatch()
int8_t PrefixMatch (const uint8_t * a, const uint8_t * b, uint8_t aLength) static protected
This method computes the number of IPv6 Prefix bits that match.
Parameters
[in] a A pointer to the first IPv6 Prefix.
[in] b A pointer to the second IPv6 prefix.
[in] aLength The maximum length in bits to compare.
Returns
The number of matching bits.
References BitVectorBytes, and Address::PrefixMatch().
Referenced by NetworkData::CanInsert(), LeaderBase::ExternalRouteLookup(), LeaderBase::FindNextMatchingPrefix(), and NetworkData::FindPrefix().
SendServerDataNotification()
otError SendServerDataNotification (uint16_t aRloc16, Coap::ResponseHandler aHandler, void * aContext) protected
This method sends a Server Data Notification message to the Leader.
Parameters
[in] aRloc16 The old RLOC16 value that was previously registered.
[in] aHandler A function pointer that is called when the transaction ends.
[in] aContext A pointer to arbitrary context information.
Return values
OT_ERROR_NONE Successfully enqueued the notification message.
OT_ERROR_NO_BUFS Insufficient message buffers to generate the notification message.
References Message::Append(), Tlv::AppendUint16Tlv(), Message::Free(), MessageInfo::GetPeerAddr(), Message::Init(), ot::kCoapUdpPort, ThreadTlv::kRloc16, ot::Mac::kShortAddrInvalid, ThreadTlv::kThreadNetworkData, NetworkData::kTypeLocal, NetworkData::mTlvs, NetworkData::mType, OT_COAP_CODE_POST, OT_COAP_TYPE_CONFIRMABLE, OT_ERROR_NO_BUFS, OT_ERROR_NONE, OT_URI_PATH_SERVER_DATA, otLogInfoNetData, Tlv::SetLength(), Message::SetPayloadMarker(), MessageInfo::SetPeerPort(), MessageInfo::SetSockAddr(), ThreadTlv::SetType(), SuccessOrExit, and VerifyOrExit.
Referenced by NetworkData::CanInsert().
FindTlv() [1/8]
static NetworkDataTlv* FindTlv (NetworkDataTlv * aStart, NetworkDataTlv * aEnd, NetworkDataTlv::Type aType) inline static protected
This static method searches in a given sequence of TLVs to find the first TLV with a given TLV Type.
Parameters
[in] aStart A pointer to the start of the sequence of TLVs to search within.
[in] aEnd A pointer to the end of the sequence of TLVs.
[in] aType The TLV type to find.
Returns
A pointer to the TLV if found, or NULL if not found.
Referenced by NetworkData::FindTlv().
FindTlv() [2/8]
const NetworkDataTlv * FindTlv (const NetworkDataTlv * aStart, const NetworkDataTlv * aEnd, NetworkDataTlv::Type aType) static protected
This static method searches in a given sequence of TLVs to find the first TLV with a given TLV Type.
Parameters
[in] aStart A pointer to the start of the sequence of TLVs to search within.
[in] aEnd A pointer to the end of the sequence of TLVs.
[in] aType The TLV type to find.
Returns
A pointer to the TLV if found, or NULL if not found.
References ExitNow, NetworkDataTlv::GetNext(), and VerifyOrExit.
FindTlv() [3/8]
static TlvType* FindTlv (NetworkDataTlv * aStart, NetworkDataTlv * aEnd) inline static protected
This static template method searches in a given sequence of TLVs to find the first TLV with a give template TlvType.
Parameters
[in] aStart A pointer to the start of the sequence of TLVs to search within.
[in] aEnd A pointer to the end of the sequence of TLVs.
Returns
A pointer to the TLV if found, or NULL if not found.
References NetworkData::FindTlv().
FindTlv() [4/8]
static const TlvType* FindTlv (const NetworkDataTlv * aStart, const NetworkDataTlv * aEnd) inline static protected
This static template method searches in a given sequence of TLVs to find the first TLV with a give template TlvType.
Parameters
[in] aStart A pointer to the start of the sequence of TLVs to search within.
[in] aEnd A pointer to the end of the sequence of TLVs.
Returns
A pointer to the TLV if found, or NULL if not found.
References NetworkData::FindTlv().
FindTlv() [5/8]
static NetworkDataTlv* FindTlv (NetworkDataTlv * aStart, NetworkDataTlv * aEnd, NetworkDataTlv::Type aType, bool aStable) inline static protected
This static method searches in a given sequence of TLVs to find the first TLV with a given TLV Type and stable flag.
Parameters
[in] aStart A pointer to the start of the sequence of TLVs to search within.
[in] aEnd A pointer to the end of the sequence of TLVs.
[in] aType The TLV type to find.
[in] aStable TRUE to find a stable TLV, FALSE to find a TLV not marked as stable.
Returns
A pointer to the TLV if found, or NULL if not found.
References NetworkData::FindTlv().
FindTlv() [6/8]
const NetworkDataTlv * FindTlv (const NetworkDataTlv * aStart, const NetworkDataTlv * aEnd, NetworkDataTlv::Type aType, bool aStable) static protected
This static method searches in a given sequence of TLVs to find the first TLV with a given TLV Type and stable flag.
Parameters
[in] aStart A pointer to the start of the sequence of TLVs to search within.
[in] aEnd A pointer to the end of the sequence of TLVs.
[in] aType The TLV type to find.
[in] aStable TRUE to find a stable TLV, FALSE to find a TLV not marked as stable.
Returns
A pointer to the TLV if found, or NULL if not found.
References ExitNow, NetworkDataTlv::GetNext(), and VerifyOrExit.
FindTlv() [7/8]
static TlvType* FindTlv (NetworkDataTlv * aStart, NetworkDataTlv * aEnd, bool aStable) inline static protected
This template static method searches in a given sequence of TLVs to find the first TLV with a given TLV Type and stable flag.
Parameters
[in] aStart A pointer to the start of the sequence of TLVs to search within.
[in] aEnd A pointer to the end of the sequence of TLVs.
[in] aStable TRUE to find a stable TLV, FALSE to find a TLV not marked as stable.
Returns
A pointer to the TLV if found, or NULL if not found.
References NetworkData::FindTlv().
FindTlv() [8/8]
static const TlvType* FindTlv (const NetworkDataTlv * aStart, const NetworkDataTlv * aEnd, bool aStable) inline static protected
This template static method searches in a given sequence of TLVs to find the first TLV with a given TLV Type and stable flag.
Parameters
[in] aStart A pointer to the start of the sequence of TLVs to search within.
[in] aEnd A pointer to the end of the sequence of TLVs.
[in] aStable TRUE to find a stable TLV, FALSE to find a TLV not marked as stable.
Returns
A pointer to the TLV if found, or NULL if not found.
References NetworkData::FindTlv().
NetworkDataIterator()
NetworkDataIterator (Iterator & aIterator) inline explicit
GetTlv()
const NetworkDataTlv* GetTlv (const uint8_t * aTlvs) const inline
References NetworkData::NetworkDataIterator::GetTlvOffset().
Referenced by NetworkData::NetworkDataIterator::AdvanceTlv(), and NetworkData::Iterate().
AdvanceTlv()
void AdvanceTlv (const uint8_t * aTlvs) inline
References NetworkData::NetworkDataIterator::GetTlv(), NetworkData::NetworkDataIterator::SaveTlvOffset(), NetworkData::NetworkDataIterator::SetEntryIndex(), and NetworkData::NetworkDataIterator::SetSubTlvOffset().
Referenced by NetworkData::Iterate().
GetSubTlv()
const NetworkDataTlv* GetSubTlv (const NetworkDataTlv * aSubTlvs) const inline
References NetworkData::NetworkDataIterator::GetSubTlvOffset().
Referenced by NetworkData::NetworkDataIterator::AdvaceSubTlv(), and NetworkData::Iterate().
AdvaceSubTlv()
void AdvaceSubTlv (const NetworkDataTlv * aSubTlvs) inline
References NetworkData::NetworkDataIterator::GetSubTlv(), NetworkData::NetworkDataIterator::SaveSubTlvOffset(), and NetworkData::NetworkDataIterator::SetEntryIndex().
Referenced by NetworkData::Iterate().
GetAndAdvanceIndex()
uint8_t GetAndAdvanceIndex (void) inline
References NetworkData::NetworkDataIterator::kEntryPosition, and NetworkData::NetworkDataIterator::mIteratorBuffer.
Referenced by NetworkData::Iterate().
IsNewEntry()
bool IsNewEntry (void) const inline
References NetworkData::NetworkDataIterator::GetEntryIndex().
Referenced by NetworkData::Iterate().
MarkEntryAsNotNew()
void MarkEntryAsNotNew (void) inline
References NetworkData::NetworkDataIterator::SetEntryIndex().
Referenced by NetworkData::Iterate().
GetTlvOffset()
uint8_t GetTlvOffset (void) const inline private
References NetworkData::NetworkDataIterator::kTlvPosition, and NetworkData::NetworkDataIterator::mIteratorBuffer.
Referenced by NetworkData::NetworkDataIterator::GetTlv().
GetSubTlvOffset()
uint8_t GetSubTlvOffset (void) const inline private
References NetworkData::NetworkDataIterator::kSubTlvPosition, and NetworkData::NetworkDataIterator::mIteratorBuffer.
Referenced by NetworkData::NetworkDataIterator::GetSubTlv().
SetSubTlvOffset()
void SetSubTlvOffset (uint8_t aOffset) inline private
References NetworkData::NetworkDataIterator::kSubTlvPosition, and NetworkData::NetworkDataIterator::mIteratorBuffer.
Referenced by NetworkData::NetworkDataIterator::AdvanceTlv(), and NetworkData::NetworkDataIterator::SaveSubTlvOffset().
SetTlvOffset()
void SetTlvOffset (uint8_t aOffset) inline private
References NetworkData::NetworkDataIterator::kTlvPosition, and NetworkData::NetworkDataIterator::mIteratorBuffer.
Referenced by NetworkData::NetworkDataIterator::SaveTlvOffset().
GetEntryIndex()
uint8_t GetEntryIndex (void) const inline private
References NetworkData::NetworkDataIterator::kEntryPosition, and NetworkData::NetworkDataIterator::mIteratorBuffer.
Referenced by NetworkData::NetworkDataIterator::IsNewEntry().
SetEntryIndex()
void SetEntryIndex (uint8_t aIndex) inline private
References NetworkData::NetworkDataIterator::kEntryPosition, and NetworkData::NetworkDataIterator::mIteratorBuffer.
Referenced by NetworkData::NetworkDataIterator::AdvaceSubTlv(), NetworkData::NetworkDataIterator::AdvanceTlv(), and NetworkData::NetworkDataIterator::MarkEntryAsNotNew().
SaveTlvOffset()
void SaveTlvOffset (const NetworkDataTlv * aTlv, const uint8_t * aTlvs) inline private
References NetworkData::NetworkDataIterator::SetTlvOffset().
Referenced by NetworkData::NetworkDataIterator::AdvanceTlv().
SaveSubTlvOffset()
void SaveSubTlvOffset (const NetworkDataTlv * aSubTlv, const NetworkDataTlv * aSubTlvs) inline private
References NetworkData::NetworkDataIterator::SetSubTlvOffset().
Referenced by NetworkData::NetworkDataIterator::AdvaceSubTlv().
Iterate()
otError Iterate (Iterator & aIterator, uint16_t aRloc16, Config & aConfig) const private
References NetworkData::NetworkDataIterator::AdvaceSubTlv(), NetworkData::NetworkDataIterator::AdvanceTlv(), BitVectorBytes, ExitNow, NetworkData::NetworkDataIterator::GetAndAdvanceIndex(), ServiceTlv::GetEnterpriseNumber(), HasRouteTlv::GetEntry(), BorderRouterTlv::GetEntry(), NetworkDataTlv::GetNext(), HasRouteTlv::GetNumEntries(), BorderRouterTlv::GetNumEntries(), HasRouteEntry::GetPreference(), BorderRouterEntry::GetPreference(), PrefixTlv::GetPrefix(), PrefixTlv::GetPrefixLength(), HasRouteEntry::GetRloc(), BorderRouterEntry::GetRloc(), ServerTlv::GetServer16(), ServerTlv::GetServerData(), ServerTlv::GetServerDataLength(), ServiceTlv::GetServiceData(), ServiceTlv::GetServiceDataLength(), ServiceTlv::GetServiceId(), NetworkData::NetworkDataIterator::GetSubTlv(), NetworkData::NetworkDataIterator::GetTlv(), NetworkData::GetTlvsEnd(), BorderRouterEntry::IsConfigure(), BorderRouterEntry::IsDefaultRoute(), BorderRouterEntry::IsDhcp(), BorderRouterEntry::IsDp(), BorderRouterEntry::IsNdDns(), NetworkData::NetworkDataIterator::IsNewEntry(), BorderRouterEntry::IsOnMesh(), BorderRouterEntry::IsPreferred(), BorderRouterEntry::IsSlaac(), NetworkDataTlv::IsStable(), ot::Mac::kShortAddrBroadcast, NetworkDataTlv::kTypeBorderRouter, NetworkDataTlv::kTypeHasRoute, NetworkDataTlv::kTypePrefix, NetworkDataTlv::kTypeServer, NetworkDataTlv::kTypeService, NetworkData::NetworkDataIterator::MarkEntryAsNotNew(), otBorderRouterConfig::mConfigure, otBorderRouterConfig::mDefaultRoute, otBorderRouterConfig::mDhcp, otBorderRouterConfig::mDp, otServiceConfig::mEnterpriseNumber, NetworkData::Config::mExternalRoute, otIp6Prefix::mLength, otBorderRouterConfig::mNdDns, otExternalRouteConfig::mNextHopIsThisDevice, otBorderRouterConfig::mOnMesh, NetworkData::Config::mOnMeshPrefix, otBorderRouterConfig::mPreference, otExternalRouteConfig::mPreference, otBorderRouterConfig::mPreferred, otBorderRouterConfig::mPrefix, otIp6Prefix::mPrefix, otExternalRouteConfig::mPrefix, otBorderRouterConfig::mRloc16, otExternalRouteConfig::mRloc16, otServerConfig::mRloc16, otServiceConfig::mServerConfig, otServerConfig::mServerData, otServerConfig::mServerDataLength, NetworkData::Config::mService, otServiceConfig::mServiceData, otServiceConfig::mServiceDataLength, otServiceConfig::mServiceId, otBorderRouterConfig::mSlaac, otBorderRouterConfig::mStable, otExternalRouteConfig::mStable, otServerConfig::mStable, NetworkData::mTlvs, OT_ERROR_NONE, and OT_ERROR_NOT_FOUND.
Referenced by NetworkData::GetNextExternalRoute(), NetworkData::GetNextOnMeshPrefix(), NetworkData::GetNextServer(), and NetworkData::GetNextService().
RemoveTemporaryData() [2/3]
void RemoveTemporaryData (uint8_t * aData, uint8_t & aDataLength, PrefixTlv & aPrefix) static private
References NetworkData::FindContext(), ContextTlv::GetContextId(), HasRouteTlv::GetFirstEntry(), BorderRouterTlv::GetFirstEntry(), HasRouteTlv::GetLastEntry(), BorderRouterTlv::GetLastEntry(), NetworkDataTlv::GetNext(), HasRouteEntry::GetNext(), BorderRouterEntry::GetNext(), NetworkDataTlv::GetSize(), PrefixTlv::GetSubTlvs(), PrefixTlv::GetSubTlvsLength(), NetworkDataTlv::GetType(), NetworkDataTlv::IsStable(), NetworkDataTlv::kTypeBorderRouter, NetworkDataTlv::kTypeHasRoute, NetworkData::RemoveTlv(), and PrefixTlv::SetSubTlvsLength().
RemoveTemporaryData() [3/3]
void RemoveTemporaryData (uint8_t * aData, uint8_t & aDataLength, ServiceTlv & aService) static private
References NetworkDataTlv::GetNext(), ServiceTlv::GetServiceId(), NetworkDataTlv::GetSize(), ServiceTlv::GetSubTlvs(), ServiceTlv::GetSubTlvsLength(), NetworkDataTlv::GetType(), NetworkDataTlv::IsStable(), NetworkDataTlv::kTypeServer, NetworkData::RemoveTlv(), Mle::ServiceAlocFromId(), ServerTlv::SetServer16(), and ServiceTlv::SetSubTlvsLength().
Remove() [2/2]
void Remove (uint8_t * aData, uint8_t & aDataLength, uint8_t * aRemoveStart, uint8_t aRemoveLength) static private
References OT_ASSERT.
RemoveTlv() [2/2]
void RemoveTlv (uint8_t * aData, uint8_t & aDataLength, NetworkDataTlv * aTlv) static private
References NetworkDataTlv::GetSize(), and NetworkData::Remove().
Variable Documentation
mTlvs
uint8_t mTlvs[kMaxSize] protected
The Network Data buffer.
Referenced by NetworkData::FindPrefix(), NetworkData::FindService(), NetworkData::GetNetworkData(), NetworkData::GetTlvsEnd(), NetworkData::GetTlvsStart(), NetworkData::Insert(), NetworkData::Iterate(), NetworkData::Remove(), NetworkData::RemoveTlv(), NetworkData::SendServerDataNotification(), and LeaderBase::SetNetworkData().
mIteratorBuffer
uint8_t* mIteratorBuffer private
Referenced by NetworkData::NetworkDataIterator::GetAndAdvanceIndex(), NetworkData::NetworkDataIterator::GetEntryIndex(), NetworkData::NetworkDataIterator::GetSubTlvOffset(), NetworkData::NetworkDataIterator::GetTlvOffset(), NetworkData::NetworkDataIterator::SetEntryIndex(), NetworkData::NetworkDataIterator::SetSubTlvOffset(), and NetworkData::NetworkDataIterator::SetTlvOffset().
mOnMeshPrefix
OnMeshPrefixConfig* mOnMeshPrefix
Referenced by NetworkData::GetNextExternalRoute(), NetworkData::GetNextOnMeshPrefix(), NetworkData::GetNextServer(), NetworkData::GetNextService(), and NetworkData::Iterate().
mExternalRoute
ExternalRouteConfig* mExternalRoute
Referenced by NetworkData::GetNextExternalRoute(), NetworkData::GetNextOnMeshPrefix(), NetworkData::GetNextServer(), NetworkData::GetNextService(), and NetworkData::Iterate().
mService
ServiceConfig* mService
Referenced by NetworkData::GetNextExternalRoute(), NetworkData::GetNextOnMeshPrefix(), NetworkData::GetNextServer(), NetworkData::GetNextService(), and NetworkData::Iterate().
mType
const Type mType private
Referenced by NetworkData::SendServerDataNotification().
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale