OpenThread: Core-dhcp6
Core-dhcp6
This module includes definitions for DHCPv6.
Data Structures
class ClientIdentifier
class Dhcp6Client
class Dhcp6Header
class Dhcp6Option
class Dhcp6Server
class ElapsedTime
class IaAddress
class IaNa
struct IdentityAssociation
class Dhcp6Server::PrefixAgent
class RapidCommit
class ServerIdentifier
class StatusCode
Macros
#define OT_DHCP6_DEFAULT_IA_NA_T1 0xffffffffU
#define OT_DHCP6_DEFAULT_IA_NA_T2 0xffffffffU
#define OT_DHCP6_DEFAULT_PREFERRED_LIFETIME 0xffffffffU
#define OT_DHCP6_DEFAULT_VALID_LIFETIME 0xffffffffU
Typedefs
typedef enum ot::Dhcp6::Code Code
typedef enum ot::Dhcp6::DuidType DuidType
typedef enum ot::Dhcp6::Status Status
typedef enum ot::Dhcp6::Type Type
Enumerations
enum {
kDhcpClientPort = 546, kDhcpServerPort = 547, kTransactionIdSize = 3, kLinkLayerAddressLen = 8,
kHardwareTypeEui64 = 27, kHardwareTypeEthernet = 1, kLinkLayerAddressPlusLen = 6
}
enum { kTrickleTimerImin = 1, kTrickleTimerImax = 120 }
enum Code {
kOptionClientIdentifier = 1, kOptionServerIdentifier = 2, kOptionIaNa = 3, kOptionIaTa = 4,
kOptionIaAddress = 5, kOptionRequestOption = 6, kOptionPreference = 7, kOptionElapsedTime = 8,
kOptionRelayMessage = 9, kOptionAuthentication = 11, kOptionServerUnicast = 12, kOptionStatusCode = 13,
kOptionRapidCommit = 14, kOptionUserClass = 15, kOptionVendorClass = 16, kOptionVendorSpecificInformation = 17,
kOptionInterfaceId = 18, kOptionReconfigureMessage = 19, kOptionReconfigureAccept = 20, kOptionLeaseQuery = 44,
kOptionClientData = 45, kOptionClientLastTransactionTime = 46
}
enum DuidType { kDuidLLT = 1, kDuidEN = 2, kDuidLL = 3 }
enum IaStatus { kIaStatusInvalid, kIaStatusSolicit, kIaStatusSoliciting, kIaStatusSolicitReplied }
enum Status {
kStatusSuccess = 0, kStatusUnspecFail = 1, kStatusNoAddrsAvail = 2, kStatusNoBinding = 3,
kStatusNotOnLink = 4, kStatusUseMulticast = 5, kUnknownQueryType = 7, kMalformedQuery = 8,
kNotConfigured = 9, kNotAllowed = 10
}
enum Type {
kTypeSolicit = 1, kTypeAdvertise = 2, kTypeRequest = 3, kTypeConfirm = 4,
kTypeRenew = 5, kTypeRebind = 6, kTypeReply = 7, kTypeRelease = 8,
kTypeDecline = 9, kTypeReconfigure = 10, kTypeInformationRequest = 11, kTypeRelayForward = 12,
kTypeRelayReply = 13, kTypeLeaseQuery = 14, kTypeLeaseQueryReply = 15
}
Functions
otError AddIaAddress (Message &aMessage, const Ip6::Address &aPrefix, ClientIdentifier &aClientId)
void AddIdentityAssociation (uint16_t aRloc16, otIp6Prefix &aIp6Prefix)
otError AddPrefixAgent (const otIp6Prefix &aIp6Prefix, const Lowpan::Context &aContext)
otError AppendClientIdentifier (Message &aMessage)
otError AppendClientIdentifier (Message &aMessage, ClientIdentifier &aClientId)
otError AppendElapsedTime (Message &aMessage)
otError AppendHeader (Message &aMessage)
otError AppendHeader (Message &aMessage, uint8_t *aTransactionId)
otError AppendIaAddress (Message &aMessage, uint16_t aRloc16)
otError AppendIaAddress (Message &aMessage, ClientIdentifier &aClientId)
otError AppendIaNa (Message &aMessage, uint16_t aRloc16)
otError AppendIaNa (Message &aMessage, IaNa &aIaNa)
otError AppendRapidCommit (Message &aMessage)
otError AppendRapidCommit (Message &aMessage)
otError AppendServerIdentifier (Message &aMessage)
otError AppendStatusCode (Message &aMessage, Status aStatusCode)
otError AppendVendorSpecificInformation (Message &aMessage)
void ApplyMeshLocalPrefix (void)
void Clear (void)
Dhcp6Client (Instance &aInstance)
Dhcp6Server (Instance &aInstance)
uint16_t FindOption (Message &aMessage, uint16_t aOffset, uint16_t aLength, Code aCode)
uint16_t FindOption (Message &aMessage, uint16_t aOffset, uint16_t aLength, Code aCode)
Ip6::Address & GetAddress (void)
Ip6::NetifUnicastAddress & GetAloc (void)
Code GetCode (void) const
uint8_t GetContextId (void) const
uint16_t GetDuidHardwareType (void) const
uint16_t GetDuidHardwareType (void) const
uint8_t * GetDuidLinkLayerAddress (void)
uint8_t * GetDuidLinkLayerAddress (void)
DuidType GetDuidType (void) const
DuidType GetDuidType (void) const
uint16_t GetElapsedTime (void) const
uint32_t GetIaid (void) const
uint16_t GetLength (void) const
uint32_t GetPreferredLifetime (void) const
const Ip6::Address & GetPrefix (void) const
Status GetStatusCode (void) const
uint32_t GetT1 (void) const
uint32_t GetT2 (void) const
uint8_t * GetTransactionId (void)
Type GetType (void) const
uint32_t GetValidLifetime (void) const
static bool HandleTrickleTimer (TrickleTimer &aTrickleTimer)
bool HandleTrickleTimer (void)
static void HandleUdpReceive (void *aContext, otMessage *aMessage, const otMessageInfo *aMessageInfo)
void HandleUdpReceive (Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
static void HandleUdpReceive (void *aContext, otMessage *aMessage, const otMessageInfo *aMessageInfo)
void HandleUdpReceive (Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
void Init (void)
void Init (void)
void Init (void)
void Init (void)
void Init (void)
void Init (void)
void Init (void)
void Init (void)
void Init (void)
bool IsPrefixMatch (const otIp6Prefix &aPrefix) const
bool IsPrefixMatch (const otIp6Address &aAddress) const
bool IsValid (void) const
static bool MatchNetifAddressWithPrefix (const Ip6::NetifUnicastAddress &aAddress, const otIp6Prefix &aIp6Prefix)
otError ProcessClientIdentifier (Message &aMessage, uint16_t aOffset)
otError ProcessClientIdentifier (Message &aMessage, uint16_t aOffset, ClientIdentifier &aClientId)
otError ProcessElapsedTime (Message &aMessage, uint16_t aOffset)
otError ProcessIaAddress (Message &aMessage, uint16_t aOffset)
otError ProcessIaAddress (Message &aMessage, uint16_t aOffset)
otError ProcessIaNa (Message &aMessage, uint16_t aOffset)
otError ProcessIaNa (Message &aMessage, uint16_t aOffset, IaNa &aIaNa)
bool ProcessNextIdentityAssociation (void)
void ProcessReply (Message &aMessage)
otError ProcessServerIdentifier (Message &aMessage, uint16_t aOffset)
void ProcessSolicit (Message &aMessage, otIp6Address &aDst, uint8_t *aTransactionId)
otError ProcessStatusCode (Message &aMessage, uint16_t aOffset)
void RemoveIdentityAssociation (uint16_t aRloc16, otIp6Prefix &aIp6Prefix)
otError SendReply (otIp6Address &aDst, uint8_t *aTransactionId, ClientIdentifier &aClientId, IaNa &aIaNa)
void Set (const otIp6Prefix &aPrefix, const Mle::MeshLocalPrefix &aMeshLocalPrefix, uint8_t aContextId)
void SetAddress (otIp6Address &aAddress)
void SetCode (Code aCode)
void SetDuidHardwareType (uint16_t aDuidHardwareType)
void SetDuidHardwareType (uint16_t aDuidHardwareType)
void SetDuidLinkLayerAddress (const Mac::ExtAddress &aDuidLinkLayerAddress)
void SetDuidLinkLayerAddress (const Mac::ExtAddress &aDuidLinkLayerAddress)
void SetDuidType (DuidType aDuidType)
void SetDuidType (DuidType aDuidType)
void SetElapsedTime (uint16_t aElapsedTime)
void SetIaid (uint32_t aIaid)
void SetLength (uint16_t aLength)
void SetPreferredLifetime (uint32_t aPreferredLifetime)
void SetStatusCode (Status aStatus)
void SetT1 (uint32_t aT1)
void SetT2 (uint32_t aT2)
void SetTransactionId (uint8_t *aBuf)
void SetType (Type aType)
void SetValidLifetime (uint32_t aValidLifetime)
otError Solicit (uint16_t aRloc16)
void Start (void)
void Start (void)
void Stop (void)
void Stop (void)
void UpdateAddresses (void)
otError UpdateService ()
Variables
Ip6::Address mAddress
IPv6 address.
Ip6::NetifUnicastAddress mAloc
uint16_t mCode
Code.
uint16_t mDuidHardwareType
Duid HardwareType.
uint16_t mDuidHardwareType
Duid HardwareType.
uint8_t mDuidLinkLayerAddress [kLinkLayerAddressLen]
Duid LinkLayerAddress.
uint8_t mDuidLinkLayerAddress [kLinkLayerAddressLen]
Duid LinkLayerAddress.
uint16_t mDuidType
Duid Type.
uint16_t mDuidType
Duid Type.
uint16_t mElapsedTime
Elapsed time.
uint32_t mIaid
IAID.
IdentityAssociation * mIdentityAssociationCurrent
IdentityAssociation mIdentityAssociations [OPENTHREAD_CONFIG_DHCP6_CLIENT_NUM_PREFIXES]
uint16_t mLength
Length.
Ip6::NetifUnicastAddress mNetifAddress
the NetifAddress
uint32_t mPreferredLifetime
The preferred lifetime.
uint32_t mPreferredLifetime
Preferred Lifetime.
otIp6Prefix mPrefix
uint16_t mPrefixAgentRloc
Rloc of Prefix Agent.
PrefixAgent mPrefixAgents [OPENTHREAD_CONFIG_DHCP6_SERVER_NUM_PREFIXES]
uint8_t mPrefixAgentsCount
uint8_t mPrefixAgentsMask
Ip6::UdpSocket mSocket
Ip6::UdpSocket mSocket
TimeMilli mStartTime
uint8_t mStatus
Status of IdentityAssociation.
uint16_t mStatus
Status Code.
uint32_t mT1
T1.
uint32_t mT2
T2.
uint8_t mTransactionId [kTransactionIdSize]
Transaction Id.
uint8_t mTransactionId [kTransactionIdSize]
TrickleTimer mTrickleTimer
uint8_t mType
Type.
uint32_t mValidLifetime
The valid lifetime.
uint32_t mValidLifetime
Valid Lifetime.
OT_TOOL_PACKED_BEGIN class ot::Dhcp6::Dhcp6Header OT_TOOL_PACKED_END
Detailed Description
This module includes definitions for DHCPv6.
This module includes definitions for DHCPv6 Server.
This module includes definitions for DHCPv6 Client.
Macro Definition Documentation
OT_DHCP6_DEFAULT_IA_NA_T1
#define OT_DHCP6_DEFAULT_IA_NA_T1 0xffffffffU
DHCPv6 default constant
OT_DHCP6_DEFAULT_IA_NA_T2
#define OT_DHCP6_DEFAULT_IA_NA_T2 0xffffffffU
OT_DHCP6_DEFAULT_PREFERRED_LIFETIME
#define OT_DHCP6_DEFAULT_PREFERRED_LIFETIME 0xffffffffU
OT_DHCP6_DEFAULT_VALID_LIFETIME
#define OT_DHCP6_DEFAULT_VALID_LIFETIME 0xffffffffU
Typedef Documentation
Type
typedef enum ot::Dhcp6::Type Type
DHCPv6 Message Types
Code
typedef enum ot::Dhcp6::Code Code
DHCPv6 Option Codes
DuidType
typedef enum ot::Dhcp6::DuidType DuidType
Duid Type
Status
typedef enum ot::Dhcp6::Status Status
Status Code
Enumeration Type Documentation
anonymous enum
anonymous enum
DHCPv6 constant
Enumerator
kDhcpClientPort
kDhcpServerPort
kTransactionIdSize
kLinkLayerAddressLen
kHardwareTypeEui64
kHardwareTypeEthernet
kLinkLayerAddressPlusLen
Type
enum Type
DHCPv6 Message Types
Enumerator
kTypeSolicit
kTypeAdvertise
kTypeRequest
kTypeConfirm
kTypeRenew
kTypeRebind
kTypeReply
kTypeRelease
kTypeDecline
kTypeReconfigure
kTypeInformationRequest
kTypeRelayForward
kTypeRelayReply
kTypeLeaseQuery
kTypeLeaseQueryReply
Code
enum Code
DHCPv6 Option Codes
Enumerator
kOptionClientIdentifier
kOptionServerIdentifier
kOptionIaNa
kOptionIaTa
kOptionIaAddress
kOptionRequestOption
kOptionPreference
kOptionElapsedTime
kOptionRelayMessage
kOptionAuthentication
kOptionServerUnicast
kOptionStatusCode
kOptionRapidCommit
kOptionUserClass
kOptionVendorClass
kOptionVendorSpecificInformation
kOptionInterfaceId
kOptionReconfigureMessage
kOptionReconfigureAccept
kOptionLeaseQuery
kOptionClientData
kOptionClientLastTransactionTime
DuidType
enum DuidType
Duid Type
Enumerator
kDuidLLT
kDuidEN
kDuidLL
Status
enum Status
Status Code
Enumerator
kStatusSuccess
kStatusUnspecFail
kStatusNoAddrsAvail
kStatusNoBinding
kStatusNotOnLink
kStatusUseMulticast
kUnknownQueryType
kMalformedQuery
kNotConfigured
kNotAllowed
anonymous enum
anonymous enum
Some constants
Enumerator
kTrickleTimerImin
kTrickleTimerImax
IaStatus
enum IaStatus
Status of IdentityAssociation
Enumerator
kIaStatusInvalid
kIaStatusSolicit
kIaStatusSoliciting
kIaStatusSolicitReplied
Function Documentation
Init() [1/9]
void Init (void) inline
This method initializes the DHCPv6 header to all zeros.
References Dhcp6Header::mTransactionId, and Dhcp6Header::mType.
GetType()
Type GetType (void) const inline
This method returns the DHCPv6 message type.
Returns
The DHCPv6 message type.
References Dhcp6Header::mType.
SetType()
void SetType (Type aType) inline
This method sets the DHCPv6 message type.
Parameters
[in] aType The DHCPv6 message type.
References Dhcp6Header::mType.
GetTransactionId()
uint8_t* GetTransactionId (void) inline
This method returns the DHCPv6 message transaction id.
Returns
A pointer of DHCPv6 message transaction id.
References Dhcp6Header::mTransactionId.
SetTransactionId()
void SetTransactionId (uint8_t * aBuf) inline
This method sets the DHCPv6 message transaction id.
Parameters
[in] aBuf The DHCPv6 message transaction id.
References ot::Dhcp6::kTransactionIdSize, and Dhcp6Header::mTransactionId.
Init() [2/9]
void Init (void) inline
This method initializes the DHCPv6 option to all zeros.
GetCode()
Code GetCode (void) const inline
This method returns the DHCPv6 option code.
Returns
The DHCPv6 option code.
References ot::Encoding::BigEndian::HostSwap16().
SetCode()
void SetCode (Code aCode) inline
This method sets the DHCPv6 option code.
Parameters
[in] aCode The DHCPv6 option code.
References ot::Encoding::BigEndian::HostSwap16().
GetLength()
uint16_t GetLength (void) const inline
This method returns the Length of DHCPv6 option.
Returns
The length of DHCPv6 option.
References ot::Encoding::BigEndian::HostSwap16().
SetLength()
void SetLength (uint16_t aLength) inline
This method sets the length of DHCPv6 option.
Parameters
[in] aLength The length of DHCPv6 option.
References ot::Encoding::BigEndian::HostSwap16().
Init() [3/9]
void Init (void) inline
This method initializes the DHCPv6 Option.
References ot::Dhcp6::kOptionClientIdentifier.
GetDuidType() [1/2]
DuidType GetDuidType (void) const inline
This method returns the client Duid Type.
Returns
The client Duid Type.
References ot::Encoding::BigEndian::HostSwap16().
SetDuidType() [1/2]
void SetDuidType (DuidType aDuidType) inline
This method sets the client Duid Type.
Parameters
[in] aDuidType The client Duid Type.
References ot::Encoding::BigEndian::HostSwap16().
GetDuidHardwareType() [1/2]
uint16_t GetDuidHardwareType (void) const inline
This method returns the client Duid HardwareType.
Returns
The client Duid HardwareType.
References ot::Encoding::BigEndian::HostSwap16().
SetDuidHardwareType() [1/2]
void SetDuidHardwareType (uint16_t aDuidHardwareType) inline
This method sets the client Duid HardwareType.
Parameters
[in] aDuidHardwareType The client Duid HardwareType.
References ot::Encoding::BigEndian::HostSwap16().
GetDuidLinkLayerAddress() [1/2]
uint8_t* GetDuidLinkLayerAddress (void) inline
This method returns the client LinkLayerAddress.
Returns
A pointer to the client LinkLayerAddress.
SetDuidLinkLayerAddress() [1/2]
void SetDuidLinkLayerAddress (const Mac::ExtAddress & aDuidLinkLayerAddress) inline
This method sets the client LinkLayerAddress.
Parameters
[in] aLinkLayerAddress The client LinkLayerAddress.
Init() [4/9]
void Init (void) inline
This method initializes the DHCPv6 Option.
References ot::Dhcp6::kOptionServerIdentifier.
GetDuidType() [2/2]
DuidType GetDuidType (void) const inline
This method returns the server Duid Type.
Returns
The server Duid Type.
References ot::Encoding::BigEndian::HostSwap16().
SetDuidType() [2/2]
void SetDuidType (DuidType aDuidType) inline
This method sets the server Duid Type.
Parameters
[in] aDuidType The server Duid Type.
References ot::Encoding::BigEndian::HostSwap16().
GetDuidHardwareType() [2/2]
uint16_t GetDuidHardwareType (void) const inline
This method returns the server Duid HardwareType.
Returns
The server Duid HardwareType.
References ot::Encoding::BigEndian::HostSwap16().
SetDuidHardwareType() [2/2]
void SetDuidHardwareType (uint16_t aDuidHardwareType) inline
This method sets the server Duid HardwareType.
Parameters
[in] aDuidHardwareType The server Duid HardwareType.
References ot::Encoding::BigEndian::HostSwap16().
GetDuidLinkLayerAddress() [2/2]
uint8_t* GetDuidLinkLayerAddress (void) inline
This method returns the server LinkLayerAddress.
Returns
A pointer to the server LinkLayerAddress.
SetDuidLinkLayerAddress() [2/2]
void SetDuidLinkLayerAddress (const Mac::ExtAddress & aDuidLinkLayerAddress) inline
This method sets the server LinkLayerAddress.
Parameters
[in] aLinkLayerAddress The server LinkLayerAddress.
Init() [5/9]
void Init (void) inline
This method initializes the DHCPv6 Option.
References ot::Dhcp6::kOptionIaNa.
GetIaid()
uint32_t GetIaid (void) const inline
This method returns client IAID.
Returns
The client IAID.
References ot::Encoding::BigEndian::HostSwap32().
SetIaid()
void SetIaid (uint32_t aIaid) inline
This method sets the client IAID.
Parameters
[in] aIaId The client IAID.
References ot::Encoding::BigEndian::HostSwap32().
GetT1()
uint32_t GetT1 (void) const inline
This method returns T1.
Returns
The value of T1.
References ot::Encoding::BigEndian::HostSwap32().
SetT1()
void SetT1 (uint32_t aT1) inline
This method sets the value of T1.
Parameters
[in] aT1 The value of T1.
References ot::Encoding::BigEndian::HostSwap32().
GetT2()
uint32_t GetT2 (void) const inline
This method returns T2.
Returns
The value of T2.
References ot::Encoding::BigEndian::HostSwap32().
SetT2()
void SetT2 (uint32_t aT2) inline
This method sets the value of T2.
Parameters
[in] aT2 The value of T2.
References ot::Encoding::BigEndian::HostSwap32().
Init() [6/9]
void Init (void) inline
This method initializes the DHCPv6 Option.
References ot::Dhcp6::kOptionIaAddress.
GetAddress()
Ip6::Address& GetAddress (void) inline
This method returns the pointer to the IPv6 address.
Returns
A pointer to the IPv6 address.
SetAddress()
void SetAddress (otIp6Address & aAddress) inline
This method sets the IPv6 address.
Parameters
[in] aAddress The reference to the IPv6 address to set.
References otIp6Address::OT_TOOL_PACKED_FIELD::m8, and otIp6Address::mFields.
GetPreferredLifetime()
uint32_t GetPreferredLifetime (void) const inline
This method returns the preferred lifetime of the IPv6 address.
Returns
The preferred lifetime of the IPv6 address.
References ot::Encoding::BigEndian::HostSwap32().
SetPreferredLifetime()
void SetPreferredLifetime (uint32_t aPreferredLifetime) inline
This method sets the preferred lifetime of the IPv6 address.
Parameters
[in] aPreferredLifetime The preferred lifetime of the IPv6 address.
References ot::Encoding::BigEndian::HostSwap32().
GetValidLifetime()
uint32_t GetValidLifetime (void) const inline
This method returns the valid lifetime of the IPv6 address.
Returns
The valid lifetime of the IPv6 address.
References ot::Encoding::BigEndian::HostSwap32().
SetValidLifetime()
void SetValidLifetime (uint32_t aValidLifetime) inline
This method sets the valid lifetime of the IPv6 address.
Parameters
[in] aValidLifetime The valid lifetime of the IPv6 address.
References ot::Encoding::BigEndian::HostSwap32().
Init() [7/9]
void Init (void) inline
This method initializes the DHCPv6 Option.
References ot::Dhcp6::kOptionElapsedTime.
GetElapsedTime()
uint16_t GetElapsedTime (void) const inline
This method returns the elapsed time since solicit starts.
Returns
The elapsed time since solicit starts.
References ot::Encoding::BigEndian::HostSwap16().
SetElapsedTime()
void SetElapsedTime (uint16_t aElapsedTime) inline
This method sets the elapsed time since solicit starts.
Parameters
[in] aElapsedTime The elapsed time since solicit starts.
References ot::Encoding::BigEndian::HostSwap16().
Init() [8/9]
void Init (void) inline
This method initializes the DHCPv6 Option.
References ot::Dhcp6::kOptionStatusCode.
GetStatusCode()
Status GetStatusCode (void) const inline
This method returns the status code.
Returns
The status code.
References ot::Encoding::BigEndian::HostSwap16().
SetStatusCode()
void SetStatusCode (Status aStatus) inline
This method sets the status code.
Parameters
[in] aStatus The status code.
References ot::Encoding::BigEndian::HostSwap16().
Init() [9/9]
void Init (void) inline
This method initializes the DHCPv6 Option.
References ot::Dhcp6::kOptionRapidCommit, and ot::Dhcp6::OT_TOOL_PACKED_END.
Dhcp6Client()
Dhcp6Client (Instance & aInstance) explicit
This constructor initializes the object.
Parameters
[in] aInstance A reference to the OpenThread instance.
UpdateAddresses()
void UpdateAddresses (void)
This method update addresses that shall be automatically created using DHCP.
Start() [1/2]
void Start (void) private
Stop() [1/2]
void Stop (void) private
MatchNetifAddressWithPrefix()
static bool MatchNetifAddressWithPrefix (const Ip6::NetifUnicastAddress & aAddress, const otIp6Prefix & aIp6Prefix) static private
Solicit()
otError Solicit (uint16_t aRloc16) private
AddIdentityAssociation()
void AddIdentityAssociation (uint16_t aRloc16, otIp6Prefix & aIp6Prefix) private
RemoveIdentityAssociation()
void RemoveIdentityAssociation (uint16_t aRloc16, otIp6Prefix & aIp6Prefix) private
ProcessNextIdentityAssociation()
bool ProcessNextIdentityAssociation (void) private
AppendHeader() [1/2]
otError AppendHeader (Message & aMessage) private
AppendClientIdentifier() [1/2]
otError AppendClientIdentifier (Message & aMessage) private
AppendIaNa() [1/2]
otError AppendIaNa (Message & aMessage, uint16_t aRloc16) private
AppendIaAddress() [1/2]
otError AppendIaAddress (Message & aMessage, uint16_t aRloc16) private
AppendElapsedTime()
otError AppendElapsedTime (Message & aMessage) private
AppendRapidCommit() [1/2]
otError AppendRapidCommit (Message & aMessage) private
HandleUdpReceive() [1/4]
static void HandleUdpReceive (void * aContext, otMessage * aMessage, const otMessageInfo * aMessageInfo) static private
HandleUdpReceive() [2/4]
void HandleUdpReceive (Message & aMessage, const Ip6::MessageInfo & aMessageInfo) private
ProcessReply()
void ProcessReply (Message & aMessage) private
FindOption() [1/2]
uint16_t FindOption (Message & aMessage, uint16_t aOffset, uint16_t aLength, Code aCode) private
ProcessServerIdentifier()
otError ProcessServerIdentifier (Message & aMessage, uint16_t aOffset) private
ProcessClientIdentifier() [1/2]
otError ProcessClientIdentifier (Message & aMessage, uint16_t aOffset) private
ProcessIaNa() [1/2]
otError ProcessIaNa (Message & aMessage, uint16_t aOffset) private
ProcessStatusCode()
otError ProcessStatusCode (Message & aMessage, uint16_t aOffset) private
ProcessIaAddress() [1/2]
otError ProcessIaAddress (Message & aMessage, uint16_t aOffset) private
HandleTrickleTimer() [1/2]
static bool HandleTrickleTimer (TrickleTimer & aTrickleTimer) static private
HandleTrickleTimer() [2/2]
bool HandleTrickleTimer (void) private
Dhcp6Server()
Dhcp6Server (Instance & aInstance) explicit
This constructor initializes the object.
Parameters
[in] aInstance A reference to the OpenThread instance.
UpdateService()
otError UpdateService ()
This method updates DHCP Agents and DHCP Alocs.
ApplyMeshLocalPrefix()
void ApplyMeshLocalPrefix (void)
This method applies the Mesh Local Prefix.
IsPrefixMatch() [1/2]
bool IsPrefixMatch (const otIp6Prefix & aPrefix) const inline
This method indicates whether or not aPrefix matches this entry.
Parameters
[in] aPrefix The prefix to compare.
Return values
TRUE if the prefix matches.
FALSE if the prefix does not match.
References otIp6Prefix::mLength, otIp6Prefix::mPrefix, Dhcp6Server::PrefixAgent::mPrefix, and otIp6PrefixMatch().
IsPrefixMatch() [2/2]
bool IsPrefixMatch (const otIp6Address & aAddress) const inline
This method indicates whether or not aAddress has a matching prefix.
Parameters
[in] aAddress The IPv6 address to compare.
Return values
TRUE if the address has a matching prefix.
FALSE if the address does not have a matching prefix.
References otIp6Prefix::mLength, otIp6Prefix::mPrefix, Dhcp6Server::PrefixAgent::mPrefix, and otIp6PrefixMatch().
IsValid()
bool IsValid (void) const inline
This method indicates whether or not this entry is valid.
Return values
TRUE if this entry is valid.
FALSE if this entry is not valid.
References Dhcp6Server::PrefixAgent::mAloc, and otNetifAddress::mValid.
Clear()
void Clear (void) inline
This method sets the entry to invalid.
References Dhcp6Server::PrefixAgent::mAloc, and otNetifAddress::mValid.
GetContextId()
uint8_t GetContextId (void) const inline
This method returns the 6LoWPAN context ID.
Returns
The 6LoWPAN context ID.
References otIp6Address::OT_TOOL_PACKED_FIELD::m8, otNetifAddress::mAddress, Dhcp6Server::PrefixAgent::mAloc, and otIp6Address::mFields.
GetAloc()
Ip6::NetifUnicastAddress& GetAloc (void) inline
This method returns the ALOC.
Returns
the ALOC.
References Dhcp6Server::PrefixAgent::mAloc.
GetPrefix()
const Ip6::Address& GetPrefix (void) const inline
This method returns the IPv6 prefix.
Returns
The IPv6 prefix.
References otIp6Prefix::mPrefix, and Dhcp6Server::PrefixAgent::mPrefix.
Set()
void Set (const otIp6Prefix & aPrefix, const Mle::MeshLocalPrefix & aMeshLocalPrefix, uint8_t aContextId) inline
This method sets the ALOC.
Parameters
[in] aPrefix The IPv6 prefix.
[in] aMeshLocalPrefix The Mesh Local Prefix.
[in] aContextId The 6LoWPAN Context ID.
References NetifUnicastAddress::GetAddress(), Address::kAloc16Mask, Dhcp6Server::PrefixAgent::mAloc, otNetifAddress::mPreferred, Dhcp6Server::PrefixAgent::mPrefix, otNetifAddress::mPrefixLength, otNetifAddress::mValid, OT_IP6_PREFIX_BITSIZE, and Address::SetToAnycastLocator().
Start() [2/2]
void Start (void) private
Stop() [2/2]
void Stop (void) private
AddPrefixAgent()
otError AddPrefixAgent (const otIp6Prefix & aIp6Prefix, const Lowpan::Context & aContext) private
AppendHeader() [2/2]
otError AppendHeader (Message & aMessage, uint8_t * aTransactionId) private
AppendClientIdentifier() [2/2]
otError AppendClientIdentifier (Message & aMessage, ClientIdentifier & aClientId) private
AppendServerIdentifier()
otError AppendServerIdentifier (Message & aMessage) private
AppendIaNa() [2/2]
otError AppendIaNa (Message & aMessage, IaNa & aIaNa) private
AppendStatusCode()
otError AppendStatusCode (Message & aMessage, Status aStatusCode) private
AppendIaAddress() [2/2]
otError AppendIaAddress (Message & aMessage, ClientIdentifier & aClientId) private
AppendRapidCommit() [2/2]
otError AppendRapidCommit (Message & aMessage) private
AppendVendorSpecificInformation()
otError AppendVendorSpecificInformation (Message & aMessage) private
AddIaAddress()
otError AddIaAddress (Message & aMessage, const Ip6::Address & aPrefix, ClientIdentifier & aClientId) private
HandleUdpReceive() [3/4]
static void HandleUdpReceive (void * aContext, otMessage * aMessage, const otMessageInfo * aMessageInfo) static private
HandleUdpReceive() [4/4]
void HandleUdpReceive (Message & aMessage, const Ip6::MessageInfo & aMessageInfo) private
ProcessSolicit()
void ProcessSolicit (Message & aMessage, otIp6Address & aDst, uint8_t * aTransactionId) private
FindOption() [2/2]
uint16_t FindOption (Message & aMessage, uint16_t aOffset, uint16_t aLength, Code aCode) private
ProcessClientIdentifier() [2/2]
otError ProcessClientIdentifier (Message & aMessage, uint16_t aOffset, ClientIdentifier & aClientId) private
ProcessIaNa() [2/2]
otError ProcessIaNa (Message & aMessage, uint16_t aOffset, IaNa & aIaNa) private
ProcessIaAddress() [2/2]
otError ProcessIaAddress (Message & aMessage, uint16_t aOffset) private
ProcessElapsedTime()
otError ProcessElapsedTime (Message & aMessage, uint16_t aOffset) private
SendReply()
otError SendReply (otIp6Address & aDst, uint8_t * aTransactionId, ClientIdentifier & aClientId, IaNa & aIaNa) private
Variable Documentation
mType
uint8_t mType private
Type.
Referenced by Dhcp6Header::GetType(), Dhcp6Header::Init(), and Dhcp6Header::SetType().
mTransactionId [1/2]
uint8_t mTransactionId[kTransactionIdSize] private
Transaction Id.
Referenced by Dhcp6Header::GetTransactionId(), Dhcp6Header::Init(), and Dhcp6Header::SetTransactionId().
OT_TOOL_PACKED_END
ot::Dhcp6::RapidCommit OT_TOOL_PACKED_END
Referenced by RapidCommit::Init().
mCode
uint16_t mCode private
Code.
mLength
uint16_t mLength private
Length.
mDuidType [1/2]
uint16_t mDuidType private
Duid Type.
mDuidHardwareType [1/2]
uint16_t mDuidHardwareType private
Duid HardwareType.
mDuidLinkLayerAddress [1/2]
uint8_t mDuidLinkLayerAddress[kLinkLayerAddressLen] private
Duid LinkLayerAddress.
mDuidType [2/2]
uint16_t mDuidType private
Duid Type.
mDuidHardwareType [2/2]
uint16_t mDuidHardwareType private
Duid HardwareType.
mDuidLinkLayerAddress [2/2]
uint8_t mDuidLinkLayerAddress[kLinkLayerAddressLen] private
Duid LinkLayerAddress.
mIaid
uint32_t mIaid private
IAID.
mT1
uint32_t mT1 private
T1.
mT2
uint32_t mT2 private
T2.
mAddress
Ip6::Address mAddress private
IPv6 address.
mPreferredLifetime [1/2]
uint32_t mPreferredLifetime private
Preferred Lifetime.
mValidLifetime [1/2]
uint32_t mValidLifetime private
Valid Lifetime.
mElapsedTime
uint16_t mElapsedTime private
Elapsed time.
mStatus [1/2]
uint16_t mStatus private
Status Code.
mNetifAddress
Ip6::NetifUnicastAddress mNetifAddress
the NetifAddress
mPreferredLifetime [2/2]
uint32_t mPreferredLifetime
The preferred lifetime.
mValidLifetime [2/2]
uint32_t mValidLifetime
The valid lifetime.
mPrefixAgentRloc
uint16_t mPrefixAgentRloc
Rloc of Prefix Agent.
mStatus [2/2]
uint8_t mStatus
Status of IdentityAssociation.
mSocket [1/2]
Ip6::UdpSocket mSocket private
mTrickleTimer
TrickleTimer mTrickleTimer private
mTransactionId [2/2]
uint8_t mTransactionId[kTransactionIdSize] private
mStartTime
TimeMilli mStartTime private
mIdentityAssociations
IdentityAssociation mIdentityAssociations[OPENTHREAD_CONFIG_DHCP6_CLIENT_NUM_PREFIXES] private
mIdentityAssociationCurrent
IdentityAssociation* mIdentityAssociationCurrent private
mAloc
Ip6::NetifUnicastAddress mAloc private
Referenced by Dhcp6Server::PrefixAgent::Clear(), Dhcp6Server::PrefixAgent::GetAloc(), Dhcp6Server::PrefixAgent::GetContextId(), Dhcp6Server::PrefixAgent::IsValid(), and Dhcp6Server::PrefixAgent::Set().
mPrefix
otIp6Prefix mPrefix private
Referenced by Dhcp6Server::PrefixAgent::GetPrefix(), Dhcp6Server::PrefixAgent::IsPrefixMatch(), and Dhcp6Server::PrefixAgent::Set().
mSocket [2/2]
Ip6::UdpSocket mSocket private
mPrefixAgents
PrefixAgent mPrefixAgents[OPENTHREAD_CONFIG_DHCP6_SERVER_NUM_PREFIXES] private
mPrefixAgentsCount
uint8_t mPrefixAgentsCount private
mPrefixAgentsMask
uint8_t mPrefixAgentsMask private
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale