OpenThread: Command Line Interface
Command Line Interface
API » Add-Ons
This module includes functions that control the Thread stack's execution.
Typedefs
typedef int(* otCliConsoleOutputCallback) (const char *aBuf, uint16_t aBufLength, void *aContext)
Functions
void otCliAppendResult (otError aError)
void otCliConsoleInit (otInstance *aInstance, otCliConsoleOutputCallback aCallback, void *aContext)
void otCliConsoleInputLine (char *aBuf, uint16_t aBufLength)
void otCliOutput (const char *aString, uint16_t aLength)
void otCliOutputBytes (const uint8_t *aBytes, uint8_t aLength)
void otCliOutputFormat (const char *aFmt,...)
void otCliPlatLogv (otLogLevel aLogLevel, otLogRegion aLogRegion, const char *aFormat, va_list aArgs)
void otCliSetUserCommands (const otCliCommand *aUserCommands, uint8_t aLength)
void otCliUartInit (otInstance *aInstance)
Detailed Description
This module includes functions that control the Thread stack's execution.
Typedef Documentation
otCliConsoleOutputCallback
typedef int(* otCliConsoleOutputCallback) (const char *aBuf, uint16_t aBufLength, void *aContext)
This function pointer is called to notify about Console output.
Parameters
[in] aBuf A pointer to a buffer with an output.
[in] aBufLength A length of the output data stored in the buffer.
[out] aContext A user context pointer.
Returns
Number of bytes processed by the callback.
Function Documentation
otCliConsoleInit()
void otCliConsoleInit (otInstance * aInstance, otCliConsoleOutputCallback aCallback, void * aContext)
Initialize the CLI CONSOLE module.
Parameters
[in] aInstance The OpenThread instance structure.
[in] aCallback A callback method called to process console output.
[in] aContext A user context pointer.
References Server::sServer.
otCliConsoleInputLine()
void otCliConsoleInputLine (char * aBuf, uint16_t aBufLength)
This method is called to feed in a console input line.
Parameters
[in] aBuf A pointer to a buffer with an input.
[in] aBufLength A length of the input data stored in the buffer.
References Server::sServer.
otCliUartInit()
void otCliUartInit (otInstance * aInstance)
Initialize the CLI UART module.
Parameters
[in] aInstance The OpenThread instance structure.
References Server::sServer.
Referenced by main().
otCliSetUserCommands()
void otCliSetUserCommands (const otCliCommand * aUserCommands, uint8_t aLength)
Set a user command table.
Parameters
[in] aUserCommands A pointer to an array with user commands.
[in] aLength aUserCommands length.
References Server::GetInterpreter(), and Server::sServer.
otCliOutputBytes()
void otCliOutputBytes (const uint8_t * aBytes, uint8_t aLength)
Write a number of bytes to the CLI console as a hex string.
Parameters
[in] aBytes A pointer to data which should be printed.
[in] aLength aBytes length.
References Server::GetInterpreter(), and Server::sServer.
otCliOutputFormat()
void otCliOutputFormat (const char * aFmt, ...)
Write formatted string to the CLI console
Parameters
[in] aFmt A pointer to the format string.
[in] ... A matching list of arguments.
References Server::OutputFormatV(), and Server::sServer.
otCliOutput()
void otCliOutput (const char * aString, uint16_t aLength)
Write string to the CLI console
Parameters
[in] aString A pointer to the string, which may not be null-terminated.
[in] aLength Number of bytes.
References Server::Output(), and Server::sServer.
otCliAppendResult()
void otCliAppendResult (otError aError)
Write error code to the CLI console
Parameters
[in] aError Error code value.
References Server::GetInterpreter(), and Server::sServer.
otCliPlatLogv()
void otCliPlatLogv (otLogLevel aLogLevel, otLogRegion aLogRegion, const char * aFormat, va_list aArgs)
Callback to write the OpenThread Log to the CLI console
Parameters
[in] aLogLevel The log level.
[in] aLogRegion The log region.
[in] aFormat A pointer to the format string.
[in] aArgs va_list matching aFormat.
References OT_NOOP, OT_TOOL_WEAK, OT_UNUSED_VARIABLE, otNcpHandleDidReceiveNewLegacyUlaPrefix(), otNcpHandleLegacyNodeDidJoin(), otNcpRegisterLegacyHandlers(), Server::OutputFormat(), Server::OutputFormatV(), Server::sServer, and VerifyOrExit.
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale