OpenThread: Core-coap
Core-coap
This module includes definitions for CoAP.
Data Structures
class Coap
class CoapBase
class Message
class MessageQueue
struct CoapBase::Metadata
class OptionIterator
class Resource
struct ResponsesQueue::ResponseMetadata
class ResponsesQueue
class TxParameters
Typedefs
typedef otError(* Interceptor) (const Message &aMessage, const Ip6::MessageInfo &aMessageInfo, void *aContext)
typedef otCoapRequestHandler RequestHandler
typedef otCoapResponseHandler ResponseHandler
typedef otError(* Sender) (CoapBase &aCoapBase, ot::Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
Enumerations
enum {
kDefaultAckTimeout = 2000, kDefaultAckRandomFactorNumerator = 3, kDefaultAckRandomFactorDenominator = 2, kDefaultMaxRetransmit = 4,
kDefaultMaxLatency = 100000
}
enum { kMaxReceivedUriPath = 32 }
enum { kMaxCachedResponses = OPENTHREAD_CONFIG_COAP_SERVER_MAX_CACHED_RESPONSES }
Functions
otError AbortTransaction (ResponseHandler aHandler, void *aContext)
otError AddResource (Resource &aResource)
otError AppendTo (Message &aMessage) const
otError AppendTo (Message &aMessage) const
uint32_t CalculateExchangeLifetime (void) const
uint32_t CalculateInitialRetransmissionTimeout (void) const
uint32_t CalculateMaxTransmitWait (void) const
uint32_t CalculateSpan (uint8_t aMaxRetx) const
void ClearRequests (const Ip6::Address &aAddress)
void ClearRequests (const Ip6::Address *aAddress)
void ClearRequestsAndResponses (void)
Coap (Instance &aInstance)
CoapBase (Instance &aInstance, Sender aSender)
Message * CopyAndEnqueueMessage (const Message &aMessage, uint16_t aCopyLength, const Metadata &aMetadata)
void DequeueAllResponses (void)
void DequeueMessage (Message &aMessage)
void DequeueResponse (Message &aMessage)
void EnqueueResponse (Message &aMessage, const Ip6::MessageInfo &aMessageInfo, const TxParameters &aTxParameters)
void FinalizeCoapTransaction (Message &aRequest, const Metadata &aMetadata, Message *aResponse, const Ip6::MessageInfo *aMessageInfo, otError aResult)
const Message * FindMatchedResponse (const Message &aRequest, const Ip6::MessageInfo &aMessageInfo) const
Message * FindRelatedRequest (const Message &aResponse, const Ip6::MessageInfo &aMessageInfo, Metadata &aMetadata)
static const TxParameters & From (const otCoapTxParameters *aTxParameters)
const MessageQueue & GetCachedResponses (void) const
static const TxParameters & GetDefault (void)
otError GetMatchedResponseCopy (const Message &aRequest, const Ip6::MessageInfo &aMessageInfo, Message **aResponse)
const MessageQueue & GetRequestMessages (void) const
const MessageQueue & GetResponses (void) const
const char * GetUriPath (void) const
void HandleRequest (Message &aMessage, const Ip6::MessageInfo &aMessageInfo) const
static void HandleRetransmissionTimer (Timer &aTimer)
void HandleRetransmissionTimer (void)
static void HandleTimer (Timer &aTimer)
void HandleTimer (void)
static void HandleUdpReceive (void *aContext, otMessage *aMessage, const otMessageInfo *aMessageInfo)
bool IsValid (void) const
Message * NewMessage (const otMessageSettings *aSettings=NULL)
void ProcessReceivedRequest (Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
void ProcessReceivedResponse (Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
void ReadFrom (const Message &aMessage)
void ReadFrom (const Message &aMessage)
void Receive (ot::Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
void RemoveResource (Resource &aResource)
Resource (const char *aUriPath, RequestHandler aHandler, void *aContext)
ResponsesQueue (Instance &aInstance)
otError Send (ot::Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
static otError Send (CoapBase &aCoapBase, ot::Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
otError Send (ot::Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
otError SendAck (const Message &aRequest, const Ip6::MessageInfo &aMessageInfo)
otError SendCopy (const Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
otError SendEmptyAck (const Message &aRequest, const Ip6::MessageInfo &aMessageInfo)
otError SendEmptyMessage (Message::Type aType, const Message &aRequest, const Ip6::MessageInfo &aMessageInfo)
otError SendHeaderResponse (Message::Code aCode, const Message &aRequest, const Ip6::MessageInfo &aMessageInfo)
otError SendMessage (Message &aMessage, const Ip6::MessageInfo &aMessageInfo, const TxParameters &aTxParameters, ResponseHandler aHandler=NULL, void *aContext=NULL)
otError SendMessage (Message &aMessage, const Ip6::MessageInfo &aMessageInfo, ResponseHandler aHandler=NULL, void *aContext=NULL)
otError SendNotFound (const Message &aRequest, const Ip6::MessageInfo &aMessageInfo)
otError SendReset (Message &aRequest, const Ip6::MessageInfo &aMessageInfo)
void SetDefaultHandler (RequestHandler aHandler, void *aContext)
void SetInterceptor (Interceptor aInterceptor, void *aContext)
otError Start (uint16_t aPort)
otError Stop (void)
int UpdateIn (Message &aMessage) const
void UpdateQueue (void)
Variables
static const otCoapTxParameters kDefaultTxParameters
bool mAcknowledged: 1
bool mConfirmable: 1
void * mContext
RequestHandler mDefaultHandler
void * mDefaultHandlerContext
TimeMilli mDequeueTime
Ip6::Address mDestinationAddress
uint16_t mDestinationPort
Interceptor mInterceptor
uint16_t mMessageId
Ip6::MessageInfo mMessageInfo
TimeMilli mNextTimerShot
MessageQueue mPendingRequests
MessageQueue mQueue
LinkedList< Resource > mResources
void * mResponseContext
ResponseHandler mResponseHandler
ResponsesQueue mResponsesQueue
uint8_t mRetransmissionsRemaining
uint32_t mRetransmissionTimeout
TimerMilliContext mRetransmissionTimer
const Sender mSender
Ip6::UdpSocket mSocket
Ip6::Address mSourceAddress
TimerMilliContext mTimer
Friends
class CoapBase
class CoapBase
class ResponsesQueue
class ResponsesQueue
Detailed Description
This module includes definitions for CoAP.
Typedef Documentation
ResponseHandler
typedef otCoapResponseHandler ResponseHandler
This type represents a function pointer which is called when a CoAP response is received or on the request timeout.
Please see otCoapResponseHandler for details.
RequestHandler
typedef otCoapRequestHandler RequestHandler
This type represents a function pointer which is called when a CoAP request associated with a given URI path is received.
Please see otCoapRequestHandler for details.
Interceptor
typedef otError(* Interceptor) (const Message &aMessage, const Ip6::MessageInfo &aMessageInfo, void *aContext)
This function pointer is called before CoAP server processing a CoAP message.
Parameters
[in] aMessage A reference to the message. @
[in] aMessageInfo A reference to the message info associated with aMessage.
[in] aContext A pointer to arbitrary context information.
Return values
OT_ERROR_NONE Server should continue processing this message, other return values indicates the server should stop processing this message.
OT_ERROR_NOT_TMF The message is not a TMF message.
Sender
typedef otError(* Sender) (CoapBase &aCoapBase, ot::Message &aMessage, const Ip6::MessageInfo &aMessageInfo) protected
This function pointer is called to send a CoAP message.
Parameters
[in] aCoapBase A reference to the CoAP agent.
[in] aMessage A reference to the message to send.
[in] aMessageInfo A reference to the message info associated with aMessage.
Return values
OT_ERROR_NONE Successfully sent CoAP message.
OT_ERROR_NO_BUFS Failed to allocate retransmission data.
Enumeration Type Documentation
anonymous enum
anonymous enum private
Enumerator
kDefaultAckTimeout
kDefaultAckRandomFactorNumerator
kDefaultAckRandomFactorDenominator
kDefaultMaxRetransmit
kDefaultMaxLatency
anonymous enum
anonymous enum
Enumerator
kMaxReceivedUriPath
Maximum supported URI path on received messages.
anonymous enum
anonymous enum private
Enumerator
kMaxCachedResponses
Function Documentation
From()
static const TxParameters& From (const otCoapTxParameters * aTxParameters) inline static
This static method coverts a pointer to otCoapTxParameters to Coap::TxParamters
If the pointer is NULL, the default parameters are used instead.
Parameters
[in] aTxParameters A pointer to tx parameter.
Returns
A reference to corresponding TxParamters if aTxParameters is not NULL, otherwise the default tx parameters.
References TxParameters::GetDefault(), and TxParameters::IsValid().
IsValid()
bool IsValid (void) const
This method validates whether the CoAP transmission parameters are valid.
Returns
Whether the parameters are valid.
References ot::Coap::Multiply(), OT_COAP_MAX_RETRANSMIT, and OT_COAP_MIN_ACK_TIMEOUT.
Referenced by TxParameters::From().
GetDefault()
static const TxParameters& GetDefault (void) inline static
This static method returns default CoAP tx parameters.
Returns
The default tx parameters.
References TxParameters::kDefaultTxParameters.
Referenced by TxParameters::From(), and CoapBase::SendMessage().
CalculateInitialRetransmissionTimeout()
uint32_t CalculateInitialRetransmissionTimeout (void) const private
References ot::Random::NonCrypto::GetUint32InRange().
Referenced by CoapBase::SendMessage().
CalculateExchangeLifetime()
uint32_t CalculateExchangeLifetime (void) const private
Referenced by ResponsesQueue::EnqueueResponse().
CalculateMaxTransmitWait()
uint32_t CalculateMaxTransmitWait (void) const private
Referenced by CoapBase::SendMessage().
CalculateSpan()
uint32_t CalculateSpan (uint8_t aMaxRetx) const private
References TxParameters::kDefaultTxParameters.
Resource()
Resource (const char * aUriPath, RequestHandler aHandler, void * aContext) inline
This constructor initializes the resource.
Parameters
[in] aUriPath A pointer to a NULL-terminated string for the URI path.
[in] aHandler A function pointer that is called when receiving a CoAP message for aUriPath.
[in] aContext A pointer to arbitrary context information.
GetUriPath()
const char* GetUriPath (void) const inline
This method returns a pointer to the URI path.
Returns
A pointer to the URI path.
HandleRequest()
void HandleRequest (Message & aMessage, const Ip6::MessageInfo & aMessageInfo) const inline private
ResponsesQueue()
ResponsesQueue (Instance & aInstance) explicit
Default class constructor.
Parameters
[in] aInstance A reference to the OpenThread instance.
EnqueueResponse()
void EnqueueResponse (Message & aMessage, const Ip6::MessageInfo & aMessageInfo, const TxParameters & aTxParameters)
This method adds a given response to the cache.
If matching response (the same Message ID, source endpoint address and port) exists in the cache given response is not added.
The CoAP response is copied before it is added to the cache.
Parameters
[in] aMessage The CoAP response to add to the cache.
[in] aMessageInfo The message info corresponding to aMessage.
[in] aTxParameters Transmission parameters.
References ResponsesQueue::ResponseMetadata::AppendTo(), TxParameters::CalculateExchangeLifetime(), Message::Clone(), MessageQueue::Enqueue(), ResponsesQueue::FindMatchedResponse(), TimerMilli::FireAtIfEarlier(), Message::Free(), TimerMilli::GetNow(), ResponsesQueue::ResponseMetadata::mDequeueTime, ResponsesQueue::ResponseMetadata::mMessageInfo, ResponsesQueue::mQueue, ResponsesQueue::mTimer, OT_ERROR_NONE, OT_NOOP, ResponsesQueue::UpdateQueue(), and VerifyOrExit.
Referenced by CoapBase::SendMessage().
DequeueAllResponses()
void DequeueAllResponses (void)
This method removes all responses from the cache.
References ResponsesQueue::DequeueResponse(), MessageQueue::GetHead(), and ResponsesQueue::mQueue.
Referenced by CoapBase::ClearRequestsAndResponses().
GetMatchedResponseCopy()
otError GetMatchedResponseCopy (const Message & aRequest, const Ip6::MessageInfo & aMessageInfo, Message ** aResponse)
This method gets a copy of CoAP response from the cache that matches a given Message ID and source endpoint.
Parameters
[in] aRequest The CoAP message containing Message ID.
[in] aMessageInfo The message info containing source endpoint address and port.
[out] aResponse A pointer to return a copy of a cached CoAP response matching given arguments.
Return values
OT_ERROR_NONE Matching response found and successfully created a copy.
OT_ERROR_NO_BUFS Matching response found but there is not sufficient buffer to create a copy.
OT_ERROR_NOT_FOUND Matching response not found.
References Message::Clone(), ResponsesQueue::FindMatchedResponse(), Message::GetLength(), OT_ERROR_NO_BUFS, OT_ERROR_NONE, OT_ERROR_NOT_FOUND, and VerifyOrExit.
Referenced by CoapBase::ProcessReceivedRequest().
GetResponses()
const MessageQueue& GetResponses (void) const inline
This method gets a reference to the cached CoAP responses queue.
Returns
A reference to the cached CoAP responses queue.
AppendTo() [1/2]
otError AppendTo (Message & aMessage) const inline
References Message::Append().
Referenced by ResponsesQueue::EnqueueResponse().
ReadFrom() [1/2]
void ReadFrom (const Message & aMessage)
References Message::GetLength(), OT_ASSERT, and Message::Read().
Referenced by ResponsesQueue::FindMatchedResponse(), ResponsesQueue::HandleTimer(), and ResponsesQueue::UpdateQueue().
FindMatchedResponse()
const Message * FindMatchedResponse (const Message & aRequest, const Ip6::MessageInfo & aMessageInfo) const private
References MessageQueue::GetHead(), Message::GetMessageId(), Message::GetNextCoapMessage(), MessageInfo::GetPeerAddr(), MessageInfo::GetPeerPort(), ResponsesQueue::ResponseMetadata::mMessageInfo, ResponsesQueue::mQueue, and ResponsesQueue::ResponseMetadata::ReadFrom().
Referenced by ResponsesQueue::EnqueueResponse(), and ResponsesQueue::GetMatchedResponseCopy().
DequeueResponse()
void DequeueResponse (Message & aMessage) private
References MessageQueue::Dequeue(), Message::Free(), and ResponsesQueue::mQueue.
Referenced by ResponsesQueue::DequeueAllResponses(), ResponsesQueue::HandleTimer(), and ResponsesQueue::UpdateQueue().
UpdateQueue()
void UpdateQueue (void) private
References ResponsesQueue::DequeueResponse(), MessageQueue::GetHead(), Message::GetNextCoapMessage(), ResponsesQueue::kMaxCachedResponses, ResponsesQueue::ResponseMetadata::mDequeueTime, ResponsesQueue::mQueue, and ResponsesQueue::ResponseMetadata::ReadFrom().
Referenced by ResponsesQueue::EnqueueResponse().
HandleTimer() [1/2]
void HandleTimer (Timer & aTimer) static private
References ResponsesQueue::HandleTimer().
HandleTimer() [2/2]
void HandleTimer (void) private
References ResponsesQueue::DequeueResponse(), TimerMilli::FireAt(), Time::GetDistantFuture(), MessageQueue::GetHead(), Message::GetNextCoapMessage(), TimerMilli::GetNow(), ResponsesQueue::ResponseMetadata::mDequeueTime, ResponsesQueue::mQueue, ResponsesQueue::mTimer, and ResponsesQueue::ResponseMetadata::ReadFrom().
Referenced by ResponsesQueue::HandleTimer().
ClearRequestsAndResponses()
void ClearRequestsAndResponses (void)
This method clears requests and responses used by this CoAP agent.
References CoapBase::ClearRequests(), ResponsesQueue::DequeueAllResponses(), and CoapBase::mResponsesQueue.
Referenced by Coap::Stop().
ClearRequests() [1/2]
void ClearRequests (const Ip6::Address & aAddress)
This method clears requests with specified source address used by this CoAP agent.
Parameters
[in] aAddress A reference to the specified address.
Referenced by CoapBase::ClearRequestsAndResponses().
AddResource()
otError AddResource (Resource & aResource)
This method adds a resource to the CoAP server.
Parameters
[in] aResource A reference to the resource.
Return values
OT_ERROR_NONE Successfully added aResource.
OT_ERROR_ALREADY The aResource was already added.
References CoapBase::mResources.
RemoveResource()
void RemoveResource (Resource & aResource)
This method removes a resource from the CoAP server.
Parameters
[in] aResource A reference to the resource.
References CoapBase::mResources, and LinkedListEntry< Type >::SetNext().
SetDefaultHandler()
void SetDefaultHandler (RequestHandler aHandler, void * aContext)
References CoapBase::mDefaultHandler, and CoapBase::mDefaultHandlerContext.
NewMessage()
Message * NewMessage (const otMessageSettings * aSettings = NULL)
This method creates a new message with a CoAP header.
Note
If aSettings is 'NULL', the link layer security is enabled and the message priority is set to OT_MESSAGE_PRIORITY_NORMAL by default.
Parameters
[in] aSettings A pointer to the message settings or NULL to set default settings.
Returns
A pointer to the message or NULL if failed to allocate message.
References OT_NOOP, Message::SetOffset(), and VerifyOrExit.
Referenced by ot::MeshCoP::NewMeshCoPMessage(), CoapBase::SendEmptyMessage(), and CoapBase::SendHeaderResponse().
SendMessage() [1/2]
otError SendMessage (Message & aMessage, const Ip6::MessageInfo & aMessageInfo, const TxParameters & aTxParameters, ResponseHandler aHandler = NULL, void * aContext = NULL)
This method sends a CoAP message with custom transmission parameters.
If a response for a request is expected, respective function and context information should be provided. If no response is expected, these arguments should be NULL pointers. If Message Id was not set in the header (equal to 0), this function will assign unique Message Id to the message.
Parameters
[in] aMessage A reference to the message to send.
[in] aMessageInfo A reference to the message info associated with aMessage.
[in] aTxParameters A reference to transmission parameters for this message.
[in] aHandler A function pointer that shall be called on response reception or time-out.
[in] aContext A pointer to arbitrary context information.
Return values
OT_ERROR_NONE Successfully sent CoAP message.
OT_ERROR_NO_BUFS Insufficient buffers available to send the CoAP message.
References TxParameters::CalculateInitialRetransmissionTimeout(), TxParameters::CalculateMaxTransmitWait(), CoapBase::CopyAndEnqueueMessage(), CoapBase::DequeueMessage(), ResponsesQueue::EnqueueResponse(), CoapBase::FinalizeCoapTransaction(), CoapBase::FindRelatedRequest(), Message::Finish(), Message::GetCode(), OptionIterator::GetFirstOptionMatching(), Message::GetLength(), TimerMilli::GetNow(), Message::GetOptionStart(), OptionIterator::GetOptionValue(), MessageInfo::GetPeerAddr(), MessageInfo::GetPeerPort(), MessageInfo::GetSockAddr(), Message::GetType(), OptionIterator::Init(), Message::IsConfirmable(), Message::IsNonConfirmable(), CoapBase::Metadata::mAcknowledged, CoapBase::Metadata::mConfirmable, CoapBase::Metadata::mDestinationAddress, CoapBase::Metadata::mDestinationPort, otCoapTxParameters::mMaxRetransmit, CoapBase::mMessageId, CoapBase::Metadata::mNextTimerShot, CoapBase::Metadata::mResponseContext, CoapBase::Metadata::mResponseHandler, CoapBase::mResponsesQueue, CoapBase::Metadata::mRetransmissionsRemaining, CoapBase::Metadata::mRetransmissionTimeout, CoapBase::Metadata::mSourceAddress, OT_ASSERT, OT_COAP_CODE_EMPTY, OT_COAP_CODE_GET, OT_COAP_OPTION_OBSERVE, OT_COAP_TYPE_ACKNOWLEDGMENT, OT_COAP_TYPE_RESET, OT_ERROR_NO_BUFS, OT_ERROR_NONE, CoapBase::Send(), Message::SetMessageId(), SuccessOrExit, and VerifyOrExit.
Referenced by CoapBase::SendHeaderResponse(), and CoapBase::SendMessage().
SendMessage() [2/2]
otError SendMessage (Message & aMessage, const Ip6::MessageInfo & aMessageInfo, ResponseHandler aHandler = NULL, void * aContext = NULL)
This method sends a CoAP message with default transmission parameters.
If a response for a request is expected, respective function and context information should be provided. If no response is expected, these arguments should be NULL pointers. If Message Id was not set in the header (equal to 0), this function will assign unique Message Id to the message.
Parameters
[in] aMessage A reference to the message to send.
[in] aMessageInfo A reference to the message info associated with aMessage.
[in] aHandler A function pointer that shall be called on response reception or time-out.
[in] aContext A pointer to arbitrary context information.
Return values
OT_ERROR_NONE Successfully sent CoAP message.
OT_ERROR_NO_BUFS Insufficient buffers available to send the CoAP response.
References TxParameters::GetDefault(), and CoapBase::SendMessage().
SendReset()
otError SendReset (Message & aRequest, const Ip6::MessageInfo & aMessageInfo)
This method sends a CoAP reset message.
Parameters
[in] aRequest A reference to the CoAP Message that was used in CoAP request.
[in] aMessageInfo The message info corresponding to the CoAP request.
Return values
OT_ERROR_NONE Successfully enqueued the CoAP response message.
OT_ERROR_NO_BUFS Insufficient buffers available to send the CoAP response.
OT_ERROR_INVALID_ARGS The aRequest is not of confirmable type.
References OT_COAP_TYPE_RESET, and CoapBase::SendEmptyMessage().
Referenced by CoapBase::ProcessReceivedResponse(), and CoapBase::Receive().
SendHeaderResponse()
otError SendHeaderResponse (Message::Code aCode, const Message & aRequest, const Ip6::MessageInfo & aMessageInfo)
This method sends header-only CoAP response message.
Parameters
[in] aCode The CoAP code of this response.
[in] aRequest A reference to the CoAP Message that was used in CoAP request.
[in] aMessageInfo The message info corresponding to the CoAP request.
Return values
OT_ERROR_NONE Successfully enqueued the CoAP response message.
OT_ERROR_NO_BUFS Insufficient buffers available to send the CoAP response.
OT_ERROR_INVALID_ARGS The aRequest header is not of confirmable type.
References ExitNow, Message::Free(), Message::GetMessageId(), Message::GetToken(), Message::GetTokenLength(), Message::GetType(), Message::Init(), Message::IsRequest(), CoapBase::NewMessage(), OT_COAP_TYPE_ACKNOWLEDGMENT, OT_COAP_TYPE_CONFIRMABLE, OT_COAP_TYPE_NON_CONFIRMABLE, OT_ERROR_INVALID_ARGS, OT_ERROR_NO_BUFS, OT_ERROR_NONE, OT_UNREACHABLE_CODE, CoapBase::SendMessage(), Message::SetMessageId(), Message::SetToken(), SuccessOrExit, and VerifyOrExit.
Referenced by CoapBase::SendEmptyAck(), and CoapBase::SendNotFound().
SendAck()
otError SendAck (const Message & aRequest, const Ip6::MessageInfo & aMessageInfo)
This method sends a CoAP ACK empty message which is used in Separate Response for confirmable requests.
Parameters
[in] aRequest A reference to the CoAP Message that was used in CoAP request.
[in] aMessageInfo The message info corresponding to the CoAP request.
Return values
OT_ERROR_NONE Successfully enqueued the CoAP response message.
OT_ERROR_NO_BUFS Insufficient buffers available to send the CoAP response.
OT_ERROR_INVALID_ARGS The aRequest header is not of confirmable type.
References OT_COAP_TYPE_ACKNOWLEDGMENT, and CoapBase::SendEmptyMessage().
Referenced by CoapBase::ProcessReceivedResponse().
SendEmptyAck()
otError SendEmptyAck (const Message & aRequest, const Ip6::MessageInfo & aMessageInfo)
This method sends a CoAP ACK message on which a dummy CoAP response is piggybacked.
Parameters
[in] aRequest A reference to the CoAP Message that was used in CoAP request.
[in] aMessageInfo The message info corresponding to the CoAP request.
Return values
OT_ERROR_NONE Successfully enqueued the CoAP response message.
OT_ERROR_NO_BUFS Insufficient buffers available to send the CoAP response.
OT_ERROR_INVALID_ARGS The aRequest header is not of confirmable type.
References Message::IsConfirmable(), OT_COAP_CODE_CHANGED, OT_ERROR_INVALID_ARGS, and CoapBase::SendHeaderResponse().
SendNotFound()
otError SendNotFound (const Message & aRequest, const Ip6::MessageInfo & aMessageInfo)
This method sends a header-only CoAP message to indicate no resource matched for the request.
Parameters
[in] aRequest A reference to the CoAP Message that was used in CoAP request.
[in] aMessageInfo The message info corresponding to the CoAP request.
Return values
OT_ERROR_NONE Successfully enqueued the CoAP response message.
OT_ERROR_NO_BUFS Insufficient buffers available to send the CoAP response.
References OT_COAP_CODE_NOT_FOUND, and CoapBase::SendHeaderResponse().
Referenced by CoapBase::ProcessReceivedRequest().
AbortTransaction()
otError AbortTransaction (ResponseHandler aHandler, void * aContext)
This method aborts CoAP transactions associated with given handler and context.
The associated response handler will be called with OT_ERROR_ABORT.
Parameters
[in] aHandler A function pointer that should be called when the transaction ends.
[in] aContext A pointer to arbitrary context information.
Return values
OT_ERROR_NONE Successfully aborted CoAP transactions.
OT_ERROR_NOT_FOUND CoAP transaction associated with given handler was not found.
References CoapBase::FinalizeCoapTransaction(), MessageQueue::GetHead(), Message::GetNextCoapMessage(), CoapBase::mPendingRequests, CoapBase::Metadata::mResponseContext, CoapBase::Metadata::mResponseHandler, OT_ERROR_ABORT, OT_ERROR_NONE, OT_ERROR_NOT_FOUND, and CoapBase::Metadata::ReadFrom().
SetInterceptor()
void SetInterceptor (Interceptor aInterceptor, void * aContext)
This method sets interceptor to be called before processing a CoAP packet.
Parameters
[in] aInterceptor A pointer to the interceptor.
[in] aContext A pointer to arbitrary context information.
References CoapBase::mContext, and CoapBase::mInterceptor.
GetRequestMessages()
const MessageQueue& GetRequestMessages (void) const inline
This method returns a reference to the request message list.
Returns
A reference to the request message list.
GetCachedResponses()
const MessageQueue& GetCachedResponses (void) const inline
This method returns a reference to the cached response list.
Returns
A reference to the cached response list.
CoapBase()
CoapBase (Instance & aInstance, Sender aSender) protected
This constructor initializes the object.
Parameters
[in] aInstance A reference to the OpenThread instance.
[in] aSender A function pointer to send CoAP message, which SHOULD be a static member method of a descendant of this class.
Receive()
void Receive (ot::Message & aMessage, const Ip6::MessageInfo & aMessageInfo) protected
This method receives a CoAP message.
Parameters
[in] aMessage A reference to the received message.
[in] aMessageInfo A reference to the message info associated with aMessage.
References MessageInfo::GetSockAddr(), Message::IsConfirmable(), Address::IsMulticast(), Message::IsRequest(), OT_ERROR_NONE, otLogDebgCoap, Message::ParseHeader(), CoapBase::ProcessReceivedRequest(), CoapBase::ProcessReceivedResponse(), and CoapBase::SendReset().
Referenced by Coap::HandleUdpReceive().
AppendTo() [2/2]
otError AppendTo (Message & aMessage) const inline
References Message::Append().
Referenced by CoapBase::CopyAndEnqueueMessage().
ReadFrom() [2/2]
void ReadFrom (const Message & aMessage)
References Message::GetLength(), OT_ASSERT, and Message::Read().
Referenced by CoapBase::AbortTransaction(), CoapBase::ClearRequests(), CoapBase::FindRelatedRequest(), and CoapBase::HandleRetransmissionTimer().
UpdateIn()
int UpdateIn (Message & aMessage) const
References Message::GetLength(), and Message::Write().
Referenced by CoapBase::HandleRetransmissionTimer(), and CoapBase::ProcessReceivedResponse().
HandleRetransmissionTimer() [1/2]
void HandleRetransmissionTimer (Timer & aTimer) static private
References CoapBase::HandleRetransmissionTimer().
HandleRetransmissionTimer() [2/2]
void HandleRetransmissionTimer (void) private
References CoapBase::FinalizeCoapTransaction(), TimerMilli::FireAt(), Time::GetDistantFuture(), MessageQueue::GetHead(), Message::GetNextCoapMessage(), TimerMilli::GetNow(), CoapBase::Metadata::mAcknowledged, CoapBase::Metadata::mConfirmable, CoapBase::Metadata::mDestinationAddress, CoapBase::Metadata::mDestinationPort, CoapBase::Metadata::mNextTimerShot, CoapBase::mPendingRequests, CoapBase::Metadata::mRetransmissionsRemaining, CoapBase::Metadata::mRetransmissionTimeout, CoapBase::mRetransmissionTimer, CoapBase::Metadata::mSourceAddress, OT_ERROR_RESPONSE_TIMEOUT, CoapBase::Metadata::ReadFrom(), CoapBase::SendCopy(), MessageInfo::SetPeerAddr(), MessageInfo::SetPeerPort(), MessageInfo::SetSockAddr(), and CoapBase::Metadata::UpdateIn().
Referenced by CoapBase::HandleRetransmissionTimer().
ClearRequests() [2/2]
void ClearRequests (const Ip6::Address * aAddress) private
References CoapBase::FinalizeCoapTransaction(), MessageQueue::GetHead(), Message::GetNextCoapMessage(), CoapBase::mPendingRequests, CoapBase::Metadata::mSourceAddress, OT_ERROR_ABORT, and CoapBase::Metadata::ReadFrom().
CopyAndEnqueueMessage()
Message * CopyAndEnqueueMessage (const Message & aMessage, uint16_t aCopyLength, const Metadata & aMetadata) private
References CoapBase::Metadata::AppendTo(), Message::Clone(), MessageQueue::Enqueue(), TimerMilli::FireAtIfEarlier(), Message::Free(), CoapBase::Metadata::mNextTimerShot, CoapBase::mPendingRequests, CoapBase::mRetransmissionTimer, OT_ERROR_NO_BUFS, OT_ERROR_NONE, SuccessOrExit, and VerifyOrExit.
Referenced by CoapBase::SendMessage().
DequeueMessage()
void DequeueMessage (Message & aMessage) private
References MessageQueue::Dequeue(), Message::Free(), MessageQueue::GetHead(), Timer::IsRunning(), CoapBase::mPendingRequests, CoapBase::mRetransmissionTimer, and TimerMilli::Stop().
Referenced by CoapBase::FinalizeCoapTransaction(), CoapBase::ProcessReceivedResponse(), and CoapBase::SendMessage().
FindRelatedRequest()
Message * FindRelatedRequest (const Message & aResponse, const Ip6::MessageInfo & aMessageInfo, Metadata & aMetadata) private
References ExitNow, MessageQueue::GetHead(), Message::GetMessageId(), Message::GetNextCoapMessage(), MessageInfo::GetPeerAddr(), MessageInfo::GetPeerPort(), Message::GetType(), Address::IsIidAnycastLocator(), Address::IsMulticast(), Message::IsTokenEqual(), CoapBase::Metadata::mDestinationAddress, CoapBase::Metadata::mDestinationPort, CoapBase::mPendingRequests, OT_COAP_TYPE_ACKNOWLEDGMENT, OT_COAP_TYPE_CONFIRMABLE, OT_COAP_TYPE_NON_CONFIRMABLE, OT_COAP_TYPE_RESET, and CoapBase::Metadata::ReadFrom().
Referenced by CoapBase::ProcessReceivedResponse(), and CoapBase::SendMessage().
FinalizeCoapTransaction()
void FinalizeCoapTransaction (Message & aRequest, const Metadata & aMetadata, Message * aResponse, const Ip6::MessageInfo * aMessageInfo, otError aResult) private
References CoapBase::DequeueMessage(), CoapBase::Metadata::mResponseContext, and CoapBase::Metadata::mResponseHandler.
Referenced by CoapBase::AbortTransaction(), CoapBase::ClearRequests(), CoapBase::HandleRetransmissionTimer(), CoapBase::ProcessReceivedResponse(), and CoapBase::SendMessage().
ProcessReceivedRequest()
void ProcessReceivedRequest (Message & aMessage, const Ip6::MessageInfo & aMessageInfo) private
References ExitNow, Message::Finish(), Message::Free(), OptionIterator::GetFirstOption(), ResponsesQueue::GetMatchedResponseCopy(), OptionIterator::GetNextOption(), OptionIterator::GetOptionValue(), MessageInfo::GetSockAddr(), OptionIterator::Init(), Address::IsMulticast(), Resource::kMaxReceivedUriPath, CoapBase::mContext, CoapBase::mDefaultHandler, CoapBase::mDefaultHandlerContext, CoapBase::mInterceptor, CoapBase::mResources, CoapBase::mResponsesQueue, OT_COAP_OPTION_URI_PATH, OT_ERROR_NO_BUFS, OT_ERROR_NONE, OT_ERROR_NOT_FOUND, OT_NOOP, otLogInfoCoap, otThreadErrorToString(), CoapBase::Send(), CoapBase::SendNotFound(), SuccessOrExit, and VerifyOrExit.
Referenced by CoapBase::Receive().
ProcessReceivedResponse()
void ProcessReceivedResponse (Message & aMessage, const Ip6::MessageInfo & aMessageInfo) private
References CoapBase::DequeueMessage(), CoapBase::FinalizeCoapTransaction(), CoapBase::FindRelatedRequest(), OptionIterator::GetFirstOptionMatching(), Message::GetType(), OptionIterator::Init(), Message::IsConfirmable(), Message::IsEmpty(), Address::IsMulticast(), Message::IsNonConfirmable(), Message::IsRequest(), Message::IsResponse(), Message::IsTokenEqual(), CoapBase::Metadata::mAcknowledged, CoapBase::Metadata::mConfirmable, CoapBase::Metadata::mDestinationAddress, CoapBase::Metadata::mResponseContext, CoapBase::Metadata::mResponseHandler, OT_COAP_OPTION_OBSERVE, OT_COAP_TYPE_ACKNOWLEDGMENT, OT_COAP_TYPE_CONFIRMABLE, OT_COAP_TYPE_NON_CONFIRMABLE, OT_COAP_TYPE_RESET, OT_ERROR_ABORT, OT_ERROR_NONE, OT_NOOP, CoapBase::SendAck(), CoapBase::SendReset(), SuccessOrExit, CoapBase::Metadata::UpdateIn(), and VerifyOrExit.
Referenced by CoapBase::Receive().
SendCopy()
otError SendCopy (const Message & aMessage, const Ip6::MessageInfo & aMessageInfo) private
References Message::Clone(), Message::Free(), Message::GetLength(), OT_ERROR_NO_BUFS, OT_ERROR_NONE, CoapBase::Send(), SuccessOrExit, and VerifyOrExit.
Referenced by CoapBase::HandleRetransmissionTimer().
SendEmptyMessage()
otError SendEmptyMessage (Message::Type aType, const Message & aRequest, const Ip6::MessageInfo & aMessageInfo) private
References Message::Finish(), Message::Free(), Message::GetMessageId(), Message::Init(), Message::IsConfirmable(), CoapBase::NewMessage(), OT_COAP_CODE_EMPTY, OT_ERROR_INVALID_ARGS, OT_ERROR_NO_BUFS, OT_ERROR_NONE, CoapBase::Send(), Message::SetMessageId(), SuccessOrExit, and VerifyOrExit.
Referenced by CoapBase::SendAck(), and CoapBase::SendReset().
Send() [1/3]
otError Send (ot::Message & aMessage, const Ip6::MessageInfo & aMessageInfo) private
References CoapBase::mSender.
Referenced by CoapBase::ProcessReceivedRequest(), CoapBase::SendCopy(), CoapBase::SendEmptyMessage(), and CoapBase::SendMessage().
Coap()
Coap (Instance & aInstance) explicit
This constructor initializes the object.
Parameters
[in] aInstance A reference to the OpenThread instance.
Start()
otError Start (uint16_t aPort)
This method starts the CoAP service.
Parameters
[in] aPort The local UDP port to bind to.
Return values
OT_ERROR_NONE Successfully started the CoAP service.
OT_ERROR_ALREADY Already started.
References UdpSocket::Bind(), UdpSocket::Close(), Coap::HandleUdpReceive(), otSockAddr::mPort, Coap::mSocket, UdpSocket::Open(), OT_ERROR_NONE, SuccessOrExit, and VerifyOrExit.
Stop()
otError Stop (void)
This method stops the CoAP service.
Return values
OT_ERROR_NONE Successfully stopped the CoAP service.
OT_ERROR_FAILED Failed to stop CoAP agent.
References CoapBase::ClearRequestsAndResponses(), UdpSocket::Close(), Coap::mSocket, and SuccessOrExit.
Send() [2/3]
otError Send (CoapBase & aCoapBase, ot::Message & aMessage, const Ip6::MessageInfo & aMessageInfo) static private
HandleUdpReceive()
void HandleUdpReceive (void * aContext, otMessage * aMessage, const otMessageInfo * aMessageInfo) static private
References CoapBase::Receive().
Referenced by Coap::Start().
Send() [3/3]
otError Send (ot::Message & aMessage, const Ip6::MessageInfo & aMessageInfo) private
References UdpSocket::IsBound(), Coap::mSocket, OT_ERROR_INVALID_STATE, and UdpSocket::SendTo().
Variable Documentation
kDefaultTxParameters
const otCoapTxParameters kDefaultTxParameters static private
Initial value:
= {
    kDefaultAckTimeout,
    kDefaultAckRandomFactorNumerator,
    kDefaultAckRandomFactorDenominator,
    kDefaultMaxRetransmit,
}
Referenced by TxParameters::CalculateSpan(), and TxParameters::GetDefault().
mDequeueTime
TimeMilli mDequeueTime
Referenced by ResponsesQueue::EnqueueResponse(), ResponsesQueue::HandleTimer(), and ResponsesQueue::UpdateQueue().
mMessageInfo
Ip6::MessageInfo mMessageInfo
Referenced by ResponsesQueue::EnqueueResponse(), and ResponsesQueue::FindMatchedResponse().
mQueue
MessageQueue mQueue private
Referenced by ResponsesQueue::DequeueAllResponses(), ResponsesQueue::DequeueResponse(), ResponsesQueue::EnqueueResponse(), ResponsesQueue::FindMatchedResponse(), ResponsesQueue::HandleTimer(), and ResponsesQueue::UpdateQueue().
mTimer
TimerMilliContext mTimer private
Referenced by ResponsesQueue::EnqueueResponse(), and ResponsesQueue::HandleTimer().
mSourceAddress
Ip6::Address mSourceAddress
Referenced by CoapBase::ClearRequests(), CoapBase::HandleRetransmissionTimer(), and CoapBase::SendMessage().
mDestinationAddress
Ip6::Address mDestinationAddress
Referenced by CoapBase::FindRelatedRequest(), CoapBase::HandleRetransmissionTimer(), CoapBase::ProcessReceivedResponse(), and CoapBase::SendMessage().
mDestinationPort
uint16_t mDestinationPort
Referenced by CoapBase::FindRelatedRequest(), CoapBase::HandleRetransmissionTimer(), and CoapBase::SendMessage().
mResponseHandler
ResponseHandler mResponseHandler
Referenced by CoapBase::AbortTransaction(), CoapBase::FinalizeCoapTransaction(), CoapBase::ProcessReceivedResponse(), and CoapBase::SendMessage().
mResponseContext
void* mResponseContext
Referenced by CoapBase::AbortTransaction(), CoapBase::FinalizeCoapTransaction(), CoapBase::ProcessReceivedResponse(), and CoapBase::SendMessage().
mNextTimerShot
TimeMilli mNextTimerShot
Referenced by CoapBase::CopyAndEnqueueMessage(), CoapBase::HandleRetransmissionTimer(), and CoapBase::SendMessage().
mRetransmissionTimeout
uint32_t mRetransmissionTimeout
Referenced by CoapBase::HandleRetransmissionTimer(), and CoapBase::SendMessage().
mRetransmissionsRemaining
uint8_t mRetransmissionsRemaining
Referenced by CoapBase::HandleRetransmissionTimer(), and CoapBase::SendMessage().
mAcknowledged
bool mAcknowledged
Referenced by CoapBase::HandleRetransmissionTimer(), CoapBase::ProcessReceivedResponse(), and CoapBase::SendMessage().
mConfirmable
bool mConfirmable
Referenced by CoapBase::HandleRetransmissionTimer(), CoapBase::ProcessReceivedResponse(), and CoapBase::SendMessage().
mPendingRequests
MessageQueue mPendingRequests private
Referenced by CoapBase::AbortTransaction(), CoapBase::ClearRequests(), CoapBase::CopyAndEnqueueMessage(), CoapBase::DequeueMessage(), CoapBase::FindRelatedRequest(), and CoapBase::HandleRetransmissionTimer().
mMessageId
uint16_t mMessageId private
Referenced by CoapBase::SendMessage().
mRetransmissionTimer
TimerMilliContext mRetransmissionTimer private
Referenced by CoapBase::CopyAndEnqueueMessage(), CoapBase::DequeueMessage(), and CoapBase::HandleRetransmissionTimer().
mResources
LinkedList<Resource> mResources private
Referenced by CoapBase::AddResource(), CoapBase::ProcessReceivedRequest(), and CoapBase::RemoveResource().
mContext
void* mContext private
Referenced by CoapBase::ProcessReceivedRequest(), and CoapBase::SetInterceptor().
mInterceptor
Interceptor mInterceptor private
Referenced by CoapBase::ProcessReceivedRequest(), and CoapBase::SetInterceptor().
mResponsesQueue
ResponsesQueue mResponsesQueue private
Referenced by CoapBase::ClearRequestsAndResponses(), CoapBase::ProcessReceivedRequest(), and CoapBase::SendMessage().
mDefaultHandler
RequestHandler mDefaultHandler private
Referenced by CoapBase::ProcessReceivedRequest(), and CoapBase::SetDefaultHandler().
mDefaultHandlerContext
void* mDefaultHandlerContext private
Referenced by CoapBase::ProcessReceivedRequest(), and CoapBase::SetDefaultHandler().
mSender
const Sender mSender private
Referenced by CoapBase::Send().
mSocket
Ip6::UdpSocket mSocket private
Referenced by Coap::Send(), Coap::Start(), and Coap::Stop().
Friends
CoapBase [1/2]
friend class CoapBase friend
ResponsesQueue [1/2]
friend class ResponsesQueue friend
CoapBase [2/2]
friend class CoapBase friend
ResponsesQueue [2/2]
friend class ResponsesQueue friend
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale