OpenThread: Core
Core
MLE
This module includes definitions for MLE functionality required by the Thread Child, Router, and Leader roles.
Data Structures
struct Mle::Challenge
struct Mle::DelayedResponseMetadata
class DeviceMode
class Header
class LeaderData
class MeshLocalPrefix
class Mle
struct Mle::RequestedTlvs
class RouterIdSet
Typedefs
typedef void(* DiscoverHandler) (otActiveScanResult *aResult, void *aContext)
Enumerations
enum { kMleMaxResponseDelay = 1000u }
enum {
kMleMessagePriority = Message::kPriorityNet, kMleHopLimit = 255, kParentSearchCheckInterval = (OPENTHREAD_CONFIG_PARENT_SEARCH_CHECK_INTERVAL * 1000u), kParentSearchBackoffInterval = (OPENTHREAD_CONFIG_PARENT_SEARCH_BACKOFF_INTERVAL * 1000u),
kParentSearchJitterInterval = (15 * 1000u), kParentSearchRssThreadhold = OPENTHREAD_CONFIG_PARENT_SEARCH_RSS_THRESHOLD, kAttachBackoffMinInterval = OPENTHREAD_CONFIG_MLE_ATTACH_BACKOFF_MINIMUM_INTERVAL, kAttachBackoffMaxInterval = OPENTHREAD_CONFIG_MLE_ATTACH_BACKOFF_MAXIMUM_INTERVAL,
kAttachBackoffJitter = OPENTHREAD_CONFIG_MLE_ATTACH_BACKOFF_JITTER_INTERVAL
}
enum { kMaxNumTlvs = 16 }
enum { kMaxChildren = OPENTHREAD_CONFIG_MLE_MAX_CHILDREN, kMaxChildKeepAliveAttempts = 4, kFailedChildTransmissions = OPENTHREAD_CONFIG_FAILED_CHILD_TRANSMISSIONS, kMaxServiceAlocs = OPENTHREAD_CONFIG_TMF_NETDATA_SERVICE_MAX_ALOCS }
enum {
kThreadVersion = OPENTHREAD_CONFIG_THREAD_VERSION, kUdpPort = 19788, kParentRequestRouterTimeout = 750, kParentRequestDuplicateMargin = 50,
kParentRequestReedTimeout = 1250, kAttachStartJitter = 50, kAnnounceProcessTimeout = 250, kAnnounceTimeout = 1400,
kMinAnnounceDelay = 80, kParentResponseMaxDelayRouters = 500, kParentResponseMaxDelayAll = 1000, kUnicastRetransmissionDelay = 1000,
kChildUpdateRequestPendingDelay = 100, kMaxTransmissionCount = 3, kMaxResponseDelay = 1000, kMaxChildIdRequestTimeout = 5000,
kMaxChildUpdateResponseTimeout = 2000, kMaxLinkRequestTimeout = 2000, kMinTimeoutKeepAlive, kMinTimeoutDataPoll,
kMinTimeout
}
enum { kMinChildId = 1, kMaxChildId = 511, kRouterIdOffset = 10, kRlocPrefixLength = 14 }
enum { kMinChallengeSize = 4, kMaxChallengeSize = 8 }
enum {
kAdvertiseIntervalMin = 1, kAdvertiseIntervalMax = 32, kFailedRouterTransmissions = 4, kRouterIdReuseDelay = 100,
kRouterIdSequencePeriod = 10, kMaxNeighborAge = 100, kMaxRouteCost = 16, kMaxRouterId = OT_NETWORK_MAX_ROUTER_ID,
kInvalidRouterId = kMaxRouterId + 1, kMaxRouters = OPENTHREAD_CONFIG_MLE_MAX_ROUTERS, kMinDowngradeNeighbors = 7, kNetworkIdTimeout = 120,
kParentRouteToLeaderTimeout = 20, kRouterSelectionJitter = 120, kRouterDowngradeThreshold = 23, kRouterUpgradeThreshold = 16,
kMaxLeaderToRouterTimeout = 90, kReedAdvertiseInterval = 570, kReedAdvertiseJitter = 60, kLeaderWeight = 64,
kMleEndDeviceTimeout = OPENTHREAD_CONFIG_MLE_CHILD_TIMEOUT_DEFAULT, kMeshLocalPrefixContextId = 0
}
enum { kParentPriorityHigh = 1, kParentPriorityMedium = 0, kParentPriorityLow = -1, kParentPriorityUnspecified = -2 }
enum { kLinkQuality3LinkCost = 1, kLinkQuality2LinkCost = 2, kLinkQuality1LinkCost = 4, kLinkQuality0LinkCost = kMaxRouteCost }
enum { kMplChildDataMessageTimerExpirations = 0, kMplRouterDataMessageTimerExpirations = 2 }
enum { kServiceMinId = 0x00, kServiceMaxId = 0x0f }
enum AddressRegistrationMode { kAppendAllAddresses, kAppendMeshLocalOnly }
enum AlocAllocation {
kAloc16Leader = 0xfc00, kAloc16DhcpAgentStart = 0xfc01, kAloc16DhcpAgentEnd = 0xfc0f, kAloc16DhcpAgentMask = 0x000f,
kAloc16ServiceStart = 0xfc10, kAloc16ServiceEnd = 0xfc2f, kAloc16CommissionerStart = 0xfc30, kAloc16CommissionerEnd = 0xfc37,
kAloc16BackboneRouterPrimary = 0xfc38, kAloc16CommissionerMask = 0x0007, kAloc16NeighborDiscoveryAgentStart = 0xfc40, kAloc16NeighborDiscoveryAgentEnd = 0xfc4e
}
enum AttachMode {
kAttachAny = 0, kAttachSame1 = 1, kAttachSame2 = 2, kAttachBetter = 3,
kAttachSameDowngrade = 4
}
enum AttachState {
kAttachStateIdle, kAttachStateProcessAnnounce, kAttachStateStart, kAttachStateParentRequestRouter,
kAttachStateParentRequestReed, kAttachStateAnnounce, kAttachStateChildIdRequest
}
enum ChildUpdateRequestState { kChildUpdateRequestNone, kChildUpdateRequestPending, kChildUpdateRequestActive }
enum Command {
kCommandLinkRequest = 0, kCommandLinkAccept = 1, kCommandLinkAcceptAndRequest = 2, kCommandLinkReject = 3,
kCommandAdvertisement = 4, kCommandUpdate = 5, kCommandUpdateRequest = 6, kCommandDataRequest = 7,
kCommandDataResponse = 8, kCommandParentRequest = 9, kCommandParentResponse = 10, kCommandChildIdRequest = 11,
kCommandChildIdResponse = 12, kCommandChildUpdateRequest = 13, kCommandChildUpdateResponse = 14, kCommandAnnounce = 15,
kCommandDiscoveryRequest = 16, kCommandDiscoveryResponse = 17, kCommandTimeSync = 99
}
enum DataRequestState { kDataRequestNone, kDataRequestActive }
enum DeviceRole {
kRoleDisabled = OT_DEVICE_ROLE_DISABLED, kRoleDetached = OT_DEVICE_ROLE_DETACHED, kRoleChild = OT_DEVICE_ROLE_CHILD, kRoleRouter = OT_DEVICE_ROLE_ROUTER,
kRoleLeader = OT_DEVICE_ROLE_LEADER
}
enum ParentRequestType { kParentRequestTypeRouters, kParentRequestTypeRoutersAndReeds }
enum ReattachState { kReattachStop = 0, kReattachStart = 1, kReattachActive = 2, kReattachPending = 3 }
enum SecuritySuite { k154Security = 0, kNoSecurity = 255 }
Functions
otError AddDelayedResponse (Message &aMessage, const Ip6::Address &aDestination, uint16_t aDelay)
otError AddLeaderAloc (void)
otError AppendActiveTimestamp (Message &aMessage)
otError AppendAddress16 (Message &aMessage, uint16_t aRloc16)
otError AppendAddressRegistration (Message &aMessage, AddressRegistrationMode aMode=kAppendAllAddresses)
otError AppendChallenge (Message &aMessage, const uint8_t *aChallenge, uint8_t aChallengeLength)
otError AppendChallenge (Message &aMessage, const Challenge &aChallenge)
otError AppendHeader (Message &aMessage, Header::Command aCommand)
otError AppendLeaderData (Message &aMessage)
otError AppendLinkFrameCounter (Message &aMessage)
otError AppendLinkMargin (Message &aMessage, uint8_t aLinkMargin)
otError AppendMleFrameCounter (Message &aMessage)
otError AppendMode (Message &aMessage, DeviceMode aMode)
otError AppendNetworkData (Message &aMessage, bool aStableOnly)
otError AppendPendingTimestamp (Message &aMessage)
otError AppendResponse (Message &aMessage, const Challenge &aResponse)
otError AppendScanMask (Message &aMessage, uint8_t aScanMask)
otError AppendSourceAddress (Message &aMessage)
otError AppendStatus (Message &aMessage, StatusTlv::Status aStatus)
otError AppendTimeout (Message &aMessage, uint32_t aTimeout)
otError AppendTlvRequest (Message &aMessage, const uint8_t *aTlvs, uint8_t aTlvsLength)
otError AppendTo (Message &aMessage) const
otError AppendVersion (Message &aMessage)
void ApplyMeshLocalPrefix (void)
otError BecomeChild (AttachMode aMode)
otError BecomeDetached (void)
otError CheckReachability (uint16_t aMeshDest, Ip6::Header &aIp6Header)
static uint16_t ChildIdFromRloc16 (uint16_t aRloc16)
static uint16_t CommissionerAloc16FromId (uint16_t aSessionId)
otError Disable (void)
otError Discover (const Mac::ChannelMask &aScanChannels, uint16_t aPanId, bool aJoiner, bool aEnableFiltering, DiscoverHandler aCallback, void *aContext)
otError Enable (void)
void GenerateRandom (void)
uint32_t GetAttachStartDelay (void) const
const uint8_t * GetBytes (void) const
Command GetCommand (void) const
otError GetCommissionerAloc (Ip6::Address &aAddress, uint16_t aSessionId) const
const otMleCounters & GetCounters (void) const
DeviceMode GetDeviceMode (void) const
uint32_t GetFrameCounter (void) const
uint8_t GetHeaderLength (void) const
uint32_t GetKeyId (void) const
otError GetLeaderAddress (Ip6::Address &aAddress) const
otError GetLeaderAloc (Ip6::Address &aAddress) const
const LeaderData & GetLeaderData (void)
uint8_t GetLeaderId (void) const
uint8_t GetLength (void) const
const Ip6::Address & GetLinkLocalAddress (void) const
const Ip6::Address & GetLinkLocalAllThreadNodesAddress (void) const
otError GetLocatorAddress (Ip6::Address &aAddress, uint16_t aLocator) const
const Ip6::Address & GetMeshLocal16 (void) const
const Ip6::Address & GetMeshLocal64 (void) const
const MeshLocalPrefix & GetMeshLocalPrefix (void) const
const MessageQueue & GetMessageQueue (void) const
Neighbor * GetNeighbor (const Mac::Address &aAddress)
Neighbor * GetNeighbor (Mac::ShortAddress aAddress)
Neighbor * GetNeighbor (const Mac::ExtAddress &aAddress)
Neighbor * GetNeighbor (const Ip6::Address &aAddress)
Mac::ShortAddress GetNextHop (uint16_t aDestination) const
Router & GetParent (void)
Router & GetParentCandidate (void)
const Ip6::Address & GetRealmLocalAllThreadNodesAddress (void) const
uint16_t GetRloc16 (void) const
DeviceRole GetRole (void) const
uint8_t GetSecurityControl (void) const
SecuritySuite GetSecuritySuite (void) const
otError GetServiceAloc (uint8_t aServiceId, Ip6::Address &aAddress) const
uint32_t GetTimeout (void) const
otError HandleAdvertisement (const Message &aMessage, const Ip6::MessageInfo &aMessageInfo, Neighbor *aNeighbor)
otError HandleAnnounce (const Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
static void HandleAttachTimer (Timer &aTimer)
void HandleAttachTimer (void)
otError HandleChildIdResponse (const Message &aMessage, const Ip6::MessageInfo &aMessageInfo, const Neighbor *aNeighbor)
otError HandleChildUpdateRequest (const Message &aMessage, const Ip6::MessageInfo &aMessageInfo, Neighbor *aNeighbor)
otError HandleChildUpdateResponse (const Message &aMessage, const Ip6::MessageInfo &aMessageInfo, const Neighbor *aNeighbor)
otError HandleDataResponse (const Message &aMessage, const Ip6::MessageInfo &aMessageInfo, const Neighbor *aNeighbor)
static void HandleDelayedResponseTimer (Timer &aTimer)
void HandleDelayedResponseTimer (void)
void HandleDiscoverComplete (void)
otError HandleDiscoveryResponse (const Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
otError HandleLeaderData (const Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
static void HandleMessageTransmissionTimer (Timer &aTimer)
void HandleMessageTransmissionTimer (void)
otError HandleParentResponse (const Message &aMessage, const Ip6::MessageInfo &aMessageInfo, uint32_t aKeySequence)
static void HandleStateChanged (Notifier::Callback &aCallback, otChangedFlags aFlags)
void HandleStateChanged (otChangedFlags aFlags)
static void HandleUdpReceive (void *aContext, otMessage *aMessage, const otMessageInfo *aMessageInfo)
void HandleUdpReceive (Message &aMessage, const Ip6::MessageInfo &aMessageInfo)
bool HasUnregisteredAddress (void)
void InformPreviousChannel (void)
void Init (void)
static bool IsActiveRouter (uint16_t aRloc16)
bool IsAnnounceAttach (void) const
bool IsAnycastLocator (const Ip6::Address &aAddress) const
bool IsAttached (void) const
bool IsAttaching (void) const
bool IsBetterParent (uint16_t aRloc16, uint8_t aLinkQuality, uint8_t aLinkMargin, const ConnectivityTlv &aConnectivityTlv, uint8_t aVersion)
bool IsChild (void) const
bool IsDetached (void) const
bool IsDisabled (void) const
bool IsDiscoverInProgress (void) const
bool IsFullNetworkData (void) const
bool IsFullThreadDevice (void) const
bool IsKeyIdMode2 (void) const
bool IsLeader (void) const
bool IsMeshLocalAddress (const Ip6::Address &aAddress) const
bool IsMinimalEndDevice (void) const
bool IsNetworkDataNewer (const LeaderData &aLeaderData)
bool IsRouter (void) const
bool IsRouterOrLeader (void) const
bool IsRoutingLocator (const Ip6::Address &aAddress) const
bool IsRxOnWhenIdle (void) const
bool IsSecureDataRequest (void) const
bool IsValid (void) const
void LogMleMessage (const char *aLogString, const Ip6::Address &aAddress) const
void LogMleMessage (const char *aLogString, const Ip6::Address &aAddress, uint16_t aRloc) const
bool Matches (const uint8_t *aBuffer, uint8_t aLength) const
Mle (Instance &aInstance)
Message * NewMleMessage (void)
bool operator== (const Challenge &aOther) const
bool PrepareAnnounceState (void)
void ProcessAnnounce (void)
otError ReadChallenge (const Message &aMessage, Challenge &aChallenge)
otError ReadChallengeOrResponse (const Message &aMessage, uint8_t aTlvType, Challenge &aBuffer)
void ReadFrom (const Message &aMessage)
otError ReadLeaderData (const Message &aMessage, LeaderData &aLeaderData)
otError ReadResponse (const Message &aMessage, Challenge &aResponse)
otError ReadTlvRequest (const Message &aMessage, RequestedTlvs &aRequestedTlvs)
uint32_t Reattach (void)
void RegisterParentResponseStatsCallback (otThreadParentResponseCallback aCallback, void *aContext)
void RemoveDelayedDataResponseMessage (void)
void RemoveFrom (Message &aMessage) const
void RequestShorterChildIdRequest (void)
void ResetCounters (void)
otError Restore (void)
static uint16_t Rloc16FromRouterId (uint8_t aRouterId)
static const char * RoleToString (DeviceRole aRole)
static uint8_t RouterIdFromRloc16 (uint16_t aRloc16)
static bool RouterIdMatch (uint16_t aRloc16A, uint16_t aRloc16B)
void ScheduleMessageTransmissionTimer (void)
otError SendAnnounce (uint8_t aChannel, bool aOrphanAnnounce)
otError SendAnnounce (uint8_t aChannel, bool aOrphanAnnounce, const Ip6::Address &aDestination)
otError SendChildIdRequest (void)
otError SendChildUpdateRequest (void)
otError SendChildUpdateResponse (const uint8_t *aTlvs, uint8_t aNumTlvs, const Challenge &aChallenge)
otError SendDataRequest (const Ip6::Address &aDestination, const uint8_t *aTlvs, uint8_t aTlvsLength, uint16_t aDelay)
otError SendMessage (Message &aMessage, const Ip6::Address &aDestination)
otError SendOrphanAnnounce (void)
otError SendParentRequest (ParentRequestType aType)
static uint16_t ServiceAlocFromId (uint8_t aServiceId)
static uint8_t ServiceIdFromAloc (uint16_t aAloc16)
void SetAttachState (AttachState aState)
void SetCommand (Command aCommand)
otError SetDeviceMode (DeviceMode aDeviceMode)
void SetFrameCounter (uint32_t aFrameCounter)
void SetKeyId (uint32_t aKeySequence)
void SetKeyIdMode2 (void)
void SetLeaderData (uint32_t aPartitionId, uint8_t aWeighting, uint8_t aLeaderRouterId)
void SetMeshLocalPrefix (const MeshLocalPrefix &aMeshLocalPrefix)
void SetRloc16 (uint16_t aRloc16)
void SetRole (DeviceRole aRole)
void SetSecuritySuite (SecuritySuite aSecuritySuite)
void SetStateChild (uint16_t aRloc16)
void SetStateDetached (void)
void SetTimeout (uint32_t aTimeout)
otError Start (bool aAnnounceAttach)
void Stop (bool aClearNetworkDatasets)
otError Store (void)
void UpdateLinkLocalAddress (void)
Variables
AddressRegistrationMode mAddressRegistrationMode
uint8_t mAlternateChannel
uint16_t mAlternatePanId
uint64_t mAlternateTimestamp
uint8_t mAnnounceChannel
uint16_t mAnnounceDelay
Delay in between sending Announce messages during attach.
uint16_t mAttachCounter
Attach attempt counter.
AttachState mAttachState
The parent request state.
TimerMilli mAttachTimer
The timer for driving the attach process.
uint8_t mBuffer [kMaxChallengeSize]
Buffer containing the challenge/response byte sequence.
uint8_t mChildUpdateAttempts
ChildUpdateRequestState mChildUpdateRequestState
uint8_t mCommand
otMleCounters mCounters
uint8_t mDataRequestAttempts
DataRequestState mDataRequestState
MessageQueue mDelayedResponses
TimerMilli mDelayedResponseTimer
The timer to delay MLE responses.
Ip6::Address mDestination
DeviceMode mDeviceMode
Device mode setting.
uint16_t mDiscoverAnsiIndex
uint16_t mDiscoverCcittIndex
void * mDiscoverContext
bool mDiscoverEnableFiltering
DiscoverHandler mDiscoverHandler
bool mDiscoverInProgress
uint32_t mFrameCounter
uint8_t mKeyIndex
uint32_t mKeySource
Ip6::NetifUnicastAddress mLeaderAloc
LeaderData mLeaderData
Last received Leader Data TLV.
uint8_t mLength
Challenge length (in bytes).
Ip6::NetifUnicastAddress mLinkLocal64
Ip6::NetifMulticastAddress mLinkLocalAllThreadNodes
Ip6::NetifUnicastAddress mMeshLocal16
Ip6::NetifUnicastAddress mMeshLocal64
TimerMilli mMessageTransmissionTimer
The timer for (re-)sending of MLE messages (e.g. Child Update).
Notifier::Callback mNotifierCallback
uint8_t mNumTlvs
Number of TLVs in the array.
Router mParent
Parent information.
Router mParentCandidate
Challenge mParentCandidateChallenge
bool mParentIsSingleton
uint8_t mParentLeaderCost
LeaderData mParentLeaderData
uint8_t mParentLinkMargin
uint8_t mParentLinkQuality1
uint8_t mParentLinkQuality2
uint8_t mParentLinkQuality3
int8_t mParentPriority
Challenge mParentRequestChallenge
AttachMode mParentRequestMode
otThreadParentResponseCallback mParentResponseCb
void * mParentResponseCbContext
uint16_t mParentSedBufferSize
uint8_t mParentSedDatagramCount
Ip6::NetifMulticastAddress mRealmLocalAllThreadNodes
ReattachState mReattachState
Reattach state.
bool mReceivedResponseFromParent
bool mRetrieveNewNetworkData
Indicating new Network Data is needed if set.
DeviceRole mRole
Current Thread role.
uint8_t mSecurityControl
uint8_t mSecuritySuite
TimeMilli mSendTime
Ip6::UdpSocket mSocket
uint32_t mTimeout
uint8_t mTlvs [kMaxNumTlvs]
Array of requested TLVs.
OT_TOOL_PACKED_BEGIN class ot::Mle::Header OT_TOOL_PACKED_END
Detailed Description
This module includes definitions for MLE functionality required by the Thread Child, Router, and Leader roles.
This module includes definition for MLE types and constants.
Typedef Documentation
DiscoverHandler
typedef void(* DiscoverHandler) (otActiveScanResult *aResult, void *aContext)
This function pointer is called on receiving an MLE Discovery Response message.
Parameters
[in] aResult A valid pointer to the Discovery Response information or NULL when the Discovery completes.
[in] aContext A pointer to application-specific context.
Enumeration Type Documentation
Command
enum Command
MLE Command Types.
Enumerator
kCommandLinkRequest
Link Request.
kCommandLinkAccept
Link Accept.
kCommandLinkAcceptAndRequest
Link Accept and Reject.
kCommandLinkReject
Link Reject.
kCommandAdvertisement
Advertisement.
kCommandUpdate
Update.
kCommandUpdateRequest
Update Request.
kCommandDataRequest
Data Request.
kCommandDataResponse
Data Response.
kCommandParentRequest
Parent Request.
kCommandParentResponse
Parent Response.
kCommandChildIdRequest
Child ID Request.
kCommandChildIdResponse
Child ID Response.
kCommandChildUpdateRequest
Child Update Request.
kCommandChildUpdateResponse
Child Update Response.
kCommandAnnounce
Announce.
kCommandDiscoveryRequest
Discovery Request.
kCommandDiscoveryResponse
Discovery Response.
kCommandTimeSync
Time Sync (applicable when OPENTHREAD_CONFIG_TIME_SYNC_ENABLE enabled)
SecuritySuite
enum SecuritySuite
MLE Security Suite
Enumerator
k154Security
IEEE 802.15.4-2006 security.
kNoSecurity
No security enabled.
AttachState
enum AttachState protected
States during attach (when searching for a parent).
Enumerator
kAttachStateIdle
Not currently searching for a parent.
kAttachStateProcessAnnounce
Waiting to process a received Announce (to switch channel/pan-id).
kAttachStateStart
Starting to look for a parent.
kAttachStateParentRequestRouter
Searching for a Router to attach to.
kAttachStateParentRequestReed
Searching for Routers or REEDs to attach to.
kAttachStateAnnounce
Send Announce messages.
kAttachStateChildIdRequest
Sending a Child ID Request message.
ReattachState
enum ReattachState protected
States when reattaching network using stored dataset
Enumerator
kReattachStop
Reattach process is disabled or finished.
kReattachStart
Start reattach process.
kReattachActive
Reattach using stored Active Dataset.
kReattachPending
Reattach using stored Pending Dataset.
anonymous enum
anonymous enum protected
Enumerator
kMleMaxResponseDelay
Maximum delay before responding to a multicast request.
AddressRegistrationMode
enum AddressRegistrationMode protected
This enumeration type is used in AppendAddressRegistration() to determine which addresses to include in the appended Address Registration TLV.
Enumerator
kAppendAllAddresses
Append all addresses (unicast/multicast) in Address Registration TLV.
kAppendMeshLocalOnly
Only append the Mesh Local (ML-EID) address in Address Registration TLV.
anonymous enum
anonymous enum
Enumerator
kMaxNumTlvs
Maximum number of TLVs in request array.
anonymous enum
anonymous enum private
Enumerator
kMleMessagePriority
kMleHopLimit
kParentSearchCheckInterval
kParentSearchBackoffInterval
kParentSearchJitterInterval
kParentSearchRssThreadhold
kAttachBackoffMinInterval
kAttachBackoffMaxInterval
kAttachBackoffJitter
ParentRequestType
enum ParentRequestType private
Enumerator
kParentRequestTypeRouters
Parent Request to all routers.
kParentRequestTypeRoutersAndReeds
Parent Request to all routers and REEDs.
ChildUpdateRequestState
enum ChildUpdateRequestState private
Enumerator
kChildUpdateRequestNone
No pending or active Child Update Request.
kChildUpdateRequestPending
Pending Child Update Request due to relative OT_CHANGED event.
kChildUpdateRequestActive
Child Update Request has been sent and Child Update Response is expected.
DataRequestState
enum DataRequestState private
Enumerator
kDataRequestNone
Not waiting for a Data Response.
kDataRequestActive
Data Request has been sent, Data Response is expected.
anonymous enum
anonymous enum
Enumerator
kMaxChildren
kMaxChildKeepAliveAttempts
Maximum keep alive attempts before attempting to reattach to a new Parent.
kFailedChildTransmissions
FAILED_CHILD_TRANSMISSIONS.
kMaxServiceAlocs
anonymous enum
anonymous enum
MLE Protocol Constants
Enumerator
kThreadVersion
Thread Version.
kUdpPort
MLE UDP Port.
kParentRequestRouterTimeout
Router Parent Request timeout.
kParentRequestDuplicateMargin
Margin for duplicate parent request.
kParentRequestReedTimeout
Router and REEDs Parent Request timeout.
kAttachStartJitter
Maximum jitter time added to start of attach.
kAnnounceProcessTimeout
Timeout after receiving Announcement before channel/pan-id change.
kAnnounceTimeout
Total timeout used for sending Announcement messages.
kMinAnnounceDelay
Minimum delay between Announcement messages.
kParentResponseMaxDelayRouters
Maximum delay for response for Parent Request sent to routers only.
kParentResponseMaxDelayAll
Maximum delay for response for Parent Request sent to all devices.
kUnicastRetransmissionDelay
Base delay before retransmitting an MLE unicast.
kChildUpdateRequestPendingDelay
Delay (in ms) for aggregating Child Update Request.
kMaxTransmissionCount
Maximum number of times an MLE message may be transmitted.
kMaxResponseDelay
Maximum delay before responding to a multicast request.
kMaxChildIdRequestTimeout
Maximum delay for receiving a Child ID Request.
kMaxChildUpdateResponseTimeout
Maximum delay for receiving a Child Update Response.
kMaxLinkRequestTimeout
Maximum delay for receiving a Link Accept.
kMinTimeoutKeepAlive
Minimum timeout(in seconds) for keep alive.
kMinTimeoutDataPoll
Minimum timeout(in seconds) for data poll.
kMinTimeout
Minimum timeout(in seconds)
anonymous enum
anonymous enum
Enumerator
kMinChildId
Minimum Child ID.
kMaxChildId
Maximum Child ID.
kRouterIdOffset
Bit offset of Router ID in RLOC16.
kRlocPrefixLength
Prefix length of RLOC in bytes.
anonymous enum
anonymous enum
MLE TLV Constants
Enumerator
kMinChallengeSize
Minimum Challenge size in bytes.
kMaxChallengeSize
Maximum Challenge size in bytes.
anonymous enum
anonymous enum
Routing Protocol Constants
Enumerator
kAdvertiseIntervalMin
ADVERTISEMENT_I_MIN (sec)
kAdvertiseIntervalMax
ADVERTISEMENT_I_MAX (sec)
kFailedRouterTransmissions
FAILED_ROUTER_TRANSMISSIONS.
kRouterIdReuseDelay
ID_REUSE_DELAY (sec)
kRouterIdSequencePeriod
ID_SEQUENCE_PERIOD (sec)
kMaxNeighborAge
MAX_NEIGHBOR_AGE (sec)
kMaxRouteCost
MAX_ROUTE_COST.
kMaxRouterId
MAX_ROUTER_ID.
kInvalidRouterId
Value indicating incorrect Router Id.
kMaxRouters
MAX_ROUTERS.
kMinDowngradeNeighbors
MIN_DOWNGRADE_NEIGHBORS.
kNetworkIdTimeout
NETWORK_ID_TIMEOUT (sec)
kParentRouteToLeaderTimeout
PARENT_ROUTE_TO_LEADER_TIMEOUT (sec)
kRouterSelectionJitter
ROUTER_SELECTION_JITTER (sec)
kRouterDowngradeThreshold
ROUTER_DOWNGRADE_THRESHOLD (routers)
kRouterUpgradeThreshold
ROUTER_UPGRADE_THRESHOLD (routers)
kMaxLeaderToRouterTimeout
INFINITE_COST_TIMEOUT (sec)
kReedAdvertiseInterval
REED_ADVERTISEMENT_INTERVAL (sec)
kReedAdvertiseJitter
REED_ADVERTISEMENT_JITTER (sec)
kLeaderWeight
Default leader weight.
kMleEndDeviceTimeout
MLE_END_DEVICE_TIMEOUT (sec)
kMeshLocalPrefixContextId
0 is reserved for Mesh Local Prefix
anonymous enum
anonymous enum
Parent Priority values
Enumerator
kParentPriorityHigh
kParentPriorityMedium
kParentPriorityLow
kParentPriorityUnspecified
anonymous enum
anonymous enum
Enumerator
kLinkQuality3LinkCost
Link Cost for Link Quality 3.
kLinkQuality2LinkCost
Link Cost for Link Quality 2.
kLinkQuality1LinkCost
Link Cost for Link Quality 1.
kLinkQuality0LinkCost
Link Cost for Link Quality 0.
anonymous enum
anonymous enum
Multicast Forwarding Constants
Enumerator
kMplChildDataMessageTimerExpirations
Number of MPL retransmissions for Children.
kMplRouterDataMessageTimerExpirations
Number of MPL retransmissions for Routers.
DeviceRole
enum DeviceRole
This type represents a Thread device role.
Enumerator
kRoleDisabled
The Thread stack is disabled.
kRoleDetached
Not currently participating in a Thread network/partition.
kRoleChild
The Thread Child role.
kRoleRouter
The Thread Router role.
kRoleLeader
The Thread Leader role.
AttachMode
enum AttachMode
MLE Attach modes
Enumerator
kAttachAny
Attach to any Thread partition.
kAttachSame1
Attach to the same Thread partition (attempt 1 when losing connectivity).
kAttachSame2
Attach to the same Thread partition (attempt 2 when losing connectivity).
kAttachBetter
Attach to a better (i.e. higher weight/partition id) Thread partition.
kAttachSameDowngrade
Attach to the same Thread partition during downgrade process.
AlocAllocation
enum AlocAllocation
This enumeration represents the allocation of the ALOC Space
Enumerator
kAloc16Leader
kAloc16DhcpAgentStart
kAloc16DhcpAgentEnd
kAloc16DhcpAgentMask
kAloc16ServiceStart
kAloc16ServiceEnd
kAloc16CommissionerStart
kAloc16CommissionerEnd
kAloc16BackboneRouterPrimary
kAloc16CommissionerMask
kAloc16NeighborDiscoveryAgentStart
kAloc16NeighborDiscoveryAgentEnd
anonymous enum
anonymous enum
Service IDs
Enumerator
kServiceMinId
Minimal Service ID.
kServiceMaxId
Maximal Service ID.
Function Documentation
Init()
void Init (void) inline
This method initializes the MLE header.
References Header::k154Security, Frame::kSecEncMic32, Header::mSecurityControl, and Header::mSecuritySuite.
Referenced by Mle::AppendHeader().
IsValid()
bool IsValid (void) const inline
This method indicates whether or not the TLV appears to be well-formed.
Return values
TRUE If the TLV appears to be well-formed.
FALSE If the TLV does not appear to be well-formed.
References Header::k154Security, Frame::kKeyIdMode2, Header::kNoSecurity, Frame::kSecEncMic32, Header::mSecurityControl, and Header::mSecuritySuite.
Referenced by Mle::HandleUdpReceive().
GetLength()
uint8_t GetLength (void) const inline
This method returns the MLE header and Command Type length.
Returns
The MLE header and Command Type length.
References Header::k154Security, Header::mCommand, Header::mFrameCounter, Header::mKeyIndex, Header::mKeySource, Header::mSecurityControl, and Header::mSecuritySuite.
Referenced by Mle::AppendHeader(), Mle::HandleUdpReceive(), and Mle::SendMessage().
GetSecuritySuite()
SecuritySuite GetSecuritySuite (void) const inline
This method returns the Security Suite value.
Returns
The Security Suite value.
References Header::mSecuritySuite.
Referenced by Mle::HandleUdpReceive(), and Mle::SendMessage().
SetSecuritySuite()
void SetSecuritySuite (SecuritySuite aSecuritySuite) inline
This method sets the Security Suite value.
Parameters
[in] aSecuritySuite The Security Suite value.
References Header::mSecuritySuite.
Referenced by Mle::AppendHeader().
GetHeaderLength()
uint8_t GetHeaderLength (void) const inline
This method returns the MLE header length (excluding the Command Type).
Returns
The MLE header length (excluding the Command Type).
References Header::mFrameCounter, Header::mKeyIndex, Header::mKeySource, and Header::mSecurityControl.
Referenced by Mle::HandleUdpReceive(), and Mle::SendMessage().
GetBytes()
const uint8_t* GetBytes (void) const inline
This method returns a pointer to first byte of the MLE header.
Returns
A pointer to the first byte of the MLE header.
References Header::mSecuritySuite.
Referenced by Mle::HandleUdpReceive(), and Mle::SendMessage().
GetSecurityControl()
uint8_t GetSecurityControl (void) const inline
This method returns the Security Control value.
Returns
The Security Control value.
References Header::mSecurityControl.
IsKeyIdMode2()
bool IsKeyIdMode2 (void) const inline
This method indicates whether or not the Key ID Mode is set to 2.
Return values
TRUE If the Key ID Mode is set to 2.
FALSE If the Key ID Mode is not set to 2.
References Frame::kKeyIdMode2, Frame::kKeyIdModeMask, and Header::mSecurityControl.
SetKeyIdMode2()
void SetKeyIdMode2 (void) inline
This method sets the Key ID Mode to 2.
References Frame::kKeyIdMode2, and Header::mSecurityControl.
Referenced by Mle::AppendHeader().
GetKeyId()
uint32_t GetKeyId (void) const inline
This method returns the Key ID value.
Returns
The Key ID value.
References ot::Encoding::BigEndian::HostSwap32(), and Header::mKeySource.
Referenced by Mle::HandleUdpReceive().
SetKeyId()
void SetKeyId (uint32_t aKeySequence) inline
This method sets the Key ID value.
Parameters
[in] aKeySequence The Key ID value.
References ot::Encoding::BigEndian::HostSwap32(), Header::mKeyIndex, and Header::mKeySource.
Referenced by Mle::SendMessage().
GetFrameCounter()
uint32_t GetFrameCounter (void) const inline
This method returns the Frame Counter value.
Returns
The Frame Counter value.
References ot::Encoding::LittleEndian::HostSwap32(), and Header::mFrameCounter.
Referenced by Mle::HandleUdpReceive().
SetFrameCounter()
void SetFrameCounter (uint32_t aFrameCounter) inline
This method sets the Frame Counter value.
Parameters
[in] aFrameCounter The Frame Counter value.
References ot::Encoding::LittleEndian::HostSwap32(), and Header::mFrameCounter.
Referenced by Mle::SendMessage().
GetCommand()
Command GetCommand (void) const inline
This method returns the Command Type value.
Returns
The Command Type value.
References Header::kNoSecurity, Header::mCommand, Header::mSecurityControl, and Header::mSecuritySuite.
Referenced by Mle::HandleUdpReceive().
SetCommand()
void SetCommand (Command aCommand) inline
This method sets the Command Type value.
Parameters
[in] aCommand The Command Type value.
References Header::kNoSecurity, Header::mCommand, Header::mSecurityControl, and Header::mSecuritySuite.
Referenced by Mle::AppendHeader().
Mle()
Mle (Instance & aInstance) explicit
This constructor initializes the MLE object.
Parameters
[in] aInstance A reference to the OpenThread instance.
References NetifUnicastAddress::Clear(), NetifMulticastAddress::Clear(), LeaderData::Clear(), Router::Clear(), ot::Random::Crypto::FillBuffer(), NetifUnicastAddress::GetAddress(), NetifMulticastAddress::GetAddress(), ot::Encoding::BigEndian::HostSwap16(), Router::Init(), MeshLocalPrefix::kLength, Address::kRealmLocalScope, ot::Mac::kShortAddrInvalid, otIp6Address::OT_TOOL_PACKED_FIELD::m16, otIp6Address::OT_TOOL_PACKED_FIELD::m8, otIp6Address::mFields, Mle::mLeaderAloc, Mle::mLeaderData, Mle::mLinkLocal64, Mle::mLinkLocalAllThreadNodes, Mle::mMeshLocal16, Mle::mMeshLocal64, Mle::mParent, Mle::mParentCandidate, Mle::mParentLeaderData, otNetifAddress::mPreferred, otNetifAddress::mPrefixLength, Mle::mRealmLocalAllThreadNodes, otNetifAddress::mRloc, otNetifAddress::mScopeOverride, otNetifAddress::mScopeOverrideValid, otNetifAddress::mValid, OT_ARRAY_LENGTH, OT_IP6_ADDRESS_SIZE, OT_IP6_PREFIX_SIZE, Mle::ResetCounters(), MeshLocalPrefix::SetFromExtendedPanId(), Address::SetIidToLocator(), Mle::SetMeshLocalPrefix(), and Address::SetToLinkLocalAddress().
Enable()
otError Enable (void)
This method enables MLE.
Return values
OT_ERROR_NONE Successfully enabled MLE.
OT_ERROR_ALREADY MLE was already enabled.
References UdpSocket::Bind(), Mle::HandleUdpReceive(), ot::Mle::kUdpPort, otSockAddr::mPort, Mle::mSocket, UdpSocket::Open(), OT_ERROR_NONE, SuccessOrExit, and Mle::UpdateLinkLocalAddress().
Disable()
otError Disable (void)
This method disables MLE.
Return values
OT_ERROR_NONE Successfully disabled MLE.
References UdpSocket::Close(), Mle::mLinkLocal64, Mle::mSocket, OT_ERROR_NONE, Mle::Stop(), and SuccessOrExit.
Start()
otError Start (bool aAnnounceAttach)
This method starts the MLE protocol operation.
Parameters
[in] aAnnounceAttach True if attach on the announced thread network with newer active timestamp, or False if not.
Return values
OT_ERROR_NONE Successfully started the protocol operation.
OT_ERROR_ALREADY The protocol operation was already started.
References Mle::ApplyMeshLocalPrefix(), Mle::BecomeChild(), Mle::GetRloc16(), ot::Random::NonCrypto::GetUint16(), Mle::IsActiveRouter(), ot::Mle::kAttachAny, ot::Mac::kPanIdBroadcast, Mle::kReattachStart, ot::Mac::kShortAddrInvalid, ThreadStatusTlv::kTooFewRouters, Mle::mAttachCounter, Mle::mChildUpdateAttempts, Mle::mReattachState, OT_ERROR_INVALID_STATE, OT_ERROR_NONE, Mle::SendChildUpdateRequest(), Mle::SetRloc16(), Mle::SetStateDetached(), and VerifyOrExit.
Referenced by Mle::ProcessAnnounce().
Stop()
void Stop (bool aClearNetworkDatasets)
This method stops the MLE protocol operation.
Parameters
[in] aClearNetworkDatasets True to clear network datasets, False not.
References Mle::IsDisabled(), ot::Mle::kRoleDisabled, Mle::mLinkLocalAllThreadNodes, Mle::mMeshLocal16, Mle::mMeshLocal64, Mle::mRealmLocalAllThreadNodes, OT_NOOP, Mle::SetRole(), Mle::SetStateDetached(), and VerifyOrExit.
Referenced by Mle::Disable(), and Mle::ProcessAnnounce().
Restore()
otError Restore (void)
This method restores network information from non-volatile memory.
Return values
OT_ERROR_NONE Successfully restore the network information.
OT_ERROR_NOT_FOUND There is no valid network information stored in non-volatile memory.
References Router::Clear(), ExitNow, NetifUnicastAddress::GetAddress(), SettingsBase::NetworkInfo::GetDeviceMode(), SettingsBase::NetworkInfo::GetExtAddress(), SettingsBase::ParentInfo::GetExtAddress(), SettingsBase::NetworkInfo::GetKeySequence(), SettingsBase::NetworkInfo::GetMacFrameCounter(), SettingsBase::NetworkInfo::GetMeshLocalIid(), SettingsBase::NetworkInfo::GetMleFrameCounter(), SettingsBase::NetworkInfo::GetPreviousPartitionId(), SettingsBase::NetworkInfo::GetRloc16(), Neighbor::GetRloc16(), Mle::GetRloc16(), SettingsBase::NetworkInfo::GetRole(), SettingsBase::NetworkInfo::GetVersion(), SettingsBase::ParentInfo::GetVersion(), Mle::IsActiveRouter(), DeviceMode::kModeFullNetworkData, DeviceMode::kModeFullThreadDevice, DeviceMode::kModeRxOnWhenIdle, DeviceMode::kModeSecureDataRequest, ot::Mle::kRoleChild, ot::Mle::kRoleLeader, ot::Mle::kRoleRouter, ot::Mac::kShortAddrInvalid, Neighbor::kStateRestored, ot::Mle::kThreadVersion, otIp6Address::OT_TOOL_PACKED_FIELD::m8, Mle::mDeviceMode, otIp6Address::mFields, Mle::mMeshLocal64, Mle::mParent, OT_ERROR_NONE, OT_IP6_ADDRESS_SIZE, OT_IP6_PREFIX_SIZE, OT_NOOP, otLogWarnMle, Mle::Rloc16FromRouterId(), Mle::RouterIdFromRloc16(), DeviceMode::Set(), Neighbor::SetDeviceMode(), Neighbor::SetExtAddress(), Neighbor::SetRloc16(), Neighbor::SetState(), Neighbor::SetVersion(), SuccessOrExit, and VerifyOrExit.
Referenced by Mle::BecomeChild(), and Mle::Reattach().
Store()
otError Store (void)
This method stores network information into non-volatile memory.
Return values
OT_ERROR_NONE Successfully store the network information.
OT_ERROR_NO_BUFS Could not store the network information due to insufficient memory space.
References DeviceMode::Get(), NetifUnicastAddress::GetAddress(), Neighbor::GetExtAddress(), SettingsBase::NetworkInfo::GetMacFrameCounter(), SettingsBase::NetworkInfo::GetMleFrameCounter(), LeaderData::GetPartitionId(), Mle::GetRloc16(), Neighbor::GetVersion(), SettingsBase::NetworkInfo::Init(), SettingsBase::ParentInfo::Init(), Mle::IsAttached(), Mle::IsChild(), ot::Mle::kThreadVersion, otIp6Address::OT_TOOL_PACKED_FIELD::m8, Mle::mDeviceMode, otIp6Address::mFields, Mle::mLeaderData, Mle::mMeshLocal64, Mle::mParent, Mle::mRole, OPENTHREAD_CONFIG_STORE_FRAME_COUNTER_AHEAD, OT_ERROR_NONE, OT_IP6_PREFIX_SIZE, otLogDebgMle, SettingsBase::NetworkInfo::SetDeviceMode(), SettingsBase::NetworkInfo::SetExtAddress(), SettingsBase::ParentInfo::SetExtAddress(), SettingsBase::NetworkInfo::SetKeySequence(), SettingsBase::NetworkInfo::SetMacFrameCounter(), SettingsBase::NetworkInfo::SetMeshLocalIid(), SettingsBase::NetworkInfo::SetMleFrameCounter(), SettingsBase::NetworkInfo::SetPreviousPartitionId(), SettingsBase::NetworkInfo::SetRloc16(), SettingsBase::NetworkInfo::SetRole(), SettingsBase::NetworkInfo::SetVersion(), SettingsBase::ParentInfo::SetVersion(), and SuccessOrExit.
Referenced by Mle::HandleStateChanged(), and Mle::SetDeviceMode().
Discover()
otError Discover (const Mac::ChannelMask & aScanChannels, uint16_t aPanId, bool aJoiner, bool aEnableFiltering, DiscoverHandler aCallback, void * aContext)
This method initiates a Thread Discovery.
Parameters
[in] aScanChannels A bit vector indicating which channels to scan.
[in] aPanId The PAN ID filter (set to Broadcast PAN to disable filter).
[in] aJoiner Value of the Joiner Flag in the Discovery Request TLV.
[in] aEnableFiltering Enable filtering out MLE discovery responses that don't match our factory assigned EUI64.
[in] aHandler A pointer to a function that is called on receiving an MLE Discovery Response.
[in] aContext A pointer to arbitrary context information.
Return values
OT_ERROR_NONE Successfully started a Thread Discovery.
OT_ERROR_BUSY Thread Discovery is already in progress.
References Message::Append(), Mle::AppendHeader(), Tlv::AppendTo(), ot::MeshCoP::ComputeJoinerId(), Message::Free(), Crc16::Get(), Message::GetLength(), DiscoveryRequestTlv::Init(), Crc16::kAnsi, Crc16::kCcitt, Header::kCommandDiscoveryRequest, Tlv::kDiscovery, Message::kSubTypeMleDiscoverRequest, ot::Mle::kThreadVersion, Mle::LogMleMessage(), otExtAddress::m8, Mle::mDiscoverAnsiIndex, Mle::mDiscoverCcittIndex, Mle::mDiscoverContext, Mle::mDiscoverEnableFiltering, Mle::mDiscoverHandler, Mle::mDiscoverInProgress, Mle::NewMleMessage(), OT_ERROR_BUSY, OT_ERROR_NO_BUFS, OT_ERROR_NONE, Mle::SendMessage(), DiscoveryRequestTlv::SetJoiner(), Tlv::SetLength(), Message::SetPanId(), Message::SetSubType(), Address::SetToLinkLocalAllRoutersMulticast(), Tlv::SetType(), DiscoveryRequestTlv::SetVersion(), SuccessOrExit, Crc16::Update(), VerifyOrExit, and Message::Write().
IsDiscoverInProgress()
bool IsDiscoverInProgress (void) const inline
This method indicates whether or not an MLE Thread Discovery is currently in progress.
Returns
true if an MLE Thread Discovery is in progress, false otherwise.
HandleDiscoverComplete()
void HandleDiscoverComplete (void)
This method is called by the MeshForwarder to indicate that discovery is complete.
References Mle::mDiscoverContext, Mle::mDiscoverEnableFiltering, Mle::mDiscoverHandler, and Mle::mDiscoverInProgress.
SendAnnounce() [1/2]
otError SendAnnounce (uint8_t aChannel, bool aOrphanAnnounce)
This method generates an MLE Announce message.
Parameters
[in] aChannel The channel to use when transmitting.
[in] aOrphanAnnounce To indicate if MLE Announce is sent from an orphan end device.
Return values
OT_ERROR_NONE Successfully generated an MLE Announce message.
OT_ERROR_NO_BUFS Insufficient buffers to generate the MLE Announce message.
References Address::SetToLinkLocalAllNodesMulticast().
Referenced by Mle::HandleAnnounce(), Mle::InformPreviousChannel(), and Mle::SendOrphanAnnounce().
BecomeDetached()
otError BecomeDetached (void)
This method causes the Thread interface to detach from the Thread network.
Return values
OT_ERROR_NONE Successfully detached from the Thread network.
OT_ERROR_INVALID_STATE MLE is Disabled.
References Mle::BecomeChild(), Mle::IsDetached(), Mle::IsDisabled(), ot::Mle::kAttachAny, Mle::kAttachStateStart, Mle::kReattachStop, ot::Mac::kShortAddrInvalid, Neighbor::kStateInvalid, Mle::mAttachState, Mle::mParent, Mle::mReattachState, OT_ERROR_INVALID_STATE, OT_ERROR_NONE, OT_NOOP, Mle::SetRloc16(), Neighbor::SetState(), Mle::SetStateDetached(), and VerifyOrExit.
Referenced by Mle::HandleAdvertisement(), Mle::HandleChildUpdateRequest(), Mle::HandleChildUpdateResponse(), Mle::HandleMessageTransmissionTimer(), Mle::Reattach(), Mle::SendChildUpdateRequest(), and Mle::SetDeviceMode().
BecomeChild()
otError BecomeChild (AttachMode aMode)
This method causes the Thread interface to attempt an MLE attach.
Parameters
[in] aMode Indicates what partitions to attach to.
Return values
OT_ERROR_NONE Successfully began the attach process.
OT_ERROR_INVALID_STATE MLE is Disabled.
OT_ERROR_BUSY An attach process is in progress.
References Router::Clear(), Mle::GetAttachStartDelay(), Mle::IsAttaching(), Mle::IsDetached(), Mle::IsDisabled(), Mle::IsFullThreadDevice(), Mle::IsRxOnWhenIdle(), ot::Mle::kAttachBetter, Mle::kAttachStateStart, Mle::kReattachActive, Mle::kReattachStart, Mle::kReattachStop, otMleCounters::mAttachAttempts, Mle::mAttachCounter, Mle::mAttachTimer, otMleCounters::mBetterPartitionAttachAttempts, Mle::mCounters, Mle::mParentCandidate, Mle::mParentRequestMode, Mle::mReattachState, OT_ERROR_BUSY, OT_ERROR_INVALID_STATE, OT_ERROR_NONE, Mle::Restore(), Mle::SetAttachState(), TimerMilli::Start(), and VerifyOrExit.
Referenced by Mle::BecomeDetached(), Mle::CheckReachability(), Mle::Reattach(), Mle::SetDeviceMode(), and Mle::Start().
IsAttached()
bool IsAttached (void) const
This method indicates whether or not the Thread device is attached to a Thread network.
Return values
TRUE Attached to a Thread network.
FALSE Not attached to a Thread network.
References Mle::IsChild(), Mle::IsLeader(), and Mle::IsRouter().
Referenced by Mle::ApplyMeshLocalPrefix(), Mle::HandleParentResponse(), Mle::HandleStateChanged(), and Mle::Store().
IsAttaching()
bool IsAttaching (void) const inline
This method indicates whether device is currently attaching or not.
Note that an already attached device may also be in attaching state. Examples of this include a leader/router trying to attach to a better partition, or a child trying to find a better parent (when feature OPENTHREAD_CONFIG_PARENT_SEARCH_ENABLE is enabled).
Return values
TRUE Device is currently trying to attach.
FALSE Device is not in middle of attach process.
Referenced by Mle::BecomeChild().
GetRole()
DeviceRole GetRole (void) const inline
This method returns the current Thread device role.
Returns
The current Thread device role.
IsDisabled()
bool IsDisabled (void) const inline
This method indicates whether device role is disabled.
Return values
TRUE Device role is disabled.
FALSE Device role is not disabled.
References ot::Mle::kRoleDisabled.
Referenced by Mle::ApplyMeshLocalPrefix(), Mle::BecomeChild(), Mle::BecomeDetached(), Mle::HandleStateChanged(), Mle::HandleUdpReceive(), and Mle::Stop().
IsDetached()
bool IsDetached (void) const inline
This method indicates whether device role is detached.
Return values
TRUE Device role is detached.
FALSE Device role is not detached.
References ot::Mle::kRoleDetached.
Referenced by Mle::BecomeChild(), Mle::BecomeDetached(), Mle::GetAttachStartDelay(), Mle::HandleAdvertisement(), Mle::HandleAnnounce(), and Mle::HandleParentResponse().
IsChild()
bool IsChild (void) const inline
This method indicates whether device role is child.
Return values
TRUE Device role is child.
FALSE Device role is not child.
References ot::Mle::kRoleChild.
Referenced by Mle::CheckReachability(), Mle::HandleAttachTimer(), Mle::HandleLeaderData(), Mle::HandleMessageTransmissionTimer(), Mle::HandleParentResponse(), Mle::HandleStateChanged(), Mle::InformPreviousChannel(), Mle::IsAttached(), Mle::PrepareAnnounceState(), Mle::Reattach(), Mle::ScheduleMessageTransmissionTimer(), Mle::SendChildIdRequest(), Mle::SendDataRequest(), Mle::SetRole(), Mle::SetTimeout(), and Mle::Store().
IsRouter()
bool IsRouter (void) const inline
This method indicates whether device role is router.
Return values
TRUE Device role is router.
FALSE Device role is not router.
References ot::Mle::kRoleRouter.
Referenced by Mle::InformPreviousChannel(), Mle::IsAttached(), and Mle::IsRouterOrLeader().
IsLeader()
bool IsLeader (void) const inline
This method indicates whether device role is leader.
Return values
TRUE Device role is leader.
FALSE Device role is not leader.
References ot::Mle::kRoleLeader.
Referenced by Mle::AddLeaderAloc(), Mle::ApplyMeshLocalPrefix(), Mle::IsAttached(), Mle::IsRouterOrLeader(), Mle::SetStateChild(), and Mle::SetStateDetached().
IsRouterOrLeader()
bool IsRouterOrLeader (void) const
This method indicates whether device role is either router or leader.
Return values
TRUE Device role is either router or leader.
FALSE Device role is neither router nor leader.
References Mle::IsLeader(), and Mle::IsRouter().
Referenced by Mle::HandleUdpReceive().
GetDeviceMode()
DeviceMode GetDeviceMode (void) const inline
This method returns the Device Mode as reported in the Mode TLV.
Returns
The Device Mode as reported in the Mode TLV.
SetDeviceMode()
otError SetDeviceMode (DeviceMode aDeviceMode)
This method sets the Device Mode as reported in the Mode TLV.
Parameters
[in] aDeviceMode The device mode to set.
Return values
OT_ERROR_NONE Successfully set the Mode TLV.
OT_ERROR_INVALID_ARGS The mode combination specified in aMode is invalid.
References String< SIZE >::AsCString(), Mle::BecomeChild(), Mle::BecomeDetached(), DeviceMode::Get(), Mle::GetRloc16(), DeviceMode::IsFullThreadDevice(), DeviceMode::IsValid(), ot::Mle::kAttachAny, ot::Mle::kRoleChild, ot::Mle::kRoleDetached, ot::Mle::kRoleDisabled, ot::Mle::kRoleLeader, ot::Mle::kRoleRouter, Mle::mAttachCounter, Mle::mDeviceMode, Mle::mRole, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, OT_NOOP, otLogNoteMle, Mle::SendChildUpdateRequest(), Mle::SetStateChild(), Mle::SetStateDetached(), Mle::Store(), DeviceMode::ToString(), and VerifyOrExit.
IsRxOnWhenIdle()
bool IsRxOnWhenIdle (void) const inline
This method indicates whether or not the device is rx-on-when-idle.
Returns
TRUE if rx-on-when-idle, FALSE otherwise.
Referenced by Mle::AppendAddressRegistration(), Mle::BecomeChild(), Mle::HandleChildIdResponse(), Mle::HandleChildUpdateResponse(), Mle::HandleDataResponse(), Mle::HandleDelayedResponseTimer(), Mle::HandleMessageTransmissionTimer(), Mle::HandleStateChanged(), Mle::HasUnregisteredAddress(), Mle::Reattach(), Mle::ScheduleMessageTransmissionTimer(), Mle::SendChildIdRequest(), Mle::SendChildUpdateRequest(), and Mle::SendDataRequest().
IsFullThreadDevice()
bool IsFullThreadDevice (void) const inline
This method indicates whether or not the device is a Full Thread Device.
Returns
TRUE if a Full Thread Device, FALSE otherwise.
Referenced by Mle::BecomeChild(), Mle::HandleAdvertisement(), Mle::HandleChildIdResponse(), Mle::HandleParentResponse(), Mle::HandleStateChanged(), Mle::InformPreviousChannel(), Mle::PrepareAnnounceState(), Mle::Reattach(), Mle::SendChildIdRequest(), Mle::SendChildUpdateRequest(), Mle::SendChildUpdateResponse(), and Mle::SetStateChild().
IsSecureDataRequest()
bool IsSecureDataRequest (void) const inline
This method indicates whether or not the device uses secure IEEE 802.15.4 Data Request messages.
Returns
TRUE if using secure IEEE 802.15.4 Data Request messages, FALSE otherwise.
IsFullNetworkData()
bool IsFullNetworkData (void) const inline
This method indicates whether or not the device requests Full Network Data.
Returns
TRUE if requests Full Network Data, FALSE otherwise.
Referenced by Mle::HandleChildIdResponse(), Mle::HandleLeaderData(), and Mle::IsNetworkDataNewer().
IsMinimalEndDevice()
bool IsMinimalEndDevice (void) const inline
This method indicates whether or not the device is a Minimal End Device.
Returns
TRUE if the device is a Minimal End Device, FALSE otherwise.
GetMeshLocalPrefix()
const MeshLocalPrefix& GetMeshLocalPrefix (void) const inline
This method returns a pointer to the Mesh Local Prefix.
Returns
A reference to the Mesh Local Prefix.
Referenced by Mle::ApplyMeshLocalPrefix(), Mle::GetLeaderAddress(), Mle::GetServiceAloc(), Mle::IsMeshLocalAddress(), and Mle::SetMeshLocalPrefix().
SetMeshLocalPrefix()
void SetMeshLocalPrefix (const MeshLocalPrefix & aMeshLocalPrefix)
This method sets the Mesh Local Prefix.
Parameters
[in] aMeshLocalPrefix A reference to the Mesh Local Prefix.
References Mle::ApplyMeshLocalPrefix(), NetifUnicastAddress::GetAddress(), Mle::GetMeshLocalPrefix(), Mle::mLeaderAloc, Mle::mLinkLocalAllThreadNodes, Mle::mMeshLocal16, Mle::mMeshLocal64, Mle::mRealmLocalAllThreadNodes, OT_CHANGED_THREAD_ML_ADDR, OT_NOOP, Address::SetPrefix(), and VerifyOrExit.
Referenced by Mle::Mle().
ApplyMeshLocalPrefix()
void ApplyMeshLocalPrefix (void)
This method applies the Mesh Local Prefix.
References NetifMulticastAddress::GetAddress(), Mle::GetMeshLocalPrefix(), Mle::IsAttached(), Mle::IsDisabled(), Mle::IsLeader(), ot::Mac::kShortAddrInvalid, Mle::mLeaderAloc, Mle::mLinkLocalAllThreadNodes, Mle::mMeshLocal16, Mle::mMeshLocal64, Mle::mRealmLocalAllThreadNodes, OT_ARRAY_LENGTH, OT_CHANGED_THREAD_ML_ADDR, OT_NOOP, Address::SetMulticastNetworkPrefix(), and VerifyOrExit.
Referenced by Mle::SetMeshLocalPrefix(), and Mle::Start().
GetLinkLocalAddress()
const Ip6::Address& GetLinkLocalAddress (void) const inline
This method returns a reference to the Thread link-local address.
The Thread link local address is derived using IEEE802.15.4 Extended Address as Interface Identifier.
Returns
A reference to the Thread link local address.
UpdateLinkLocalAddress()
void UpdateLinkLocalAddress (void)
This method updates the link local address.
Call this method when the IEEE 802.15.4 Extended Address has changed.
References NetifUnicastAddress::GetAddress(), Mle::mLinkLocal64, OT_CHANGED_THREAD_LL_ADDR, and Address::SetIid().
Referenced by Mle::Enable().
GetLinkLocalAllThreadNodesAddress()
const Ip6::Address& GetLinkLocalAllThreadNodesAddress (void) const inline
This method returns a reference to the link-local all Thread nodes multicast address.
Returns
A reference to the link-local all Thread nodes multicast address.
GetRealmLocalAllThreadNodesAddress()
const Ip6::Address& GetRealmLocalAllThreadNodesAddress (void) const inline
This method returns a reference to the realm-local all Thread nodes multicast address.
Returns
A reference to the realm-local all Thread nodes multicast address.
GetParent()
Router& GetParent (void) inline
This method gets the parent when operating in End Device mode.
Returns
A reference to the parent.
Referenced by Mle::AppendAddressRegistration(), Mle::CheckReachability(), and Mle::HandleStateChanged().
GetParentCandidate()
Router& GetParentCandidate (void) inline
This method get the parent candidate.
The parent candidate is valid when attempting to attach to a new parent.
IsRoutingLocator()
bool IsRoutingLocator (const Ip6::Address & aAddress) const
This method indicates whether or not an IPv6 address is an RLOC.
Return values
TRUE If aAddress is an RLOC.
FALSE If aAddress is not an RLOC.
References Address::IsIidRoutingLocator(), and Mle::IsMeshLocalAddress().
Referenced by Mle::AppendAddressRegistration(), and Mle::HasUnregisteredAddress().
IsAnycastLocator()
bool IsAnycastLocator (const Ip6::Address & aAddress) const
This method indicates whether or not an IPv6 address is an ALOC.
Return values
TRUE If aAddress is an ALOC.
FALSE If aAddress is not an ALOC.
References Address::IsIidAnycastLocator(), and Mle::IsMeshLocalAddress().
Referenced by Mle::AppendAddressRegistration(), and Mle::HasUnregisteredAddress().
IsMeshLocalAddress()
bool IsMeshLocalAddress (const Ip6::Address & aAddress) const
This method indicates whether or not an IPv6 address is a Mesh Local Address.
Return values
TRUE If aAddress is a Mesh Local Address.
FALSE If aAddress is not a Mesh Local Address.
References Mle::GetMeshLocalPrefix(), and MeshLocalPrefix::kSize.
Referenced by Mle::IsAnycastLocator(), and Mle::IsRoutingLocator().
GetTimeout()
uint32_t GetTimeout (void) const inline
This method returns the MLE Timeout value.
Returns
The MLE Timeout value in seconds.
SetTimeout()
void SetTimeout (uint32_t aTimeout)
This method sets the MLE Timeout value.
Parameters
[in] aTimeout The Timeout value in seconds.
References Mle::IsChild(), ot::Mle::kMinTimeout, Mle::mTimeout, OT_NOOP, Mle::SendChildUpdateRequest(), and VerifyOrExit.
GetRloc16()
uint16_t GetRloc16 (void) const
This method returns the RLOC16 assigned to the Thread interface.
Returns
The RLOC16 assigned to the Thread interface.
Referenced by Mle::AppendSourceAddress(), Mle::CheckReachability(), Mle::GetLeaderAddress(), Mle::GetLocatorAddress(), Mle::GetServiceAloc(), Mle::HandleChildUpdateResponse(), Mle::HandleStateChanged(), Mle::Restore(), Mle::SetDeviceMode(), Mle::SetRloc16(), Mle::Start(), and Mle::Store().
GetMeshLocal16()
const Ip6::Address& GetMeshLocal16 (void) const inline
This method returns a reference to the RLOC assigned to the Thread interface.
Returns
A reference to the RLOC assigned to the Thread interface.
Referenced by Mle::CheckReachability().
GetMeshLocal64()
const Ip6::Address& GetMeshLocal64 (void) const inline
This method returns a reference to the ML-EID assigned to the Thread interface.
Returns
A reference to the ML-EID assigned to the Thread interface.
Referenced by Mle::AppendAddressRegistration(), Mle::CheckReachability(), and Mle::HasUnregisteredAddress().
GetLeaderId()
uint8_t GetLeaderId (void) const inline
This method returns the Router ID of the Leader.
Returns
The Router ID of the Leader.
Referenced by Mle::HandleAdvertisement(), and Mle::HandleLeaderData().
GetLeaderAddress()
otError GetLeaderAddress (Ip6::Address & aAddress) const
This method retrieves the Leader's RLOC.
Parameters
[out] aAddress A reference to the Leader's RLOC.
Return values
OT_ERROR_NONE Successfully retrieved the Leader's RLOC.
OT_ERROR_DETACHED The Thread interface is not currently attached to a Thread Partition.
References LeaderData::GetLeaderRouterId(), Mle::GetMeshLocalPrefix(), Mle::GetRloc16(), ot::Mac::kShortAddrInvalid, Mle::mLeaderData, OT_ERROR_DETACHED, OT_ERROR_NONE, Mle::Rloc16FromRouterId(), Address::SetToRoutingLocator(), and VerifyOrExit.
GetLeaderAloc()
otError GetLeaderAloc (Ip6::Address & aAddress) const inline
This method retrieves the Leader's ALOC.
Parameters
[out] aAddress A reference to the Leader's ALOC.
Return values
OT_ERROR_NONE Successfully retrieved the Leader's ALOC.
OT_ERROR_DETACHED The Thread interface is not currently attached to a Thread Partition.
References ot::Mle::kAloc16Leader.
Referenced by Mle::AddLeaderAloc().
GetCommissionerAloc()
otError GetCommissionerAloc (Ip6::Address & aAddress, uint16_t aSessionId) const inline
This method computes the Commissioner's ALOC.
Parameters
[out] aAddress A reference to the Commissioner's ALOC.
[in] aSessionId Commissioner session id.
Return values
OT_ERROR_NONE Successfully retrieved the Commissioner's ALOC.
OT_ERROR_DETACHED The Thread interface is not currently attached to a Thread Partition.
GetServiceAloc()
otError GetServiceAloc (uint8_t aServiceId, Ip6::Address & aAddress) const
This method retrieves the Service ALOC for given Service ID.
Parameters
[in] aServiceId Service ID to get ALOC for.
[out] aAddress A reference to the Service ALOC.
Return values
OT_ERROR_NONE Successfully retrieved the Service ALOC.
OT_ERROR_DETACHED The Thread interface is not currently attached to a Thread Partition.
References Mle::GetMeshLocalPrefix(), Mle::GetRloc16(), ot::Mac::kShortAddrInvalid, OT_ERROR_DETACHED, OT_ERROR_NONE, Mle::ServiceAlocFromId(), Address::SetToAnycastLocator(), and VerifyOrExit.
Referenced by Mle::HandleStateChanged().
AddLeaderAloc()
otError AddLeaderAloc (void)
This method adds Leader's ALOC to its Thread interface.
Return values
OT_ERROR_NONE Successfully added the Leader's ALOC.
OT_ERROR_BUSY The Leader's ALOC address was already added.
OT_ERROR_INVALID_STATE The device's role is not Leader.
References NetifUnicastAddress::GetAddress(), Mle::GetLeaderAloc(), Mle::IsLeader(), Mle::mLeaderAloc, OT_ERROR_INVALID_STATE, OT_ERROR_NONE, SuccessOrExit, and VerifyOrExit.
GetLeaderData()
const LeaderData & GetLeaderData (void)
This method returns the most recently received Leader Data.
Returns
A reference to the most recently received Leader Data.
References Mle::mLeaderData, LeaderData::SetDataVersion(), and LeaderData::SetStableDataVersion().
ChildIdFromRloc16()
static uint16_t ChildIdFromRloc16 (uint16_t aRloc16) inline static
This method derives the Child ID from a given RLOC16.
Parameters
[in] aRloc16 The RLOC16 value.
Returns
The Child ID portion of an RLOC16.
References ot::Mle::kMaxChildId.
RouterIdFromRloc16()
static uint8_t RouterIdFromRloc16 (uint16_t aRloc16) inline static
This method derives the Router ID portion from a given RLOC16.
Parameters
[in] aRloc16 The RLOC16 value.
Returns
The Router ID portion of an RLOC16.
References ot::Mle::kRouterIdOffset.
Referenced by Mle::HandleChildUpdateResponse(), MeshForwarder::PrepareDataFrame(), and Mle::Restore().
RouterIdMatch()
static bool RouterIdMatch (uint16_t aRloc16A, uint16_t aRloc16B) inline static
This method returns whether the two RLOC16 have the same Router ID.
Parameters
[in] aRloc16A The first RLOC16 value.
[in] aRloc16B The second RLOC16 value.
Returns
true if the two RLOC16 have the same Router ID, false otherwise.
ServiceIdFromAloc()
static uint8_t ServiceIdFromAloc (uint16_t aAloc16) inline static
This method returns the Service ID corresponding to a Service ALOC16.
Parameters
[in] aAloc16 The Servicer ALOC16 value.
Returns
The Service ID corresponding to given ALOC16.
References ot::Mle::kAloc16ServiceStart.
Referenced by Mle::HandleStateChanged().
ServiceAlocFromId()
static uint16_t ServiceAlocFromId (uint8_t aServiceId) inline static
This method returns the Service Aloc corresponding to a Service ID.
Parameters
[in] aServiceId The Service ID value.
Returns
The Service ALOC16 corresponding to given ID.
References ot::Mle::kAloc16ServiceStart.
Referenced by Mle::GetServiceAloc(), and NetworkData::RemoveTemporaryData().
CommissionerAloc16FromId()
static uint16_t CommissionerAloc16FromId (uint16_t aSessionId) inline static
This method returns the Commissioner Aloc corresponding to a Commissioner Session ID.
Parameters
[in] aSessionId The Commissioner Session ID value.
Returns
The Commissioner ALOC16 corresponding to given ID.
References ot::Mle::kAloc16CommissionerMask, and ot::Mle::kAloc16CommissionerStart.
Rloc16FromRouterId()
static uint16_t Rloc16FromRouterId (uint8_t aRouterId) inline static
This method derives RLOC16 from a given Router ID.
Parameters
[in] aRouterId The Router ID value.
Returns
The RLOC16 corresponding to the given Router ID.
References ot::Mle::kRouterIdOffset.
Referenced by LeaderBase::GetBackboneRouterPrimary(), Mle::GetLeaderAddress(), and Mle::Restore().
IsActiveRouter()
static bool IsActiveRouter (uint16_t aRloc16) inline static
This method indicates whether or not aRloc16 refers to an active router.
Parameters
[in] aRloc16 The RLOC16 value.
Return values
TRUE If aRloc16 refers to an active router.
FALSE If aRloc16 does not refer to an active router.
Referenced by Mle::IsBetterParent(), MeshForwarder::PrepareDataFrame(), Mle::Restore(), Mle::Start(), and MeshForwarder::UpdateNeighborOnSentFrame().
GetMessageQueue()
const MessageQueue& GetMessageQueue (void) const inline
This method returns a reference to the send queue.
Returns
A reference to the send queue.
RemoveDelayedDataResponseMessage()
void RemoveDelayedDataResponseMessage (void)
This method frees multicast MLE Data Response from Delayed Message Queue if any.
References MessageQueue::Dequeue(), Message::Free(), MessageQueue::GetHead(), Message::GetNext(), Message::GetSubType(), Message::kSubTypeMleDataResponse, Mle::LogMleMessage(), Mle::mDelayedResponses, Mle::DelayedResponseMetadata::mDestination, and Mle::DelayedResponseMetadata::ReadFrom().
RoleToString()
const char * RoleToString (DeviceRole aRole) static
This method converts a device role into a human-readable string.
References ot::Mle::kAttachAny, ot::Mle::kAttachBetter, ot::Mle::kAttachSame1, ot::Mle::kAttachSame2, ot::Mle::kAttachSameDowngrade, Mle::kAttachStateAnnounce, Mle::kAttachStateChildIdRequest, Mle::kAttachStateIdle, Mle::kAttachStateParentRequestReed, Mle::kAttachStateParentRequestRouter, Mle::kAttachStateProcessAnnounce, Mle::kAttachStateStart, Mle::kReattachActive, Mle::kReattachPending, Mle::kReattachStart, Mle::kReattachStop, ot::Mle::kRoleChild, ot::Mle::kRoleDetached, ot::Mle::kRoleDisabled, ot::Mle::kRoleLeader, and ot::Mle::kRoleRouter.
Referenced by Mle::SetRole().
GetCounters()
const otMleCounters& GetCounters (void) const inline
This method gets the MLE counters.
Returns
A reference to the MLE counters.
ResetCounters()
void ResetCounters (void) inline
This method resets the MLE counters.
Referenced by Mle::Mle().
RegisterParentResponseStatsCallback()
void RegisterParentResponseStatsCallback (otThreadParentResponseCallback aCallback, void * aContext)
This function registers the client callback that is called when processing an MLE Parent Response message.
Parameters
[in] aCallback A pointer to a function that is called to deliver MLE Parent Response data.
[in] aContext A pointer to application-specific context.
References Mle::mParentResponseCb, and Mle::mParentResponseCbContext.
RequestShorterChildIdRequest()
void RequestShorterChildIdRequest (void)
This method requests MLE layer to prepare and send a shorter version of Child ID Request message by only including the mesh-local IPv6 address in the Address Registration TLV.
This method should be called when a previous MLE Child ID Request message would require fragmentation at 6LoWPAN layer.
References Mle::kAppendMeshLocalOnly, Mle::kAttachStateChildIdRequest, Mle::mAddressRegistrationMode, Mle::mAttachState, and Mle::SendChildIdRequest().
GetLocatorAddress()
otError GetLocatorAddress (Ip6::Address & aAddress, uint16_t aLocator) const
This method gets the RLOC or ALOC of a given RLOC16 or ALOC16.
Parameters
[out] aAddress A reference to the RLOC or ALOC.
[in] aLocator RLOC16 or ALOC16.
Return values
OT_ERROR_NONE If got the RLOC or ALOC successfully.
OT_ERROR_DETACHED If device is detached.
References NetifUnicastAddress::GetAddress(), Mle::GetRloc16(), ot::Mac::kShortAddrInvalid, Mle::mMeshLocal16, OT_ERROR_DETACHED, OT_ERROR_NONE, Address::SetLocator(), and VerifyOrExit.
GenerateRandom()
void GenerateRandom (void)
This method generates a cryptographically secure random sequence to populate the challenge data.
References ot::Random::Crypto::FillBuffer(), and ot::Mle::kMaxChallengeSize.
Referenced by Mle::SendChildUpdateRequest(), and Mle::SendParentRequest().
Matches()
bool Matches (const uint8_t * aBuffer, uint8_t aLength) const
This method indicates whether the Challenge matches a given buffer.
Parameters
[in] aBuffer A pointer to a buffer to compare with the Challenge.
[in] aLength Length of aBuffer (in bytes).
Return values
TRUE If the Challenge matches the given buffer.
FALSE If the Challenge does not match the given buffer.
operator==()
bool operator== (const Challenge & aOther) const inline
This method indicates whether two Challenge data byte sequences are equal or not.
Parameters
[in] aOther Another Challenge data to compare.
Return values
TRUE If the two Challenges match.
FALSE If the two Challenges do not match.
References Mle::Challenge::mBuffer, and Mle::Challenge::mLength.
NewMleMessage()
Message * NewMleMessage (void) protected
This method allocates a new message buffer for preparing an MLE message.
Returns
A pointer to the message or NULL if insufficient message buffers are available.
References Mle::kMleMessagePriority, Message::kSubTypeMleGeneral, Mle::mSocket, UdpSocket::NewMessage(), OT_NOOP, Message::SetSubType(), and VerifyOrExit.
Referenced by Mle::Discover(), Mle::SendAnnounce(), Mle::SendChildIdRequest(), Mle::SendChildUpdateRequest(), Mle::SendChildUpdateResponse(), Mle::SendDataRequest(), and Mle::SendParentRequest().
SetRole()
void SetRole (DeviceRole aRole) protected
This method sets the device role.
Parameters
[in] aRole A device role.
References Mle::IsChild(), ot::Mle::kRoleChild, ot::Mle::kRoleDetached, ot::Mle::kRoleDisabled, ot::Mle::kRoleLeader, ot::Mle::kRoleRouter, Neighbor::kStateInvalid, otMleCounters::mChildRole, Mle::mCounters, otMleCounters::mDetachedRole, otMleCounters::mDisabledRole, otMleCounters::mLeaderRole, Mle::mParent, Mle::mRole, otMleCounters::mRouterRole, OT_CHANGED_THREAD_ROLE, OT_UNUSED_VARIABLE, otLogNoteMle, Mle::RoleToString(), Neighbor::SetState(), and SuccessOrExit.
Referenced by Mle::SetStateChild(), Mle::SetStateDetached(), and Mle::Stop().
SetAttachState()
void SetAttachState (AttachState aState) protected
This method sets the attach state
Parameters
[in] aState An attach state
References Mle::mAttachState, OT_NOOP, otLogInfoMle, and VerifyOrExit.
Referenced by Mle::BecomeChild(), Mle::HandleAnnounce(), Mle::HandleAttachTimer(), Mle::Reattach(), Mle::SetStateChild(), and Mle::SetStateDetached().
AppendHeader()
otError AppendHeader (Message & aMessage, Header::Command aCommand) protected
This method appends an MLE header to a message.
Parameters
[in] aMessage A reference to the message.
[in] aCommand The MLE Command Type.
Return values
OT_ERROR_NONE Successfully appended the header.
OT_ERROR_NO_BUFS Insufficient buffers available to append the header.
References Message::Append(), Header::GetLength(), Header::Init(), Header::kCommandDiscoveryRequest, Header::kCommandDiscoveryResponse, Header::kNoSecurity, OT_ERROR_NONE, Header::SetCommand(), Header::SetKeyIdMode2(), Header::SetSecuritySuite(), and SuccessOrExit.
Referenced by Mle::Discover(), Mle::SendAnnounce(), Mle::SendChildIdRequest(), Mle::SendChildUpdateRequest(), Mle::SendChildUpdateResponse(), Mle::SendDataRequest(), and Mle::SendParentRequest().
AppendSourceAddress()
otError AppendSourceAddress (Message & aMessage) protected
This method appends a Source Address TLV to a message.
Parameters
[in] aMessage A reference to the message.
Return values
OT_ERROR_NONE Successfully appended the Source Address TLV.
OT_ERROR_NO_BUFS Insufficient buffers available to append the Source Address TLV.
References Tlv::AppendUint16Tlv(), Mle::GetRloc16(), and Tlv::kSourceAddress.
Referenced by Mle::SendChildUpdateRequest(), and Mle::SendChildUpdateResponse().
AppendMode()
otError AppendMode (Message & aMessage, DeviceMode aMode) protected
This method appends a Mode TLV to a message.
Parameters
[in] aMessage A reference to the message.
[in] aMode The Device Mode.
Return values
OT_ERROR_NONE Successfully appended the Mode TLV.
OT_ERROR_NO_BUFS Insufficient buffers available to append the Mode TLV.
References Tlv::AppendUint8Tlv(), DeviceMode::Get(), and Tlv::kMode.
Referenced by Mle::SendChildIdRequest(), Mle::SendChildUpdateRequest(), and Mle::SendParentRequest().
AppendTimeout()
otError AppendTimeout (Message & aMessage, uint32_t aTimeout) protected
This method appends a Timeout TLV to a message.
Parameters
[in] aMessage A reference to the message.
[in] aTimeout The Timeout value.
Return values
OT_ERROR_NONE Successfully appended the Timeout TLV.
OT_ERROR_NO_BUFS Insufficient buffers available to append the Timeout TLV.
References Tlv::AppendUint32Tlv(), and Tlv::kTimeout.
Referenced by Mle::SendChildIdRequest(), Mle::SendChildUpdateRequest(), and Mle::SendChildUpdateResponse().
AppendChallenge() [1/2]
otError AppendChallenge (Message & aMessage, const uint8_t * aChallenge, uint8_t aChallengeLength) protected
This method appends a Challenge TLV to a message.
Parameters
[in] aMessage A reference to the message.
[in] aChallenge A pointer to the Challenge value.
[in] aChallengeLength The length of the Challenge value in bytes.
Return values
OT_ERROR_NONE Successfully appended the Challenge TLV.
OT_ERROR_NO_BUFS Insufficient buffers available to append the Challenge TLV.
References Tlv::AppendTlv(), and Tlv::kChallenge.
Referenced by Mle::SendChildUpdateRequest(), and Mle::SendParentRequest().
AppendChallenge() [2/2]
otError AppendChallenge (Message & aMessage, const Challenge & aChallenge) protected
This method appends a Challenge TLV to a message.
Parameters
[in] aMessage A reference to the message.
[in] aChallenge A reference to the Challenge data.
Return values
OT_ERROR_NONE Successfully appended the Challenge TLV.
OT_ERROR_NO_BUFS Insufficient buffers available to append the Challenge TLV.
References Tlv::AppendTlv(), Tlv::kChallenge, Mle::Challenge::mBuffer, and Mle::Challenge::mLength.
ReadChallenge()
otError ReadChallenge (const Message & aMessage, Challenge & aChallenge) protected
This method reads Challenge TLV from a message.
Parameters
[in] aMessage A reference to the message.
[out] aChallenge A reference to the Challenge data where to output the read value.
Return values
OT_ERROR_NONE Successfully read the Challenge TLV.
OT_ERROR_NOT_FOUND Challenge TLV was not found in the message.
OT_ERROR_PARSE Challenge TLV was found but could not be parsed.
References Tlv::kChallenge, and Mle::ReadChallengeOrResponse().
Referenced by Mle::HandleChildUpdateRequest(), and Mle::HandleParentResponse().
AppendResponse()
otError AppendResponse (Message & aMessage, const Challenge & aResponse) protected
This method appends a Response TLV to a message.
Parameters
[in] aMessage A reference to the message.
[in] aResponse A reference to the Response data.
Return values
OT_ERROR_NONE Successfully appended the Response TLV.
OT_ERROR_NO_BUFS Insufficient buffers available to append the Response TLV.
References Tlv::AppendTlv(), Tlv::kResponse, Mle::Challenge::mBuffer, and Mle::Challenge::mLength.
Referenced by Mle::SendChildIdRequest(), and Mle::SendChildUpdateResponse().
ReadResponse()
otError ReadResponse (const Message & aMessage, Challenge & aResponse) protected
This method reads Response TLV from a message.
Parameters
[in] aMessage A reference to the message.
[out] aResponse A reference to the Response data where to output the read value.
Return values
OT_ERROR_NONE Successfully read the Response TLV.
OT_ERROR_NOT_FOUND Response TLV was not found in the message.
OT_ERROR_PARSE Response TLV was found but could not be parsed.
References Tlv::kResponse, and Mle::ReadChallengeOrResponse().
Referenced by Mle::HandleChildUpdateResponse(), and Mle::HandleParentResponse().
AppendLinkFrameCounter()
otError AppendLinkFrameCounter (Message & aMessage) protected
This method appends a Link Frame Counter TLV to a message.
Parameters
[in] aMessage A reference to the message.
Return values
OT_ERROR_NONE Successfully appended the Link Frame Counter TLV.
OT_ERROR_NO_BUFS Insufficient buffers available to append the Link Frame Counter TLV.
References Tlv::AppendUint32Tlv(), and Tlv::kLinkFrameCounter.
Referenced by Mle::SendChildIdRequest(), and Mle::SendChildUpdateResponse().
AppendMleFrameCounter()
otError AppendMleFrameCounter (Message & aMessage) protected
This method appends an MLE Frame Counter TLV to a message.
Parameters
[in] aMessage A reference to the message.
Return values
OT_ERROR_NONE Successfully appended the Frame Counter TLV.
OT_ERROR_NO_BUFS Insufficient buffers available to append the MLE Frame Counter TLV.
References Tlv::AppendUint32Tlv(), and Tlv::kMleFrameCounter.
Referenced by Mle::SendChildIdRequest(), and Mle::SendChildUpdateResponse().
AppendAddress16()
otError AppendAddress16 (Message & aMessage, uint16_t aRloc16) protected
This method appends an Address16 TLV to a message.
Parameters
[in] aMessage A reference to the message.
[in] aRloc16 The RLOC16 value.
Return values
OT_ERROR_NONE Successfully appended the Address16 TLV.
OT_ERROR_NO_BUFS Insufficient buffers available to append the Address16 TLV.
References Tlv::AppendUint16Tlv(), and Tlv::kAddress16.
AppendNetworkData()
otError AppendNetworkData (Message & aMessage, bool aStableOnly) protected
This method appends a Network Data TLV to the message.
Parameters
[in] aMessage A reference to the message.
[in] aStableOnly TRUE to append stable data, FALSE otherwise.
Return values
OT_ERROR_NONE Successfully appended the Network Data TLV.
OT_ERROR_NO_BUFS Insufficient buffers available to append the Network Data TLV.
References Tlv::AppendTlv(), NetworkData::kMaxSize, Tlv::kNetworkData, Mle::mRetrieveNewNetworkData, OT_ERROR_INVALID_STATE, OT_ERROR_NONE, and VerifyOrExit.
AppendTlvRequest()
otError AppendTlvRequest (Message & aMessage, const uint8_t * aTlvs, uint8_t aTlvsLength) protected
This method appends a TLV Request TLV to a message.
Parameters
[in] aMessage A reference to the message.
[in] aTlvs A pointer to the list of TLV types.
[in] aTlvsLength The number of TLV types in aTlvs
Return values
OT_ERROR_NONE Successfully appended the TLV Request TLV.
OT_ERROR_NO_BUFS Insufficient buffers available to append the TLV Request TLV.
References Tlv::AppendTlv(), and Tlv::kTlvRequest.
Referenced by Mle::SendChildIdRequest(), and Mle::SendDataRequest().
ReadTlvRequest()
otError ReadTlvRequest (const Message & aMessage, RequestedTlvs & aRequestedTlvs) protected
This method reads TLV Request TLV from a message.
Parameters
[in] aMessage A reference to the message.
[out] aRequestedTlvs A reference to output the read list of requested TLVs.
Return values
OT_ERROR_NONE Successfully read the TLV.
OT_ERROR_NOT_FOUND TLV was not found in the message.
OT_ERROR_PARSE TLV was found but could not be parsed.
References Tlv::GetValueOffset(), Tlv::kTlvRequest, Mle::RequestedTlvs::mNumTlvs, Mle::RequestedTlvs::mTlvs, Message::Read(), and SuccessOrExit.
Referenced by Mle::HandleChildUpdateRequest().
AppendLeaderData()
otError AppendLeaderData (Message & aMessage) protected
This method appends a Leader Data TLV to a message.
Parameters
[in] aMessage A reference to the message.
Return values
OT_ERROR_NONE Successfully appended the Leader Data TLV.
OT_ERROR_NO_BUFS Insufficient buffers available to append the Leader Data TLV.
References Tlv::AppendTo(), LeaderDataTlv::Init(), Mle::mLeaderData, LeaderDataTlv::Set(), LeaderData::SetDataVersion(), and LeaderData::SetStableDataVersion().
Referenced by Mle::SendChildUpdateRequest(), and Mle::SendChildUpdateResponse().
ReadLeaderData()
otError ReadLeaderData (const Message & aMessage, LeaderData & aLeaderData) protected
This method reads Leader Data TLV from a message.
Parameters
[in] aMessage A reference to the message.
[out] aLeaderData A reference to output the Leader Data.
Return values
OT_ERROR_NONE Successfully read the TLV.
OT_ERROR_NOT_FOUND TLV was not found in the message.
OT_ERROR_PARSE TLV was found but could not be parsed.
References LeaderDataTlv::Get(), Tlv::GetTlv(), LeaderDataTlv::IsValid(), Tlv::kLeaderData, OT_ERROR_PARSE, SuccessOrExit, and VerifyOrExit.
Referenced by Mle::HandleAdvertisement(), Mle::HandleChildIdResponse(), Mle::HandleLeaderData(), and Mle::HandleParentResponse().
AppendScanMask()
otError AppendScanMask (Message & aMessage, uint8_t aScanMask) protected
This method appends a Scan Mask TLV to a message.
Parameters
[in] aMessage A reference to the message.
[in] aScanMask The Scan Mask value.
Return values
OT_ERROR_NONE Successfully appended the Scan Mask TLV.
OT_ERROR_NO_BUFS Insufficient buffers available to append the Scan Mask TLV.
References Tlv::AppendUint8Tlv(), and Tlv::kScanMask.
Referenced by Mle::SendParentRequest().
AppendStatus()
otError AppendStatus (Message & aMessage, StatusTlv::Status aStatus) protected
This method appends a Status TLV to a message.
Parameters
[in] aMessage A reference to the message.
[in] aStatus The Status value.
Return values
OT_ERROR_NONE Successfully appended the Status TLV.
OT_ERROR_NO_BUFS Insufficient buffers available to append the Status TLV.
References Tlv::AppendUint8Tlv(), and Tlv::kStatus.
Referenced by Mle::SendChildUpdateResponse().
AppendLinkMargin()
otError AppendLinkMargin (Message & aMessage, uint8_t aLinkMargin) protected
This method appends a Link Margin TLV to a message.
Parameters
[in] aMessage A reference to the message.
[in] aLinkMargin The Link Margin value.
Return values
OT_ERROR_NONE Successfully appended the Link Margin TLV.
OT_ERROR_NO_BUFS Insufficient buffers available to append the Link Margin TLV.
References Tlv::AppendUint8Tlv(), and Tlv::kLinkMargin.
AppendVersion()
otError AppendVersion (Message & aMessage) protected
This method appends a Version TLV to a message.
Parameters
[in] aMessage A reference to the message.
Return values
OT_ERROR_NONE Successfully appended the Version TLV.
OT_ERROR_NO_BUFS Insufficient buffers available to append the Version TLV.
References Tlv::AppendUint16Tlv(), ot::Mle::kThreadVersion, and Tlv::kVersion.
Referenced by Mle::SendChildIdRequest(), and Mle::SendParentRequest().
AppendAddressRegistration()
otError AppendAddressRegistration (Message & aMessage, AddressRegistrationMode aMode = kAppendAllAddresses) protected
This method appends an Address Registration TLV to a message.
Parameters
[in] aMessage A reference to the message.
[in] aMode Determines which addresses to include in the TLV (see AddressRegistrationMode).
Return values
OT_ERROR_NONE Successfully appended the Address Registration TLV.
OT_ERROR_NO_BUFS Insufficient buffers available to append the Address Registration TLV.
References Message::Append(), Tlv::AppendUint16Tlv(), Message::GetLength(), AddressRegistrationEntry::GetLength(), Mle::GetMeshLocal64(), LinkedListEntry< Type >::GetNext(), Mle::GetParent(), Mle::IsAnycastLocator(), Address::IsMulticastLargerThanRealmLocal(), Mle::IsRoutingLocator(), Mle::IsRxOnWhenIdle(), Tlv::kAddressRegistration, Mle::kAppendMeshLocalOnly, ot::Mle::kMeshLocalPrefixContextId, Tlv::kXtalAccuracy, Context::mContextId, OPENTHREAD_CONFIG_MLE_IP_ADDRS_TO_REGISTER, OPENTHREAD_CONFIG_THREAD_VERSION, OT_ERROR_NONE, OT_NOOP, OT_THREAD_VERSION_1_2, otPlatTimeGetXtalAccuracy(), AddressRegistrationEntry::SetContextId(), AddressRegistrationEntry::SetIid(), AddressRegistrationEntry::SetIp6Address(), Tlv::SetLength(), Tlv::SetType(), AddressRegistrationEntry::SetUncompressed(), SuccessOrExit, VerifyOrExit, and Message::Write().
Referenced by Mle::SendChildIdRequest(), Mle::SendChildUpdateRequest(), and Mle::SendChildUpdateResponse().
AppendActiveTimestamp()
otError AppendActiveTimestamp (Message & aMessage) protected
This method appends a Active Timestamp TLV to a message.
Parameters
[in] aMessage A reference to the message.
Return values
OT_ERROR_NONE Successfully appended the Active Timestamp TLV.
OT_ERROR_NO_BUFS Insufficient buffers available to append the Active Timestamp TLV.
References Tlv::AppendTo(), ActiveTimestampTlv::Init(), OT_ERROR_NONE, and VerifyOrExit.
Referenced by Mle::SendAnnounce(), Mle::SendChildIdRequest(), and Mle::SendDataRequest().
AppendPendingTimestamp()
otError AppendPendingTimestamp (Message & aMessage) protected
This method appends a Pending Timestamp TLV to a message.
Parameters
[in] aMessage A reference to the message.
Return values
OT_ERROR_NONE Successfully appended the Pending Timestamp TLV.
OT_ERROR_NO_BUFS Insufficient buffers available to append the Pending Timestamp TLV.
References Tlv::AppendTo(), Timestamp::GetSeconds(), PendingTimestampTlv::Init(), OT_ERROR_NONE, and VerifyOrExit.
Referenced by Mle::SendChildIdRequest(), and Mle::SendDataRequest().
CheckReachability()
otError CheckReachability (uint16_t aMeshDest, Ip6::Header & aIp6Header) protected
This method checks if the destination is reachable.
Parameters
[in] aMeshDest The RLOC16 of the destination.
[in] aIp6Header The IPv6 header of the message.
Return values
OT_ERROR_NONE The destination is reachable.
OT_ERROR_NO_ROUTE The destination is not reachable and the message should be dropped.
References Mle::BecomeChild(), Message::Free(), LinkQualityInfo::GetAverageRss(), Header::GetDestination(), Neighbor::GetLinkInfo(), Mle::GetMeshLocal16(), Mle::GetMeshLocal64(), TimerMilli::GetNow(), OwnerLocator::GetOwner(), Mle::GetParent(), MessageInfo::GetPeerAddr(), Neighbor::GetRloc16(), Mle::GetRloc16(), ot::Random::NonCrypto::GetUint32InRange(), Mle::IsChild(), ot::Mle::kAttachAny, Mle::kParentSearchBackoffInterval, Mle::kParentSearchCheckInterval, Mle::kParentSearchJitterInterval, Mle::kParentSearchRssThreadhold, ot::Ip6::kProtoNone, ot::Mac::kShortAddrInvalid, Mle::mCounters, Mle::mParent, otMleCounters::mParentChanges, OT_ERROR_NO_BUFS, OT_ERROR_NO_ROUTE, OT_ERROR_NONE, OT_NOOP, OT_RADIO_RSSI_INVALID, otLogInfoMle, otLogNoteMle, otLogWarnMle, otThreadErrorToString(), Message::SetLength(), Address::SetLocator(), MessageInfo::SetPeerAddr(), MessageInfo::SetSockAddr(), SuccessOrExit, and VerifyOrExit.
GetNeighbor() [1/4]
Neighbor * GetNeighbor (const Mac::Address & aAddress) protected
This method returns a pointer to the neighbor object.
Parameters
[in] aAddress A reference to the MAC address.
Returns
A pointer to the neighbor object.
References Address::GetExtended(), Address::GetShort(), Address::GetType(), Address::kTypeExtended, and Address::kTypeShort.
Referenced by Mle::HandleUdpReceive().
GetNeighbor() [2/4]
Neighbor * GetNeighbor (Mac::ShortAddress aAddress) protected
This method returns a pointer to the neighbor object.
Parameters
[in] aAddress A reference to the MAC short address.
Returns
A pointer to the neighbor object.
References Neighbor::GetRloc16(), Neighbor::IsStateValid(), Neighbor::IsStateValidOrRestoring(), Mle::mParent, and Mle::mParentCandidate.
GetNeighbor() [3/4]
Neighbor * GetNeighbor (const Mac::ExtAddress & aAddress) protected
This method returns a pointer to the neighbor object.
Parameters
[in] aAddress A reference to the MAC extended address.
Returns
A pointer to the neighbor object.
References Neighbor::GetExtAddress(), Neighbor::IsStateValid(), Neighbor::IsStateValidOrRestoring(), Mle::mParent, and Mle::mParentCandidate.
GetNeighbor() [4/4]
Neighbor* GetNeighbor (const Ip6::Address & aAddress) inline protected
This method returns a pointer to the neighbor object.
Parameters
[in] aAddress A reference to the IPv6 address.
Returns
A pointer to the neighbor object.
References OT_UNUSED_VARIABLE.
GetNextHop()
uint16_t GetNextHop (uint16_t aDestination) const protected
This method returns the next hop towards an RLOC16 destination.
Parameters
[in] aDestination The RLOC16 of the destination.
Returns
A RLOC16 of the next hop if a route is known, kInvalidRloc16 otherwise.
References Neighbor::GetRloc16(), Neighbor::IsStateValid(), ot::Mac::kShortAddrInvalid, Mle::mParent, and OT_UNUSED_VARIABLE.
SendDataRequest()
otError SendDataRequest (const Ip6::Address & aDestination, const uint8_t * aTlvs, uint8_t aTlvsLength, uint16_t aDelay) protected
This method generates an MLE Data Request message.
Parameters
[in] aDestination A reference to the IPv6 address of the destination.
[in] aTlvs A pointer to requested TLV types.
[in] aTlvsLength The number of TLV types in aTlvs.
[in] aDelay Delay in milliseconds before the Data Request message is sent.
Return values
OT_ERROR_NONE Successfully generated an MLE Data Request message.
OT_ERROR_NO_BUFS Insufficient buffers to generate the MLE Data Request message.
References Mle::AddDelayedResponse(), Mle::AppendActiveTimestamp(), Mle::AppendHeader(), Mle::AppendPendingTimestamp(), Mle::AppendTlvRequest(), Message::Free(), Mle::IsChild(), Mle::IsRxOnWhenIdle(), Mle::kChildUpdateRequestNone, Header::kCommandDataRequest, Mle::kDataRequestActive, DataPollSender::kDefaultFastPolls, Mle::LogMleMessage(), Mle::mChildUpdateRequestState, Mle::mDataRequestState, Mle::NewMleMessage(), OT_ERROR_NO_BUFS, OT_ERROR_NONE, Mle::ScheduleMessageTransmissionTimer(), Mle::SendMessage(), SuccessOrExit, and VerifyOrExit.
Referenced by Mle::HandleAdvertisement(), Mle::HandleLeaderData(), and Mle::HandleMessageTransmissionTimer().
SendChildUpdateRequest()
otError SendChildUpdateRequest (void) protected
This method generates an MLE Child Update Request message.
Return values
OT_ERROR_NONE Successfully generated an MLE Child Update Request message.
OT_ERROR_NO_BUFS Insufficient buffers to generate the MLE Child Update Request message.
References Mle::AppendAddressRegistration(), Mle::AppendChallenge(), Mle::AppendHeader(), Mle::AppendLeaderData(), Mle::AppendMode(), Mle::AppendSourceAddress(), Mle::AppendTimeout(), Mle::BecomeDetached(), ExitNow, Message::Free(), Mle::Challenge::GenerateRandom(), Neighbor::GetExtAddress(), Mle::IsFullThreadDevice(), Mle::IsRxOnWhenIdle(), Neighbor::IsStateValidOrRestoring(), Mle::kChildUpdateRequestActive, Header::kCommandChildUpdateRequest, ot::Mle::kRoleChild, ot::Mle::kRoleDetached, ot::Mle::kRoleDisabled, ot::Mle::kRoleLeader, ot::Mle::kRoleRouter, Message::kSubTypeMleChildUpdateRequest, Mle::LogMleMessage(), Mle::mChildUpdateRequestState, Mle::mDeviceMode, Mle::mParent, Mle::mParentRequestChallenge, Mle::mRole, Mle::mTimeout, Mle::NewMleMessage(), OT_ASSERT, OT_ERROR_NO_BUFS, OT_ERROR_NONE, OT_UNREACHABLE_CODE, otLogWarnMle, Mle::ScheduleMessageTransmissionTimer(), Mle::SendMessage(), Message::SetSubType(), Address::SetToLinkLocalAddress(), SuccessOrExit, and VerifyOrExit.
Referenced by Mle::HandleMessageTransmissionTimer(), Mle::SendChildUpdateResponse(), Mle::SetDeviceMode(), Mle::SetTimeout(), and Mle::Start().
SendChildUpdateResponse()
otError SendChildUpdateResponse (const uint8_t * aTlvs, uint8_t aNumTlvs, const Challenge & aChallenge) protected
This method generates an MLE Child Update Response message.
Parameters
[in] aTlvs A pointer to requested TLV types.
[in] aNumTlvs The number of TLV types in aTlvs.
[in] aChallenge The Challenge for the response.
Return values
OT_ERROR_NONE Successfully generated an MLE Child Update Response message.
OT_ERROR_NO_BUFS Insufficient buffers to generate the MLE Child Update Response message.
References Mle::AppendAddressRegistration(), Mle::AppendHeader(), Mle::AppendLeaderData(), Mle::AppendLinkFrameCounter(), Mle::AppendMleFrameCounter(), Mle::AppendResponse(), Mle::AppendSourceAddress(), Mle::AppendStatus(), Mle::AppendTimeout(), Message::Free(), Neighbor::GetExtAddress(), Mle::HasUnregisteredAddress(), Mle::IsFullThreadDevice(), Tlv::kAddressRegistration, Mle::kAppendMeshLocalOnly, Header::kCommandChildUpdateResponse, StatusTlv::kError, Tlv::kLinkFrameCounter, Tlv::kMleFrameCounter, Tlv::kResponse, Tlv::kStatus, Tlv::kTimeout, Mle::LogMleMessage(), Mle::mParent, Mle::mTimeout, Mle::NewMleMessage(), OT_ERROR_NO_BUFS, OT_ERROR_NONE, Mle::SendChildUpdateRequest(), Mle::SendMessage(), Address::SetToLinkLocalAddress(), SuccessOrExit, and VerifyOrExit.
Referenced by Mle::HandleChildUpdateRequest().
SendMessage()
otError SendMessage (Message & aMessage, const Ip6::Address & aDestination) protected
This method submits an MLE message to the UDP socket.
Parameters
[in] aMessage A reference to the message.
[in] aDestination A reference to the IPv6 address of the destination.
Return values
OT_ERROR_NONE Successfully submitted the MLE message.
OT_ERROR_NO_BUFS Insufficient buffers to form the rest of the MLE message.
References Message::Append(), AesCcm::Finalize(), KeyManager::GenerateNonce(), NetifUnicastAddress::GetAddress(), Header::GetBytes(), Header::GetHeaderLength(), Header::GetLength(), Message::GetLength(), Message::GetOffset(), Header::GetSecuritySuite(), AesCcm::Header(), AesCcm::Init(), Header::k154Security, Mle::kMleHopLimit, KeyManager::kNonceSize, Frame::kSecEncMic32, ot::Mle::kUdpPort, Mle::mLinkLocal64, Message::MoveOffset(), Mle::mSocket, OT_ASSERT, OT_ERROR_NONE, AesCcm::Payload(), Message::Read(), UdpSocket::SendTo(), Header::SetFrameCounter(), MessageInfo::SetHopLimit(), AesCcm::SetKey(), Header::SetKeyId(), Message::SetOffset(), MessageInfo::SetPeerAddr(), MessageInfo::SetPeerPort(), MessageInfo::SetSockAddr(), SuccessOrExit, and Message::Write().
Referenced by Mle::Discover(), Mle::HandleDelayedResponseTimer(), Mle::SendAnnounce(), Mle::SendChildIdRequest(), Mle::SendChildUpdateRequest(), Mle::SendChildUpdateResponse(), Mle::SendDataRequest(), and Mle::SendParentRequest().
SetRloc16()
void SetRloc16 (uint16_t aRloc16) protected
This method sets the RLOC16 assigned to the Thread interface.
Parameters
[in] aRloc16 The RLOC16 to set.
References NetifUnicastAddress::GetAddress(), Mle::GetRloc16(), ot::Mac::kShortAddrInvalid, Mle::mMeshLocal16, otLogNoteMle, and Address::SetLocator().
Referenced by Mle::BecomeDetached(), Mle::SetStateChild(), and Mle::Start().
SetStateDetached()
void SetStateDetached (void) protected
This method sets the Device State to Detached.
References Mle::IsLeader(), Mle::kAttachStateIdle, Mle::kChildUpdateRequestNone, Mle::kDataRequestNone, ot::Mle::kRoleDetached, Mle::mAttachTimer, Mle::mChildUpdateAttempts, Mle::mChildUpdateRequestState, Mle::mDataRequestAttempts, Mle::mDataRequestState, Mle::mLeaderAloc, Mle::mMessageTransmissionTimer, Mle::SetAttachState(), Mle::SetRole(), and TimerMilli::Stop().
Referenced by Mle::BecomeDetached(), Mle::HandleChildIdResponse(), Mle::SetDeviceMode(), Mle::Start(), and Mle::Stop().
SetStateChild()
void SetStateChild (uint16_t aRloc16) protected
This method sets the Device State to Child.
References Neighbor::GetRloc16(), Mle::InformPreviousChannel(), Mle::IsFullThreadDevice(), Mle::IsLeader(), Mle::kAttachStateIdle, ot::Mle::kMplChildDataMessageTimerExpirations, Mle::kReattachStop, ot::Mle::kRoleChild, Mle::mAttachCounter, Mle::mAttachTimer, Mle::mChildUpdateAttempts, Mle::mDataRequestAttempts, Mle::mLeaderAloc, Mle::mParent, Mle::mParentRequestMode, Mle::mReattachState, Mle::ScheduleMessageTransmissionTimer(), Mle::SetAttachState(), Mle::SetRloc16(), Mle::SetRole(), and TimerMilli::Stop().
Referenced by Mle::HandleChildIdResponse(), Mle::HandleChildUpdateResponse(), and Mle::SetDeviceMode().
SetLeaderData()
void SetLeaderData (uint32_t aPartitionId, uint8_t aWeighting, uint8_t aLeaderRouterId) protected
This method sets the Leader's Partition ID, Weighting, and Router ID values.
Parameters
[in] aPartitionId The Leader's Partition ID value.
[in] aWeighting The Leader's Weighting value.
[in] aLeaderRouterId The Leader's Router ID value.
References LeaderData::GetPartitionId(), Mle::mCounters, Mle::mLeaderData, otMleCounters::mPartitionIdChanges, OT_CHANGED_THREAD_PARTITION_ID, LeaderData::SetLeaderRouterId(), LeaderData::SetPartitionId(), and LeaderData::SetWeighting().
Referenced by Mle::HandleAdvertisement(), Mle::HandleChildIdResponse(), and Mle::HandleLeaderData().
AddDelayedResponse()
otError AddDelayedResponse (Message & aMessage, const Ip6::Address & aDestination, uint16_t aDelay) protected
This method adds a message to the message queue. The queued message will be transmitted after given delay.
Parameters
[in] aMessage The message to transmit after given delay.
[in] aDestination The IPv6 address of the recipient of the message.
[in] aDelay The delay in milliseconds before transmission of the message.
Return values
OT_ERROR_NONE Successfully queued the message to transmit after the delay.
OT_ERROR_NO_BUFS Insufficient buffers to queue the message.
References Mle::DelayedResponseMetadata::AppendTo(), MessageQueue::Enqueue(), TimerMilli::FireAtIfEarlier(), TimerMilli::GetNow(), Mle::mDelayedResponses, Mle::mDelayedResponseTimer, Mle::DelayedResponseMetadata::mDestination, Mle::DelayedResponseMetadata::mSendTime, OT_ERROR_NONE, and SuccessOrExit.
Referenced by Mle::SendDataRequest().
LogMleMessage() [1/2]
void LogMleMessage (const char * aLogString, const Ip6::Address & aAddress) const protected
This method prints an MLE log message with an IPv6 address.
Parameters
[in] aLogString The log message string.
[in] aAddress The IPv6 address of the peer.
References String< SIZE >::AsCString(), OT_UNUSED_VARIABLE, otLogInfoMle, and Address::ToString().
Referenced by Mle::Discover(), Mle::HandleAdvertisement(), Mle::HandleAnnounce(), Mle::HandleChildIdResponse(), Mle::HandleChildUpdateRequest(), Mle::HandleChildUpdateResponse(), Mle::HandleDataResponse(), Mle::HandleDelayedResponseTimer(), Mle::HandleDiscoveryResponse(), Mle::HandleParentResponse(), Mle::RemoveDelayedDataResponseMessage(), Mle::SendChildIdRequest(), Mle::SendChildUpdateRequest(), Mle::SendChildUpdateResponse(), Mle::SendDataRequest(), and Mle::SendParentRequest().
LogMleMessage() [2/2]
void LogMleMessage (const char * aLogString, const Ip6::Address & aAddress, uint16_t aRloc) const protected
This method prints an MLE log message with an IPv6 address and RLOC16.
Parameters
[in] aLogString The log message string.
[in] aAddress The IPv6 address of the peer.
[in] aRloc The RLOC16.
References String< SIZE >::AsCString(), OT_UNUSED_VARIABLE, otLogInfoMle, and Address::ToString().
InformPreviousChannel()
void InformPreviousChannel (void) protected
This method triggers MLE Announce on previous channel after the Thread device successfully attaches and receives the new Active Commissioning Dataset if needed.
MTD would send Announce immediately after attached. FTD would delay to send Announce after tried to become Router or decided to stay in REED role.
References Mle::IsChild(), Mle::IsFullThreadDevice(), Mle::IsRouter(), ot::Mac::kPanIdBroadcast, Mle::mAlternateChannel, Mle::mAlternatePanId, OT_NOOP, Mle::SendAnnounce(), and VerifyOrExit.
Referenced by Mle::SetStateChild().
IsAnnounceAttach()
bool IsAnnounceAttach (void) const inline protected
This method indicates whether or not in announce attach process.
Return values
true if attaching/attached on the announced parameters, false otherwise.
References ot::Mac::kPanIdBroadcast.
AppendTo()
otError AppendTo (Message & aMessage) const inline
References Message::Append().
Referenced by Mle::AddDelayedResponse().
ReadFrom()
void ReadFrom (const Message & aMessage)
References Message::GetLength(), OT_ASSERT, and Message::Read().
Referenced by Mle::HandleDelayedResponseTimer(), and Mle::RemoveDelayedDataResponseMessage().
RemoveFrom()
void RemoveFrom (Message & aMessage) const
References Message::GetLength(), OT_ASSERT, OT_ERROR_NONE, OT_UNUSED_VARIABLE, and Message::SetLength().
Referenced by Mle::HandleDelayedResponseTimer().
HandleStateChanged() [1/2]
void HandleStateChanged (Notifier::Callback & aCallback, otChangedFlags aFlags) static private
References OwnerLocator::GetOwner().
HandleStateChanged() [2/2]
void HandleStateChanged (otChangedFlags aFlags) private
References ot::Random::Crypto::FillBuffer(), NetifUnicastAddress::GetAddress(), Mle::GetParent(), Mle::GetRloc16(), Mle::GetServiceAloc(), Mle::IsAttached(), Mle::IsChild(), Mle::IsDisabled(), Mle::IsFullThreadDevice(), Mle::IsRxOnWhenIdle(), Mle::kAppendAllAddresses, Mle::kAppendMeshLocalOnly, Mle::kChildUpdateRequestPending, ot::NetworkData::kIteratorInit, ot::Mac::kShortAddrInvalid, otIp6Address::OT_TOOL_PACKED_FIELD::m8, Mle::mAddressRegistrationMode, Mle::mChildUpdateRequestState, otIp6Address::mFields, Mle::mMeshLocal64, OPENTHREAD_CONFIG_THREAD_VERSION, OT_ARRAY_LENGTH, OT_CHANGED_IP6_ADDRESS_ADDED, OT_CHANGED_IP6_ADDRESS_REMOVED, OT_CHANGED_IP6_MULTICAST_SUBSCRIBED, OT_CHANGED_IP6_MULTICAST_UNSUBSCRIBED, OT_CHANGED_SECURITY_POLICY, OT_CHANGED_THREAD_KEY_SEQUENCE_COUNTER, OT_CHANGED_THREAD_ML_ADDR, OT_CHANGED_THREAD_NETDATA, OT_CHANGED_THREAD_ROLE, OT_ERROR_NONE, OT_IP6_ADDRESS_SIZE, OT_IP6_PREFIX_SIZE, OT_NOOP, OT_THREAD_VERSION_1_2, Mle::ScheduleMessageTransmissionTimer(), Mle::ServiceIdFromAloc(), Mle::Store(), SuccessOrExit, and VerifyOrExit.
HandleAttachTimer() [1/2]
void HandleAttachTimer (Timer & aTimer) static private
References OwnerLocator::GetOwner(), and Mle::HandleAttachTimer().
HandleAttachTimer() [2/2]
void HandleAttachTimer (void) private
References Router::Clear(), ExitNow, Neighbor::GetLinkInfo(), LinkQualityInfo::GetLinkQuality(), Router::GetLinkQualityOut(), Mle::IsChild(), Neighbor::IsStateParentResponse(), ot::Mle::kAttachBetter, ot::Mle::kAttachSame1, ot::Mle::kAttachSame2, Mle::kAttachStateAnnounce, Mle::kAttachStateChildIdRequest, Mle::kAttachStateIdle, Mle::kAttachStateParentRequestReed, Mle::kAttachStateParentRequestRouter, Mle::kAttachStateProcessAnnounce, Mle::kAttachStateStart, ChannelMask::kChannelIteratorFirst, ot::Mle::kParentRequestReedTimeout, ot::Mle::kParentRequestRouterTimeout, Mle::kParentRequestTypeRouters, Mle::kParentRequestTypeRoutersAndReeds, Neighbor::kStateInvalid, Mle::mAnnounceChannel, Mle::mAnnounceDelay, Mle::mAttachCounter, Mle::mAttachState, Mle::mAttachTimer, Mle::mParentCandidate, Mle::mParentRequestMode, Mle::mReattachState, Mle::mReceivedResponseFromParent, OT_ASSERT, OT_ERROR_NONE, OT_UNREACHABLE_CODE, otLogNoteMle, Mle::PrepareAnnounceState(), Mle::ProcessAnnounce(), Mle::Reattach(), Mle::SendChildIdRequest(), Mle::SendOrphanAnnounce(), Mle::SendParentRequest(), Mle::SetAttachState(), Neighbor::SetState(), and TimerMilli::Start().
Referenced by Mle::HandleAttachTimer().
HandleDelayedResponseTimer() [1/2]
void HandleDelayedResponseTimer (Timer & aTimer) static private
References OwnerLocator::GetOwner(), and Mle::HandleDelayedResponseTimer().
HandleDelayedResponseTimer() [2/2]
void HandleDelayedResponseTimer (void) private
References MessageQueue::Dequeue(), TimerMilli::FireAt(), Message::Free(), Time::GetDistantFuture(), MessageQueue::GetHead(), Message::GetNext(), TimerMilli::GetNow(), Mle::IsRxOnWhenIdle(), DataPollSender::kDefaultFastPolls, Mle::LogMleMessage(), Mle::mDelayedResponses, Mle::mDelayedResponseTimer, Mle::DelayedResponseMetadata::mDestination, Mle::DelayedResponseMetadata::mSendTime, OT_ERROR_NONE, Mle::DelayedResponseMetadata::ReadFrom(), Mle::DelayedResponseMetadata::RemoveFrom(), and Mle::SendMessage().
Referenced by Mle::HandleDelayedResponseTimer().
HandleMessageTransmissionTimer() [1/2]
void HandleMessageTransmissionTimer (Timer & aTimer) static private
References OwnerLocator::GetOwner(), and Mle::HandleMessageTransmissionTimer().
HandleMessageTransmissionTimer() [2/2]
void HandleMessageTransmissionTimer (void) private
References Mle::BecomeDetached(), ExitNow, Neighbor::GetExtAddress(), Mle::IsChild(), Mle::IsRxOnWhenIdle(), Mle::kChildUpdateRequestActive, Mle::kChildUpdateRequestNone, Mle::kChildUpdateRequestPending, Mle::kDataRequestActive, ot::Mle::kMaxChildKeepAliveAttempts, Tlv::kNetworkData, Mle::mChildUpdateAttempts, Mle::mChildUpdateRequestState, Mle::mDataRequestAttempts, Mle::mDataRequestState, Mle::mParent, OT_ERROR_NONE, OT_NOOP, Mle::ScheduleMessageTransmissionTimer(), Mle::SendChildUpdateRequest(), Mle::SendDataRequest(), Address::SetToLinkLocalAddress(), and VerifyOrExit.
Referenced by Mle::HandleMessageTransmissionTimer().
HandleUdpReceive() [1/2]
void HandleUdpReceive (void * aContext, otMessage * aMessage, const otMessageInfo * aMessageInfo) static private
Referenced by Mle::Enable().
HandleUdpReceive() [2/2]
void HandleUdpReceive (Message & aMessage, const Ip6::MessageInfo & aMessageInfo) private
References ExitNow, AesCcm::Finalize(), KeyManager::GenerateNonce(), Header::GetBytes(), Header::GetCommand(), Header::GetFrameCounter(), Header::GetHeaderLength(), MessageInfo::GetHopLimit(), Header::GetKeyId(), Neighbor::GetKeySequence(), Header::GetLength(), Message::GetLength(), MessageInfo::GetLinkInfo(), Neighbor::GetMleFrameCounter(), Mle::GetNeighbor(), Message::GetOffset(), MessageInfo::GetPeerAddr(), Header::GetSecuritySuite(), MessageInfo::GetSockAddr(), Mle::HandleAdvertisement(), Mle::HandleAnnounce(), Mle::HandleChildIdResponse(), Mle::HandleChildUpdateRequest(), Mle::HandleChildUpdateResponse(), Mle::HandleDataResponse(), Mle::HandleDiscoveryResponse(), Mle::HandleParentResponse(), AesCcm::Header(), AesCcm::Init(), Mle::IsDisabled(), Mle::IsRouterOrLeader(), Neighbor::IsStateValid(), Header::IsValid(), Header::k154Security, Header::kCommandAdvertisement, Header::kCommandAnnounce, Header::kCommandChildIdRequest, Header::kCommandChildIdResponse, Header::kCommandChildUpdateRequest, Header::kCommandChildUpdateResponse, Header::kCommandDataRequest, Header::kCommandDataResponse, Header::kCommandDiscoveryRequest, Header::kCommandDiscoveryResponse, Header::kCommandLinkAccept, Header::kCommandLinkAcceptAndRequest, Header::kCommandLinkRequest, Header::kCommandParentRequest, Header::kCommandParentResponse, Header::kCommandTimeSync, Mle::kMleHopLimit, KeyManager::kNonceSize, Header::kNoSecurity, ot::Mle::kRoleChild, ot::Mle::kRoleDetached, ot::Mle::kRoleLeader, ot::Mle::kRoleRouter, Frame::kSecEncMic32, Message::MoveOffset(), Mle::mRole, OT_ERROR_DROP, OT_ERROR_DUPLICATED, OT_ERROR_INVALID_STATE, OT_ERROR_NONE, OT_ERROR_PARSE, OT_ERROR_SECURITY, OT_NOOP, otLogDebgMle, otLogNoteMle, otThreadErrorToString(), AesCcm::Payload(), Message::Read(), AesCcm::SetKey(), Neighbor::SetKeySequence(), Message::SetLength(), Neighbor::SetLinkFrameCounter(), Neighbor::SetMleFrameCounter(), Message::SetOffset(), SuccessOrExit, Address::ToExtAddress(), VerifyOrExit, and Message::Write().
ScheduleMessageTransmissionTimer()
void ScheduleMessageTransmissionTimer (void) private
References ExitNow, Mle::IsChild(), Mle::IsRxOnWhenIdle(), Mle::kChildUpdateRequestActive, Mle::kChildUpdateRequestNone, Mle::kChildUpdateRequestPending, ot::Mle::kChildUpdateRequestPendingDelay, Mle::kDataRequestActive, Mle::kDataRequestNone, ot::Mle::kMaxChildKeepAliveAttempts, ot::Mle::kUnicastRetransmissionDelay, Mle::mChildUpdateRequestState, Mle::mDataRequestState, Mle::mMessageTransmissionTimer, Mle::mTimeout, Time::SecToMsec(), TimerMilli::Start(), and TimerMilli::Stop().
Referenced by Mle::HandleChildUpdateResponse(), Mle::HandleMessageTransmissionTimer(), Mle::HandleStateChanged(), Mle::SendChildUpdateRequest(), Mle::SendDataRequest(), and Mle::SetStateChild().
ReadChallengeOrResponse()
otError ReadChallengeOrResponse (const Message & aMessage, uint8_t aTlvType, Challenge & aBuffer) private
References Tlv::GetValueOffset(), ot::Mle::kMaxChallengeSize, ot::Mle::kMinChallengeSize, Mle::Challenge::mBuffer, Mle::Challenge::mLength, OT_ERROR_PARSE, Message::Read(), SuccessOrExit, and VerifyOrExit.
Referenced by Mle::ReadChallenge(), and Mle::ReadResponse().
HandleAdvertisement()
otError HandleAdvertisement (const Message & aMessage, const Ip6::MessageInfo & aMessageInfo, Neighbor * aNeighbor) private
References Mle::BecomeDetached(), ExitNow, Mle::GetLeaderId(), LeaderData::GetLeaderRouterId(), TimerMilli::GetNow(), LeaderData::GetPartitionId(), MessageInfo::GetPeerAddr(), Neighbor::GetRloc16(), Tlv::GetTlv(), ot::Random::NonCrypto::GetUint16InRange(), LeaderData::GetWeighting(), Mle::IsDetached(), Mle::IsFullThreadDevice(), Mle::IsNetworkDataNewer(), Neighbor::IsStateValid(), RouteTlv::IsValid(), Mle::kMleMaxResponseDelay, Tlv::kNetworkData, ot::Mle::kRoleChild, ot::Mle::kRoleDetached, ot::Mle::kRoleDisabled, ot::Mle::kRoleLeader, ot::Mle::kRoleRouter, Tlv::kRoute, Tlv::kSourceAddress, Mle::LogMleMessage(), Mle::mLeaderData, Mle::mParent, Mle::mRetrieveNewNetworkData, Mle::mRole, OT_ERROR_NONE, OT_NOOP, otLogWarnMle, otThreadErrorToString(), Mle::ReadLeaderData(), Tlv::ReadUint16Tlv(), Mle::SendDataRequest(), Neighbor::SetLastHeard(), Mle::SetLeaderData(), SuccessOrExit, and VerifyOrExit.
Referenced by Mle::HandleUdpReceive().
HandleChildIdResponse()
otError HandleChildIdResponse (const Message & aMessage, const Ip6::MessageInfo & aMessageInfo, const Neighbor * aNeighbor) private
References Router::Clear(), LeaderData::GetDataVersion(), LeaderData::GetLeaderRouterId(), Tlv::GetLength(), Tlv::GetOffset(), LeaderData::GetPartitionId(), MessageInfo::GetPeerAddr(), LeaderData::GetStableDataVersion(), Tlv::GetTlv(), LeaderData::GetWeighting(), Mle::IsFullNetworkData(), Mle::IsFullThreadDevice(), Mle::IsRxOnWhenIdle(), Neighbor::IsStateValid(), ActiveTimestampTlv::IsValid(), PendingTimestampTlv::IsValid(), Tlv::kActiveDataset, Tlv::kActiveTimestamp, Tlv::kAddress16, Mle::kAttachStateChildIdRequest, Tlv::kNetworkData, Tlv::kPendingDataset, Tlv::kPendingTimestamp, Mle::kReattachPending, Tlv::kRoute, Tlv::kSourceAddress, Mle::LogMleMessage(), Mle::mAttachState, Mle::mParent, Mle::mParentCandidate, Mle::mReattachState, OT_ERROR_NONE, OT_ERROR_PARSE, OT_ERROR_SECURITY, OT_NOOP, OT_TIME_SYNC_INVALID_SEQ, OT_UNUSED_VARIABLE, otLogWarnMle, otThreadErrorToString(), Message::Read(), Mle::ReadLeaderData(), Tlv::ReadUint16Tlv(), Mle::SetLeaderData(), Neighbor::SetRloc16(), Mle::SetStateChild(), Mle::SetStateDetached(), SuccessOrExit, and VerifyOrExit.
Referenced by Mle::HandleUdpReceive().
HandleChildUpdateRequest()
otError HandleChildUpdateRequest (const Message & aMessage, const Ip6::MessageInfo & aMessageInfo, Neighbor * aNeighbor) private
References Mle::BecomeDetached(), ExitNow, MessageInfo::GetPeerAddr(), Neighbor::GetRloc16(), Mle::HandleLeaderData(), StatusTlv::kError, Tlv::kLinkFrameCounter, Tlv::kMleFrameCounter, Tlv::kResponse, Tlv::kSourceAddress, Tlv::kStatus, Mle::LogMleMessage(), Mle::RequestedTlvs::mNumTlvs, Mle::mParent, Mle::RequestedTlvs::mTlvs, OT_ERROR_NONE, OT_ERROR_NOT_FOUND, OT_ERROR_PARSE, otLogWarnMle, otThreadErrorToString(), Mle::ReadChallenge(), Mle::ReadTlvRequest(), Tlv::ReadUint16Tlv(), Tlv::ReadUint8Tlv(), Mle::SendChildUpdateResponse(), SuccessOrExit, and VerifyOrExit.
Referenced by Mle::HandleUdpReceive().
HandleChildUpdateResponse()
otError HandleChildUpdateResponse (const Message & aMessage, const Ip6::MessageInfo & aMessageInfo, const Neighbor * aNeighbor) private
References Mle::BecomeDetached(), ExitNow, MessageInfo::GetPeerAddr(), Mle::GetRloc16(), Mle::HandleLeaderData(), Mle::IsRxOnWhenIdle(), Neighbor::IsStateValid(), Mle::kChildUpdateRequestActive, Mle::kChildUpdateRequestNone, Tlv::kLinkFrameCounter, Tlv::kMleFrameCounter, Tlv::kMode, ot::Mle::kRoleChild, ot::Mle::kRoleDetached, Tlv::kSourceAddress, Neighbor::kStateValid, Tlv::kStatus, Tlv::kTimeout, Mle::LogMleMessage(), Mle::mChildUpdateAttempts, Mle::mChildUpdateRequestState, Mle::mDeviceMode, Mle::mParent, Mle::mParentRequestChallenge, Mle::mRetrieveNewNetworkData, Mle::mRole, Mle::mTimeout, OT_ASSERT, OT_ERROR_DROP, OT_ERROR_NONE, OT_ERROR_NOT_FOUND, OT_ERROR_PARSE, OT_ERROR_SECURITY, OT_UNREACHABLE_CODE, otLogWarnMle, otThreadErrorToString(), Mle::ReadResponse(), Tlv::ReadUint16Tlv(), Tlv::ReadUint32Tlv(), Tlv::ReadUint8Tlv(), Mle::RouterIdFromRloc16(), Mle::ScheduleMessageTransmissionTimer(), Neighbor::SetLinkFrameCounter(), Neighbor::SetMleFrameCounter(), Neighbor::SetState(), Mle::SetStateChild(), SuccessOrExit, and VerifyOrExit.
Referenced by Mle::HandleUdpReceive().
HandleDataResponse()
otError HandleDataResponse (const Message & aMessage, const Ip6::MessageInfo & aMessageInfo, const Neighbor * aNeighbor) private
References MessageInfo::GetPeerAddr(), Mle::HandleLeaderData(), IgnoreReturnValue, Mle::IsRxOnWhenIdle(), Neighbor::IsStateValid(), Mle::kDataRequestNone, Mle::LogMleMessage(), Mle::mDataRequestState, OT_ERROR_NONE, OT_ERROR_SECURITY, otLogWarnMle, otThreadErrorToString(), and VerifyOrExit.
Referenced by Mle::HandleUdpReceive().
HandleParentResponse()
otError HandleParentResponse (const Message & aMessage, const Ip6::MessageInfo & aMessageInfo, uint32_t aKeySequence) private
References LinkQualityInfo::AddRss(), LinkQualityInfo::Clear(), LinkQualityInfo::ConvertLinkMarginToLinkQuality(), LinkQualityInfo::ConvertRssToLinkMargin(), ExitNow, ConnectivityTlv::GetActiveRouters(), Neighbor::GetExtAddress(), ConnectivityTlv::GetIdSequence(), ConnectivityTlv::GetLeaderCost(), MessageInfo::GetLinkInfo(), Neighbor::GetLinkInfo(), ConnectivityTlv::GetLinkQuality1(), ConnectivityTlv::GetLinkQuality2(), ConnectivityTlv::GetLinkQuality3(), ConnectivityTlv::GetParentPriority(), LeaderData::GetPartitionId(), MessageInfo::GetPeerAddr(), ConnectivityTlv::GetSedBufferSize(), ConnectivityTlv::GetSedDatagramCount(), Tlv::GetTlv(), Mle::IsAttached(), Mle::IsBetterParent(), Mle::IsChild(), Mle::IsDetached(), Mle::IsFullThreadDevice(), Neighbor::IsStateParentResponse(), ConnectivityTlv::IsValid(), ot::Mle::kAttachAny, ot::Mle::kAttachBetter, ot::Mle::kAttachSame1, ot::Mle::kAttachSame2, ot::Mle::kAttachSameDowngrade, Tlv::kConnectivity, Tlv::kLinkFrameCounter, Tlv::kLinkMargin, Tlv::kMleFrameCounter, DeviceMode::kModeFullNetworkData, DeviceMode::kModeFullThreadDevice, DeviceMode::kModeRxOnWhenIdle, DeviceMode::kModeSecureDataRequest, Tlv::kSourceAddress, Neighbor::kStateParentResponse, Tlv::kTimeParameter, Tlv::kVersion, Mle::LogMleMessage(), otThreadParentResponseInfo::mExtAddr, otThreadParentResponseInfo::mIsAttached, Mle::mLeaderData, otThreadParentResponseInfo::mLinkQuality1, otThreadParentResponseInfo::mLinkQuality2, otThreadParentResponseInfo::mLinkQuality3, Mle::mParent, Mle::mParentCandidate, Mle::mParentCandidateChallenge, Mle::mParentIsSingleton, Mle::mParentLeaderCost, Mle::mParentLeaderData, Mle::mParentLinkMargin, Mle::mParentLinkQuality1, Mle::mParentLinkQuality2, Mle::mParentLinkQuality3, Mle::mParentPriority, Mle::mParentRequestChallenge, Mle::mParentRequestMode, Mle::mParentResponseCb, Mle::mParentResponseCbContext, Mle::mParentSedBufferSize, Mle::mParentSedDatagramCount, otThreadParentResponseInfo::mPriority, Mle::mReceivedResponseFromParent, otThreadParentResponseInfo::mRloc16, otThreadLinkInfo::mRss, otThreadParentResponseInfo::mRssi, OT_ERROR_NONE, OT_ERROR_NOT_FOUND, OT_ERROR_PARSE, OT_NOOP, OT_THREAD_VERSION_1_1, otLogWarnMle, otThreadErrorToString(), Mle::ReadChallenge(), Mle::ReadLeaderData(), Mle::ReadResponse(), Tlv::ReadUint16Tlv(), Tlv::ReadUint32Tlv(), Tlv::ReadUint8Tlv(), Neighbor::ResetLinkFailures(), Neighbor::SetDeviceMode(), Neighbor::SetExtAddress(), Neighbor::SetKeySequence(), Neighbor::SetLinkFrameCounter(), Router::SetLinkQualityOut(), Neighbor::SetMleFrameCounter(), Neighbor::SetRloc16(), Neighbor::SetState(), Neighbor::SetVersion(), SuccessOrExit, Address::ToExtAddress(), and VerifyOrExit.
Referenced by Mle::HandleUdpReceive().
HandleAnnounce()
otError HandleAnnounce (const Message & aMessage, const Ip6::MessageInfo & aMessageInfo) private
References Timestamp::Compare(), ChannelTlv::GetChannel(), MessageInfo::GetPeerAddr(), Timestamp::GetSeconds(), Tlv::GetTlv(), Mle::IsDetached(), ChannelTlv::IsValid(), ActiveTimestampTlv::IsValid(), Tlv::kActiveTimestamp, ot::Mle::kAnnounceProcessTimeout, Mle::kAttachStateProcessAnnounce, Tlv::kChannel, Tlv::kPanId, Mle::LogMleMessage(), Mle::mAlternateChannel, Mle::mAlternatePanId, Mle::mAlternateTimestamp, Mle::mAttachState, Mle::mAttachTimer, OT_ERROR_NONE, OT_ERROR_PARSE, OT_NOOP, OT_UNUSED_VARIABLE, otLogNoteMle, otLogWarnMle, otThreadErrorToString(), Tlv::ReadUint16Tlv(), Mle::SendAnnounce(), Mle::SetAttachState(), TimerMilli::Start(), SuccessOrExit, and VerifyOrExit.
Referenced by Mle::HandleUdpReceive().
HandleDiscoveryResponse()
otError HandleDiscoveryResponse (const Message & aMessage, const Ip6::MessageInfo & aMessageInfo) private
References SteeringDataTlv::GetBit(), ExtendedPanIdTlv::GetExtendedPanId(), Tlv::GetLength(), MessageInfo::GetLinkInfo(), NetworkNameTlv::GetNetworkName(), SteeringDataTlv::GetNumBits(), Tlv::GetOffset(), MessageInfo::GetPeerAddr(), SteeringDataTlv::GetSteeringDataLength(), Tlv::GetType(), JoinerUdpPortTlv::GetUdpPort(), Tlv::GetValue(), DiscoveryResponseTlv::GetVersion(), DiscoveryResponseTlv::IsNativeCommissioner(), ExtendedPanIdTlv::IsValid(), SteeringDataTlv::IsValid(), JoinerUdpPortTlv::IsValid(), DiscoveryResponseTlv::IsValid(), Tlv::kDiscovery, Tlv::kDiscoveryResponse, Tlv::kExtendedPanId, Tlv::kJoinerUdpPort, Tlv::kNetworkName, Tlv::kSteeringData, Mle::LogMleMessage(), otSteeringData::m8, otThreadLinkInfo::mChannel, otActiveScanResult::mChannel, Mle::mDiscoverAnsiIndex, Mle::mDiscoverCcittIndex, Mle::mDiscoverContext, Mle::mDiscoverEnableFiltering, Mle::mDiscoverHandler, Mle::mDiscoverInProgress, otActiveScanResult::mExtAddress, otActiveScanResult::mExtendedPanId, otActiveScanResult::mIsNative, otActiveScanResult::mJoinerUdpPort, otSteeringData::mLength, otThreadLinkInfo::mLqi, otActiveScanResult::mLqi, otActiveScanResult::mNetworkName, otThreadLinkInfo::mPanId, otActiveScanResult::mPanId, otThreadLinkInfo::mRss, otActiveScanResult::mRssi, otActiveScanResult::mSteeringData, otActiveScanResult::mVersion, OT_ERROR_DROP, OT_ERROR_NONE, OT_ERROR_PARSE, OT_NOOP, otLogWarnMle, otThreadErrorToString(), Message::Read(), Address::ToExtAddress(), and VerifyOrExit.
Referenced by Mle::HandleUdpReceive().
HandleLeaderData()
otError HandleLeaderData (const Message & aMessage, const Ip6::MessageInfo & aMessageInfo) private
References ExitNow, LeaderData::GetDataVersion(), Mle::GetLeaderId(), LeaderData::GetLeaderRouterId(), Tlv::GetLength(), Tlv::GetOffset(), LeaderData::GetPartitionId(), MessageInfo::GetPeerAddr(), MessageInfo::GetSockAddr(), LeaderData::GetStableDataVersion(), Tlv::GetTlv(), ot::Random::NonCrypto::GetUint16InRange(), LeaderData::GetWeighting(), Mle::IsChild(), Mle::IsFullNetworkData(), Address::IsMulticast(), Mle::IsNetworkDataNewer(), ActiveTimestampTlv::IsValid(), PendingTimestampTlv::IsValid(), Tlv::kActiveDataset, Tlv::kActiveTimestamp, Mle::kDataRequestNone, Mle::kMleMaxResponseDelay, Tlv::kNetworkData, Tlv::kPendingDataset, Tlv::kPendingTimestamp, Mle::mDataRequestAttempts, Mle::mDataRequestState, Mle::mLeaderData, Mle::mRetrieveNewNetworkData, OT_ERROR_DROP, OT_ERROR_NONE, OT_ERROR_PARSE, OT_NOOP, Message::Read(), Mle::ReadLeaderData(), Mle::SendDataRequest(), Mle::SetLeaderData(), Tlv::SetLength(), SuccessOrExit, and VerifyOrExit.
Referenced by Mle::HandleChildUpdateRequest(), Mle::HandleChildUpdateResponse(), and Mle::HandleDataResponse().
ProcessAnnounce()
void ProcessAnnounce (void) private
References Mle::kAttachStateProcessAnnounce, Mle::mAlternateChannel, Mle::mAlternatePanId, Mle::mAlternateTimestamp, Mle::mAttachState, OT_ASSERT, otLogNoteMle, Mle::Start(), and Mle::Stop().
Referenced by Mle::HandleAttachTimer().
HasUnregisteredAddress()
bool HasUnregisteredAddress (void) private
References ExitNow, Mle::GetMeshLocal64(), LinkedListEntry< Type >::GetNext(), Mle::IsAnycastLocator(), Mle::IsRoutingLocator(), Mle::IsRxOnWhenIdle(), and OT_ERROR_NONE.
Referenced by Mle::SendChildUpdateResponse().
GetAttachStartDelay()
uint32_t GetAttachStartDelay (void) const private
References ot::Random::NonCrypto::AddJitter(), ExitNow, ot::Random::NonCrypto::GetUint32InRange(), Mle::IsDetached(), Mle::kAttachBackoffJitter, Mle::kAttachBackoffMaxInterval, Mle::kAttachBackoffMinInterval, ot::Mle::kAttachStartJitter, ot::Mle::kParentRequestRouterTimeout, Mle::mAttachCounter, OT_NOOP, otLogNoteMle, and VerifyOrExit.
Referenced by Mle::BecomeChild().
SendParentRequest()
otError SendParentRequest (ParentRequestType aType) private
References Mle::AppendChallenge(), Mle::AppendHeader(), Mle::AppendMode(), Mle::AppendScanMask(), Mle::AppendVersion(), Message::Free(), Mle::Challenge::GenerateRandom(), Header::kCommandParentRequest, ScanMaskTlv::kEndDeviceFlag, Mle::kParentRequestTypeRouters, Mle::kParentRequestTypeRoutersAndReeds, ScanMaskTlv::kRouterFlag, Mle::LogMleMessage(), Mle::mDeviceMode, Mle::mParentRequestChallenge, Mle::NewMleMessage(), OT_ERROR_NO_BUFS, OT_ERROR_NONE, Mle::SendMessage(), Address::SetToLinkLocalAllRoutersMulticast(), SuccessOrExit, and VerifyOrExit.
Referenced by Mle::HandleAttachTimer().
SendChildIdRequest()
otError SendChildIdRequest (void) private
References Mle::AppendActiveTimestamp(), Mle::AppendAddressRegistration(), Mle::AppendHeader(), Mle::AppendLinkFrameCounter(), Mle::AppendMleFrameCounter(), Mle::AppendMode(), Mle::AppendPendingTimestamp(), Mle::AppendResponse(), Mle::AppendTimeout(), Mle::AppendTlvRequest(), Mle::AppendVersion(), ExitNow, Message::Free(), Neighbor::GetExtAddress(), Mle::IsChild(), Mle::IsFullThreadDevice(), Mle::IsRxOnWhenIdle(), Tlv::kAddress16, Mle::kAppendMeshLocalOnly, Header::kCommandChildIdRequest, Tlv::kNetworkData, Tlv::kRoute, Neighbor::kStateInvalid, Neighbor::kStateValid, Message::kSubTypeMleChildIdRequest, Mle::LogMleMessage(), Mle::mAddressRegistrationMode, Mle::mDeviceMode, Mle::mParent, Mle::mParentCandidate, Mle::mParentCandidateChallenge, Mle::mTimeout, Mle::NewMleMessage(), OT_ERROR_ALREADY, OT_ERROR_NO_BUFS, OT_ERROR_NONE, otLogInfoMle, Mle::SendMessage(), Neighbor::SetState(), Message::SetSubType(), Address::SetToLinkLocalAddress(), SuccessOrExit, and VerifyOrExit.
Referenced by Mle::HandleAttachTimer(), and Mle::RequestShorterChildIdRequest().
SendOrphanAnnounce()
otError SendOrphanAnnounce (void) private
References ChannelMask::GetNextChannel(), Mle::mAnnounceChannel, OT_ERROR_NONE, Mle::SendAnnounce(), and SuccessOrExit.
Referenced by Mle::HandleAttachTimer().
PrepareAnnounceState()
bool PrepareAnnounceState (void) private
References ChannelMask::GetNumberOfChannels(), Mle::IsChild(), Mle::IsFullThreadDevice(), ot::Mle::kAnnounceTimeout, ot::Mle::kMinAnnounceDelay, Mle::kReattachStop, Mle::mAnnounceDelay, Mle::mReattachState, OT_ERROR_NONE, OT_NOOP, and VerifyOrExit.
Referenced by Mle::HandleAttachTimer().
SendAnnounce() [2/2]
otError SendAnnounce (uint8_t aChannel, bool aOrphanAnnounce, const Ip6::Address & aDestination) private
References Mle::AppendActiveTimestamp(), Mle::AppendHeader(), Tlv::AppendTo(), Tlv::AppendUint16Tlv(), Message::Free(), ChannelTlv::Init(), ActiveTimestampTlv::Init(), Header::kCommandAnnounce, Tlv::kPanId, Message::kSubTypeMleAnnounce, Mle::NewMleMessage(), OT_ERROR_INVALID_ARGS, OT_ERROR_NO_BUFS, OT_ERROR_NONE, otLogInfoMle, Mle::SendMessage(), Timestamp::SetAuthoritative(), Message::SetChannel(), ChannelTlv::SetChannel(), Message::SetLinkSecurityEnabled(), Timestamp::SetSeconds(), Message::SetSubType(), Timestamp::SetTicks(), SuccessOrExit, and VerifyOrExit.
Reattach()
uint32_t Reattach (void) private
References Mle::BecomeChild(), Mle::BecomeDetached(), ot::Random::NonCrypto::GetUint32InRange(), Mle::IsChild(), Mle::IsFullThreadDevice(), Mle::IsRxOnWhenIdle(), ot::Mle::kAttachAny, ot::Mle::kAttachBetter, ot::Mle::kAttachSame1, ot::Mle::kAttachSame2, ot::Mle::kAttachSameDowngrade, ot::Mle::kAttachStartJitter, Mle::kAttachStateStart, ot::Mac::kPanIdBroadcast, Mle::kReattachActive, Mle::kReattachPending, Mle::kReattachStop, Mle::mAlternateChannel, Mle::mAlternatePanId, Mle::mParentRequestMode, Mle::mReattachState, OT_ERROR_NONE, OT_NOOP, Mle::Restore(), Mle::SetAttachState(), and VerifyOrExit.
Referenced by Mle::HandleAttachTimer().
IsBetterParent()
bool IsBetterParent (uint16_t aRloc16, uint8_t aLinkQuality, uint8_t aLinkMargin, const ConnectivityTlv & aConnectivityTlv, uint8_t aVersion) private
References ExitNow, Neighbor::GetLinkInfo(), LinkQualityInfo::GetLinkQuality(), ConnectivityTlv::GetLinkQuality1(), ConnectivityTlv::GetLinkQuality2(), ConnectivityTlv::GetLinkQuality3(), Router::GetLinkQualityOut(), ConnectivityTlv::GetParentPriority(), Neighbor::GetRloc16(), ConnectivityTlv::GetSedBufferSize(), ConnectivityTlv::GetSedDatagramCount(), Neighbor::GetVersion(), Mle::IsActiveRouter(), Mle::mParentCandidate, Mle::mParentLinkMargin, Mle::mParentLinkQuality1, Mle::mParentLinkQuality2, Mle::mParentLinkQuality3, Mle::mParentPriority, Mle::mParentSedBufferSize, and Mle::mParentSedDatagramCount.
Referenced by Mle::HandleParentResponse().
IsNetworkDataNewer()
bool IsNetworkDataNewer (const LeaderData & aLeaderData) private
References LeaderData::GetDataVersion(), LeaderData::GetStableDataVersion(), and Mle::IsFullNetworkData().
Referenced by Mle::HandleAdvertisement(), and Mle::HandleLeaderData().
Variable Documentation
mSecuritySuite
uint8_t mSecuritySuite private
Referenced by Header::GetBytes(), Header::GetCommand(), Header::GetLength(), Header::GetSecuritySuite(), Header::Init(), Header::IsValid(), Header::SetCommand(), and Header::SetSecuritySuite().
mSecurityControl
uint8_t mSecurityControl private
Referenced by Header::GetCommand(), Header::GetHeaderLength(), Header::GetLength(), Header::GetSecurityControl(), Header::Init(), Header::IsKeyIdMode2(), Header::IsValid(), Header::SetCommand(), and Header::SetKeyIdMode2().
mFrameCounter
uint32_t mFrameCounter private
Referenced by Header::GetFrameCounter(), Header::GetHeaderLength(), Header::GetLength(), and Header::SetFrameCounter().
mKeySource
uint32_t mKeySource private
Referenced by Header::GetHeaderLength(), Header::GetKeyId(), Header::GetLength(), and Header::SetKeyId().
mKeyIndex
uint8_t mKeyIndex private
Referenced by Header::GetHeaderLength(), Header::GetLength(), and Header::SetKeyId().
mCommand
uint8_t mCommand private
Referenced by Header::GetCommand(), Header::GetLength(), and Header::SetCommand().
OT_TOOL_PACKED_END
OT_TOOL_PACKED_BEGIN class ot::Mle::RouterIdSet OT_TOOL_PACKED_END
Referenced by Tlv::GetOffset(), ActiveTimestampTlv::IsValid(), PendingTimestampTlv::IsValid(), and MeshLocalPrefix::operator!=().
mBuffer
uint8_t mBuffer[kMaxChallengeSize]
Buffer containing the challenge/response byte sequence.
Referenced by Mle::AppendChallenge(), Mle::AppendResponse(), Mle::Challenge::operator==(), and Mle::ReadChallengeOrResponse().
mLength
uint8_t mLength
Challenge length (in bytes).
Referenced by Mle::AppendChallenge(), Mle::AppendResponse(), Mle::Challenge::operator==(), and Mle::ReadChallengeOrResponse().
mTlvs
uint8_t mTlvs[kMaxNumTlvs]
Array of requested TLVs.
Referenced by Mle::HandleChildUpdateRequest(), and Mle::ReadTlvRequest().
mNumTlvs
uint8_t mNumTlvs
Number of TLVs in the array.
Referenced by Mle::HandleChildUpdateRequest(), and Mle::ReadTlvRequest().
mLeaderData
LeaderData mLeaderData protected
Last received Leader Data TLV.
Referenced by Mle::AppendLeaderData(), Mle::GetLeaderAddress(), Mle::GetLeaderData(), Mle::HandleAdvertisement(), Mle::HandleLeaderData(), Mle::HandleParentResponse(), Mle::Mle(), Mle::SetLeaderData(), and Mle::Store().
mRetrieveNewNetworkData
bool mRetrieveNewNetworkData protected
Indicating new Network Data is needed if set.
Referenced by Mle::AppendNetworkData(), Mle::HandleAdvertisement(), Mle::HandleChildUpdateResponse(), and Mle::HandleLeaderData().
mRole
DeviceRole mRole protected
Current Thread role.
Referenced by Mle::HandleAdvertisement(), Mle::HandleChildUpdateResponse(), Mle::HandleUdpReceive(), Mle::SendChildUpdateRequest(), Mle::SetDeviceMode(), Mle::SetRole(), and Mle::Store().
mParent
Router mParent protected
Parent information.
Referenced by Mle::BecomeDetached(), Mle::CheckReachability(), Mle::GetNeighbor(), Mle::GetNextHop(), Mle::HandleAdvertisement(), Mle::HandleChildIdResponse(), Mle::HandleChildUpdateRequest(), Mle::HandleChildUpdateResponse(), Mle::HandleMessageTransmissionTimer(), Mle::HandleParentResponse(), Mle::Mle(), Mle::Restore(), Mle::SendChildIdRequest(), Mle::SendChildUpdateRequest(), Mle::SendChildUpdateResponse(), Mle::SetRole(), Mle::SetStateChild(), and Mle::Store().
mDeviceMode
DeviceMode mDeviceMode protected
Device mode setting.
Referenced by Mle::HandleChildUpdateResponse(), Mle::Restore(), Mle::SendChildIdRequest(), Mle::SendChildUpdateRequest(), Mle::SendParentRequest(), Mle::SetDeviceMode(), and Mle::Store().
mAttachState
AttachState mAttachState protected
The parent request state.
Referenced by Mle::BecomeDetached(), Mle::HandleAnnounce(), Mle::HandleAttachTimer(), Mle::HandleChildIdResponse(), Mle::ProcessAnnounce(), Mle::RequestShorterChildIdRequest(), and Mle::SetAttachState().
mReattachState
ReattachState mReattachState protected
Reattach state.
Referenced by Mle::BecomeChild(), Mle::BecomeDetached(), Mle::HandleAttachTimer(), Mle::HandleChildIdResponse(), Mle::PrepareAnnounceState(), Mle::Reattach(), Mle::SetStateChild(), and Mle::Start().
mAttachCounter
uint16_t mAttachCounter protected
Attach attempt counter.
Referenced by Mle::BecomeChild(), Mle::GetAttachStartDelay(), Mle::HandleAttachTimer(), Mle::SetDeviceMode(), Mle::SetStateChild(), and Mle::Start().
mAnnounceDelay
uint16_t mAnnounceDelay protected
Delay in between sending Announce messages during attach.
Referenced by Mle::HandleAttachTimer(), and Mle::PrepareAnnounceState().
mAttachTimer
TimerMilli mAttachTimer protected
The timer for driving the attach process.
Referenced by Mle::BecomeChild(), Mle::HandleAnnounce(), Mle::HandleAttachTimer(), Mle::SetStateChild(), and Mle::SetStateDetached().
mDelayedResponseTimer
TimerMilli mDelayedResponseTimer protected
The timer to delay MLE responses.
Referenced by Mle::AddDelayedResponse(), and Mle::HandleDelayedResponseTimer().
mMessageTransmissionTimer
TimerMilli mMessageTransmissionTimer protected
The timer for (re-)sending of MLE messages (e.g. Child Update).
Referenced by Mle::ScheduleMessageTransmissionTimer(), and Mle::SetStateDetached().
mParentLeaderCost
uint8_t mParentLeaderCost protected
Referenced by Mle::HandleParentResponse().
mDestination
Ip6::Address mDestination
Referenced by Mle::AddDelayedResponse(), Mle::HandleDelayedResponseTimer(), and Mle::RemoveDelayedDataResponseMessage().
mSendTime
TimeMilli mSendTime
Referenced by Mle::AddDelayedResponse(), and Mle::HandleDelayedResponseTimer().
mDelayedResponses
MessageQueue mDelayedResponses private
Referenced by Mle::AddDelayedResponse(), Mle::HandleDelayedResponseTimer(), and Mle::RemoveDelayedDataResponseMessage().
mParentRequestChallenge
Challenge mParentRequestChallenge private
Referenced by Mle::HandleChildUpdateResponse(), Mle::HandleParentResponse(), Mle::SendChildUpdateRequest(), and Mle::SendParentRequest().
mParentRequestMode
AttachMode mParentRequestMode private
Referenced by Mle::BecomeChild(), Mle::HandleAttachTimer(), Mle::HandleParentResponse(), Mle::Reattach(), and Mle::SetStateChild().
mParentPriority
int8_t mParentPriority private
Referenced by Mle::HandleParentResponse(), and Mle::IsBetterParent().
mParentLinkQuality3
uint8_t mParentLinkQuality3 private
Referenced by Mle::HandleParentResponse(), and Mle::IsBetterParent().
mParentLinkQuality2
uint8_t mParentLinkQuality2 private
Referenced by Mle::HandleParentResponse(), and Mle::IsBetterParent().
mParentLinkQuality1
uint8_t mParentLinkQuality1 private
Referenced by Mle::HandleParentResponse(), and Mle::IsBetterParent().
mParentSedBufferSize
uint16_t mParentSedBufferSize private
Referenced by Mle::HandleParentResponse(), and Mle::IsBetterParent().
mParentSedDatagramCount
uint8_t mParentSedDatagramCount private
Referenced by Mle::HandleParentResponse(), and Mle::IsBetterParent().
mChildUpdateAttempts
uint8_t mChildUpdateAttempts private
Referenced by Mle::HandleChildUpdateResponse(), Mle::HandleMessageTransmissionTimer(), Mle::SetStateChild(), Mle::SetStateDetached(), and Mle::Start().
mChildUpdateRequestState
ChildUpdateRequestState mChildUpdateRequestState private
Referenced by Mle::HandleChildUpdateResponse(), Mle::HandleMessageTransmissionTimer(), Mle::HandleStateChanged(), Mle::ScheduleMessageTransmissionTimer(), Mle::SendChildUpdateRequest(), Mle::SendDataRequest(), and Mle::SetStateDetached().
mDataRequestAttempts
uint8_t mDataRequestAttempts private
Referenced by Mle::HandleLeaderData(), Mle::HandleMessageTransmissionTimer(), Mle::SetStateChild(), and Mle::SetStateDetached().
mDataRequestState
DataRequestState mDataRequestState private
Referenced by Mle::HandleDataResponse(), Mle::HandleLeaderData(), Mle::HandleMessageTransmissionTimer(), Mle::ScheduleMessageTransmissionTimer(), Mle::SendDataRequest(), and Mle::SetStateDetached().
mAddressRegistrationMode
AddressRegistrationMode mAddressRegistrationMode private
Referenced by Mle::HandleStateChanged(), Mle::RequestShorterChildIdRequest(), and Mle::SendChildIdRequest().
mParentLinkMargin
uint8_t mParentLinkMargin private
Referenced by Mle::HandleParentResponse(), and Mle::IsBetterParent().
mParentIsSingleton
bool mParentIsSingleton private
Referenced by Mle::HandleParentResponse().
mReceivedResponseFromParent
bool mReceivedResponseFromParent private
Referenced by Mle::HandleAttachTimer(), and Mle::HandleParentResponse().
mParentLeaderData
LeaderData mParentLeaderData private
Referenced by Mle::HandleParentResponse(), and Mle::Mle().
mParentCandidate
Router mParentCandidate private
Referenced by Mle::BecomeChild(), Mle::GetNeighbor(), Mle::HandleAttachTimer(), Mle::HandleChildIdResponse(), Mle::HandleParentResponse(), Mle::IsBetterParent(), Mle::Mle(), and Mle::SendChildIdRequest().
mParentCandidateChallenge
Challenge mParentCandidateChallenge private
Referenced by Mle::HandleParentResponse(), and Mle::SendChildIdRequest().
mSocket
Ip6::UdpSocket mSocket private
Referenced by Mle::Disable(), Mle::Enable(), Mle::NewMleMessage(), and Mle::SendMessage().
mTimeout
uint32_t mTimeout private
Referenced by Mle::HandleChildUpdateResponse(), Mle::ScheduleMessageTransmissionTimer(), Mle::SendChildIdRequest(), Mle::SendChildUpdateRequest(), Mle::SendChildUpdateResponse(), and Mle::SetTimeout().
mDiscoverHandler
DiscoverHandler mDiscoverHandler private
Referenced by Mle::Discover(), Mle::HandleDiscoverComplete(), and Mle::HandleDiscoveryResponse().
mDiscoverContext
void* mDiscoverContext private
Referenced by Mle::Discover(), Mle::HandleDiscoverComplete(), and Mle::HandleDiscoveryResponse().
mDiscoverCcittIndex
uint16_t mDiscoverCcittIndex private
Referenced by Mle::Discover(), and Mle::HandleDiscoveryResponse().
mDiscoverAnsiIndex
uint16_t mDiscoverAnsiIndex private
Referenced by Mle::Discover(), and Mle::HandleDiscoveryResponse().
mDiscoverInProgress
bool mDiscoverInProgress private
Referenced by Mle::Discover(), Mle::HandleDiscoverComplete(), and Mle::HandleDiscoveryResponse().
mDiscoverEnableFiltering
bool mDiscoverEnableFiltering private
Referenced by Mle::Discover(), Mle::HandleDiscoverComplete(), and Mle::HandleDiscoveryResponse().
mAnnounceChannel
uint8_t mAnnounceChannel private
Referenced by Mle::HandleAttachTimer(), and Mle::SendOrphanAnnounce().
mAlternateChannel
uint8_t mAlternateChannel private
Referenced by Mle::HandleAnnounce(), Mle::InformPreviousChannel(), Mle::ProcessAnnounce(), and Mle::Reattach().
mAlternatePanId
uint16_t mAlternatePanId private
Referenced by Mle::HandleAnnounce(), Mle::InformPreviousChannel(), Mle::ProcessAnnounce(), and Mle::Reattach().
mAlternateTimestamp
uint64_t mAlternateTimestamp private
Referenced by Mle::HandleAnnounce(), and Mle::ProcessAnnounce().
mLeaderAloc
Ip6::NetifUnicastAddress mLeaderAloc private
Referenced by Mle::AddLeaderAloc(), Mle::ApplyMeshLocalPrefix(), Mle::Mle(), Mle::SetMeshLocalPrefix(), Mle::SetStateChild(), and Mle::SetStateDetached().
mCounters
otMleCounters mCounters private
Referenced by Mle::BecomeChild(), Mle::CheckReachability(), Mle::SetLeaderData(), and Mle::SetRole().
mLinkLocal64
Ip6::NetifUnicastAddress mLinkLocal64 private
Referenced by Mle::Disable(), Mle::Mle(), Mle::SendMessage(), and Mle::UpdateLinkLocalAddress().
mMeshLocal64
Ip6::NetifUnicastAddress mMeshLocal64 private
Referenced by Mle::ApplyMeshLocalPrefix(), Mle::HandleStateChanged(), Mle::Mle(), Mle::Restore(), Mle::SetMeshLocalPrefix(), Mle::Stop(), and Mle::Store().
mMeshLocal16
Ip6::NetifUnicastAddress mMeshLocal16 private
Referenced by Mle::ApplyMeshLocalPrefix(), Mle::GetLocatorAddress(), Mle::Mle(), Mle::SetMeshLocalPrefix(), Mle::SetRloc16(), and Mle::Stop().
mLinkLocalAllThreadNodes
Ip6::NetifMulticastAddress mLinkLocalAllThreadNodes private
Referenced by Mle::ApplyMeshLocalPrefix(), Mle::Mle(), Mle::SetMeshLocalPrefix(), and Mle::Stop().
mRealmLocalAllThreadNodes
Ip6::NetifMulticastAddress mRealmLocalAllThreadNodes private
Referenced by Mle::ApplyMeshLocalPrefix(), Mle::Mle(), Mle::SetMeshLocalPrefix(), and Mle::Stop().
mNotifierCallback
Notifier::Callback mNotifierCallback private
mParentResponseCb
otThreadParentResponseCallback mParentResponseCb private
Referenced by Mle::HandleParentResponse(), and Mle::RegisterParentResponseStatsCallback().
mParentResponseCbContext
void* mParentResponseCbContext private
Referenced by Mle::HandleParentResponse(), and Mle::RegisterParentResponseStatsCallback().
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale