OpenThread: Message
Message
API
This module includes functions that manipulate OpenThread message buffers.
Data Structures
struct otBufferInfo
struct otMessage
struct otMessageQueue
struct otMessageSettings
Typedefs
typedef struct otBufferInfo otBufferInfo
typedef struct otMessage otMessage
typedef enum otMessagePriority otMessagePriority
typedef struct otMessageSettings otMessageSettings
Enumerations
enum otMessagePriority { OT_MESSAGE_PRIORITY_LOW = 0, OT_MESSAGE_PRIORITY_NORMAL = 1, OT_MESSAGE_PRIORITY_HIGH = 2 }
Functions
otError otMessageAppend (otMessage *aMessage, const void *aBuf, uint16_t aLength)
void otMessageFree (otMessage *aMessage)
void otMessageGetBufferInfo (otInstance *aInstance, otBufferInfo *aBufferInfo)
uint16_t otMessageGetLength (const otMessage *aMessage)
uint16_t otMessageGetOffset (const otMessage *aMessage)
int8_t otMessageGetRss (const otMessage *aMessage)
bool otMessageIsLinkSecurityEnabled (const otMessage *aMessage)
otError otMessageQueueDequeue (otMessageQueue *aQueue, otMessage *aMessage)
otError otMessageQueueEnqueue (otMessageQueue *aQueue, otMessage *aMessage)
otError otMessageQueueEnqueueAtHead (otMessageQueue *aQueue, otMessage *aMessage)
otMessage * otMessageQueueGetHead (otMessageQueue *aQueue)
otMessage * otMessageQueueGetNext (otMessageQueue *aQueue, const otMessage *aMessage)
void otMessageQueueInit (otMessageQueue *aQueue)
uint16_t otMessageRead (const otMessage *aMessage, uint16_t aOffset, void *aBuf, uint16_t aLength)
void otMessageSetDirectTransmission (otMessage *aMessage, bool aEnabled)
otError otMessageSetLength (otMessage *aMessage, uint16_t aLength)
otError otMessageSetOffset (otMessage *aMessage, uint16_t aOffset)
int otMessageWrite (otMessage *aMessage, uint16_t aOffset, const void *aBuf, uint16_t aLength)
Detailed Description
This module includes functions that manipulate OpenThread message buffers.
Typedef Documentation
otMessage
typedef struct otMessage otMessage
This structure points to an OpenThread message buffer.
otBufferInfo
typedef struct otBufferInfo otBufferInfo
This structure represents the message buffer information.
otMessagePriority
typedef enum otMessagePriority otMessagePriority
This enumeration defines the OpenThread message priority levels.
otMessageSettings
typedef struct otMessageSettings otMessageSettings
This structure represents a message settings.
Enumeration Type Documentation
otMessagePriority
enum otMessagePriority
This enumeration defines the OpenThread message priority levels.
Enumerator
OT_MESSAGE_PRIORITY_LOW
Low priority level.
OT_MESSAGE_PRIORITY_NORMAL
Normal priority level.
OT_MESSAGE_PRIORITY_HIGH
High priority level.
Function Documentation
otMessageFree()
void otMessageFree (otMessage * aMessage)
Free an allocated message buffer.
Parameters
[in] aMessage A pointer to a message buffer.
See also
otMessageAppend
otMessageGetLength
otMessageSetLength
otMessageGetOffset
otMessageSetOffset
otMessageRead
otMessageWrite
Referenced by Buffer::Clear(), and Buffer::OutFrameRemove().
otMessageGetLength()
uint16_t otMessageGetLength (const otMessage * aMessage)
Get the message length in bytes.
Parameters
[in] aMessage A pointer to a message buffer.
Returns
The message length in bytes.
See also
otMessageFree
otMessageAppend
otMessageSetLength
otMessageGetOffset
otMessageSetOffset
otMessageRead
otMessageWrite
otMessageSetLength
References Message::GetLength().
Referenced by Buffer::OutFrameGetLength(), and Buffer::OutFramePrepareSegment().
otMessageSetLength()
otError otMessageSetLength (otMessage * aMessage, uint16_t aLength)
Set the message length in bytes.
Parameters
[in] aMessage A pointer to a message buffer.
[in] aLength A length in bytes.
Return values
OT_ERROR_NONE Successfully set the message length.
OT_ERROR_NO_BUFS No available buffers to grow the message.
See also
otMessageFree
otMessageAppend
otMessageGetLength
otMessageGetOffset
otMessageSetOffset
otMessageRead
otMessageWrite
References Message::SetLength().
otMessageGetOffset()
uint16_t otMessageGetOffset (const otMessage * aMessage)
Get the message offset in bytes.
Parameters
[in] aMessage A pointer to a message buffer.
Returns
The message offset value.
See also
otMessageFree
otMessageAppend
otMessageGetLength
otMessageSetLength
otMessageSetOffset
otMessageRead
otMessageWrite
References Message::GetOffset().
otMessageSetOffset()
otError otMessageSetOffset (otMessage * aMessage, uint16_t aOffset)
Set the message offset in bytes.
Parameters
[in] aMessage A pointer to a message buffer.
[in] aOffset An offset in bytes.
Return values
OT_ERROR_NONE Successfully set the message offset.
OT_ERROR_INVALID_ARGS The offset is beyond the message length.
See also
otMessageFree
otMessageAppend
otMessageGetLength
otMessageSetLength
otMessageGetOffset
otMessageRead
otMessageWrite
References Message::SetOffset().
otMessageIsLinkSecurityEnabled()
bool otMessageIsLinkSecurityEnabled (const otMessage * aMessage)
This function indicates whether or not link security is enabled for the message.
Parameters
[in] aMessage A pointer to a message buffer.
Return values
TRUE If link security is enabled.
FALSE If link security is not enabled.
References Message::IsLinkSecurityEnabled().
otMessageSetDirectTransmission()
void otMessageSetDirectTransmission (otMessage * aMessage, bool aEnabled)
This function sets/forces the message to be forwarded using direct transmission. Default setting for a new message is false.
Parameters
[in] aMessage A pointer to a message buffer.
[in] aEnabled If true, the message is forced to use direct transmission. If false, the message follows the normal procedure.
References Message::ClearDirectTransmission(), and Message::SetDirectTransmission().
otMessageGetRss()
int8_t otMessageGetRss (const otMessage * aMessage)
This function returns the average RSS (received signal strength) associated with the message.
Returns
The average RSS value (in dBm) or OT_RADIO_RSSI_INVALID if no average RSS is available.
References Message::GetAverageRss().
otMessageAppend()
otError otMessageAppend (otMessage * aMessage, const void * aBuf, uint16_t aLength)
Append bytes to a message.
Parameters
[in] aMessage A pointer to a message buffer.
[in] aBuf A pointer to the data to append.
[in] aLength Number of bytes to append.
Return values
OT_ERROR_NONE Successfully appended to the message
OT_ERROR_NO_BUFS No available buffers to grow the message.
See also
otMessageFree
otMessageGetLength
otMessageSetLength
otMessageGetOffset
otMessageSetOffset
otMessageRead
otMessageWrite
References Message::Append().
otMessageRead()
uint16_t otMessageRead (const otMessage * aMessage, uint16_t aOffset, void * aBuf, uint16_t aLength)
Read bytes from a message.
Parameters
[in] aMessage A pointer to a message buffer.
[in] aOffset An offset in bytes.
[in] aBuf A pointer to a buffer that message bytes are read to.
[in] aLength Number of bytes to read.
Returns
The number of bytes read.
See also
otMessageFree
otMessageAppend
otMessageGetLength
otMessageSetLength
otMessageGetOffset
otMessageSetOffset
otMessageWrite
References Message::Read().
Referenced by Buffer::OutFramePrepareSegment().
otMessageWrite()
int otMessageWrite (otMessage * aMessage, uint16_t aOffset, const void * aBuf, uint16_t aLength)
Write bytes to a message.
Parameters
[in] aMessage A pointer to a message buffer.
[in] aOffset An offset in bytes.
[in] aBuf A pointer to a buffer that message bytes are written from.
[in] aLength Number of bytes to write.
Returns
The number of bytes written.
See also
otMessageFree
otMessageAppend
otMessageGetLength
otMessageSetLength
otMessageGetOffset
otMessageSetOffset
otMessageRead
References Message::Write().
otMessageQueueInit()
void otMessageQueueInit (otMessageQueue * aQueue)
Initialize the message queue.
This function MUST be called once and only once for a otMessageQueue instance before any other otMessageQueue functions. The behavior is undefined if other queue APIs are used with an otMessageQueue before it being initialized or if it is initialized more than once.
Parameters
[in] aQueue A pointer to a message queue.
References otMessageQueue::mData.
Referenced by Buffer::Buffer(), and NcpBase::NcpBase().
otMessageQueueEnqueue()
otError otMessageQueueEnqueue (otMessageQueue * aQueue, otMessage * aMessage)
This function adds a message to the end of the given message queue.
Parameters
[in] aQueue A pointer to the message queue.
[in] aMessage The message to add.
Return values
OT_ERROR_NONE Successfully added the message to the queue.
OT_ERROR_ALREADY The message is already enqueued in a queue.
References MessageQueue::Enqueue().
Referenced by Buffer::InFrameEnd(), and Buffer::InFrameFeedData().
otMessageQueueEnqueueAtHead()
otError otMessageQueueEnqueueAtHead (otMessageQueue * aQueue, otMessage * aMessage)
This function adds a message at the head/front of the given message queue.
Parameters
[in] aQueue A pointer to the message queue.
[in] aMessage The message to add.
Return values
OT_ERROR_NONE Successfully added the message to the queue.
OT_ERROR_ALREADY The message is already enqueued in a queue.
References MessageQueue::Enqueue(), and MessageQueue::kQueuePositionHead.
otMessageQueueDequeue()
otError otMessageQueueDequeue (otMessageQueue * aQueue, otMessage * aMessage)
This function removes a message from the given message queue.
Parameters
[in] aQueue A pointer to the message queue.
[in] aMessage The message to remove.
Return values
OT_ERROR_NONE Successfully removed the message from the queue.
OT_ERROR_NOT_FOUND The message is not enqueued in this queue.
References MessageQueue::Dequeue().
Referenced by Buffer::Clear(), Buffer::InFrameDiscard(), Buffer::InFrameEnd(), and Buffer::OutFrameRemove().
otMessageQueueGetHead()
otMessage* otMessageQueueGetHead (otMessageQueue * aQueue)
This function returns a pointer to the message at the head of the queue.
Parameters
[in] aQueue A pointer to a message queue.
Returns
A pointer to the message at the head of queue or NULL if queue is empty.
References MessageQueue::GetHead().
Referenced by Buffer::Clear(), Buffer::InFrameDiscard(), Buffer::InFrameEnd(), Buffer::OutFrameGetLength(), Buffer::OutFramePrepareSegment(), and Buffer::OutFrameRemove().
otMessageQueueGetNext()
otMessage* otMessageQueueGetNext (otMessageQueue * aQueue, const otMessage * aMessage)
This function returns a pointer to the next message in the queue by iterating forward (from head to tail).
Parameters
[in] aQueue A pointer to a message queue.
[in] aMessage A pointer to current message buffer.
Returns
A pointer to the next message in the queue after aMessage or NULL if aMessage is the tail of queue. NULL is returned ifaMessageis not in the queueaQueue`.
References Instance::Get(), Message::GetMessageQueue(), Message::GetNext(), otBufferInfo::m6loReassemblyBuffers, otBufferInfo::m6loReassemblyMessages, otBufferInfo::m6loSendBuffers, otBufferInfo::m6loSendMessages, otBufferInfo::mApplicationCoapBuffers, otBufferInfo::mApplicationCoapMessages, otBufferInfo::mArpBuffers, otBufferInfo::mArpMessages, otBufferInfo::mCoapBuffers, otBufferInfo::mCoapMessages, otBufferInfo::mCoapSecureBuffers, otBufferInfo::mCoapSecureMessages, otBufferInfo::mFreeBuffers, otBufferInfo::mIp6Buffers, otBufferInfo::mIp6Messages, otBufferInfo::mMleBuffers, otBufferInfo::mMleMessages, otBufferInfo::mMplBuffers, otBufferInfo::mMplMessages, otBufferInfo::mTotalBuffers, OPENTHREAD_CONFIG_NUM_MESSAGE_BUFFERS, otMessageGetBufferInfo(), and VerifyOrExit.
Referenced by Buffer::OutFrameGetLength(), and Buffer::OutFramePrepareSegment().
otMessageGetBufferInfo()
void otMessageGetBufferInfo (otInstance * aInstance, otBufferInfo * aBufferInfo)
Get the Message Buffer information.
Parameters
[in] aInstance A pointer to the OpenThread instance.
[out] aBufferInfo A pointer where the message buffer information is written.
Referenced by otMessageQueueGetNext().
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale