OpenThread: Logging
Logging
API » Add-Ons
This module includes OpenThread logging related definitions.
Functions
otLogLevel otLoggingGetLevel (void)
otError otLoggingSetLevel (otLogLevel aLogLevel)
Detailed Description
This module includes OpenThread logging related definitions.
Function Documentation
otLoggingGetLevel()
otLogLevel otLoggingGetLevel (void)
This function returns the current log level.
If dynamic log level feature OPENTHREAD_CONFIG_LOG_LEVEL_DYNAMIC_ENABLE is enabled, this function returns the currently set dynamic log level. Otherwise, this function returns the build-time configured log level.
Returns
The log level.
References Instance::Get(), Instance::GetLogLevel(), OPENTHREAD_CONFIG_LOG_LEVEL, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, OT_LOG_LEVEL_NONE, and otLoggingSetLevel().
Referenced by NcpBase::HandlePropertyGet().
otLoggingSetLevel()
otError otLoggingSetLevel (otLogLevel aLogLevel)
This function sets the log level.
Note
This function requires OPENTHREAD_CONFIG_LOG_LEVEL_DYNAMIC_ENABLE=1.
Parameters
[in] aLogLevel The log level.
Return values
OT_ERROR_NONE Successfully updated log level.
OT_ERROR_INVALID_ARGS Log level value is invalid.
Referenced by NcpBase::HandlePropertyGet(), InitInstance(), and otLoggingGetLevel().
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale