OpenThread: General
General
API » Thread
This module includes functions for all Thread roles.
Data Structures
struct otBorderRouterConfig
struct otExtendedPanId
struct otExternalRouteConfig
struct otIpCounters
struct otLeaderData
struct otLinkModeConfig
struct otMasterKey
struct otMeshLocalPrefix
struct otMleCounters
struct otNeighborInfo
struct otNetworkDiagChildEntry
struct otNetworkDiagConnectivity
struct otNetworkDiagMacCounters
struct otNetworkDiagRoute
struct otNetworkDiagRouteData
struct otNetworkDiagTlv
struct otNetworkName
struct otOperationalDataset
struct otOperationalDatasetComponents
struct otPskc
struct otRouterInfo
struct otSecurityPolicy
struct otServerConfig
struct otServiceConfig
struct otThreadParentResponseInfo
Macros
#define OT_CHANNEL_10_MASK (1 << 10)
Channel 10.
#define OT_CHANNEL_11_MASK (1 << 11)
Channel 11.
#define OT_CHANNEL_12_MASK (1 << 12)
Channel 12.
#define OT_CHANNEL_13_MASK (1 << 13)
Channel 13.
#define OT_CHANNEL_14_MASK (1 << 14)
Channel 14.
#define OT_CHANNEL_15_MASK (1 << 15)
Channel 15.
#define OT_CHANNEL_16_MASK (1 << 16)
Channel 16.
#define OT_CHANNEL_17_MASK (1 << 17)
Channel 17.
#define OT_CHANNEL_18_MASK (1 << 18)
Channel 18.
#define OT_CHANNEL_19_MASK (1 << 19)
Channel 19.
#define OT_CHANNEL_1_MASK (1 << 1)
Channel 1.
#define OT_CHANNEL_20_MASK (1 << 20)
Channel 20.
#define OT_CHANNEL_21_MASK (1 << 21)
Channel 21.
#define OT_CHANNEL_22_MASK (1 << 22)
Channel 22.
#define OT_CHANNEL_23_MASK (1 << 23)
Channel 23.
#define OT_CHANNEL_24_MASK (1 << 24)
Channel 24.
#define OT_CHANNEL_25_MASK (1 << 25)
Channel 25.
#define OT_CHANNEL_26_MASK (1 << 26)
Channel 26.
#define OT_CHANNEL_2_MASK (1 << 2)
Channel 2.
#define OT_CHANNEL_3_MASK (1 << 3)
Channel 3.
#define OT_CHANNEL_4_MASK (1 << 4)
Channel 4.
#define OT_CHANNEL_5_MASK (1 << 5)
Channel 5.
#define OT_CHANNEL_6_MASK (1 << 6)
Channel 6.
#define OT_CHANNEL_7_MASK (1 << 7)
Channel 7.
#define OT_CHANNEL_8_MASK (1 << 8)
Channel 8.
#define OT_CHANNEL_9_MASK (1 << 9)
Channel 9.
#define OT_EXT_PAN_ID_SIZE 8
Size of a Thread PAN ID (bytes)
#define OT_MASTER_KEY_SIZE 16
Size of the Thread Master Key (bytes)
#define OT_MESH_LOCAL_PREFIX_SIZE 8
Size of the Mesh Local Prefix (bytes)
#define OT_NEIGHBOR_INFO_ITERATOR_INIT 0
Initializer for otNeighborInfoIterator.
#define OT_NETWORK_BASE_TLV_MAX_LENGTH 254
#define OT_NETWORK_DATA_ITERATOR_INIT 0
Initializer for otNetworkDataIterator.
#define OT_NETWORK_DIAGNOSTIC_CHILD_TABLE_ENTRY_SIZE 3
#define OT_NETWORK_DIAGNOSTIC_ITERATOR_INIT 0
#define OT_NETWORK_DIAGNOSTIC_TYPELIST_MAX_ENTRIES 19
#define OT_NETWORK_MAX_ROUTER_ID 62
Maximum Router ID.
#define OT_NETWORK_NAME_MAX_SIZE 16
Maximum size of the Thread Network Name field (bytes)
#define OT_PSKC_MAX_SIZE 16
Maximum size of the PSKc (bytes)
#define OT_SERVER_DATA_MAX_SIZE 248
Maximum size of Server Data in bytes. This is theoretical limit, practical one is much lower.
#define OT_SERVICE_DATA_MAX_SIZE 252
Maximum size of Service Data in bytes.
Typedefs
typedef struct otBorderRouterConfig otBorderRouterConfig
typedef uint32_t otChannelMask
typedef struct otExtendedPanId otExtendedPanId
typedef struct otExternalRouteConfig otExternalRouteConfig
typedef struct otIpCounters otIpCounters
typedef struct otLeaderData otLeaderData
typedef struct otLinkModeConfig otLinkModeConfig
typedef struct otMasterKey otMasterKey
typedef enum otMeshcopTlvType otMeshcopTlvType
typedef struct otMeshLocalPrefix otMeshLocalPrefix
typedef struct otMleCounters otMleCounters
typedef int16_t otNeighborInfoIterator
Used to iterate through neighbor table.
typedef uint32_t otNetworkDataIterator
Used to iterate through Network Data information.
typedef struct otNetworkDiagChildEntry otNetworkDiagChildEntry
typedef struct otNetworkDiagConnectivity otNetworkDiagConnectivity
typedef uint16_t otNetworkDiagIterator
Used to iterate through Network Diagnostic TLV.
typedef struct otNetworkDiagMacCounters otNetworkDiagMacCounters
typedef struct otNetworkDiagRoute otNetworkDiagRoute
typedef struct otNetworkDiagRouteData otNetworkDiagRouteData
typedef struct otNetworkDiagTlv otNetworkDiagTlv
typedef struct otNetworkName otNetworkName
typedef struct otOperationalDataset otOperationalDataset
typedef struct otOperationalDatasetComponents otOperationalDatasetComponents
typedef struct otPskc otPskc
typedef void(* otReceiveDiagnosticGetCallback) (otMessage *aMessage, const otMessageInfo *aMessageInfo, void *aContext)
typedef enum otRoutePreference otRoutePreference
typedef struct otSecurityPolicy otSecurityPolicy
typedef struct otServerConfig otServerConfig
typedef struct otServiceConfig otServiceConfig
typedef void(* otThreadParentResponseCallback) (otThreadParentResponseInfo *aInfo, void *aContext)
typedef struct otThreadParentResponseInfo otThreadParentResponseInfo
Enumerations
enum {
OT_SECURITY_POLICY_OBTAIN_MASTER_KEY = 1 << 7, OT_SECURITY_POLICY_NATIVE_COMMISSIONING = 1 << 6, OT_SECURITY_POLICY_ROUTERS = 1 << 5, OT_SECURITY_POLICY_EXTERNAL_COMMISSIONER = 1 << 4,
OT_SECURITY_POLICY_BEACONS = 1 << 3
}
enum {
OT_NETWORK_DIAGNOSTIC_TLV_EXT_ADDRESS = 0, OT_NETWORK_DIAGNOSTIC_TLV_SHORT_ADDRESS = 1, OT_NETWORK_DIAGNOSTIC_TLV_MODE = 2, OT_NETWORK_DIAGNOSTIC_TLV_TIMEOUT = 3,
OT_NETWORK_DIAGNOSTIC_TLV_CONNECTIVITY = 4, OT_NETWORK_DIAGNOSTIC_TLV_ROUTE = 5, OT_NETWORK_DIAGNOSTIC_TLV_LEADER_DATA = 6, OT_NETWORK_DIAGNOSTIC_TLV_NETWORK_DATA = 7,
OT_NETWORK_DIAGNOSTIC_TLV_IP6_ADDR_LIST = 8, OT_NETWORK_DIAGNOSTIC_TLV_MAC_COUNTERS = 9, OT_NETWORK_DIAGNOSTIC_TLV_BATTERY_LEVEL = 14, OT_NETWORK_DIAGNOSTIC_TLV_SUPPLY_VOLTAGE = 15,
OT_NETWORK_DIAGNOSTIC_TLV_CHILD_TABLE = 16, OT_NETWORK_DIAGNOSTIC_TLV_CHANNEL_PAGES = 17, OT_NETWORK_DIAGNOSTIC_TLV_TYPE_LIST = 18, OT_NETWORK_DIAGNOSTIC_TLV_MAX_CHILD_TIMEOUT = 19
}
enum otDeviceRole {
OT_DEVICE_ROLE_DISABLED = 0, OT_DEVICE_ROLE_DETACHED = 1, OT_DEVICE_ROLE_CHILD = 2, OT_DEVICE_ROLE_ROUTER = 3,
OT_DEVICE_ROLE_LEADER = 4
}
enum otMeshcopTlvType {
OT_MESHCOP_TLV_CHANNEL = 0, OT_MESHCOP_TLV_PANID = 1, OT_MESHCOP_TLV_EXTPANID = 2, OT_MESHCOP_TLV_NETWORKNAME = 3,
OT_MESHCOP_TLV_PSKC = 4, OT_MESHCOP_TLV_MASTERKEY = 5, OT_MESHCOP_TLV_NETWORK_KEY_SEQUENCE = 6, OT_MESHCOP_TLV_MESHLOCALPREFIX = 7,
OT_MESHCOP_TLV_STEERING_DATA = 8, OT_MESHCOP_TLV_BORDER_AGENT_RLOC = 9, OT_MESHCOP_TLV_COMMISSIONER_ID = 10, OT_MESHCOP_TLV_COMM_SESSION_ID = 11,
OT_MESHCOP_TLV_SECURITYPOLICY = 12, OT_MESHCOP_TLV_GET = 13, OT_MESHCOP_TLV_ACTIVETIMESTAMP = 14, OT_MESHCOP_TLV_COMMISSIONER_UDP_PORT = 15,
OT_MESHCOP_TLV_STATE = 16, OT_MESHCOP_TLV_JOINER_DTLS = 17, OT_MESHCOP_TLV_JOINER_UDP_PORT = 18, OT_MESHCOP_TLV_JOINER_IID = 19,
OT_MESHCOP_TLV_JOINER_RLOC = 20, OT_MESHCOP_TLV_JOINER_ROUTER_KEK = 21, OT_MESHCOP_TLV_PROVISIONING_URL = 32, OT_MESHCOP_TLV_VENDOR_NAME_TLV = 33,
OT_MESHCOP_TLV_VENDOR_MODEL_TLV = 34, OT_MESHCOP_TLV_VENDOR_SW_VERSION_TLV = 35, OT_MESHCOP_TLV_VENDOR_DATA_TLV = 36, OT_MESHCOP_TLV_VENDOR_STACK_VERSION_TLV = 37,
OT_MESHCOP_TLV_UDP_ENCAPSULATION_TLV = 48, OT_MESHCOP_TLV_IPV6_ADDRESS_TLV = 49, OT_MESHCOP_TLV_PENDINGTIMESTAMP = 51, OT_MESHCOP_TLV_DELAYTIMER = 52,
OT_MESHCOP_TLV_CHANNELMASK = 53, OT_MESHCOP_TLV_COUNT = 54, OT_MESHCOP_TLV_PERIOD = 55, OT_MESHCOP_TLV_SCAN_DURATION = 56,
OT_MESHCOP_TLV_ENERGY_LIST = 57, OT_MESHCOP_TLV_DISCOVERYREQUEST = 128, OT_MESHCOP_TLV_DISCOVERYRESPONSE = 129
}
enum otRoutePreference { OT_ROUTE_PREFERENCE_LOW = -1, OT_ROUTE_PREFERENCE_MED = 0, OT_ROUTE_PREFERENCE_HIGH = 1 }
Functions
otError otDatasetCreateNewNetwork (otInstance *aInstance, otOperationalDataset *aDataset)
otError otDatasetGeneratePskc (const char *aPassPhrase, const otNetworkName *aNetworkName, const otExtendedPanId *aExtPanId, otPskc *aPskc)
otError otDatasetGetActive (otInstance *aInstance, otOperationalDataset *aDataset)
uint32_t otDatasetGetDelayTimerMinimal (otInstance *aInstance)
otError otDatasetGetPending (otInstance *aInstance, otOperationalDataset *aDataset)
bool otDatasetIsCommissioned (otInstance *aInstance)
otError otDatasetSendMgmtActiveGet (otInstance *aInstance, const otOperationalDatasetComponents *aDatasetComponents, const uint8_t *aTlvTypes, uint8_t aLength, const otIp6Address *aAddress)
otError otDatasetSendMgmtActiveSet (otInstance *aInstance, const otOperationalDataset *aDataset, const uint8_t *aTlvs, uint8_t aLength)
otError otDatasetSendMgmtPendingGet (otInstance *aInstance, const otOperationalDatasetComponents *aDatasetComponents, const uint8_t *aTlvTypes, uint8_t aLength, const otIp6Address *aAddress)
otError otDatasetSendMgmtPendingSet (otInstance *aInstance, const otOperationalDataset *aDataset, const uint8_t *aTlvs, uint8_t aLength)
otError otDatasetSetActive (otInstance *aInstance, const otOperationalDataset *aDataset)
otError otDatasetSetDelayTimerMinimal (otInstance *aInstance, uint32_t aDelayTimerMinimal)
otError otDatasetSetPending (otInstance *aInstance, const otOperationalDataset *aDataset)
otError otNetDataGet (otInstance *aInstance, bool aStable, uint8_t *aData, uint8_t *aDataLength)
otError otNetDataGetNextOnMeshPrefix (otInstance *aInstance, otNetworkDataIterator *aIterator, otBorderRouterConfig *aConfig)
otError otNetDataGetNextRoute (otInstance *aInstance, otNetworkDataIterator *aIterator, otExternalRouteConfig *aConfig)
otError otNetDataGetNextService (otInstance *aInstance, otNetworkDataIterator *aIterator, otServiceConfig *aConfig)
uint8_t otNetDataGetStableVersion (otInstance *aInstance)
uint8_t otNetDataGetVersion (otInstance *aInstance)
otError otThreadBecomeChild (otInstance *aInstance)
otError otThreadBecomeDetached (otInstance *aInstance)
otError otThreadDiscover (otInstance *aInstance, uint32_t aScanChannels, uint16_t aPanId, bool aJoiner, bool aEnableEui64Filtering, otHandleActiveScanResult aCallback, void *aCallbackContext)
uint32_t otThreadGetChildTimeout (otInstance *aInstance)
otDeviceRole otThreadGetDeviceRole (otInstance *aInstance)
const char * otThreadGetDomainName (otInstance *aInstance)
const otExtendedPanId * otThreadGetExtendedPanId (otInstance *aInstance)
const otIpCounters * otThreadGetIp6Counters (otInstance *aInstance)
uint32_t otThreadGetKeySequenceCounter (otInstance *aInstance)
uint32_t otThreadGetKeySwitchGuardTime (otInstance *aInstance)
otError otThreadGetLeaderData (otInstance *aInstance, otLeaderData *aLeaderData)
otError otThreadGetLeaderRloc (otInstance *aInstance, otIp6Address *aLeaderRloc)
uint8_t otThreadGetLeaderRouterId (otInstance *aInstance)
uint8_t otThreadGetLeaderWeight (otInstance *aInstance)
const otIp6Address * otThreadGetLinkLocalIp6Address (otInstance *aInstance)
otLinkModeConfig otThreadGetLinkMode (otInstance *aInstance)
const otMasterKey * otThreadGetMasterKey (otInstance *aInstance)
const otIp6Address * otThreadGetMeshLocalEid (otInstance *aInstance)
const otMeshLocalPrefix * otThreadGetMeshLocalPrefix (otInstance *aInstance)
const otMleCounters * otThreadGetMleCounters (otInstance *aInstance)
const char * otThreadGetNetworkName (otInstance *aInstance)
otError otThreadGetNextDiagnosticTlv (const otMessage *aMessage, otNetworkDiagIterator *aIterator, otNetworkDiagTlv *aNetworkDiagTlv)
otError otThreadGetNextNeighborInfo (otInstance *aInstance, otNeighborInfoIterator *aIterator, otNeighborInfo *aInfo)
otError otThreadGetParentAverageRssi (otInstance *aInstance, int8_t *aParentRssi)
otError otThreadGetParentInfo (otInstance *aInstance, otRouterInfo *aParentInfo)
otError otThreadGetParentLastRssi (otInstance *aInstance, int8_t *aLastRssi)
uint32_t otThreadGetPartitionId (otInstance *aInstance)
const otIp6Address * otThreadGetRloc (otInstance *aInstance)
uint16_t otThreadGetRloc16 (otInstance *aInstance)
uint16_t otThreadGetVersion (void)
bool otThreadIsDiscoverInProgress (otInstance *aInstance)
bool otThreadIsSingleton (otInstance *aInstance)
void otThreadRegisterParentResponseCallback (otInstance *aInstance, otThreadParentResponseCallback aCallback, void *aContext)
void otThreadResetIp6Counters (otInstance *aInstance)
void otThreadResetMleCounters (otInstance *aInstance)
otError otThreadSendDiagnosticGet (otInstance *aInstance, const otIp6Address *aDestination, const uint8_t aTlvTypes[], uint8_t aCount)
otError otThreadSendDiagnosticReset (otInstance *aInstance, const otIp6Address *aDestination, const uint8_t aTlvTypes[], uint8_t aCount)
void otThreadSetChildTimeout (otInstance *aInstance, uint32_t aTimeout)
otError otThreadSetDomainName (otInstance *aInstance, const char *aDomainName)
otError otThreadSetEnabled (otInstance *aInstance, bool aEnabled)
otError otThreadSetExtendedPanId (otInstance *aInstance, const otExtendedPanId *aExtendedPanId)
void otThreadSetKeySequenceCounter (otInstance *aInstance, uint32_t aKeySequenceCounter)
void otThreadSetKeySwitchGuardTime (otInstance *aInstance, uint32_t aKeySwitchGuardTime)
otError otThreadSetLinkMode (otInstance *aInstance, otLinkModeConfig aConfig)
otError otThreadSetMasterKey (otInstance *aInstance, const otMasterKey *aKey)
otError otThreadSetMeshLocalPrefix (otInstance *aInstance, const otMeshLocalPrefix *aMeshLocalPrefix)
otError otThreadSetNetworkName (otInstance *aInstance, const char *aNetworkName)
void otThreadSetReceiveDiagnosticGetCallback (otInstance *aInstance, otReceiveDiagnosticGetCallback aCallback, void *aCallbackContext)
Variables
OT_TOOL_PACKED_BEGIN struct otMasterKey OT_TOOL_PACKED_END
Detailed Description
This module includes functions for all Thread roles.
Note
The functions in this module require OPENTHREAD_FTD=1 or OPENTHREAD_MTD=1.
Macro Definition Documentation
OT_MASTER_KEY_SIZE
#define OT_MASTER_KEY_SIZE 16
Size of the Thread Master Key (bytes)
Referenced by Dataset::ProcessMasterKey(), Dataset::ProcessMgmtSetCommand(), and RadioSpinel< InterfaceType, ProcessContextType >::ThreadDatasetHandler().
OT_NETWORK_NAME_MAX_SIZE
#define OT_NETWORK_NAME_MAX_SIZE 16
Maximum size of the Thread Network Name field (bytes)
Referenced by ot::MeshCoP::GetBorderAgentRloc(), Dataset::ProcessMgmtSetCommand(), Dataset::ProcessNetworkName(), and RadioSpinel< InterfaceType, ProcessContextType >::ThreadDatasetHandler().
OT_EXT_PAN_ID_SIZE
#define OT_EXT_PAN_ID_SIZE 8
Size of a Thread PAN ID (bytes)
Referenced by ot::MeshCoP::GetBorderAgentRloc(), Dataset::ProcessExtPanId(), and RadioSpinel< InterfaceType, ProcessContextType >::ThreadDatasetHandler().
OT_MESH_LOCAL_PREFIX_SIZE
#define OT_MESH_LOCAL_PREFIX_SIZE 8
Size of the Mesh Local Prefix (bytes)
Referenced by RadioSpinel< InterfaceType, ProcessContextType >::ThreadDatasetHandler().
OT_PSKC_MAX_SIZE
#define OT_PSKC_MAX_SIZE 16
Maximum size of the PSKc (bytes)
Referenced by ot::MeshCoP::GetBorderAgentRloc(), and RadioSpinel< InterfaceType, ProcessContextType >::ThreadDatasetHandler().
OT_CHANNEL_1_MASK
#define OT_CHANNEL_1_MASK (1 << 1)
Channel 1.
OT_CHANNEL_2_MASK
#define OT_CHANNEL_2_MASK (1 << 2)
Channel 2.
OT_CHANNEL_3_MASK
#define OT_CHANNEL_3_MASK (1 << 3)
Channel 3.
OT_CHANNEL_4_MASK
#define OT_CHANNEL_4_MASK (1 << 4)
Channel 4.
OT_CHANNEL_5_MASK
#define OT_CHANNEL_5_MASK (1 << 5)
Channel 5.
OT_CHANNEL_6_MASK
#define OT_CHANNEL_6_MASK (1 << 6)
Channel 6.
OT_CHANNEL_7_MASK
#define OT_CHANNEL_7_MASK (1 << 7)
Channel 7.
OT_CHANNEL_8_MASK
#define OT_CHANNEL_8_MASK (1 << 8)
Channel 8.
OT_CHANNEL_9_MASK
#define OT_CHANNEL_9_MASK (1 << 9)
Channel 9.
OT_CHANNEL_10_MASK
#define OT_CHANNEL_10_MASK (1 << 10)
Channel 10.
OT_CHANNEL_11_MASK
#define OT_CHANNEL_11_MASK (1 << 11)
Channel 11.
OT_CHANNEL_12_MASK
#define OT_CHANNEL_12_MASK (1 << 12)
Channel 12.
OT_CHANNEL_13_MASK
#define OT_CHANNEL_13_MASK (1 << 13)
Channel 13.
OT_CHANNEL_14_MASK
#define OT_CHANNEL_14_MASK (1 << 14)
Channel 14.
OT_CHANNEL_15_MASK
#define OT_CHANNEL_15_MASK (1 << 15)
Channel 15.
OT_CHANNEL_16_MASK
#define OT_CHANNEL_16_MASK (1 << 16)
Channel 16.
OT_CHANNEL_17_MASK
#define OT_CHANNEL_17_MASK (1 << 17)
Channel 17.
OT_CHANNEL_18_MASK
#define OT_CHANNEL_18_MASK (1 << 18)
Channel 18.
OT_CHANNEL_19_MASK
#define OT_CHANNEL_19_MASK (1 << 19)
Channel 19.
OT_CHANNEL_20_MASK
#define OT_CHANNEL_20_MASK (1 << 20)
Channel 20.
OT_CHANNEL_21_MASK
#define OT_CHANNEL_21_MASK (1 << 21)
Channel 21.
OT_CHANNEL_22_MASK
#define OT_CHANNEL_22_MASK (1 << 22)
Channel 22.
OT_CHANNEL_23_MASK
#define OT_CHANNEL_23_MASK (1 << 23)
Channel 23.
OT_CHANNEL_24_MASK
#define OT_CHANNEL_24_MASK (1 << 24)
Channel 24.
OT_CHANNEL_25_MASK
#define OT_CHANNEL_25_MASK (1 << 25)
Channel 25.
OT_CHANNEL_26_MASK
#define OT_CHANNEL_26_MASK (1 << 26)
Channel 26.
OT_NETWORK_DATA_ITERATOR_INIT
#define OT_NETWORK_DATA_ITERATOR_INIT 0
Initializer for otNetworkDataIterator.
OT_SERVICE_DATA_MAX_SIZE
#define OT_SERVICE_DATA_MAX_SIZE 252
Maximum size of Service Data in bytes.
OT_SERVER_DATA_MAX_SIZE
#define OT_SERVER_DATA_MAX_SIZE 248
Maximum size of Server Data in bytes. This is theoretical limit, practical one is much lower.
OT_NETWORK_DIAGNOSTIC_TYPELIST_MAX_ENTRIES
#define OT_NETWORK_DIAGNOSTIC_TYPELIST_MAX_ENTRIES 19
Maximum Number of Network Diagnostic TLV Types to Request or Reset.
OT_NETWORK_DIAGNOSTIC_CHILD_TABLE_ENTRY_SIZE
#define OT_NETWORK_DIAGNOSTIC_CHILD_TABLE_ENTRY_SIZE 3
Size of Network Diagnostic Child Table entry.
OT_NETWORK_DIAGNOSTIC_ITERATOR_INIT
#define OT_NETWORK_DIAGNOSTIC_ITERATOR_INIT 0
Initializer for otNetworkDiagIterator.
OT_NETWORK_BASE_TLV_MAX_LENGTH
#define OT_NETWORK_BASE_TLV_MAX_LENGTH 254
Maximum value length of Thread Base TLV.
OT_NETWORK_MAX_ROUTER_ID
#define OT_NETWORK_MAX_ROUTER_ID 62
Maximum Router ID.
OT_NEIGHBOR_INFO_ITERATOR_INIT
#define OT_NEIGHBOR_INFO_ITERATOR_INIT 0
Initializer for otNeighborInfoIterator.
Typedef Documentation
otMasterKey
typedef struct otMasterKey otMasterKey
This structure represents a Thread Master Key.
otNetworkName
typedef struct otNetworkName otNetworkName
This structure represents a Network Name.
otExtendedPanId
typedef struct otExtendedPanId otExtendedPanId
This structure represents an Extended PAN ID.
otMeshLocalPrefix
typedef struct otMeshLocalPrefix otMeshLocalPrefix
This structure represents a Mesh Local Prefix.
otPskc
typedef struct otPskc otPskc
This structure represents a PSKc.
otSecurityPolicy
typedef struct otSecurityPolicy otSecurityPolicy
This structure represent Security Policy.
otChannelMask
typedef uint32_t otChannelMask
This type represents Channel Mask.
otOperationalDatasetComponents
typedef struct otOperationalDatasetComponents otOperationalDatasetComponents
This structure represents presence of different components in Active or Pending Operational Dataset.
otOperationalDataset
typedef struct otOperationalDataset otOperationalDataset
This structure represents an Active or Pending Operational Dataset.
Components in Dataset are optional. mComponets structure specifies which components are present in the Dataset.
otMeshcopTlvType
typedef enum otMeshcopTlvType otMeshcopTlvType
This enumeration represents meshcop TLV types.
otNetworkDataIterator
typedef uint32_t otNetworkDataIterator
Used to iterate through Network Data information.
otBorderRouterConfig
typedef struct otBorderRouterConfig otBorderRouterConfig
This structure represents a Border Router configuration.
otExternalRouteConfig
typedef struct otExternalRouteConfig otExternalRouteConfig
This structure represents an External Route configuration.
otRoutePreference
typedef enum otRoutePreference otRoutePreference
Defines valid values for member mPreference in otExternalRouteConfig and otBorderRouterConfig.
otServerConfig
typedef struct otServerConfig otServerConfig
This structure represents a Server configuration.
otServiceConfig
typedef struct otServiceConfig otServiceConfig
This structure represents a Service configuration.
otNetworkDiagIterator
typedef uint16_t otNetworkDiagIterator
Used to iterate through Network Diagnostic TLV.
otNetworkDiagConnectivity
typedef struct otNetworkDiagConnectivity otNetworkDiagConnectivity
This structure represents a Network Diagnostic Connectivity value.
otNetworkDiagRouteData
typedef struct otNetworkDiagRouteData otNetworkDiagRouteData
This structure represents a Network Diagnostic Route data.
otNetworkDiagRoute
typedef struct otNetworkDiagRoute otNetworkDiagRoute
This structure represents a Network Diagnostic Route TLV value.
otNetworkDiagMacCounters
typedef struct otNetworkDiagMacCounters otNetworkDiagMacCounters
This structure represents a Network Diagnostic Mac Counters value.
See RFC 2863 for definitions of member fields.
otNetworkDiagChildEntry
typedef struct otNetworkDiagChildEntry otNetworkDiagChildEntry
This structure represents a Network Diagnostic Child Table Entry.
otNetworkDiagTlv
typedef struct otNetworkDiagTlv otNetworkDiagTlv
This structure represents a Network Diagnostic TLV.
otReceiveDiagnosticGetCallback
typedef void(* otReceiveDiagnosticGetCallback) (otMessage *aMessage, const otMessageInfo *aMessageInfo, void *aContext)
This function pointer is called when Network Diagnostic Get response is received.
Parameters
[in] aMessage A pointer to the message buffer containing the received Network Diagnostic Get response payload.
[in] aMessageInfo A pointer to the message info for aMessage.
[in] aContext A pointer to application-specific context.
otLinkModeConfig
typedef struct otLinkModeConfig otLinkModeConfig
This structure represents an MLE Link Mode configuration.
otNeighborInfoIterator
typedef int16_t otNeighborInfoIterator
Used to iterate through neighbor table.
otLeaderData
typedef struct otLeaderData otLeaderData
This structure represents the Thread Leader Data.
otIpCounters
typedef struct otIpCounters otIpCounters
This structure represents the IP level counters.
otMleCounters
typedef struct otMleCounters otMleCounters
This structure represents the Thread MLE counters.
otThreadParentResponseInfo
typedef struct otThreadParentResponseInfo otThreadParentResponseInfo
This structure represents the MLE Parent Response data.
otThreadParentResponseCallback
typedef void(* otThreadParentResponseCallback) (otThreadParentResponseInfo *aInfo, void *aContext)
This function pointer is called every time an MLE Parent Response message is received.
Parameters
[in] aStats pointer to a location on stack holding the stats data.
[in] aContext A pointer to callback client-specific context.
Enumeration Type Documentation
anonymous enum
anonymous enum
This enumeration defines the Security Policy TLV flags.
Enumerator
OT_SECURITY_POLICY_OBTAIN_MASTER_KEY
Obtaining the Master Key.
OT_SECURITY_POLICY_NATIVE_COMMISSIONING
Native Commissioning.
OT_SECURITY_POLICY_ROUTERS
Routers enabled.
OT_SECURITY_POLICY_EXTERNAL_COMMISSIONER
External Commissioner allowed.
OT_SECURITY_POLICY_BEACONS
Beacons enabled.
otMeshcopTlvType
enum otMeshcopTlvType
This enumeration represents meshcop TLV types.
Enumerator
OT_MESHCOP_TLV_CHANNEL
meshcop Channel TLV
OT_MESHCOP_TLV_PANID
meshcop Pan Id TLV
OT_MESHCOP_TLV_EXTPANID
meshcop Extended Pan Id TLV
OT_MESHCOP_TLV_NETWORKNAME
meshcop Network Name TLV
OT_MESHCOP_TLV_PSKC
meshcop PSKc TLV
OT_MESHCOP_TLV_MASTERKEY
meshcop Network Master Key TLV
OT_MESHCOP_TLV_NETWORK_KEY_SEQUENCE
meshcop Network Key Sequence TLV
OT_MESHCOP_TLV_MESHLOCALPREFIX
meshcop Mesh Local Prefix TLV
OT_MESHCOP_TLV_STEERING_DATA
meshcop Steering Data TLV
OT_MESHCOP_TLV_BORDER_AGENT_RLOC
meshcop Border Agent Locator TLV
OT_MESHCOP_TLV_COMMISSIONER_ID
meshcop Commissioner ID TLV
OT_MESHCOP_TLV_COMM_SESSION_ID
meshcop Commissioner Session ID TLV
OT_MESHCOP_TLV_SECURITYPOLICY
meshcop Security Policy TLV
OT_MESHCOP_TLV_GET
meshcop Get TLV
OT_MESHCOP_TLV_ACTIVETIMESTAMP
meshcop Active Timestamp TLV
OT_MESHCOP_TLV_COMMISSIONER_UDP_PORT
meshcop Commissioner UDP Port TLV
OT_MESHCOP_TLV_STATE
meshcop State TLV
OT_MESHCOP_TLV_JOINER_DTLS
meshcop Joiner DTLS Encapsulation TLV
OT_MESHCOP_TLV_JOINER_UDP_PORT
meshcop Joiner UDP Port TLV
OT_MESHCOP_TLV_JOINER_IID
meshcop Joiner IID TLV
OT_MESHCOP_TLV_JOINER_RLOC
meshcop Joiner Router Locator TLV
OT_MESHCOP_TLV_JOINER_ROUTER_KEK
meshcop Joiner Router KEK TLV
OT_MESHCOP_TLV_PROVISIONING_URL
meshcop Provisioning URL TLV
OT_MESHCOP_TLV_VENDOR_NAME_TLV
meshcop Vendor Name TLV
OT_MESHCOP_TLV_VENDOR_MODEL_TLV
meshcop Vendor Model TLV
OT_MESHCOP_TLV_VENDOR_SW_VERSION_TLV
meshcop Vendor SW Version TLV
OT_MESHCOP_TLV_VENDOR_DATA_TLV
meshcop Vendor Data TLV
OT_MESHCOP_TLV_VENDOR_STACK_VERSION_TLV
meshcop Vendor Stack Version TLV
OT_MESHCOP_TLV_UDP_ENCAPSULATION_TLV
meshcop UDP encapsulation TLV
OT_MESHCOP_TLV_IPV6_ADDRESS_TLV
meshcop IPv6 address TLV
OT_MESHCOP_TLV_PENDINGTIMESTAMP
meshcop Pending Timestamp TLV
OT_MESHCOP_TLV_DELAYTIMER
meshcop Delay Timer TLV
OT_MESHCOP_TLV_CHANNELMASK
meshcop Channel Mask TLV
OT_MESHCOP_TLV_COUNT
meshcop Count TLV
OT_MESHCOP_TLV_PERIOD
meshcop Period TLV
OT_MESHCOP_TLV_SCAN_DURATION
meshcop Scan Duration TLV
OT_MESHCOP_TLV_ENERGY_LIST
meshcop Energy List TLV
OT_MESHCOP_TLV_DISCOVERYREQUEST
meshcop Discovery Request TLV
OT_MESHCOP_TLV_DISCOVERYRESPONSE
meshcop Discovery Response TLV
otRoutePreference
enum otRoutePreference
Defines valid values for member mPreference in otExternalRouteConfig and otBorderRouterConfig.
Enumerator
OT_ROUTE_PREFERENCE_LOW
Low route preference.
OT_ROUTE_PREFERENCE_MED
Medium route preference.
OT_ROUTE_PREFERENCE_HIGH
High route preference.
anonymous enum
anonymous enum
Enumerator
OT_NETWORK_DIAGNOSTIC_TLV_EXT_ADDRESS
MAC Extended Address TLV.
OT_NETWORK_DIAGNOSTIC_TLV_SHORT_ADDRESS
Address16 TLV.
OT_NETWORK_DIAGNOSTIC_TLV_MODE
Mode TLV.
OT_NETWORK_DIAGNOSTIC_TLV_TIMEOUT
Timeout TLV (the maximum polling time period for SEDs)
OT_NETWORK_DIAGNOSTIC_TLV_CONNECTIVITY
Connectivity TLV.
OT_NETWORK_DIAGNOSTIC_TLV_ROUTE
Route64 TLV.
OT_NETWORK_DIAGNOSTIC_TLV_LEADER_DATA
Leader Data TLV.
OT_NETWORK_DIAGNOSTIC_TLV_NETWORK_DATA
Network Data TLV.
OT_NETWORK_DIAGNOSTIC_TLV_IP6_ADDR_LIST
IPv6 Address List TLV.
OT_NETWORK_DIAGNOSTIC_TLV_MAC_COUNTERS
MAC Counters TLV.
OT_NETWORK_DIAGNOSTIC_TLV_BATTERY_LEVEL
Battery Level TLV.
OT_NETWORK_DIAGNOSTIC_TLV_SUPPLY_VOLTAGE
Supply Voltage TLV.
OT_NETWORK_DIAGNOSTIC_TLV_CHILD_TABLE
Child Table TLV.
OT_NETWORK_DIAGNOSTIC_TLV_CHANNEL_PAGES
Channel Pages TLV.
OT_NETWORK_DIAGNOSTIC_TLV_TYPE_LIST
Type List TLV.
OT_NETWORK_DIAGNOSTIC_TLV_MAX_CHILD_TIMEOUT
Max Child Timeout TLV.
otDeviceRole
enum otDeviceRole
Represents a Thread device role.
Enumerator
OT_DEVICE_ROLE_DISABLED
The Thread stack is disabled.
OT_DEVICE_ROLE_DETACHED
Not currently participating in a Thread network/partition.
OT_DEVICE_ROLE_CHILD
The Thread Child role.
OT_DEVICE_ROLE_ROUTER
The Thread Router role.
OT_DEVICE_ROLE_LEADER
The Thread Leader role.
Function Documentation
otDatasetIsCommissioned()
bool otDatasetIsCommissioned (otInstance * aInstance)
This function indicates whether a valid network is present in the Active Operational Dataset or not.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
TRUE if a valid network is present in the Active Operational Dataset, FALSE otherwise.
References otOperationalDataset::mComponents, otOperationalDatasetComponents::mIsChannelPresent, otOperationalDatasetComponents::mIsExtendedPanIdPresent, otOperationalDatasetComponents::mIsMasterKeyPresent, otOperationalDatasetComponents::mIsNetworkNamePresent, otOperationalDatasetComponents::mIsPanIdPresent, otDatasetGetActive(), and SuccessOrExit.
otDatasetGetActive()
otError otDatasetGetActive (otInstance * aInstance, otOperationalDataset * aDataset)
This function gets the Active Operational Dataset.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[out] aDataset A pointer to where the Active Operational Dataset will be placed.
Return values
OT_ERROR_NONE Successfully retrieved the Active Operational Dataset.
OT_ERROR_INVALID_ARGS aDataset was NULL.
References Instance::Get(), and OT_ASSERT.
Referenced by otDatasetIsCommissioned(), Dataset::ProcessActive(), and Dataset::ProcessInit().
otDatasetSetActive()
otError otDatasetSetActive (otInstance * aInstance, const otOperationalDataset * aDataset)
This function sets the Active Operational Dataset.
If the dataset does not include an Active Timestamp, the dataset is only partially complete.
If Thread is enabled on a device that has a partially complete Active Dataset, the device will attempt to attach to an existing Thread network using any existing information in the dataset. Only the Thread Master Key is needed to attach to a network.
If channel is not included in the dataset, the device will send MLE Announce messages across different channels to find neighbors on other channels.
If the device successfully attaches to a Thread network, the device will then retrieve the full Active Dataset from its Parent. Note that a router-capable device will not transition to the Router or Leader roles until it has a complete Active Dataset.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aDataset A pointer to the Active Operational Dataset.
Return values
OT_ERROR_NONE Successfully set the Active Operational Dataset.
OT_ERROR_NO_BUFS Insufficient buffer space to set the Active Operational Dataset.
OT_ERROR_INVALID_ARGS aDataset was NULL.
References Instance::Get(), and OT_ASSERT.
Referenced by Dataset::ProcessCommit().
otDatasetGetPending()
otError otDatasetGetPending (otInstance * aInstance, otOperationalDataset * aDataset)
This function gets the Pending Operational Dataset.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[out] aDataset A pointer to where the Pending Operational Dataset will be placed.
Return values
OT_ERROR_NONE Successfully retrieved the Pending Operational Dataset.
OT_ERROR_INVALID_ARGS aDataset was NULL.
References Instance::Get(), and OT_ASSERT.
Referenced by Dataset::ProcessInit(), and Dataset::ProcessPending().
otDatasetSetPending()
otError otDatasetSetPending (otInstance * aInstance, const otOperationalDataset * aDataset)
This function sets the Pending Operational Dataset.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aDataset A pointer to the Pending Operational Dataset.
Return values
OT_ERROR_NONE Successfully set the Pending Operational Dataset.
OT_ERROR_NO_BUFS Insufficient buffer space to set the Pending Operational Dataset.
OT_ERROR_INVALID_ARGS aDataset was NULL.
References Instance::Get(), and OT_ASSERT.
Referenced by Dataset::ProcessCommit().
otDatasetSendMgmtActiveGet()
otError otDatasetSendMgmtActiveGet (otInstance * aInstance, const otOperationalDatasetComponents * aDatasetComponents, const uint8_t * aTlvTypes, uint8_t aLength, const otIp6Address * aAddress)
This function sends MGMT_ACTIVE_GET.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aDatasetComponents A pointer to a Dataset Components structure specifying which components to request.
[in] aTlvTypes A pointer to array containing additional raw TLV types to be requested.
[in] aLength The length of aTlvTypes.
[in] aAddress A pointer to the IPv6 destination, if it is NULL, will use Leader ALOC as default.
Return values
OT_ERROR_NONE Successfully send the meshcop dataset command.
OT_ERROR_NO_BUFS Insufficient buffer space to send.
References Instance::Get().
Referenced by Dataset::ProcessMgmtGetCommand().
otDatasetSendMgmtActiveSet()
otError otDatasetSendMgmtActiveSet (otInstance * aInstance, const otOperationalDataset * aDataset, const uint8_t * aTlvs, uint8_t aLength)
This function sends MGMT_ACTIVE_SET.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aDataset A pointer to operational dataset.
[in] aTlvs A pointer to TLVs.
[in] aLength The length of TLVs.
Return values
OT_ERROR_NONE Successfully send the meshcop dataset command.
OT_ERROR_NO_BUFS Insufficient buffer space to send.
References Instance::Get().
Referenced by Dataset::ProcessMgmtSetCommand().
otDatasetSendMgmtPendingGet()
otError otDatasetSendMgmtPendingGet (otInstance * aInstance, const otOperationalDatasetComponents * aDatasetComponents, const uint8_t * aTlvTypes, uint8_t aLength, const otIp6Address * aAddress)
This function sends MGMT_PENDING_GET.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aDatasetComponents A pointer to a Dataset Components structure specifying which components to request.
[in] aTlvTypes A pointer to array containing additional raw TLV types to be requested.
[in] aLength The length of aTlvTypes.
[in] aAddress A pointer to the IPv6 destination, if it is NULL, will use Leader ALOC as default.
Return values
OT_ERROR_NONE Successfully send the meshcop dataset command.
OT_ERROR_NO_BUFS Insufficient buffer space to send.
References Instance::Get().
Referenced by Dataset::ProcessMgmtGetCommand().
otDatasetSendMgmtPendingSet()
otError otDatasetSendMgmtPendingSet (otInstance * aInstance, const otOperationalDataset * aDataset, const uint8_t * aTlvs, uint8_t aLength)
This function sends MGMT_PENDING_SET.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aDataset A pointer to operational dataset.
[in] aTlvs A pointer to TLVs.
[in] aLength The length of TLVs.
Return values
OT_ERROR_NONE Successfully send the meshcop dataset command.
OT_ERROR_NO_BUFS Insufficient buffer space to send.
References ot::MeshCoP::GeneratePskc(), Instance::Get(), and otDatasetGeneratePskc().
Referenced by Dataset::ProcessMgmtSetCommand().
otDatasetGeneratePskc()
otError otDatasetGeneratePskc (const char * aPassPhrase, const otNetworkName * aNetworkName, const otExtendedPanId * aExtPanId, otPskc * aPskc)
This function generates PSKc from a given pass-phrase, network name, and extended PAN ID.
PSKc is used to establish the Commissioner Session.
Parameters
[in] aPassPhrase The commissioning pass-phrase.
[in] aNetworkName The network name for PSKc computation.
[in] aExtPanId The extended PAN ID for PSKc computation.
[out] aPskc A pointer to variable to output the generated PSKc.
Return values
OT_ERROR_NONE Successfully generate PSKc.
OT_ERROR_INVALID_ARGS If any of the input arguments is invalid.
Referenced by otDatasetSendMgmtPendingSet(), and Dataset::ProcessPskc().
otDatasetCreateNewNetwork()
otError otDatasetCreateNewNetwork (otInstance * aInstance, otOperationalDataset * aDataset)
This method creates a new Operational Dataset to use when forming a new network.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[out] aDataset The Operational Dataset.
Return values
OT_ERROR_NONE Successfully created a new Operational Dataset.
OT_ERROR_FAILED Failed to generate random values for new parameters.
Referenced by Dataset::ProcessInit().
otDatasetGetDelayTimerMinimal()
uint32_t otDatasetGetDelayTimerMinimal (otInstance * aInstance)
Get minimal delay timer.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Return values
the value of minimal delay timer (in ms).
otDatasetSetDelayTimerMinimal()
otError otDatasetSetDelayTimerMinimal (otInstance * aInstance, uint32_t aDelayTimerMinimal)
Set minimal delay timer.
Note
This API is reserved for testing and demo purposes only. Changing settings with this API will render a production application non-compliant with the Thread Specification.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aDelayTimerMinimal The value of minimal delay timer (in ms).
Return values
OT_ERROR_NONE Successfully set minimal delay timer.
OT_ERROR_INVALID_ARGS If aDelayTimerMinimal is not valid.
otNetDataGet()
otError otNetDataGet (otInstance * aInstance, bool aStable, uint8_t * aData, uint8_t * aDataLength)
This method provides a full or stable copy of the Partition's Thread Network Data.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aStable TRUE when copying the stable version, FALSE when copying the full version.
[out] aData A pointer to the data buffer.
[in,out] aDataLength On entry, size of the data buffer pointed to by aData. On exit, number of copied bytes.
References Instance::Get(), and OT_ASSERT.
otNetDataGetNextOnMeshPrefix()
otError otNetDataGetNextOnMeshPrefix (otInstance * aInstance, otNetworkDataIterator * aIterator, otBorderRouterConfig * aConfig)
This function gets the next On Mesh Prefix in the partition's Network Data.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in,out] aIterator A pointer to the Network Data iterator context. To get the first on-mesh entry it should be set to OT_NETWORK_DATA_ITERATOR_INIT.
[out] aConfig A pointer to where the On Mesh Prefix information will be placed.
Return values
OT_ERROR_NONE Successfully found the next On Mesh prefix.
OT_ERROR_NOT_FOUND No subsequent On Mesh prefix exists in the Thread Network Data.
References Instance::Get(), OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, and VerifyOrExit.
otNetDataGetNextRoute()
otError otNetDataGetNextRoute (otInstance * aInstance, otNetworkDataIterator * aIterator, otExternalRouteConfig * aConfig)
This function gets the next external route in the partition's Network Data.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in,out] aIterator A pointer to the Network Data iterator context. To get the first external route entry it should be set to OT_NETWORK_DATA_ITERATOR_INIT.
[out] aConfig A pointer to where the External Route information will be placed.
Return values
OT_ERROR_NONE Successfully found the next External Route.
OT_ERROR_NOT_FOUND No subsequent external route entry exists in the Thread Network Data.
References Instance::Get(), OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, and VerifyOrExit.
otNetDataGetNextService()
otError otNetDataGetNextService (otInstance * aInstance, otNetworkDataIterator * aIterator, otServiceConfig * aConfig)
This function gets the next service in the partition's Network Data.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in,out] aIterator A pointer to the Network Data iterator context. To get the first service entry it should be set to OT_NETWORK_DATA_ITERATOR_INIT.
[out] aConfig A pointer to where the service information will be placed.
Return values
OT_ERROR_NONE Successfully found the next service.
OT_ERROR_NOT_FOUND No subsequent service exists in the partition's Network Data.
References Instance::Get(), OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, and VerifyOrExit.
otNetDataGetVersion()
uint8_t otNetDataGetVersion (otInstance * aInstance)
Get the Network Data Version.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
The Network Data Version.
References Instance::Get().
otNetDataGetStableVersion()
uint8_t otNetDataGetStableVersion (otInstance * aInstance)
Get the Stable Network Data Version.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
The Stable Network Data Version.
References Instance::Get().
otThreadGetNextDiagnosticTlv()
otError otThreadGetNextDiagnosticTlv (const otMessage * aMessage, otNetworkDiagIterator * aIterator, otNetworkDiagTlv * aNetworkDiagTlv)
This function gets the next Network Diagnostic TLV in the message.
Parameters
[in] aMessage A pointer to a message.
[in,out] aIterator A pointer to the Network Diagnostic iterator context. To get the first Network Diagnostic TLV it should be set to OT_NETWORK_DIAGNOSTIC_ITERATOR_INIT.
[out] aNetworkDiagTlv A pointer to where the Network Diagnostic TLV information will be placed.
Return values
OT_ERROR_NONE Successfully found the next Network Diagnostic TLV.
OT_ERROR_NOT_FOUND No subsequent Network Diagnostic TLV exists in the message.
OT_ERROR_PARSE Parsing the next Network Diagnostic failed.
A subsequent call to this function is allowed only when current return value is OT_ERROR_NONE.
otThreadSetReceiveDiagnosticGetCallback()
void otThreadSetReceiveDiagnosticGetCallback (otInstance * aInstance, otReceiveDiagnosticGetCallback aCallback, void * aCallbackContext)
This function registers a callback to provide received raw Network Diagnostic Get response payload.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aCallback A pointer to a function that is called when Network Diagnostic Get response is received or NULL to disable the callback.
[in] aCallbackContext A pointer to application-specific context.
otThreadSendDiagnosticGet()
otError otThreadSendDiagnosticGet (otInstance * aInstance, const otIp6Address * aDestination, const uint8_t aTlvTypes[], uint8_t aCount)
Send a Network Diagnostic Get request.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aDestination A pointer to destination address.
[in] aTlvTypes An array of Network Diagnostic TLV types.
[in] aCount Number of types in aTlvTypes.
Return values
OT_ERROR_NONE Successfully queued the DIAG_GET.req.
OT_ERROR_NO_BUFS Insufficient message buffers available to send DIAG_GET.req.
otThreadSendDiagnosticReset()
otError otThreadSendDiagnosticReset (otInstance * aInstance, const otIp6Address * aDestination, const uint8_t aTlvTypes[], uint8_t aCount)
Send a Network Diagnostic Reset request.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aDestination A pointer to destination address.
[in] aTlvTypes An array of Network Diagnostic TLV types. Currently only Type 9 is allowed.
[in] aCount Number of types in aTlvTypes
Return values
OT_ERROR_NONE Successfully queued the DIAG_RST.ntf.
OT_ERROR_NO_BUFS Insufficient message buffers available to send DIAG_RST.ntf.
otThreadSetEnabled()
otError otThreadSetEnabled (otInstance * aInstance, bool aEnabled)
This function starts Thread protocol operation.
The interface must be up when calling this function.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aEnabled TRUE if Thread is enabled, FALSE otherwise.
Return values
OT_ERROR_NONE Successfully started Thread protocol operation.
OT_ERROR_INVALID_STATE The network interface was not not up.
Referenced by NcpBase::CommandHandler_RESET(), Instance::Finalize(), and NcpBase::HandlePropertyGet().
otThreadGetVersion()
uint16_t otThreadGetVersion (void)
This function gets the Thread protocol version.
Returns
the Thread protocol version.
Referenced by InitInstance().
otThreadIsSingleton()
bool otThreadIsSingleton (otInstance * aInstance)
This function indicates whether a node is the only router on the network.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Return values
TRUE It is the only router in the network.
FALSE It is a child or is not a single router in the network.
otThreadDiscover()
otError otThreadDiscover (otInstance * aInstance, uint32_t aScanChannels, uint16_t aPanId, bool aJoiner, bool aEnableEui64Filtering, otHandleActiveScanResult aCallback, void * aCallbackContext)
This function starts a Thread Discovery scan.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aScanChannels A bit vector indicating which channels to scan (e.g. OT_CHANNEL_11_MASK).
[in] aPanId The PAN ID filter (set to Broadcast PAN to disable filter).
[in] aJoiner Value of the Joiner Flag in the Discovery Request TLV.
[in] aEnableEui64Filtering TRUE to filter responses on EUI-64, FALSE otherwise.
[in] aCallback A pointer to a function called on receiving an MLE Discovery Response or scan completes.
[in] aCallbackContext A pointer to application-specific context.
Return values
OT_ERROR_NONE Accepted the Thread Discovery request.
OT_ERROR_BUSY Already performing an Thread Discovery.
Referenced by NcpBase::HandlePropertySet().
otThreadIsDiscoverInProgress()
bool otThreadIsDiscoverInProgress (otInstance * aInstance)
This function determines if an MLE Thread Discovery is currently in progress.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Referenced by NcpBase::HandlePropertyGet().
otThreadGetChildTimeout()
uint32_t otThreadGetChildTimeout (otInstance * aInstance)
Get the Thread Child Timeout used when operating in the Child role.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
The Thread Child Timeout value in seconds.
See also
otThreadSetChildTimeout
otThreadSetChildTimeout()
void otThreadSetChildTimeout (otInstance * aInstance, uint32_t aTimeout)
Set the Thread Child Timeout used when operating in the Child role.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aTimeout The timeout value in seconds.
See also
otThreadGetChildTimeout
otThreadGetExtendedPanId()
const otExtendedPanId* otThreadGetExtendedPanId (otInstance * aInstance)
Get the IEEE 802.15.4 Extended PAN ID.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
A pointer to the IEEE 802.15.4 Extended PAN ID.
See also
otThreadSetExtendedPanId
Referenced by Dataset::ProcessPskc().
otThreadSetExtendedPanId()
otError otThreadSetExtendedPanId (otInstance * aInstance, const otExtendedPanId * aExtendedPanId)
Set the IEEE 802.15.4 Extended PAN ID.
This function can only be called while Thread protocols are disabled. A successful call to this function invalidates the Active and Pending Operational Datasets in non-volatile memory.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aExtendedPanId A pointer to the IEEE 802.15.4 Extended PAN ID.
Return values
OT_ERROR_NONE Successfully set the Extended PAN ID.
OT_ERROR_INVALID_STATE Thread protocols are enabled.
See also
otThreadGetExtendedPanId
otThreadGetLeaderRloc()
otError otThreadGetLeaderRloc (otInstance * aInstance, otIp6Address * aLeaderRloc)
This function returns a pointer to the Leader's RLOC.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[out] aLeaderRloc A pointer to the Leader's RLOC.
Return values
OT_ERROR_NONE The Leader's RLOC was successfully written to aLeaderRloc.
OT_ERROR_INVALID_ARGS aLeaderRloc was NULL.
OT_ERROR_DETACHED Not currently attached to a Thread Partition.
otThreadGetLinkMode()
otLinkModeConfig otThreadGetLinkMode (otInstance * aInstance)
Get the MLE Link Mode configuration.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
The MLE Link Mode configuration.
See also
otThreadSetLinkMode
otThreadSetLinkMode()
otError otThreadSetLinkMode (otInstance * aInstance, otLinkModeConfig aConfig)
Set the MLE Link Mode configuration.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aConfig A pointer to the Link Mode configuration.
Return values
OT_ERROR_NONE Successfully set the MLE Link Mode configuration.
See also
otThreadGetLinkMode
otThreadGetMasterKey()
const otMasterKey* otThreadGetMasterKey (otInstance * aInstance)
Get the thrMasterKey.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
A pointer to a buffer containing the thrMasterKey.
See also
otThreadSetMasterKey
otThreadSetMasterKey()
otError otThreadSetMasterKey (otInstance * aInstance, const otMasterKey * aKey)
Set the thrMasterKey.
This function succeeds only when Thread protocols are disabled. A successful call to this function invalidates the Active and Pending Operational Datasets in non-volatile memory.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aKey A pointer to a buffer containing the thrMasterKey.
Return values
OT_ERROR_NONE Successfully set the thrMasterKey.
OT_ERROR_INVALID_ARGS If aKeyLength is larger than 16.
OT_ERROR_INVALID_STATE Thread protocols are enabled.
See also
otThreadGetMasterKey
otThreadGetRloc()
const otIp6Address* otThreadGetRloc (otInstance * aInstance)
This function returns a pointer to the Thread Routing Locator (RLOC) address.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
A pointer to the Thread Routing Locator (RLOC) address.
otThreadGetMeshLocalEid()
const otIp6Address* otThreadGetMeshLocalEid (otInstance * aInstance)
This function returns a pointer to the Mesh Local EID address.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
A pointer to the Mesh Local EID address.
otThreadGetMeshLocalPrefix()
const otMeshLocalPrefix* otThreadGetMeshLocalPrefix (otInstance * aInstance)
This function returns a pointer to the Mesh Local Prefix.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
A pointer to the Mesh Local Prefix.
otThreadSetMeshLocalPrefix()
otError otThreadSetMeshLocalPrefix (otInstance * aInstance, const otMeshLocalPrefix * aMeshLocalPrefix)
This function sets the Mesh Local Prefix.
This function succeeds only when Thread protocols are disabled. A successful call to this function invalidates the Active and Pending Operational Datasets in non-volatile memory.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aMeshLocalPrefix A pointer to the Mesh Local Prefix.
Return values
OT_ERROR_NONE Successfully set the Mesh Local Prefix.
OT_ERROR_INVALID_STATE Thread protocols are enabled.
otThreadGetLinkLocalIp6Address()
const otIp6Address* otThreadGetLinkLocalIp6Address (otInstance * aInstance)
This function returns the Thread link-local IPv6 address.
The Thread link local address is derived using IEEE802.15.4 Extended Address as Interface Identifier.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
A pointer to Thread link-local IPv6 address.
otThreadGetNetworkName()
const char* otThreadGetNetworkName (otInstance * aInstance)
Get the Thread Network Name.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
A pointer to the Thread Network Name.
See also
otThreadSetNetworkName
Referenced by Dataset::ProcessPskc().
otThreadSetNetworkName()
otError otThreadSetNetworkName (otInstance * aInstance, const char * aNetworkName)
Set the Thread Network Name.
This function succeeds only when Thread protocols are disabled. A successful call to this function invalidates the Active and Pending Operational Datasets in non-volatile memory.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aNetworkName A pointer to the Thread Network Name.
Return values
OT_ERROR_NONE Successfully set the Thread Network Name.
OT_ERROR_INVALID_STATE Thread protocols are enabled.
See also
otThreadGetNetworkName
otThreadGetDomainName()
const char* otThreadGetDomainName (otInstance * aInstance)
Get the Thread Domain Name.
This function is only availble since Thread 1.2.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
A pointer to the Thread Domain Name.
See also
otThreadSetDomainName
otThreadSetDomainName()
otError otThreadSetDomainName (otInstance * aInstance, const char * aDomainName)
Set the Thread Domain Name.
This function is only availble since Thread 1.2. This function succeeds only when Thread protocols are disabled.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aDomainName A pointer to the Thread Domain Name.
Return values
OT_ERROR_NONE Successfully set the Thread Domain Name.
OT_ERROR_INVALID_STATE Thread protocols are enabled.
See also
otThreadGetDomainName
otThreadGetKeySequenceCounter()
uint32_t otThreadGetKeySequenceCounter (otInstance * aInstance)
Get the thrKeySequenceCounter.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
The thrKeySequenceCounter value.
See also
otThreadSetKeySequenceCounter
otThreadSetKeySequenceCounter()
void otThreadSetKeySequenceCounter (otInstance * aInstance, uint32_t aKeySequenceCounter)
Set the thrKeySequenceCounter.
Note
This API is reserved for testing and demo purposes only. Changing settings with this API will render a production application non-compliant with the Thread Specification.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aKeySequenceCounter The thrKeySequenceCounter value.
See also
otThreadGetKeySequenceCounter
otThreadGetKeySwitchGuardTime()
uint32_t otThreadGetKeySwitchGuardTime (otInstance * aInstance)
Get the thrKeySwitchGuardTime
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
The thrKeySwitchGuardTime value (in hours).
See also
otThreadSetKeySwitchGuardTime
otThreadSetKeySwitchGuardTime()
void otThreadSetKeySwitchGuardTime (otInstance * aInstance, uint32_t aKeySwitchGuardTime)
Set the thrKeySwitchGuardTime
Note
This API is reserved for testing and demo purposes only. Changing settings with this API will render a production application non-compliant with the Thread Specification.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aKeySwitchGuardTime The thrKeySwitchGuardTime value (in hours).
See also
otThreadGetKeySwitchGuardTime
otThreadBecomeDetached()
otError otThreadBecomeDetached (otInstance * aInstance)
Detach from the Thread network.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Return values
OT_ERROR_NONE Successfully detached from the Thread network.
OT_ERROR_INVALID_STATE Thread is disabled.
otThreadBecomeChild()
otError otThreadBecomeChild (otInstance * aInstance)
Attempt to reattach as a child.
Note
This API is reserved for testing and demo purposes only. Changing settings with this API will render a production application non-compliant with the Thread Specification.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Return values
OT_ERROR_NONE Successfully begin attempt to become a child.
OT_ERROR_INVALID_STATE Thread is disabled.
otThreadGetNextNeighborInfo()
otError otThreadGetNextNeighborInfo (otInstance * aInstance, otNeighborInfoIterator * aIterator, otNeighborInfo * aInfo)
This function gets the next neighbor information. It is used to go through the entries of the neighbor table.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in,out] aIterator A pointer to the iterator context. To get the first neighbor entry it should be set to OT_NEIGHBOR_INFO_ITERATOR_INIT.
[out] aInfo A pointer to the neighbor information.
Return values
OT_ERROR_NONE Successfully found the next neighbor entry in table.
OT_ERROR_NOT_FOUND No subsequent neighbor entry exists in the table.
OT_ERROR_INVALID_ARGS aIterator or aInfo was NULL.
otThreadGetDeviceRole()
otDeviceRole otThreadGetDeviceRole (otInstance * aInstance)
Get the device role.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Return values
OT_DEVICE_ROLE_DISABLED The Thread stack is disabled.
OT_DEVICE_ROLE_DETACHED The device is not currently participating in a Thread network/partition.
OT_DEVICE_ROLE_CHILD The device is currently operating as a Thread Child.
OT_DEVICE_ROLE_ROUTER The device is currently operating as a Thread Router.
OT_DEVICE_ROLE_LEADER The device is currently operating as a Thread Leader.
Referenced by NcpBase::HandlePropertyGet().
otThreadGetLeaderData()
otError otThreadGetLeaderData (otInstance * aInstance, otLeaderData * aLeaderData)
This function get the Thread Leader Data.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[out] aLeaderData A pointer to where the leader data is placed.
Return values
OT_ERROR_NONE Successfully retrieved the leader data.
OT_ERROR_DETACHED Not currently attached.
otThreadGetLeaderRouterId()
uint8_t otThreadGetLeaderRouterId (otInstance * aInstance)
Get the Leader's Router ID.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
The Leader's Router ID.
otThreadGetLeaderWeight()
uint8_t otThreadGetLeaderWeight (otInstance * aInstance)
Get the Leader's Weight.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
The Leader's Weight.
otThreadGetPartitionId()
uint32_t otThreadGetPartitionId (otInstance * aInstance)
Get the Partition ID.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
The Partition ID.
otThreadGetRloc16()
uint16_t otThreadGetRloc16 (otInstance * aInstance)
Get the RLOC16.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
The RLOC16.
otThreadGetParentInfo()
otError otThreadGetParentInfo (otInstance * aInstance, otRouterInfo * aParentInfo)
The function retrieves diagnostic information for a Thread Router as parent.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[out] aParentInfo A pointer to where the parent router information is placed.
otThreadGetParentAverageRssi()
otError otThreadGetParentAverageRssi (otInstance * aInstance, int8_t * aParentRssi)
The function retrieves the average RSSI for the Thread Parent.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[out] aParentRssi A pointer to where the parent RSSI should be placed.
otThreadGetParentLastRssi()
otError otThreadGetParentLastRssi (otInstance * aInstance, int8_t * aLastRssi)
The function retrieves the RSSI of the last packet from the Thread Parent.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[out] aLastRssi A pointer to where the last RSSI should be placed.
Return values
OT_ERROR_NONE Successfully retrieved the RSSI data.
OT_ERROR_FAILED Unable to get RSSI data.
OT_ERROR_INVALID_ARGS aLastRssi is NULL.
otThreadGetIp6Counters()
const otIpCounters* otThreadGetIp6Counters (otInstance * aInstance)
Get the IPv6 counters.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
A pointer to the IPv6 counters.
otThreadResetIp6Counters()
void otThreadResetIp6Counters (otInstance * aInstance)
Reset the IPv6 counters.
Parameters
[in] aInstance A pointer to an OpenThread instance.
otThreadGetMleCounters()
const otMleCounters* otThreadGetMleCounters (otInstance * aInstance)
Get the Thread MLE counters.
Parameters
[in] aInstance A pointer to an OpenThread instance.
Returns
A pointer to the Thread MLE counters.
otThreadResetMleCounters()
void otThreadResetMleCounters (otInstance * aInstance)
Reset the Thread MLE counters.
Parameters
[in] aInstance A pointer to an OpenThread instance.
otThreadRegisterParentResponseCallback()
void otThreadRegisterParentResponseCallback (otInstance * aInstance, otThreadParentResponseCallback aCallback, void * aContext)
This function registers a callback to receive MLE Parent Response data.
Parameters
[in] aInstance A pointer to an OpenThread instance.
[in] aCallback A pointer to a function that is called upon receiving an MLE Parent Response message.
[in] aContext A pointer to callback client-specific context.
Referenced by NcpBase::NcpBase().
Variable Documentation
OT_TOOL_PACKED_END
OT_TOOL_PACKED_BEGIN struct otPskc OT_TOOL_PACKED_END
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale