OpenThread: Core-radio
Core-radio
This module includes definitions for OpenThread radio abstraction.
Data Structures
class Radio::Callbacks
class Radio
Enumerations
enum
Functions
otError AddSrcMatchExtEntry (const Mac::ExtAddress &aExtAddress)
otError AddSrcMatchShortEntry (Mac::ShortAddress aShortAddress)
Callbacks (Instance &aInstance)
void ClearSrcMatchExtEntries (void)
otError ClearSrcMatchExtEntry (const Mac::ExtAddress &aExtAddress)
void ClearSrcMatchShortEntries (void)
otError ClearSrcMatchShortEntry (Mac::ShortAddress aShortAddress)
otError Disable (void)
otError Enable (void)
void EnableSrcMatch (bool aEnable)
otError EnergyScan (uint8_t aScanChannel, uint16_t aScanDuration)
otRadioCaps GetCaps (void)
otError GetCcaEnergyDetectThreshold (int8_t &aThreshold)
void GetIeeeEui64 (Mac::ExtAddress &aIeeeEui64)
otInstance * GetInstance (void)
uint32_t GetPreferredChannelMask (void)
bool GetPromiscuous (void)
int8_t GetReceiveSensitivity (void)
int8_t GetRssi (void)
otRadioState GetState (void)
uint32_t GetSupportedChannelMask (void)
Mac::TxFrame & GetTransmitBuffer (void)
otError GetTransmitPower (int8_t &aPower)
const char * GetVersionString (void)
void HandleEnergyScanDone (int8_t aMaxRssi)
void HandleReceiveDone (Mac::RxFrame *aFrame, otError aError)
void HandleTransmitDone (Mac::TxFrame &aFrame, Mac::RxFrame *aAckFrame, otError aError)
void HandleTransmitStarted (Mac::TxFrame &aFrame)
bool IsEnabled (void)
OT_STATIC_ASSERT ((OPENTHREAD_CONFIG_RADIO_2P4GHZ_OQPSK_SUPPORT||OPENTHREAD_CONFIG_RADIO_915MHZ_OQPSK_SUPPORT), "OPENTHREAD_CONFIG_RADIO_2P4GHZ_OQPSK_SUPPORT or OPENTHREAD_CONFIG_RADIO_915MHZ_OQPSK_SUPPORT " "must be set to 1 to specify the radio mode")
Radio (Instance &aInstance)
otError Receive (uint8_t aChannel)
otError SetCcaEnergyDetectThreshold (int8_t aThreshold)
void SetExtendedAddress (const Mac::ExtAddress &aExtAddress)
void SetPanId (Mac::PanId aPanId)
void SetPromiscuous (bool aEnable)
void SetShortAddress (Mac::ShortAddress aShortAddress)
otError SetTransmitPower (int8_t aPower)
otError Sleep (void)
otError Transmit (Mac::TxFrame &aFrame)
Variables
Callbacks mCallbacks
Friends
class Instance
class Radio
Detailed Description
This module includes definitions for OpenThread radio abstraction.
Enumeration Type Documentation
anonymous enum
anonymous enum
This enumeration defines the IEEE 802.15.4 channel related parameters.
Function Documentation
OT_STATIC_ASSERT()
OT_STATIC_ASSERT ((OPENTHREAD_CONFIG_RADIO_2P4GHZ_OQPSK_SUPPORT||OPENTHREAD_CONFIG_RADIO_915MHZ_OQPSK_SUPPORT) , "OPENTHREAD_CONFIG_RADIO_2P4GHZ_OQPSK_SUPPORT or OPENTHREAD_CONFIG_RADIO_915MHZ_OQPSK_SUPPORT " "must be set to 1 to specify the radio mode")
HandleReceiveDone()
void HandleReceiveDone (Mac::RxFrame * aFrame, otError aError)
This callback method handles a "Receive Done" event from radio platform.
Parameters
[in] aFrame A pointer to the received frame or NULL if the receive operation failed.
[in] aError OT_ERROR_NONE when successfully received a frame, OT_ERROR_ABORT when reception was aborted and a frame was not received, OT_ERROR_NO_BUFS when a frame could not be received due to lack of rx buffer space.
Referenced by Radio::Callbacks::HandleEnergyScanDone().
HandleTransmitStarted()
void HandleTransmitStarted (Mac::TxFrame & aFrame)
This callback method handles a "Transmit Started" event from radio platform.
Parameters
[in] aFrame The frame that is being transmitted.
HandleTransmitDone()
void HandleTransmitDone (Mac::TxFrame & aFrame, Mac::RxFrame * aAckFrame, otError aError)
This callback method handles a "Transmit Done" event from radio platform.
Parameters
[in] aFrame The frame that was transmitted.
[in] aAckFrame A pointer to the ACK frame, NULL if no ACK was received.
[in] aError OT_ERROR_NONE when the frame was transmitted, OT_ERROR_NO_ACK when the frame was transmitted but no ACK was received, OT_ERROR_CHANNEL_ACCESS_FAILURE tx could not take place due to activity on the channel, OT_ERROR_ABORT when transmission was aborted for other reasons.
Referenced by Radio::Callbacks::HandleEnergyScanDone().
HandleEnergyScanDone()
void HandleEnergyScanDone (int8_t aMaxRssi)
This callback method handles "Energy Scan Done" event from radio platform.
This method is used when radio provides OT_RADIO_CAPS_ENERGY_SCAN capability. It is called from otPlatRadioEnergyScanDone().
Parameters
[in] aInstance The OpenThread instance structure.
[in] aEnergyScanMaxRssi The maximum RSSI encountered on the scanned channel.
References Radio::Callbacks::HandleReceiveDone(), Radio::Callbacks::HandleTransmitDone(), and OT_UNUSED_VARIABLE.
Callbacks()
Callbacks (Instance & aInstance) inline explicit private
Radio()
Radio (Instance & aInstance) inline
This constructor initializes the Radio object.
Parameters
[in] aInstance A reference to the OpenThread instance.
GetCaps()
otRadioCaps GetCaps (void) inline
This method gets the radio capabilities.
Returns
The radio capability bit vector (see OT_RADIO_CAP_* definitions).
References InstanceLocator::GetInstance(), and otPlatRadioGetCaps().
GetVersionString()
const char* GetVersionString (void) inline
This method gets the radio version string.
Returns
A pointer to the OpenThread radio version.
References InstanceLocator::GetInstance(), and otPlatRadioGetVersionString().
GetReceiveSensitivity()
int8_t GetReceiveSensitivity (void) inline
This method gets the radio receive sensitivity value.
Returns
The radio receive sensitivity value in dBm.
References InstanceLocator::GetInstance(), and otPlatRadioGetReceiveSensitivity().
GetIeeeEui64()
void GetIeeeEui64 (Mac::ExtAddress & aIeeeEui64) inline
This method gets the factory-assigned IEEE EUI-64 for the device.
Parameters
[out] aIeeeEui64 A reference to Mac::ExtAddress to place the factory-assigned IEEE EUI-64.
References InstanceLocator::GetInstance(), otExtAddress::m8, and otPlatRadioGetIeeeEui64().
SetPanId()
void SetPanId (Mac::PanId aPanId) inline
This method sets the PAN ID for address filtering.
Parameters
[in] aPanId The IEEE 802.15.4 PAN ID.
References InstanceLocator::GetInstance(), otPlatRadioSetPanId(), Radio::SetExtendedAddress(), and Radio::SetShortAddress().
SetExtendedAddress()
void SetExtendedAddress (const Mac::ExtAddress & aExtAddress)
This method sets the Extended Address for address filtering.
Parameters
[in] aExtAddress The IEEE 802.15.4 Extended Address stored in little-endian byte order.
References Radio::GetInstance(), and otPlatRadioSetExtendedAddress().
Referenced by Radio::SetPanId().
SetShortAddress()
void SetShortAddress (Mac::ShortAddress aShortAddress)
This method sets the Short Address for address filtering.
Parameters
[in] aShortAddress The IEEE 802.15.4 Short Address.
References Radio::GetInstance(), and otPlatRadioSetShortAddress().
Referenced by Radio::SetPanId().
GetTransmitPower()
otError GetTransmitPower (int8_t & aPower) inline
This method gets the radio's transmit power in dBm.
Parameters
[out] aPower A reference to output the transmit power in dBm.
Return values
OT_ERROR_NONE Successfully retrieved the transmit power.
OT_ERROR_NOT_IMPLEMENTED Transmit power configuration via dBm is not implemented.
References InstanceLocator::GetInstance(), and otPlatRadioGetTransmitPower().
SetTransmitPower()
otError SetTransmitPower (int8_t aPower) inline
This method sets the radio's transmit power in dBm.
Parameters
[in] aPower The transmit power in dBm.
Return values
OT_ERROR_NONE Successfully set the transmit power.
OT_ERROR_NOT_IMPLEMENTED Transmit power configuration via dBm is not implemented.
References InstanceLocator::GetInstance(), and otPlatRadioSetTransmitPower().
GetCcaEnergyDetectThreshold()
otError GetCcaEnergyDetectThreshold (int8_t & aThreshold) inline
This method gets the radio's CCA ED threshold in dBm.
Parameters
[in] aThreshold The CCA ED threshold in dBm.
Return values
OT_ERROR_NONE A reference to output the CCA ED threshold in dBm.
OT_ERROR_NOT_IMPLEMENTED CCA ED threshold configuration via dBm is not implemented.
References InstanceLocator::GetInstance(), and otPlatRadioGetCcaEnergyDetectThreshold().
SetCcaEnergyDetectThreshold()
otError SetCcaEnergyDetectThreshold (int8_t aThreshold) inline
This method sets the radio's CCA ED threshold in dBm.
Parameters
[in] aThreshold The CCA ED threshold in dBm.
Return values
OT_ERROR_NONE Successfully set the CCA ED threshold.
OT_ERROR_NOT_IMPLEMENTED CCA ED threshold configuration via dBm is not implemented.
References InstanceLocator::GetInstance(), and otPlatRadioSetCcaEnergyDetectThreshold().
GetPromiscuous()
bool GetPromiscuous (void) inline
This method gets the status of promiscuous mode.
Return values
TRUE Promiscuous mode is enabled.
FALSE Promiscuous mode is disabled.
References InstanceLocator::GetInstance(), and otPlatRadioGetPromiscuous().
SetPromiscuous()
void SetPromiscuous (bool aEnable) inline
This method enables or disables promiscuous mode.
Parameters
[in] aEnable TRUE to enable or FALSE to disable promiscuous mode.
References InstanceLocator::GetInstance(), and otPlatRadioSetPromiscuous().
GetState()
otRadioState GetState (void) inline
This method returns the current state of the radio.
This function is not required by OpenThread. It may be used for debugging and/or application-specific purposes.
Note
This function may be not implemented. In this case it always returns OT_RADIO_STATE_INVALID state.
Returns
Current state of the radio.
References InstanceLocator::GetInstance(), and otPlatRadioGetState().
Enable()
otError Enable (void) inline
This method enables the radio.
Return values
OT_ERROR_NONE Successfully enabled.
OT_ERROR_FAILED The radio could not be enabled.
References InstanceLocator::GetInstance(), and otPlatRadioEnable().
Disable()
otError Disable (void) inline
This method disables the radio.
Return values
OT_ERROR_NONE Successfully transitioned to Disabled.
OT_ERROR_INVALID_STATE The radio was not in sleep state.
References InstanceLocator::GetInstance(), and otPlatRadioDisable().
IsEnabled()
bool IsEnabled (void) inline
This method indicates whether radio is enabled or not.
Returns
TRUE if the radio is enabled, FALSE otherwise.
References InstanceLocator::GetInstance(), and otPlatRadioIsEnabled().
Sleep()
otError Sleep (void) inline
This method transitions the radio from Receive to Sleep (turn off the radio).
Return values
OT_ERROR_NONE Successfully transitioned to Sleep.
OT_ERROR_BUSY The radio was transmitting.
OT_ERROR_INVALID_STATE The radio was disabled.
References InstanceLocator::GetInstance(), and otPlatRadioSleep().
Receive()
otError Receive (uint8_t aChannel) inline
This method transitions the radio from Sleep to Receive (turn on the radio).
Parameters
[in] aChannel The channel to use for receiving.
Return values
OT_ERROR_NONE Successfully transitioned to Receive.
OT_ERROR_INVALID_STATE The radio was disabled or transmitting.
References InstanceLocator::GetInstance(), and otPlatRadioReceive().
GetTransmitBuffer()
Mac::TxFrame& GetTransmitBuffer (void) inline
This method gets the radio transmit frame buffer.
OpenThread forms the IEEE 802.15.4 frame in this buffer then calls Transmit() to request transmission.
Returns
A reference to the transmit frame buffer.
References InstanceLocator::GetInstance(), and otPlatRadioGetTransmitBuffer().
Transmit()
otError Transmit (Mac::TxFrame & aFrame) inline
This method starts the transmit sequence on the radio.
The caller must form the IEEE 802.15.4 frame in the buffer provided by GetTransmitBuffer() before requesting transmission. The channel and transmit power are also included in the frame.
Parameters
[in] aFrame A reference to the frame to be transmitted.
Return values
OT_ERROR_NONE Successfully transitioned to Transmit.
OT_ERROR_INVALID_STATE The radio was not in the Receive state.
References InstanceLocator::GetInstance(), and otPlatRadioTransmit().
GetRssi()
int8_t GetRssi (void) inline
This method gets the most recent RSSI measurement.
Returns
The RSSI in dBm when it is valid. 127 when RSSI is invalid.
References InstanceLocator::GetInstance(), and otPlatRadioGetRssi().
EnergyScan()
otError EnergyScan (uint8_t aScanChannel, uint16_t aScanDuration) inline
This method begins the energy scan sequence on the radio.
This function is used when radio provides OT_RADIO_CAPS_ENERGY_SCAN capability.
Parameters
[in] aScanChannel The channel to perform the energy scan on.
[in] aScanDuration The duration, in milliseconds, for the channel to be scanned.
Return values
OT_ERROR_NONE Successfully started scanning the channel.
OT_ERROR_NOT_IMPLEMENTED The radio doesn't support energy scanning.
References InstanceLocator::GetInstance(), and otPlatRadioEnergyScan().
EnableSrcMatch()
void EnableSrcMatch (bool aEnable) inline
This method enables/disables source address match feature.
The source address match feature controls how the radio layer decides the "frame pending" bit for acks sent in response to data request commands from children.
If disabled, the radio layer must set the "frame pending" on all acks to data request commands.
If enabled, the radio layer uses the source address match table to determine whether to set or clear the "frame pending" bit in an ack to a data request command.
The source address match table provides the list of children for which there is a pending frame. Either a short address or an extended/long address can be added to the source address match table.
Parameters
[in] aEnable Enable/disable source address match feature.
References InstanceLocator::GetInstance(), and otPlatRadioEnableSrcMatch().
AddSrcMatchShortEntry()
otError AddSrcMatchShortEntry (Mac::ShortAddress aShortAddress) inline
This method adds a short address to the source address match table.
Parameters
[in] aShortAddress The short address to be added.
Return values
OT_ERROR_NONE Successfully added short address to the source match table.
OT_ERROR_NO_BUFS No available entry in the source match table.
References InstanceLocator::GetInstance(), and otPlatRadioAddSrcMatchShortEntry().
AddSrcMatchExtEntry()
otError AddSrcMatchExtEntry (const Mac::ExtAddress & aExtAddress) inline
This method adds an extended address to the source address match table.
Parameters
[in] aExtAddress The extended address to be added stored in little-endian byte order.
Return values
OT_ERROR_NONE Successfully added extended address to the source match table.
OT_ERROR_NO_BUFS No available entry in the source match table.
References InstanceLocator::GetInstance(), and otPlatRadioAddSrcMatchExtEntry().
ClearSrcMatchShortEntry()
otError ClearSrcMatchShortEntry (Mac::ShortAddress aShortAddress) inline
This method removes a short address from the source address match table.
Parameters
[in] aShortAddress The short address to be removed.
Return values
OT_ERROR_NONE Successfully removed short address from the source match table.
OT_ERROR_NO_ADDRESS The short address is not in source address match table.
References InstanceLocator::GetInstance(), and otPlatRadioClearSrcMatchShortEntry().
ClearSrcMatchExtEntry()
otError ClearSrcMatchExtEntry (const Mac::ExtAddress & aExtAddress) inline
This method removes an extended address from the source address match table.
Parameters
[in] aExtAddress The extended address to be removed stored in little-endian byte order.
Return values
OT_ERROR_NONE Successfully removed the extended address from the source match table.
OT_ERROR_NO_ADDRESS The extended address is not in source address match table.
References InstanceLocator::GetInstance(), and otPlatRadioClearSrcMatchExtEntry().
ClearSrcMatchShortEntries()
void ClearSrcMatchShortEntries (void) inline
This method clears all short addresses from the source address match table.
References InstanceLocator::GetInstance(), and otPlatRadioClearSrcMatchShortEntries().
ClearSrcMatchExtEntries()
void ClearSrcMatchExtEntries (void) inline
This method clears all the extended/long addresses from source address match table.
References InstanceLocator::GetInstance(), and otPlatRadioClearSrcMatchExtEntries().
GetSupportedChannelMask()
uint32_t GetSupportedChannelMask (void) inline
This method gets the radio supported channel mask that the device is allowed to be on.
Returns
The radio supported channel mask.
References InstanceLocator::GetInstance(), and otPlatRadioGetSupportedChannelMask().
GetPreferredChannelMask()
uint32_t GetPreferredChannelMask (void) inline
This method gets the radio preferred channel mask that the device prefers to form on.
Returns
The radio preferred channel mask.
References InstanceLocator::GetInstance(), and otPlatRadioGetPreferredChannelMask().
GetInstance()
otInstance* GetInstance (void) inline private
References InstanceLocator::GetInstance().
Referenced by Radio::SetExtendedAddress(), and Radio::SetShortAddress().
Variable Documentation
mCallbacks
Callbacks mCallbacks private
Friends
Instance
friend class Instance friend
Radio
friend class Radio friend
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale