OpenThread: Error
Error
API
This module includes error definitions used in OpenThread.
Typedefs
typedef enum otError otError
Enumerations
enum otError {
OT_ERROR_NONE = 0, OT_ERROR_FAILED = 1, OT_ERROR_DROP = 2, OT_ERROR_NO_BUFS = 3,
OT_ERROR_NO_ROUTE = 4, OT_ERROR_BUSY = 5, OT_ERROR_PARSE = 6, OT_ERROR_INVALID_ARGS = 7,
OT_ERROR_SECURITY = 8, OT_ERROR_ADDRESS_QUERY = 9, OT_ERROR_NO_ADDRESS = 10, OT_ERROR_ABORT = 11,
OT_ERROR_NOT_IMPLEMENTED = 12, OT_ERROR_INVALID_STATE = 13, OT_ERROR_NO_ACK = 14, OT_ERROR_CHANNEL_ACCESS_FAILURE = 15,
OT_ERROR_DETACHED = 16, OT_ERROR_FCS = 17, OT_ERROR_NO_FRAME_RECEIVED = 18, OT_ERROR_UNKNOWN_NEIGHBOR = 19,
OT_ERROR_INVALID_SOURCE_ADDRESS = 20, OT_ERROR_ADDRESS_FILTERED = 21, OT_ERROR_DESTINATION_ADDRESS_FILTERED = 22, OT_ERROR_NOT_FOUND = 23,
OT_ERROR_ALREADY = 24, OT_ERROR_IP6_ADDRESS_CREATION_FAILURE = 26, OT_ERROR_NOT_CAPABLE = 27, OT_ERROR_RESPONSE_TIMEOUT = 28,
OT_ERROR_DUPLICATED = 29, OT_ERROR_REASSEMBLY_TIMEOUT = 30, OT_ERROR_NOT_TMF = 31, OT_ERROR_NOT_LOWPAN_DATA_FRAME = 32,
OT_ERROR_LINK_MARGIN_LOW = 34, OT_ERROR_INVALID_COMMAND = 35, OT_NUM_ERRORS, OT_ERROR_GENERIC = 255
}
Functions
const char * otThreadErrorToString (otError aError)
Detailed Description
This module includes error definitions used in OpenThread.
Typedef Documentation
otError
typedef enum otError otError
This enumeration represents error codes used throughout OpenThread.
Enumeration Type Documentation
otError
enum otError
This enumeration represents error codes used throughout OpenThread.
Enumerator
OT_ERROR_NONE
No error.
OT_ERROR_FAILED
Operational failed.
OT_ERROR_DROP
Message was dropped.
OT_ERROR_NO_BUFS
Insufficient buffers.
OT_ERROR_NO_ROUTE
No route available.
OT_ERROR_BUSY
Service is busy and could not service the operation.
OT_ERROR_PARSE
Failed to parse message.
OT_ERROR_INVALID_ARGS
Input arguments are invalid.
OT_ERROR_SECURITY
Security checks failed.
OT_ERROR_ADDRESS_QUERY
Address resolution requires an address query operation.
OT_ERROR_NO_ADDRESS
Address is not in the source match table.
OT_ERROR_ABORT
Operation was aborted.
OT_ERROR_NOT_IMPLEMENTED
Function or method is not implemented.
OT_ERROR_INVALID_STATE
Cannot complete due to invalid state.
OT_ERROR_NO_ACK
No acknowledgment was received after macMaxFrameRetries (IEEE 802.15.4-2006).
OT_ERROR_CHANNEL_ACCESS_FAILURE
A transmission could not take place due to activity on the channel, i.e., the CSMA-CA mechanism has failed (IEEE 802.15.4-2006).
OT_ERROR_DETACHED
Not currently attached to a Thread Partition.
OT_ERROR_FCS
FCS check failure while receiving.
OT_ERROR_NO_FRAME_RECEIVED
No frame received.
OT_ERROR_UNKNOWN_NEIGHBOR
Received a frame from an unknown neighbor.
OT_ERROR_INVALID_SOURCE_ADDRESS
Received a frame from an invalid source address.
OT_ERROR_ADDRESS_FILTERED
Received a frame filtered by the address filter (whitelisted or blacklisted).
OT_ERROR_DESTINATION_ADDRESS_FILTERED
Received a frame filtered by the destination address check.
OT_ERROR_NOT_FOUND
The requested item could not be found.
OT_ERROR_ALREADY
The operation is already in progress.
OT_ERROR_IP6_ADDRESS_CREATION_FAILURE
The creation of IPv6 address failed.
OT_ERROR_NOT_CAPABLE
Operation prevented by mode flags
OT_ERROR_RESPONSE_TIMEOUT
Coap response or acknowledgment or DNS, SNTP response not received.
OT_ERROR_DUPLICATED
Received a duplicated frame.
OT_ERROR_REASSEMBLY_TIMEOUT
Message is being dropped from reassembly list due to timeout.
OT_ERROR_NOT_TMF
Message is not a TMF Message.
OT_ERROR_NOT_LOWPAN_DATA_FRAME
Received a non-lowpan data frame.
OT_ERROR_LINK_MARGIN_LOW
The link margin was too low.
OT_ERROR_INVALID_COMMAND
Input (CLI) command is invalid.
OT_NUM_ERRORS
The number of defined errors.
OT_ERROR_GENERIC
Generic error (should not use).
Function Documentation
otThreadErrorToString()
const char* otThreadErrorToString (otError aError)
This function converts an otError enum into a string.
Parameters
[in] aError An otError enum.
Returns
A string representation of an otError.
References OT_ARRAY_LENGTH.
Referenced by Dataset::ApplyConfiguration(), Mle::CheckReachability(), RadioSpinel< InterfaceType, ProcessContextType >::Enable(), MeshForwarder::GetFramePriority(), Mle::HandleAdvertisement(), Mle::HandleAnnounce(), Mle::HandleChildIdResponse(), Mle::HandleChildUpdateRequest(), Mle::HandleChildUpdateResponse(), Mle::HandleDataResponse(), Mle::HandleDiscoveryResponse(), HdlcInterface::HandleHdlcFrame(), Ip6::HandleOptions(), Mle::HandleParentResponse(), DataPollSender::HandlePollSent(), RadioSpinel< InterfaceType, ProcessContextType >::HandleReceivedFrame(), Mle::HandleUdpReceive(), ot::Spinel::LogIfFail(), CoapBase::ProcessReceivedRequest(), SubMac::Receive(), DataPollSender::SendDataPoll(), Mac::SetPromiscuous(), and SubMac::Sleep().
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale