OpenThread: ot::Random::Crypto Namespace Reference
ot::Random::Crypto Namespace Reference
Functions
otError FillBuffer (uint8_t *aBuffer, uint16_t aSize)
mbedtls_ctr_drbg_context * MbedTlsContextGet (void)
Function Documentation
FillBuffer()
otError ot::Random::Crypto::FillBuffer (uint8_t * aBuffer, uint16_t aSize) inline
This function fills a given buffer with cryptographically secure random bytes.
Parameters
[out] aBuffer A pointer to a buffer to fill with the random bytes.
[in] aSize Size of buffer (number of bytes to fill).
Return values
OT_ERROR_NONE Successfully filled buffer with random values.
References RandomManager::CryptoFillBuffer().
Referenced by Neighbor::GenerateChallenge(), Child::GenerateChallenge(), ExtAddress::GenerateRandom(), Pskc::GenerateRandom(), Mle::Challenge::GenerateRandom(), Mle::HandleStateChanged(), Mle::Mle(), otRandomCryptoFillBuffer(), RandomManager::RandomManager(), and Message::SetToken().
MbedTlsContextGet()
mbedtls_ctr_drbg_context* ot::Random::Crypto::MbedTlsContextGet (void) inline
This function returns initialized mbedtls_ctr_drbg_context.
Returns
A pointer to initialized mbedtls_ctr_drbg_context.
References RandomManager::GetMbedTlsCtrDrbgContext().
Referenced by otRandomCryptoMbedTlsContextGet().
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale