OpenThread: ot::Utils Namespace Reference
ot::Utils Namespace Reference
Data Structures
class Block
class ChildSupervisor
class CmdLineParser
class Heap
class JamDetector
class Slaac
class SupervisionListener
Functions
static bool IsEscapable (char aChar)
static bool IsSeparator (char aChar)
Function Documentation
IsSeparator()
static bool ot::Utils::IsSeparator (char aChar) static
Referenced by IsEscapable(), and CmdLineParser::ParseCmd().
IsEscapable()
static bool ot::Utils::IsEscapable (char aChar) static
References IsSeparator().
Referenced by CmdLineParser::ParseCmd().
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale