OpenThread: ot::Encoding::LittleEndian Namespace Reference
ot::Encoding::LittleEndian Namespace Reference
Functions
uint16_t HostSwap16 (uint16_t v)
uint32_t HostSwap32 (uint32_t v)
uint64_t HostSwap64 (uint64_t v)
uint16_t ReadUint16 (const uint8_t *aBuffer)
uint32_t ReadUint32 (const uint8_t *aBuffer)
void WriteUint16 (uint16_t aValue, uint8_t *aBuffer)
void WriteUint32 (uint32_t aValue, uint8_t *aBuffer)
Function Documentation
HostSwap16()
uint16_t ot::Encoding::LittleEndian::HostSwap16 (uint16_t v) inline
Referenced by HeaderIe::GetId(), HeaderIe::GetLength(), SettingsBase::NetworkInfo::GetRloc16(), SettingsBase::ChildInfo::GetRloc16(), SettingsBase::NetworkInfo::GetVersion(), SettingsBase::ParentInfo::GetVersion(), SettingsBase::ChildInfo::GetVersion(), Beacon::Init(), Beacon::IsValid(), HeaderIe::SetId(), HeaderIe::SetLength(), SettingsBase::NetworkInfo::SetRloc16(), SettingsBase::ChildInfo::SetRloc16(), SettingsBase::NetworkInfo::SetVersion(), SettingsBase::ParentInfo::SetVersion(), and SettingsBase::ChildInfo::SetVersion().
HostSwap32()
uint32_t ot::Encoding::LittleEndian::HostSwap32 (uint32_t v) inline
Referenced by Header::GetFrameCounter(), SettingsBase::NetworkInfo::GetKeySequence(), SettingsBase::NetworkInfo::GetMacFrameCounter(), SettingsBase::NetworkInfo::GetMleFrameCounter(), SettingsBase::NetworkInfo::GetPreviousPartitionId(), SettingsBase::ChildInfo::GetTimeout(), Header::SetFrameCounter(), SettingsBase::NetworkInfo::SetKeySequence(), SettingsBase::NetworkInfo::SetMacFrameCounter(), SettingsBase::NetworkInfo::SetMleFrameCounter(), SettingsBase::NetworkInfo::SetPreviousPartitionId(), and SettingsBase::ChildInfo::SetTimeout().
HostSwap64()
uint64_t ot::Encoding::LittleEndian::HostSwap64 (uint64_t v) inline
ReadUint16()
uint16_t ot::Encoding::LittleEndian::ReadUint16 (const uint8_t * aBuffer) inline
This function reads a uint16_t value from a given buffer assuming little-ending encoding.
Parameters
[in] aBuffer Pointer to buffer to read from.
Returns
The uint16_t value read from buffer.
Referenced by Frame::GetDstAddr(), Frame::GetDstPanId(), Frame::GetFrameControlField(), SpiFrame::GetHeaderAcceptLen(), SpiFrame::GetHeaderDataLen(), MultiFrameBuffer< kMaxFrameSize >::GetNextSavedFrame(), MultiFrameBuffer< kMaxFrameSize >::GetSkipLength(), Frame::GetSrcAddr(), and Frame::GetSrcPanId().
ReadUint32()
uint32_t ot::Encoding::LittleEndian::ReadUint32 (const uint8_t * aBuffer) inline
This function reads a uint32_t value from a given buffer assuming little-ending encoding.
Parameters
[in] aBuffer Pointer to buffer to read from.
Returns
The uint32_t value read from buffer.
Referenced by Frame::GetFrameCounter().
WriteUint16()
void ot::Encoding::LittleEndian::WriteUint16 (uint16_t aValue, uint8_t * aBuffer) inline
This function writes a uint16_t value to a given buffer using little-ending encoding.
Parameters
[in] aValue The value to write to buffer.
[out] aBuffer Pointer to buffer where the value will be written.
Referenced by Frame::InitMacHeader(), MultiFrameBuffer< kMaxFrameSize >::SaveFrame(), Frame::SetDstAddr(), Frame::SetDstPanId(), SpiFrame::SetHeaderAcceptLen(), SpiFrame::SetHeaderDataLen(), MultiFrameBuffer< kMaxFrameSize >::SetSkipLength(), Frame::SetSrcAddr(), and Frame::SetSrcPanId().
WriteUint32()
void ot::Encoding::LittleEndian::WriteUint32 (uint32_t aValue, uint8_t * aBuffer) inline
This function writes a uint32_t value to a given buffer using little-ending encoding.
Parameters
[in] aValue The value to write to buffer.
[out] aBuffer Pointer to buffer where the value will be written.
Referenced by Frame::SetFrameCounter().
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale