OpenThread: ot::MeshCoP Namespace Reference
ot::MeshCoP Namespace Reference
Data Structures
class ActiveDataset
class ActiveTimestampTlv
class BorderAgent
class BorderAgentLocatorTlv
class ChannelMaskBaseTlv
class ChannelMaskEntry
class ChannelMaskEntryBase
class ChannelMaskTlv
class ChannelTlv
class Commissioner
class CommissionerIdTlv
class CommissionerSessionIdTlv
class CommissioningData
class Dataset
class DatasetLocal
class DatasetManager
class DelayTimerTlv
class DiscoveryRequestTlv
class DiscoveryResponseTlv
class Dtls
class EnergyListTlv
class ExtendedPanIdTlv
class ExtendedTlv
class Joiner
class JoinerRouter
class JoinerUdpPortTlv
class Leader
class MeshLocalPrefixTlv
class NetworkKeySequenceTlv
class NetworkMasterKeyTlv
class NetworkNameTlv
class PanIdTlv
class PendingDataset
class PendingTimestampTlv
class ProvisioningUrlTlv
class PskcTlv
class SecurityPolicyTlv
class StateTlv
class SteeringDataTlv
class Timestamp
class Tlv
class UdpEncapsulationTlv
class VendorDataTlv
class VendorModelTlv
class VendorNameTlv
class VendorStackVersionTlv
class VendorSwVersionTlv
Enumerations
enum { kMeshCoPMessagePriority = Message::kPriorityNet, kBorderAgentUdpPort = 49191 }
Functions
void ComputeJoinerId (const Mac::ExtAddress &aEui64, Mac::ExtAddress &aJoinerId)
otError GeneratePskc (const char *aPassPhrase, const Mac::NetworkName &aNetworkName, const Mac::ExtendedPanId &aExtPanId, Pskc &aPskc)
otError GetBorderAgentRloc (ThreadNetif &aNetif, uint16_t &aRloc)
Coap::Message * NewMeshCoPMessage (Coap::CoapBase &aCoap)
Variables
OT_TOOL_PACKED_BEGIN class ot::MeshCoP::CommissioningData OT_TOOL_PACKED_END
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
kMeshCoPMessagePriority
The priority for MeshCoP message.
kBorderAgentUdpPort
UDP port of border agent service.
Function Documentation
ComputeJoinerId()
void ComputeJoinerId (const Mac::ExtAddress & aEui64, Mac::ExtAddress & aJoinerId)
This function computes the Joiner ID from a factory-assigned IEEE EUI-64.
Parameters
[in] aEui64 The factory-assigned IEEE EUI-64.
[out] aJoinerId The Joiner ID.
References Sha256::Finish(), Sha256::kHashSize, otExtAddress::m8, ExtAddress::SetLocal(), Sha256::Start(), and Sha256::Update().
Referenced by Mle::Discover(), and NewMeshCoPMessage().
GetBorderAgentRloc()
otError GetBorderAgentRloc (ThreadNetif & aNetIf, uint16_t & aRloc)
This function gets the border agent RLOC.
Parameters
[in] aNetif A reference to the thread interface.
[out] aRloc Border agent RLOC.
Return values
OT_ERROR_NONE Successfully got the Border Agent Rloc.
OT_ERROR_NOT_FOUND Border agent is not available.
References GeneratePskc(), InstanceLocator::Get(), NetworkName::GetAsCString(), BorderAgentLocatorTlv::GetBorderAgentLocator(), Tlv::kBorderAgentLocator, otExtendedPanId::m8, otPskc::m8, OT_COMMISSIONING_PASSPHRASE_MAX_SIZE, OT_COMMISSIONING_PASSPHRASE_MIN_SIZE, OT_ERROR_INVALID_ARGS, OT_ERROR_NONE, OT_ERROR_NOT_FOUND, OT_EXT_PAN_ID_SIZE, OT_NETWORK_NAME_MAX_SIZE, OT_PBKDF2_SALT_MAX_LEN, OT_PSKC_MAX_SIZE, otPbkdf2Cmac(), ot::StringLength(), and VerifyOrExit.
Referenced by NewMeshCoPMessage().
NewMeshCoPMessage()
Coap::Message* ot::MeshCoP::NewMeshCoPMessage (Coap::CoapBase & aCoap) inline
This function create Message for MeshCoP
References ComputeJoinerId(), GeneratePskc(), GetBorderAgentRloc(), kMeshCoPMessagePriority, and CoapBase::NewMessage().
Referenced by DatasetManager::Register(), PanIdQueryServer::SendConflict(), DatasetManager::SendGetRequest(), DatasetManager::SendGetResponse(), EnergyScanServer::SendReport(), and DatasetManager::SendSetRequest().
GeneratePskc()
otError ot::MeshCoP::GeneratePskc (const char * aPassPhrase, const Mac::NetworkName & aNetworkName, const Mac::ExtendedPanId & aExtPanId, Pskc & aPskc)
This function generates PSKc.
PSKc is used to establish the Commissioner Session.
Parameters
[in] aPassPhrase The commissioning passphrase.
[in] aNetworkName The network name for PSKc computation.
[in] aExtPanId The extended PAN ID for PSKc computation.
[out] aPskc A reference to a PSKc where the generated PSKc will be placed.
Return values
OT_ERROR_NONE Successfully generate PSKc.
OT_ERROR_INVALID_ARGS If the length of passphrase is out of range.
Referenced by GetBorderAgentRloc(), NewMeshCoPMessage(), and otDatasetSendMgmtPendingSet().
Variable Documentation
OT_TOOL_PACKED_END
OT_TOOL_PACKED_BEGIN class ot::MeshCoP::Timestamp OT_TOOL_PACKED_END
Referenced by Tlv::FindTlv(), ActiveTimestampTlv::IsValid(), PendingTimestampTlv::IsValid(), ChannelMaskBaseTlv::IsValid(), EnergyListTlv::IsValid(), and ExtendedTlv::SetType().
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale