OpenThread: settings.cpp File Reference
posix/platform/settings.cpp File Reference
Detailed Description
This file implements the OpenThread platform abstraction for non-volatile storage of settings.
#include "openthread-posix-config.h"
#include "platform-posix.h"
#include <assert.h>
#include <fcntl.h>
#include <inttypes.h>
#include <stddef.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
#include <openthread/platform/misc.h>
#include <openthread/platform/radio.h>
#include <openthread/platform/settings.h>
#include "common/code_utils.hpp"
#include "common/encoding.hpp"
Macros
#define SELF_TEST 0
Functions
static void getSettingsFileName (otInstance *aInstance, char aFileName[kMaxFileNameSize], bool aSwap)
otError otPlatSettingsAdd (otInstance *aInstance, uint16_t aKey, const uint8_t *aValue, uint16_t aValueLength)
Adds a value to a setting.
void otPlatSettingsDeinit (otInstance *aInstance)
otError otPlatSettingsDelete (otInstance *aInstance, uint16_t aKey, int aIndex)
Removes a setting from the setting store.
otError otPlatSettingsGet (otInstance *aInstance, uint16_t aKey, int aIndex, uint8_t *aValue, uint16_t *aValueLength)
Fetches the value of a setting.
void otPlatSettingsInit (otInstance *aInstance)
otError otPlatSettingsSet (otInstance *aInstance, uint16_t aKey, const uint8_t *aValue, uint16_t aValueLength)
Sets or replaces the value of a setting.
void otPlatSettingsWipe (otInstance *aInstance)
Removes all settings from the setting store.
static otError platformSettingsDelete (otInstance *aInstance, uint16_t aKey, int aIndex, int *aSwapFd)
static void swapDiscard (otInstance *aInstance, int aFd)
static int swapOpen (otInstance *aInstance)
static void swapPersist (otInstance *aInstance, int aFd)
static void swapWrite (otInstance *aInstance, int aFd, uint16_t aLength)
Variables
static const size_t kMaxFileNameSize = sizeof(OPENTHREAD_CONFIG_POSIX_SETTINGS_PATH) + 32
static int sSettingsFd = -1
Macro Definition Documentation
SELF_TEST
#define SELF_TEST 0
Function Documentation
platformSettingsDelete()
static otError platformSettingsDelete (otInstance * aInstance, uint16_t aKey, int aIndex, int * aSwapFd) static
This function removes a setting either from swap file or persisted file.
Parameters
[in] aInstance The OpenThread instance structure.
[in] aKey The key associated with the requested setting.
[in] aIndex The index of the value to be removed. If set to -1, all values for this aKey will be removed.
[out] aSwapFd A optional pointer to receive file descriptor of the generated swap file descriptor.
Note
If aSwapFd is null, operate deleting on the setting file. If aSwapFd is not null, operate on the swap file, and aSwapFd will point to the swap file descriptor.
Return values
OT_ERROR_NONE The given key and index was found and removed successfully.
OT_ERROR_NOT_FOUND The given key or index was not found in the setting store.
References OT_ERROR_NONE, OT_ERROR_NOT_FOUND, OT_ERROR_PARSE, OT_EXIT_FAILURE, OT_UNUSED_VARIABLE, sSettingsFd, swapDiscard(), swapOpen(), swapPersist(), swapWrite(), VerifyOrDie, and VerifyOrExit.
Referenced by otPlatSettingsDelete(), and otPlatSettingsSet().
getSettingsFileName()
static void getSettingsFileName (otInstance * aInstance, char aFileName[kMaxFileNameSize], bool aSwap) static
References ot::Encoding::BigEndian::HostSwap64(), OPENTHREAD_CONFIG_POSIX_SETTINGS_PATH, and otPlatRadioGetIeeeEui64().
Referenced by otPlatSettingsInit(), swapDiscard(), swapOpen(), and swapPersist().
swapOpen()
static int swapOpen (otInstance * aInstance) static
References getSettingsFileName(), kMaxFileNameSize, OT_EXIT_ERROR_ERRNO, and VerifyOrDie.
Referenced by otPlatSettingsAdd(), and platformSettingsDelete().
swapWrite()
static void swapWrite (otInstance * aInstance, int aFd, uint16_t aLength) static
This function reads aLength bytes from the data file and appends to the swap file.
Parameters
[in] aFd The file descriptor of the current swap file.
[in] aLength Number of bytes to copy.
References OT_EXIT_FAILURE, OT_UNUSED_VARIABLE, sSettingsFd, and VerifyOrDie.
Referenced by otPlatSettingsAdd(), and platformSettingsDelete().
swapPersist()
static void swapPersist (otInstance * aInstance, int aFd) static
References getSettingsFileName(), kMaxFileNameSize, OT_EXIT_ERROR_ERRNO, sSettingsFd, and VerifyOrDie.
Referenced by otPlatSettingsAdd(), otPlatSettingsSet(), and platformSettingsDelete().
swapDiscard()
static void swapDiscard (otInstance * aInstance, int aFd) static
References getSettingsFileName(), kMaxFileNameSize, OT_EXIT_ERROR_ERRNO, and VerifyOrDie.
Referenced by platformSettingsDelete().
Variable Documentation
kMaxFileNameSize
const size_t kMaxFileNameSize = sizeof(OPENTHREAD_CONFIG_POSIX_SETTINGS_PATH) + 32 static
Referenced by otPlatSettingsInit(), swapDiscard(), swapOpen(), and swapPersist().
sSettingsFd
int sSettingsFd = -1 static
Referenced by otPlatSettingsAdd(), otPlatSettingsDeinit(), otPlatSettingsGet(), otPlatSettingsInit(), otPlatSettingsWipe(), platformSettingsDelete(), swapPersist(), and swapWrite().
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale