OpenThread: JoinerRouter::JoinerEntrustMetadata Struct Reference
JoinerRouter::JoinerEntrustMetadata Struct Reference
Public Member Functions
otError AppendTo (Message &aMessage)
void ReadFrom (const Message &aMessage)
Data Fields
Kek mKek
Ip6::MessageInfo mMessageInfo
TimeMilli mSendTime
Member Function Documentation
AppendTo()
otError AppendTo (Message & aMessage) inline
References Message::Append(), and JoinerRouter::JoinerEntrustMetadata::ReadFrom().
ReadFrom()
void ReadFrom (const Message & aMessage)
Referenced by JoinerRouter::JoinerEntrustMetadata::AppendTo().
Field Documentation
mMessageInfo
Ip6::MessageInfo mMessageInfo
mSendTime
TimeMilli mSendTime
mKek
Kek mKek
The documentation for this struct was generated from the following file:
joiner_router.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale