OpenThread: system.cpp File Reference
system.cpp File Reference
Detailed Description
This file includes the platform-specific initializers.
#include "openthread-posix-config.h"
#include "platform-posix.h"
#include <assert.h>
#include <openthread-core-config.h>
#include <openthread/tasklet.h>
#include <openthread/platform/alarm-milli.h>
#include <openthread/platform/radio.h>
Functions
void otSysDeinit (void)
otInstance * otSysInit (otPlatformConfig *aPlatformConfig)
int otSysMainloopPoll (otSysMainloopContext *aMainloop)
void otSysMainloopProcess (otInstance *aInstance, const otSysMainloopContext *aMainloop)
void otSysMainloopUpdate (otInstance *aInstance, otSysMainloopContext *aMainloop)
Variables
uint64_t gNodeId = 0
Function Documentation
otSysInit()
otInstance* otSysInit (otPlatformConfig * aPlatformConfig)
This function performs all platform-specific initialization of OpenThread's drivers.
Note
This function is not called by the OpenThread library. Instead, the system/RTOS should call this function when initialization of OpenThread's drivers is most appropriate.
Parameters
[in] aPlatformConfig Platform configuration structure.
Returns
A pointer to the OpenThread instance.
References otPlatformConfig::mInterfaceName, otPlatformConfig::mSpeedUpFactor, otInstanceInitSingle(), platformAlarmInit(), platformNetifInit(), platformRadioInit(), platformRandomInit(), platformUdpInit(), and virtualTimeInit().
Referenced by InitInstance().
otSysDeinit()
void otSysDeinit (void)
This function performs all platform-specific deinitialization for OpenThread's drivers.
Note
This function is not called by the OpenThread library. Instead, the system/RTOS should call this function when deinitialization of OpenThread's drivers is most appropriate.
References platformNetifDeinit(), platformRadioDeinit(), and virtualTimeDeinit().
Referenced by main(), and otPlatReset().
otSysMainloopUpdate()
void otSysMainloopUpdate (otInstance * aInstance, otSysMainloopContext * aMainloop)
This function updates the file descriptor sets with file descriptors used by OpenThread drivers.
Parameters
[in] aInstance The OpenThread instance structure.
[in,out] aMainloop A pointer to the mainloop context.
References otSysMainloopContext::mErrorFdSet, otSysMainloopContext::mMaxFd, otSysMainloopContext::mReadFdSet, otSysMainloopContext::mTimeout, otSysMainloopContext::mWriteFdSet, otTaskletsArePending(), platformAlarmUpdateTimeout(), platformNetifUpdateFdSet(), platformRadioUpdateFdSet(), platformUartUpdateFdSet(), platformUdpUpdateFdSet(), and virtualTimeUpdateFdSet().
Referenced by main().
otSysMainloopPoll()
int otSysMainloopPoll (otSysMainloopContext * aMainloop)
This function polls OpenThread's mainloop.
Parameters
[in,out] aMainloop A pointer to the mainloop context.
Returns
value returned from select().
References otSysMainloopContext::mErrorFdSet, otSysMainloopContext::mMaxFd, otSysMainloopContext::mReadFdSet, otSysMainloopContext::mTimeout, otSysMainloopContext::mWriteFdSet, and virtualTimeSendSleepEvent().
Referenced by main().
otSysMainloopProcess()
void otSysMainloopProcess (otInstance * aInstance, const otSysMainloopContext * aMainloop)
This function performs all platform-specific processing for OpenThread's example applications.
Note
This function is not called by the OpenThread library. Instead, the system/RTOS should call this function in the main loop when processing OpenThread's drivers is most appropriate.
Parameters
[in] aInstance The OpenThread instance structure.
[in] aMainloop A pointer to the mainloop context.
References otSysMainloopContext::mErrorFdSet, otSysMainloopContext::mReadFdSet, otSysMainloopContext::mWriteFdSet, platformAlarmProcess(), platformNetifProcess(), platformRadioProcess(), platformUartProcess(), platformUdpProcess(), and virtualTimeProcess().
Referenced by main().
Variable Documentation
gNodeId
uint64_t gNodeId = 0
Unique node ID.
Referenced by platformRandomInit().
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale