OpenThread: otIp6Address::OT_TOOL_PACKED_FIELD Union Reference
otIp6Address::OT_TOOL_PACKED_FIELD Union Reference
#include <ip6.h>
Data Fields
uint16_t m16 [OT_IP6_ADDRESS_SIZE/sizeof(uint16_t)]
16-bit fields
uint32_t m32 [OT_IP6_ADDRESS_SIZE/sizeof(uint32_t)]
32-bit fields
uint8_t m8 [OT_IP6_ADDRESS_SIZE]
8-bit fields
Field Documentation
m8
uint8_t m8[OT_IP6_ADDRESS_SIZE]
8-bit fields
Referenced by Address::Clear(), Lowpan::Compress(), Lowpan::CompressDestinationIid(), Lowpan::CompressMulticast(), Lowpan::CompressSourceIid(), Lowpan::ComputeIid(), Lowpan::DecompressBaseHeader(), LeaderBase::ExternalRouteLookup(), LeaderBase::FindNextMatchingPrefix(), Address::FromString(), Dhcp6Server::PrefixAgent::GetContextId(), Address::GetIid(), Address::GetScope(), Mle::HandleStateChanged(), Address::IsIidAnycastLocator(), Address::IsIidRoutingLocator(), Address::IsMulticast(), Address::IsReservedSubnetAnycast(), Mle::Mle(), Address::operator==(), Address::PrefixMatch(), Dataset::ProcessMeshLocalPrefix(), Dataset::ProcessMgmtSetCommand(), Mle::Restore(), IaAddress::SetAddress(), Address::SetIid(), Address::SetMulticastNetworkPrefix(), Address::SetPrefix(), Mle::Store(), Address::ToExtAddress(), Ip6::UpdateChecksum(), Leader::UpdateDomainPrefixConfig(), and Encoder::WriteIp6Address().
m16
uint16_t m16[OT_IP6_ADDRESS_SIZE/sizeof(uint16_t)]
16-bit fields
Referenced by Lowpan::DecompressBaseHeader(), Address::GetLocator(), Address::IsIidLocator(), Address::IsLinkLocal(), Address::IsReservedSubnetAnycast(), Mle::Mle(), Mpl::ProcessOption(), Address::SetIidToLocator(), Address::SetLocator(), and Address::ToString().
m32
uint32_t m32[OT_IP6_ADDRESS_SIZE/sizeof(uint32_t)]
32-bit fields
Referenced by Address::IsIidLocator(), Address::IsLoopback(), Address::IsReservedSubnetAnycast(), Address::IsSubnetRouterAnycast(), Address::IsUnspecified(), Address::SetIidToLocator(), and Address::SetToLinkLocalAddress().
The documentation for this union was generated from the following file:
include/openthread/ip6.h
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale