OpenThread: HeaderPoD::OT_TOOL_PACKED_FIELD Union Reference
HeaderPoD::OT_TOOL_PACKED_FIELD Union Reference
#include <ip6_headers.hpp>
Data Fields
uint16_t m16 [kVersionClassFlowSize/sizeof(uint16_t)]
uint32_t m32 [kVersionClassFlowSize/sizeof(uint32_t)]
uint8_t m8 [kVersionClassFlowSize/sizeof(uint8_t)]
Field Documentation
m8
uint8_t m8[kVersionClassFlowSize/sizeof(uint8_t)]
Referenced by Header::Init(), and Header::IsVersion6().
m16
uint16_t m16[kVersionClassFlowSize/sizeof(uint16_t)]
m32
uint32_t m32[kVersionClassFlowSize/sizeof(uint32_t)]
Referenced by Header::GetDscp(), Header::Init(), and Header::SetDscp().
The documentation for this union was generated from the following file:
ip6_headers.hpp
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale